### DISCUSSION TITLE
ECS queries port `8888` if ingress allows `8888`

### DISCUSSION THREAD

**Discussion by kapunakap** [qdm12/gluetun#1010] [Ideas]
### Is this urgent?

Yes

### Host OS

Amazon Linux 2 ECS-optimised

### CPU arch

aarch64

### VPN service provider

Private Internet Access

### What are you using to run the container

Other

### What is the version of Gluetun

latest in docker hub

### What's the problem 🤔

The container keeps restarting if ingress 8888 TCP isn't allowed in a security group.

If I allow 8888, it reaches a steady state. When I delete it, it stops working. All egress is allowed.

It works locally and on EC2 using `docker-compose up`.

### Share your logs

```log
service [OpenvpnClientEcsCdkStack-Service9571FDD8-81c1WQ5PpClR](https://us-east-1.console.aws.amazon.com/ecs/home?region=us-east-1#/clusters/OpenvpnClientEcsCdkStack-ClusterEB0386A7-bSi249yD6pD5/services/OpenvpnClientEcsCdkStack-Service9571FDD8-81c1WQ5PpClR) (instance i-0693254a4b6e23b91) (port 8888) is unhealthy in target-group [Openv-Servi-1FL0A3PFL27JU](https://us-east-1.console.aws.amazon.com/ec2/v2/home?region=us-east-1#TargetGroups:search=arn:aws:elasticloadbalancing:us-east-1:XXXXX:targetgroup/Openv-Servi-1FL0A3PFL27JU/154063a780656037) due to (reason Health checks failed)
```

### Share your configuration

```yml
My ENV vars are:


        VPN_SERVICE_PROVIDER: "private internet access",
        OPENVPN_USER: "XXX",
        OPENVPN_PASSWORD: 'XXX',
        SERVER_HOSTNAMES: 'XXX.privacy.network',
        HTTPPROXY: "on",
        HTTPPROXY_LOG: "on",
        HTTPPROXY_STEALTH: "on",
        DNS_KEEP_NAMESERVER: 'on',
        DOT: 'off'
```

(I had to change DNS configuration, otherwise it doesn't work in ECS.)
