### DISCUSSION TITLE
Can't Reach Gluetun Network From Lan Network

### DISCUSSION THREAD

**Discussion by basudip** [qdm12/gluetun#1060] [Q&A]
Hi, 
after finding out about Gluetun I was very excited when reading all the features. I am currently using OpenVPN using "trigus42/qbittorrentvpn". VPN working fine and I can connect other containers like Sonnarr/Radarr through it and can access Sonnarr/Radarr web UI. 

But when I used Gluetun I could not access the Gluetun network from lan network. I set the environment variable FIREWALL_OUTBOUND_SUBNETS. but nothing solved. The Network mode I am using is macvlan. Every container has there own IP address.  I tried to disable the Firewall also with no success. One thing I notice that if I ping the Gluetun container from my PC while restarting, only a couple of times I get a response. After that, something kicks in and I can't reach it. 

since my other openvpn container from other developer working fine on my setting, there must be some configuration mistake I am making.

**Comment by qdm12** [comment]
> But when I used Gluetun I could not access the Gluetun network from lan network.

What do you mean by that? Are you trying for example to access the web ui port of a connected container like Sonarrr? Did you publish ports on Gluetun?

Also it would help if you can share your config (omit credentials)

**Reply by basudip** [reply]
> What do you mean by that? Are you trying for example to access the web ui port of a connected container like Sonarrr? Did you publish ports on Gluetun?

Sorry I was trying to write "But when I try to ping Gluetun I could not access the Gluetun network from lan network."
I am using macvlan so dont need to open ports and yes I am trying to access Sonarr/Jacket web-ui from my lan PC.

here is my v3 compose file. This is auto generated using "docker-autocompose". So that's why its long. I use portainer to deploy the image initially. 
Device:-ARM V7 Raspberrypi
Network Mode: MACVLAN

```yml
version: "3"
services:
  Gluetun-VPN:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - AUDIT_CONTROL
      - BLOCK_SUSPEND
      - DAC_READ_SEARCH
      - IPC_LOCK
      - IPC_OWNER
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - NET_BROADCAST
      - SYSLOG
      - SYS_ADMIN
      - SYS_BOOT
      - SYS_MODULE
      - SYS_NICE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_TTY_CONFIG
      - WAKE_ALARM
    container_name: Gluetun-VPN
    devices:
      - /dev/net/tun:/dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
    entrypoint:
      - /gluetun-entrypoint
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=xxxxxxxxxxxx
      - OPENVPN_PASSWORD=xxxxxxxxxxxxxxxxxx
      - SERVER_COUNTRIES=Netherlands
      - FREE_ONLY=
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - VPN_TYPE=openvpn
      - VPN_ENDPOINT_IP=
      - VPN_ENDPOINT_PORT=
      - VPN_INTERFACE=tun0
      - OPENVPN_PROTOCOL=udp
      - OPENVPN_USER_SECRETFILE=/run/secrets/openvpn_user
      - OPENVPN_PASSWORD_SECRETFILE=/run/secrets/openvpn_password
      - OPENVPN_VERSION=2.5
      - OPENVPN_VERBOSITY=1
      - OPENVPN_FLAGS=
      - OPENVPN_CIPHERS=
      - OPENVPN_AUTH=
      - OPENVPN_PROCESS_USER=
      - OPENVPN_IPV6=off
      - OPENVPN_CUSTOM_CONFIG=
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_PRESHARED_KEY=
      - WIREGUARD_PUBLIC_KEY=
      - WIREGUARD_ADDRESSES=
      - SERVER_REGIONS=
      - SERVER_CITIES=
      - SERVER_HOSTNAMES=
      - ISP=
      - OWNED_ONLY=no
      - PRIVATE_INTERNET_ACCESS_OPENVPN_ENCRYPTION_PRESET=
      - PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING=off
      - PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING_STATUS_FILE=/tmp/gluetun/forwarded_port
      - OPENVPN_CLIENTCRT_SECRETFILE=/run/secrets/openvpn_clientcrt
      - OPENVPN_CLIENTKEY_SECRETFILE=/run/secrets/openvpn_clientkey
      - SERVER_NUMBER=
      - SERVER_NAMES=
      - MULTIHOP_ONLY=
      - FIREWALL=off
      - FIREWALL_VPN_INPUT_PORTS=
      - FIREWALL_INPUT_PORTS=
      - FIREWALL_DEBUG=off
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - HEALTH_TARGET_ADDRESS=cloudflare.com:443
      - HEALTH_VPN_DURATION_INITIAL=6s
      - HEALTH_VPN_DURATION_ADDITION=5s
      - DOT=off
      - DOT_PROVIDERS=cloudflare
      - DOT_PRIVATE_ADDRESS=127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16,::1/128,fc00::/7,fe80::/10,::ffff:7f00:1/104,::ffff:a00:0/104,::ffff:a9fe:0/112,::ffff:ac10:0/108,::ffff:c0a8:0/112
      - DOT_VERBOSITY=1
      - DOT_VERBOSITY_DETAILS=0
      - DOT_VALIDATION_LOGLEVEL=0
      - DOT_CACHING=on
      - DOT_IPV6=off
      - BLOCK_MALICIOUS=on
      - BLOCK_SURVEILLANCE=off
      - BLOCK_ADS=off
      - UNBLOCK=
      - DNS_UPDATE_PERIOD=24h
      - DNS_ADDRESS=127.0.0.1
      - DNS_KEEP_NAMESERVER=on
      - HTTPPROXY=on
      - HTTPPROXY_LOG=off
      - HTTPPROXY_LISTENING_ADDRESS=:8888
      - HTTPPROXY_USER=
      - HTTPPROXY_PASSWORD=
      - HTTPPROXY_USER_SECRETFILE=/run/secrets/httpproxy_user
      - HTTPPROXY_PASSWORD_SECRETFILE=/run/secrets/httpproxy_password
      - SHADOWSOCKS=off
      - SHADOWSOCKS_LOG=off
      - SHADOWSOCKS_LISTENING_ADDRESS=:8388
      - SHADOWSOCKS_PASSWORD=
      - SHADOWSOCKS_PASSWORD_SECRETFILE=/run/secrets/shadowsocks_password
      - SHADOWSOCKS_CIPHER=chacha20-ietf-poly1305
      - HTTP_CONTROL_SERVER_ADDRESS=:8000
      - UPDATER_PERIOD=0
      - UPDATER_MIN_RATIO=0.8
      - UPDATER_VPN_SERVICE_PROVIDERS=
      - PUBLICIP_FILE=/tmp/gluetun/ip
      - PUBLICIP_PERIOD=12h
      - PPROF_ENABLED=no
      - PPROF_BLOCK_PROFILE_RATE=0
      - PPROF_MUTEX_PROFILE_RATE=0
      - PPROF_HTTP_SERVER_ADDRESS=:6060
      - VERSION_INFORMATION=on
      - TZ=
      - PUID=
      - PGID=
    expose:
      - 8000/tcp
      - 8388/tcp
      - 8388/udp
      - 8888/tcp
    hostname: Gluetun
    image: qmcgaw/gluetun:latest
    ipc: private
    labels:
      org.opencontainers.image.authors: quentin.mcgaw@gmail.com
      org.opencontainers.image.created: '2022-07-04T00:42:53.696Z'
      org.opencontainers.image.description: 'VPN client in a thin Docker container
        for multiple VPN providers, written in Go, and using OpenVPN or Wireguard,
        DNS over TLS, with a few proxy servers built-in.'
      org.opencontainers.image.documentation: https://github.com/qdm12/gluetun
      org.opencontainers.image.licenses: MIT
      org.opencontainers.image.revision: a4c80b3045e65afbf86de44c89ad18deca51a43f
      org.opencontainers.image.source: https://github.com/qdm12/gluetun
      org.opencontainers.image.title: gluetun
      org.opencontainers.image.url: https://github.com/qdm12/gluetun
      org.opencontainers.image.version: latest
    logging:
      driver: json-file
      options: {}
    networks:
      - alt_net
    volumes:
      - /srv/dev-disk-by-label-RaspiBackup/Docker/Gluetun-VPN:/gluetun
networks:
  alt_net:
    external: true
    name: alt_net
```
