### DISCUSSION TITLE
Multiple torrent containers through one gluetun with docker compose?

### DISCUSSION THREAD

**Discussion by jogaman** [qdm12/gluetun#1084] [Ideas]
Hi there,
I have this docker compose file that works excellent with qbtorrent and mullvad (below)

But, how would i add another qbtorrent container to this without port conflicts? If I was to have a bunch of different containers (with various conflicting ports) connected through one single gluetun container, is that possible somehow?

Maybe more of a docker question than gluetun, but hoping someone here would know.

```yaml

version: "2.1"
services:
   gluetun:
      image: qmcgaw/gluetun
      container_name: gluetun
      cap_add: 
        - NET_ADMIN
      devices: 
        - "/dev/net/tun:/dev/net/tun"
      environment: 
        - VPN_SERVICE_PROVIDER=mullvad
        - VPN_TYPE=wireguard
        - OPENVPN_USER=
        - OPENVPN_PASSWORD=
        - WIREGUARD_PRIVATE_KEY=xxx
        - WIREGUARD_ADDRESSES=10.xx.xx.xx/32
        - SERVER_CITIES=Amsterdam
        - TZ=Amsterdam
        - HTTPPROXY=on
        - HTTPPROXY_USER=xx
        - HTTPPROXY_PASSWORD=xx
      ports: 
        - "8888:8888/tcp"
        - "8388:8388/tcp"
        - "8388:8388/udp"
        - 8080:8080 	#qb
        - 6881:6881		#qb
        - 6881:6881/udp	#qb
      
      volumes: 
        - "/data/gluetun:/gluetun"
        
   qbittorrent:
      image: lscr.io/linuxserver/qbittorrent:latest
      container_name: qbittorrent
      environment:
       - PUID=1000
       - PGID=1000
       - TZ=Europe/London
       - WEBUI_PORT=8080
      volumes:
       - /data/qbtorrent/config:/config
       - /mnt/video/qb/downloads:/downloads
      restart: unless-stopped
        
      network_mode: 'service:gluetun'

```
