### DISCUSSION TITLE
Running a wireguard server through gluetun

### DISCUSSION THREAD

**Discussion by Subbeh** [qdm12/gluetun#1092] [Q&A]
Is it possible to run a wireguard server container and point it to the gluetun container?

I want to be able to connect to my home network using the wireguard server, and still have the protection of the wireguard client through gluetun for internet access.

I've tried setting this up as follows (ansible format), but it's not working when I try to connect to 103.231.88.30:54915 with my wireguard client. I mapped the port through Mullvad, and can confim it's working by running the port-checker script. Am I missing something here?

```
container_gluetun:
  <<: *core
  name: "gluetun"
  image: "qmcgaw/gluetun"
  capabilities:
    - net_admin
  ports:
    - "8888:8888"
  volumes:
    "{{ app_data }}/gluetun:/gluetun"
  env:
    "VPN_SERVICE_PROVIDER": "mullvad"
    "VPN_TYPE": "wireguard"
    "VPN_ENDPOINT_PORT": "51820"
    "WIREGUARD_PRIVATE_KEY": "{{ wireguard_privkey }}"
    "WIREGUARD_ADDRESSES": "{{ wireguard_addr }}"
    "SERVER_CITIES": "Melbourne"
    "HTTPPROXY": "on"
    "HTTPPROXY_LOG": "on"
    "FIREWALL_VPN_INPUT_PORTS": "54915"

container_wireguard:
  # <<: *def
  name: "wireguard"
  image: "linuxserver/wireguard"
  network_mode: "container:gluetun"
  privileged: yes
  sysctls:
    "net.ipv4.conf.all.src_valid_mark": "1"
  capabilities:
    - net_admin
    - sys_module
  env:
    "SERVERURL": "103.231.88.30"
    "SERVERPORT": "54915"
    "PEERS": "1"
    "INTERNAL_SUBNET": "10.13.13.0"
    "ALLOWEDIPS": "0.0.0.0/0"
    "LOG_CONFS": "TRUE"
  volumes:
    - "{{ app_data }}/wireguard/config:/config"
    - "/lib/modules:/lib/modules"
```
