### DISCUSSION TITLE
Wireguard on ProtonVPN

### DISCUSSION THREAD

**Discussion by pvanryn** [qdm12/gluetun#1105] [Ideas]
This may be common knowledge, but I did not see any posts about it.

ProtonVPN subscribers can now run Wireguard in their gluetun container. I noticed the other day that Proton is providing a Linux wireguard client now, and after a bit of reading, I spun up a container with it.  I have not been using it for long, but it seems to be very stable and fast.

Go to the [ProtonVPN](https://account.proton.me/u/0/vpn/WireGuard) page and create your configuration, name it, and then download it into the directory where you intend to create your VPN container. Then, go to [Quentin's custom provider page for Wireguard](https://github.com/qdm12/gluetun/wiki/Custom-provider), and copy his template. Fill in all of the particulars as required from the configuration file that you downloaded. Mine looks like this:

```
version: '3.7'
services:
   protonvpn:
     image: qmcgaw/gluetun:latest
     container_name: protonvpn
     cap_add:
       - NET_ADMIN
     network_mode: bridge
     ports:
       - 8000:8000 # HTTP Control Server
       - 8888:8888/tcp # HTTP Proxy
     volumes:
       - ./protonvpn:/gluetun
       - ./myProtonVPN.conf:/gluetun/config.conf:ro
     environment:
       - VPN_SERVICE_PROVIDER=custom
       - VPN_TYPE=wireguard
       - VPN_ENDPOINT_IP=92.17.63.9
       - VPN_ENDPOINT_PORT=51820
       - WIREGUARD_PUBLIC_KEY=MyVeryPublicKey
       - WIREGUARD_PRIVATE_KEY=MyVeryPrivateKey
       - WIREGUARD_ADDRESSES=10.2.0.2/24
       - HTTPPROXY=on
       - HTTPPROXY_USER=
       - HTTPPROXY_PASSWORD=
       - HTTPPROXY_STEALTH=off
```
Thanks to Quentin for his hard work.

**Comment by qdm12** [comment]
Awesome! Does your private key and address stay the same for all their servers? I'm asking since if this is the case (like mullvad, ivpn) I can add native support for it. Otherwise you're better off using the custom provider as you did.

**Comment by pvanryn** [comment]
Unfortunately, the private and public keys change for each generated configuration, so it looks like custom .conf only for now.

I used your speed test to do a very casual comparison of wireguard with openvpn. It is not possible to do an apples to apples comparison, because I can't connect both to the same server, but if I connect to servers in the same city, wireguard is significantly faster.  I want to check  them over a longer period of time.

**Reply by qdm12** [reply]
Nice, are you running on a low power device perhaps?

I'll document that on the protonvpn page then!

**Comment by pvanryn** [comment]
I have a Ryzen 3 with plenty of memory.

The protonvpn config generator looks like this:
![protonconf](https://user-images.githubusercontent.com/1633790/185620106-66676d6a-1a89-4b01-ba0e-7e447bb843ca.png)

With wireguard, do all of the options (like VPN Accelerator) work natively, or do they need to be configured in the docker-compose environment?

**Reply by qdm12** [reply]
I have been trying to understand how their vpn accelerator works and what it is, but it's still unclear. It might be something they did on the server side.
What difference do you see in the config generated?
If it is just a different ip address endpoint, yes it will work in Gluetun (since Wireguard is wireguard really 😉).

**Comment by pvanryn** [comment]
The configuration files for accelerated and non-accelerated are _exactly_ the same, except the private keys are different. For whatever it's worth, the VPN accelerator is on by default, you have to switch it off if you don't want it.

I tested from inside the container so that I could pick the same speedtest server each time, and my docker configurations were the same, except for name and port assignments. The accelerated containers are significantly faster for downloading, less so for upload speeds. 

I did several tests, but here is a sample of my results.

Test 1 | Accelerated | Non-Accelerated |
---| --- | ---|
`Down` | `526.40` | `420.62`
`Up` | `35.11` | `13.86`
---| --- | ---|
Test 2 | Accelerated | Non-Accelerated |
`Down` | `374.86` | `326.40`
`Up` | `20.86` | `25.74`
---| --- | ---|
Test 3 | Accelerated | Non-Accelerated |
`Down` | `313.93` | `119.21`
`Up` | `28.31` | `27.37`

**Reply by qdm12** [reply]
Ok it should work too if it's just the private key changing. I guess it's a fully server side optimization, although I don't see why they don't just enable it everywhere and allow the user to disable it, seems rather odd 🤔

**Comment by evanrich** [comment]
2 years late to the party, just foudn this out.   two questions if anyone sees this:

1.) Is port forwarding required?  I'm using https://bjw-s.github.io/helm-charts/docs/app-template/examples/qbittorrent-gluetun/  as a start, but with the wireguard config, and I'm not sure if the portforwarding is required with wireguard

2.) how can you test that everything works?  I see that a proton vpn ip shows up, but QBT shows that its firewalled and I don't seem to connect to any peers

**Reply by blakedaniel** [reply]
> 2.) how can you test that everything works? I see that a proton vpn ip shows up, but QBT shows that its firewalled and I don't seem to connect to any peers

1. when Gluetun runs, check the logs for the `port forwarding`port using `docker compose logs <name-of-gluetun-container>` - let's say that the port forward port is `6888`
2. configure qbittorrent with port `6888` by adding `TORRENTING_PORT=6888` to env variables in qbittorrent
3. For added security click on `Advanced` in the `settings` panel, and select `tun0` under the `Network Interface` drop down (optional)

**Reply by qdm12** [reply]
DO NOT do this. That means traffic will come from the Internet to your public IP address directly, without the VPN, and that for torrenting traffic. You really don't want to do that. Please think twice!

Just do step 1 and then configure qbitorrent to use that port, that's it. It's automatically forwarded by the VPN server and allowed through the gluetun firewall and routing.

**Reply by blakedaniel** [reply]
@qdm12 - thank you for correcting me with this. You saved me some headache and some bad advice I got.

**Comment by nebb00** [comment]
https://news.itsfoss.com/protonvpn-wireguard-linux/

Does this help better support,?

**Comment by kingscott** [comment]
Just coming back to say thank you @pvanryn for providing your config for ProtonVPN + Wireguard. I was struggling getting this work, and I really appreciate it seeing a fresh example with a "custom" wireguard config. 🙌

**Comment by rmcgirr83** [comment]
If anyone else stumbles across this topic, here is my vpn stack that I use in portainer in a synology nas. It populates the forwarded port in gluetun to qbit without having to set it manually. You must within qbit settings in the webui section do this

![Screenshot from 2025-05-17 09-25-00](https://github.com/user-attachments/assets/817793aa-76b7-4a03-9b8b-3dc68b424f65)

based on these settings from below
`FIREWALL_OUTBOUND_SUBNETS=172.17.0.0/16,192.168.1.0/24`

and here ya g0
```
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080 # qbittorrent Web UI
      - 8888:8888/tcp #HTTP proxy
      - 8388:8388/tcp #shadowsocks
      - 8388:8388/udp #shadowsocks
    volumes:
      - /volume1/docker/gluetun:/gluetun
      - /lib/modules:/lib/modules:ro #this is for wireguard module that I have installed on the NAS
    environment:
      - PUID=${PUID} #CHANGE_TO_YOUR_UID
      - PGID=${PGID} #CHANGE_TO_YOUR_GID
      - TZ=${TZ} #CHANGE_TO_YOUR_TZ
      - HEALTH_TARGET_ADDRESS=1.1.1.1:443
      - UPDATER_PERIOD=24h
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - PORT_FORWARD_ONLY=on
      - WIREGUARD_PRIVATE_KEY=your-private-key-here# "PrivateKey" under [Interface] in WG Config - only shown on config creation
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'# automatically sets forwarded port to qbit NOTE the port used for qbit which is 8080 in my setup
      - SERVER_COUNTRIES=United States # what country do you want to use
      - SERVER_CITIES=New York #can specify city
      - VPN_PORT_FORWARDING=on
      - FIREWALL_OUTBOUND_SUBNETS=172.17.0.0/16,192.168.1.0/24 #change this in line with your subnet see note on guide.
    security_opt:
      - no-new-privileges:true
    network_mode: bridge
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022
      - WEBUI_PORT=8080
      - VPN_ENABLED=true
    logging:
      driver: json-file
      options:
        max-file: 10
        max-size: 200
    volumes:
      - /volume1/docker/qbittorrent:/config
      - /volume1/media/torrents/:/media/torrents
    network_mode: container:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    security_opt:
      - no-new-privileges:true
```
