### DISCUSSION TITLE
Unable to connect to Proxy Server

### DISCUSSION THREAD

**Discussion by WINOFFRG** [qdm12/gluetun#1112] [Q&A] [answered]
Hello!

I have been able to start my Docker Container properly with **Wireguard Custom Config** as shown below:

```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /data:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=REDACTED
      - WIREGUARD_ADDRESSES=172.16.0.2/32
      - WIREGUARD_PUBLIC_KEY=REDACTED
      - VPN_ENDPOINT_IP=162.159.192.1
      - VPN_ENDPOINT_PORT=2408
```

I tried to connect to this proxy server from NodeJS Axios as well as Windows Proxy Options from 
Host = `127.0.0.1`
Port = `8888 / 8388`

When I opened up anything in browser, I got ERR_EMPTY_RESPONSE
and in my NodeJS the connection just hung up, As shown below in the image.

This container is running on my VPS and my NodeJS app is also running on the same server. I tried connecting to it via Port Forwarding through Windows.

![image](https://user-images.githubusercontent.com/61311751/185764116-c65bd468-8185-445a-b776-402687157dce.png)

Kindly help if there is something where I am missing it.
