### DISCUSSION TITLE
Own Custom VPN Server - docker-compose.yml incomplete

### DISCUSSION THREAD

**Discussion by Grey-Cookie** [qdm12/gluetun#1125] [Q&A] [answered]
Hei you all

I'm in aaaw for this awesome docker image and definitely want to use this one and no other, but having trouble setting up the yml correctly..
I'm getting following Error in the logs:

```
2022-08-28T15:11:56+02:00 INFO [routing] default route found: interface eth0, gateway 172.22.0.1 and assigned IP 172.22.0.2
2022-08-28T15:11:56+02:00 INFO [routing] local ethernet link found: eth0
2022-08-28T15:11:56+02:00 INFO [routing] local ipnet found: 172.22.0.0/16
2022-08-28T15:11:56+02:00 INFO [firewall] enabling...
2022-08-28T15:11:56+02:00 INFO [firewall] enabled successfully
2022-08-28T15:12:01+02:00 INFO [storage] merging by most recent 11432 hardcoded servers and 11432 servers read from /gluetun/servers.json
2022-08-28T15:12:02+02:00 ERROR VPN settings: OpenVPN settings: custom configuration file: filepath is missing
2022-08-28T15:12:02+02:00 INFO Shutdown successful
```

I currently don't understand if the issue is in the docker-compose file or the vpn.conf file
The server itself is working. I'm using it with laptop and phones with the OpenVPN client app.
Its running on a rented VPS.

I tried the docker-compose.yml in all sorts of variations of the one in the wiki, created a volume and put the .conf file there, bind the file in my home directory...
I'm betting I'm missing something obvious or it has to do with the way I try to define the volume..
Also tried exec into the container to look at the mounted file, if its correct but since the container stops all the time that won't work..

```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https:$
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /homes/jayadmin/gluetun-vpn_client/RPI4.conf:/gluetun/config.conf:ro
      #- /var/lib/run/docker/volumes/gluetun-vol/:gluetun/
      #- /var/lib/run/docker/voluems/gluetun-vol/RPI4.conf:gluetun/config.conf:ro
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      # - WIREGUARD_ADDRESSES=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=Europe/Berlin
```

[myown.conf.pdf](https://github.com/qdm12/gluetun/files/9439753/myown.conf.pdf)

I'll appreciate any hint and dig into it!
