### DISCUSSION TITLE
Cant get gluetun connected container to connect to non gluetun container

### DISCUSSION THREAD

**Discussion by zarskie** [qdm12/gluetun#1154] [Q&A]
```yml
version: '3.7'

networks:
  default:
    name: dockernet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24           

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
    - VPN_SERVICE_PROVIDER=mullvad
    - VPN_TYPE=wireguard
    - WIREGUARD_PRIVATE_KEY=xxx
    - WIREGUARD_ADDRESSES=xxx
    - SERVER_CITIES=xxx
    - FIREWALL_VPN_INPUT_PORTS=xxx
    - TZ=Canada/Pacific 
    restart: unless-stopped
    ports:
      - 8080:8080
      - 3000:3000
  
  qflood:
    image: hotio/qflood:release-4.4.3.1--4.7.0
    container_name: qflood
    network_mode: "service:gluetun"    
  
  container B:
    networks:
      default:
        ipv4_address: 172.19.0.111
```

Trying to run external program on torrent completion:
`curl -XPOST http://172.19.0.111:2468/api/webhook --data-urlencode "name=%N"`

Getting:
`curl: (28) Failed to connect to 172.19.0.111 port 2468 after 133999 ms: Operation timed out`

```
docker inspect gluetun -f "{{json .NetworkSettings.Networks }}"
{"dockernet":{"IPAMConfig":{"IPv4Address":"172.19.0.11"}

docker inspect container b -f "{{json .NetworkSettings.Networks }}"
{"dockernet":{"IPAMConfig":{"IPv4Address":"172.19.0.111"}
```
