### DISCUSSION TITLE
/dev/net/tun error - Proxmox LXC Docker

### DISCUSSION THREAD

**Discussion by chop249** [qdm12/gluetun#1163] [Q&A]
Trying to get this up and running in a ProxMox LXC using Docker. I've tried Deb 11 both in privileged and unprivileged LXCs. I keep running into errors with the /dev/net/tun. Here is my docker-compose.yml:

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-contain>
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /docker/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=vpn unlimited
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=<USER>
      - OPENVPN_PASSWORD=<PASSWD>
      - SERVER_COUNTRIES=Canada,France,Romania
      - SERVER_CITIES=Ontario,Paris
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      # - WIREGUARD_ADDRESSES=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=America/Chicago
 ```

And the error:
ERROR: for gluetun  Cannot start service gluetun: error gathering device information while adding custom device "/dev/net/tun": no such file or directory
I've tried the suggestions in Github without a solution. The end result I'm looking for too is for separate LXC's also containing docker to be able to connect through this VPN service. I know that doesn't have anything to do with this error but maybe that will make a difference with my initial setup?
