### DISCUSSION TITLE
Mullvad wireguard freezing

### DISCUSSION THREAD

**Discussion by ForestHorns** [qdm12/gluetun#1167] [Q&A] [answered]
Im having issues setting up wireguard with Mullvad. It seems to get the ip just fine then the entire container freezes? Im new to docker/self host so I have no idea whats going on.

Fresh install of omv6
The compose file im using is :

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY= XXXX
      - WIREGUARD_ADDRESSES=10.xx/32
      - SERVER_CITIES=stockholm,gothenburg,amsterdam,oslo,zurich
      #- SERVER_HOSTNAMES=se13-wireguard,se14-wireguard,se26-wireguard,se28-wireguard,se2-wireguard,se6-wireguard,se7-wireguard,se8-wireguard
      - OWNED_ONLY=yes
      # Timezone for accurate log times
      - TZ=America/Chicago
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
 ```
   
[_vpn-gluetun-1_logs.txt](https://github.com/qdm12/gluetun/files/9641742/_vpn-gluetun-1_logs.txt)
I've attatched logs.

Things I've tried: changing to openvpn mode, running it as a container, changing the citys, changing the settings pre-conf with mullvad. I also tried connecting via wireguard on another machine and it seemed to work.
