### DISCUSSION TITLE
Perfect-Privacy and Port-Management/-Forwarding

### DISCUSSION THREAD

**Discussion by olvier** [qdm12/gluetun#1182] [Q&A] [answered]
Hi,

i'm try to troubleshooting my problem with connection to perfect-privacy.
I'm using gluetun in docker with standard "docker run" from the wiki here.
Everything is fine, gluetun obtains an ip-address and it seems to be everything fine.

I'm using vpn for linux-image sharing via torrent.
Also at the trackers and [torrent-checker](https://ipleak.net/) is shown the right IP and Port.

But with those [port-checkers](https://dnschecker.org/port-scanner.php) from the web, the ports are "all" closed.
At the trackers I'm not connectable, too.
Of course, I just need one port, but i tried those 3 ports from the port-calculator and i also tried a pre-defined port.
Non of them are open. I don't have any further idea, where to look for an error.

Somebody has an idea, hint or experience?

System:
Synology NAS, newest gluetun image.

**Comment by bnhf** [comment]
@olvier 

Have you logged into your account at Perfect-Privacy to setup an open port?

Have you configured gluetun to open that same port through its firewall?

Have you mapped that port in your container stack?

The gluetun wiki covers this topic:
https://github.com/qdm12/gluetun/wiki/VPN-server-port-forwarding

**Reply by olvier** [reply]
> @olvier
> 
> Have you logged into your account at Perfect-Privacy to setup an open port?
> 

Yeah. I did both. The last year I worked totally noiseless (with another container) with those self-calculated ports by the internal container-IP ( `ifconfig tun0` ) and a script, which tells qbit the right port.
For error-potential-reduction I now the created a "static" port in the web-gui. ll are staying `closed`


> Have you configured gluetun to open that same port through its firewall?
> 

Puh. How do I do that? I mean, the port is calculated AFTER the containter starts, because its calculated by the IP, which is obtained while create connection. I just forwarded the static ports for qbit-web-gui. I never used to forward other ports. Maybe because of `--cap-add=NET_ADMIN`?


> Have you mapped that port in your container stack?
> 
> The gluetun wiki covers this topic: https://github.com/qdm12/gluetun/wiki/VPN-server-port-forwarding

Same as above, but i will read about it. I never stumbled about that before.

**Comment by bnhf** [comment]
@olvier 

As it says in the wiki, each VPN provider has their own method of opening a port. In the case of AirVPN, which I use, that port is valid across all of their servers (though I only use their servers from one country). Their built-in port checker will test a number of servers, but will only show as open for the server I'm connected to at that time.

**Comment by olvier** [comment]
> "Getting VPN port forwarding set up when using containers can be a pain since the port number is dynamic. This plugin automatically updates the incoming port for Deluge based on the current forwarded port." [SOURCE](https://github.com/qdm12/gluetun/wiki/VPN-server-port-forwarding#deluge) linked [TO](https://github.com/jawilson/deluge-piaportplugin)

I guess, this is a problem I already solved a year before. In perfect-privacy, the port is calculated in dependency of the internal vpn-ip. The calculated port I "send" to qbittorrent, what worked very well, the whole last year.

As mentioned, also the tracker sees the right IP and port where I am sharing from. But the ports are all closed. I never had any troubles with forwarding of ports.

Do I need this? Its in the Deluge Tutorial.
<img width="452" alt="image" src="https://user-images.githubusercontent.com/13106409/193475857-b42b88cf-4914-4cdc-bc50-d7a87d3ba2f6.png">

But my setup is dead simple. Its from the wiki and I just added the city and the ports for the qbit-webgui.
<img width="373" alt="image" src="https://user-images.githubusercontent.com/13106409/193475908-49e943f6-a3fe-48b5-8a85-2d057b1313e5.png">

**Comment by bnhf** [comment]
@olvier

So I spun-up a qBittorrent container to take a look at the setup, and it actually seems quite similar to Deluge.

The Linuxserver.io Docker image has a recommended docker-compose that looks like this:
```
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8080
    volumes:
      - /path/to/appdata/config:/config
      - /path/to/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
```
Looking at the ports, 8080 would be the WebUI, and 6881 and 6881/udp would be the listening ports (though these can be changed).

And within qBittorent, you can see that same listening port set, with the option to generate a new random one:
![Screenshot 2022-10-03 085100](https://user-images.githubusercontent.com/41088895/193608008-9dd30265-b78d-4740-8630-41f482bb0889.png)
So adapting this to a gluetun setup where qBittorrent would use the VPN exclusively, you'd be using a docker-compose like this:
```
version: "3"
services:
    gluetun:
        image: qmcgaw/gluetun:latest
        container_name: gluetun
        cap_add:
            - NET_ADMIN
        ports:
            - 8080:8080 # qBittorrent webui
            - 6881:6881 # qBittorrent listening port
            - 6881:6881/udp # qBittorrent listening port/udp
        environment:
            - VPN_SERVICE_PROVIDER=perfect privacy
            - OPENVPN_USER=abc
            - OPENVPN_PASSWORD=abc
            - OPENVPN_CITIES=Amsterdam
            - FIREWALL_VPN_INPUT_PORTS=6881
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Amsterdam
        volumes:
            - /data/openvpn:/gluetun
 
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Amsterdam
            - DELUGE_LOGLEVEL=error
        volumes:
            - /data/qbittorrent:/config # Change to your desired config directory mapping
            - ~/Downloads/complete:/downloads # Change to your desired download data directory
        network_mode: 'service:gluetun'
        depends_on:
            - gluetun
```
With the above setup, you can either open a port through your VPN provider or not. Both should work -- though there should be some performance advantage to configuring an open port through your provider's setup pages. They'll likely assign you a different port than 6881, in which case you'll need to update the port # in your docker-compose and in your qBittorrent interface.
