### DISCUSSION TITLE
Gluetun + Wg-easy container

### DISCUSSION THREAD

**Discussion by maodelg** [qdm12/gluetun#1192] [Q&A]
Hi! I would love some help from the community to get this working...

- I use a VPN Unlimited subscription with Gluetun, and it is working flawlessly, Gluetun container configuration is ok and tested.
- I also have a WG-Easy (Wireguard server container) configured, tested, and working.
- I want to have the wg-easy container to access the internet using the Gluetun network, so all my devices connected over my own VPN can benefit from the VPN Unlimited connection... this is to circumvent the hard limit of clients (5 total) that VPN Unlimited provides. In theory, I could connect any amount of devices using this method...
- After moving the open ports from the wg-easy container to the glutun one, and properly launching both, I just can't connect to the internet... No error, just can't browse the web or ping google from the GW-Easy clients...

Has anyone successfully recreated this use case? The idea is to have an unlimited amount of VPN clients using 1 slot of the paid VPN service by routing all of them over Gluetun using another custom VPN server container.

The WG-Easy server detects the client connection (see screenshot), but the client can't browse the internet... So the VPN connection between the CLIENT and WG-Easy server is being established trough the GLUETUN container, it's just like is not resolving DNS or something like that...

<img width="796" alt="image" src="https://user-images.githubusercontent.com/73360536/195480946-9df9afd2-0e8f-4d38-af21-819e6108d9be.png">

Thoughts? 
Thanks!

**Comment by bnhf** [comment]
@maodelg 

I think this is going to be difficult to do using a container like Wg-easy, as it has both cap_add and sysctls in the docker-compose.  This means that the container has special capabilities to access the host that normal containers don't, and in this case means that Wg-easy would be going directly to the host at times when you want it to do everything through Gluetun.

What you are trying to do can likely be done, but I think you'll find that most VPN containers need at least a cap_add of NET_ADMIN to function, which will make it very tricky (probably impossible) to do using two containers.

I'd recommend doing this at the router level, using an x86 platform (industrial PCs with multiple ethernet ports work well), and running OpenWRT or pfSense as the RouterOS.  I'm most familiar with OpenWRT, and with that you'd be able setup a WireGuard server, and VPN client (running OpenVPN or WireGuard), and have the Wireguard server use the VPN client for its outbound connection.  The advantage of this approach, using a relatively powerful router device, is that it keeps the traffic off of your LAN if you have a large number of incoming Wireguard clients.

**Comment by nedix** [comment]
I gave this a shot using a shadowsocks proxy.

<details>
  <summary>compose.yml</summary>

  ```yaml
  services:
    client:
      image: qmcgaw/gluetun:v3.39.0
      cap_add:
        - NET_ADMIN
      sysctls:
        - net.ipv4.ip_forward=1
        - net.ipv6.conf.all.disable_ipv6=0
      environment:
        VPN_SERVICE_PROVIDER: ${WIREGUARD_CLIENT_SERVICE_PROVIDER}
        VPN_TYPE: wireguard
        WIREGUARD_MTU: 1296
        WIREGUARD_PRIVATE_KEY: ${WIREGUARD_CLIENT_PRIVATE_KEY}
        WIREGUARD_ADDRESSES: ${WIREGUARD_CLIENT_ADDRESSES}
        SERVER_COUNTRIES: ${WIREGUARD_CLIENT_COUNTRIES}
        SHADOWSOCKS: on
        SHADOWSOCKS_PASSWORD: "${SHADOWSOCKS_PASSWORD:-secret}"
        SHADOWSOCKS_CIPHER: aes-128-gcm
      restart: unless-stopped
  
    proxy:
      image: ghcr.io/shadowsocks/sslocal-rust:v1.20.4
      cap_add:
        - NET_ADMIN
      devices:
        - /dev/net/tun:/dev/net/tun
      entrypoint:
        - /bin/sh
        - -ec
        - >
          wget -qO- "https://gist.githubusercontent.com/nedix/27f291577b03ced31076b3e093b604d2/raw/e2ea27707ede65c7df044d7596c09609523cf741/local.conf" > /etc/sysctl.d/local.conf;
          setsid sslocal \
            -U \
            --protocol tun \
            --server-addr "client:8388" \
            --encrypt-method "aes-128-gcm" \
            --password "${SHADOWSOCKS_PASSWORD:-secret}" \
            --tun-interface-address "${NETWORK_PREFIX:-10.8.0}.0/32"
      ports:
        - 51821:51821/tcp
        - 51820:51820/udp
      depends_on:
        client:
          condition: service_healthy
      restart: unless-stopped
  
    server:
      image: ghcr.io/wg-easy/wg-easy:14
      cap_add:
        - NET_ADMIN
      sysctls:
        - net.ipv4.ip_forward=1
        - net.ipv6.conf.all.disable_ipv6=0
      environment:
        WG_HOST: "${HOSTNAME:-host.docker.internal}"
        WG_DEFAULT_ADDRESS: "${NETWORK_PREFIX:-10.8.0}.x"
        WG_MTU: 1296
        WG_POST_UP: >
          ip route add default dev tun0 table 123;
          ip rule add from "${NETWORK_PREFIX:-10.8.0}.0/24" table 123;
      network_mode: service:proxy
      volumes:
        - /config
      restart: unless-stopped
  ```
</details>

<details>
  <summary>/etc/sysctl.d/local.conf</summary>

  ```ini
  # Source: https://github.com/shadowsocks/shadowsocks/wiki/Optimizing-Shadowsocks
  
  # max open files
  fs.file-max = 51200
  # max read buffer
  net.core.rmem_max = 67108864
  # max write buffer
  net.core.wmem_max = 67108864
  # default read buffer
  net.core.rmem_default = 65536
  # default write buffer
  net.core.wmem_default = 65536
  # max processor input queue
  net.core.netdev_max_backlog = 4096
  # max backlog
  net.core.somaxconn = 4096
  
  # resist SYN flood attacks
  net.ipv4.tcp_syncookies = 1
  # reuse timewait sockets when safe
  net.ipv4.tcp_tw_reuse = 1
  # turn off fast timewait sockets recycling
  net.ipv4.tcp_tw_recycle = 0
  # short FIN timeout
  net.ipv4.tcp_fin_timeout = 30
  # short keepalive time
  net.ipv4.tcp_keepalive_time = 1200
  # outbound port range
  net.ipv4.ip_local_port_range = 10000 65000
  # max SYN backlog
  net.ipv4.tcp_max_syn_backlog = 4096
  # max timewait sockets held by system simultaneously
  net.ipv4.tcp_max_tw_buckets = 5000
  # turn on TCP Fast Open on both client and server side
  net.ipv4.tcp_fastopen = 3
  # TCP receive buffer
  net.ipv4.tcp_rmem = 4096 87380 67108864
  # TCP write buffer
  net.ipv4.tcp_wmem = 4096 65536 67108864
  # turn on path MTU discovery
  net.ipv4.tcp_mtu_probing = 1
  
  # for high-latency network
  # net.ipv4.tcp_congestion_control = hybla
  
  # for low-latency network, use cubic instead
  net.ipv4.tcp_congestion_control = cubic
  ```
</details>

Unfortunately the connection is VERY spotty and not useful.

![screencapture-speed-cloudflare-2024-09-11-00_24_02](https://github.com/user-attachments/assets/8fda14e0-e8c5-4fc9-a091-19b2cba36f77)

**Comment by saturneric** [comment]
Hi everyone!

I’ve successfully implemented this setup, and it’s working really well with no noticeable performance issues. Here’s a cleaned-up and more straightforward explanation:

Summary:

The setup allows wg-easy (WireGuard) traffic (10.8.0.0/24) to be routed through Gluetun (172.32.0.4). The network bridge VPN uses the subnet 172.32.0.0/24, where:
- 172.32.0.4 = Gluetun (VPN Container)
- 172.32.0.8 = wg-easy (WireGuard Server Container)

What works:
- Traffic from wg-easy clients (10.8.0.0/24) is routed through Gluetun to reach the internet.
- This setup works regardless of whether Gluetun uses OpenVPN or WireGuard as the protocol.
- The method allows for unlimited clients to connect via wg-easy using a single VPN slot.

wg0 PostUp Configuration (Simplified):

```
iptables -P FORWARD DROP;
iptables -A FORWARD -i wg0 -j ACCEPT;
iptables -A FORWARD -o wg0 -m state --state RELATED,ESTABLISHED -j ACCEPT;
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE;
ip rule add from 10.8.0.0/24 table 200;
ip route add default via 172.32.0.4 dev $VPN table 200;
```

Additional Rules in Gluetun Container:
```
iptables -A FORWARD -i eth0 -o tun0 -j ACCEPT
iptables -A FORWARD -i tun0 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE
iptables -t nat -A PREROUTING -i tun0 -p tcp --dport <Remote_Port> -j DNAT --to-destination 172.32.0.8
iptables -t nat -A PREROUTING -i tun0 -p udp --dport <Remote_Port> -j DNAT --to-destination 172.32.0.8
```

Notes:
- If you want devices within 10.8.0.0/24 to be able to communicate with each other, you will need to configure additional routing tables or firewall rules.
- <Remote_Port> refers to your VPN’s remote port forwarding. This can be customized according to your needs.

Results:

This approach allows all clients connected to wg-easy to access the internet through the VPN connection provided by Gluetun. This effectively bypasses any client limits set by the VPN provider.

To make setup simpler: https://github.com/saturneric/wg-easy-gluetun

Would love to hear your thoughts or suggestions for improvement!

**Reply by lagcero** [reply]
Can you share your docker-compose?

**Reply by saturneric** [reply]
Here.

docker-compose.yaml

``` yaml
version: "3"

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun-ws
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=XXXXXX
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=XXXXX
      - WIREGUARD_PRESHARED_KEY=XXXXX
      - WIREGUARD_ADDRESSES=XXXXXX
      - SERVER_REGIONS=XXXXXX
    volumes:
      - /lib/modules:/lib/modules:ro
      - ./post-rules.txt:/iptables/post-rules.txt:ro
      - ./gluetun-ws:/gluetun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      vpn:
        ipv4_address: 172.32.0.4
        ipv6_address: "fd01:beee:beee::4"
    restart: unless-stopped
      
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:nightly
    container_name: wg-easy
    ports:
      - "51820:51820/udp"
    networks:
      vpn:
        ipv4_address: 172.32.0.8
        ipv6_address: "fd01:beee:beee::8"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - LANG=de
      - WG_HOST=XXXXXX
      - PASSWORD_HASH=XXXXXX
      - PORT=51821
      - WG_PORT=51820
      - WG_DEFAULT_DNS=XXXXXX
      - WG_POST_UP=iptables -P FORWARD DROP; VPN=$(ifconfig | grep -B1 172.32.0.8 | grep -o "^\w*"); iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -m state --state RELATED,ESTABLISHED -j ACCEPT; iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o $$VPN -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; ip rule add from 10.8.0.0/24 table 200; ip route add default via 172.32.0.4 dev $$VPN table 200; ip route add 10.8.0.0/24 dev wg0 table 200; iptables -A FORWARD -s 10.8.0.0/24 -d 10.8.0.0/24 -i wg0 -o wg0 -j ACCEPT; 
      - WG_POST_DOWN=iptables -P FORWARD ACCEPT; VPN=$(ifconfig | grep -B1 172.32.0.8 | grep -o "^\w*"); iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -m state --state RELATED,ESTABLISHED -j ACCEPT; iptables -t nat -D POSTROUTING -s 10.8.0.0/24 -o $$VPN -j MASQUERADE; iptables -D INPUT -p udp -m udp --dport 51820 -j ACCEPT; ip rule del from 10.8.0.0/24 table 200; ip route del default via 172.32.0.4 dev $$VPN table 200; ip route del 10.8.0.0/24 dev wg0 table 200; iptables -D FORWARD -s 10.8.0.0/24 -d 10.8.0.0/24 -i wg0 -o wg0 -j ACCEPT; 
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    volumes:
      - /lib/modules:/lib/modules:ro
      - ./wg-easy:/etc/wireguard
    restart: unless-stopped

networks:
  vpn:
    name: vpn
    external: true

```

post-rules.txt

``` shell

iptables -A FORWARD -i eth0 -o tun0 -j ACCEPT
iptables -A FORWARD -i tun0  -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE

```

**Reply by tomorrow-nf** [reply]
After fighting this for a few days, I've got an updated version I can share that not only filters outgoing traffic through Mullvad, but also allows me to connect to my LAN. (I plugged in my PiHole for WG_DEFAULT_DNS but I don't actually think that does anything here since we're routing out through Gluetun's VPN anyway).

I basically took [this compose, which is meant to do basically the same thing](https://gist.github.com/skylerwlewis/f009741cd20d8ab86ce65d67accccc3f), but swapped out the iptable rules from @saturneric  and added one more:

(replace 192.168.50.0 appropriately)
Up: _ip route add 192.168.50.0/24 via 172.32.0.100 dev $$VPN table 200;_
Down: _ip route del 192.168.50.0/24 via 172.32.0.100 dev $$VPN table 200;_

I also moved WG_HOST and PASSWORD_HASH into a .env file for convenience. My next small task will be automatically updating the IP in this file, as I don't want to expose an A record with my public DNS (Cloudflare's proxy doesn't play well with Wireguard).

This config also disables ipv6, as the one I based most of this on does, probably not necessary and might revisit that later. There are probably cleaner ways to do all of this, networking is a VERY weak area for me, but it seems to be working okay so far

Values to update for anyone who wants to use this:
- 172.32.0.100: Gluetun
- 172.32.0.2: wg-easy
- 192.168.50.0: your local range
- Anything marked XXXXXX
- WG_HOST and PASSWORD_HASH in .env file (or just add them back in)

```yaml
services:
  gluetun:
    container_name: gluetun-wg
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      VPN_SERVICE_PROVIDER: XXXXXX
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: XXXXXX
      WIREGUARD_ADDRESSES: XXXXXX
      SERVER_COUNTRIES: XXXXXX
      UPDATER_PERIOD: 24h
    volumes:
      - ./data/gluetun/conf:/gluetun
    sysctls:
      # Disables ipv6
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
    networks:
      vpn:
        ipv4_address: 172.32.0.100
    ports:
      # port of the gluetun healthcheck server
      - 9999:9999/tcp
    configs:
      # allows wireguard to send traffic through gluetun
      # https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/firewall.md#custom-iptables-rules
      - source: post-rules.txt
        target: /iptables/post-rules.txt
  wg-easy:
    env_file:
      - .env
    environment:
      - LANG=en
      - PORT=51821
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=XXXXXX
      - WG_POST_UP=iptables -P FORWARD DROP; VPN=$(ifconfig | grep -B1 172.32.0.2 | grep -o "^\w*"); iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -m state --state RELATED,ESTABLISHED -j ACCEPT; iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o $$VPN -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; ip rule add from 10.8.0.0/24 table 200; ip route add default via 172.32.0.100 dev $$VPN table 200; ip route add 10.8.0.0/24 dev wg0 table 200; ip route add 192.168.50.0/24 via 172.32.0.1 dev $$VPN table 200; iptables -A FORWARD -s 10.8.0.0/24 -d 10.8.0.0/24 -i wg0 -o wg0 -j ACCEPT;
      - WG_POST_DOWN=iptables -P FORWARD ACCEPT; VPN=$(ifconfig | grep -B1 172.32.0.2 | grep -o "^\w*"); iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -m state --state RELATED,ESTABLISHED -j ACCEPT; iptables -t nat -D POSTROUTING -s 10.8.0.0/24 -o $$VPN -j MASQUERADE; iptables -D INPUT -p udp -m udp --dport 51820 -j ACCEPT; ip rule del from 10.8.0.0/24 table 200; ip route del default via 172.32.0.100 dev $$VPN table 200; ip route del 10.8.0.0/24 dev wg0 table 200; ip route del 192.168.50.0/24 via 172.32.0.100 dev $$VPN table 200; iptables -D FORWARD -s 10.8.0.0/24 -d 10.8.0.0/24 -i wg0 -o wg0 -j ACCEPT;
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ./data/wireguard:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    healthcheck:
      # check health of gluetun container, and auto-restart if gluetun is unhealthy
      test: nc -z 172.32.0.1 9999 || kill 1
      interval: 1m
      timeout: 1m
    restart: unless-stopped
    networks:
      vpn:
        ipv4_address: 172.32.0.2
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
networks:
  vpn:
    ipam:
      config:
        - subnet: 172.32.0.0/24
configs:
  post-rules.txt:
    content: |
      iptables -t nat -A POSTROUTING -o tun+ -j MASQUERADE
      iptables -t filter -A FORWARD -d 172.32.0.2 -j ACCEPT
      iptables -t filter -A FORWARD -s 172.32.0.2 -j ACCEPT

 ```

EDIT:  Slapped together a quick bash script for those who want to set WG_HOST as a direct IP and not expose an A record (i.e. Cloudflare's proxy doesn't work with Wireguard, needs to be "DNS Only", and I didn't want to put that out there publicly). Just slap it on a crontab to run every X minutes.

```
#!/bin/bash
ipinfo=$(curl -s icanhazip.com)
sed -i "/WG_HOST/s/.*/WG_HOST=$ipinfo/" .env
```
