### DISCUSSION TITLE
Reaching other containers on a same stack

### DISCUSSION THREAD

**Discussion by pluja** [qdm12/gluetun#1227] [Q&A] [answered]
I have a stack with 3 containers. Say these containers are `app`, `redis` and `gluetun`. The app should connect through `gluetun` (and it does just fine), but then, from within `app` I can't reach `redis` even being on the same network as `app` and `gluetun`.

Sample docker compose:

```
version: '3.9'

services:
    app:
        image: my/app
        container_name: app
        network_mode: "service:gluetun"
        depends_on:
           - gluetun
           - redis

    redis:
        image: redis
        container_name: redis
        expose:
            - "6379"

    gluetun:
        container_name: archivist-vpn
        image: qmcgaw/gluetun
        ports:
          - 127.0.0.1:8000:8000/tcp
        cap_add:
          - NET_ADMIN
        environment:
          - VPN_SERVICE_PROVIDER=mullvad
          - VPN_TYPE=wireguard
          - WIREGUARD_PRIVATE_KEY=xxxx
          - WIREGUARD_ADDRESSES=xxxx
        restart: "unless-stopped"
```

This is a sample config I just made to illustrate the issue. The fact is that the `app` container can't see the `redis` host. How can I solve this?
