### DISCUSSION TITLE
Issue with Private Internet Access port forwarding

### DISCUSSION THREAD

**Discussion by bmarkenson** [qdm12/gluetun#1247] [Q&A] [answered]
Hi all,
  I'm trying to implement gluetun for the first time, and I'm getting this error in the log:

```
    2022-11-17T12:00:18-08:00 ERROR [port forwarding] cannot refresh port forward data: cannot fetch port forwarding data: cannot obtain signature payload: Get "https://10.33.110.1:19999/getSignature?token=<token>": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

  Thanks for any help!

Here's my docker compose:

```yml
gluetun:
    cap_add:
    - NET_ADMIN
    container_name: gluetun
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: America/Los_Angeles
      VPN_SERVICE_PROVIDER: private internet access
      OPENVPN_USER:  xxxxxxx
      OPENVPN_PASSWORD:  xxxxxxx
      EXTRA_SUBNETS: 10.0.0.0/8,192.168.0.0/16,176.16.0.0/12
      PGID: "1000"
      PUID: "1000"
      TZ: America/Los_Angeles
      SERVER_REGIONS: CA Vancouver
      #SERVER_NAMES: vancouver401,vancouver405,vancouver408,vancouver409
      PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING: enabled
      PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING_STATUS_FILE: /gluetun/forwarded_port
    hostname: DockStarter
    image: qmcgaw/gluetun
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 200k
    networks:
      default: null
    restart: unless-stopped
    volumes:
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: /home/brianm/.config/appdata/gluetun
      target: /config
      bind:
        create_host_path: true
    - type: bind
      source: /mnt/storage/docker
      target: /storage
      bind:
        create_host_path: true
    - type: bind
      source: /mnt/gluetun
      target: /gluetun
      bind:
        create_host_path: true
    ports:
    - 8888:8888/tcp # HTTP proxy
    - 8388:8388/tcp # Shadowsocks
    - 8388:8388/udp # Shadowsocks
    - 8191:8191/tcp # FlareSolverr
    - 6789:6789/tcp # nzbget
    - 5076:5076/tcp # nzbhydra2
    - 9696:9696/tcp # prowlarr
    - 7227:7227/tcp # pyload
    - 8000:8800/tcp # pyload-web
    - 6881:6881/tcp # qBittorrent
    - 6881:6881/udp # qBittorrent
    - 8080:8910/tcp # qBittorrent-web
    - 51413:51413/tcp # Forwarded port
    - 51413:51413/udp # Forwarded port
```
