### DISCUSSION TITLE
NordVPN over OpenVPN credential issue + wireguard

### DISCUSSION THREAD

**Discussion by hydravigil** [qdm12/gluetun#1255] [Q&A]
Putting this here for the moment, because I don't know if these are issues on my side or with gluetun.

## Wireguard

I am currently trying to get NordVPN working over wireguard.  The connection seems to be working at first (I get a ```Wireshark up!``` and ```[healthcheck] healthy!``` at first), but the ```[ip getter]``` greets me with

```
ERROR [ip getter] Get "https://ipinfo.io/": net/http: TLS handshake timeout
```

Pings work from within the container. 

Now, regarding the first line. This behaviour is similar to what I get if I try and switch to NordLynx in the normal linux nordvpn app (on a different host than the container). I can connect to servers, but then again can't seem to make any connections except pings. 

I don't quite know how I even should go about figuring out this issue. There are packets other than ping packets which make their way back to me, i.e. by looking at a tcpdump of the interface container from the outside and doing a ```wget google.com``` from within.

For reference, here is the compose file I used:

```
  gluetun:
    image: qmcgaw/gluetun
    container_name: nordlynx
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - DOT=off
      - LOG_LEVEL=debug
      - FIREWALL_OUTBOUND_SUBNETS=192.168.178.0/24
      - DNS_ADDRESS=192.168.178.59
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=$ip
      - VPN_ENDPOINT_PORT=51820
      - WIREGUARD_PUBLIC_KEY=$pubkey
      - WIREGUARD_PRIVATE_KEY=$privkey
      - WIREGUARD_ADDRESSES=10.5.0.2/32
```

## OpenVPN

Seeing that wireguard was not going to work for now I tried going back to OpenVPN. I first went with the most basic compose, but kept getting my credentials rejected (I was using my mail address as ```OPENVPN_USERNAME```). The first thing I tried was using double quotes around both username and password which did not work. 

I then found some other kind of "service credentials" on the nordvpn website and used them. This also did not work at first, but when I removed the double quotes it somehow started working. I must have restarted the container 20 times before this last change and it never worked so there might be some issue here?
