### DISCUSSION TITLE
Deployment error failed to deploy a stack: (root) Additional property gluetun is not allowed

### DISCUSSION THREAD

**Discussion by edoardoru** [qdm12/gluetun#1272] [Q&A]
Deployment error
failed to deploy a stack: (root) Additional property gluetun is not allowed

```
gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8085:8085
    volumes:
      - /srv/***/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=***
      - OPENVPN_PASSWORD=***
      - SERVER_REGIONS=Italy
      - VPN_TYPE=openvpn
      #- VPNSP=private internet access
      - TZ=Europe/Rome
      - PIA_ENCRYPTION=strong
      - PROTOCOL=tcp
      - OPENVPN_MSSFIX=1460
    restart: always

qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Rome
      - WEBUI_PORT=8085
    volumes:
      - /srv/***:/config
      - /srv/***:/downloads
    depends_on:
      - gluetun
    restart: always
```

is it because of wrong PUID PGID? How can I fix this issue?
