### DISCUSSION TITLE
DNS leak using NordVPN openvpn

### DISCUSSION THREAD

**Discussion by ben-kenney** [qdm12/gluetun#1324] [Q&A] [answered]
Hi, I have been able to setup openvpn with NordVPN and then to check to make sure everything is working correctly, I'm using firefox running in a second container which is networked using `network_mode: "container:gluetun"`. Everything seems to be working but when I check for DNS leaks using https://dnsleaktest.com, it turns out that I **do** have a DNS leak.

My `docker-compose.yml` is basic. Is there anything that I can do to avoid this DNS leak?

gluetun:
```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=${SERVER_REGIONS}
    ports:
      - 3000:3000/tcp # firefox

    restart: unless-stopped
```

firefox container:
```
version: "3"
services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/ben/Downloads/firefox/config:/config
    shm_size: "1gb"
    restart: unless-stopped
    network_mode: "container:gluetun"
```

**Comment by bnhf** [comment, marked as answer]
@ben-kenney 

I have a somewhat similar setup, and I like to use the linuxserver/firefox container for testing as well. Just checked my preferred DNS leak testing website (IPLeak.net), and I saw the correct exit IP addresses and two Cloudflare DNS servers being hit (200x test) -- with no DNS leaks to my ISP. I also tried https://dnsleaktest.com with similar results.

Did you by chance try the Firefox container using your host's Internet connection before connecting it to Gluetun? If so, you may have had some cached entries that need to be cleared from the browser.

Otherwise, there are a few differences between our configurations, which probably won't make a difference, but might be worth trying. I use a single Compose Stack (via Portainer), and so am using service:gluetun rather than container:gluetun:

```yml
version: '3.7'
services:
    gluetun:
        image: qmcgaw/gluetun:latest
        container_name: gluetun
        cap_add:
            - NET_ADMIN
        ports:
            - 8100:8000 # Remote Control VPN
            - 3000:3000 # Firefox
        environment:
            - VPN_SERVICE_PROVIDER=airvpn
            - VPN_TYPE=openvpn
            - SERVER_COUNTRIES=Canada
            - OPENVPN_CIPHERS=AES-256-GCM
            - PUID=1000
            - PGID=1000
            - TZ=US/Mountain
        volumes:
            - /data/openvpn:/gluetun # /data/openvpn contains client.crt and client.key
    
     firefox:
        image: lscr.io/linuxserver/firefox:latest
        container_name: firefox
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=US/Mountain
        volumes:
            - /data/firefox:/config
        shm_size: '1gb'
        network_mode: 'service:gluetun'
        depends_on:
            - gluetun
```

**Reply by ben-kenney** [reply]
Thanks! When I reconfigure to use a single docker-compose file like you have done, I can confirm that I don't get any DNS leaks. I don't know enough to comment about WHY this is happening though but from my testing I would only be recommending a single docker-compose file for now.

**Reply by frepke** [reply]
> Thanks! When I reconfigure to use a single docker-compose file like you have done, I can confirm that I don't get any DNS leaks. I don't know enough to comment about WHY this is happening though but from my testing I would only be recommending a single docker-compose file for now.

I can hardly believe this, if DoT is enabled you have a DNS leak because the DNS server is different from your vpn provider.

@qdm12 When the var `DNS_ADDRESS=x.x.x.x `is used, it overrules `DOT=on`

**Reply by ben-kenney** [reply]
Well, I do have an update on this after some more testing. I'm sorry to say that my previous testing wasn't well controlled 😊 . 

It turns out it was my firefox container configuration that seems to be the source of the DNS leak. What seems to be the issue is how I was defining the firefox `config` volume. When I specify the config volume mapped from my user's home directory like `/home/user/Downloads/firefox/config:/config`, this results in a DNS leak but when I have the volume mapped like `./firefox/config:/config` I don't have a DNS leak.

With the firefox config below I'm now able to have zero DNS leaks using combined `docker-compose.yml` with `network_mode: 'service:gluetun'` and also with separate `docker-compose.yml` with `network_mode: 'container:gluetun'`.

```
version: "3"
services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./firefox/config:/config # -> this DOES NOT result in a DNS leak
      #- /home/ben/Downloads/firefox/config:/config # -> this results in a DNS leak
    shm_size: "1gb"
    restart: unless-stopped
    network_mode: "container:gluetun"
```
