### DISCUSSION TITLE
Privatevpn: what port is forwarded?

### DISCUSSION THREAD

**Discussion by sorentorp** [qdm12/gluetun#1326] [Q&A] [answered]
Hi - love Gluetun, just need one last bit to have the ultimate VPN setup for my p2p needs.

According to PrivateVPN support a port is forwarded as part of the VPN connection, fx. for use in P2P/torrenting usecases.

How do I know what portnumber this is? And how can I read it out, so I can configure my rtorrent to use it as the external port?

Any help is much apreaciated!

**Comment by bnhf** [comment]
@sorentorp 

In my case, with AirVPN, I need to request a port (up to 5 are allowed) through their website by logging into my account. Then the requested port(s) are forwarded on all of their servers -- so it doesn't matter which I'm connected to in the country I'm using as my exit point.

Other providers forward ports they choose randomly, and you need to log into their website to find out the number. After that, you need to open a firewall port in Gluetun using that same port number, and configure your torrent client with it as well. Some VPN providers make it easy, others are a significant hassle.

**Reply by sorentorp** [reply]
Well that was what I feared... I'm still hoping someone has a great solution

**Reply by bnhf** [reply]
@sorentorp 

I did some quick research, since my last post, and it looks like their approach works with their app only. I also checked the Gluetun wiki for PrivateVPN and there's no reference to support for that feature -- assuming it's even available through a public API. Also, would it change every time your VPN connection dropped? Probably. Which means reconfiguring the Gluetun firewall and bittorrent client on each reconnection. Not ideal if you really want/need port forwarding.

**Reply by sorentorp** [reply]
I just got it to work, without any problems. They have specific configs for p2p servers - ovpn-files that need to be used. When they are used, it works just fine...
I'll paste the configs later...

**Comment by bnhf** [comment]
@sorentorp 

Nice work! Great to hear they have a reasonable way to accomplish port forwarding with Gluetun. When you have a chance to post the config info, you could do it as an "Issue" - "Wiki issue", and I'm sure @qdm12 will be happy to add to the Gluetun Wiki for PrivateVPN. It could probably also be done as a PR, if you're familiar with that process.

**Comment by sorentorp** [comment]
I hope this helps

```yml
version: "3"
services:
  gluetun:
    networks:
      - web
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 51413:51413   # rtorrent
      - 6881:6881     # rtorrent DHP
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf #ovpn files provided by PrivatePVN. Pref. Swedish for torrenting.
      - OPENVPN_USER=user@name.com
      - OPENVPN_PASSWORD=Extremelyprivatepassword
      - FIREWALL_VPN_INPUT_PORTS=51413,6881
      - TZ=Europe/Copenhagen
```
