### DISCUSSION TITLE
[dns over tls], [ip getter] write: operation not supported

### DISCUSSION THREAD

**Discussion by cpalll** [qdm12/gluetun#1341] [Q&A]
Currently trying to connect to a wireguard vpn using Gluetun via the userspace implementation. However, logs show the following errors: 
```
gluetun  | 2023-01-11T04:39:56Z INFO [vpn] starting
gluetun  | 2023-01-11T04:39:56Z INFO [firewall] allowing VPN connection...
gluetun  | 2023-01-11T04:39:56Z INFO [wireguard] Using userspace implementation since Kernel support does not exist
gluetun  | 2023-01-11T04:39:56Z INFO [wireguard] Connecting to 103.137.12.195:51820
gluetun  | 2023-01-11T04:39:56Z INFO [wireguard] Wireguard is up
gluetun  | 2023-01-11T04:39:59Z INFO [dns over tls] downloading DNS over TLS cryptographic files
gluetun  | 2023-01-11T04:39:59Z WARN [dns over tls] cannot update files: Get "https://www.internic.net/domain/named.root": dial tcp: lookup www.internic.net on 1.1.1.1:53: write udp 172.29.4.2:51350->1.1.1.1:53: write: operation not permitted
gluetun  | 2023-01-11T04:39:59Z INFO [dns over tls] attempting restart in 20s
gluetun  | 2023-01-11T04:39:59Z ERROR [ip getter] Get "https://ipinfo.io/": dial tcp: lookup ipinfo.io on 1.1.1.1:53: write udp 172.29.4.2:39827->1.1.1.1:53: write: operation not permitted
gluetun  | 2023-01-11T04:39:59Z INFO [ip getter] retrying in 5s
```
My compose file:
```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    #volumes:
      #- ./yourovpnconfig.conf:/gluetun/config.conf:ro
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard

      # For OpenVPN
      #- OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf

      # For Wireguard
      - VPN_ENDPOINT_IP=******
      - VPN_ENDPOINT_PORT=51820
      - WIREGUARD_PUBLIC_KEY=*********************
      - WIREGUARD_PRIVATE_KEY=*************************
      - WIREGUARD_ADDRESSES=0.0.0.0/0 
```
I'm new to using gluetun so any advice would be much appreciated :)
