### DISCUSSION TITLE
Mullvad and port forwarding

### DISCUSSION THREAD

**Discussion by capsel22** [qdm12/gluetun#1355] [Q&A]
Hi,

Would someone be so kind and help me work out why I cant get port forwarding to work, please?

I've got mullvad port forwarding configured on the website (59130). 
Now, I've created two mapping 5055:5055 and 59130:5055 so that the container which is routed via gluetun can be reached on both ports.
It works internally when I do http://privateIP:5055/ and http://privateIP:59130 . Both are working no issues.

However when I try to use http://publicIP:59130 it doesn't. I've checked and I am using the correct IP based on mullvad guide to port forwarding.

I am attaching my cut-down docker-compose:

```yml
version: "3.6"
services:

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    network_mode: bridge
    networks: 
      - privatenet
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTPProxy
      - 5055:5055 # overseerr
      - 59130:5055 # overseerr public
    environment:
      - TZ=Europe/London
      - PUID=1001
      - PGID=1001
      - HTTPPROXY=on
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=xx
      - WIREGUARD_ADDRESSES=xx
      - SERVER_CITIES=Amsterdam
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - FIREWALL_VPN_INPUT_PORTS=59130
    restart: always

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
    volumes:
      - /mnt/data/config/overseerr:/config
    restart: unless-stopped
              
networks:
  privatenet:
    ipam:
      driver: default
      config:
        - subnet: 172.99.0.0/16
          gateway: 172.99.0.1
        - subnet: 2001:db8:1::/64
          gateway: 2001:db8:1::1
```
