### DISCUSSION TITLE
cant make heads or tails of the custom openvpn guide

### DISCUSSION THREAD

**Discussion by verisar** [qdm12/gluetun#1375] [Q&A] [answered]
starting at 2 from https://github.com/qdm12/gluetun/wiki/OpenVPN-configuration-file 

bind mount from where? i just drop files into my created docker folder per container for configs so i dont understand where i would keep this file and bind mount it to? LIke do i need a folder at /gluetun/ on my distro?

4. wow like holy how i dont understand, is this for .env file and am i just circle jerking the .conf file, i have no clue why its called in the .env and is it just like a ghost or something could i not instead do like -e /path/to/conf:/glueton/custom.conf

this is thuraly thrown my thought process thru a loop.

after writing the above i said fuck it and just did it the way i thought and well the checked ip results look like they worked

**Comment by alexeyhome21** [comment]
Hi all! (same for open vpn)  and who knows, installed the client in the docker. And if your server is openvpn. That's where the files are imported, ovpn. Or am I misunderstanding how it works, thanks in advance.

**Comment by beyondunreal79** [comment]
I am in the same boat. Ever get anywhere with his?

**Comment by bnhf** [comment]
@beyondunreal79 

Lots of people use custom configurations with Gluetun. It can either be for those that have their own OpenVPN server somewhere, or for an as yet unsupported VPN provider.

Linux OpenVPN clients typically use a .conf file (containing the OpenVPN directives required for the client), with separate .crt and .key files. If you're using a commercial VPN service you'll need to be able to download those by logging into your provider's website, and generating them. If your provider only offers a .ovpn file, then you'll want to use a text editor to separate the OpenVPN directives from the cert and key. Usually you can download a zip where they're already separate files.

The other key thing you need to do, in this case somewhat specific to Gluetun, is to turn the hostname of the OpenVPN server into an IP address. This is required because Gluetun blocks DNS queries until the VPN tunnel is up-and-running. See the guide referenced at the beginning of this discussion for a suggested way to turn the server's hostname into an IP address.

Once you have your .conf, .crt and .key files, they need to be placed in a directory on your host computer and that directory needs to be bound to the Gluetun Docker container. An example of a docker-compose for a custom config would look like this:

```yml
version: '3.7'
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    volumes:
      - /yourpath:/gluetun
      - /yourpath/custom.conf:/gluetun/custom.conf:ro
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
      - VPN_TYPE=openvpn
      - OPENVPN_USER='yourusername'
      - OPENVPN_PASSWORD='yourpassword'
      - TZ=Europe/London
  ```

So those are the basics stated in a little bit different way than the referenced guide. Let us know if you have any more specific questions.
