### DISCUSSION TITLE
Reverse proxy with SSL

### DISCUSSION THREAD

**Discussion by sighdigh** [qdm12/gluetun#1457] [Q&A]
Hi everyone,

I absolutely love Gluetun and the way everything is documented. I feel very safe using it. I am sorry if this question has an obvious answer but I am completely clueless as to how to proceed with the setup of a reverse proxy. My ISP does not allow me to forward ports and I was hoping I could achieve this via a VPN instead. I purchased a domain via GoDaddy and I use Cloudflare for my DNS. I would like to serve Jellyfin on that domain and to have SSL enabled.

My current setup is done with Mullvad and the docker-compose.yml (which has been managed via Portainer) runs like this:

```
version: "3"
services:
  gluetun:
    container_name: mullvad
    image: qmcgaw/gluetun
    networks:
      gluetun_network:
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER={ACCOUNT NUMBER}
      - SERVER_CITIES=zurich
      - FIREWALL_VPN_INPUT_PORTS=56598,56854
      - OWNED_ONLY=yes
      - HTTP_CONTROL_SERVER_LOG=on
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - "8080:8080" #QBIT
      - "8989:8989" #SONARR
      - "7878:7878" #RADARR
      - "9696:9696" #PROWLARR
      - "6767:6767" #BAZARR
      - "5055:5055" #JELLYSEERR
      - "8787:8787" #READARR
      - "3000:3000" #FIREFOX
      - "8096:8096" #JELLYFIN
      - "8000:8000" #HTTP CONTROL SERVER
      - "56598:56598" #PF1
      - "56854:56854" #PF2

networks:
  gluetun_network:
    external: true

```
I have also got a few other containers (namely the ones mentioned in the ports section) connected to the gluetun container via network_mode: “container:mullvad”. I’ve done connection tests and the containers can all see each other and there are no IP leaks or anything.

I set up an A record to point to my VPN’s IP address and another A record for the subdomain (jelly.mydomain.com)

As you can see in the docker-compose.yml file, I have forwarded ports 56598 and 56854 via Mullvad’s website (well, it’s the random ports that I got) and I’ve done the port check and they are indeed open and reachable. 
I have tried setting up a reverse proxy with caddy-scratch, trying to make it point to my jellyfin container (port 8096) by setting up my Caddyfile like this:

```

{
    email my@email.com
    http_port 56598
    https_port 56854

}

jelly.mydomain.com {
    reverse_proxy 127.0.0.1:8096
}
```
My caddy-scratch container looks like this:
```
version: "3.7"

services:
  caddy:
    image: caddy-scratch
    user: "1001:1001"
    network_mode: "container:mullvad"
    restart: unless-stopped
    environment:
      - TZ=Europe/Germany     
    volumes:
      - /home/me/docker/appdata/caddy/caddydir:/caddydir
```

Whenever I run it, though, it keeps throwing up “acme challenge failed” prompts in the logs and naturally I cannot access jellyfin by doing jelly.mydomain.com

I have been following #464 but there are a few concepts that are too advanced for me unfortunately. I do not know if I am supposed to publish the ports I am forwarding via gluetun or if it matters at all. Also, I’m not familiar with DNS challenges and how I should set it up via caddy in docker, if it’s even possible.

Any help would be greatly appreciated!
