### DISCUSSION TITLE
Error response from daemon: failed to create shim task when environment variable HTTPPROXY is enabled.

### DISCUSSION THREAD

**Discussion by gruesomehit** [qdm12/gluetun#1462] [Q&A] [answered]
Hello,

I recenly installed Gluetun with Qbitorrent. Everything works well except when HTTPPROXY variable is enabled.

When the container starts, it shows this error message:

_Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: can't get final child's PID from pipe: EOF: unknown_

If I run `docker logs gluetun` to get more information, I get the following error:

_ERROR reading from environment variables: environment variable HTTPPROXY: value is not valid: value "true" can only be one of enabled, yes, on, disabled, no, off_

My docker-compose file:
```
 gluetun:
      image: qmcgaw/gluetun
      container_name: gluetun
      networks:
        - t2_proxy
      restart: always
      security_opt:
        - no-new-privileges:true
      cap_add:
        - NET_ADMIN
       devices:
         - /dev/net/tun
       volumes:
         - ${USERDIR}/docker/gluetun:/gluetun
       ports:
         - 9699:9699 # qBittorrent
         - 8889:8888/tcp #proxy    
       environment:
         TZ: $TZ
         HTTPPROXY: on                                                                                                                                                                                                                                        
        FIREWALL_OUTBOUND_SUBNETS: 192.168.1.0/24
        # Wireguard
         VPN_SERVICE_PROVIDER: custom
         VPN_TYPE: wireguard
         VPN_ENDPOINT_IP: $ENDPOINT
         VPN_ENDPOINT_PORT: 51820
         WIREGUARD_PUBLIC_KEY: $PUBLIC_KEY
         WIREGUARD_PRIVATE_KEY: $PRIVATE_KEY
         WIREGUARD_ADDRESSES: $IP_ADDRESS
```
Disabling `HTTPPROXY: on` makes it work flawlessly. 

Thank you very much in advance.
