### DISCUSSION TITLE
How to use surfshark (wireguard) with DNS container in same docker-compose

### DISCUSSION THREAD

**Discussion by Covernel** [qdm12/gluetun#1467] [Q&A] [answered]
I want to use single DNS server with many gluetun containers to save resources, but i can't make it work with surfshark (wireguard)

1. surfshark (OpenVPN) + DNS_ADDRESS=[container IP] -> **Everything works**
2. surfshark (wireguard) -> **Everything works**
3. surfshark (wireguard) + DNS_ADDRESS=[container IP] -> **DNS Resolution not work**, I can visit internet via IP address only.
`ERROR [ip getter] Get "https://ipinfo.io/": dial tcp: lookup ipinfo.io on 172.30.0.10:53: read udp 10.14.0.2:36938->172. timeout`
------
1. docker-compose: surfshark (OpenVPN) + DNS_ADDRESS
```
version: '3.7'

networks:
  default:
    ipam:
      config:
        - subnet: 172.30.0.0/24
	
services	
  dns:  
    image: qmcgaw/dns:v2.0.0-beta
    container_name: dns
    restart: always
    networks:
      default:
        ipv4_address: 172.30.0.10
		
  surfshark:
    image: qmcgaw/gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      - default
    environment:
      - DOT=off
      - DNS_ADDRESS=172.30.0.10
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=openvpn
      - OPENVPN_USER=<OPEN_VPN_USER>
      - OPENVPN_PASSWORD=<OPEN_VPN_PASSWORD>
```

2. docker-compose: surfshark (wireguard)
```
version: '3.7'

services	
  surfshark:
    image: qmcgaw/gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      - default
    environment:
      - DOT=off
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_ADDRESSES=<WIREGUARD_ADDRESSES>
      - WIREGUARD_PRIVATE_KEY=<WIREGUARD_PRIVATE_KEY>
```

3. docker-compose: surfshark (wireguard) + DNS_ADDRESS
```
version: '3.7'

networks:
  default:
    ipam:
      config:
        - subnet: 172.30.0.0/24
	
services	
  surfshark:
    image: qmcgaw/gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      - default
    environment:
      - DOT=off
      - DNS_ADDRESS=172.30.0.10  
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_ADDRESSES=<WIREGUARD_ADDRESSES>
      - WIREGUARD_PRIVATE_KEY=<WIREGUARD_PRIVATE_KEY>
```

**Comment by Covernel** [comment, marked as answer]
Solved. 
Because all traffic go through wireguard,  `gluetun (surfshark)` cannot reach local container `dns`.

Switched to image `image: qmcgaw/gluetun:pr-1291` which support env `WIREGUARD_ALLOWED_IPS`. 
After exclude the stack's CIDR, DNS works.


```
surfshark-wg:  
  image: qmcgaw/gluetun:pr-1291
  ...
  environment:
    # excluded stack's subnet 172.30.0.0/24
    - WIREGUARD_ALLOWED_IPS=0.0.0.0/1, 128.0.0.0/3, 160.0.0.0/5, 168.0.0.0/6, 172.0.0.0/12, 172.16.0.0/13, 172.24.0.0/14, 172.28.0.0/15, 172.30.1.0/24, 172.30.2.0/23, 172.30.4.0/22, 172.30.8.0/21, 172.30.16.0/20, 172.30.32.0/19, 172.30.64.0/18, 172.30.128.0/17, 172.31.0.0/16, 172.32.0.0/11, 172.64.0.0/10, 172.128.0.0/9, 173.0.0.0/8, 174.0.0.0/7, 176.0.0.0/4, 192.0.0.0/2
```
