### DISCUSSION TITLE
NordVPN setup not working "OpenVPN settings: user is empty"

### DISCUSSION THREAD

**Discussion by Whipbread** [qdm12/gluetun#1468] [Q&A] [answered]
Hi,

Im trying to setup a new stack with NordVPN. I followed the wiki as in: 

[NordVPN](https://github.com/qdm12/gluetun/wiki/NordVPN)

I'm getting ths error in the logs:

> ERROR VPN settings: OpenVPN settings: user is empty

I've used the VPN provider on other containers and it works.

Here's my stack:

```
services:
  gluetun-vpn:
    image: qmcgaw/gluetun:latest
    container_name: gluetun-vpn
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /(mystack):/gluetun
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=(myuser)
      - OPENVPN_PASSWORD=(mypassword)
      - SERVER_REGIONS=Netherlands    
    restart: always
```

Help appreciated,

W.
