### DISCUSSION TITLE
Using Pihole as DNS When Accessing Gluetun via HTTP Proxy

### DISCUSSION THREAD

**Discussion by rab23** [qdm12/gluetun#1469] [Q&A]
Struggling a bit with this so hoping  someone might be able to help.  I've connected my pihole container to gluetun based on comments in similar discussions: 
Connect pihole container to gluetun and set the following gluetun parameters
DOT=off 
DNS_PLAINTEXT_ADDRESS=127.0.0.1
-p 53:53/udp -p 53:53/tcp -p xxxx:80/tcp

I'm able to access the pihole admin site and can use pihole as the DNS on my router and get the expected results (i.e. devices on my lan pass thru the pihole sever).
What I can't seem to get working is when using SwithcyOmega/HTTP Proxy to access gluetun via another pc on my lan,  the dns requests don't go thru pihole.  I even set my pihole config to permit all origins but still not luck.

Is what I'm trying to do not possible?  I thought that the above settings forced pihole to be the only DNS used, but it seems when I go thru the HTTP Proxy, cloudfare or whatever DOT_PROVIDERS I set gets used instead.

**Comment by dessijr** [comment]
Hello, i am trying this to but can not get it to use pihole with unbound as dns. This is my compose file:

```
volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    #dns:
      #- 127.0.0.1
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 4480:4480
      - 443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - ${PIHOLE_WEBPORT:-80}:80/tcp #Allows use of different port to access pihole web interface when other docker containers use port 80
      - 5335:5335/tcp # Uncomment to enable unbound access on local server
      - 22/tcp # Uncomment to enable SSH
    volumes:
      - /etc/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      #- VPN_SERVICE_PROVIDER=surfshark
      #- VPN_TYPE=wireguard
      # OpenVPN:
      #- OPENVPN_USER=
      #- OPENVPN_PASSWORD=
      # Wireguard:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=######
      - WIREGUARD_ADDRESSES=10.14.0.2/16
      - SERVER_COUNTRIES=Germany #,Netherlands ,United States
      - HTTPPROXY=on
      - HTTPPROXY_LOG=off
      - FIREWALL_OUTBOUND_SUBNETS=192.168.178.0/24,10.6.0.0/24,172.0.0.0/8
      #- DNS_ADDRESS=127.0.0.1
      - DNS_PLAINTEXT_ADDRESS=127.0.0.1
      #- HTTP_CONTROL_SERVER_ADDRESS=:8001
      - DOT=off
      #- DNS_KEEP_NAMESERVER= on
      # Timezone for accurate log times
      - TZ=Europe/Berlin
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h
    restart: unless-stopped 
  
  pihole:
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    container_name: pihole
    image: cbcrowe/pihole-unbound:latest

    domainname: local
    environment:
      - HOSTNAME=pihole
      - PIHOLE_WEBPORT=80
      - DOMAIN_NAME=local
      #- FTLCONF_LOCAL_IPV4=192.168.178.2
      - TZ=Europe/Berlin
      - WEBPASSWORD='####
      - WEBTHEME=default-darker
      - REV_SERVER=true
      - REV_SERVER_TARGET=192.168.178.1
      - REV_SERVER_DOMAIN=local
      - REV_SERVER_CIDR=192.168.0.0/16
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC="true"
      - DNSMASQ_LISTENING=single
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    restart: unless-stopped
`
```
