### DISCUSSION TITLE
Static Docker IP using network_mode

### DISCUSSION THREAD

**Discussion by macdis** [qdm12/gluetun#1478] [Q&A] [answered]
So in normal Docker networking, it's possible to assign a static docker IP to a container within docker-compose.yml, for example as follows:
```
services:
  serviceA:
    networks:
      somenetwork:
        ipv4_address: 172.20.0.20    # <---Here I'm assigning a static IP to this container
networks:
  somenetwork:
    external: true
    name: somenetwork

```
 But this doesn't seem to work if network_mode is used, because "ipv4_address" is not a parameter of "network_mode":
```
services:
  gluetun:
    [...]
    networks:
      - somenetwork
  serviceB:
    network_mode:
      service:gluetun    # <---Here I'm using the gluetun service
networks:
  somenetwork:
    external: true
    name: somenetwork
```
How do I assign a static Docker IP 172.20.0.x to serviceB in the second example, where network_mode is defined as service:gluetun?

Reason I'm asking: I have a container that misbehaves occasionally and I noticed that this correlates with the internal docker IP changing for whatever reason, so I'm trying to troubleshoot the issue by assigning a static Docker IP to the container.

**Comment by macdis** [comment, marked as answer]
Silly me. I just need to assign a static IP to the gluetun container, which is what the serviceB container uses.
```
services:
  gluetun:
    [...]
    networks:
      somenetwork:
        ipv4_address: 172.20.0.20
  serviceB:
    network_mode:
      service:gluetun
```
