### DISCUSSION TITLE
qbittorrent and port mapping

### DISCUSSION THREAD

**Discussion by ghost** [qdm12/gluetun#1514] [Q&A]
Hi,

I have the following configuration (2 different containers) with qbittorrent :

For **gluten**
```
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy. !! I Guess I can remove this !!
      - 8388:8388/tcp # Shadowsocks  !! I Guess I can remove this !!
      - 8388:8388/udp # Shadowsocks  !! I Guess I can remove this !!
      - 8090:8090 # port for qbittorrent
      # - 6881:6881   !! Why people add this ? !!
      # - 6881:6881/udp  !! Why people add this ? !!
    volumes:
      - xxx/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=xxx
      - VPN_TYPE=openvpn
      - OPENVPN_USER= xxx
      - OPENVPN_PASSWORD= xxx
      - SERVER_REGIONS= xxx
      - TZ=xxx
    restart: unless-stopped

``` 
For **qbittorrent**
```
services:
  torrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: container:gluetun
    environment:
      - WEBUI_PORT=8090
      - PUID=1001
      - PGID=100
      - TZ= xx
    volumes:
      -xx:/config
      -xx:/downloads
    restart: unless-stopped
```

As you can see I do not specify ports for qbittorent ( 6881 for tcp and udp) but most people do (at least what I have seen).
Still (and having the default settings on qbittorent) using https://ipleak.net, I can see that qbittorrent traffic goes through my vpn provider on port 6881 (which is not open on my router and which is the default port on qbittorrent). For me this is THE expect behavior. Or  ? 

Best
