### DISCUSSION TITLE
LinuxServer Containers do not start if connected to gluetun on Synology reboot

### DISCUSSION THREAD

**Discussion by agent3133** [qdm12/gluetun#1525] [Q&A]
Hi,

I have fairly simple Docker compose stack based on your examples. It has gluetun container in "bridge" network_mode and several containers connected to it. Docker is running on Synology with Portainer.

As long as it is started manually in Portainer all works just fine. But if Synology is restarted, then only "gluetun" container manages to start, all other containers on the same network fail to start either with error 128, wenn it is started in the same compose file, or with error 137, when it is started from different compose file.

If containers are not connected to the gluetun, then they are restarted without any issues.

```yaml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun_vpn
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=vpn unlimited
      - OPENVPN_USER=...
      - OPENVPN_PASSWORD=...
      - SERVER_HOSTNAMES=fr.vpnunlimitedapp.com,ro.vpnunlimitedapp.com
      - OPENVPN_VERSION=2.4
      - OPENVPN_KEY=...
      - OPENVPN_CERT=...
    ports: #uncomment ports below for additional applications
      - 8085:8085 # port for qbittorrent remove the # to use
      - 8999:8999
    volumes:
      - /volume1/docker/gluetun:/gluetun
    network_mode: bridge
    restart: unless-stopped
    
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    mem_limit: 3000m
    mem_reservation: 128M
    environment:
      - PUID=1040
      - PGID=100
      - TZ=Europe/Berlin
      - WEBUI_PORT=8085
    volumes:
      - /volume1/docker/qbittorrent/config:/config
      - /volume1/Downloads:/downloads
    restart: always
    network_mode: "service:gluetun"
```
