### DISCUSSION TITLE
Wireguard k8s sidecar to access remote LAN for HomeAssistant

### DISCUSSION THREAD

**Discussion by danriedl** [qdm12/gluetun#1558] [Q&A]
Ola amigos,

I use the newest truecharts for my TrueNAS system, which allows the usage of gluetun, to have a kubernetes sidecar alongside an application.
Gluetun does connect to the remote site and if i exec into the container I also can see that I'm using the external WAN IP of the remote site, but I'm not able to access the remote LAN and its devices to use it in local homeassistant pod.

Some more details:
- The WG-Server is hosted on a FritzBox (widely used in Germany i guess).
- The wg-config:
```ini
[Interface]
PrivateKey = EKd[...]UY=
Address = 192.168.178.202/24
DNS = 172.17.0.10
DNS = 192.168.178.1
DNS = fritz.box

[Peer]
PublicKey = bzz[...]4jE=
PresharedKey = CEG/O[...]S8=
AllowedIPs = 192.168.178.0/24,0.0.0.0/0
Endpoint = xyz.[...].de:50100
PersistentKeepalive = 25
```
- The remote LAN is `192.168.178.0/24` and the Kubernetes DNS is `172.17.0.10``

- This is my container right now:
```yaml
- env:
    - name: TZ
      value: Europe/Berlin
    - name: UMASK
      value: "0022"
    - name: UMASK_SET
      value: "0022"
    - name: NVIDIA_VISIBLE_DEVICES
      value: void
    - name: PUID
      value: "568"
    - name: USER_ID
      value: "568"
    - name: UID
      value: "568"
    - name: PGID
      value: "568"
    - name: GROUP_ID
      value: "568"
    - name: GID
      value: "568"
    - name: DNS_KEEP_NAMESERVER
      value: "on"
    - name: DOT
      value: "off"
    - name: FIREWALL
      value: "on"
    - name: FIREWALL_OUTBOUND_SUBNETS
      value: 192.168.178.0/24
    - name: VPN_ENDPOINT_IP
      value: [...].8.[...].109
    - name: VPN_ENDPOINT_PORT
      value: "50100"
    - name: VPN_SERVICE_PROVIDER
      value: custom
    - name: VPN_TYPE
      value: wireguard
    - name: WIREGUARD_ADDRESSES
      value: 192.168.178.202/24
    - name: WIREGUARD_PRESHARED_KEY
      value: CEG/O[...]S8=
    - name: WIREGUARD_PRIVATE_KEY
      value: EKd[...]UY=
    - name: WIREGUARD_PUBLIC_KEY
      value: bzz[...]4jE=
  image: qmcgaw/gluetun:latest
  imagePullPolicy: IfNotPresent
  name: xyz-ha-home-assistant-vpn
  resources:
    limits:
      cpu: "4"
      memory: 8Gi
    requests:
      cpu: 10m
      memory: 50Mi
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      add:
        - NET_ADMIN
        - NET_RAW
        - MKNOD
        - SYS_MODULE
        - CHOWN
        - SETUID
        - SETGID
        - FOWNER
        - DAC_OVERRIDE
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: false
    runAsGroup: 568
    runAsNonRoot: false
    runAsUser: 0
    seccompProfile:
      type: RuntimeDefault
  terminationMessagePath: /dev/termination-log
  terminationMessagePolicy: File
  volumeMounts:
    - mountPath: /config
      name: config
    - mountPath: /dev/shm
      name: devshm
    - mountPath: /shared
      name: shared
    - mountPath: /tmp
      name: tmp
    - mountPath: /var/logs
      name: varlogs
    - mountPath: /var/run
      name: varrun
```

Could someone point me in the right correction, of how to access the remote LAN in HomeAssistant?
