### DISCUSSION TITLE
Error reading servers from file

### DISCUSSION THREAD

**Discussion by riccardoerra** [qdm12/gluetun#1657] [Q&A] [answered]
Hi all,

I'm trying to run Gluetun on my Synology via Docker. I tried for hours both yesterday and today on both DSM 7.1 and 7.2 but I always get the same error:

`ERROR reading servers from file: decoding servers: unexpected end of JSON input`.

I tried to delete the container and the image multiple times but the issue doesn't go away.

I'm using the latest release 3.34.3 and tried already a previous one, 3.34.1, but the outcome is the same.

Attaching a screenshot of the logs:
![image](https://github.com/qdm12/gluetun/assets/3142540/e7f02b5f-cdb8-4a73-b547-0a46fe63f0ca)

Any idea what is the issue and how to solve it?

Thanks in advance!

**Comment by riccardoerra** [comment]
Adding my compose file in case it helps:

```
services:
  gluetun:
    image: qmcgaw/gluetun:v3.34.1
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8090:8090 # port for qbittorrent
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=[REDACTED]
      - OPENVPN_PASSWORD=[REDACTED]
      - SERVER_REGIONS=United Kingdom
      - TZ=Europe/London
      - HTTPPROXY=off #change to on if you wish to enable
      - SHADOWSOCKS=off #change to on if you wish to enable
      - FIREWALL_OUTBOUND_SUBNETS=172.20.0.0/16,192.168.5.0/24 #change this in line with your subnet see note on guide.
    network_mode: synobridge
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1029
      - PGID=100
      - TZ=Europe/London
      - WEBUI_PORT=8090
    volumes:
      - /volume1/docker/qbittorrent:/config
      - /volume1/data/torrents:/data/torrents
    network_mode: service:gluetun # run on the vpn network
    depends_on:
      - gluetun
    restart: unless-stopped
```
