### DISCUSSION TITLE
IP address not found for interface

### DISCUSSION THREAD

**Discussion by darthf1** [qdm12/gluetun#1662] [Q&A]
Hi!

Since recently, I noticed my gluetun container cannot go up anymore, and I noticed the following error log:
```
gluetun  | ========================================
gluetun  | ========================================
gluetun  | =============== gluetun ================
gluetun  | ========================================
gluetun  | =========== Made with ❤️ by ============
gluetun  | ======= https://github.com/qdm12 =======
gluetun  | ========================================
gluetun  | ========================================
gluetun  | 
gluetun  | Running version latest built on 2023-06-08T09:55:12.339Z (commit 2ec9293)
gluetun  | 
gluetun  | 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
gluetun  | 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
gluetun  | ✨ New feature? https://github.com/qdm12/gluetun/issues/new
gluetun  | ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
gluetun  | 💻 Email? quentin.mcgaw@gmail.com
gluetun  | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
gluetun  | 2023-06-08T12:31:57+02:00 WARN DNS_ADDRESS is set to 192.168.2.254 so the DNS over TLS (DoT) server will not be used. The default value changed to 127.0.0.1 so it uses the internal DoT serves. If the DoT server fails to start, the IPv4 address of the first plaintext DNS server corresponding to the first DoT provider chosen is used.
gluetun  | 2023-06-08T12:31:57+02:00 INFO [routing] default route found: interface eth0, gateway 172.18.0.1, assigned IP 172.18.0.4 and family v4
gluetun  | 2023-06-08T12:31:57+02:00 ERROR getting assigned IP of lo: IP address not found for interface: interface lo in 1 addresses
gluetun  | 2023-06-08T12:31:57+02:00 INFO Shutdown successful
```

I have no idea what to do about:
```
ERROR getting assigned IP of lo: IP address not found for interface: interface lo in 1 addresses
```

I added `DNS_ADDRESS` which you can see emitted as a warning, but with or without that variable does not change anything.

```yaml
version: ‘3.9’
services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      - PUID=1026
      - PGID=100
      - DNS_ADDRESS=192.168.2.254
      - VPN_SERVICE_PROVIDER=
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - SERVER_REGIONS=Netherlands
      - TZ=Europe/Amsterdam
      - FIREWALL_OUTBOUND_SUBNETS=192.168.2.0/24
      - UPDATER_PERIOD=24h
```
