### DISCUSSION TITLE
ERROR VPN settings: OpenVPN settings: password is empty

### DISCUSSION THREAD

**Discussion by ghost** [qdm12/gluetun#1668] [Q&A]
Hello,
I am setting up gluetun with ivpn and I dont know what to put for the password. Below is my docker-compose.yml file.
```
version: "3.8"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=ivpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=i-xxx
      - OPENVPN_PASSWORD=
```
