### DISCUSSION TITLE
Newbie to Traefik having issues with proxying gluetun.

### DISCUSSION THREAD

**Discussion by nn0de** [qdm12/gluetun#1686] [Q&A]
So I haven't really been able to locate a resolution for this but I am very new to Traefik. I currently have set up traefik along with configuring my static and dynamic config files and have traefik up and running proxying most of my applications but because I have gluetun with 2 containers connected to it I have not been able to locate a set of docs that I can comprehend to get this working. Is anyone able to assist in me getting this up and running behind traefik?

Reference post I tried to follow but no luck: https://github.com/qdm12/gluetun/issues/646

Downloading stack Docker-compose

```
version: "3"

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    network_mode: "gluetun"
    environment:
      - TZ=Australia/Melbourne
      - PUID=1000
      - PGID=1000
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=xxxxxxxxxxxxx
      - OPENVPN_PASSWORD=xxxxxxxxxxxxxxx
      - SERVER_COUNTRIES=Netherlands
      - FIREWALL_OUTBOUND_SUBNETS=192.168.0.0/24
    volumes:
      - /usb1/Configs/Gluetun:/gluetun
    ports:
      - 8084:8080 #SABnzbd
      - 9696:9696 #Prowlarr
      - 8000:8000 #API
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: "service:gluetun"
#    network_mode: "bridge"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - /usb1/Configs/SABnzbd:/config
      - /usb1/Media:/Media
#    ports:
#      - 8084:8080
    depends_on:
      - gluetun
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - /usb1/Configs/Prowlarr:/config
    depends_on:
      - gluetun
    restart: unless-stopped
```
