### DISCUSSION TITLE
gluetun "arr" app and webui How to connect?

### DISCUSSION THREAD

**Discussion by mg-dev25** [qdm12/gluetun#1690] [Q&A]
Hello, I think I miss some information basic on how to connect to the webui of a container connect to gluetun?

First, maybe my compose is missing something?

```
version: "3.9"
name: media-stack
services:
  vpn:
    container_name: vpn
    image: qmcgaw/gluetun:v3.33
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - SERVER_COUNTRIES=Switzerland
      - WIREGUARD_PRIVATE_KEY=0###hidden####=
    networks:
      - mynetwork
    ports:
      # qbittorrent ports
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
      # prowlarr ports
      - 9696:9696
    restart: "unless-stopped"

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:4.5.2
    # Comment this if vpn is disabled
    depends_on:
      - vpn
    network_mode: service:vpn # Comment this line if vpn is disabled
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=5080
    volumes:
      - qbittorrent-config:/config
      - torrent-downloads:/data
    restart: "unless-stopped"

  radarr:
    container_name: radarr
    image: linuxserver/radarr:4.4.4
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - torrent-downloads:/data
    restart: "unless-stopped"

  sonarr:
    image: linuxserver/sonarr:4.0.0-develop
    container_name: sonarr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - sonarr-config:/config
      - torrent-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:1.4.1-develop
    # Comment this if vpn is disabled
    depends_on:
      - vpn
    network_mode: service:vpn # Comment this line if vpn is disabled
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - ES_URL=http://localhost:9696
      - REDIS_HOST=localhost
    volumes:
      - prowlarr-config:/config
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin:10.8.10
    container_name: jellyfin
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyfin-config:/config
      - torrent-downloads:/data
  # devices:
   #  - /dev/videoN:/dev/videoN # Mount GPU device 
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 8920:8920
    restart: unless-stopped
  
volumes:
  torrent-downloads:
  radarr-config:
  sonarr-config:
  prowlarr-config:
  jellyfin-config:
  qbittorrent-config:
  tx-config:
  tx-watch:

networks:
  mynetwork:
    external: true
```

I'm on arck linux. My all system is already connect to nordvpn, so maybe in this situation, I need to add other option in "compose".

Thanks for you help.
