### DISCUSSION TITLE
Windscribe with Wireguard, Static IP and permanent port forwarding

### DISCUSSION THREAD

**Discussion by pannal** [qdm12/gluetun#1704] [Q&A]
Hey,

Thank you for this great docker image, first of all.

My issue is with Windscribe. I've paid for a static IP and added permanent ports. Then I downloaded a Wireguard config and adapted it to gluetun in docker-compose.

The connection works well but the ports don't get exposed (I'm using port-checker to test). ~Weirdly the same happens with the Windscribe Windows client as well.~ See below, it works on Windows with the official client, but not using gluetun.

Did anyone get this to work?

For reference, here's my gluetun config;
```
xxxxxxxxx:
    image: qmcgaw/gluetun
    container_name: xxxxxxxxx
    hostname: xxxxxxx
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - TZ=Europe/Berlin
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=1.2.3.4
      - VPN_ENDPOINT_PORT=443
      - WIREGUARD_PRIVATE_KEY=redacted
      - WIREGUARD_PUBLIC_KEY=redacted
      - WIREGUARD_ADDRESSES=1.2.3.5/32
      - WIREGUARD_PRESHARED_KEY=redacted
      - FIREWALL_OUTBOUND_SUBNETS=192.168.0.0/24
      - FIREWALL_VPN_INPUT_PORTS=23949,32400,44109
      - DNS_ADDRESS=10.255.255.1
      - DOT=off
      - BLOCK_MALICIOUS=off
```

Thank you!
