### DISCUSSION TITLE
Double VPN with bounce to hide public ip

### DISCUSSION THREAD

**Discussion by Paulpatou** [qdm12/gluetun#1709] [Q&A]
I'm trying to configure two vpn simultaneously with two Gluetun containers via network_mode: "service:gluetun" .
The aim is for VPN 2 not to know the public IP of the client connecting.
VPN 1: OpenVPN/Wireguard consumer 
VPN 2: self-hosted Wireguard 
Here's the diagram:
![image](https://github.com/qdm12/gluetun/assets/33478981/34de2f4b-7da4-4a59-b9e4-c45bc35c1cc1)

I've encountered several errors that I've already corrected
such as:
Changing the port for HTTP_CONTROL_SERVER_ADDRESS and HEALTH_SERVER_ADDRESS   

Now I'm stuck on 

Log VPN1

```
WARN [dns over tls] cannot update files: Get "https://www.internic.net/domain/named.root": dial tcp: lookup www.internic.net on 1.1.1.1:53: read udp 10.67.34.51:49712->1.1.1.1:53: i/o timeout
```
Log VPN2
```
INFO [healthcheck] program has been unhealthy for
ERROR [vpn] cannot add route for interface: adding route for link wg2, destination 0.0.0.0/0 and table 51820: file exists

```

Example docker-compose.yml
```
version: "3"
services:
  vpn1:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=################################
      - VPN_ENDPOINT_PORT=52000
      - WIREGUARD_PUBLIC_KEY=################################
      - WIREGUARD_PRIVATE_KEY=################################
      - WIREGUARD_ADDRESSES=################################
      - WIREGUARD_INTERFACE=wg1

    restart: unless-stopped

  vpn2:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=################################
      - VPN_ENDPOINT_PORT=51820
      - WIREGUARD_PUBLIC_KEY=################################
      - WIREGUARD_PRIVATE_KEY=################################
      - WIREGUARD_ADDRESSES=################################
      - WIREGUARD_INTERFACE=wg2
      - HTTP_CONTROL_SERVER_ADDRESS=:8001
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9998
    network_mode: "service:vpn1"

```

Has anyone ever tried this solution and do you think it's feasible?
