### DISCUSSION TITLE
Unable to connect between VPN and Non-VPN'd containers - Likely subnet confusion

### DISCUSSION THREAD

**Discussion by Jacksaur** [qdm12/gluetun#1744] [Q&A]
Got a bunch of containers within the same Compose file running under Gluetun properly. They recieve a VPN IP and can connect to the internet fine. I can also connect to all containers through my LAN.
Problem is, non-VPN containers can't seem to access those same VPN containers in the compose file. From what I've read, the option I need is FIREWALL_OUTBOUND_SUBNETS, but I'm utterly clueless when it comes to network stuff so I have no idea what I actually need to enter there.

I tried the subnet listed in docker network inspect bridge, I tried docker network inspect host but that didn't give a subnet at all, I tried 127.0.0.0/8 but no effect.  I also tried 192.168.0.0/24, since I believe that's my local subnet, that causes Gluetun to crash. Terminal lists the docker network interface as using the IP of 172.17.0.1, but trying that also causes Gluetun to crash.

I'm probably going to make some people cringe with how I'm fumbling my way through this with probably the completely wrong idea of it all: But I've googled around and I can't find any concrete answers on the actual subnet I need to enter. How can I find the subnet that I need to enter, to allow non-VPN'd containers to communicate with the VPN'd ones?

Snippet of my compose:

```
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: unless-stopped
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - FIREWALL_OUTBOUND_SUBNETS=
      - WIREGUARD_PRIVATE_KEY=${WGUARD_KEY}
      - WIREGUARD_ADDRESSES=${WGUARD_ADDR}
      - SERVER_COUNTRIES=france
      - SERVER_CITIES=marseille
    volumes:
      - ${ROOT}/Gluetun:/gluetun
    ports:
      - 3000:3000 #Firefox
      - 3001:3001 #Firefox
      - 9696:9696 #Prowlarr

  firefox:
    container_name: firefox
    image: lscr.io/linuxserver/firefox:latest
    network_mode: "service:gluetun"
    volumes:
      - ${ROOT}/Firefox:/config
    shm_size: "1gb"

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    volumes:
      - ${ROOT}/Prowlarr:/config
      - ${ROOT}/Downloads:/downloads
    network_mode: "service:gluetun"

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - 8989:8989
    volumes:
      - ${ROOT}/config/sonarr:/config
      - ${ROOT}/library/TV:/tv
      - ${ROOT}/downloads:/downloads
```

The Firefox container can access ipleak.net, and show that it is recieving a VPN IP. It can also reach Prowlarr at localhost:9696. It cannot reach Sonarr at localhost:8989, it fails every time.  
A separate device on the LAN can access all three containers without issue.
