### DISCUSSION TITLE
Did I set something up wrong? Gluetun with norvpn using wireguard constantly moves between healthy and unhealthy

### DISCUSSION THREAD

**Discussion by uglyfish333** [qdm12/gluetun#1750] [Q&A]
Trying to set up a docker container to handle nordvpn and gluetun and it seems as soon as a connection is formed it's dropped, then it eventually tries a new server. Here's a snippet:

```
gluetun           | 2023-07-15T07:33:11Z INFO [healthcheck] healthy!
gluetun           | 2023-07-15T07:34:01Z INFO [healthcheck] unhealthy: dialing: dial tcp4: lookup cloudflare.com: i/o timeout
gluetun           | 2023-07-15T07:34:02Z INFO [healthcheck] healthy!
gluetun           | 2023-07-15T07:34:10Z INFO [healthcheck] unhealthy: dialing: dial tcp4: lookup cloudflare.com: i/o timeout
gluetun           | 2023-07-15T07:34:12Z INFO [healthcheck] healthy!
gluetun           | 2023-07-15T07:34:28Z INFO [healthcheck] unhealthy: dialing: dial tcp4: lookup cloudflare.com: i/o timeout
gluetun           | 2023-07-15T07:34:36Z INFO [healthcheck] program has been unhealthy for 6s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
gluetun           | 2023-07-15T07:34:36Z INFO [vpn] stopping
gluetun           | 2023-07-15T07:34:36Z INFO [vpn] starting
gluetun           | 2023-07-15T07:34:36Z INFO [firewall] allowing VPN connection...
gluetun           | 2023-07-15T07:34:36Z INFO [wireguard] Using available kernelspace implementation
gluetun           | 2023-07-15T07:34:36Z INFO [wireguard] Connecting to 84.247.0.20:51820
gluetun           | 2023-07-15T07:34:36Z INFO [wireguard] Wireguard is up
gluetun           | 2023-07-15T07:34:46Z INFO [healthcheck] healthy!
gluetun           | 2023-07-15T07:34:47Z INFO [ip getter] Public IP address is 86.104.20.188 (France, Île-de-France, Paris)
gluetun           | 2023-07-15T07:34:54Z INFO [healthcheck] unhealthy: dialing: dial tcp4: lookup cloudflare.com: i/o timeout
gluetun           | 2023-07-15T07:34:57Z INFO [healthcheck] healthy!
gluetun           | 2023-07-15T07:35:27Z INFO [healthcheck] unhealthy: dialing: dial tcp4: lookup cloudflare.com: i/o timeout
gluetun           | 2023-07-15T07:35:29Z INFO [healthcheck] healthy!
gluetun           | 2023-07-15T07:35:45Z INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
gluetun           | 2023-07-15T07:35:48Z INFO [healthcheck] healthy!
gluetun           | 2023-07-15T07:35:56Z INFO [healthcheck] unhealthy: dialing: dial tcp4: lookup cloudflare.com: i/o timeout
gluetun           | 2023-07-15T07:36:04Z INFO [healthcheck] program has been unhealthy for 6s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
gluetun           | 2023-07-15T07:36:04Z INFO [vpn] stopping
gluetun           | 2023-07-15T07:36:04Z INFO [vpn] starting
gluetun           | 2023-07-15T07:36:04Z INFO [firewall] allowing VPN connection...
gluetun           | 2023-07-15T07:36:04Z INFO [wireguard] Using available kernelspace implementation
gluetun           | 2023-07-15T07:36:04Z INFO [wireguard] Connecting to 82.180.151.37:51820
gluetun           | 2023-07-15T07:36:04Z INFO [wireguard] Wireguard is up
gluetun           | 2023-07-15T07:36:10Z INFO [ip getter] Public IP address is 193.42.99.83 (Poland, Mazovia, Warsaw)
gluetun           | 2023-07-15T07:36:10Z INFO [healthcheck] healthy!

```

Here's my compose:

 
    
```
version: "3.5"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8089:8089/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /home/lol/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=-------------
      - DNS_ADDRESS=1.1.1.1 #testing - cloudflare, should support tls
    healthcheck:
      disable: true #doesnt seem to work

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    network_mode: "service:gluetun"
    container_name: QbitTorrent-Nord
    depends_on:
      - gluetun
    environment:
      - WEBUI_PORT=8089
      - PUID=1000
      - PGID=1000
      - TZ=US/Central
    volumes:
      - /home/lol/qbit-nord/config:/config
      - /home/lol/Downloads/torrents:/downloads
    restart: unless-stopped

```

any help would be appreciated. been at this for hours and just can't seem to sort it out.

**Comment by niravjdn** [comment]
I think it might be due to missing WIREGUARD_ADDRESSES in environment,

below is my compose file if you can checkout if it works.

Try to use pulling latest image also.

```
version: "3.3"
services:
  nordvpn:
    container_name: GlueTun-Nord
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:    
      - "8089:8089" # QbitTorrent UI
      - "51420:51420" # QbitTorrent
      - "51420:51420/udp" # QbitTorrent
      #- "9092:9091" # Transmission
      #- "51413:51413" # Transmision
      #- "51413:51413/udp" # Transmision  
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      #- OPENVPN_USER=openvpn_username
      #- OPENVPN_PASSWORD=openvpn_password
      - WIREGUARD_PRIVATE_KEY=KEY
      - WIREGUARD_ADDRESSES=10.x.x.x/32
      - SERVER_REGIONS=Canada
      - TZ=America/Toronto
      - VPN_TYPE=wireguard
    restart: always
  qbittorrent:
    image: linuxserver/qbittorrent:4.5.2
    network_mode: "service:nordvpn"
    container_name: QbitTorrent-VPN
    depends_on:
      - nordvpn
    environment:
      - WEBUI_PORT=8089
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - "/DATA/AppData/qBittorrent-VPN/config:/config"
      - "/media/LocalDrive/Downloads/QBitTorrent:/downloads"
    restart: unless-stopped
  #transmission:
  #  image: ghcr.io/linuxserver/transmission:4.0.2
  #  network_mode: "service:nordvpn"
  #  container_name: Transmission-VPN
  #  depends_on:
  #    - nordvpn
  #  environment:
  #    - PUID=1000
  #    - PGID=1000
  #    - TZ=America/Toronto
  #   - PEERPORT=51413
  # volumes:
  #   - "/DATA/AppData/Transmission-VPN/config:/config"
  #   - "/media/LocalDrive/Downloads/Transmission:/downloads"
  #   - "/media/LocalDrive/Downloads/Transmission/watch:/watch"
  # 
  # restart: unless-stopped
  
```
