### DISCUSSION TITLE
Can't get connection using wireguard

### DISCUSSION THREAD

**Discussion by Moret84** [qdm12/gluetun#1766] [Q&A]
Hi, I can't manage getting connection wth wireguard.   
Here is my docker-compose:

```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
        - 2817:2817/tcp 
        - 49166:49166 
        - 6881:6991/udp 
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
    container_name: gluetun
    volumes:
      - ./wireguard/wg0.conf:/gluetun/wireguard/wg0.conf
```

And my wg0.conf:  
```
[Interface]
PrivateKey = *******
ListenPort = 254
Address = 10.10.1.184/32
DNS = 10.100.0.1

[Peer]
PublicKey = ****************
PresharedKey = ************
AllowedIPs = 0.0.0.0/0
Endpoint = 195.154.204.36:254
PersistentKeepalive = 25
```

The provider is VPN unlimited.
The exact same wg0.conf works as expected with [linuxserver/docker-wireguard](https://github.com/linuxserver/docker-wireguard). 
Could someone help me finding out the point that I am missing ?
