### DISCUSSION TITLE
How to reach a container behind the gluetun vpn in kubernetes

### DISCUSSION THREAD

**Discussion by isdigital-github** [qdm12/gluetun#1771] [Q&A]
Hi all, nice to see so helpful community here.

I have one task to accomplish and for several days I try with no success. I've established a custom vpn connection from gluetun to my private wireguard vpn server and it works very well.

The task that I need to solve is to send the requests from a small proxy nodejs app through that vpn connection to our test api server.
I.e. that proxy app should be reachable on port 4000 where it listens to incoming requests and then it should send them over the gluetun vpn connection.

I've tried to put the proxy and gluetun containers in the same pod, the proxy sends test requests through gluetun very well, but its port 4000 is not reachable from outside of the pod (I assume because gluetun changes the pod's networking setup)

How do I make the proxy app to be reachable by other pods in the cluster? Maybe there's an option where I could split gluetun and the proxy app into different pods, so that the proxy app would still forward the incoming requests through gluetun? What am I doing wrong?

Here is my current manifest, which makes the proxy app unreachable:

```
apiVersion: apps/v1
kind: Deployment
metadata:
    name: gluetun
    labels:
        app: gluetun
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gluetun
    template:
        metadata:
            labels:
                app: gluetun
        spec:
            volumes:
                - name: wireguard-config
                  secret:
                      secretName: wg0-config
            containers:
                - name: gluetun
                  image: qmcgaw/gluetun
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 4000
                  securityContext:
                      capabilities:
                          add:
                              - NET_ADMIN
                  volumeMounts:
                      - name: wireguard-config
                        mountPath: /gluetun/wireguard
                  env:
                      - name: HTTPPROXY
                        value: 'ON'
                      - name: EXTRA_SUBNETS
                        value: 192.168.0.0/16
                      - name: VPN_SERVICE_PROVIDER
                        value: 'custom'
                      - name: VPN_TYPE
                        value: 'wireguard'
                      - name: VPN_ENDPOINT_IP
                        valueFrom:
                            secretKeyRef:
                                name: wg0-config
                                key: Endpoint
                      - name: VPN_ENDPOINT_PORT
                        valueFrom:
                            secretKeyRef:
                                name: wg0-config
                                key: EndpointPort
                      - name: WIREGUARD_PUBLIC_KEY
                        valueFrom:
                            secretKeyRef:
                                name: wg0-config
                                key: PublicKey
                      - name: WIREGUARD_PRIVATE_KEY
                        valueFrom:
                            secretKeyRef:
                                name: wg0-config
                                key: PrivateKey
                      - name: WIREGUARD_ADDRESSES
                        valueFrom:
                            secretKeyRef:
                                name: wg0-config
                                key: Address
                      - name: WIREGUARD_PRESHARED_KEY
                        valueFrom:
                            secretKeyRef:
                                name: wg0-config
                                key: PresharedKey
# The proxy app container here ########################
                - name: proxy
                  image: test-proxy-dev:latest
                  imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
    name: proxy-svc
spec:
    selector:
        app: gluetun
    ports:
        - protocol: TCP
          port: 4000
          targetPort: 4000
```

My greatest thanks if you can help to solve this!!!
