### DISCUSSION TITLE
Gluetun, VPS, and Reverse Proxy Issue

### DISCUSSION THREAD

**Discussion by IronicMango** [qdm12/gluetun#1772] [Q&A]
Recently found gluetun, and pumped about the possibilities. I may be missing something obvious but I'm having a little bit of trouble, so please be patient, but hopefully this is easy.

I'm attempting to expose services on my local network through gluetun to the internet using a VPS to avoid opening ports in my home network. The VPS has a wireguard server, and already hosts a site so it already has SWAG (fancy nginx) running as well. I'm trying to run jellyfin on my home network through gluetun to connect to the VPS, then reverse proxy a subdomain to the gluetun/jellyfin container. Gluetun is showing as healthy, the VPS is working, and jellyfin is still running properly after moving it to gluetun's network.

**Problem:**
How would the reverse proxy work to reach jellyfin? I thought I could essentially use the following:
```
set $gluetun_ip x.x.x.x;
proxy_pass http://$gluetun_ip:8096;
```
But that doesn't seem to work. If that's the proper method then I just need to troubleshoot my nginx config which doesn't belong here, but I think my issue is with actually reaching the gluetun container

**Relevant Info:**

docker-compose.yml
```
Version: "3.7"
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: "service:gluetun"
    volumes:
      - /path/to/jellyfin/config:/config
      - /path/to/jellyfin/cache:/cache
      - /path/to/jellyfin/media:/media
    restart: 'unless-stopped'
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=X.X.X.X #VPS address
      - VPN_ENDPOINT_PORT=51820
      - FIREWALL_VPN_INPUT_PORTS=8096
      - WIREGUARD_PUBLIC_KEY=**Redacted**
      - WIREGUARD_PRIVATE_KEY=**Redacted**
      - WIREGUARD_PRESHARED_KEY=**Redacted**
      - WIREGUARD_ADDRESSES=X.X.X.X/X
    ports:
      - 8096:8096/tcp
      - 8920:8920/tcp
      - 1900:1900/udp
      - 7359:7359/udp
```
