### DISCUSSION TITLE
2 instances of qBittorrent with gluetun, 2nd one does not connect

### DISCUSSION THREAD

**Discussion by nigiriemoji** [qdm12/gluetun#1779] [Q&A]
Hello, I use gluetun to connect 2 instances of qBittorrent (one for private tracker and one for public) but some reason the first container to connect to gluetun works but the second instance of qBit does not. I can stop one of my qBit instances and the other will work and vice versa. I just can't get both to work for some reason. My 2nd instance of qbittorrent shows as not being able to contact any trackers. I can look at the webUI for BOTH instances, but the internet connection beyond that just doesn't work for 2nd.

I'm not sure what's going on here, below is my docker-compose. I hope I can improve on it somehow. Both qBittorrent use the same # port that came from port forwarding in PIA

```
  qbittorrent:
    container_name: qbittorrent
    image: cr.hotio.dev/hotio/qbittorrent
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=002
      - TZ=America/Los_Angeles
      - WEBUI_PORTS=8080
    network_mode: service:gluetun
    volumes:
      - ./qbittorrent:/config
      - /srv/dev-disk-by-HDD1/downloads:/14TB/downloads
      - /srv/dev-disk-by-HDD2/downloads:/8TB/downloads
      - /Music:/Music
      - ./gluetun/:/gluetun:ro
    restart: unless-stopped
    cpus: '2'
    mem_limit: 2g
  qbittorrentTL:
    container_name: qbittorrentTL
    image: cr.hotio.dev/hotio/qbittorrent
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=002
      - TZ=America/Los_Angeles
      - WEBUI_PORTS=8082
    network_mode: service:gluetun
    volumes:
      - ./qbittorrentTL:/config
      - /srv/dev-disk-by-HDD1/downloads:/14TB/downloads
      - /srv/dev-disk-by-HDD2/downloads:/8TB/downloads
      - /Music:/Music
      - ./gluetun/:/gluetun:ro
    restart: unless-stopped
    cpus: '2'
    mem_limit: 2g
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080
      - 8082:8082
    volumes:
      - ./gluetun:/gluetun
    environment:
      - PUID=1000
      - PGID=100
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=XXXXXXXXXX
      - OPENVPN_PASSWORD=XXXXXXXX
      - SERVER_REGIONS=XXXXXXXXXXXXXXXXXXXX
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_STATUS_FILE=/gluetun/forwarded_port
    restart: always
    cpus: '2'
    mem_limit: 2g
```
