### DISCUSSION TITLE
Additional networks no longer showing up when network_mode: "container:gluetun" is used.

### DISCUSSION THREAD

**Discussion by tarchive** [qdm12/gluetun#1792] [Q&A]
I just want to start off by saying that this was working perfectly but it stopped after i updated the gluetun container and gluetun_default network.

service_a - Has access to local internet via "lan" and access to isolated network "myisonet"
service_b - Has access to vpn internet via "container:gluetun" and access to isolated network "myisonet"

This was my compose file i was testing with. Nothing has changed here.
```version: '3'
services:
  service_a:
    image: jonlabelle/network-tools
    command: tail -f /dev/null
    networks:
      myisonet:
        aliases:
          - "service_a"
      lan:

  service_b:
    image: jonlabelle/network-tools
    command: tail -f /dev/null 
    networks:
      myisonet:
        aliases:
          - "service_b"
    network_mode: "container:gluetun"

networks:
  myisonet: # isolated
    external: true
  lan:
    external: true
```

Gluetun compose - Never changed here either. This exactly what was used when it was working before.
```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8388:8388/tcp" # Shadowsocks
      - "8388:8388/udp" # Shadowsocks
    volumes:
      - /mnt/data/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=REDACTED
      - OPENVPN_PASSWORD=REDACTED
      - SERVER_REGIONS=REDACTED
    restart: always
```

Relevent networks 
lan                   - 172.18.0.0/16 172.18.0.1
myisonet         - 172.28.0.0/16 172.28.0.1
gluetun_default - 192.168.0.0/20 192.168.0.1

As i said, this all worked perfectly until I updated and recreated the gluetun container/network. Each service had the correct internet access and was able to communicate between each other with the defined aliases.

So now if i set network_mode: "container:gluetun" then service_b will no longer join the "myisonet". 
Looking at the ifconfig output i can see the network is no longer listed. I would expect there to be an eth1 
```
service_b:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:C0:A8:00:02  
          inet addr:192.168.0.2  Bcast:192.168.15.255  Mask:255.255.240.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5789 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3119 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:6858070 (6.5 MiB)  TX bytes:524421 (512.1 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:3471 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3471 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:255271 (249.2 KiB)  TX bytes:255271 (249.2 KiB)

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.18.XXX.XXX  P-t-P:10.18.XXX.XXX  Mask:255.255.255.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:5664 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3015 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:6222191 (5.9 MiB)  TX bytes:196508 (191.9 KiB)

service_b:/# 
```

If i remove "container:gluetun" from service_b then "myisonet" will connect and can communicate with service_a, but now i obviously don't have vpn internet anymore.
```
service_b:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:1C:00:03  
          inet addr:172.28.0.3  Bcast:172.28.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:586 (586.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

service_b:/#
```

I reverted back to the original image from  2023-05-24T21:51:12.297Z (commit 1827a03) which seems to be removed from dockerhub(?) so luckily i still had a local copy cached to retest. Unfortunately it still does not work like before.

I this point I'm at a loss why something as simple as this is no longer working. 
I really don't know where or what the issue is. Networking is my strong suit so I'd appreciate any help. Thanks

**Comment by tarchive** [comment]
I've been doing some research on the issue and I'm seeing many similar question which the answer is "it's not possible" so i am really confused and wondering if something was borked in my networks that allowed it to work and was "fixed" when they were recreated. 

With that reality looming I've decided to try and get it to work again with a different method. 
I found that when i add "myisonet" to gluetun's networks, that my service_b container will now show "myisonet" again!
```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8388:8388/tcp" # Shadowsocks
      - "8388:8388/udp" # Shadowsocks
    networks:
      myisonet:
      glutun_default:
    volumes:
      - /mnt/data/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=REDACTED
      - OPENVPN_PASSWORD=REDACTED
      - SERVER_REGIONS=REDACTED
    restart: always
networks:
  myisonet: # isolated
    external: true
  glutun_default:
    external: true
```

No changes made to the service compose file. Just recreated service containers after updating the gluetun container.
Now i have myisonet as eth1 in service_b
```
service_b:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:C0:A8:00:02  
          inet addr:192.168.0.2  Bcast:192.168.15.255  Mask:255.255.240.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5363 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2992 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:6786852 (6.4 MiB)  TX bytes:504059 (492.2 KiB)

eth1      Link encap:Ethernet  HWaddr 02:42:AC:1C:00:03  
          inet addr:172.28.0.3  Bcast:172.28.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:10 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:796 (796.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:291 errors:0 dropped:0 overruns:0 frame:0
          TX packets:291 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:22071 (21.5 KiB)  TX bytes:22071 (21.5 KiB)

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.1.XXX.XXX  P-t-P:10.1.XXX.XXX  Mask:255.255.255.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:5319 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2958 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:6204719 (5.9 MiB)  TX bytes:188317 (183.9 KiB)

service_b:/#
```
The only problem with this is that aliases on myisonet don't work. IP's do though.
```
service_b:/# ping service_a
ping: service_a: Name does not resolve
service_b:/# ping 172.28.0.2
PING 172.28.0.2 (172.28.0.2) 56(84) bytes of data.
64 bytes from 172.28.0.2: icmp_seq=1 ttl=64 time=0.117 ms
64 bytes from 172.28.0.2: icmp_seq=2 ttl=64 time=0.062 ms
64 bytes from 172.28.0.2: icmp_seq=3 ttl=64 time=0.063 ms
```

From service_a. First test that it's alias works
```
service_a:/# ping service_a
PING service_a (172.18.0.2) 56(84) bytes of data.
64 bytes from service_a (172.18.0.2): icmp_seq=1 ttl=64 time=0.037 ms
64 bytes from service_a (172.18.0.2): icmp_seq=2 ttl=64 time=0.050 ms
^C
--- service_a ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1018ms
rtt min/avg/max/mdev = 0.037/0.043/0.050/0.006 ms
```
now ping service_b
```
service_a:/# ping service_b
ping: service_b: Try again
```
no alias but ip works
```
service_a:/# ping 172.28.0.3
PING 172.28.0.3 (172.28.0.3) 56(84) bytes of data.
64 bytes from 172.28.0.3: icmp_seq=1 ttl=64 time=0.110 ms
64 bytes from 172.28.0.3: icmp_seq=2 ttl=64 time=0.094 ms
64 bytes from 172.28.0.3: icmp_seq=3 ttl=64 time=0.068 ms
^C
--- 172.28.0.3 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2026ms
rtt min/avg/max/mdev = 0.068/0.090/0.110/0.017 ms
```

I also tried setting an alias in gluetun but that didn't work either. Seems aliases are completely disabled/removed in service_b. 
Everything works fine as soon as  `network_mode: "container:gluetun"` is removed from service_b but then i don't have vpn internet access.

So it's technically possible with what i learned so far. You just have to assign every network you plan to use to gluetun and then only use ip addresses to point to other containers. 

Unfortunately that's not a solution in my case because the reason i have this service compose file is that i was testing this idea for a much larger project deployment. After confirming everything worked as expected I was excited and went ahead restructured my project expecting this to work as tested. 
Even though i found a workaround, it just does not scale with my project anymore and can't be used without redoing a lot of things, again. I'm really kicking myself for updating. Wouldn't be so bad if i didn't know it was possible.

Nonetheless I'm determined to find the solution and will keep trying different things. sorry for the ramble.
