### DISCUSSION TITLE
ProtonVPN Port Forwarding Static Port

### DISCUSSION THREAD

**Discussion by scott-mitchell-0023** [qdm12/gluetun#1846] [Q&A]
Hi Guys,

Great work on Gluten.  This is the first time I have experienced an issue I couldn't resolve since I started using the product, which is a fantastic result.

I am trying to set up ProtonVPN with a forwarded port of 53000. Is there a way to do this? All I could find was "VPN_PORT_FORWARDING = on" and that seems to result in a random port being chosen.

The docker-compose.yaml file is as follows:

```
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      t2_proxy:
        ipv4_address: 192.168.100.241
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "8081:8080" # Exposing qBittorrent through Docker Host LAN IP
      - "8989:8989" # Sonarr
      - "7878:7878" # Radarr
      - "9117:9117" # Jackett
    # #   - 8888:8888/tcp # HTTP proxy
    # #   - 8388:8388/tcp # Shadowsocks
    # #   - 8388:8388/udp # Shadowsocks
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=$OPENVPN_USER
      - OPENVPN_PASSWORD=$OPENVPN_PASSWORD
      - SERVER_COUNTRIES=Netherlands
      - SERVER_HOSTNAMES=node-nl-01.protonvpn.net
      - VPN_PORT_FORWARDING=on
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.gluetun-qbittorrent-rtr.entrypoints=https"
      - "traefik.http.routers.gluetun-qbittorrent-rtr.rule=Host(`qbit.$DOMAIN`)" # qBittorrent
      - "traefik.http.routers.gluetun-sonarr-rtr.entrypoints=https"
      - "traefik.http.routers.gluetun-sonarr-rtr.rule=Host(`sonarr.$DOMAIN`)"
      - "traefik.http.routers.gluetun-radarr-rtr.entrypoints=https"
      - "traefik.http.routers.gluetun-radarr-rtr.rule=Host(`radarr.$DOMAIN`)"
      - "traefik.http.routers.gluetun-jackett-rtr.entrypoints=https"
      - "traefik.http.routers.gluetun-jackett-rtr.rule=Host(`jackett.$DOMAIN`)"
      - "traefik.http.routers.gluetun-readarr-rtr.entrypoints=https"
      - "traefik.http.routers.gluetun-readarr-rtr.rule=Host(`readarr.$DOMAIN`)"
      ## Middlewares
      - "traefik.http.routers.gluetun-qbittorrent-rtr.middlewares=chain-oauth@file" # qBittorrent
      - "traefik.http.routers.gluetun-sonarr-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.gluetun-radarr-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.gluetun-jackett-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.gluetun-readarr-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.gluetun-qbittorrent-rtr.service=gluetun-qbittorrent-svc" # qBittorrent
      - "traefik.http.services.gluetun-qbittorrent-svc.loadbalancer.server.port=8080" # qBittorrent
      - "traefik.http.routers.gluetun-sonarr-rtr.service=gluetun-sonarr-svc"
      - "traefik.http.services.gluetun-sonarr-svc.loadbalancer.server.port=8989"
      - "traefik.http.routers.gluetun-radarr-rtr.service=gluetun-radarr-svc"
      - "traefik.http.services.gluetun-radarr-svc.loadbalancer.server.port=7878"
      - "traefik.http.routers.gluetun-jackett-rtr.service=gluetun-jackett-svc"
      - "traefik.http.services.gluetun-jackett-svc.loadbalancer.server.port=9117"
      - "traefik.http.routers.gluetun-readarr-rtr.service=gluetun-readarr-svc"
      - "traefik.http.services.gluetun-readarr-svc.loadbalancer.server.port=8787"
```
