### DISCUSSION TITLE
VPN Unlimited problem

### DISCUSSION THREAD

**Discussion by tenwa** [qdm12/gluetun#1873] [Q&A] [answered]
I've just tried to use gluetun, to connect to a VPN Unlimited server, looking at both the sample compose format, mixed with the sample VPN unlimited compose data, i ended up with

```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    environment:
      - VPN_SERVICE_PROVIDER=vpn unlimited
      - VPN_TYPE=openvpn
      - OPENVPN_USER=xxxx
      - OPENVPN_PASSWORD=xxxx
      - SERVER_COUNTRIES=Canada,Netherlands
    volumes:
      - /home/tim24e/data/gluetun:/gluetun

```
But when I try to up the docker I am getting the following output

```
gluetun-gluetun-1  | 2023-09-20T10:53:57Z INFO [routing] default route found: interface eth0, gateway 172.21.0.1, assigned IP 172.21.0.2 and family v4
gluetun-gluetun-1  | 2023-09-20T10:53:57Z INFO [routing] local ethernet link found: eth0
gluetun-gluetun-1  | 2023-09-20T10:53:57Z INFO [routing] local ipnet found: 172.21.0.0/16
gluetun-gluetun-1  | 2023-09-20T10:53:57Z INFO [firewall] enabling...
gluetun-gluetun-1  | 2023-09-20T10:53:57Z INFO [firewall] enabled successfully
gluetun-gluetun-1  | 2023-09-20T10:53:58Z INFO [storage] merging by most recent 17689 hardcoded servers and 17689 servers read from /gluetun/servers.json
gluetun-gluetun-1  | 2023-09-20T10:53:58Z ERROR VPN settings: OpenVPN settings: client certificate: missing value
gluetun-gluetun-1  | 2023-09-20T10:53:58Z INFO Shutdown successful
gluetun-gluetun-1 exited with code 1

```
Is there something I'm missing from the compose file to get this working?
