### DISCUSSION TITLE
How to map all ports of a Docker container to gluetun containers vpn client?

### DISCUSSION THREAD

**Discussion by vybraan** [qdm12/gluetun#1927] [Q&A]
I have a Docker Compose file that sets up a small lab with two VPN client containers and two application containers. I want to map all ports of the vpn_network1 network to the application1 container, all ports of the vpn_network2 network to the application2 container so that everyone on the VPN network can reach the containers.

example
```
version: "3"
services:
  vpn_client1:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=vpn-server-ip
      - VPN_ENDPOINT_PORT=51820
      - WIREGUARD_PUBLIC_KEY= my-key
      - WIREGUARD_PRIVATE_KEY= my-key
      - WIREGUARD_PRESHARED_KEY= my-key
      - WIREGUARD_ADDRESSES=10.8.0.2/24
  vpn_client2:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP= vpn-server-ip
      - VPN_ENDPOINT_PORT=51820
      - WIREGUARD_PUBLIC_KEY= my-key
      - WIREGUARD_PRIVATE_KEY= my-key
      - WIREGUARD_PRESHARED_KEY= my-key
      - WIREGUARD_ADDRESSES=10.8.0.3/24
  application2:
    depends_on:
      - vpn_client2
    image: user/someimage
    container_name: application2
    network_mode: "service:vpn_client2"
  application1:
    depends_on:
      - vpn_client1
    image: user/someimage
    container_name: application1
    network_mode: "service:vpn_client1"
    command: /bin/services.sh && bash
```
When using a different machine (10.8.0.4) on the VPN network, I aim to communicate with Application 1 or 2 from the VPNs network. However, when accessing 10.8.0.3, the connection is directed to Application2.

The overall idea is to construct a laboratory comprising several containers and provide exclusive access to the containers via a specified VPN network to ensure that only VPN users can access the lab, without exposing the host machine.

I attempted to publish the ports from the VPN client container, but it resulted in mapping them to the host's ports, which is not what I intended. I want the ports to be mapped from app containers to their specific VPN client IP and restricted to the VPN network.
