### DISCUSSION TITLE
Strange issue between 2 Wireguard machines on gluetun connect

### DISCUSSION THREAD

**Discussion by hugalafutro** [qdm12/gluetun#1951] [Q&A]
Hi,
I have a strange issue between 2 machines

Machine A: hetzner cloud, running qbittorrent via gluetun (mullvad, london)
Machine B: home computer, running mullvad client on win64, london as well

Whenever I reboot Machine A or rebuild/restart the gluetun stack, Machine B loses all connectivity to any service running on Machine A. Disconnecting Machine B from VPN, or reconnecting Machine B's mullvad client to a london server DIFFERENT from the one it's on immediately restores connection

I'm struggling with where to even begin trying to investigate this, any advice welcome. 
Thanks!

for reference the gluetun stack from Machine A:
```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 20143:20143
    volumes:
      - ./gluetun-data:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=[REDACTED]
      - WIREGUARD_ADDRESSES=[REDACTED]
      - FIREWALL_VPN_INPUT_PORTS=[REDACTED]
      - SERVER_CITIES=London
      - OWNED=yes
    restart: "unless-stopped"

  qbittorrent-vpn:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent_vpn
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=20143
    volumes:
      - ./qbittorrent-config:/config
      - /mnt/torrents:/downloads
    restart: "unless-stopped"
```
