### DISCUSSION TITLE
Mullvad Wireguard, hijack_dns, Unbound Recursive

### DISCUSSION THREAD

**Discussion by ezekieldas** [qdm12/gluetun#1954] [Q&A]
I recently did a trial of Mullvad VPN service and had difficulties with gluetun, Wireguard, Unbound (as recursive). One of the primary reasons I had trouble is because Mullvad employs 'DNS Hijack' by default. It took time to realize and circumvent this obstacle. Shown below are details on how to first verify a successful Mullvad/Wireguard connection using DNS forwarding (the gluetun default), then disable DNS Hijack per your account / public key, and ultimately run the configuration with and Unbound recursive configuration. 

Also important to note, applying to Unbound recursive use in general, is gluetun by default has trouble returning UDP packets without the `interface-automatic: yes` option in Unbound. See https://github.com/NLnetLabs/unbound/issues/960 and https://github.com/qdm12/gluetun/issues/1929 

## Mullvad Wireguard Configuration (simple)

With Mullvad, Wireguard configuration of keys is done in **the Devices section of the Account page**. At the time of this writing, it is here: https://mullvad.net/en/account/devices. This is separate and distinct from the WireGuard configuration page, which leads to an unusual 'Generate a WireGuard key' function, the download of config files, and unsatisfactory results. I strongly suggest creating keys with `wg` (from `wireguard-tools`) and uploading the public key to the Devices page noted here. 

Begin with a minimal configuration like the one shown here: 

https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/mullvad.md

To get the ip address for `WIREGUARD_ADDRESSES` use:

```
curl https://api.mullvad.net/www/accounts/<MULLVAD_ACCOUNT_NUMBER> 
... "ipv4_address":"10.14.1.13/32" ... 
```

This should provide all necessary values for creating a successful Wireguard connection. 

## Mullvad Disable `hijack_dns`

To use Unbound as recursive DNS as shown below, it may be necessary to disable the default Mullvad feature of `hijack_dns`.

This script was inspired by Michael Schnerring's writing on [Use Custom DNS Servers With Mullvad...](https://schnerring.net/blog/use-custom-dns-servers-with-mullvad-and-any-wireguard-client/)

```
#!/bin/bash

# requires wg from wireguard-tools, jq

# be aware of the 5 device limitation. This output may be suppressed from the redirection below. 
# {"detail":"This account already has the maximum number of devices.","code":"MAX_DEVICES_REACHED"}

account_number="1026354772865986"

die() {
	echo "[-] Error: $1" >&2
	exit 1
}

type curl >/dev/null || die "Please install curl and then try again."
type jq >/dev/null || die "Please install jq and then try again."

private_key="$(wg genkey)"
public_key="$(wg pubkey <<<"${private_key}")"

# get access token
access_token=$(curl -s -X POST 'https://api.mullvad.net/auth/v1/token' -H 'accept: application/json' -H 'content-type: application/json' -d '{ "account_number": "'${account_number}'" }' | jq -r .access_token)

# post hijack_dns setting and get device name and ipaddr
jblob=$(curl -s -X POST 'https://api.mullvad.net/accounts/v1/devices' -H "Authorization: Bearer ${access_token}" -H 'content-type: application/json' -d '{"pubkey":"'${public_key}'","hijack_dns":false}')

device_name=$(echo ${jblob} | jq -r .name)
wg_ipaddr=$(echo ${jblob} | jq -r .ipv4_address)

echo "Mullvad Device Name: $(echo -n ${device_name})"
echo "Public Key: $(echo -n ${public_key})"
echo "WIREGUARD_PRIVATE_KEY=$(echo -n ${private_key})"
echo "WIREGUARD_ADDRESSES=$(echo -n ${wg_ipaddr})"
```

## Mullvad Wireguard Configuration (Unbound, Recursive)

For this to function it's most likely necessary to disable hijack_dns as shown previously. Also be aware of the `interface-automatic: yes` option as mentioned earlier. 

Note the few differences between the following docker-compose.yml and the minimal configuration as previously shown. The `WIREGUARD_ADDRESSES` shown here is fictitious and should be produced with the Mullvad API as shown earlier. 

Also, I have no strong technical argument for the use of: `dns: 127.0.0.1`, `- DOT=off`, `- DNS_KEEP_NAMESERVER=on` This was developed by partial guesswork and trial/error. However, it has proven to function perfectly without leaks. 

```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=<MY_PRIVATE_KEY>
      - WIREGUARD_ADDRESSES=10.14.1.13/32
      - DOT=off
      - DNS_KEEP_NAMESERVER=on

  unbound:
    image: "mvance/unbound:latest"
    container_name: unbound
    volumes:
      - ./unbound_config/unbound.conf:/opt/unbound/etc/unbound/unbound.conf
      - ./unbound_config/conf.d/:/opt/unbound/etc/unbound/conf.d/
    network_mode: "service:gluetun"
```
