### DISCUSSION TITLE
Certificate Missing Value Error

### DISCUSSION THREAD

**Discussion by justinroberson** [qdm12/gluetun#1956] [Q&A]
I'm relatively new to Linux and docker. I set up my QNAP NAS, and successfully got Gluetun running with my CyberGhost credentials using the key/crt files. And, I also got deluge dependent on the VPN. I verified the IP/health and things were looking good.

Anyways, I got stuck when it came to mounting volumes (I wanted to put config files on one volume and the downloads on another) and setting up watched folders with the -arr suite of products. So, I contracted someone to just do it for me. They weren't familiar with gluetun but I assisted them by creating a new device configuration in CyberGhost. He added those files to the config folder (named properly!), but when he was trying to compose he kept running into `ERROR VPN settings: OpenVPN settings: client certificate: missing value`

```
[docker@Media ~]$ sudo docker compose up
Password:
[+] Running 2/0
 ⠿ Container gluetun  Created                                                                                      0.0s
 ⠿ Container deluge   Running                                                                                      0.0s
Attaching to deluge, gluetun
gluetun  | ========================================
gluetun  | ========================================
gluetun  | =============== gluetun ================
gluetun  | ========================================
gluetun  | =========== Made with ❤️ by ============
gluetun  | ======= https://github.com/qdm12 =======
gluetun  | ========================================
gluetun  | ========================================
gluetun  |
gluetun  | Running version latest built on 2023-11-08T10:11:52.918Z (commit 8318be3)
gluetun  |
gluetun  | 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
gluetun  | 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
gluetun  | ✨ New feature? https://github.com/qdm12/gluetun/issues/new
gluetun  | ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
gluetun  | 💻 Email? quentin.mcgaw@gmail.com
gluetun  | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
gluetun  | 2023-11-10T14:33:51-05:00 INFO [routing] default route found: interface eth0, gateway 172.29.4.1, assigned IP 172.29.4.2 and family v4
gluetun  | 2023-11-10T14:33:51-05:00 INFO [routing] local ethernet link found: eth0
gluetun  | 2023-11-10T14:33:51-05:00 INFO [routing] local ipnet found: 172.29.4.0/22
gluetun  | 2023-11-10T14:33:51-05:00 INFO [firewall] enabling...
gluetun  | 2023-11-10T14:33:51-05:00 INFO [firewall] enabled successfully
gluetun  | 2023-11-10T14:33:51-05:00 INFO [storage] merging by most recent 17689 hardcoded servers and 17689 servers read from /gluetun/servers.json
gluetun  | 2023-11-10T14:33:51-05:00 ERROR VPN settings: OpenVPN settings: client certificate: missing value
gluetun  | 2023-11-10T14:33:51-05:00 INFO Shutdown successful
gluetun exited with code 1
```

I verified the files in the config folder were named correctly. I set up a new device in QNAP so these were fresh credentials with OpenVPN configuration. He ended up wanting to go a different route with Proxies but I don't want to do that since I have a dedicated IP address. Anyways, I just need to figure out this issue so that he can finish the work.

Below is the yaml data
```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8112:8112 # deluge
    volumes:
      - /media/configs/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=cyberghost
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=UyhUakWv85
      - OPENVPN_PASSWORD=xRmU4qUgwD
      - SERVER_COUNTRIES="United States"
      - TZ=America/New_York

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=10001
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /media/configs/deluge:/deluge
```

I'm sure it's something so incredibly simple that will bring eternal shame to my bloodline when someone offers a solution, but I just never ran into this issue when I did my first attempt at set up.

I have a Mac and after SSH'ing in on initial set up, just edited the docker compose.yaml directly in QNAP's File Editor along with an .env file for variables. I borrowed my parent's laptop to make it easier for them to remote in and do what he needed to do through command prompt so our approaches are different. Any help at all is appreciated. I've had this QNAP and a newborn for two months and I just don't have the capacity to devote uninterrupted time to the former.
