### DISCUSSION TITLE
IPVanish doesn't work with `SERVER_CITIES` or `SERVER_HOSTNAMES` filters applied

### DISCUSSION THREAD

**Discussion by KierenB** [qdm12/gluetun#1964] [Q&A]
Config:
- gluetun via docker-compose running on a Synology DS916+

## docker-compose snippet
```
gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080 # SABnzbd
      - 8180:8180 #qBittorrent webUI
      - 6881:6881 #qBittorrent
      - 6881:6881/udp #qBittorrent
    volumes:
      - ${DOCKER_DIR}/docker/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=ipvanish
      - OPENVPN_USER=${VPN_user}
      - OPENVPN_PASSWORD=${VPN_password}
      - SERVER_COUNTRIES=Canada
      #- SERVER_CITIES=Vancouver
      #- SERVER_HOSTNAMES=yvr-c15.ipvanish.com,yvr-c08.ipvanish.com,yvr-c09.ipvanish.com, yvr-c10.ipvanish.com,yvr-c11.ipvanish.com,yvr-c12.ipvanish.com,yvr-c13.ipvanish.com
      - TZ=${TZ}
      # Server list updater, see https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=168h #weekly
```

## What happens
- the config above is healthy and working, but connected to a server a long way from me (Montreal, I am in western Canada)
- Gluetun would never go healthy status if I used the `SERVER_CITIES` filter.
- I then tried using only `SERVER_HOSTNAMES` but running `docker-compose up gluetun`  quit the container with the error `ERROR VPN settings: provider settings: server selection: for VPN service provider ipvanish: the hostname specified is not valid`. The list of servers it provided did not match the server list given to me by IPVanish (yvr-c08.ipvanish.com to yvr-c17.ipvanish.com). 

Could it be that Gluetun config is only looking for free servers?

## What I would like to happen
- Why doesn't the `SERVER_CITIES` filter work?
- Why does a mismatch between SERVER_HOSTNAMES kill the container? FWIW I do have auto-update turned on

Is there something I'm doing wrong with the above? Thanks.
