### DISCUSSION TITLE
How to pass a Proton VPN port forward from Gluetun to Transmission (via LinuxServer.io)

### DISCUSSION THREAD

**Discussion by hozza** [qdm12/gluetun#1979] [Q&A]
Can anyone help? I'm looking for someone more savvy with this sort of inter-container config setup or maybe someone has done something similar already.

Once gluetun has got a [forwarded port from Proton VPN](https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/port-forwarding.md), it's saved into the `/tmp/gluetun/forwarded_port` file. 

How could docker-compose read the content of this file, after it's written, and then pass it along to the Transmission container as an environment variable (PEERPORT=) or config modification.

I'm thinking volume mount `/tmp/gluetun/forwarded_port` to the host, then delay starting transmission starting by using depends on with a health check (?) then using another container (maybe alpine?) to run a bash/sh script to copy the content from the file and provide as an environment variable to linuxserver.io's transmission container as the env var `PEERPORT`.

It's also mentioned in issue [53](https://github.com/qdm12/gluetun/issues/53) (specifically [this comment](https://github.com/qdm12/gluetun/issues/53#issuecomment-554650455)) to use `sed` to modify transmissions `settings.json` with the port directly but this would require transmission to be restarted maybe? I also spotted somewhere that linuxserver.io images allow you to run scripts at boot.

Example `compose.yml`...

```
version: "3"

services:
  gluetun:
    container_name: gluetun
    restart: unless-stopped
    image: docker.io/qmcgaw/gluetun
    ports:
      # Built-in VPN HTTP Control Server
      # - 127.0.0.1:8000:8000
      # Transmission WebUI
      - 127.0.0.1:9091:9091
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - PUID=1000
      - PGID=1000
      - BLOCK_SURVEILLANCE=on
      - UPDATER_PERIOD=24h
    env_file: 
      - gluetun.env
      # - VPN_SERVICE_PROVIDER=protonvpn # or other port forwarding vpn provider
      # - OPENVPN_USER= # (append `+f2+pmp`)
      # - OPENVPN_PASSWORD=
      # - SERVER_COUNTRIES=
      # - VPN_PORT_FORWARDING=on

  transmission:
    container_name: transmission
    restart: unless-stopped
    network_mode: "service:gluetun"
    image: lscr.io/linuxserver/transmission
    volumes:
      - /media/containers/transmission:/config
      - /media/downloads:/downloads
      - /media/downloads/watch:/watch
    environment:
      - PGID=1000
      - PUID=1000
      - DOCKER_MODS=linuxserver/mods:transmission-floodui
    env_file:
      - transmission.env
      # - USER=
      # - PASS=
      # - PEERPORT= # get this from gluetun somehow?
```

_Opening a port would make downloading slightly faster with more peers. e.g. linux iso's and other such legit content..._

**Comment by Michsior14** [comment]
You can use [my docker mod](https://github.com/Michsior14/docker-mods?tab=readme-ov-file#transmission-gluetun-port-update) for transmission that will handle port updating automatically. 

In your example it's as easy as adjusting `DOCKER_MODS` in the following way:
```
DOCKER_MODS=michaukrieg/docker-mods:transmission-gluetun-port-update|linuxserver/mods:transmission-floodui
```

**Reply by DennisGaida** [reply]
How do you deal with port forwarding on the gluetun docker container itself? Or do you use host network not bridged?

**Reply by Michsior14** [reply]
I've never had the need to expose a forwarded port on gluetun container. I do nothing else than [this](https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/protonvpn.md?plain=1#L46).

**Reply by sunmetis** [reply]
> You can use [my docker mod](https://github.com/Michsior14/docker-mods?tab=readme-ov-file#transmission-gluetun-port-update) for transmission that will handle port updating automatically. 
> 
> 
> 
> In your example it's as easy as adjusting `DOCKER_MODS` in the following way:
> 
> ```
> 
> DOCKER_MODS=michaukrieg/docker-mods:transmission-gluetun-port-update|linuxserver/mods:transmission-floodui
> 
> ```

Hi ... testing gluetun and proton vpn .. for test just put transmission torrent behind ports still closed (Even with docker mod method) . Wich parameters in the transmission network section( random, fixed ports ?) thx a lot

**Reply by darrendavid** [reply]
> You can use [my docker mod](https://github.com/Michsior14/docker-mods?tab=readme-ov-file#transmission-gluetun-port-update) for transmission that will handle port updating automatically.
> 
> In your example it's as easy as adjusting `DOCKER_MODS` in the following way:
> 
> ```
> DOCKER_MODS=michaukrieg/docker-mods:transmission-gluetun-port-update|linuxserver/mods:transmission-floodui
> ```

This looks like a great solution. I've got it configured and I can see that the VPN port is correctly updating in Transmission from what gluetun reports as the current port, however, Transmission still reports that the "Port is Closed" - is there some additional configuration required to get this to pass through properly?

**Reply by Michsior14** [reply]
Here's my env for gluetun that works:
```
environment:
  - VPN_SERVICE_PROVIDER=protonvpn
  - VPN_TYPE=wireguard
  - WIREGUARD_PRIVATE_KEY=${PROTON_WIREGUARD_PRIVATE_KEY}
  - VPN_PORT_FORWARDING=on
  - PORT_FORWARD_ONLY=on
  - UPDATER_PERIOD=24h
  - PUID=${PUID}
  - PGID=${PGID}
  - TZ=${TIMEZONE}
```
Of course transmission should be running in the same network as gluetun.

**Reply by darrendavid** [reply]
That's more or less what mine looks like, but same issue. For reference, here are the relevant portions of my configs:

gluetun:
```
image: qmcgaw/gluetun
    restart: always
    container_name: gluetun
    hostname: mediagluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - <REDACTED>
    volumes:
      - /mnt/Apps/docker/data/gluetun/config:/gluetun
      - /mnt/Apps/docker/data/gluetun/tmp:/tmp/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_STATUS_FILE=/tmp/gluetun/forwarded_port
      - PORT_FORWARD_ONLY=on
      - UPDATER_PERIOD=24h
      - WIREGUARD_ADDRESSES=$WG_ADDRESS
      - WIREGUARD_PRIVATE_KEY=$WG_PRIVKEY
      - DNS_ADDRESS=$WG_DNS
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TIMEZONE
      - FIREWALL_OUTBOUND_SUBNETS=10.0.1.0/24
      - HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE='{"auth":"none"}'
```

```
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TIMEZONE
      - TRANSMISSION_USER=$TRANSMISSION_USER
      - TRANSMISSION_PASSWORD=$TRANSMISSION_PW
      - USER=$TRANSMISSION_USER
      - PASS=$TRANSMISSION_PW
      - DOCKER_MODS=ghcr.io/michsior14/docker-mods:transmission-gluetun-port-update-20260127123449
      - GLUETUN_PROTOCOL=http
      - GLUETUN_HOSTNAME=10.0.1.10
      - GLUETUN_PORT=8000
      - GLUETUN_ENDPOINT=/v1/portforward
      - GLUETUN_AUTH_TYPE=none
      - CHECK_INTERVAL=1m
```

There's nothing I need to do on my *literal* firewall, is there? I'm assuming not, just confirming that this is all happening at the VPN endpoint.
