### DISCUSSION TITLE
Wireguard & Windscribe: permanent IP with port forwarding doesn't forward

### DISCUSSION THREAD

**Discussion by Proximyst** [qdm12/gluetun#1996] [Q&A]
Heyo! I've tried going through every single place I've found so far for this, and the Garry bot on Windscribe's website doesn't help.

I'm running a Gluetun container as such:

```yaml
  vpn:
    image: qmcgaw/gluetun
    restart: unless-stopped
    environment:
      PUID: '1000'
      PGID: '1001'
      TZ: Etc/UTC
      VPN_SERVICE_PROVIDER: custom
      VPN_TYPE: wireguard
      DOT: 'off'
      WIREGUARD_PUBLIC_KEY: ${WIREGUARD_PUBLIC_KEY} # Gotten from their generated config
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY} # Gotten from their generated config
      WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES} # Gotten from their generated config
      WIREGUARD_PRESHARED_KEY: ${WIREGUARD_PRESHARED_KEY} # Gotten from their generated config
      VPN_ENDPOINT_IP: ${WIREGUARD_IP} # My static IP
      VPN_ENDPOINT_PORT: ${WIREGUARD_PORT} # 443
      FIREWALL_DEBUG: 'on'
      FIREWALL_VPN_INPUT_PORTS: '1234,6881,10414'
    cap_add:
      - NET_ADMIN
        # Tried with and without this:
        #    devices:
        #      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./gluetun:/gluetun
```

```
test-vpn-1  | 2023-12-07T19:50:16Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
test-vpn-1  | 2023-12-07T19:50:16Z INFO [firewall] setting allowed input port 6881 through interface tun0...
test-vpn-1  | 2023-12-07T19:50:16Z DEBUG [firewall] iptables --append INPUT -i tun0 -p tcp --dport 6881 -j ACCEPT
test-vpn-1  | 2023-12-07T19:50:16Z DEBUG [firewall] ip6tables --append INPUT -i tun0 -p tcp --dport 6881 -j ACCEPT
test-vpn-1  | 2023-12-07T19:50:16Z DEBUG [firewall] iptables --append INPUT -i tun0 -p udp --dport 6881 -j ACCEPT
test-vpn-1  | 2023-12-07T19:50:16Z DEBUG [firewall] ip6tables --append INPUT -i tun0 -p udp --dport 6881 -j ACCEPT
test-vpn-1  | 2023-12-07T19:50:16Z INFO [firewall] setting allowed input port 1234 through interface tun0...
test-vpn-1  | 2023-12-07T19:50:16Z DEBUG [firewall] iptables --append INPUT -i tun0 -p tcp --dport 1234 -j ACCEPT
test-vpn-1  | 2023-12-07T19:50:16Z DEBUG [firewall] ip6tables --append INPUT -i tun0 -p tcp --dport 1234 -j ACCEPT
test-vpn-1  | 2023-12-07T19:50:16Z DEBUG [firewall] iptables --append INPUT -i tun0 -p udp --dport 1234 -j ACCEPT
test-vpn-1  | 2023-12-07T19:50:16Z DEBUG [firewall] ip6tables --append INPUT -i tun0 -p udp --dport 1234 -j ACCEPT
test-vpn-1  | 2023-12-07T19:50:16Z INFO [firewall] setting allowed input port 10414 through interface tun0...
test-vpn-1  | 2023-12-07T19:50:16Z DEBUG [firewall] iptables --append INPUT -i tun0 -p tcp --dport 10414 -j ACCEPT
test-vpn-1  | 2023-12-07T19:50:16Z DEBUG [firewall] ip6tables --append INPUT -i tun0 -p tcp --dport 10414 -j ACCEPT
test-vpn-1  | 2023-12-07T19:50:16Z DEBUG [firewall] iptables --append INPUT -i tun0 -p udp --dport 10414 -j ACCEPT
test-vpn-1  | 2023-12-07T19:50:16Z DEBUG [firewall] ip6tables --append INPUT -i tun0 -p udp --dport 10414 -j ACCEPT
test-vpn-1  | 2023-12-07T19:50:17Z INFO [ip getter] Public IP address is [[ manually edited for GitHub ]] 1.2.3.4 (Country, Region, City)
test-vpn-1  | 2023-12-07T19:50:17Z INFO [vpn] You are running on the bleeding edge of latest!
test-vpn-1  | 2023-12-07T19:50:17Z INFO [healthcheck] healthy!
```

If I then use `nc -l` with any of the 3 ports, I do not get any throughput at all. Now, the first thing you think of is probably "does it tunnel anything?": 

```
$ sudo docker compose exec -it vpn wget -qO- 'https://api.ipify.org?format=json'
{"ip":"1.2.3.4"} [[ manually edited: this is the exact same ip as shown on the original log output! ]]
```

On the other hand, if I use a public IP with an ephemeral port (I've requested the internal port 10414 here and got 10094 as external), all is swell:

```yaml
  vpn:
    image: qmcgaw/gluetun
    restart: unless-stopped
    environment:
      PUID: '1000'
      PGID: '1001'
      TZ: Etc/UTC
      VPN_SERVICE_PROVIDER: windscribe
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES}
      WIREGUARD_PRESHARED_KEY: ${WIREGUARD_PRESHARED_KEY}
      FIREWALL_VPN_INPUT_PORTS: '10414'
      FIREWALL_DEBUG: 'on'
    cap_add:
      - NET_ADMIN
    volumes:
      - ./gluetun:/gluetun
```

```
test-vpn-1  | 2023-12-07T19:46:36Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
test-vpn-1  | 2023-12-07T19:46:36Z INFO [firewall] setting allowed input port 10414 through interface tun0...
test-vpn-1  | 2023-12-07T19:46:36Z DEBUG [firewall] iptables --append INPUT -i tun0 -p tcp --dport 10414 -j ACCEPT
test-vpn-1  | 2023-12-07T19:46:36Z DEBUG [firewall] ip6tables --append INPUT -i tun0 -p tcp --dport 10414 -j ACCEPT
test-vpn-1  | 2023-12-07T19:46:36Z DEBUG [firewall] iptables --append INPUT -i tun0 -p udp --dport 10414 -j ACCEPT
test-vpn-1  | 2023-12-07T19:46:36Z DEBUG [firewall] ip6tables --append INPUT -i tun0 -p udp --dport 10414 -j ACCEPT
test-vpn-1  | 2023-12-07T19:46:37Z INFO [ip getter] Public IP address is 89.187.185.56 (United States, California, Los Angeles)
test-vpn-1  | 2023-12-07T19:46:37Z INFO [healthcheck] healthy!
```

```
$ sudo docker compose exec -it vpn nc -l -p 10414 -s 0.0.0.0
[[ next line pops up after i press enter on the netcat locally; nc 89.187.185.56 10094 ]]
hi
```

I really can't fathom why this works with public IPs only. I would highly appreciate your answer. Cheers!
