### DISCUSSION TITLE
Trouble getting gluetun to work with other containers

### DISCUSSION THREAD

**Discussion by RobertVoorn1977** [qdm12/gluetun#2058] [Q&A] [answered]
I have successfully configured a gluetun container using docker-compose. Connecting to it gives me internet access with a different ip address that my providers provides me. I want to connect other container so they can also use the vpn provider, but this is where I get into trouble.

I have disabled the ports used by the A container and bound these on the glueton container (xxxx:xxxx/tcp). I also added the configuration to the A container for linking it to the gluetun container with the following line:
```
network_mode: "service:gluetun"
```
This is what I could find on the wiki. I expect container A to be accessible on the port 9117 of the host these containers are running on. I however get a page not found 404.

**Comment by bnhf** [comment]
@RobertVoorn1977 

> I also added the configuration to the A container for linking it to the gluetun container with the following line:
```network_mode: "service:gluetun"```

This is correct if they're in the same stack. If you spun them up separately, then you use:
```
  network_mode: "container:gluetun"
```

If they are in the same stack, please post your docker-compose here.

**Reply by RobertVoorn1977** [reply]
They are in the same stack (docker-compose.yml), so here is my stack:

```

  containerA:
#    ports:
#      - 9000:9000
    image: containerA
    network_mode: "service:gluetun"


  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-contain>
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./gluetun:/gluetun
    ports:
      - 9000:9000/tcp
    environment:
      - VPN_SERVICE_PROVIDER=
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
```

I would expect containerA to be accessible on port 9000, but it is not. In containerA, I uncommented the ports that are normally used to access that container and left it in for clarity. Since I access it with a browser the tcp is added.

**Comment by bnhf** [comment]
@RobertVoorn1977 

> I would expect containerA to be accessible on port 9000, but it is not.

Have you tried something like `lsof i:9000` to see if docker-pr is listening on that port? And then maybe `docker ps | grep gluetun` to make sure the gluetun container is the one listening?

**Reply by RobertVoorn1977** [reply]
Hi bnhf, silly of me to not check that. Port 9000 not open (used a different command (sudo lsof -i -P -n | grep LISTEN) to check that. When using the ```docker ps | grep gluetun``` command, I see the following
```
dc37abf9f7e8   qmcgaw/gluetun                             "/gluetun-entrypoint"    33 seconds ago   Up 31 seconds (healthy)   8000/tcp, 8388/tcp, 8888/tcp, 8388/udp
```
So the ports are not correctly bound. Yesterday, they were there. Something must have broken during the testing of different solutions. When checking the docker-compose, I see that the following is defined for the gluetun container:
```
    ports:
      - 9000:9000/tcp
```
so I would expect there to be port open for that container. Not sure why this is not the case. Even in Portainer, the ports are not shown

**Comment by bnhf** [comment, marked as answer]
@RobertVoorn1977

> Not sure why this is not the case. Even in Portainer, the ports are not shown

Why don't you try using Glutetun with a completely different container, using a different port, other than "ContainerA".

This Firefox container can be handy for debugging, speedtest.net, ipleak.net, or accessing your VPN provider's web page. Also will give you an idea of whether you have a general problem with opening ports, or just 9000 in specific:
```
 firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Mountain
    volumes:
      - /data/firefox:/config
    shm_size: '1gb'
    network_mode: 'service:gluetun'
    depends_on:
      - gluetun
    restart: unless-stopped
```
Spin this up with Gluetun, and you should have a browser using your VPN, on a tab in your everyday browser at `http://yourdockerhost:3000`. Don't forget to define 3000:3000 in the Gluetun part of the compose.
