### DISCUSSION TITLE
Unable to communicate between containers in Gluetun network

### DISCUSSION THREAD

**Discussion by ianb445** [qdm12/gluetun#2064] [Q&A]
Hi,
I have looked at QA https://github.com/qdm12/gluetun/discussions/1576 but it does not help.

I need some help. I have Jackett and Flaresolverr protected by gluetun. They are provisioned via docker-compose and deployed to the same network.

I can connect to both Jackett and Flaresolverr from the host machine or other machines on the local network, however they cannot communicate with each other using the IP of the host.

Does anyone have any suggestions on what needs to be changed as far as the configuration is concerned so that I can call Flaresolverr from Jackett.

My config below:

```
version: "3"
services:
  gluetunvpn:
    image: qmcgaw/gluetun:latest
    container_name: gluetunvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8191:8191 #Flaresolverr
      - 9117:9117 #Jackett
    volumes:
      - ${configpath}/gluetun/:/config
    environment:
      - VPN_SERVICE_PROVIDER=avpnprodiver
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=gC32dbVe334c30jkuQOf2tseiqkDc32d4461c=
      - WIREGUARD_ADDRESSES=10.32.1.16/16
      - SERVER_COUNTRIES="Netherlands"
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGIP}
  flaresolverrvpn:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverrvpn
    depends_on:
      - gluetunvpn
    network_mode: "service:gluetunvpn"
    volumes:
      - ${configpath}/flaresolverr/:/config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGIP}
      - UMASK=022
    restart: unless-stopped
  jackettvpn:
    image: ghcr.io/linuxserver/jackett:latest
    container_name: jackettvpn
    depends_on:
      - gluetunvpn
    network_mode: "service:gluetunvpn"
    volumes:
      - ${configpath}/jackett/:/config
      - ${downloadpath}/:${downloadpath}
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGIP}
      - UMASK=022
    restart: unless-stopped
```
