### DISCUSSION TITLE
Error creating TUN device operation not permitted

### DISCUSSION THREAD

**Discussion by TheTercept** [qdm12/gluetun#2085] [Q&A] [answered]
Trying to get gluetun started so I can have other containers (arrs) connect using its network. On Rocky Linux 9.3 using podman (and podman-compose).

I have tried running the compose file as my user account, with and without sudo, and as the root account.

Logs:

```
[gluetun] | ========================================
[gluetun] | ========================================
[gluetun] | =============== gluetun ================
[gluetun] | ========================================
[gluetun] | =========== Made with ❤️ by ============
[gluetun] | ======= https://github.com/qdm12 =======
[gluetun] | ========================================
[gluetun] | ========================================
[gluetun] | 
[gluetun] | Running version latest built on 2024-01-29T18:29:14.880Z (commit 6b9c775)
[gluetun] | 
[gluetun] | 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
[gluetun] | 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
[gluetun] | ✨ New feature? https://github.com/qdm12/gluetun/issues/new
[gluetun] | ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
[gluetun] | 💻 Email? quentin.mcgaw@gmail.com
[gluetun] | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
[gluetun] | 2024-01-31T21:53:59Z INFO [routing] default route found: interface eth0, gateway 10.89.0.1, assigned IP 10.89.0.5 and family v4
[gluetun] | 2024-01-31T21:53:59Z INFO [routing] local ethernet link found: eth0
[gluetun] | 2024-01-31T21:53:59Z INFO [routing] local ipnet found: 10.89.0.0/24
[gluetun] | 2024-01-31T21:53:59Z INFO [routing] local ipnet found: fe80::/64
[gluetun] | 2024-01-31T21:53:59Z INFO [firewall] enabling...
[gluetun] | 2024-01-31T21:53:59Z INFO [firewall] enabled successfully
[gluetun] | 2024-01-31T21:53:59Z INFO [storage] creating /gluetun/servers.json with 17743 hardcoded servers
[gluetun] | 2024-01-31T21:53:59Z INFO Alpine version: 3.18.6
[gluetun] | 2024-01-31T21:53:59Z INFO OpenVPN 2.5 version: 2.5.8
[gluetun] | 2024-01-31T21:53:59Z INFO OpenVPN 2.6 version: 2.6.8
[gluetun] | 2024-01-31T21:53:59Z INFO Unbound version: 1.17.1
[gluetun] | 2024-01-31T21:53:59Z INFO IPtables version: v1.8.9
[gluetun] | 2024-01-31T21:53:59Z INFO Settings summary:
[gluetun] | ├── VPN settings:
[gluetun] | |   ├── VPN provider settings:
[gluetun] | |   |   ├── Name: protonvpn
[gluetun] | |   |   ├── Server selection settings:
[gluetun] | |   |   |   ├── VPN type: openvpn
[gluetun] | |   |   |   ├── Countries: netherlands
[gluetun] | |   |   |   └── OpenVPN server selection settings:
[gluetun] | |   |   |       └── Protocol: UDP
[gluetun] | |   |   └── Automatic port forwarding settings:
[gluetun] | |   |       ├── Redirection listening port: disabled
[gluetun] | |   |       ├── Use port forwarding code for current provider
[gluetun] | |   |       └── Forwarded port file path: /tmp/gluetun/forwarded_port
[gluetun] | |   └── OpenVPN settings:
[gluetun] | |       ├── OpenVPN version: 2.5
[gluetun] | |       ├── User: [set]
[gluetun] | |       ├── Password: il...b7
[gluetun] | |       ├── Network interface: tun0
[gluetun] | |       ├── Run OpenVPN as: root
[gluetun] | |       └── Verbosity level: 1
[gluetun] | ├── DNS settings:
[gluetun] | |   ├── Keep existing nameserver(s): no
[gluetun] | |   ├── DNS server address to use: 127.0.0.1
[gluetun] | |   └── DNS over TLS settings:
[gluetun] | |       ├── Enabled: yes
[gluetun] | |       ├── Update period: every 24h0m0s
[gluetun] | |       ├── Unbound settings:
[gluetun] | |       |   ├── Authoritative servers:
[gluetun] | |       |   |   └── cloudflare
[gluetun] | |       |   ├── Caching: yes
[gluetun] | |       |   ├── IPv6: no
[gluetun] | |       |   ├── Verbosity level: 1
[gluetun] | |       |   ├── Verbosity details level: 0
[gluetun] | |       |   ├── Validation log level: 0
[gluetun] | |       |   ├── System user: root
[gluetun] | |       |   └── Allowed networks:
[gluetun] | |       |       ├── 0.0.0.0/0
[gluetun] | |       |       └── ::/0
[gluetun] | |       └── DNS filtering settings:
[gluetun] | |           ├── Block malicious: yes
[gluetun] | |           ├── Block ads: no
[gluetun] | |           ├── Block surveillance: no
[gluetun] | |           └── Blocked IP networks:
[gluetun] | |               ├── 127.0.0.1/8
[gluetun] | |               ├── 10.0.0.0/8
[gluetun] | |               ├── 172.16.0.0/12
[gluetun] | |               ├── 192.168.0.0/16
[gluetun] | |               ├── 169.254.0.0/16
[gluetun] | |               ├── ::1/128
[gluetun] | |               ├── fc00::/7
[gluetun] | |               ├── fe80::/10
[gluetun] | |               ├── ::ffff:127.0.0.1/104
[gluetun] | |               ├── ::ffff:10.0.0.0/104
[gluetun] | |               ├── ::ffff:169.254.0.0/112
[gluetun] | |               ├── ::ffff:172.16.0.0/108
[gluetun] | |               └── ::ffff:192.168.0.0/112
[gluetun] | ├── Firewall settings:
[gluetun] | |   ├── Enabled: yes
[gluetun] | |   └── Outbound subnets:
[gluetun] | |       └── 192.168.1.0/24
[gluetun] | ├── Log settings:
[gluetun] | |   └── Log level: INFO
[gluetun] | ├── Health settings:
[gluetun] | |   ├── Server listening address: 127.0.0.1:9999
[gluetun] | |   ├── Target address: cloudflare.com:443
[gluetun] | |   ├── Duration to wait after success: 5s
[gluetun] | |   ├── Read header timeout: 100ms
[gluetun] | |   ├── Read timeout: 500ms
[gluetun] | |   └── VPN wait durations:
[gluetun] | |       ├── Initial duration: 6s
[gluetun] | |       └── Additional duration: 5s
[gluetun] | ├── Shadowsocks server settings:
[gluetun] | |   └── Enabled: no
[gluetun] | ├── HTTP proxy settings:
[gluetun] | |   ├── Enabled: yes
[gluetun] | |   ├── Listening address: :8888
[gluetun] | |   ├── User: 
[gluetun] | |   ├── Password: [not set]
[gluetun] | |   ├── Stealth mode: no
[gluetun] | |   ├── Log: no
[gluetun] | |   ├── Read header timeout: 1s
[gluetun] | |   └── Read timeout: 3s
[gluetun] | ├── Control server settings:
[gluetun] | |   ├── Listening address: :8000
[gluetun] | |   └── Logging: yes
[gluetun] | ├── OS Alpine settings:
[gluetun] | |   ├── Process UID: 0
[gluetun] | |   ├── Process GID: 0
[gluetun] | |   └── Timezone: europe/london
[gluetun] | ├── Public IP settings:
[gluetun] | |   ├── Fetching: every 12h0m0s
[gluetun] | |   └── IP file path: /tmp/gluetun/ip
[gluetun] | └── Version settings:
[gluetun] |     └── Enabled: yes
[gluetun] | 2024-01-31T21:53:59Z INFO using existing username root corresponding to user id 0
[gluetun] | 2024-01-31T21:53:59Z INFO [routing] default route found: interface eth0, gateway 10.89.0.1, assigned IP 10.89.0.5 and family v4
[gluetun] | 2024-01-31T21:53:59Z INFO [routing] adding route for 0.0.0.0/0
[gluetun] | 2024-01-31T21:53:59Z INFO [firewall] setting allowed subnets...
[gluetun] | 2024-01-31T21:53:59Z INFO [routing] default route found: interface eth0, gateway 10.89.0.1, assigned IP 10.89.0.5 and family v4
[gluetun] | 2024-01-31T21:53:59Z INFO [routing] adding route for 192.168.1.0/24
[gluetun] | 2024-01-31T21:53:59Z INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
[gluetun] | 2024-01-31T21:53:59Z INFO [routing] routing cleanup...
[gluetun] | 2024-01-31T21:53:59Z INFO [routing] default route found: interface eth0, gateway 10.89.0.1, assigned IP 10.89.0.5 and family v4
[gluetun] | 2024-01-31T21:53:59Z INFO [routing] deleting route for 0.0.0.0/0
[gluetun] | 2024-01-31T21:53:59Z INFO [routing] deleting route for 192.168.1.0/24
[gluetun] | 2024-01-31T21:53:59Z ERROR creating TUN device file node: operation not permitted
[gluetun] | 2024-01-31T21:53:59Z INFO Shutdown successful
```
Compose file:

```
version: '3.7'
services:
  gluetun:
    image: qmcgaw/private-internet-access:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
# other containers ports
      - 8112:8112     # deluge webui
      - 58846:58846   # deluge daemon
      - 8080:8080     # qbittorrent
      - 6767:6767     # bazarr
      - 8989:8989     # sonarr
      - 7878:7878     # radarr
      - 8686:8686     # lidarr
      - 9117:9117     # jackett
      - 4040:4040     # airsonic
      - 8096:8096     # jellyfin/emby
      - 8227:8227     # pyload
    volumes:
      - ./data_gluetun:/data/containerdata/gluetun
      - ./data_gluetun/port_forward:/tmp/gluetun/forwarded_port
    environment:
      - VPNSP=protonvpn
      - TZ=Europe/London
      - OPENVPN_USER=<user>+pmp
      - OPENVPN_PASSWORD=<password>
      - SERVER_COUNTRIES=Netherlands
      - VPN_PORT_FORWARDING=on
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - HTTPPROXY=on
      #- SHADOWSOCKS=on
      #- SHADOWSOCKS_PASSWORD=shadowsocks
      - PGID=0
      - PUID=0
    restart: unless-stopped
```

Fairly new to containers (other than using them on unraid and making minor tweaks. I'm trying to learn something new. Any help is appreciated.
