### DISCUSSION TITLE
No connection with tzahi12345/youtubedl-material

### DISCUSSION THREAD

**Discussion by truthsword** [qdm12/gluetun#2096] [Q&A]
I have 3 containers connected through Gluetun that work as expected. Recently I tried to spin up a new container, tzahi12345/youtubedl-material, and I cannot connect to the container when passing through Gluetun. Specifically when using my LAN IP...

http://192.168.1.42:8999 

There is no connection, and the UI does not appear.

My docker-compose is:

```
version: "2"
services:
  ytdl_material:
    image: tzahi12345/youtubedl-material:latest
    container_name: ytdl-material
    depends_on:
      - ytdl-mongo-db
    restart: always
    environment:
      ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
      ytdl_use_local_db: 'false'
      write_ytdl_config: 'true'
      UID: 1000
      GID: 1000
    volumes:
      - appdata:/app/appdata
      - /mnt/audio:/app/audio
      - /mnt/video:/app/video
      - subscriptions:/app/subscriptions
      - users:/app/users
#    ports:
#      - 8999:17442
    network_mode: "container:gluetun"

  ytdl-mongo-db:
    image: mongo:4
    container_name: mongo-db
    restart: always
    logging:
      driver: "none"
    volumes:
      - db:/data/db

volumes:
  appdata:
  subscriptions:
  users:
  db:
```
The port `8999:17442` is passed through the Gluetun container.

Any thoughts? Thank you!

[docker compose reference](https://github.com/Tzahi12345/YoutubeDL-Material/blob/master/docker-compose.yml)
