### DISCUSSION TITLE
ProtonVPN Wireguard Port Forwarding Not Working

### DISCUSSION THREAD

**Discussion by Enduriel** [qdm12/gluetun#2098] [Q&A]
I'm unable to figure out how to make the protonvpn port forwarding work. Best as I can tell, everything *should* be working. The docker logs give me:
```
2024-02-07T11:46:26Z INFO [ip getter] Public IP address is XX.XX.XX.XX (...)
2024-02-07T11:46:26Z INFO [port forwarding] starting
2024-02-07T11:46:27Z INFO [port forwarding] gateway external IPv4 address is XX.XX.XX.XX
2024-02-07T11:46:27Z INFO [ip getter] Public IP address is XX.XX.XX.XX (...)
2024-02-07T11:46:27Z INFO [port forwarding] port forwarded is YYYYY
2024-02-07T11:46:27Z INFO [firewall] setting allowed input port YYYYY through interface tun0...
```
but when I run
```bash
nc -l YYYYY
```
within the container and
```bash
telnet XX.XX.XX.XX YYYYY
```
on another device or use https://www.yougetsignal.com/tools/open-ports/ the port is closed.

This is my docker compose:
```yaml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      # - 8388:8388/tcp # Shadowsocks
      # - 8388:8388/udp # Shadowsocks
      - 8080:8080
      - 6881:6881 # qbit
      - 6881:6881/udp # qbit
      - 50003:50003 # qbit UI
    volumes:
      - gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=XX.XX.XX.XX
      - VPN_ENDPOINT_PORT=51820
      - WIREGUARD_PUBLIC_KEY=[REDACTED]
      - WIREGUARD_PRIVATE_KEY=[REDACTED]
      - WIREGUARD_ADDRESSES=10.2.0.2/32
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - TZ=Europe/London
volumes:
  gluetun:
    name: gluetun
```
I've spent a good few hours trying to figure this out so I'm reaching out for advice here because I'm completely out of ideas and no one else seems to get to this state of stuff working and still be unable to actually use a service on the 'open' port.
