### DISCUSSION TITLE
Private Internet Access trouble

### DISCUSSION THREAD

**Discussion by SamLawAnthro** [qdm12/gluetun#2112] [Q&A]
I had everything up and working, but then I ran a script that borked my gluetun docker compose file and now I'm getting AUTH_FAILED when I try to connect to Private Internet Access. I've carefully been through the wiki and checked a bunch of different people's docker compose and I can't figure it out.

Docker Compose file: 
 ```
  # Gluetun is our VPN, so you can download torrents safely
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8080:8080/tcp # gluetun
      - 8000:8000/tcp # Built-in HTTP control server
    volumes:
      - ${INSTALL_DIRECTORY}/config/gluetun:/config
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE} # private internet access is default
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${VPN_USER} #correct in .env file
      - OPENVPN_PASSWORD=${VPN_PASSWORD} #correct in .env file
      - SERVER_REGIONS=CA Toronto 
      - OPENVPN_CIPHERS=AES-256-GCM
      - VPN_PORT_FORWARDING=on
    restart: unless-stopped
```

And relevant logs are here:

```
gluetun  | 2024-02-14T14:41:22Z INFO [openvpn] SIGUSR1[soft,auth-failure] received, process restarting
gluetun  | 2024-02-14T14:41:32Z INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]66.115.142.115:1197
gluetun  | 2024-02-14T14:41:32Z INFO [openvpn] UDP link local: (not bound)
gluetun  | 2024-02-14T14:41:32Z INFO [openvpn] UDP link remote: [AF_INET]66.115.142.115:1197
gluetun  | 2024-02-14T14:41:32Z WARN [openvpn] 'link-mtu' is used inconsistently, local='link-mtu 1549', remote='link-mtu 1554'
gluetun  | 2024-02-14T14:41:32Z WARN [openvpn] 'auth' is used inconsistently, local='auth [null-digest]', remote='auth SHA256'
gluetun  | 2024-02-14T14:41:32Z WARN [openvpn] 'keysize' is used inconsistently, local='keysize 256', remote='keysize 128'
gluetun  | 2024-02-14T14:41:32Z WARN [openvpn] 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
gluetun  | 2024-02-14T14:41:32Z INFO [openvpn] [toronto403] Peer Connection Initiated with [AF_INET]66.115.142.115:1197
gluetun  | 2024-02-14T14:41:33Z ERROR [openvpn] AUTH: Received control message: AUTH_FAILED
```

**Comment by bluskye** [comment]
I would start without port forwarding, see below with a transmission buddy container

```
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
#      - 8388:8388/tcp # Shadowsocks
#      - 8388:8388/udp # Shadowsocks
      - 9091:9091 #transmission
      - 51413:51413 #transmission
      - 51413:51413/udp #transmission
    volumes:
      - /yourpath:/gluetun
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - NETWORK=192.168.1.0/24
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=YOURID
      - OPENVPN_PASSWORD=YOURPASSWORD
      - SERVER_REGIONS=US Chicago
      - UPDATER_PERIOD=12h
      - HTTPPROXY=on
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /yourpath:/config
      - /yourpath:/downloads
      - /yourpath:/watch
#    ports:
#      - 9094:9091
#      - 51414:51413
#      - 51414:51413/udp
    restart: unless-stopped
```
