### DISCUSSION TITLE
Not able to connect using CyberGhost

### DISCUSSION THREAD

**Discussion by Whisper40** [qdm12/gluetun#2121] [Q&A]
I created client.crt and client.key (export from the website of the provider ubuntu 22)

Error : 
2024-02-19T19:45:59+01:00 ERROR [openvpn] AUTH: Received control message: AUTH_FAILED
Your credentials might be wrong 🤨
2024-02-19T19:45:59+01:00 INFO [openvpn] SIGUSR1[soft,auth-failure] received, process restarting
2024-02-19T19:46:09+01:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]84.17.47.15:443
2024-02-19T19:46:09+01:00 INFO [openvpn] UDP link local: (not bound)
2024-02-19T19:46:09+01:00 INFO [openvpn] UDP link remote: [AF_INET]84.17.47.15:443
2024-02-19T19:46:09+01:00 WARN [openvpn] 'link-mtu' is used inconsistently, local='link-mtu 1549', remote='link-mtu 1553'
2024-02-19T19:46:09+01:00 WARN [openvpn] 'auth' is used inconsistently, local='auth [null-digest]', remote='auth SHA256'
2024-02-19T19:46:09+01:00 WARN [openvpn] 'keysize' is used inconsistently, local='keysize 256', remote='keysize 128'
2024-02-19T19:46:09+01:00 INFO [openvpn] [amsterdam-rack402.nodes.gen4.ninja] Peer Connection Initiated with [AF_INET]84.17.47.15:443
2024-02-19T19:46:10+01:00 ERROR [openvpn] AUTH: Received control message: AUTH_FAILED
Your credentials might be wrong 🤨

```

  cyberghost_s50:
    image: qmcgaw/gluetun:v3.37.0
    container_name: cyberghost_s50
    restart: always
    environment:
      - VPN_SERVICE_PROVIDER=cyberghost
      - OPENVPN_USER=${USER_CYBERGHOST}
      - OPENVPN_PASSWORD=${PASSWORD_CYBERGHOST}
      - TZ=Europe/Paris
      - SERVER_COUNTRIES=Netherlands
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    cap_add:
      - NET_ADMIN
    devices:
     - /dev/net/tun
    ports: 
      - 8888:8888/tcp
      - 8388:8388/tcp
      - ${RUTORRENT_PORT}:${RUTORRENT_PORT}
      - 8388:8388/udp
    volumes:
      - $DATA_DIR/s50/config/cyberghost:/gluetun:rw
    networks:
      - proxy
```

![image](https://github.com/qdm12/gluetun/assets/30440458/ae998bcd-ed97-4a54-9309-8cec0238f42c)

User and password shown in portainer UI are correct, i can log in on the web ui without problem
