### DISCUSSION TITLE
Using Puppeteer with GlueTun. Problem with DNS not working

### DISCUSSION THREAD

**Discussion by TheoOliveira** [qdm12/gluetun#2153] [Q&A]
just sharing in case someone faces issues with DNS not resolving, the other discussion worked for me. Idk where is this  Flag is coming but using in the composer UNBLOCK worked for me

[DNS not working](https://github.com/qdm12/gluetun/issues/1515)

```
version: "3.8"
services:
  gluetun:
    image: qmcgaw/gluetun:v3.34.0
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=xx
      - VPN_ENDPOINT_PORT=1xx
      - WIREGUARD_PUBLIC_KEY=xx
      - WIREGUARD_PRIVATE_KEY=xx
      - WIREGUARD_PRESHARED_KEY=xx
      - WIREGUARD_ADDRESSES=xxx
      - UNBLOCK=qxbroker.com
    volumes:
      - ./gluetun:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8888:8888/tcp"
```
