### DISCUSSION TITLE
Switch from Docker Desktop to Colima: "configuration file does not exist"

### DISCUSSION THREAD

**Discussion by rob-bc** [qdm12/gluetun#2157] [Q&A]
With Docker Desktop running, my docker compose file runs without errors. If I close down Docker Desktop and start Colima, the same docker compose fails saying that the openvpn configuration file does not exist.

I presume this is an issue with how I have set up Colima, so apologies if this is not the right forum, but if you can offer any advice I'd appreciate it!

### Docker Compose:
```
services:
  vpn:
    profiles: ["vpn"]
    container_name: vpn
    image: qmcgaw/gluetun:v3.37.0
    cap_add:
      - NET_ADMIN

    environment:
      - VPN_SERVICE_PROVIDER=airvpn
      - SERVER_COUNTRIES=Netherlands
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
      - LOG_LEVEL=debug

    volumes:
      - ./gluetun:/gluetun

    networks:
      mynetwork:

    ports:
      # qbittorrent ports
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
      # prowlarr ports
      - 9696:9696
    restart: "unless-stopped"
```

### Log w/ Colima:
```
% sudo docker compose up vpn
[+] Running 1/1
 ⠿ Container vpn  Created                                                                                    0.1s
Attaching to vpn
vpn  | ========================================
vpn  | ========================================
vpn  | =============== gluetun ================
vpn  | ========================================
vpn  | =========== Made with ❤️ by ============
vpn  | ======= https://github.com/qdm12 =======
vpn  | ========================================
vpn  | ========================================
vpn  | 
vpn  | Running version v3.37.0 built on 2024-01-02T00:01:06.245Z (commit c826707)
vpn  | 
vpn  | 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
vpn  | 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
vpn  | ✨ New feature? https://github.com/qdm12/gluetun/issues/new
vpn  | ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
vpn  | 💻 Email? quentin.mcgaw@gmail.com
vpn  | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
vpn  | 2024-03-14T09:02:03Z INFO [routing] default route found: interface eth0, gateway 172.20.0.1, assigned IP 172.20.0.2 and family v4
vpn  | 2024-03-14T09:02:03Z INFO [routing] local ethernet link found: eth0
vpn  | 2024-03-14T09:02:03Z INFO [routing] local ipnet found: 172.20.0.0/16
vpn  | 2024-03-14T09:02:03Z INFO [firewall] enabling...
vpn  | 2024-03-14T09:02:03Z DEBUG [firewall] iptables --policy INPUT DROP
vpn  | 2024-03-14T09:02:03Z DEBUG [firewall] iptables --policy OUTPUT DROP
vpn  | 2024-03-14T09:02:03Z DEBUG [firewall] iptables --policy FORWARD DROP
vpn  | 2024-03-14T09:02:03Z DEBUG [firewall] ip6tables --policy INPUT DROP
vpn  | 2024-03-14T09:02:03Z DEBUG [firewall] ip6tables --policy OUTPUT DROP
vpn  | 2024-03-14T09:02:03Z DEBUG [firewall] ip6tables --policy FORWARD DROP
vpn  | 2024-03-14T09:02:03Z DEBUG [firewall] iptables --append INPUT -i lo -j ACCEPT
vpn  | 2024-03-14T09:02:03Z DEBUG [firewall] ip6tables --append INPUT -i lo -j ACCEPT
vpn  | 2024-03-14T09:02:03Z DEBUG [firewall] iptables --append OUTPUT -o lo -j ACCEPT
vpn  | 2024-03-14T09:02:03Z DEBUG [firewall] ip6tables --append OUTPUT -o lo -j ACCEPT
vpn  | 2024-03-14T09:02:03Z DEBUG [firewall] iptables --append OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
vpn  | 2024-03-14T09:02:03Z DEBUG [firewall] ip6tables --append OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
vpn  | 2024-03-14T09:02:03Z DEBUG [firewall] iptables --append INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
vpn  | 2024-03-14T09:02:03Z DEBUG [firewall] ip6tables --append INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
vpn  | 2024-03-14T09:02:03Z DEBUG [firewall] iptables --append OUTPUT -o eth0 -s 172.20.0.2 -d 172.20.0.0/16 -j ACCEPT
vpn  | 2024-03-14T09:02:03Z DEBUG [firewall] ip6tables --append OUTPUT -o eth0 -d ff02::1:ff/104 -j ACCEPT
vpn  | 2024-03-14T09:02:03Z DEBUG [firewall] iptables --append INPUT -i eth0 -d 172.20.0.0/16 -j ACCEPT
vpn  | 2024-03-14T09:02:03Z INFO [firewall] enabled successfully
vpn  | 2024-03-14T09:02:04Z INFO [storage] merging by most recent 17743 hardcoded servers and 17743 servers read from /gluetun/servers.json
vpn  | 2024-03-14T09:02:04Z DEBUG [netlink] IPv6 is not supported after searching 0 routes
vpn  | 2024-03-14T09:02:04Z ERROR VPN settings: provider settings: server selection: OpenVPN server selection settings: configuration file: file does not exist: /gluetun/custom.conf
vpn  | 2024-03-14T09:02:04Z INFO Shutdown successful
```
