### DISCUSSION TITLE
Slow Speed with Custom VPN Provider and Wireguard

### DISCUSSION THREAD

**Discussion by theodorp** [qdm12/gluetun#2173] [Q&A]
Hi all -- trying to debug my Gluetun Docker container. 

I'm using wireguard, and the VPN provider is OVPN (OVPN.com). 

Speed test outside of docker without VPN is about 2.3Gbps; outside docker with OVPN Wireguard is about 800Mbps. Insider docker below. 

Using speedtest-cli in the Gluetun container I get:

`Retrieving speedtest.net configuration...`
`Testing from Datacamp (169.150.231.246)...`
`Retrieving speedtest.net server list...`
`Selecting best server based on ping...`
`Hosted by SUMOFIBER (Denver, CO) [0.30 km]: 54.14 ms`
`Testing download speed....................`
**`Download: 279.63 Mbit/s`**
`Testing upload speed....................`
`Upload: 162.31 Mbit/s`

In a different container I get without VPN:

`Retrieving speedtest.net configuration...`
`Testing from Bell Canada (74.15.x.xxx)...`
`Retrieving speedtest.net server list...`
`Selecting best server based on ping...`
`Hosted by Teksavvy Solutions Inc (Toronto, ON) [5.71 km]: 4.088 ms`
`Testing download speed....................`
**`Download: 1432.44 Mbit/s`**
`Testing upload speed....................`
`Upload: 1851.79 Mbit/s`

So quite a substantial drop when routing through Gluetun. My docker compose looks like: 

```
version: '3.4'

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8550:80/tcp
      - 8085:8085/tcp # qBitorrent WebUI
      - 6881:6881/tcp # qBitorrent tcp connection port
      - 6881:6881/udp # qBitorrent udp connection port
    volumes:
      - ${ROOT}/config/gluetun:/gluetun
    environment:
      - VPNSP=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_ENDPOINT_IP=169.xxx.xxx.xxx #endpoint from wireguard config
      - WIREGUARD_ENDPOINT_PORT=9929 # this port is what I see on the wireguard config
      - WIREGUARD_PUBLIC_KEY= xxx # this is the public key I generated on OVPN
      - WIREGUARD_PRIVATE_KEY=xxx # this is the private key
      - WIREGUARD_ADDRESS=172.xx.xx.xxx/32 # this is the address assigned to me
    restart: always
```

Any ideas?

**Comment by cal3k** [comment]
Have you ever found out the reason? 

I'm running into the same exact issue, and I know for a fact is not the VPN speed.
While I'm aware speeds can vary a lot depending on the peers, these tests were all done around the same time.

![image](https://github.com/user-attachments/assets/3713c83d-ca22-4147-9e5f-cba7521070dd)

exact same containers stack, only difference in qbit I select the interface to tun0, and not all
![image](https://github.com/user-attachments/assets/43c1c4a3-1948-4341-b562-7d6650c46374)

to show it's not the VPN, from my laptop, via same custom surfshark wireguard setup, same exit node
![image](https://github.com/user-attachments/assets/9e58ccbb-f260-465a-a796-f0b75a277bb8)

```
├── VPN settings:
|   ├── VPN provider settings:
|   |   ├── Name: custom
|   |   └── Server selection settings:
|   |       ├── VPN type: wireguard
|   |       └── Wireguard selection settings:
|   |           ├── Endpoint IP address:  <redacted>
|   |           ├── Endpoint port: <redacted>
|   |           └── Server public key: <redacted>
|   └── Wireguard settings:
|       ├── Private key: yO+...XE=
|       ├── Interface addresses:
|       |   └── 10.14.0.2/32
|       ├── Allowed IPs:
|       |   └── 0.0.0.0/0
|       └── Network interface: tun0
|           └── MTU: 1400
├── DNS settings:
|   ├── Keep existing nameserver(s): no
|   ├── DNS server address to use: 127.0.0.1
|   └── DNS over TLS settings:
|       ├── Enabled: yes
|       ├── Update period: every 24h0m0s
|       ├── Upstream resolvers:
|       |   └── cloudflare
|       ├── Caching: yes
|       ├── IPv6: no
|       └── DNS filtering settings:
|           ├── Block malicious: no
|           ├── Block ads: no
|           ├── Block surveillance: no
|           └── Blocked IP networks:
|               ├── 127.0.0.1/8
|               ├── 10.0.0.0/8
|               ├── 172.16.0.0/12
|               ├── 192.168.0.0/16
|               ├── 169.254.0.0/16
|               ├── ::1/128
|               ├── fc00::/7
|               ├── fe80::/10
|               ├── ::ffff:127.0.0.1/104
|               ├── ::ffff:10.0.0.0/104
|               ├── ::ffff:169.254.0.0/112
|               ├── ::ffff:172.16.0.0/108
|               └── ::ffff:192.168.0.0/112
├── Firewall settings:
|   ├── Enabled: yes
|   └── VPN input ports:
|       └── 33331
├── Log settings:
|   └── Log level: info
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Target address: cloudflare.com:443
|   ├── Duration to wait after success: 5s
|   ├── Read header timeout: 100ms
|   ├── Read timeout: 500ms
|   └── VPN wait durations:
|       ├── Initial duration: 2m0s
|       └── Additional duration: 5s
├── Shadowsocks server settings:
|   └── Enabled: no
├── HTTP proxy settings:
|   └── Enabled: no
├── Control server settings:
|   ├── Listening address: :8000
|   └── Logging: yes
├── Storage settings:
|   └── Filepath: /gluetun/servers.json
├── OS Alpine settings:
|   ├── Process UID: 1000
|   └── Process GID: 1000
├── Public IP settings:
|   ├── Fetching: every 12h0m0s
|   ├── IP file path: /tmp/gluetun/ip
|   └── Public IP data API: ipinfo
└── Version settings:
    └── Enabled: yes
```

```
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 3000:3000 #firefox
      - 3001:3001 #firefox
      - 6500:6500 #rdtclient
      - 7878:7878 # Radarr
      - 8085:8085 # qbit Webui
      - 8191:8191 # FlareSolverr
      - 8989:8989 # Sonarr
      - 9117:9117 # Jackett
      - 9696:9696 # Prowlarr
      - 33331:33331 # qbit
      - 33331:33331/udp # qbit
    volumes:
      - ~/.docker:/gluetun
      - ~/.docker/wireguard:/gluetun/wireguard
      # bind custom wg0 to inside of the container
    environment:
      - DOT=on
      - BLOCK_MALICIOUS=off
      - BLOCK_SURVEILLANCE=off
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=  <redacted>
      - WIREGUARD_PUBLIC_KEY=    <redacted>
      - WIREGUARD_ENDPOINT_IP=   <redacted>
      - WIREGUARD_ALLOWED_IPS=0.0.0.0/0
      - WIREGUARD_ENDPOINT_PORT=51820
      - WIREGUARD_ADDRESSES=10.14.0.2/32
      - FIREWALL_VPN_INPUT_PORTS=33331
      - HEALTH_VPN_DURATION_INITIAL=120s
      - UPDATER_PERIOD=24h
    restart: always
```
