### DISCUSSION TITLE
Regular "unhealthy" messages and subsequent restarts - advice requested

### DISCUSSION THREAD

**Discussion by DoAndroids** [qdm12/gluetun#2180] [Q&A] [answered]
Hi all,
I've been hitting issues with the project since last weekend, where it will periodically become unhealthy.
` [healthcheck] program has been unhealthy for 6s: restarting VPN`

I think my issues are device related, because it's doing the same thing on both PIA and AirVPN.
It's also happening with both Wireguard & OpenVPN protocols...as well as with the thrnz/docker-wireguard-pia image.

I'm running on a QNAP box which...which I haven't (knowingly) made any changes to of late.

I'm looking for any advice people might have on where to go with fixing this (it was running perfectly fine for a year).

Thanks

I should include my docker-compose:
```
version: '3.9'
services:
 vpn:
  image: qmcgaw/gluetun
  container_name: vpn
  cap_add:
   - NET_ADMIN
  network_mode: "bridge"
  ports:
   - 8888:8888/tcp # HTTP proxy
   - 8388:8388/tcp # Shadowsocks
   - 8388:8388/udp # Shadowsocks
   - 8000:8000/tcp # Build-in HTTP control header
  volumes:
   - ./config/gluetun:/gluetun
   - ./config/airvpn:/airvpn
  environment:
   - PUID=${PUID}
   - PGID=${PGID}
   - TZ=${TZ}
   - VPN_SERVICE_PROVIDER=${AIRVPN_SERVICE_PROVIDER}
   - VPN_TYPE=openvpn
   - OPENVPN_CIPHERS=AES-256-GCM
   - OPENVPN_VERSION=2.6
   - FIREWALL_VPN_INPUT_PORTS=${AIRVPN_INPUT_PORT}
   - UPDATER_PERIOD=24h
   - SERVER_COUNTRIES=${SERVER_COUNTRIES}
   - FIREWALL_OUTBOUND_SUBNETS=${NETWORK_SUBNET}/24
  healthcheck:
   test: ping -c 1 www.google.com || exit 1
   interval: 60s
   timeout: 20s
   retries: 5
  restart: unless-stopped
```
