### DISCUSSION TITLE
External access from VPN ip

### DISCUSSION THREAD

**Discussion by kalogirev2** [qdm12/gluetun#2262] [Q&A]
Hello everyone,

I installed the VPN tunnel on a personal wireguard install on a host VPS.

The tunnel is working fine and my public ip is well up on the containers but I'd like to know if it's possible to access the service from the internet via the tunnel's public ip (by mapping the ports).

**Comment by kalogirev2** [comment]
Here's my conf,
I'd like to access my apache server via my public ip in the tunnel and port 80

```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 80:80 #apache2
    volumes:
      - ./gluetun:/gluetun
    environment:
      # Wireguard:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=163.5.xxx.xxx
      - VPN_ENDPOINT_PORT=59183
      - WIREGUARD_PUBLIC_KEY=*my public key*
      - WIREGUARD_PRIVATE_KEY= * my private key*
      - WIREGUARD_PRESHARED_KEY= *my preshared key*
      - WIREGUARD_ADDRESSES=163.5.xxx.xxx/32
      # Time
      - TZ=Europe/Paris
  apache2:
    stdin_open: true
    tty: true
    container_name: apache2
    volumes:
      - ./apache-data:/usr/local/apache2/htdocs/'
    image: httpd:2.4
    network_mode: service:gluetun
networks: {}
```
