### DISCUSSION TITLE
ProtonVPN Wireguard Port Forwarding

### DISCUSSION THREAD

**Discussion by aaronmee** [qdm12/gluetun#2275] [Q&A] [answered]
Hi,
I'm using gluetun to run qBittorrent behind a protonvpn connection. I'm using wireguard and wanted to forward a port using gluetuns port-forwarding mechanism. At the beginning it worked, but now I'm getting a `connection refused` message from my tracker. 
My question is: Does port forwarding only work with openvpn (as the api call v1/openvpn/portforwarded suggests), or should it work with wireguard as well without issues?

Docker-compose file (without qBittorrent part):
```yaml
---
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    ports:
      - '8010:8000/tcp'
      - '8080:8080'
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/wireguard/wg8.conf:/gluetun/wireguard/wg0.conf:ro
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
```
   
System:
* Ubuntu Server 22.04
* Docker version 26.0.0
* VPN Provider ProtonVPN
* VPN Protocol Wireguard
