### DISCUSSION TITLE
Having problems running pihole/unbound and gluetun/deluge/arrs on same host

### DISCUSSION THREAD

**Discussion by bunkerman** [qdm12/gluetun#2284] [Q&A] [answered]
So I tried to setup gluetun/arrs/qbittorent, but that really didn't work with qbittorrent and stalled downloads. With deluge instead of qbittorrent it works right away - nice!
But then after a while I face DNS resolving issues (I guess, I can't really debug it, but also have limited experience). So deluge continues to download the content, but the host itself can't resolve anymore. And my whole home network is using pihole with DNS and DHCP and so the whole network suffers DNS resloving issues, unless I change the DNS Server on the client.
I'm using separate containers for my own wireguard server (wg easy), unbound (mvance) and pihole via a macvlan, because of port collision.
I also tried to use my separate unbound container for gluetun via - DOT=off;- DNS_ADDRESS=pihole adress, but that also didn't work.
I host everything on the same machine.
I'm using OMV 7 (Debian 12) and Portainer Stacks.
So my does anyone have a similar setup and knows how to fix this?

my docker compose:
```
version: "3"
networks:
  wirehole:
    driver: macvlan
    external: true
services:
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: vpn
    networks:
      wirehole:
        ipv4_address: xxx
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 53:53/tcp
      - 53:53/udp
      - ${Proxy}:8888/tcp
      - ${ShadowsocksTCP}:8388/tcp
      - ${ShadowsocksUDP}:8388/udp
      - ${deluge}:6881
      - ${delugeUDP}:6881/udp
      - ${GluetunPort}:8889/tcp
      - 8112:8112
      - 58846:58846 #optional
    volumes:
      - /portainer/Files/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=Germany,Switzerland,Austria,Netherlands,Ireland,Hungary,Belgium,Czech Republic,Bulgaria,France,Italy,Slovenia,Spain,Sweden,Ukraine
      #- SERVER_CITIES=Frankfurt am Main
      - TZ=${TZ}
      - UPDATER_PERIOD=
      #- HTTP_CONTROL_SERVER_ADDRESS=:8000
      #- HTTP_CONTROL_SERVER_LOG=on
      #- DOT=off
      #- DNS_ADDRESS=xxx
    restart: unless-stopped
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /portainer/Files/deluge/config:/config
      - /portainer/Files/deluge/downloads:/downloads
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn
```
