### DISCUSSION TITLE
ERROR [vpn]getting external IPv4 address: executing remote procedure call: connection timeout

### DISCUSSION THREAD

**Discussion by brpaz** [qdm12/gluetun#2293] [Q&A]
Hello.

I am running glutun in Kubernetes, and ProtonVPN but I am having some issues with port forwarding. The Tunnel is working fine.

This is the error I got, in gluetun logs.

```
2024-05-25T13:44:48Z INFO [vpn] You are running the latest release v3.38.0                                                 
2024-05-25T13:44:48Z INFO [port forwarding] starting
2024-05-25T13:46:56Z ERROR [vpn] port forwarding for the first time: getting external IPv4 address: executing remote procedure call: connection timeout: failed attempts: read udp 10.0.0.166:47010->10.19.0.1:5351: i/o timeout
``` 

Here is my kubernetes deployment:

```yaml
    image: ghcr.io/qdm12/gluetun:v3.38.0
    imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        envFrom:
          - secretRef:
              name: gluetun-protonvpn-creds
        env:
          - name: FIREWALL_INPUT_PORTS
            value: "8080,6881,8001"
          - name: FIREWALL_OUTBOUND_SUBNETS
            value: 10.0.0.0/8
          - name: HEALTH_VPN_DURATION_INITIAL
            value: 360s
          - name: UPDATER_PERIOD
            value: "24h"
          - name: LOG_LEVEL
            value: debug
        volumeMounts:
          - name: gluetun-config
            mountPath: /gluetun
        resources:
          requests:
            cpu: 1m
            memory: 128Mi
          limits:
            memory: 256Mi
```

Anyone has an idea what might be wrong?

I guess it´s something network related or firewall issue, but I networking is not really my expertise.

I have no idea, where that ip addresses came from. My cluster is configured with CIDR 10.43.0.0
