### DISCUSSION TITLE
Gluetun HTTP proxy behind Traefik reverse proxy using HTTPS

### DISCUSSION THREAD

**Discussion by 0xFFA500** [qdm12/gluetun#2298] [Q&A]
I wanted to use HTTPS to connect to the Gluetun HTTP proxy server but when I tried I got an unsupported scheme error logged by Gluetun. Is what I am trying possible?

<details><summary>docker-compose.yaml</summary>
<p>

```yaml
services:
  traefik:
    command:
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false

      - --experimental.http3=true

      - --entryPoints.web.address=:80
      - --entryPoints.web.http.redirections.entryPoint.to=websecure

      - --entryPoints.websecure.address=:443
      - --entryPoints.websecure.http3

      - --certificatesResolvers.duckdns.acme.email=👀
      - --certificatesResolvers.duckdns.acme.storage=/letsencrypt/duckdns.json
      - --certificatesResolvers.duckdns.acme.dnsChallenge=true
      - --certificatesResolvers.duckdns.acme.dnsChallenge.provider=duckdns
      - --certificatesResolvers.duckdns.acme.dnsChallenge.resolvers=1.1.1.1:53,8.8.8.8:53
    container_name: traefik
    environment:
      - DUCKDNS_TOKEN=👀
    image: traefik:v2.10
    networks:
      - traefik
      - gluetun
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

      - ./traefik/letsencrypt:/letsencrypt

  gluetun:
    cap_add:
      - NET_ADMIN
    container_name: gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - SERVER_HOSTNAMES=👀.prod.surfshark.com
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_ADDRESSES=👀
      - WIREGUARD_PRIVATE_KEY=👀
      - HEALTH_TARGET_ADDRESS=127.0.0.1:9999

      - HTTPPROXY=on
      - HTTPPROXY_LOG=on
      - HTTPPROXY_USER=👀
      - HTTPPROXY_PASSWORD=👀
    image: ghcr.io/qdm12/gluetun
    labels:
      - traefik.enable=true

      - traefik.http.routers.gluetun.entryPoints=websecure
      - traefik.http.routers.gluetun.rule=Host(`👀.duckdns.org`)
      - traefik.http.routers.gluetun.service=gluetun

      - traefik.http.services.gluetun.loadBalancer.server.port=8888

      - traefik.http.routers.gluetun.tls.certResolver=duckdns
      - traefik.http.routers.gluetun.tls.domains[0].main=👀.duckdns.org
      - traefik.http.routers.gluetun.tls.domains[0].sans=*.👀.duckdns.org
    networks:
      - gluetun
    restart: unless-stopped
    volumes:
      - ./gluetun:/gluetun

networks:
  traefik:
    name: traefik

  gluetun:
    name: gluetun
```

</p>
</details>
