### DISCUSSION TITLE
Problems setting up an ARR stack.

### DISCUSSION THREAD

**Discussion by azazael13** [qdm12/gluetun#2299] [Q&A] [answered]
Good *whatever time of day it is for you*,

I am trying to get my ARR stack redone using docker instead of a cumbersome ubuntu setup. I have gluetun setup with PIA and it connects seems to work fine. I spun up a prowlarr and radarr docker as well. The problem I am running into is getting them to acknowledge each other.

When I use 'network_mode: "container:gluetun"' in the docker compose for prowlarr and radarr I am able to see access the UI's without issues, but as soon as I try to set them up to communicate with each other I am getting http time outs. Both containers are connected to gluetun (verified with curl ipconfig.io) but neither has an ip address listed (as shown with portainer).

I am guessing I am overlooking something small and stupid, but I have spent days on this, looked at numerous video's and just need another set of eye's at this point.

I am also aware of the issues PIA has with port forwarding, but didn't think that was the issue I was running into, maybe I am? I am open to switching to another VPN if that is what is causing all of these headaches. 

Below are my gluetun/prowlarr/radarr compose. I am more than happy to provide other logs or information, just let me know what is helpful.

```
#version: "3.38"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    restart: always
    ports:
      - 7878:7878/tcp #radarr
      - 8778:8778/tcp #radarr4k
      - 8080:8080/tcp #SAB
      - 8989:8989/tcp #sonarr
      - 9696:9696/tcp #prowlarr
      - 5055:5055       #Overseer
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=*redacted*
      - OPENVPN_PASSWORD=*redacted*
      - SERVER_REGIONS=Netherlands
```

```
---
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "container:gluetun"
    environment:
      - PUID=1035
      - PGID=65537
      - TZ=Etc/EST
    volumes:
      - /volume1/docker/prowlarr:/config
    restart: unless-stopped 
```

```
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr4k
    network_mode: "container:gluetun"
    environment:
      - PUID=1034
      - PGID=65537
      - TZ=Etc/EST
    volumes:
      - /volume1/docker/radarr4k:/config
      - /volume1/Video/4kMovies:/movies
    restart: unless-stopped
```
