### DISCUSSION TITLE
Tailscale container overwrites /etc/resolv.conf

### DISCUSSION THREAD

**Discussion by ghost** [qdm12/gluetun#2330] [Q&A]
For context: https://www.reddit.com/r/Tailscale/comments/1djpx3n/docker_compose_tailscale_exit_node_in_proxmox_lxc/

Somehow even gluetun's resolv.conf gets this content, no matter the config:
```
/ # cat /etc/resolv.conf 
# resolv.conf(5) file generated by tailscale
# For more info, see https://tailscale.com/s/resolvconf-overwrite
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

nameserver 100.100.100.100
search xxx.xx root.xxx.xx
```

And thus DNS is broken in both containers (gluetun and tailscale). Both of these work perfectly seperately.

How could I keep using Tailscale's DNS while also using Gluetun?

Current setup:
```yaml
services:

  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
#   dns:
#     - xxx
    environment:
      - VPN_SERVICE_PROVIDER=mullvad # hijack_dns?
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=xxx
      - WIREGUARD_ADDRESSES=xxx/32
      - SERVER_CITIES=xxx
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24 # tried adding ,100.100.100.100/32 didn't work
#     - DNS_ADDRESS=192.168.1.208
      - DOT=off
      - DNS_KEEP_NAMESERVER=on
    volumes:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped

  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:stable
    volumes:
      - ./tailscale:/var/lib
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    command: tailscaled
    privileged: true
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
```
