### DISCUSSION TITLE
Can I route a tailscale container through gluetun?

### DISCUSSION THREAD

**Discussion by forabi** [qdm12/gluetun#2396] [Q&A]
I can't seem to use the internet through the Tailscale exit node configured below. If I remove `network_mode`, it works fine, but of course it does not go through my VPN provider

```yml
services:
  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    networks:
      - caddy
      - default
    restart: always

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /media/f/data/docker/volumes/gluetun:/gluetun
    env_file:
      - gluetun.env
    environment:
      - TZ=Europe/Berlin
      - UPDATER_PERIOD=24h
      - SHADOWSOCKS=on

  tailscale:
    image: tailscale/tailscale:v1.70
    hostname: tailscale-docker
    container_name: tailscale
    network_mode: service:gluetun
    env_file:
      - tailscale.env
    user: root
    environment:
      - "TS_EXTRA_ARGS=--advertise-exit-node --advertise-tags=tag:ci,tag:container"
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=0
      - TS_AUTH_ONCE=1
    volumes:
      - /media/f/data/docker/volumes/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - SYS_ADMIN
      - NET_RAW
    restart: always
```
