### DISCUSSION TITLE
VPN a container in a podman pod

### DISCUSSION THREAD

**Discussion by mrepetto94** [qdm12/gluetun#2406] [Q&A]
Sorry for posting it here, but no one had an answer to this problem, apparently
I'm crushing my head over the way Podman does networking.

I have the following minimal Ansible playbook:

```
- name: Setup Media Server Pod
  hosts: localhost
  tasks:

    - name: Run Gluetun container for AirVPN
      containers.podman.podman_container:
        name: gluetun-airvpn
        image: docker.io/qmcgaw/gluetun:latest
        state: quadlet
        quadlet_dir: ~/.config/containers/systemd/
        env:
          TZ: Europe/Rome
          VPN_SERVICE_PROVIDER: airvpn
          VPN_TYPE: wireguard
          WIREGUARD_PRIVATE_KEY: xxx
          WIREGUARD_PRESHARED_KEY: xxx
          WIREGUARD_ADDRESSES: xxx
          SERVER_COUNTRIES: Switzerland
          FIREWALL_VPN_INPUT_PORTS: 13445
        cap_add:
          - NET_ADMIN
        privileged: true
        device:
          - /dev/net/tun:/dev/net/tun
        quadlet_options:
          - "AutoUpdate=registry"
          - |
            [Service]
            Restart=always
            RestartSec=5
          - |
            [Install]
            WantedBy=default.target


    - name: Create media pod
      containers.podman.podman_pod:
        name: media_server
        state: quadlet
        quadlet_dir: ~/.config/containers/systemd/
        quadlet_options:
          - |
            [Install]
            WantedBy=default.target
        ports:
          - 8096:8096 # jellyfin
          - 8080:8080 # qbittorrent

    - name: Run Jellyfin container
      containers.podman.podman_container:
        name: jellyfin
        image: docker.io/jellyfin/jellyfin:latest
        state: quadlet
        quadlet_dir: ~/.config/containers/systemd/
        pod: media_server.pod
        cap_add:
          - SYS_ADMIN
          - MKNOD
        device:
          - /dev/dri:/dev/dri:rwm
        quadlet_options:
          - "AutoUpdate=registry"
          - |
            [Service]
            Restart=always
            RestartSec=5
          - |
            [Install]
            WantedBy=default.target

    - name: Run qBittorrent container
      containers.podman.podman_container:
        name: qbittorrent
        image: ghcr.io/linuxserver/qbittorrent:latest
        state: quadlet
        quadlet_dir: ~/.config/containers/systemd/
        pod: media_server.pod
        network_mode:
          - container:gluetun-airvpn
        env:
          WEBUI_PORT: 8080
          TORRENTING_PORT: 13445
          PUID: 1000
          PGID: 1000
          TZ: Europe/Rome
        quadlet_options:
          - "AutoUpdate=registry"
          - |
            [Service]
            Restart=always
            RestartSec=5
          - |
            [Install]
            WantedBy=default.target


    - name: Reload systemd
      ansible.builtin.systemd_service:
        daemon_reload: true
        scope: user

    - name: Start Media Server Pod
      ansible.builtin.systemd_service:
        name: media_server-pod
        state: started
        scope: user
        enabled: true

    - name: Start Gluetun AirVPN
      ansible.builtin.systemd_service:
        name: gluetun-airvpn
        state: started
        scope: user
        enabled: true

    - name: Start Jellyfin
      ansible.builtin.systemd_service:
        name: jellyfin
        state: started
        scope: user
        enabled: true

    - name: Start qBittorrent
      ansible.builtin.systemd_service:
        name: qbittorrent
        state: started
        scope: user
        enabled: true
```

I can't make the qbitorrent container using the VPN inside the container. But If I build the container outside the pod I can. The problem is that I would like to use this container inside the pod. Has anyone figured out a solution?
