### DISCUSSION TITLE
How to use it with OpenVPN.

### DISCUSSION THREAD

**Discussion by Ch1ngg** [qdm12/gluetun#2408] [Q&A]
I want to use OpenVPN as the entry point. To pass all OpenVPN traffic through gluetun, I tried configuring it with network_mode, but it had no effect. he looks like this
```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - "61194:1194/tcp" 
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=123456
      - SERVER_COUNTRIES=Japan
    restart: unless-stopped

  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn-server
    cap_add:
      - NET_ADMIN
    volumes:
      - openvpn-data:/etc/openvpn
    environment:
      - OVPN_SERVER_URL=tcp://your-server-ip:1194
    network_mode: "service:gluetun"
    restart: unless-stopped

volumes
  openvpn-data:
```
OpenVPN will report the following error

```
Checking IPv6 Forwarding
Sysctl error for default forwarding, please run docker with '--sysctl net.ipv6.conf.default.forwarding=1'
Sysctl error for all forwarding, please run docker with '--sysctl net.ipv6.conf.all.forwarding=1'
Running 'openvpn --config /etc/openvpn/openvpn.conf --client-config-dir /etc/openvpn/ccd --crl-verify /etc/openvpn/crl.pem '
Sun Aug 11 11:21:40 2024 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
Sun Aug 11 11:21:40 2024 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
Sun Aug 11 11:21:40 2024 Diffie-Hellman initialized with 2048 bit key
Sun Aug 11 11:21:40 2024 CRL: loaded 1 CRLs from file /etc/openvpn/crl.pem
Sun Aug 11 11:21:40 2024 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Sun Aug 11 11:21:40 2024 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Sun Aug 11 11:21:40 2024 ROUTE_GATEWAY 172.18.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:12:00:02
Sun Aug 11 11:21:40 2024 ERROR: Cannot ioctl TUNSETIFF tun0: Invalid argument (errno=22)
Sun Aug 11 11:21:40 2024 Exiting due to fatal error
```
So how should I integrate OpenVPN?
Has anyone written a similar docker-compose configuration file?
