### DISCUSSION TITLE
Deployment error

### DISCUSSION THREAD

**Discussion by riddertommie** [qdm12/gluetun#2429] [Q&A]
As soon if i try to connect a container (in the same docker-compose file) i get below error in portainer.

![image](https://github.com/user-attachments/assets/4c1e25eb-736a-4ca8-95f9-470428ea56ba)

Is the feature no supported anymore?

I used with different containers all give the same.

below is a example with curl:

```
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-glue>
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8881:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /opt/gluetun:/gluetun
    environment:
      - PUID=1000
      - PGID=1000
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      # OpenVPN:
      # - OPENVPN_USER=
      # - OPENVPN_PASSWORD=
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_ADDRESSES=10.14.0.2/16
      # Timezone for accurate log times
      - TZ=Europe/Amsterdam
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=
      - SERVER_COUNTRIES=Netherlands
      # - SERVER_COUNTRIES=Belgium
    restart: always
  
  curl:
    image: curlimages/curl
    network_mode: "service:gluetun"
```

Do i make a mistake? any help welcome!
