### DISCUSSION TITLE
Issues with docker compose as a service and wg0.conf

### DISCUSSION THREAD

**Discussion by cal3k** [qdm12/gluetun#2457] [Q&A]
Hi all,

I've been playing around with Gluetun and an arr stack, and it's quite a nice thing.
I'm running docker on a proxmox LXC and my goal is to have everything back up and running when rebooting the proxmox container underneath docker. As such I've setup a simple service called arr:
```
[Unit]
Description=Docker ARR Stack
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/bash -c "docker compose -p arr -f ~/docker-compose.yaml up -d"
ExecStop=/bin/bash -c "docker compose -p arr stop"

[Install]
WantedBy=multi-user.target
```
The problem I'm having is no matter what I do if I start the service guletun completely ignores the wg0.conf file. If I manually start it with docker compose everything is great.
This is my gluetun section:

```
  # Gluetun/VPN ================================
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 3000:3000 #firefox
      - 3001:3001 #firefox
      - 6500:6500 #rdtclient
      - 6881:6881 # qbit
      - 6881:6881/udp # qbit
      - 7878:7878 # Radarr
      - 8085:8085 # qbit Webui
      - 8191:8191 # FlareSolverr
      - 8989:8989 # Sonarr
      - 9117:9117 # Jackett
      - 9696:9696 # Prowlarr
    volumes:
      - ~/.docker:/gluetun
      - ~/.docker/wireguard/wg0.conf:/gluetun/wireguard/wg0.conf
      # bind custom wg0 to the inside of the container
    environment:
      - DOT=on
      - BLOCK_MALICIOUS=on
      - BLOCK_SURVEILLANCE=on
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY= <redacted>
      - WIREGUARD_PUBLIC_KEY= <redacted>
      - WIREGUARD_ENDPOINT_IP= <redacted>
      - WIREGUARD_ALLOWED_IPS=0.0.0.0/0
      - WIREGUARD_ENDPOINT_PORT= <redacted>
      - WIREGUARD_ADDRESSES= <redacted>
      - FIREWALL_VPN_INPUT_PORTS=6881
      - HEALTH_VPN_DURATION_INITIAL=120s
      - UPDATER_PERIOD=24h
    restart: always
```
All the redacted settings work perfectly fine inside wg0.conf if I start the stack manually. The screenshots below list the type of startup and where those 5 settings are found. The same is valid for any single setting, not all at once.

![image](https://github.com/user-attachments/assets/993caf48-8144-40c0-8e6d-0741bb382ccd)

![image](https://github.com/user-attachments/assets/1f26cb35-ba03-4668-b4f3-c581c7be14bc)

![image](https://github.com/user-attachments/assets/cf08caa6-fbac-442b-a13a-6939cdfde449)

I tried finding anything related of that warning that the config file is ignored, but I could not find anything.
I would rather have the ability to use the wireguard config file, mainly for "unfirewalling"/port forwarding in qbit... which sometimes works and sometimes doesn't....but that's a different issue :)

I'd appreciate any help.
