### DISCUSSION TITLE
Can't connect with Cyberghost and Gluetun with OpenVPN.

### DISCUSSION THREAD

**Discussion by JasonReb0rn** [qdm12/gluetun#2477] [Q&A]
Hello,

I'm trying to use cyberghost with gluetun as a part of [YAMS](https://yams.media/). I've been running into some trouble and could use some help.

This is what the glueton portion of my docker-compose.yaml looks like:
```  
    gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8080:8080/tcp # gluetun
    volumes:
      - ${INSTALL_DIRECTORY}/config/gluetun:/config
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE}
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
    restart: unless-stopped
```

No matter what I do, the gluetun docker container enters a reboot-loop with the log simply stating:
```
2024-09-08T01:21:33Z INFO [firewall] enabling...
2024-09-08T01:21:33Z INFO [firewall] enabled successfully
2024-09-08T01:21:33Z INFO [storage] merging by most recent 20480 hardcoded servers and 20480 servers read from /gluetun/servers.json
2024-09-08T01:21:33Z ERROR VPN settings: OpenVPN settings: client certificate: missing value
2024-09-08T01:21:33Z INFO Shutdown successful
```

Cyberghost supplied me with the files 'ca.crt', 'client.crt', 'client.key' and 'openvpn.ovpn', which are placed in /opt/yams/config/gluetun.

Any help would be much appreciated! Thanks.
