### DISCUSSION TITLE
dialing DoT server

### DISCUSSION THREAD

**Discussion by Henrique-DeSousa** [qdm12/gluetun#2487] [Q&A]
Hello!

I'm currently having the following warning, over and over again and I do not know what could be the issue. I opened port 853 in my firewall, should I also attach the port to the container?   I have block ads and all that stuff blocked in the Wireguard configuration from mullvad and also in the compose file.

`dialing DoT server: dial tcp 1.0.0.1:853: i/o timeout`

```
services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    hostname: gluetun
    healthcheck: 
      test: ping -c 1 8.8.8.8
    cap_add:
      - NET_ADMIN
    ports:	
      - "Ports:Ports"
      - "Port2:Port2"
    environment:
      - BLOCK_ADS=on
      - BLOCK_SURVEILLANCE=on
      - TZ=
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=key
      - WIREGUARD_ADDRESSES=Address
      - WIREGUARD_ENDPOINT_PORT=12345
      - SERVER_COUNTRIES="Sweden,Finland"
      - SERVER_CITIES="Stockholm,Helsinki"
      - UPDATER_PERIOD=12h
    volumes:
      - /Home/Docker/Gluetun:/gluetun
    restart: unless-stopped
```
