### DISCUSSION TITLE
How to route a container's traffic through gluetun while keeping connectivity between them

### DISCUSSION THREAD

**Discussion by SuperCuber** [qdm12/gluetun#2500] [Q&A]
I'd like to route outgoing connections from a single container in my docker-compose setup through a VPN, while keeping connectivity in my network. I followed [the wiki](https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md), and I have something along the lines of
```yml
version: '3.3'
services:
  db:
    image: mongo
  api:
    image: -snip- # has the outgoing connection
    depends_on:
      - db
    network_mode: "service:gluetun" # is this right?
  server:
    image: -snip- # reverse proxy over the server
    depends_on:
      - api
    ports:
      - 8000:80
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - SERVER_COUNTRIES=Netherlands
      - FREE_ONLY=on
      - OPENVPN_USER=-snip-
      - OPENVPN_PASSWORD=-snip-
```

When I start up the server, it can no longer resolve the host `db:27017` that it could before (without the `network_mode`).

I tried adding `ports: - 27017:27017` to the `db` container but it does not help :( any ideas?
