### DISCUSSION TITLE
HELP: Diagnose Docker Compose for StreamMaster Behind Gluetun

### DISCUSSION THREAD

**Discussion by rammjet** [qdm12/gluetun#2539] [Q&A]
I am trying to run the streaming app StreamMaster behind gluetun.

StreamMaster works fine by itself, but once I place it behind gluetun, steams cannot be accessed.

I have verified that gluetun is connected to the target server and can access the internet.

I keep both in separate docker containers.  Here are my docker compose files. Can anyone see what is wrong?

```
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 7095:7095 # streammaster
    volumes:
      - /mnt/Storage/Docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=123
      - OPENVPN_PASSWORD=123
      - SERVER_REGIONS=Netherlands
    restart: unless-stopped


services:
  streammaster:
    image: senexcrenshaw/streammaster:latest
    container_name: streammaster
    network_mode: "container:gluetun"
#    ports:
#      - 7095:7095
#      - 7096:7096 # Only for SSL
    environment:
      - PUID=1000 # UID to Run As
      - PGID=1000 # GID to Run As
      - TZ=America/New_York
    restart: unless-stopped
    volumes:
      - /mnt/Storage/Docker/streammaster/config:/config
      - /mnt/Storage/Docker/streammaster/tv-logos:/config/tv-logos
    devices:
      - /dev/dri:/dev/dri
```
