### DISCUSSION TITLE
"Inactivity timeout (--ping-restart)" in container; no error on host

### DISCUSSION THREAD

**Discussion by cassdeckard** [qdm12/gluetun#2545] [Q&A]
I started seeing this problem shortly after starting use of gluetun in a docker compose configuration with [qbittorrent](https://hub.docker.com/r/linuxserver/qbittorrent):

```yaml
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - WEBUI_PORT=6011
    volumes:
      - /home/cass/.config/qbittorrent:/config
      - type: volume
        source: nas
        target: /nas
        volume:
          nocopy: true
    network_mode: "service:gluetun"
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun:v3.35
    container_name: gluetun
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - MKNOD
    ports:
      - 6081:6881     # qbittorrent
      - 6081:6881/udp # qbittorrent
      - 6011:6011     # qbittorrent web ui
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_CUSTOM_CONFIG=/gluetun/REDACTED.ovpn
      - OPENVPN_USER=REDACTED
      - OPENVPN_PASSWORD=REDACTED
      - OPENVPN_FLAGS=--mute-replay-warnings --dhcp-option DNS 209.222.18.222 --dhcp-option DNS 209.222.18.218
      - OPENVPN_VERBOSITY=4
      - TZ=America/Los_Angeles
    volumes:
      - /home/cass/.config/gluetun:/gluetun
    restart: unless-stopped

volumes:
  nas:
    driver: local
    driver_opts:
      type: none
      device: /mnt/nas
      o: bind

```

If I run openvpn via systemd on the host machine, I get no issues whatsoever. This is using the same config file I have the gluetun container using.

However, when I run gluetun in the container, every 1-3 minutes it will restart with errors like this:
```
2024-10-26T19:04:07-07:00 INFO [openvpn] [uswvpn.REDACTED.org] Inactivity timeout (--ping-restart), restarting
2024-10-26T19:04:07-07:00 INFO [openvpn] SIGUSR1[soft,ping-restart] received, process restarting
2024-10-26T19:04:07-07:00 INFO [openvpn] Restart pause, 10 second(s)
2024-10-26T19:04:10-07:00 INFO [healthcheck] program has been unhealthy for 6s: restarting VPN
2024-10-26T19:04:10-07:00 INFO [healthcheck] 👉 See https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md
2024-10-26T19:04:10-07:00 INFO [healthcheck] DO NOT OPEN AN ISSUE UNLESS YOU READ AND TRIED EACH POSSIBLE SOLUTION
2024-10-26T19:04:10-07:00 INFO [vpn] stopping
2024-10-26T19:04:10-07:00 INFO [vpn] starting
```

Host: Linux raspberrypi 6.6.28+rpt-rpi-2712 \#\1 SMP PREEMPT Debian 1:6.6.28-1+rpt1 (2024-04-22) aarch64 GNU/Linux

I'm attaching more complete logs from both gluetun and openvpn via systemd on host. I'm thinking since it runs fine straight on the host, it isn't a problem with the VPN server or my client configuration, but rather with my Docker configuration?

Any help would be greatly appreciated!

[log-gluetun1.txt](https://github.com/user-attachments/files/17532608/log-gluetun1.txt)
[log-systemd.txt](https://github.com/user-attachments/files/17532609/log-systemd.txt)
