### DISCUSSION TITLE
Cannot specify server/region on PIA

### DISCUSSION THREAD

**Discussion by SyfSchydea** [qdm12/gluetun#2552] [Q&A]
I'm trying to setup Gluetun with private internet access at the moment. My container seems to be connecting to *a* PIA server correctly, but seems to be completely random as to which one it connects to.

[The setup page](https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/private-internet-access.md) lists `SERVER_REGIONS`, `SERVER_NAMES`, `SERVER_HOSTNAMES` as ways of specifying a specific server to connect to. 
They specifically give `SERVER_REGIONS=Netherlands` as an example. I try this, it connects me to Douglas instead, another time, Baltimore.

I've tried various other regions, and combinations of names and hostnames (as returned by `sudo docker run --rm -v ./gluetun:/gluetun qmcgaw/gluetun format-servers -private-internet-access`, which should give the full list of available servers), but it never connects me to the server I'm trying to specify.

Does anyone know if this is a bug, or if I'm doing something wrong in my setup?

I'm running on Ubuntu 24.04.1 LTS, x86_64
Running version latest built on 2024-10-28T09:25:35.847Z (commit f1f3472)

Using this compose file:
```yaml
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - SERVER_REGIONS=Netherlands
      - OPENVPN_USER=blah
      - OPENVPN_PASSWORD=blah
```
