### DISCUSSION TITLE
Issues connecting to Proton with both OpenVPN and Wireguard

### DISCUSSION THREAD

**Discussion by jgeorgeson** [qdm12/gluetun#2555] [Q&A]
I have gluetun v3 running via compose on a Synology DSM 7.2 NAS. It routinely will just get into a state with no connectivity and I have to destroy and recreate the gluetun container. I typically will run a manual server update before recreating. A few days ago my internet service went down, and I haven't been able to get gluetun to connect again since then. I am able to connect Proton VPN clients using same account and server settings, so I at least know that in general I am able to make the VPN connection from this network.

Compose file:

```yaml
services:
  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: vpn-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      - DOT=on
      - DOT_PROVIDERS=cloudflare,google
      - FIREWALL_OUTBOUND_SUBNETS=172.16.0.0/12,192.168.68.0/24
      - HTTPPROXY=off #change to on if you wish to enable
      - OPENVPN_ENDPOINT_PORT=443
      - OPENVPN_USER=[redacted]+pmp
      - OPENVPN_PASSWORD=[redacted]
      - PORT_FORWARD_ONLY=on
      - PGID=65538 #CHANGE_TO_YOUR_GID
      - PUID=1034 #CHANGE_TO_YOUR_UID
      - SERVER_CITIES=New York,Denver,Los Angeles,Chicago
      - SERVER_COUNTRIES=United States
      - SHADOWSOCKS=off #change to on if you wish to enable
      - TZ=America/Chicago
      - UPDATER_PERIOD=24h
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
    network_mode: gluetunbridge
    labels:
      - com.centurylinklabs.watchtower.enable=false
    security_opt:
      - no-new-privileges:true
    restart: always
```

Here is the command I use to run the manual server update (which appears to working fine at the moment, despite the issue I'm having, so I know that the bridge network for the gluetun container isn't the issue)

```shell
docker run --rm -v /volume1/docker/gluetun:/gluetun --network gluetunbridge qmcgaw/gluetun:v3 update --enduser --providers protonvpn
```

Typical errors

```
vpn-gluetun  | 2024-10-31T11:14:45-05:00 INFO [vpn] starting
vpn-gluetun  | 2024-10-31T11:14:45-05:00 INFO [firewall] allowing VPN connection...
vpn-gluetun  | 2024-10-31T11:14:45-05:00 INFO [openvpn] OpenVPN 2.6.11 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD]
vpn-gluetun  | 2024-10-31T11:14:45-05:00 INFO [openvpn] library versions: OpenSSL 3.3.2 3 Sep 2024, LZO 2.10
vpn-gluetun  | 2024-10-31T11:14:45-05:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]149.22.80.55:443
vpn-gluetun  | 2024-10-31T11:14:45-05:00 INFO [openvpn] UDPv4 link local: (not bound)
vpn-gluetun  | 2024-10-31T11:14:45-05:00 INFO [openvpn] UDPv4 link remote: [AF_INET]149.22.80.55:443
vpn-gluetun  | 2024-10-31T11:15:42-05:00 INFO [healthcheck] program has been unhealthy for 56s: restarting VPN
vpn-gluetun  | 2024-10-31T11:15:42-05:00 INFO [healthcheck] 👉 See https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md
vpn-gluetun  | 2024-10-31T11:15:42-05:00 INFO [healthcheck] DO NOT OPEN AN ISSUE UNLESS YOU READ AND TRIED EACH POSSIBLE SOLUTION
vpn-gluetun  | 2024-10-31T11:15:42-05:00 INFO [vpn] stopping
vpn-gluetun  | 2024-10-31T11:15:42-05:00 INFO [vpn] starting
vpn-gluetun  | 2024-10-31T11:15:42-05:00 INFO [firewall] allowing VPN connection...
vpn-gluetun  | 2024-10-31T11:15:42-05:00 INFO [openvpn] OpenVPN 2.6.11 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD]
vpn-gluetun  | 2024-10-31T11:15:42-05:00 INFO [openvpn] library versions: OpenSSL 3.3.2 3 Sep 2024, LZO 2.10
vpn-gluetun  | 2024-10-31T11:15:42-05:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]146.70.174.194:443
vpn-gluetun  | 2024-10-31T11:15:42-05:00 INFO [openvpn] UDPv4 link local: (not bound)
vpn-gluetun  | 2024-10-31T11:15:42-05:00 INFO [openvpn] UDPv4 link remote: [AF_INET]146.70.174.194:443
vpn-gluetun  | 2024-10-31T11:16:42-05:00 WARN [openvpn] TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
vpn-gluetun  | 🚒🚒🚒🚒🚒🚨🚨🚨🚨🚨🚨🚒🚒🚒🚒🚒
vpn-gluetun  | That error usually happens because either:
vpn-gluetun  | 
vpn-gluetun  | 1. The VPN server IP address you are trying to connect to is no longer valid 🔌
vpn-gluetun  |    Check out https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
vpn-gluetun  | 
vpn-gluetun  | 2. The VPN server crashed 💥, try changing your VPN servers filtering options such as SERVER_REGIONS
vpn-gluetun  | 
vpn-gluetun  | 3. Your Internet connection is not working 🤯, ensure it works
vpn-gluetun  | 
vpn-gluetun  | 4. Something else ➡️ https://github.com/qdm12/gluetun/issues/new/choose
vpn-gluetun  | 
vpn-gluetun  | 2024-10-31T11:16:42-05:00 INFO [openvpn] TLS Error: TLS handshake failed
vpn-gluetun  | 2024-10-31T11:16:42-05:00 INFO [openvpn] SIGTERM received, sending exit notification to peer
vpn-gluetun  | 2024-10-31T11:16:42-05:00 INFO [openvpn] SIGTERM[soft,tls-error] received, process exiting
vpn-gluetun  | 2024-10-31T11:16:42-05:00 INFO [vpn] retrying in 15s
vpn-gluetun  | 2024-10-31T11:16:43-05:00 INFO [healthcheck] program has been unhealthy for 1m1s: restarting VPN
vpn-gluetun  | 2024-10-31T11:16:43-05:00 INFO [healthcheck] 👉 See https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md
vpn-gluetun  | 2024-10-31T11:16:43-05:00 INFO [healthcheck] DO NOT OPEN AN ISSUE UNLESS YOU READ AND TRIED EACH POSSIBLE SOLUTION
vpn-gluetun  | 2024-10-31T11:16:57-05:00 INFO [firewall] allowing VPN connection...
vpn-gluetun  | 2024-10-31T11:16:57-05:00 INFO [openvpn] OpenVPN 2.6.11 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD]
vpn-gluetun  | 2024-10-31T11:16:57-05:00 INFO [openvpn] library versions: OpenSSL 3.3.2 3 Sep 2024, LZO 2.10
vpn-gluetun  | 2024-10-31T11:16:57-05:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]146.70.202.162:443
vpn-gluetun  | 2024-10-31T11:16:57-05:00 INFO [openvpn] UDPv4 link local: (not bound)
vpn-gluetun  | 2024-10-31T11:16:57-05:00 INFO [openvpn] UDPv4 link remote: [AF_INET]146.70.202.162:443
vpn-gluetun  | 2024-10-31T11:17:57-05:00 INFO [vpn] retrying in 15s

```
And here is the full [gluetun.log](https://github.com/user-attachments/files/17591738/gluetun.log)

I have tried changing the `SERVER_CITIES` value, even completely commenting it out to test with any US server, no help. I've tried commenting out the `OPENVPN_ENDPOINT_PORT` variable to toggle between TCP and UDP. I've tried using Wireguard instead of OpenVPN but that was failing on the external IP lookup/verification with DNS timeout issues (sorry, didn't save the logs). Since I'm on Synology, though, I want to keep it with OpenVPN as there's no kernel support for Wireguard without a third-party build of the module(s).
