### DISCUSSION TITLE
UDP OpenVPN connection to PIA causes all network traffic in the host to become sluggish

### DISCUSSION THREAD

**Discussion by mpriem** [qdm12/gluetun#2562] [Q&A]
I'm using gluetun to tunnel traffic of two containers. This now works like a charm, but I had this weird issue when using the default configuration of OpenVPN would cause the entire network of all containers (also other containers in other bridge networks) and the host to become extremely sluggish. Pings to hosts internally and externally would go from milliseconds to hundreds of milliseconds. The host cpu, disk and memory are totally fine. It seems to be something fully network related. The moment I stop the gluetun container the network would go back to normal for all other containers, networks and the host.

I then continued to try various approaches, but what ultimately solved the issue was to add the `OPENVPN_PROTOCOL=tcp` environment variable to the gluetun container.

Even though this solves my issue I really would want to understand what could have been happening. Can someone help me understand what might be the issue? How can I troubleshoot this? 

I'm using a Debian pixie server, which runs on a 2019 Intel NUC with an I219-V NIC.

My docker compose can be found below.

```
version: "3"
services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=<user>
      - OPENVPN_PASSWORD=<pw>
      - SERVER_REGIONS=<region>
      - OPENVPN_PROTOCOL=tcp
    ports:
      - '6881:6881/tcp'
      - '6881:6881/udp'
      - '9117:9117'
      - '8080:8080/tcp'
    networks:
      - gluetun_network
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - AUTO_UPDATE=true
    volumes:
      - '/srv/jackett/config/:/config'
      - '/srv/jackett/downloads/:/downloads'
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
  qbittorrent-nox:
    container_name: qbittorrent
    environment:
      - QBT_LEGAL_NOTICE=confirm
      - QBT_VERSION=latest
      - QBT_WEBUI_PORT=8080
    image: qbittorrentofficial/qbittorrent-nox:latest
    read_only: true
    stop_grace_period: 30m
    network_mode: "service:gluetun"
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - /srv/qbittorrent/config/:/config
      - /srv/qbittorrent/downloads/:/downloads
    depends_on:
      - gluetun
networks:
  gluetun_network:
    driver: bridge
```
