### DISCUSSION TITLE
Hot to get Host-IP from a local WireGuard Server

### DISCUSSION THREAD

**Discussion by shoutmarble** [qdm12/gluetun#2602] [Q&A]
I'm running a WireGuard server to try and forward the Host's IP to a child container using gluetun.

I'm testing with my VPN on my VPS with WHOAMI which will later be an email server which requires 
the HOST IP for CNAME, A, AAAA, etc records.

```
  root@server:~/wireguard/wireguard_conf/peer1# cat peer1.conf                 
                                                  ┌───────────────────────────┐
  [Interface]                       ┌─────────────┤ I don't want my WHOAMI to │
┌──────────────────────┐            │             │ use the WireGuard IP      │
│ Address = 10.13.13.2 ◀────────────┘             └───────────────────────────┘
└──────────────────────┘                                                       
  PrivateKey = SColjufKpaq44OZJpxhCBgiecaLqVPhTTuwW+5WqLGg=                    
                                                                               
  ListenPort = 51820                                                           
                                                                               
  DNS = 10.13.13.1                                                             
                                                                               
  [Peer]                                                                       
                                                                               
  PublicKey = OGOy5Qh2afc9Blmx9Xguqs+21XKwXVrSzl48qbKz5V0=                     
                                                                               
  PresharedKey = 60HcCQN+s4qbcZcvnOweEJbYy0jbLZ04SrdYxAqUIm8=                  
┌────────────────────────────────┐             ┌────────────────────────┐      
│ Endpoint = 185.28.22.166:51820 ◀─────────────┤I want my WHOAMI service│      
└────────────────────────────────┘             │to use this HOST's IP   │      
  AllowedIPs = 0.0.0.0/0                       └────────────────────────┘      
                                                                               
                                                                               
```

`compose.yml`
`docker compose up`
```
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/North_Dakota/Beulah
      - SERVERURL=185.28.22.166 #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./wireguard_conf:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

`gluetun.yml`
`docker compose -f gluetun.yml up`
```
services:
    gluetun:
        image: qmcgaw/gluetun
        container_name: gluetun
        cap_add:
            - NET_ADMIN
        ports:
            - "2001:2001"
            - "80:80"
            - "443:443" # JMAP
            - "25:25"
            - "110:110"
            - "143:143"
            - "465:465"
            - "587:587"
            - "993:993"
            - "995:995"
            - "4190:4190"
            - "8080:8080"
            - "8443:8443"
        devices:
          - /dev/net/tun:/dev/net/tun
        volumes:
            - ./gluetun_conf:/gluetun
        restart: unless-stopped
        environment:
            - VPN_SERVICE_PROVIDER=custom
            - VPN_TYPE=wireguard
            # - WIREGUARD_ENDPOINT_IP=10.13.13.2
            - WIREGUARD_ENDPOINT_IP=185.28.22.166
            - WIREGUARD_ENDPOINT_PORT=51820
            - WIREGUARD_PRIVATE_KEY=SColjufKpaq44OZJpxhCBgiecaLqVPhTTuwW+5WqLGg=
            - WIREGUARD_PUBLIC_KEY=OGOy5Qh2afc9Blmx9Xguqs+21XKwXVrSzl48qbKz5V0=
            # - WIREGUARD_ADDRESSES=185.28.22.166
            - WIREGUARD_ADDRESSES=10.13.13.2/32
            - WIREGUARD_PRESHARED_KEY=60HcCQN+s4qbcZcvnOweEJbYy0jbLZ04SrdYxAqUIm8=
```

`whoami.yml`
`docker compose -f whoami.yml up`
```
services:

    whoami:
        image: traefik/whoami
        container_name: whoami
        command:
            - --port=2001
        network_mode: "container:gluetun"
        restart: unless-stopped
```

`whoami.landingdev.xyz:2001`
```
  Hostname: 148fb89fab5c                                                                                                                         
                                                                                                                                                 
  IP: 127.0.0.1                                                                                                                                  
                                                                                                                                                 
  IP: ::1                                        VPS Server's Host IP                                                                            
┌────────────────┐                              ┌───────────────┐                                                                                
│ IP: 10.13.13.2 ◀──────────────────────────────┤ 185.28.22.166 │                                                                                
└────────────────┘                              └───────────────┘                                                                                
  IP: 172.18.0.3                                                                                                                                 
                                                                                                                                                 
  RemoteAddr: 66.51.236.224:52626                                                                                                                
  GET / HTTP/1.1                                                                                                                                 
  Host: test.landingdev.xyz:2001                                                                                                                 
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36                    
  Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
  Accept-Encoding: gzip, deflate                                                                                                                 
  Accept-Language: en-US,en-CA;q=0.9,en-AU;q=0.8,en;q=0.7                                                                                        
  Connection: keep-alive                                                                                                                         
  Dnt: 1                                                                                                                                         
  Upgrade-Insecure-Requests: 1                                                                                                                   
                                                                                                                                                 
```

**Comment by shoutmarble** [comment]
Update:
I have my HOST IP being used in my WHOAMI service
```
  Hostname: a3dc00f12fdc                                                                                                                          
                                                                                                                                                  
  IP: 127.0.0.1                                                                                                                                   
                                                                                                                                                  
  IP: ::1                                                                                                                                         
                                                                                                                                                  
┌───────────────────┐            ┌──────────────────────────────────────────┐                                                                     
│ IP: 185.28.22.166 ◀────────────┤ I got the "HOST IP" in my WHOAMI service │                                                                     
└───────────────────┘            └──────────────────────────────────────────┘                                                                     
                                                                                                                                                  
  IP: 172.18.0.3                                                                                                                                  
                                                                                                                                                  
  RemoteAddr: 66.51.236.224:52778                                                                                                                 
                                                                                                                                                  
  GET / HTTP/1.1                                                                                                                                  
                                                                                                                                                  
  Host: test.landingdev.xyz:2001                                                                                                                  
                                                                                                                                                  
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36                     
                                                                                                                                                  
  Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7 
                                                                                                                                                  
  Accept-Encoding: gzip, deflate                                                                                                                  
                                                                                                                                                  
  Accept-Language: en-US,en-CA;q=0.9,en-AU;q=0.8,en;q=0.7                                                                                         
                                                                                                                                                  
  Cache-Control: max-age=0                                                                                                                        
                                                                                                                                                  
  Connection: keep-alive                                                                                                                          
                                                                                                                                                  
  Dnt: 1                                                                                                                                          
                                                                                                                                                  
  Upgrade-Insecure-Requests: 1                                                                                                                    
```

```
services:
    gluetun:
        image: qmcgaw/gluetun
        container_name: gluetun
        cap_add:
            - NET_ADMIN
        ports:
            - "2001:2001"
            - "80:80"
            - "443:443" # JMAP
            - "25:25"
            - "110:110"
            - "143:143"
            - "465:465"
            - "587:587"
            - "993:993"
            - "995:995"
            - "4190:4190"
            - "8080:8080"
            - "8443:8443"
        devices:
          - /dev/net/tun:/dev/net/tun
        volumes:
            - ./gluetun_conf:/gluetun
        restart: unless-stopped
        environment:
            - VPN_SERVICE_PROVIDER=custom
            - VPN_TYPE=wireguard
            # - WIREGUARD_ENDPOINT_IP=10.13.13.2
            - WIREGUARD_ENDPOINT_IP=185.28.22.166
            - WIREGUARD_ENDPOINT_PORT=51820
            - WIREGUARD_PRIVATE_KEY=SColjufKpaq44OZJpxhCBgiecaLqVPhTTuwW+5WqLGg=
            - WIREGUARD_PUBLIC_KEY=OGOy5Qh2afc9Blmx9Xguqs+21XKwXVrSzl48qbKz5V0=
            - WIREGUARD_ADDRESSES=185.28.22.166  <----- set the endpoint to be the HOST's IP
            - WIREGUARD_PRESHARED_KEY=60HcCQN+s4qbcZcvnOweEJbYy0jbLZ04SrdYxAqUIm8=
```

I now only need to figure out how to IGNORE this in my LOG files in GLUETUN.
```
gluetun  | 2024-11-25T19:47:30Z INFO [healthcheck] 👉 See https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md
gluetun  | 2024-11-25T19:47:30Z INFO [healthcheck] DO NOT OPEN AN ISSUE UNLESS YOU READ AND TRIED EACH POSSIBLE SOLUTION
gluetun  | 2024-11-25T19:47:30Z INFO [vpn] stopping
gluetun  | 2024-11-25T19:47:30Z ERROR [vpn] getting public IP address information: fetching information: Get "https://ipinfo.io/": context canceled
gluetun  | 2024-11-25T19:47:30Z ERROR [vpn] cannot get version information: Get "https://api.github.com/repos/qdm12/gluetun/commits": context canceled
gluetun  | 2024-11-25T19:47:30Z INFO [vpn] starting
gluetun  | 2024-11-25T19:47:30Z INFO [firewall] allowing VPN connection...
gluetun  | 2024-11-25T19:47:30Z INFO [wireguard] Using available kernelspace implementation
gluetun  | 2024-11-25T19:47:30Z INFO [wireguard] Connecting to 185.28.22.166:51820
gluetun  | 2024-11-25T19:47:30Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
gluetun  | 2024-11-25T19:47:35Z INFO [dns] downloading hostnames and IP block lists
gluetun  | 2024-11-25T19:47:40Z ERROR [vpn] getting public IP address information: fetching information: Get "https://ipinfo.io/": dial tcp: lookup ipinfo.io on 1.1.1.1:53: read udp 185.28.22.166:36692->1.1.1.1:53: i/o timeout
gluetun  | 2024-11-25T19:47:42Z INFO [healthcheck] program has been unhealthy for 11s: restarting VPN (healthcheck error: dialing: dial tcp4: lookup cloudflare.com: i/o timeout)
gluetun  | 2024-11-25T19:47:42Z INFO [healthcheck] 👉 See https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md
gluetun  | 2024-11-25T19:47:42Z INFO [healthcheck] DO NOT OPEN AN ISSUE UNLESS YOU READ AND TRIED EACH POSSIBLE SOLUTION
gluetun  | 2024-11-25T19:47:42Z INFO [vpn] stopping
gluetun  | 2024-11-25T19:47:42Z INFO [vpn] starting
gluetun  | 2024-11-25T19:47:42Z INFO [firewall] allowing VPN connection...
gluetun  | 2024-11-25T19:47:42Z INFO [wireguard] Using available kernelspace implementation
gluetun  | 2024-11-25T19:47:42Z INFO [wireguard] Connecting to 185.28.22.166:51820
gluetun  | 2024-11-25T19:47:42Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
gluetun  | 2024-11-25T19:47:45Z WARN [dns] cannot update filter block lists: Get "https://raw.githubusercontent.com/qdm12/files/master/malicious-hostnames.updated": dial tcp: lookup raw.githubusercontent.com on 1.1.1.1:53: read udp 185.28.22.166:47540->1.1.1.1:53: i/o timeout, Get "https://raw.githubusercontent.com/qdm12/files/master/malicious-ips.updated": dial tcp: lookup raw.githubusercontent.com on 1.1.1.1:53: read udp 185.28.22.166:47540->1.1.1.1:53: i/o timeout
gluetun  | 2024-11-25T19:47:45Z INFO [dns] attempting restart in 20s
gluetun  | 2024-11-25T19:47:52Z ERROR [vpn] getting public IP address information: fetching information: Get "https://ipinfo.io/": dial tcp: lookup ipinfo.io on 1.1.1.1:53: read udp 185.28.22.166:57844->1.1.1.1:53: i/o timeout
gluetun  | 2024-11-25T19:48:02Z INFO [healthcheck] program has been unhealthy for 16s: restarting VPN (healthcheck error: dialing: dial tcp4: lookup cloudflare.com: i/o timeout)
gluetun  | 2024-11-25T19:48:02Z INFO [healthcheck] 👉 See https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md
gluetun  | 2024-11-25T19:48:02Z INFO [healthcheck] DO NOT OPEN AN ISSUE UNLESS YOU READ AND TRIED EACH POSSIBLE SOLUTION
```
