### DISCUSSION TITLE
401 thrown when attempting to access control server

### DISCUSSION THREAD

**Discussion by sugzone** [qdm12/gluetun#2653] [Q&A]
Attempting to access control server at port :8000. Everything else is working and logging just fine.

Error:
`2025-01-10T02:13:37Z INFO [http server] 401 GET /v1/openvpn/portforwarded wrote 13B to 172.18.0.1:57486 in 12.573µs`

Here's my Docker Compose:
```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun 
    volumes:
      - /github/lv-server/config.toml:/gluetun/auth/config.toml
    environment:
      - TZ=Etc/US
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - FIREWALL_VPN_INPUT_PORTS=8080,6080,50000,20911,9000,8000,61012,61013,2416
      - FIREWALL_INPUT_PORTS=8080,6080,50000,20911,9000,8000,61012,61013,2416
      - SERVER_COUNTRIES=United States
    ports:
      - 6080:6080
      - 8000:8000
      - 8080:8080
      - 20911:20911
      - 20911:20911/tcp
      - 50000:50000
      - 9000:9000
      - 61012:61012
      - 61013:61013 
      - 2416:2416
      - 8000:8000/tcp
    restart: unless-stopped
```
