### DISCUSSION TITLE
Tailscale connect to containers protected by gluetun

### DISCUSSION THREAD

**Discussion by ExcaliburVT** [qdm12/gluetun#2668] [Q&A]
I commonly have my docker containers set up with Tailscale so that I am able to access the container pages through my tailnet.
https://tailscale.com/kb/1282/docker

For instance, I am able to connect to sonarr using my tailnet https:// url and it makes everything nice and secure as well has HTTPS.

---break

I also have set up several containers with gluetun, and I am able to access their container pages by adding their ports to the gluetun ports list.  This makes those pages only accessible on my local network and doesn't let me use the Tailscale https setup.

Is it possible to add one (or more) Tailscale containers to the gluetun network in a way that I get the best of both worlds?  The main thing is to ensure that the security of gluetun outbound is not compromised.  The connection from the Tailnet should only be inbound, and I am not trying to do anything with an exit node in this scenario.

The main problem I'm facing is that the docker setup for both gluetun and tailscale requires the "app" containers to use network_mode of service like:
network_mode: "service:gluetun"

Thanks in advance!

**Comment by Pyro2677** [comment]
I would like to know this also.

**Comment by the-eversio** [comment]
I've wanted this for ages, and I _think_ this solved it.

```
services:
  gluetun:
    image: qmcgaw/gluetun
    # normal gluetun stuff
  sonarr:
    image: sonarr # whatever app you want
    network_mode: service:gluetun # use gluetun's network namespace
    # ...
  tailscale-sidecar:
    image: tailscale/tailscale:latest
    network_mode: service:gluetun # This is key! Tailscale shares the same network namespace as gluetun and your app.
    volumes:
      - tailscale-state:/var/lib/tailscale
      - $PWD/ts-config/config:/config # for serve config, see https://tailscale.com/blog/docker-tailscale-guide
    environment:
      - TS_HOSTNAME=sonarr # set hostname, otherwise it will take on the gluetun container's hostname
      - TS_AUTHKEY=tskey-...
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve/json
```

You can keep attaching apps to gluetun, they will all be accessible via the tailnet on their native ports without needing port forwarding. If you want them to all be served on their own host on the tailnet, with their own Serve/Funnel and https, you will need to add an additional tailscale sidecar for each app as well. Something like this:

```
services:
  gluetun:
    # ...
  sonarr:
    network_mode: service:gluetun
    # ...
  radarr:
    network_mode: service:gluetun
    # ...
  tailscale-sidecar-sonarr:
    network_mode: service:gluetun
    volumes:
      - tailscale-state:/var/lib/tailscale
      - $PWD/ts-sonarr/config:/config
    environment:
      - TS_HOSTNAME=sonarr
      - TS_AUTHKEY=tskey-...
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve/json
  tailscale-sidecar-radarr:
    network_mode: service:gluetun
    volumes:
      - tailscale-state:/var/lib/tailscale
      - $PWD/ts-radarr/config:/config
    environment:
      - TS_HOSTNAME=radarr
      - TS_AUTHKEY=tskey-...
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve/json
```

Note that I've dropped a bunch of stuff you might expect to see on the tailscale sidecars, like `cap_add`, `TS_ACCEPT_DNS=true`, the `/dev/net/tun` bind mount, `hostname:`. This is intentional, I don't want tailscale messing with gluetun's network stack.
