### DISCUSSION TITLE
How to connect to PureVPN with or without Port Forwarding

### DISCUSSION THREAD

**Discussion by Sevyn13** [qdm12/gluetun#2721] [Q&A] [answered]
**Here is the info needed to connect to PureVPN with or without port forwarding.**

**For Config with No VPN Port Forwarding:**
In your PureVPN Dashboard on their site and go to [Subscriptions](https://my.purevpn.com/v2/dashboard/subscriptions) and scroll to the bottom until you see VPN Username and VPN Password. Make note of the username and password as it will be needed in the Docker Compose.

**For Config with VPN Port Forwarding:**
In your PureVPN Dashboard on their site and go to [Subscriptions](https://my.purevpn.com/v2/dashboard/subscriptions) and scroll to the bottom until you see VPN Username and VPN Password. Make note of the username and password as it will be needed in the Docker Compose. Next go to [Manual Config](https://my.purevpn.com/v2/dashboard/manual-config) in your PureVPN Dashboard. You should be presented with a list of countries. I have found that not all work, but I have had no problems with using Belgium. Click the little drop down next to Belgium then click download. In the box that pops up choose the UDP protocol and download the config file. Rename the config file to belgiumudp.conf and put it in the bind mount location for the config from the Docker Compose.

**My Docker Compose with qBittorrent:**

```
services:
  gluetun:
    container_name: gluetunvpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /home/sevyn/docker/gluetun:/gluetun #Put belgiumudp.conf here
    environment:
    ########   NO PORT FORWARDING   #########
      # - VPN_SERVICE_PROVIDER=purevpn
      # - SERVER_COUNTRIES=Belgium
      # - VPN_TYPE=openvpn
      # - OPENVPN_USER=VPN Username
      # - OPENVPN_PASSWORD=VPN Password

    ########   PORT FORWARDING   ########
      - VPN_TYPE=openvpn
      - VPN_SERVICE_PROVIDER=custom
      - OPENVPN_CUSTOM_CONFIG=/gluetun/belgiumudp.conf
      - OPENVPN_USER=VPN Username
      - OPENVPN_PASSWORD=VPN Password
      - FIREWALL_VPN_INPUT_PORTS=6881
    ports:
      - 6969:6969 # qbittorrent web interface
      - 6881:6881 # qbittorrent torrent port, only needed if using VPN port forwarding
    restart: always


  qbittorrentvpn:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrentvpn
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=6969
      - TORRENTING_PORT=6881 # qbittorrent torrent port, only needed if using VPN port forwarding
    volumes:
      - /home/user/docker/qbittorrentvpn:/config
      - /home/user/torrents:/data/torrents
      - /home/user/completed:/data/completed #only needed if you tell qBittorrent to do completion moving
      - /home/user/downloading:/data/downloads

    ######### Comment Health Check Out Until You Get VPN working ##########
    depends_on:
      gluetun:
        condition: service_healthy
    restart: always
```

**Comment by nodecentral** [comment]


**Reply by Sevyn13** [reply]
I just posted my working config for both port forwarding and without port forwarding.

**Comment by Sevyn13** [comment, marked as answer]
**I got it working. Here is the info needed to connect to PureVPN with port forwarding or without.**

**For Config with No VPN Port Forwarding:**
In your PureVPN Dashboard on their site and go to [Subscriptions](https://my.purevpn.com/v2/dashboard/subscriptions) and scroll to the bottom until you see VPN Username and VPN Password. Make note of the username and password as it will be needed in the Docker Compose.

**For Config with VPN Port Forwarding:**
In your PureVPN Dashboard on their site and go to [Subscriptions](https://my.purevpn.com/v2/dashboard/subscriptions) and scroll to the bottom until you see VPN Username and VPN Password. Make note of the username and password as it will be needed in the Docker Compose. Next go to [Manual Config](https://my.purevpn.com/v2/dashboard/manual-config) in your PureVPN Dashboard. You should be presented with a list of countries. I have found that not all work, but I have had no problems with using Belgium. Click the little drop down next to Belgium then click download. In the box that pops up choose the UDP protocol and download the config file. Rename the config file to belgiumudp.conf and put it in the bind mount location for the config from the Docker Compose.

**My Docker Compose with qBittorrent:**

```
services:
  gluetun:
    container_name: gluetunvpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /home/sevyn/docker/gluetun:/gluetun #Put belgiumudp.conf here
    environment:
    ########   NO PORT FORWARDING   #########
      # - VPN_SERVICE_PROVIDER=purevpn
      # - SERVER_COUNTRIES=Belgium
      # - VPN_TYPE=openvpn
      # - OPENVPN_USER=VPN Username
      # - OPENVPN_PASSWORD=VPN Password

    ########   PORT FORWARDING   ########
      - VPN_TYPE=openvpn
      - VPN_SERVICE_PROVIDER=custom
      - OPENVPN_CUSTOM_CONFIG=/gluetun/belgiumudp.conf
      - OPENVPN_USER=VPN Username
      - OPENVPN_PASSWORD=VPN Password
      - FIREWALL_VPN_INPUT_PORTS=6881
    ports:
      - 6969:6969 # qbittorrent web interface
      - 6881:6881 # qbittorrent torrent port, only needed if using VPN port forwarding
    restart: always


  qbittorrentvpn:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrentvpn
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=6969
      - TORRENTING_PORT=6881 # qbittorrent torrent port, only needed if using VPN port forwarding
    volumes:
      - /home/user/docker/qbittorrentvpn:/config
      - /home/user/torrents:/data/torrents
      - /home/user/completed:/data/completed #only needed if you tell qBittorrent to do completion moving
      - /home/user/downloading:/data/downloads

    ######### Comment Health Check Out Until You Get VPN working ##########
    depends_on:
      gluetun:
        condition: service_healthy
    restart: always
```
