### DISCUSSION TITLE
Help! Qbittorrent and Gluetun

### DISCUSSION THREAD

**Discussion by Rhythmd7** [qdm12/gluetun#2722] [Q&A]
Hi Everyone,

I need some help downloading. I am currently using a docker compose file to spin up my stack on my raspberry pi 5.

It was working as expected but since 8 days I have been unable to download anything.

All of my torrents are stalling, or stuck on downloading metadata stage.

The only discrepancy in the logs that I see is the following for Gluetun

`INFO [vpn] You are running 1 commit behind the most recent latestINFO [vpn] You are running 1 commit behind the most recent latest`

I tried to change the image and also rerun the docker compose as well as tried to do an update from portainer but no luck.

```
services:
  gluetun:
    image: ghcr.io/qdm12/gluetun:latest
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8181:8181 # qbittorrent
      - 9696:9696 # Prowlarr
      - 8989:8989 # Sonarr
      - 6767:6767 #Bazzarr
      - 8191:8191 #Flaresolverr
      - 7878:7878 #radarr
volumes:
      - /home/pi/AppData/gluetun/config:/config
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY= xxx
      - WIREGUARD_ADDRESSES=10.5.0.2/32
      - TZ=Australia/Sydney
      - UPDATER_PERIOD=24h
      - FIREWALL_VPN_INPUT_PORTS=6881,8181
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - WEBUI_PORT=8181
      - TORRENTING_PORT=6881
    volumes:
      - /home/pi/AppData/qbittorrent/config:/config
      - /home/pi/ssd/data/torrents:/data/torrents #optional
    depends_on:
      - gluetun
    restart: unless-stopped

```

After this I tried Proton VPN:
```
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    hostname: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8181:8181 # qbittorrent
    volumes:
      - /home/pi/AppData/gluetun/config:/config
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY= xxx
      - SERVER_COUNTRIES=Netherlands,Romania
      - TZ=Australia/Sydney
      - UPDATER_PERIOD=12h
      - VPN_PORT_FORWARDING=on

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - WEBUI_PORT=8181
    volumes:
      - /home/pi/AppData/qbittorrent/config:/config
      - /home/pi/ssd/data/torrents:/data/torrents #optional
    depends_on:
      - gluetun
    restart: unless-stopped
```

After running this, I went to the logs, copied the forwarded port and set it on bittorrent via web ui. I am still unable to download anything.
If I separate out the torrent client I have no issues downloading and if I use a Firefox browser through the VPN, it works as expected. What am I missing here?

**Comment by Samaze123** [comment]
Here my compose file that works pretty well but for qbittorrent to works I need to wait 2-3 minutes each time I start it before it pass `Status: Connected`.

```YAML
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    network_mode: service:gluetun
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./gluetun:/gluetun
      - qb-config:/config
      - ../data/torrents:/data/torrents # Change it to your use case
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - curl --fail http://localhost:8080 || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s
    depends_on:
      gluetun:
        condition: service_healthy
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8000:8000 # GT
      - 8080:8080 # QB
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - DNS_ADDRESS=${WIREGUARD_DNS_ADDRESS}
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused
        --post-data "json={\"listen_port\":{{PORTS}}}"
        http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'
      - UPDATER_PERIOD=24h
      - HEALTH_READ_TIMEOUT=10s
      - HEALTH_INITIAL_DELAY=120s
      - PUID=${PUID}
      - PGID=${PGID}
      - LOG_LEVEL=debug
      - TZ=${TZ}
```

**Reply by Prolonz** [reply]
I'm experiancing a very similar issue. For me, I don't see any peers at all as if Qbittorrent has no connection but Gluetun is definitely working. 

Qbittorrent with Gluetun was working perfectly fine on the Raspberry Pi 5 until about 10 days ago (at least that's when I noticed) when it just stopped working. Gluetun is connecting properly. Qbittorrent works without Gluetun but together they do not work. Interestingly they do still seem to work together on the Raspberry Pi 4. 

I wonder if it's something to do with a recent update to the Raspberry Pi 5.

**Comment by bluskye** [comment]
Known issue, use the libtorrentv1 version, not latest

    image: lscr.io/linuxserver/qbittorrent:libtorrentv1

**Reply by LittleBitSalty** [reply]
I have the same (or at least very similar issue) and despite trying this it didn't work, do you have any other ideas?  I know Gluetun is working, and I know qBittorrent works without using Gluetun, but I can't get them to work together.

**Reply by bluskye** [reply]
Always turn OFF vpn port forwarding to test if it really works together.

      - VPN_PORT_FORWARDING=off

**Reply by LittleBitSalty** [reply]
Thank you for the reply, unfortunately qBittorrent still isn't working.  I am using Mullvad as my VPN, and I know that doesn't support port forwarding, would that have anything to do with my torrents not working (I currently am testing the arch linux iso, which I can download fine without have ports forwarded on my router)

**Reply by bluskye** [reply]
This works, turn OFF vpn port forward, stick to the standard ports.

```
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8080:8080 #qbittorrent
      - 6881:6881 #qbittorrent
      - 6881:6881/udp #qbittorrent
    volumes:
      - /folder/gluetun:/gluetun
    environment:
      - PUID=0
      - PGID=10000
      - TZ=America/Chicago
      - NETWORK=192.168.1.205/24
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=XX
      - OPENVPN_PASSWORD=YYY
      - SERVER_REGIONS=US Chicago
      - UPDATER_PERIOD=12h
      - HTTPPROXY=on
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:libtorrentv1
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=10000
      - TZ=America/Chicago
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    network_mode: service:gluetun
    volumes:
      - /folder/qbittorrent:/config
      - /folder/downloads:/downloads #optional
    restart: unless-stopped
```

**Reply by LittleBitSalty** [reply]
Our configs look basically the same, here's mine:

```                                                                                            
services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - VPN_PORT_FORWARDING=off
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY={redacted}
      - WIREGUARD_ADDRESSES=10.65.255.71/32

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:libtorrentv1
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/server/Desktop/qBittorrent/config:/config
      - /home/server/Desktop/qBittorrent/Downloads:/downloads #optional
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
```

The only difference that I see is that I am using Mullvad and Wireguard.  I'll try using OpenVPN to see if that works, and if all else fails I might just have to switch VPN providers.

**Reply by LittleBitSalty** [reply]
Just tried it with OpenVPN, Gluetun works, qBittorrent doesn't, I'll try a different provider tomorrow.

**Reply by bluskye** [reply]
Make sure you did zero configs on router or gateway.

**Reply by Prolonz** [reply]
My compose is nearly identical and I’m still experiencing the same issue. Tried adding turning off vpn port forwarding and libtorrent v1.

It’s strange to me that this is only an issue on the pi 5. On the pi 4 the nearly identical stack works.

**Reply by bluskye** [reply]
Maybe give Transmission a shot just to test by adding this to the stack.  I prefer transmission if I dont need categories
Open ports

```
      - 9091:9091 #transmission
      - 51413:51413 #transmission
      - 51413:51413/udp #transmission
```

```
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: emp-transmission
    network_mode: service:gluetun
    environment:
      - PUID=0
      - PGID=10000
      - TZ=America/Chicago
    volumes:
      - /folder/ransmission:/config
      - /folder/downloads:/downloads
      - /folder/transmission/watch:/watch
    restart: unless-stopped
```
