### DISCUSSION TITLE
ProtonVPN (paid) setup for port forwarding, log says it's setup, portchecker.io disagrees

### DISCUSSION THREAD

**Discussion by jgeorgeson** [qdm12/gluetun#2723] [Q&A] [answered]
To preface, I'm looking at this because my torrent client is reporting that it's firewalled and I assume that is preventing me from properly seeding. Downloads are working fine. I have a paid subscription, I did add `+pmp` to username.

As the title says, the gluetun logs indicate that port forwarding was setup successfully, but when I test it with portchecker.io it's reported as closed. I did try updating to v3.40 with no improvement, and [this issue](https://github.com/qdm12/gluetun/issues/2679) seems to indicate there is some regression related to Proton port forwarding in v3.40.

compose config

```
  gluetun:
    image: qmcgaw/gluetun:v3.39.1
    container_name: vpn-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8000:8000/tcp # control server
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8090:8090/tcp # port for qbittorrent
      - 8091:8091/tcp # port for sabnzbd
      - 5802:5800/tcp # port for jdownloader
      - 9117:9117     # port for jackett
      - 9999:9234     # port for stashapp
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      - FIREWALL_OUTBOUND_SUBNETS=172.16.0.0/12,192.168.68.0/24
      - HTTPPROXY=off #change to on if you wish to enable
      - OPENVPN_ENDPOINT_PORT=443
      - OPENVPN_USER=[redacted]+nr+pmp
      - OPENVPN_PASSWORD=[redacted]
      - PORT_FORWARD_ONLY=on
      - PGID=65538 #CHANGE_TO_YOUR_GID
      - PUID=1034 #CHANGE_TO_YOUR_UID
      - SERVER_CITIES=New York,Denver,Los Angeles,Chicago
      - SERVER_COUNTRIES=United States
      - SHADOWSOCKS=off #change to on if you wish to enable
      - TZ=America/Chicago
      - UPDATER_PERIOD=24h
      - VPN_PORT_FORWARDING=on
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
    network_mode: gluetunbridge
    labels:
      - com.centurylinklabs.watchtower.enable=false
    security_opt:
      - no-new-privileges:true
    restart: always
```

log

```
vpn-gluetun  | 2025-02-28T11:22:10-06:00 INFO [routing] default route found: interface eth0, gateway 172.20.0.1, assigned IP 172.20.0.2 and family v4
vpn-gluetun  | 2025-02-28T11:22:10-06:00 INFO [routing] local ethernet link found: eth0
vpn-gluetun  | 2025-02-28T11:22:10-06:00 INFO [routing] local ipnet found: 172.20.0.0/16
vpn-gluetun  | 2025-02-28T11:22:10-06:00 INFO [firewall] enabling...
vpn-gluetun  | 2025-02-28T11:22:10-06:00 INFO [firewall] enabled successfully
vpn-gluetun  | 2025-02-28T11:22:12-06:00 INFO [storage] merging by most recent 20478 hardcoded servers and 21025 servers read from /gluetun/servers.json
vpn-gluetun  | 2025-02-28T11:22:12-06:00 INFO [storage] Using ipvanish servers from file which are 885 days more recent
vpn-gluetun  | 2025-02-28T11:22:12-06:00 INFO [storage] Using privado servers from file which are 187 days more recent
vpn-gluetun  | 2025-02-28T11:22:12-06:00 INFO [storage] Using private internet access servers from file which are 176 days more recent
vpn-gluetun  | 2025-02-28T11:22:12-06:00 INFO [storage] Using protonvpn servers from file which are 210 days more recent
vpn-gluetun  | 2025-02-28T11:22:12-06:00 INFO Alpine version: 3.20.3
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO OpenVPN 2.5 version: 2.5.10
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO OpenVPN 2.6 version: 2.6.11
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO Unbound version: 1.20.0
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO IPtables version: v1.8.10
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO Settings summary:
vpn-gluetun  | ├── VPN settings:
vpn-gluetun  | |   ├── VPN provider settings:
vpn-gluetun  | |   |   ├── Name: protonvpn
vpn-gluetun  | |   |   ├── Server selection settings:
vpn-gluetun  | |   |   |   ├── VPN type: openvpn
vpn-gluetun  | |   |   |   ├── Countries: United States
vpn-gluetun  | |   |   |   ├── Cities: New York, Denver, Los Angeles, Chicago
vpn-gluetun  | |   |   |   ├── Port forwarding only servers: yes
vpn-gluetun  | |   |   |   └── OpenVPN server selection settings:
vpn-gluetun  | |   |   |       ├── Protocol: UDP
vpn-gluetun  | |   |   |       └── Custom port: 443
vpn-gluetun  | |   |   └── Automatic port forwarding settings:
vpn-gluetun  | |   |       ├── Redirection listening port: disabled
vpn-gluetun  | |   |       ├── Use port forwarding code for current provider
vpn-gluetun  | |   |       ├── Forwarded port file path: /tmp/gluetun/forwarded_port
vpn-gluetun  | |   |       └── Credentials:
vpn-gluetun  | |   |           ├── Username: [redacted]+nr+pmp
vpn-gluetun  | |   |           └── Password: [redacted]
vpn-gluetun  | |   └── OpenVPN settings:
vpn-gluetun  | |       ├── OpenVPN version: 2.6
vpn-gluetun  | |       ├── User: [set]
vpn-gluetun  | |       ├── Password: [redacted]
vpn-gluetun  | |       ├── Network interface: tun0
vpn-gluetun  | |       ├── Run OpenVPN as: root
vpn-gluetun  | |       └── Verbosity level: 1
vpn-gluetun  | ├── DNS settings:
vpn-gluetun  | |   ├── Keep existing nameserver(s): no
vpn-gluetun  | |   ├── DNS server address to use: 127.0.0.1
vpn-gluetun  | |   └── DNS over TLS settings:
vpn-gluetun  | |       ├── Enabled: yes
vpn-gluetun  | |       ├── Update period: every 24h0m0s
vpn-gluetun  | |       ├── Unbound settings:
vpn-gluetun  | |       |   ├── Authoritative servers:
vpn-gluetun  | |       |   |   └── cloudflare
vpn-gluetun  | |       |   ├── Caching: yes
vpn-gluetun  | |       |   ├── IPv6: no
vpn-gluetun  | |       |   ├── Verbosity level: 1
vpn-gluetun  | |       |   ├── Verbosity details level: 0
vpn-gluetun  | |       |   ├── Validation log level: 0
vpn-gluetun  | |       |   ├── System user: root
vpn-gluetun  | |       |   └── Allowed networks:
vpn-gluetun  | |       |       ├── 0.0.0.0/0
vpn-gluetun  | |       |       └── ::/0
vpn-gluetun  | |       └── DNS filtering settings:
vpn-gluetun  | |           ├── Block malicious: yes
vpn-gluetun  | |           ├── Block ads: no
vpn-gluetun  | |           ├── Block surveillance: no
vpn-gluetun  | |           └── Blocked IP networks:
vpn-gluetun  | |               ├── 127.0.0.1/8
vpn-gluetun  | |               ├── 10.0.0.0/8
vpn-gluetun  | |               ├── 172.16.0.0/12
vpn-gluetun  | |               ├── 192.168.0.0/16
vpn-gluetun  | |               ├── 169.254.0.0/16
vpn-gluetun  | |               ├── ::1/128
vpn-gluetun  | |               ├── fc00::/7
vpn-gluetun  | |               ├── fe80::/10
vpn-gluetun  | |               ├── ::ffff:127.0.0.1/104
vpn-gluetun  | |               ├── ::ffff:10.0.0.0/104
vpn-gluetun  | |               ├── ::ffff:169.254.0.0/112
vpn-gluetun  | |               ├── ::ffff:172.16.0.0/108
vpn-gluetun  | |               └── ::ffff:192.168.0.0/112
vpn-gluetun  | ├── Firewall settings:
vpn-gluetun  | |   ├── Enabled: yes
vpn-gluetun  | |   └── Outbound subnets:
vpn-gluetun  | |       ├── 172.16.0.0/12
vpn-gluetun  | |       └── 192.168.68.0/24
vpn-gluetun  | ├── Log settings:
vpn-gluetun  | |   └── Log level: info
vpn-gluetun  | ├── Health settings:
vpn-gluetun  | |   ├── Server listening address: 127.0.0.1:9999
vpn-gluetun  | |   ├── Target address: cloudflare.com:443
vpn-gluetun  | |   ├── Duration to wait after success: 5s
vpn-gluetun  | |   ├── Read header timeout: 100ms
vpn-gluetun  | |   ├── Read timeout: 500ms
vpn-gluetun  | |   └── VPN wait durations:
vpn-gluetun  | |       ├── Initial duration: 6s
vpn-gluetun  | |       └── Additional duration: 5s
vpn-gluetun  | ├── Shadowsocks server settings:
vpn-gluetun  | |   └── Enabled: no
vpn-gluetun  | ├── HTTP proxy settings:
vpn-gluetun  | |   └── Enabled: no
vpn-gluetun  | ├── Control server settings:
vpn-gluetun  | |   ├── Listening address: :8000
vpn-gluetun  | |   ├── Logging: yes
vpn-gluetun  | |   └── Authentication file path: /gluetun/auth/config.toml
vpn-gluetun  | ├── OS Alpine settings:
vpn-gluetun  | |   ├── Process UID: 1034
vpn-gluetun  | |   ├── Process GID: 65538
vpn-gluetun  | |   └── Timezone: America/Chicago
vpn-gluetun  | ├── Public IP settings:
vpn-gluetun  | |   ├── Fetching: every 12h0m0s
vpn-gluetun  | |   ├── IP file path: /tmp/gluetun/ip
vpn-gluetun  | |   └── Public IP data API: ipinfo
vpn-gluetun  | ├── Server data updater settings:
vpn-gluetun  | |   ├── Update period: 24h0m0s
vpn-gluetun  | |   ├── DNS address: 1.1.1.1:53
vpn-gluetun  | |   ├── Minimum ratio: 0.8
vpn-gluetun  | |   └── Providers to update: protonvpn
vpn-gluetun  | └── Version settings:
vpn-gluetun  |     └── Enabled: yes
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO [routing] default route found: interface eth0, gateway 172.20.0.1, assigned IP 172.20.0.2 and family v4
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO [routing] adding route for 0.0.0.0/0
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO [firewall] setting allowed subnets...
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO [routing] default route found: interface eth0, gateway 172.20.0.1, assigned IP 172.20.0.2 and family v4
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO [routing] adding route for 172.16.0.0/12
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO [routing] adding route for 192.168.68.0/24
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO [dns] using plaintext DNS at address 1.1.1.1
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO [http server] http server listening on [::]:8000
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO [healthcheck] listening on 127.0.0.1:9999
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO [firewall] allowing VPN connection...
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO [openvpn] OpenVPN 2.6.11 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD]
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO [openvpn] library versions: OpenSSL 3.3.2 3 Sep 2024, LZO 2.10
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]84.17.63.8:443
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO [openvpn] UDPv4 link local: (not bound)
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO [openvpn] UDPv4 link remote: [AF_INET]84.17.63.8:443
vpn-gluetun  | 2025-02-28T11:22:13-06:00 INFO [openvpn] [node-us-58.protonvpn.net] Peer Connection Initiated with [AF_INET]84.17.63.8:443
vpn-gluetun  | 2025-02-28T11:22:14-06:00 INFO [openvpn] setsockopt TCP_NODELAY=1 failed
vpn-gluetun  | 2025-02-28T11:22:14-06:00 INFO [openvpn] TUN/TAP device tun0 opened
vpn-gluetun  | 2025-02-28T11:22:14-06:00 INFO [openvpn] /sbin/ip link set dev tun0 up mtu 1500
vpn-gluetun  | 2025-02-28T11:22:14-06:00 INFO [openvpn] /sbin/ip link set dev tun0 up
vpn-gluetun  | 2025-02-28T11:22:14-06:00 INFO [openvpn] /sbin/ip addr add dev tun0 10.25.0.2/16
vpn-gluetun  | 2025-02-28T11:22:14-06:00 INFO [openvpn] UID set to nonrootuser
vpn-gluetun  | 2025-02-28T11:22:14-06:00 INFO [openvpn] Initialization Sequence Completed
vpn-gluetun  | 2025-02-28T11:22:14-06:00 INFO [dns] downloading DNS over TLS cryptographic files
vpn-gluetun  | 2025-02-28T11:22:19-06:00 INFO [healthcheck] healthy!
vpn-gluetun  | 2025-02-28T11:22:19-06:00 INFO [dns] downloading hostnames and IP block lists
vpn-gluetun  | 2025-02-28T11:22:28-06:00 INFO [dns] init module 0: validator
vpn-gluetun  | 2025-02-28T11:22:28-06:00 INFO [dns] init module 1: iterator
vpn-gluetun  | 2025-02-28T11:22:28-06:00 INFO [dns] start of service (unbound 1.20.0).
vpn-gluetun  | 2025-02-28T11:22:29-06:00 INFO [dns] generate keytag query _ta-4a5c-4f66-9728. NULL IN
vpn-gluetun  | 2025-02-28T11:22:29-06:00 INFO [dns] generate keytag query _ta-4a5c-4f66-9728. NULL IN
vpn-gluetun  | 2025-02-28T11:22:29-06:00 INFO [dns] ready
vpn-gluetun  | 2025-02-28T11:22:29-06:00 INFO [healthcheck] healthy!
vpn-gluetun  | 2025-02-28T11:22:29-06:00 INFO [ip getter] Public IP address is 178.249.210.8 (United States, Colorado, Denver)
vpn-gluetun  | 2025-02-28T11:22:30-06:00 INFO [vpn] There is a new release v3.40.0 (v3.40.0) created 64 days ago
vpn-gluetun  | 2025-02-28T11:22:30-06:00 INFO [port forwarding] starting
vpn-gluetun  | 2025-02-28T11:22:30-06:00 INFO [port forwarding] gateway external IPv4 address is 178.249.210.8
vpn-gluetun  | 2025-02-28T11:22:30-06:00 INFO [port forwarding] port forwarded is 64391
vpn-gluetun  | 2025-02-28T11:22:30-06:00 INFO [firewall] setting allowed input port 64391 through interface tun0...
vpn-gluetun  | 2025-02-28T11:22:30-06:00 INFO [port forwarding] writing port file /tmp/gluetun/forwarded_port
```
