### DISCUSSION TITLE
Connect Gluetun container to multiple networks

### DISCUSSION THREAD

**Discussion by georgemp** [qdm12/gluetun#2731] [Q&A]
I have gluetun running on a bridge network with a static ip. I also have caddy running on a separate network with containers for transmission and others. The container transmission has it's network mode set to "container: gluetun", while the others have the network set to "caddy". I have the gluetun network also connected to the caddy network

```
service:
  networks:
        bridge:
          ipv4_address: 172.20.x.x
        caddy:

networks:
  bridge:
    ipam:
      config:
        - subnet: 172.20.1.0/24
  caddy:
    external: true
```

Without the addition of the caddy network, other containers on that network cannot connect to the container hosting transmission (which is on gluetun network). Is this config safe? Would gluetun/transmission ever send traffic out the caddy network to the internet? Thanks
