### DISCUSSION TITLE
Container qbittorrent container to glueten container

### DISCUSSION THREAD

**Discussion by Crowmeister** [qdm12/gluetun#2741] [Q&A]
Let me start by saying I'm sure I'm doing something wrong.
I have glueten and qbittorrent running in separate docker-composes.

My glueten compose looks like this:

```dockerfile
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8080:8080 #qbittorrent
      - 6881:6881 #qbittorrent
      - 6881:6881/udp #qbittorrent
    volumes:
      - /xxxx/gluetun:/gluetun
    environment:
      - DNS_ADDRESS=xxx
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=xxx
      - WIREGUARD_PRESHARED_KEY=xxx
      - WIREGUARD_ADDRESSES=xxx/32
      - SERVER_COUNTRIES=xx
      - PUID=xx
      - PGID=xx
      - TZ=Europe/Berlin
      - UPDATER_PERIOD=24h
networks:
  mynetwork:
    driver: bridge
``` 

And my qbittorrent compose looks like this:

```dockerfile
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: container:gluetun-gluetun-1  #I'm not 100% sure why this is needed, but normal gluetun doesnt work
    environment:
      - PUID=xx
      - PGID=xx
      - TZ=Europe/Berlin
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - xxxx
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
networks:
  mynetwork:
    driver: bridge
``` 

The issue is, when using this configuration the qbittorrent container doesn't connect properly to glueten, I can test with the curl command to https://ipinfo.io. Within the glueten container I get the expected result from the curl, within the qbittorrent container I get my normal IP. 

If I read [this](https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md) correctly, all I have to do is add network_mode: container:gluetun-gluetun-1 .

**Comment by dansaiko** [comment]
**Is there a reason why you are not using one .yml instead ?**

if you need to run then separetly try this:

**Step 1: Create a Common Network**

```
docker network create mynetwork
```

**Step 2: Modify** `gluetun` **Docker Compose**

Add `external` at the end:
````
networks:
  mynetwork:
    external: true  # This allows another compose file to join it
````
Do the same for `qbittorrent`:

````
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: container:gluetun  # Use gluetun network
    depends_on:
      - gluetun  # Ensures gluetun starts first
    environment:
      - PUID=xx
      - PGID=xx
      - TZ=Europe/Berlin
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - xxxx
    restart: unless-stopped

networks:
  mynetwork:
    external: true  # Join the existing network
````

Also it seems your ``network_mode: container:gluetun-gluetun-1`` maybe set wrong try:

````
network_mode: container:gluetun
````

i hope this helps you.
