### DISCUSSION TITLE
Gluetun port forward kubernetes

### DISCUSSION THREAD

**Discussion by epicblood** [qdm12/gluetun#2754] [Q&A]
I am trying to setup gluetun sidecar on kubernetes for qbittorrent, but getting this error for port-forwarding:
```
2025-03-25T19:03:48-07:00 INFO [openvpn] Initialization Sequence Completed
2025-03-25T19:03:48-07:00 ERROR [vpn] getting public IP address information: fetching information: Get "https://ipinfo.io/": EOF
2025-03-25T19:03:48-07:00 INFO [port forwarding] starting
2025-03-25T19:03:49-07:00 INFO [healthcheck] healthy!
2025-03-25T19:05:38-07:00 INFO [healthcheck] healthy!
2025-03-25T19:05:56-07:00 ERROR [vpn] starting port forwarding service: port forwarding for the first time: getting external IPv4 address: executing remote procedure call: connection timeout: failed attempts: read udp 10.244.1.116:55798->10.16.0.1:5351: i/o timeout (tries 1, 2, 3, 4, 5, 6, 7, 8, 9)
2025-03-25T19:07:44-07:00 INFO [healthcheck] healthy!
2025-03-25T19:08:34-07:00 INFO [healthcheck] healthy!
```
my config works for routing through the vpn, but I am not able to seed as there are no ports forwarded.
Here is my config, I am using protonvpn. I tried wireguard first, but saw nothing to indicate that it had attempted portforwarding, so now I am trying openvpn.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: gluetun
          image: qmcgaw/gluetun
          restartPolicy: Always
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "NET_RAW"]
          env:
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: VPN_SERVICE_PROVIDER
              value: "protonvpn"
            - name: TZ
              value: "America/Los_Angeles"
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: proton-openvpn
                  key: user
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: proton-openvpn
                  key: password
            - name: PORT_FORWARD_ONLY
              value: on
            - name: VPN_PORT_FORWARDING
              value: on
            - name: VPN_PORT_FORWARDING_UP_COMMAND
              value: >
                /bin/sh -c 'wget -O- --retry-connrefused --waitretry 2 -t 0 --timeout=15 --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'
            - name: SERVER_COUNTRIES
              value: United States
            - name: FIREWALL_INPUT_PORTS
              value: '8080'
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: '10.0.0.0/8'
          volumeMounts:
            - name: gluetun-config
              mountPath: /gluetun
      containers:
        - name: qbittorrent
          image: "hotio/qbittorrent"
          resources:
            requests:
              cpu: 4
              memory: 4G
            limits:
              cpu: 6
              memory: 8G
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: downloads
              mountPath: /downloads
            - name: config
              mountPath: /config
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: qbit-data
        - name: config
          persistentVolumeClaim:
            claimName: qbit-config
        - name: gluetun-config
          persistentVolumeClaim:
            claimName: pvc-gluetun-config
```

**Comment by iridial** [comment]
when using protonvpn with wireguard you need to make sure to create a wg config that has `NAT-PMP (Port Forwarding) = on` on one of the supported servers. With openvpn there is a suffix to add to the username to enable port forwarding.

also try looking at this solution:
https://github.com/bjw-s-labs/home-ops/blob/main/kubernetes/apps/downloads/qbittorrent/app/helmrelease.yaml

they use a support container (ghcr.io/bjw-s-labs/gluetun-qb-port-sync) to manage the port forward update, however it needs the gluetun control server api to get the forwarded port, so you'd need to edit gluetun to enable that..

I use transmission so the request is different; I ended up using a script that makes n retries after a timeout since the main container may not be ready when the forwarded port is (this especially on pod start).
This script is defined as configmap and mounted read only in the gluetun init container.
my UP command looks like this:
```
- name: VPN_PORT_FORWARDING_UP_COMMAND
  value: '/bin/sh -c "/scripts/transmission-port-update.sh --port {{PORTS}}" 2>&1'
```
and volumes:
```
  volumeMounts:
    - name: transmission-portforward
      mountPath: /scripts/transmission-port-update.sh
      subPath: transmission-port-update.sh
(...)
volumes:
  - name: transmission-portforward
    configMap:
      name: transmission-update-portforward-script
      defaultMode: 0755
```
for the qbittorrent script there is currently an open pull request, you could get the code from there: https://github.com/qdm12/gluetun/pull/2700/files
and put it in the mounted configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-update-portforward-script
  namespace: default
data:
  qbittorrent-port-update.sh: |
    #!/bin/sh
    (...)
```
hope this helps :)

ps. I suggest to use a `StatefulSet` instead of a `Deployment`
