### DISCUSSION TITLE
Confused about how to split traffic over gluetun

### DISCUSSION THREAD

**Discussion by amy-langley** [qdm12/gluetun#2758] [Q&A]
I am having problem doing a "local split networking" (I'll explain what I mean below) setup with `gluetun`. I don't understand docker networking very well unfortunately. I suspect that my ignorance may be the problem, because `gluetun` has really worked well for everything else I've thrown at it.

```mermaid
stateDiagram

%% Edge connections between nodes
    gluetun --> internet
    needs_vpn --> gluetun
    needs_vpn --> no_vpn
    no_vpn --> needs_vpn
    no_vpn --> internet
```

This `docker-compose.yml` shows a contrived example. To summarize, I have two (in reality several) services, _only one_ of which needs _only its outbound_ (not routed to the cluster) traffic to be routed over the vpn. All of the services need to be able to talk to each other and need to be accessible from the host's LAN. Currently I can't figure out how to do this with `gluetun`; I imagined I would do something like connecting the services to multiple networks, but since we use the `network_mode` attribute to connect to the vpn, that's not available. Here is a sample `docker-compose.yml` that I hope will illustrate what I'm trying to do:

```yml
services:
  needs-vpn-for-remote:
    image: some/image:tag
    network_mode: "service:tunnel"
    # # I imagined that maybe  I would do something like
    # networks:
    #   - some clever stuff here
    #   - to try to make the routing work
    # # ports have to be configured on tunnel, not here
    # ports:
    #   - 1234:1234
    restart: unless-stopped
  never-needs-vpn:
    image: other/image:tag
    ports:
      - 5678:5678
    restart: unless-stopped
  tunnel:
    image: qmcgaw/gluetun:latest
    ports:
      # expose ports on behalf of "nvfr"
      - 1234:1234
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      # I prefer not to use persistent storage for this
      - gluetun:/gluetun
    environment:
      snipped: details of my vpn config (it works fine, no problem there)
    restart: unless-stopped        
```

So again, to clarify my example, I need the following:

1. `needs-vpn-for-remote` and `never-needs-vpn` must be accessible to my LAN
2. `needs-vpn-for-remote` must be able to talk to `never-needs-vpn` over docker networking
3. `never-needs-vpn` must be able to talk to `needs-vpn-for-remote` over docker networking
4. All traffic leaving the container host from `needs-vpn-for-remote` must traverse the vpn
5. Traffic leaving the container host from `never-needs-vpn` should not traverse the vpn
6. Assume that instead of just two hosts shown here, my real example has a sufficiently large number of services to make things like assigning each one its own static IP address infeasible

It seems like all of this should be possible, if complicated, but I am having a hard time figuring out just how to proceed. I would be grateful for any suggestions or links, or also questions in case I haven't explained things clearly enough. Thank you for `gluetun`--it's great and I've been making extensive use of it in simpler use cases.
