### DISCUSSION TITLE
gluetun with iprovpn?

### DISCUSSION THREAD

**Discussion by comfuzio** [qdm12/gluetun#2776] [Q&A]
Hi, I would like some help with running gluetun on my synology nas and connect to iProvpn servers.
They're offering .ovpn files and my current docker compose is:
```
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /volume1/docker/config/QBittorrent-VPN/openvpn:/gluetun/custom
    environment:
      - VPN_TYPE=openvpn
      - OPENVPN_USER=myuser
      - OPENVPN_PASSWORD=mypass
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom/bulgaria-udp.ovpn
    ports:
      - 8080:8080
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    restart: unless-stopped
    volumes:
      - /volume1/docker/config/QBittorrent-VPN/qbittorrent:/config
      - /volume1/downloads:/downloads
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Athens
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
```
My goal is to just use the qbittorrent with vpn tunnel and not all traffic.
When I deploy it, it runs but gives me error that my login info are wrong. They are 100% good and I used characters that won't conflict with the config.
I also made a file in "/volume1/docker/config/QBittorrent-VPN/openvpn/" named "auth.conf" and added my login info there as well but same result.
Can someone please help me with this in what I am doing wrong?
