### DISCUSSION TITLE
[Proton VPN] DNS issues after moving from Windows to Fedora

### DISCUSSION THREAD

**Discussion by ghost** [qdm12/gluetun#2781] [Q&A]
I previously used Gluetun on Windows with Rancher Desktop and WSL and it worked perfectly. Now I've installed Fedora 42 instead and the same compose file that I used on Windows doesn't work, I get the following error message:

`INFO [healthcheck] program has been unhealthy for 6s: restarting VPN (healthcheck error: dialing: dial tcp4: lookup cloudflare.com: i/o timeout)`

I made a new compose file with the bare minimum for troubleshooting, and it's the same issue:

```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=<REDACTED>
      - SERVER_COUNTRIES=Netherlands
```

I also tried adding Quad9's DNS servers in a `dns:` block in the compose file, but that didn't work either. I spun up a busybox container with `docker run --rm busybox nslookup cloudflare.com`  and at first it didn't work but after adding DNS servers to `/etc/docker/daemon.json`  it fixed the issue for the busybox container but Gluetun still doesn't work.

I've also tried to set permissive mode in SELinux and I've tried disabling my firewall. I've also tried updating my server information but it alternates between two error messages:

```
ERROR updating server information: getting servers: Get "https://api.protonmail.ch/vpn/logicals": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

and

```
ERROR updating server information: getting servers: HTTP status code not OK: 401 401 Unauthorized
```

I'd appreciate any help!

Thank you.
