### DISCUSSION TITLE
Problem with qBittorrent on (seemingly only) Raspberry Pi 5

### DISCUSSION THREAD

**Discussion by LittleBitSalty** [qdm12/gluetun#2787] [Q&A] [answered]
I and a lot of other people (see #2722) have had problems using qBittorrent with Gluetun on the Raspberry Pi 5 platform.  qBittorrent doesn't show any connection (0 seeds 0 peers), Transmission does not seem to have this problem. Nor does qBittorrent without using Gluetun.

My docker-compose.yml:

```
services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - VPN_PORT_FORWARDING=off
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY={redacted}
      - WIREGUARD_ADDRESSES=10.65.255.71/32

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:libtorrentv1
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/server/Desktop/qBittorrent/config:/config
      - /home/server/Desktop/qBittorrent/Downloads:/downloads #optional
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
```
