### DISCUSSION TITLE
I need help to setup with gluetun w/mullvad

### DISCUSSION THREAD

**Discussion by ruka-64** [qdm12/gluetun#2791] [Q&A] [answered]
I read [docs](https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/mullvad.md) and [(discussion)how to use gluetun as ts exit node](https://github.com/qdm12/gluetun/discussions/2201) and I set up accordingly.
but my container isn't work correctly!
it shows:
```
[dns] cannot update filter block lists:
Get "https://raw.githubusercontent.com/qdm12/files/master/malicious-hostnames.updated":
dial tcp: lookup raw.githubusercontent.com on 1.1.1.1:53: read udp 10.75.176.201:57309->1.1.1.1:53: i/o timeout,
Get "https://raw.githubusercontent.com/qdm12/files/master/malicious-ips.updated": dial tcp: lookup raw.githubusercontent.com on 1.1.1.1:53: read udp 10.75.176.201:57309->1.1.1.1:53: i/o timeout
```

**My docker-compose.yml**:
```yml
---
version: "3.7"
services:
  gruetun:
    image: qmcgaw/gluetun:latest
    hostname: gruetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./config:/gluetun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    environment:
      - LOG_LEVEL=debug
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
        #- VPN_ENDPOINT_PORT=1194
      - WIREGUARD_PRIVATE_KEY=my-mullvad-priv-key
      - WIREGUARD_ADDRESSES=10.75.176.201/32
      - SERVER_HOSTNAME=jp-osa-wg-001
        #- SERVER_CITIES=Osaka
        #- DNS_ADDRESS=1.1.1.1
      - HEALTH_VPN_DURATION_INITIAL=120s
        #network_mode: host
  tsdocker:
    image: tailscale/tailscale:latest
    depends_on:
      gruetun:
          condition: service_healthy
    environment:
      - TS_AUTHKEY=tskey-auth-xxx
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_EXTRA_ARGS=--advertise-exit-node --accept-routes
      - TS_ROUTES=192.168.12.0/24 # home LAN subnet
    volumes:
      - ./tsdocker/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    network_mode: service:gruetun
```

**Device Info**
* OS: `Ubuntu 20.04.6 LTS` (on Proxmox VE)
* Docker version: `28.0.1 (068a01e)`
* Docker compose version: `2.33.1`

**I tried**:
* search similar discussions
* ask google
* change image to `qmcgaw/gluetun:v3`
* reinstall os
