### DISCUSSION TITLE
How do I run `gluetun` as a read-only container?

### DISCUSSION THREAD

**Discussion by UtkarshVerma** [qdm12/gluetun#2797] [Q&A]
For security, it's considered a good practice to run containers as read-only and allow r/w access only to files that require it.

I tried the following in my `compose.yaml`:
```yaml
services:
  gluetun:
    container_name: gluetun
    image: docker.io/qmcgaw/gluetun

    user: $PUID:$PGID
    read_only: true
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN

    networks:
      - gluetun

    devices:
      - /dev/net/tun:/dev/net/tun

    environment:
      TZ: $TZ
      VPN_SERVICE_PROVIDER: mullvad
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: $WIREGUARD_PRIVATE_KEY
      WIREGUARD_ADDRESSES: $WIREGUARD_ADDRESSES

    volumes:
      - ./state:/gluetun:rw

    restart: unless-stopped

networks:
  gluetun:
    name: gluetun
    driver: bridge
```

but this fails with the error:

```
gluetun  | 2025-05-02T19:57:42Z ERROR creating user: open /etc/passwd: permission denied
gluetun  | 2025-05-02T19:57:42Z INFO Shutdown successful
```

Please help me achieve this.
