### DISCUSSION TITLE
Qbit and Gluetun on Unraid

### DISCUSSION THREAD

**Discussion by Obrin24** [qdm12/gluetun#2801] [Q&A]
## Hello all!

About two weeks ago, I managed to set up **Radarr**, **Sonarr**, **Jellyseerr**, and **Prowlarr**. Alongside that, I set up **qBittorrent** and **Gluetun** to handle downloading for my Jellyfin server.

However, after a day or two, it suddenly stopped working. I checked if my MullardVPN ran out of credits, and it is still full until next month.

- qBittorrent is still authenticating with an IP from my Gluetun VPN server.
- But **all downloads error out within seconds**, going from *"downloading with some seeds and peers"* to tracker errors such as:
  - `"non-authoritative"`
  - `"timed out"`

Nothing changed in my configuration, so I’m unsure what caused the break.  
The only discrepancy I noticed in the **Gluetun logs** is this:

```
INFO [vpn] You are running 1 commit behind the most recent latest
```

---

###  My apps in `docker-compose` format

```yaml
version: '3.7'

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=America/Chicago 
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=xxx
      - WIREGUARD_ADDRESSES=10.71.89.214/32
      - SERVER_CITIES=Denver CO
    volumes:
      - /mnt/user/appdata/gluetun:/gluetun
    ports:
      - 8080:8080  # Expose WebUI port (optional)
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:libtorrentv1
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /mnt/user/appdata/qbittorrent:/config
      - /mnt/user/home/downloads:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped
```

---

I’m unsure if I want to switch from using qBittorrent, but from everything I’ve read, it’s still the **preferred** client in most setups like this.

Any suggestions would be appreciated!
