### DISCUSSION TITLE
How to check if traffic is really going out though VPN?

### DISCUSSION THREAD

**Discussion by iHateThisGameSo** [qdm12/gluetun#2803] [Q&A] [answered]
I believe I got my gluetun to work with qbittorrent, however, I want to check if everything is working properly. Checking the tun0 interface on gluetun shows:

```
10:10:57 user@strike:~/stacks/vpn-stack$ docker exec gluetun-protonvpn ip link show tun0
4: tun0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1320 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/none
```

Isn't it supposed to be UP instead of UNKNOWN? How I can verify that? Everything says healthy on the logs.

```
2025-05-07T13:10:49Z INFO [healthcheck] healthy!
2025-05-07T13:10:56Z INFO [dns] downloading hostnames and IP block lists
2025-05-07T13:10:59Z INFO [dns] DNS server listening on [::]:53
2025-05-07T13:11:00Z INFO [dns] ready
```

Here's my YML

```
services:
  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun-protonvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "9091:9091"
      - "8080:8080"
    environment:
      - UPDATER_PERIOD=24h
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_STATUS_FILE=/gluetun/forwarded_port
    volumes:
      - /srv/docker/gluetun:/gluetun
    restart: unless-stopped
    labels:
      autoheal: true
    healthcheck:
      test: ["CMD-SHELL", "ip link show tun0"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent-nox
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - /srv/docker/qbittorrent/config:/config
      - /media/nas/torrents:/downloads
    labels:
      autoheal: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
```
