### DISCUSSION TITLE
qBittorrent + Gluetun + Synology - No peers

### DISCUSSION THREAD

**Discussion by poudenes** [qdm12/gluetun#2822] [Q&A]
Hi All,

I try to let this work.  Both containers show me a IP from VPN Unlimited. So thats good.

When I start a torrent I see a list of many peers. But then they all gone and my torrent status is stopped.
Can someone assist me to let this work?

in qBittorrent WebUI the download port is set on: 6881
also in Advanced the network interface: TUN0
Optional IP to bind: All IPV4 

compose file
```
version: "3.9"
services:

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    restart: always
    mem_limit: 512m
    cpu_shares: 1024
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8084:8084/tcp # qbittorrent WebUI port
      - 6881:6881/tcp # qbittorrent Download TCP port
      - 6881:6881/udp # qbittorrent Download UDP port
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volumeUSB1/usbshare/docker/gluetun:/gluetun
    environment:
      PUID: 1026
      PGID: 100
      TZ: Europe/Amsterdam      
      VPN_SERVICE_PROVIDER: custom
      OPENVPN_CUSTOM_CONFIG: /gluetun/fr_torrent_ovpn.ovpn
      OPENVPN_USER: KS2-USERNAME
      OPENVPN_PASSWORD: PASSWORD
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    healthcheck:
      disable: true
    labels:
      - com.centurylinklabs.watchtower.enable=false
    networks:
       synology:
         ipv4_address: 172.30.33.118

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent_gluetun
    network_mode: service:gluetun
    depends_on:
      - gluetun
    environment:
      PUID: 1026
      PGID: 100
      VERSION: latest
      TZ: Europe/Amsterdam 
      WEBUI_PORT: 8084
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volumeUSB1/usbshare/docker/qbittorrent/:/config:rw
      - /volumeUSB1/usbshare/docker/qbittorrent/downloads:/downloads:rw
      - /volume1/data/torrents:/data/torrents:rw
    restart: unless-stopped
    
networks:
  synology:
    external: true
```
