### DISCUSSION TITLE
Gluetun Kubernetes issues with  dns resolution

### DISCUSSION THREAD

**Discussion by bornav** [qdm12/gluetun#2825] [Q&A] [answered]
Here is my current sample configuration
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name sample
  labels:
    app: *name
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      initContainers:
      - name: gluetun
        image: ghcr.io/qdm12/gluetun:v3.40.0
        restartPolicy: Always
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "(ip rule del table 51820; ip -6 rule del table 51820) || true"]
        env: 
          - name: TZ
            value: "Europe/Vienna"
          - name: VPN_SERVICE_PROVIDER
            value: "<valid_svc_provider>"
          - name: VPN_TYPE
            value: "wireguard"
          - name: FIREWALL_INPUT_PORTS
            value: "9696"
          - name: WIREGUARD_PRIVATE_KEY
            value: "<valid_key>"
          - name: WIREGUARD_ADDRESSES
            value: "<valid_ip>"
          - name: SERVER_CITIES
            value: "<valid_city>"
          - name: FIREWALL_OUTBOUND_SUBNETS # dont know if neccesarry, as after specifying did not notice any behavior change
            value: "10.32.0.0/24"
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:1.37.0
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: "Europe/Vienna"
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        ports:
        - containerPort: 9696
          name: tcp-prowlarr
          protocol: TCP
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
```

now here is a problem im having,

the gluetun spins up, gets connected, and starts forwarding traffic, i get back dns server listening on, and a public ip

from this example prowlarr, if i exec into the container and do a curl to see the public ip it uses, it is using the correct gluetun one, if i try to curl some service, i get a normal dns resolution, so all works well, but

the prowlarr,sonarr,radarr... they all throw out lots of logs regarding unable to resolve entries

example of the log for prowlarr:  ```│ [v1.37.0.5076] System.Net.Http.HttpRequestException: Name does not resolve (indexers.prowlarr.com:443)```

if i try to curl that same domain from the prowlarr pod, i get back valid response, after which the prowlarr still logs does not resolve, (assuming)even if it should now have it cache

given this i would have assumed the issue does not lie with gluetun, but the moment i remove gluetun, all other arr-stack services work properly

so to tldr, process level queries seem to not be using correct dns for some reason

does anyone know what could be the reason for this behavior and how can it be fixed?
