### DISCUSSION TITLE
Working but not properly - Mullvad with qbittorent

### DISCUSSION THREAD

**Discussion by m0Re-p** [qdm12/gluetun#349] [Q&A]
Hi,

I trying to set up Mullvad with qbittorent. By typing curl checkip.io I can see that the IP address is changing (for both gluetun and qbittorrentglue container).

I chose a sample torrent (ubuntu) and unfortunately there is a problem. It only looks for a few seeds and peers. After a while, their number drops to zero - downloading does not even start.

I am asking for help, I buy a beer :)

my code

```yml
---
version: "2.1"    
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    environment:
      - VPNSP=mullvad 
      - OPENVPN_USER=XXXXXXXX #MULLVADTOKEN
      - COUNTRY=Germany
      - CITY=Frankfurt
      - ISP=31173
      - FIREWALL_VPN_INPUT_PORTS:XXXXX #PORT VPN
    ports:
      - 8010:8000/tcp # Built-in HTTP control server
      - 6888:6881/udp
      - 6888:6881
      - 8070:8070
    volumes:
      - /srv/XXXXXXXXXXXXXXX:/gluetun  #VOLUME FOR DATA
    restart: unless-stopped
 
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrentglue
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - WEBUI_PORT=8070
    volumes:
      - /srv/XXXXXXXXXXXXXXX:/config #VOLUME FOR CONFIG
      - /srv/XXXXXXXXXXXXXXX:/downloads #VOLUME FOR DOWNLOAD
    network_mode: service:gluetun
    depends_on:
      - gluetun
```
