### DISCUSSION TITLE
RFE - Support DDNS to update VPN Public IP address from HTTP Control Server

### DISCUSSION THREAD

**Discussion by isudoi** [qdm12/gluetun#454] [Ideas]
RFE - Support DDNS to update VPN Public IP address from HTTP Control Server

This is going to be a great addition to gluetun.

Where it is already half-way implemented, that we have https://github.com/qdm12/gluetun/wiki/HTTP-Control-server and can query the public IP address

The RFE is to have built-in support for the public IP address to update DDNS service like:
- https://www.duckdns.org/
- https://www.noip.com/
- https://www.cloudflare.com/en-ca/learning/dns/glossary/dynamic-dns/

With that, we can easily identify the IP of our VPN container so we can use it with different scenarios, such as port forwarding or even SSL cert with nginx proxy manager and other applications.

**Comment by qdm12** [comment]
Actually I'm thinking, just run qmcgaw/ddns-updater (github.com/qdm12/ddns-updater) connected to gluetun and it should do. No need to do anything 😉 Let me know if it works for you and I'll add a page in the Wiki about it!

**Reply by isudoi** [reply]
This is going to be epic!

I can't wait to test the integration.

I am already using both containers at the moment, with the new update to connect both of them and then update DDNS with the VPN ip address, that would be great indeed!!

**Comment by qdm12** [comment]
@ansred also that might interest you: https://github.com/qdm12/gluetun/issues/464#issuecomment-848063080

I'm thinking on writing a Wiki page to have a domain with https with different services running through gluetun 😉

**Reply by isudoi** [reply]
Checking ...

**Comment by isudoi** [comment]
Hey @qdm12 Good News!

I got it working ddns container as a service using gluetun as its network mode within the same stack and it worked like charm! 

it keeps updating now my A record on Cloudflare with the VPN IP which I can access it using the hostname

AMAZING!

Here is the stack for three parts
gluetun
ddns updater
nginx


```
################################################################################################

version: "3.7"

services: 
# 01 gluetun-Mullvad-VPN
# 02 gluetun-Mullvad-nginx-ansred
# 03 gluetun-Mullvad-ddns-updater

################################################################################################

  gluetun-Mullvad-VPN: 
    cap_add: 
      - NET_ADMIN
    container_name: gluetun-Mullvad-VPN
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - VPNSP=mullvad
      - PORT=443
      - COUNTRY=USA
      - CITY=New York NY
      - FIREWALL_VPN_INPUT_PORTS=56345 # PORT MULLVAD - https://mullvad.net/en/account/#/ports - #us-nyc-56345 -
      - PORT_FORWARDING=on
      - OPENVPN_USER= ############### #Change to YOUR Username
      - PROTOCOL=tcp
      - OPENVPN_IPV6=off
    image: qmcgaw/gluetun:latest
    ports: 
      - "8001:8000" #HTTP Server https://github.com/qdm12/gluetun/wiki/HTTP-Control-server#OpenVPN
      - "54823:56345" # Forwareded port 56345 over Mullvad - for example: http://89.36.78.125:54823 on Container nginx-ansred-mullvad - NYC
      - "8007:8007" # gluetun-Mullvad-ddns-updater
    volumes: 
      - "/home/pi/Docker/Gluetun/config/mullvad_openvpn_linux_us_nyc:/gluetun"

################################################################################################

  nginx:
    container_name: gluetun-Mullvad-nginx-ansred
    image: ghcr.io/linuxserver/nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/pi/Docker/Bootstrap/ansred:/config
      #Nginx Listening Port in /home/pi/Docker/Bootstrap/ansred/nginx/site-confs/default
    network_mode: "service:gluetun-Mullvad-VPN"
   #ports:
   #  - 56345:56345 Commented since it's using network_mode gluetun - port forwared using VPN - NYC
    restart: unless-stopped
    
################################################################################################

  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: gluetun-Mullvad-ddns-updater
    network_mode: "service:gluetun-Mullvad-VPN"
   #ports:
   #  - 8007:8007/tcp
    volumes:
      - /home/pi/Docker/DDNS-Updater-VPN/data:/updater/data
    environment:
      - CONFIG=
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - HTTP_TIMEOUT=10s

      # Web UI
      - LISTENING_PORT=8007
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_LEVEL=info
      - LOG_CALLER=hidden
      - GOTIFY_URL=
      - GOTIFY_TOKEN=
    restart: always
    
################################################################################################

```
