### DISCUSSION TITLE
Help in creating a (Docker Compose) Gluetun container stack - please share any working examples  ?

### DISCUSSION THREAD

**Discussion by nodecentral** [qdm12/gluetun#471] [Ideas]
Hi all

I’m still finding my feet with all of this, but I’ve manage to pull together a Docker Compose yml for a PureVPN stack of linked containers. (Sorry if I’m not using the correct terminology) - to do this, I’ve leveraged examples associated with this repository, plus I’ve found other examples online e.g https://gist.github.com/Webreaper/81ecda3ecc45fa61a16dfc90cfc4550d , https://nathanlabadie.com/htpc-docker-and-private-internet-access/)

Please could you have a look and let me know what you think, am I missing anything, as it’s not working fully yet, the main thing is that Deluge is not downloading anything, i can add things, but it times out and/or reports connection errors (FYI -  I’ve updated the download location /download, and all containers now share the same download section ?)

Feel free to share yours too ? What other apps should I have in my gluetun stack ?

```yml
version: "2"
services:
  gluetun:
    image: qmcgaw/gluetun:v3.16.0
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8000:8000/tcp # Built-in HTTP Control Server
      - 8112:8112/tcp # Deluge Admin interface
      - 89:80/tcp # whoami health api
      - 7878:7878/tcp # radarr access 
      - 9117:9117/tcp # jackett
      - 8989:8989/tcp # sonarr
      - 8686:8686/tcp # lindarr
      - 3000:3000/tcp # firefox
    # command:
    volumes:
      - /share/Container/Gluetun:/gluetun
    environment:
      # More variables are available, see the readme table
      - VPNSP=purevpn
      - REGION=North Holland
      - COUNTRY=Netherlands
      - SERVER_HOSTNAME=nl2-ovpn-udp.pointtoserver.com
      - OPENVPN_USER=purevpnname
      - OPENVPN_PASSWORD=mypassword
      - OPENVPN_VERBOSITY=3
      # Timezone for accurate logs times
      - TZ=Europe/London
    restart: always

  deluge:
    container_name: deluge
    image: ghcr.io/linuxserver/deluge
    network_mode: "service:gluetun"
    environment:
      - PUID=1005
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/Container/delugeLS/config:/config
      - /share/Container/Gluetun/downloads:/downloads
    restart: unless-stopped
    depends_on:
        - gluetun

  whoami: 
    container_name: whoami
    image: containous/whoami # A container that exposes an API to show its IP address
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
        - gluetun

  jackett:
        image: ghcr.io/linuxserver/jackett:latest
        container_name: jackett
        environment:
            - PUID=1005
            - PGID=1000
            - TZ=Europe/London
        volumes: # mkdir -p /share/Container/jackett/{config,downloads}
            - /etc/localtime:/etc/localtime:ro
            - /share/Container/jackett/config:/config
            - /share/Container/Gluetun/downloads:/downloads
        restart: unless-stopped
        network_mode: service:gluetun
        depends_on:
            - gluetun
            - deluge

  sonarr:
        image: ghcr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=1005
            - PGID=1000
            - TZ=Europe/London
        volumes: # mkdir -p /share/Container/sonarr/{config,tv,downloads}
            - /etc/localtime:/etc/localtime:ro
            - /share/Container/sonarr/config:/config
            - /share/Container/Gluetun/downloads/tv:/tv
            - /share/Container/Gluetun/downloads:/downloads
        restart: unless-stopped
        network_mode: service:gluetun
        depends_on:
            - gluetun
            - deluge
            - jackett

  radarr:
        image: ghcr.io/linuxserver/radarr:latest
        container_name: radarr
        environment:
            - PUID=1005
            - PGID=1000
            - TZ=Europe/London
        volumes: # mkdir -p /share/Container/radarr/{config,movies,downloads}
            - /etc/localtime:/etc/localtime:ro
            - /share/Container/radarr3/config:/config
            - /share/Container/Gluetun/downloads/movies:/movies
            - /share/Container/Gluetun/downloads:/downloads
        restart: unless-stopped
        network_mode: service:gluetun
        depends_on:
            - gluetun
            - deluge
            - jackett

  lidarr:
        image: ghcr.io/linuxserver/lidarr:latest
        container_name: lidarr
        environment:
            - PUID=1005
            - PGID=1000
            - TZ=Europe/London
        volumes: # mkdir -p /share/Container/lidarr/{config,music,downloads}
            - /etc/localtime:/etc/localtime:ro
            - /share/Container/lidarr/config:/config
            - /share/Container/Gluetun/downloads/music:/music
            - /share/Container/Gluetun/downloads:/downloads
        restart: unless-stopped
        network_mode: service:gluetun
        depends_on:
            - gluetun
            - deluge
            - jackett

  firefox:
    image: ghcr.io/linuxserver/firefox:latest
    container_name: firefox
    environment:
      - PUID=1005
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/Container/firefox:/config
    network_mode: service:gluetun
    shm_size: "1gb"
    restart: unless-stopped
    depends_on:
        - gluetun
 ```
