### DISCUSSION TITLE
Custom VPN cant establish connection bad protocol

### DISCUSSION THREAD

**Discussion by Sakujakira** [qdm12/gluetun#482] [Q&A] [answered]
Hello there,

since friday i cant connect anymore with my VPN Provider through Gluetun. Everything i get is this error:

`ERROR openvpn: remote: bad protocol associated with host remote: '443'`

This is my docker-compose:

```yml
gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8885:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
      - 9092:9091 # Expose Transmission Webinterface
      - 9117:9117 # Expose Jackett Interface
    volumes:
      - ${USERDIR}/docker/gluetun:/gluetun
      - ${USERDIR}/docker/gluetun/AirVPN_SE-Stockholm_Lupus_UDP-443.ovpn:/gluetun/custom.conf
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - FIREWALL_VPN_INPUT_PORTS=38080
      #- FIREWALL=on
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
      - OPENVPN_USER=""
      - OPENVPN_PASSWORD=""
      - OPENVPN_VERBOSITY=6
      - HTTPPROXY=on
      - HTTPPROXY_LOG=on
      - PROTOCOL=UDP
      - BLOCK_MALICIOUS=on
      - BLOCK_SURVEILLANCE=on
      - BLOCK_ADS=on
    restart: always
    networks:
      - web
    #security_opt:
    #  - no-new-privileges:true
    labels:
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.discord.webhook=https://discord.com/api/webhooks/[...]"
      - "org.hotio.pullio.author.avatar=https://hotio.dev/img/pullio-sunglasses.svg"
```

I'd appreciate any hints or tips for resolving my issue.

Kind regards
