### DISCUSSION TITLE
Swag Stack

### DISCUSSION THREAD

**Discussion by devilliersjohnny** [qdm12/gluetun#484] [Q&A]
Hi all

Have been attempting to get a linuxserver SWAG stack running using the gluetun vpn after the struggle of getting the docker secrets up and running ( amazingly poorly documented ) got the vpn service up and running telling me that it was connected  

Following is a running stack for Swag (minus my login details)

```yml
version: '3' 
services:
# Portainer
  portainer:
    image:  portainer/portainer-ce
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    ports:
      - 8000:8000
      - 9000:9000
    restart: always 
# Pihole - DNS Management System
  pihole:
    container_name: pihole
    hostname: RPi4
    image: pihole/pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8080:80/tcp
      - 4443:443/tcp
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=${WEBPASSWORD}
      - ServerIP=192.168.101.35
    # Volumes store your data between container upgrades
    volumes:
      - ./pihole/etc-pihole/:/etc/pihole/
      - ./pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
## gluetun vpn
#  gluetun:
#    image: qmcgaw/gluetun
#    container_name: gluetun
#    cap_add:
#      - NET_ADMIN
#    network_mode: bridge
#    secrets:
#      - openvpn_user
#      - openvpn_password
#    environment:
#      - OPENVPN_USER=bla
#      - OPENVPN_PASSWORD=nla
#      - OPENVPN_CLIENTKEY=openvpn_clientkey
#      - OPENVPN_CLIENTCRT=openvpn_clientcrt
#      - TZ=${TZ}
#      - VPNSP=${VPNSP}
#      - REGION=${OVPNReg}
#      - CYBERGHOST_GROUP=${OVPNGroup}
#      - SERVER_HOSTNAME=${OVPNServer} 
#      - FIREWALL_OUTBOUND_SUBNETS=${EXTRA_SUBNETS}
#      - BLOCK_ADS=on
#    volumes:
#      - ./gluetun:/gluetun
#      - ./secrets/client.key:/gluetun/client.key:ro
#      - ./secrets/client.crt:/gluetun/client.crt:ro
#    ports:
#      - 8888:8888/tcp # HTTP proxy
#      - 8888:8888/udp # HTTP proxy
#      - 8388:8388/tcp # Shadowsocks
#      - 8388:8388/udp # Shadowsocks
#      - 8081:8000/tcp # Built-in HTTP control server
#    restart: always
## DuckDNS - public ip tracker
  duckdns:
    image:  ghcr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=${PUID} #optional
      - PGID=${PGID} #optional
      - TZ=${TZ}
      - SUBDOMAINS=${DNSDOMAIN} 
      - TOKEN=${DUCKDNSTOKEN}
      - LOG_FILE=false #optional
    volumes:
      - ./duckdns:/config #optional
    restart: unless-stopped
# Cloudflare DDNS
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    restart: always
    environment:
      - API_KEY=${CLOUDFLARE_API_KEY}
      - ZONE=${CLOUDFLARE_ZONE}
      - SUBDOMAIN=${CLOUDFLARE_SUBDOMAIN}
      - PUID=${PUID}
      - PGID=${PGID}
      - PROXIED=${CLOUDFLARE_PROXIED}
    restart: always
# Wireguard - Remote Access to server     
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SERVERURL=${DNSDOMAIN}.duckdns.org #optional
      - SERVERPORT=51820 #optional
      - PEERS=10 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - ./wireguard-server/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
# Nextcloud - like google drive but free and self hosted    
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./nextcloud/config:/config
      - ./nextcloud/data:/data
    depends_on:
      - mariadb
    restart: unless-stopped
# Maria db for nextcloud content    
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ncuser
      - MYSQL_PASSWORD=${NCPASSWORD}
    volumes:
      - ./mariadb:/config
    restart: unless-stopped 
# Plex - Media Server 
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
    volumes:
      - ./plex:/config
      - ${EXTERNALSTORAGE}/Media:/External Media
    restart: unless-stopped  
# Bitwarden
  bitwarden:
    image: bitwardenrs/server
    container_name: bitwarden
    environment:
      WEBSOCKET_ENABLED: ${WEBSOCKET_ENABLED}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      DOMAIN: https://${DOMAIN_HTTPS}
    volumes: 
      - ./bw-data:/data
    restart: always
# Heidmal GUI Interface for server
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./heimdall:/config
    restart: unless-stopped    
# Swag Webserver software    
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${CLOUDFLARE_ZONE}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=${EMAIL}
      - CERTPROVIDER=zerossl
    volumes:
      - ./swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

secrets:
  openvpn_user:
    file: ./secrets/openvpn_user
  openvpn_password:
    file: ./secrets/openvpn_password
  openvpn_clientkey:
    file: ./secrets/client.key
  openvpn_clientcrt:
    file: ./secrets/client.crt     
    
networks:
  default:
    external:
      name: ${NETWORK_NAME}
```

Have attempted many different variations on this to attempt to get the system running however am unable to any advice is welcome
