### DISCUSSION TITLE
Custom Plaintext address being ignored

### DISCUSSION THREAD

**Discussion by kingofhteseas** [qdm12/gluetun#494] [Q&A] [answered]
When setting the DNS_PLAINTEXT_ADDRESS to a different address than 1.1.1.1 it does not pick up the change and still shows 1.1.1.1. Using Docker Compose. Doesn't matter if DOT is off or on.

```yml
version: "3.7"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 2202:2202/tcp # ubooquityConsole
      - 2203:2203/tcp # ubooquityAdmin
    # command:
    volumes:
      - /docker/gluetun:/gluetun
    environment:
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - OPENVPN_USER=<redacted>
      - OPENVPN_PASSWORD=<redacted>
      - VPNSP=private internet access
      - DOT=off
      - DNA_PLAINTEXT_ADDRESS=194.242.2.2
      - TZ=America/New_York
    restart: always
```
