### DISCUSSION TITLE
Qbittorrent stalled at Downloading Metadata when connecting through Gluetun

### DISCUSSION THREAD

**Discussion by Wils0** [qdm12/gluetun#531] [Q&A]
Hi all,

I have a Synology running DSM 7 and have a number of docker containers set up to do media management (Donarr, Radarr, Bazarr, SABNZBD, Plex, etc) which all works swimmingly, and in order to manage torrents I wanted to run Jackett and Qbittorrent containers, connecting to VPN via a Gluetun container.

I have managed to get them all seemingly successfully set up, and I can validate that Gluetun is connected (though I've recently had some issues with some Australian servers) and that Jackett is connected through Gluetun, but torrents added to qbittorrent just keeps getting stuck at Downloading Metadata, and no matter what I've tried I just can't get it to consistently work. It seems to fail to connect to the trackers, and shows 0 seed/peers  connected and MUCH smaller number of available seeds/peers than the torrent details suggested.

I'm 100% sure I'm just doing (or not doing) something that should be obvious, but I feel like I've been belting my head against a wall for ages.

The docker-compose file contains:

```yaml
version: "3.7"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
      - 9388:9388/tcp # Shadowsocks?
      - 9388:9388/udp # Shadowsocks?
      - 6881:6881/tcp # qbittorrent listening port
      - 6881:6881/udp # qbittorrent listening port
      - 9117:9117/tcp # Jackett web-ui port
      - 9117:9117/udp # Jackett web-ui port
      - 8090:8090/tcp # qbittorrent WEB_PORT
    # command:
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      # More variables are available, see the readme table
      - VPNSP=private internet access
      - OPENVPN_USER=PXXXXXXX
      - OPENVPN_PASSWORD=XXXXXXXXXXX
      - PROTOCOL=udp
      - REGION=CA Montreal
      - PORT_FORWARDING=on
      - PORT_FORWARDING_STATUS_FILE=/volume1/docker/gluetun/forwarded_port
      # Timezone for accurate logs times
      - TZ=Australia/Brisbane
    restart: always
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    # ports:
     # - 6881:6881
     # - 6881:6881/udp
     # - 8090:8090
    volumes:
      - /volume1/docker/qbittorrent:/config 
      - /volume1/downloads:/downloads 
    environment:
      - PUID=1028
      - PGID=100
      - TZ=Australia/Brisbane
      - WEBUI_PORT=8090
    restart: unless-stopped
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    network_mode: "service:gluetun"
    # ports:
      # - 9117:9117
    environment:
      - PUID=1034
      - PGID=100
      - TZ=Australia/Brisbane
      - AUTO_UPDATE=true #optional
    volumes:
      - /volume1/docker/jackett:/config
      - /volume1/downloads:/downloads
    restart: unless-stopped
```

**Comment by qdm12** [comment]
Hmm I'm not sure. If these are just torrents, try without port forwarding. I personally use deluge without port forwarding, getting easily 10MB/s which is more than enough for me. Maybe try with Deluge, it might be the torrent client acting strange...?

**Reply by Wils0** [reply]
It's only torrents that seem to be the problem, and it's something related to how it identifies seeds/peers and subsequently makes connections. 

See the attached images showing the massive discrepancy. This is the same torrent, first as it shows in Sonnarr, then as it shows in qbittorrent.
![Sonarr Details](https://user-images.githubusercontent.com/42222916/127764374-0f00b133-254a-40d3-b9e7-e3aa3b9d1972.jpg)
![Qbittorrent Details](https://user-images.githubusercontent.com/42222916/127764400-43d5bc36-2512-4a91-9cba-6afb2f59f052.jpg)

After I saw your suggestion I gave Deluge a go (with no success so far, but that it highly likely to be because I'm not familiar with it so I haven't set it up right yet), and then switched back to qbittorrent to try and nut it out.

This time, it just worked as advertised, but only for a short while, then the same problem comes back and everything is either Downloading Metadata (if it was a magnet link and doesn't yet have the torrent file) or Stalled (if it has the torrent file.

I have switched to a different PIA Endpoint, and tried without port forwarding with no joy 😢

**Reply by qdm12** [reply]
I doubt that's a gluetun issue, although maybe try running with `OPENVPN_VERSION=2.4`? Maybe PIA doesn't like openvpn 2.5. After that I don't know anymore.

Maybe ask PIA directly or on their Reddit?

**Reply by Wils0** [reply]
Using `OPENVPN_VERSION=2.4` made an immediate difference.

![Qbittorrent (OPENVPN_VERSION=2 4)](https://user-images.githubusercontent.com/42222916/127790417-d620551c-25e2-430b-9d49-0bc5a6b38a7c.jpg)

Thanks @qdm12 for your help.  Fingers crossed that it stays stable and effective this time. I'll keep looking into Deluge though.

For completeness, here is the compose file now:

```yaml
version: "3.7"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
      - 9388:9388/tcp # Shadowsocks?
      - 9388:9388/udp # Shadowsocks?
      - 6881:6881/tcp # qbittorrent listening port
      - 6881:6881/udp # qbittorrent listening port
      - 9117:9117/tcp # Jackett web-ui port
      - 9117:9117/udp # Jackett web-ui port
      - 8090:8090/tcp # qbittorrent WEB_PORT
    # command:
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      # More variables are available, see the readme table
      - VPNSP=private internet access
      - OPENVPN_USER=xxxxxxxxxx
      - OPENVPN_PASSWORD=xxxxxxxxxx
      - PROTOCOL=udp
      - REGION=AU Sydney
      - OPENVPN_VERSION=2.4
#      - PORT_FORWARDING=on
#      - PORT_FORWARDING_STATUS_FILE=/volume1/docker/gluetun/forwarded_port
      # Timezone for accurate logs times
      - TZ=Australia/Brisbane
    restart: always
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    # ports:
     # - 6881:6881
     # - 6881:6881/udp
     # - 8090:8090
    volumes:
      - /volume1/docker/qbittorrent:/config 
      - /volume1/downloads:/downloads 
    environment:
      - PUID=1028
      - PGID=100
      - TZ=Australia/Brisbane
      - WEBUI_PORT=8090
    restart: unless-stopped
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    network_mode: "service:gluetun"
    # ports:
      # - 9117:9117
    environment:
      - PUID=1034
      - PGID=100
      - TZ=Australia/Brisbane
      - AUTO_UPDATE=true #optional
    volumes:
      - /volume1/docker/jackett:/config
      - /volume1/downloads:/downloads
    restart: unless-stopped
```
