### DISCUSSION TITLE
Bridge network of gluetun safe?

### DISCUSSION THREAD

**Discussion by iluvatyr** [qdm12/gluetun#561] [Q&A] [answered]
Hello, 
thank you for your amazing app first of all.

##Edit: or is the correct way to do this to join the reverse proxy container into the gluetun container network and then inside the reverse proxy point to the containername gluetun and the port of the container that is connected to gluetun instead of the actual containers name?

I have a question regarding the use of a bridge network with the gluetun container. 
Lets say I have some containers that use gluetuns network via  "network-mode: gluetun and I publish the ports to the host so that other containers that are not in this network can access those containers.

E.g. I have a IRC Client that I connect to the internet via gluetun. Then I have a reverse proxy container to the irc-client to access it. The port of the irc client is published in gluetun. That way I can access the irc client normally and it connects to the internet via gluetun.

But instead of publishing those ports, would it be possible (and safe in the sense that there is no possibility of leaking the IP or else) of bridging the gluetun container with another network so that I can connect containers to each other?. 

Since I set the "network-mode" on the containers that should be connected to gluetun, I cannot set custom networks for that container. It has to be set on gluetun container. I would then make a new network called :  bridge_network and add gluetun and the reverse proxy to it so the gluetun docker-compose.yaml would look like this:

```yml
version: '3.8'
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    environment:
      - PUID=998
      - PGID=100
      - VPNSP=VPNPROVIDER
      - OPENVPN_VERBOSITY=3
    volumes:
      - /srv/Config/Gluetun/:/gluetun
    ports:
      - 9001:9000 #IRCCLIENT
    cap_add:
      - NET_ADMIN
    secrets:
      - openvpn_user
      - openvpn_password
    restart: unless-stopped
    networks:
        - default
        - bridge_network


networks:
    bridge_network:
        external: true
```

I would also add the Reverse proxy container to that network in the same way so I can point to the container name instead of the host IP. Would it be possible that the IRC client exposes my real ip that way? Is the question clear?
