### DISCUSSION TITLE
The test container shows actual IP

### DISCUSSION THREAD

**Discussion by nithin-bose** [qdm12/gluetun#607] [Q&A]
The gluetun container was run using the docker-compose.yml file in the documentation, modified for surfshark as follows:
```
version: "3.7"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
    # command:
    volumes:
      - ./config:/gluetun
    environment:
      # More variables are available, see the Wiki table
      - OPENVPN_USER=<user name>
      - OPENVPN_PASSWORD=<password>
      - VPNSP=surfshark
      - VPN_TYPE=openvpn
      - REGION=Germany Frankfurt am Main
      - SERVER_HOSTNAME=de-fra.prod.surfshark.com
      # Timezone for accurate logs times
     - TZ=<time zone>
    restart: always
```

The last line in the logs of gluetun container shows that it got an IP from surfshark.
```
gluetun  | 2021/09/09 15:29:07 INFO vpn: You are running on the bleeding edge of latest!
gluetun  | 2021/09/09 15:29:14 INFO ip getter: Public IP address is 156.146.33.70 (Germany, Hesse, Frankfurt am Main)
``` 

However, when running  the test container with the following command:
```
docker run --rm --network=container:gluetun alpine:3.14 apk add wget && wget -qO- https://ipinfo.io
```
returns my original IP details.

However if I run the same command inside the gluetun container as follows:
```
docker exec -it gluetun wget -qO- https://ipinfo.io
{
  "ip": "156.146.33.70",
  "hostname": "unn-156-146-33-70.cdn77.com",
  "city": "Frankfurt am Main",
  "region": "Hesse",
  "country": "DE",
  "loc": "50.1155,8.6842",
  "org": "AS60068 Datacamp Limited",
  "postal": "60311",
  "timezone": "Europe/Berlin",
  "readme": "https://ipinfo.io/missingauth"
}
```
It returns the VPN IP details as expected. What am I missing here?

Please help, thanks in advance!
