### DISCUSSION TITLE
"cannot join network of a non running container:"

### DISCUSSION THREAD

**Discussion by jgiddens** [qdm12/gluetun#637] [Q&A] [answered]
Hi there!

I am trying to setup gluetun in a fresh LXC container based on ubuntu 21.04, running on proxmox 7.0.  The LXC is privileged.  Here is what my docker-compose looks like:

```yml
version: "3.7"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8080:8080/tcp # hotio/qbittorent
    volumes:
      - /mnt/tank/config/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPNSP=private internet access
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=username
      - OPENVPN_PASSWORD=password
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      # - WIREGUARD_ADDRESS=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=America/Chicago
      - REGION=US Chicago,US Texas,US Houston,Netherlands,UK London,US Seattle
  qbittorrent:
    container_name: qbittorrent
    image: hotio/qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /mnt/tank/config/qbittorent:/config
      - /mnt/tank/downloads/qbittorent/:/downloads
    network_mode: "service:gluetun" 
```

To my untrained eye I think I have followed the directions precisely.  When I do a docker-compose up i get the following:

```
> root@dls:~# docker-compose up -d
>Creating network "root_default" with the default driver
>Creating root_gluetun_1 ... done
>Creating qbittorrent    ... error

> ERROR: for qbittorrent  Cannot start service qbittorrent: cannot join network of a non running container: 082244d1303040693c43b654f5a377775a4fe911d98d0af647ea0a0cb9693357
> 
> ERROR: for qbittorrent  Cannot start service qbittorrent: cannot join network of a non running container: 082244d1303040693c43b654f5a377775a4fe911d98d0af647ea0a0cb9693357
> ERROR: Encountered errors while bringing up the project.
> root@dls:~# 
```

Also curious is that even though docker says it is starting gluetun when running the compose file, after the error if I do a Docker PS i get this:

```
> root@dls:~# docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

Suggestions?  Any ideas what may be causing this issue?

Thanks!

**Comment by qdm12** [comment, marked as answer]
~Yes that's strange, it looks valid.~

EDIT: Try `docker-compose up gluetun`, My guess is gluetun fails to start. check the logs to find out why. You can ignore what's below.

Try

```sh
docker-compose up -d gluetun
docker-compose up qbitorrent
```

?

**Reply by jgiddens** [reply]
Thanks for the reply.  I did as you suggested.  With the -d flag it docker says "...done" for the container but then it is still not running.  I did run the command without the -d and got a different response.  I ran "docker-compose up gluetun" and it showed the start up log.  All looked normal until the end:

> gluetun_1      | |--Github version information: enabled
gluetun_1      | 2021/09/23 08:04:21 INFO routing: default route found: interface eth0, gateway 172.21.0.1
gluetun_1      | 2021/09/23 08:04:21 INFO routing: local ethernet link found: eth0
gluetun_1      | 2021/09/23 08:04:21 INFO routing: local ipnet found: 172.21.0.0/16
gluetun_1      | 2021/09/23 08:04:21 INFO routing: default route found: interface eth0, gateway 172.21.0.1
gluetun_1      | 2021/09/23 08:04:21 INFO routing: adding route for 0.0.0.0/0
gluetun_1      | 2021/09/23 08:04:21 INFO firewall: firewall disabled, only updating allowed subnets internal list
gluetun_1      | 2021/09/23 08:04:21 INFO routing: default route found: interface eth0, gateway 172.21.0.1
gluetun_1      | 2021/09/23 08:04:21 INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
gluetun_1      | 2021/09/23 08:04:21 INFO routing cleanup...
gluetun_1      | 2021/09/23 08:04:21 INFO routing: default route found: interface eth0, gateway 172.21.0.1
gluetun_1      | 2021/09/23 08:04:21 INFO routing: deleting route for 0.0.0.0/0
gluetun_1      | 2021/09/23 08:04:21 ERROR cannot Unix Open TUN device file: operation not permitted
gluetun_1      | 2021/09/23 08:04:21 INFO Shutdown successful

I did some poking around in the LXC config file in /etc/pve/lxc/308.conf (the container number) and realized I needed to add:

lxc.cgroup2.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net dev/net none bind,create=dir 0 0

to the LXC conf.  This allows the container to create tunnel interfaces.

After that I just needed to do a little docker cleanup and pruning and it all seems to start right.  Thanks!

**Reply by qdm12** [reply]
No problem, enjoy! Why not using Docker instead of raw LXC containers by the way?

**Reply by jgiddens** [reply]
On my proxmox I run Docker nested inside the lxc container.  My other options were to deploy a full KVM vm and run docker or apps within it, or to run docker on the bare metal Proxmox host.  I don't want to host any services (except hardware reporting) on the bare metal host, and running LXC has a lot less overhead than running a full VM but achieves the same goal of running docker.  I also can spin up new LXC containers if I want to mess around with stuff and not impact my production services.

**Reply by user037951** [reply]
@jgiddens could you elaborate on what more you did?
I'm having the same problem with practically the same setup and also getting the error "ERROR cannot Unix Open TUN device file: operation not permitted"

I've got these 2 in the config, also tried with 0 0 at the end.
lxc.cgroup2.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net dev/net none bind,create=dir

when using ls -l in the LXC the files come up as owned by root which seems correct and are under 100000 on the host

**Reply by jgiddens** [reply]
Hey...  Its been a minute so I had to refresh my memory.  After I made the changes above I was still having problems, they just became inconsistent.  My server sits behind an enterprise firewall and I am the only user so I run all of my containers as root.  I know thats bad.  I also add this line to the container conf:

lxc.apparmor.profile: unconfined

because I was getting lots of errors with apparmor.  Once I added that line and restarted the container I then unintalled apparmor completely.  This seemed to clear up most of my issues.  I dont know why, i just hacked around until it started working.  Now I try to not look at it so it wont fail :)

**Reply by qdm12** [reply]
If any of you figure out a restrictive yet workable solution for LXC, feel free to re-comment here I can add it to the wiki. Good luck!

**Reply by user037951** [reply]
This is the way I got it to work on an unprivileged container. So it's "safe" just like usual for unprivileged containers.

nano /etc/pve/lxc/CONTAINER NR.conf 
```
lxc.cgroup2.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net dev/net none bind,create=dir
lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file
```
(have not verified if you need both of the bottom lines, it was just easier after having so much headaches with this to keep trying with both in the file since there was so much different information floating about)

then just add this to the docker compose file

```
    devices:
      - /dev/net/tun:/dev/net/tun
```

Works without problems for me after doing it this way. Hope this can help someone else in the future.

**Reply by qdm12** [reply]
Hey again, I'm adding all this to the Wiki now.
Quick questions:

1. Is `CONTAINER NR` the container ID? Or is it a number for LXC containers?
2. Does it work with just `- /dev/net/tun` instead of `- /dev/net/tun:/dev/net/tun`?

**Reply by user037951** [reply]
Hi,

Sorry for not being clear about it.

1. Yes that's correct, container nr is container ID (ex /etc/pve/lxc/100.conf)
2. As for this question, I can not answer as I'm not that versed in Docker/Docker-compose. Perhaps you know this answer better, as this is just inside the container to the docker. If you can bind mount something from the host to the docker container if it's going to be stored in the same location as I specified and in your example if that works for any other use case scenario then it should work just as well in this scenario

**Reply by qdm12** [reply]
Ok thanks! I have the information needed from other conversations as well (#700) so that will be up in the wiki soon 😉

**Reply by dvc214** [reply]
Thank you!  After hours of tinkering, your answer hit the nail on the head.

**Comment by sixspot** [comment]
I have run into the issue. It seems to be a race condition because it may or may not happen with `docker compose up -d`.  Plain depends_on makes the dependent containers wait. The service_started or service_healthy condition takes advantage of gluetun's healtcheck.

```yml
  network_mode: "container:gluetun"
  depends_on:
     gluetun:
        condition: service_started
```

I found that info at [docker-compose-healthcheck](https://github.com/peter-evans/docker-compose-healthcheck), btw. I didn't see it in the compose docks. I'm using docker 2.5.0 without the standalone docker-compose binary.
