### DISCUSSION TITLE
OVPN Wireguard as a custom provider issue

### DISCUSSION THREAD

**Discussion by Magic-Deceiver** [qdm12/gluetun#677] [Ideas]
I have been using Gluetun for quite a while now and it has been proven to be extremely solid. Kudos to @qdm12!

However, recently I have started using OVPN as a VPN provider and for some reason, it simply won't work. 

Below is my configuration for docker-compose, and the logs associated with it. Maybe someone more knowledgeable will be able to answer what I did wrong.

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8550:80/tcp
      - 9117:9117/tcp # Jackett WebUI
      - 8080:8080/tcp # qBitorrent WebUI
      - 6881:6881/tcp # qBitorrent tcp connection port
      - 6881:6881/udp # qBitorrent udp connection port
    volumes:
      - /my-path-to-config/gluetun:/gluetun
    environment:
      - VPNSP=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_ENDPOINT_IP=152.89.162.27 # endpoint IP according to "https://www.nslookup.io/dns-records/vpn72.prd.zurich.ovpn.com"
      - WIREGUARD_ENDPOINT_PORT=9929 # this port is what I see on the wireguard configuration file
      - WIREGUARD_PUBLIC_KEY=DO9_____________________________= # this is the public key I generated on OVPN
      - WIREGUARD_PRIVATE_KEY=MNX_____________________________= # this is the private key
       # - WIREGUARD_PRESHARED_KEY= (Im actually not sure what to put this one and I see that this is not a mandatory env variable, so I deleted it, I have tried adding peer public key in there but it didn't work either)
      - WIREGUARD_ADDRESS=172.30.76.76/32 # this is the address assigned to me
    restart: always
```

The file I downloaded (modified) for the public key DO9_____________________________=

```ini
[Interface]
PrivateKey = MNX_____________________________
Address = 172.30.76.76/32, fd00:0:1337:cafe:1111:1111:ec98:9d42/128
DNS = 46.227.67.134, 192.165.9.158
 
[Peer]
PublicKey = lL+_____________________________=
AllowedIPs = 0.0.0.0/1, 128.0.0.0/1, ::/1, 8000::/1
Endpoint = vpn72.prd.zurich.ovpn.com:9929
```

And this is the logs, it basically repeats itself: 

```
2021/10/15 12:36:20 INFO vpn: stopping
2021/10/15 12:36:20 INFO vpn: starting
2021/10/15 12:36:20 INFO firewall: setting VPN connection through firewall...
2021/10/15 12:36:20 INFO wireguard: Connecting to 152.89.162.27:9929
2021/10/15 12:36:20 INFO wireguard: Wireguard is up
2021/10/15 12:36:33 ERROR ip getter: Get "https://ipinfo.io/ip": dial tcp: lookup ipinfo.io on 1.1.1.1:53: read udp 172.30.76.76:41613->1.1.1.1:53: i/o timeout
2021/10/15 12:36:33 INFO ip getter: retrying in 5s
2021/10/15 12:36:38 INFO dns over tls: downloading DNS over TLS cryptographic files
2021/10/15 12:36:48 WARN dns over tls: cannot update files
2021/10/15 12:36:48 INFO dns over tls: attempting restart in 2m40s
2021/10/15 12:36:48 ERROR ip getter: Get "https://domains.google.com/checkip": dial tcp: lookup domains.google.com on 1.1.1.1:53: read udp 172.30.76.76:48809->1.1.1.1:53: i/o timeout
2021/10/15 12:36:48 INFO ip getter: retrying in 5s
```

I am not entirely sure what I did wrong, and I hope someone could help me get this working, because so far I really enjoyed OVPN (substantially faster speed than Mullvad in my experience, but I've heard the opposite on Reddit)

Thanks for tuning in, and I hope that maybe one day Quentin will be able to add OVPN as one of the providers!

Have a great rest of your day!

MD

Update: 

Okay, my dumb brain put the public key wrong. Instead of this (public key from OVPN): 
>       - WIREGUARD_PUBLIC_KEY=DO9_____________________________=
>       - WIREGUARD_PRIVATE_KEY=MNX_____________________________=

It should be this (public key from peer):
>       - WIREGUARD_PUBLIC_KEY=lL+_____________________________=
>       - WIREGUARD_PRIVATE_KEY=MNX_____________________________=

If anyone needs help, feel free to reach out! Would love to help out anyone who has trouble setting it up! (disclaimer: I am no expert in this, but I spent a substantial amount of time trying to make it work, lol)
