### DISCUSSION TITLE
[Need Help] Configuring gluetun with containers with custom ports

### DISCUSSION THREAD

**Discussion by ghost** [qdm12/gluetun#733] [Q&A]
Hey there

So I already have a few containers set up through gluetun. But in all those containers, I'm mostly using the default ports of the containers.

Now I've found a new container, that already uses one of the ports that I already mapped through gluetun.

In the new container, I can set custom ports using a `.env` file.. The `docker-compose.yml` of the container looks like this:
```
version: "3.2"

services:
  geoip-updater:
    image: crazymax/geoip-updater:latest
    volumes:
      - "./data/geoip:/data"
    env_file:
      - "./geoip-updater.env"
    restart: always

  rtorrent-rutorrent:
    image: crazymax/rtorrent-rutorrent:latest
    expose:
      - "${RT_DHT_PORT}/udp"
      - "${XMLRPC_PORT}"
      - "${RUTORRENT_PORT}"
      - "${WEBDAV_PORT}"
      - "${RT_INC_PORT}"
    ports:
      - target: ${RT_DHT_PORT}
        published: ${RT_DHT_PORT}
        protocol: udp
      - target: ${RUTORRENT_PORT}
        published: ${RUTORRENT_PORT}
        protocol: tcp
      - target: ${WEBDAV_PORT}
        published: ${WEBDAV_PORT}
        protocol: tcp
      - target: ${RT_INC_PORT}
        published: ${RT_INC_PORT}
        protocol: tcp
    env_file:
      - "rtorrent-rutorrent.env"
      - ".env"
    volumes:
      - "./data:/data"
      - "./downloads:/downloads"
      - "./passwd:/passwd"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: always

  rtorrent-logs:
    image: bash
    command: bash -c 'tail -f /log/*.log'
    depends_on:
      - rtorrent-rutorrent
    volumes:
      - "./data/rtorrent/log:/log"
    restart: always
```

and the `.env` file looks like so:
```
RT_DHT_PORT=6881
XMLRPC_PORT=8000
RUTORRENT_PORT=8080
WEBDAV_PORT=9000
RT_INC_PORT=50000
```

Problem is, I have other containers that use port `6881`, `8000`, and `8080`. 
I can obviously edit them in the `.env` file, but that won't work if I have to pass all the ports through the gluetun `PORTS`? 
Can I pass through the .env file to gluetun, and make the `rtorrent-rutorrent` use those?? Sorry, but I'm relatively new to docker 😨 

How do I make this work with gluetun?

**Comment by ghost** [comment]
I think I found a solution..

Setting the environment options in the `.env` file and then moving the `ports` to gluetun seems to work somewhat.

If there's a better way, please enlighten me. Do I need to put in the `expose` part in gluetun as well?

**Comment by hugalafutro** [comment]
While I don't have exact answer to you as I'm fairly new to docker too, I have a working gluetun stack with full media server + all necessary "arr mateys yohoho and a bottle of rum" indexing & downloading services and I forward all ports of all services via gluetun so maybe you could adapt from this:
```
version: '3.7'
services:
  gluetun:
    image: qmcgaw/private-internet-access
    container_name: pia_gluetun_vm-docker
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 9888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
# other containers ports
      - 8112:8112     # deluge webui
      - 58846:58846   # deluge daemon
      - 6767:6767     # bazarr
      - 8989:8989     # sonarr
      - 7878:7878     # radarr
      - 8686:8686     # lidarr
      - 8191:8191     # flaresolverr
      - 3579:3579     # ombi
      - 4040:4040     # airsonic
      - 8096:8096     # jellyfin
      - 8227:8227     # pyload
      - 9696:9696     # prowlarr
    volumes:
      - ./data_gluetun:/gluetun
      - ./data_gluetun/port_forward:/tmp/gluetun/forwarded_port
    environment:
      - OPENVPN_IPV6=off
      - OPENVPN_ROOT=no
      - VPNSP=private internet access
      - TZ=${TIMEZONE}
      - OPENVPN_USER=${PIA_USER}
      - OPENVPN_PASSWORD=${PIA_PASS}
      - REGION=${PIA_REGION}
      - BLOCK_MALICIOUS=off
      - UPDATER_PERIOD=48h
      - PORT_FORWARDING=on
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - HTTPPROXY=on
      - HTTPPROXY_USER=${PROXY_USER}
      - HTTPPROXY_PASSWORD=${PROXY_PASS}
      - SHADOWSOCKS=on
      - SHADOWSOCKS_PASSWORD=${SHADOW_PASS}
      - SHADOWSOCKS_LOG=off
    restart: always

  deluge:
#    build: ./deluge_my_image
    image: ghcr.io/hugalafutro/deluge_six1.15:latest
    container_name: pia_deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DELUGE_LOGLEVEL=WARNING
      - DOCKER_MODS=linuxserver/mods:universal-wait-for-internet
    volumes:
      - ./config_deluge:/config
      - /shares/samba/media2/_downloads:/downloads
    network_mode: "service:gluetun"
    restart: always
    depends_on:
      - gluetun
    stop_grace_period: 60s

  flaresolverr:
    container_name: pia_flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    image: flaresolverr/flaresolverr:latest
    environment:
      - TZ=${TIMEZONE}
      - LOG_LEVEL=info
    network_mode: "service:gluetun"
    restart: always
    depends_on:
      - gluetun

  lidarr:
    image: linuxserver/lidarr
    container_name: pia_lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:universal-wait-for-internet
    volumes:
      - ./config_lidarr:/config
      - /shares/samba/media:/media
      - /shares/samba/media2:/media2
    network_mode: "service:gluetun"
    restart: always
    depends_on:
      - gluetun
      - prowlarr
      - deluge
    stop_grace_period: 60s

  radarr:
    image: linuxserver/radarr
    container_name: pia_radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:universal-wait-for-internet
    volumes:
      - ./config_radarr:/config
      - /shares/samba/media:/media
      - /shares/samba/media2:/media2
    network_mode: "service:gluetun"
    restart: always
    depends_on:
      - gluetun
      - prowlarr
      - deluge
    stop_grace_period: 60s

  sonarr:
    image: linuxserver/sonarr
    container_name: pia_sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:universal-wait-for-internet
    volumes:
      - ./config_sonarr:/config
      - /shares/samba/media:/media
      - /shares/samba/media2:/media2
    network_mode: "service:gluetun"
    restart: always
    depends_on:
      - gluetun
      - prowlarr
      - deluge
    stop_grace_period: 60s

  bazarr:
#    image: linuxserver/bazarr:development
    image: linuxserver/bazarr
    container_name: pia_bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:universal-wait-for-internet
    volumes:
      - ./config_bazarr:/config
      - /shares/samba/media:/media
      - /shares/samba/media2:/media2
    network_mode: "service:gluetun"
    restart: always
    depends_on:
      - gluetun
      - sonarr
      - radarr
    stop_grace_period: 60s

  ombi:
    image: lscr.io/linuxserver/ombi:development
    container_name: pia_ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:universal-wait-for-internet
    volumes:
      - ./config_ombi:/config
    restart: always
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
      - sonarr
      - radarr

  airsonic:
    image: airsonicadvanced/airsonic-advanced:latest
    container_name: pia_airsonic
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - 'JAVA_OPTS=-Xmx1024m -Xms1024m'
    volumes:
      - ./config_airsonic:/var/airsonic
      - /shares/samba/media/music:/var/music
      - ./airsonic_playlists:/var/playlists
      - ./airsonic_podcasts:/var/podcast
    network_mode: "service:gluetun"
    restart: always
    depends_on:
      - gluetun
    stop_grace_period: 60s

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:nightly
    container_name: pia_prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:universal-wait-for-internet
    volumes:
      - ./data_prowlarr:/config
    network_mode: "service:gluetun"
    restart: always
    depends_on:
      - gluetun
      - flaresolverr
      - deluge
    stop_grace_period: 60s

  pyload:
    image: linuxserver/pyload
    container_name: pia_pyload
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:universal-wait-for-internet
    volumes:
      - ./config_pyload:/config
      - /shares/samba/private:/downloads
    network_mode: "service:gluetun"
    restart: always
    depends_on:
      - gluetun

  jellyfin:
    image: linuxserver/jellyfin
    container_name: pia_jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:universal-wait-for-internet
    volumes:
      - ./library_jellyfin:/config
      - /shares/samba/media:/media
      - /shares/samba/media2:/media2
    network_mode: "service:gluetun"
    restart: always
    depends_on:
      - gluetun
    stop_grace_period: 60s
```
