### DISCUSSION TITLE
Cannot connect to service running under gluetun

### DISCUSSION THREAD

**Discussion by Huskydog9988** [qdm12/gluetun#748] [Q&A] [answered]
So I have a few serices running under gluetun, and despite my best efforts I cannot connect to them from serivces outside of gluetun's internal network. To start all the containers are under the same docker network, but even still gluetun doesn't resolve. (This doesn't seem to be a docker issue as other containers resolve fine.) I'm further preplexed as gluetun despite this one issue seems to be working perfectly fine. I've looked into solutions at #555, #485, and #356, but none of them have bore any fruit. If you have any ideas as to why specificly gluetun wouldn't be resolving I'd really appreciate it.

**Comment by Huskydog9988** [comment]
Just remebered I never provided my setup. Its divided into multiple files, so here is gluetun and one of the services I have running under it.

`gluetun.yml`
```yml
version: "3.8"

services:
  gluetun:
    image: qmcgaw/gluetun:v3.26.0
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - /data/media/gluetun:/gluetun
    environment:
      - VPNSP=protonvpn
      - CITY=New York City,Secaucus
      # Timezone for accurate logs times
      - TZ=America/New_York
      # login
      - OPENVPN_USER=USERNAME
      - OPENVPN_PASSWORD=PASSWORD
      - UPDATE_PERIOD=24h
      - HEALTH_VPN_DURATION_INITIAL=10s
    restart: always
```

`sonarr.yml`
```yml
version: "3.8"

services:

  gluetun:
    ports:
      # sonarr
      - 8989:8989

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /data/media/sonarr:/config
      - /mnt/media:/media
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
 ```
