### DISCUSSION TITLE
wireguard port forwarding issue with Windscribe

### DISCUSSION THREAD

**Discussion by jostyee** [qdm12/gluetun#749] [Q&A] [answered]
Hi, I'm trying to get gluetun working with qbittorrent on Synology, currently I use it with `dperson/openvpn-client` w/o any problem, but with gluetun I can't get qbittorrent showing the green plug icon (which means port forwarding working), my docker-compose as below:

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8010:8000/tcp # Built-in HTTP control server
      - 9091:9091/tcp # qbittorrent Admin interface
      - 6881:6881/tcp
      - 6881:6881/udp
    # command:
    volumes:
      - ./gluetun:/gluetun
      - ./tmp:/tmp
    environment:
      # More variables are available, see the readme table
      - VPNSP=windscribe
      - VPN_TYPE=wireguard
      - REGION=Singapore
      - COUNTRY=Singapore
      - SERVER_HOSTNAME=masked
      - WIREGUARD_PRESHARED_KEY= masked
      - WIREGUARD_PRIVATE_KEY= masked
      - WIREGUARD_ADDRESS= masked
      - WIREGUARD_PORT= masked
      - WIREGUARD_INTERFACE=wg0
      # Port forwarding
      - FIREWALL_VPN_INPUT_PORTS= masked
      - PUBLICIP_FILE=/tmp/gluetun/ip
      # Timezone for accurate logs times
      - TZ=Asia/Singapore
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: always

  qbittorrent:
   image: linuxserver/qbittorrent
   container_name: qbittorrent
   environment:
     - PUID=1026
     - PGID=100
     - TZ=Asia/Singapore
     - WEBUI_PORT=9091
   volumes:
     - ./config:/config
     - /volume1/Downloads/:/downloads
   network_mode: "service:gluetun"
   depends_on:
     - gluetun
   restart: unless-stopped
```

any clue which part did I misconfigured? Thanks in advance.
