### DISCUSSION TITLE
Running Prowlarr through VPN and reverse proxying with Caddy

### DISCUSSION THREAD

**Discussion by poperigby** [qdm12/gluetun#792] [Q&A] [answered]
Hey. I'm trying to create a setup where Prowlarr has all of it's traffic through ProtonVPN (for reason *ahem*), and then I can access it's dashboard through my own domain, reverse proxied with Caddy. Here's what I have so far

`docker-compose.yml`
```
services:
  app:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    network_mode: "service:vpn"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - config:/config
    restart: unless-stopped
  vpn:
    image: qmcgaw/gluetun
    container_name: prowlarr-vpn
    cap_add:
      - NET_ADMIN
    ports:
      - 9696:9696/tcp
    environment:
      - VPNSP=protonvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
volumes:
  config:
networks:
  default:
    name: reverse_proxy
    external: true
```

`Caddyfile`
```
(sso) {
    authorize {
        set auth url https://auth.haddock.cc
        allow roles authp/admin authp/user
    }
}
{ # Global configuration
    acme_dns cloudflare apikey
    email email@mail.com
    order authorize before reverse_proxy
    order authp before authorize
}
prowl.haddock.cc {
    import sso
    reverse_proxy prowlarr:9696
}
```
Trying to navigate to prowl.haddock.cc gives me a 502.
