### DISCUSSION TITLE
High CPU usage when using `network_mode: "container:gluetun"` instead of `"service:gluetun"`

### DISCUSSION THREAD

**Discussion by bisol84** [qdm12/gluetun#808] [Q&A] [answered]
### Is this urgent?

No

### Host OS

Ubuntu Server 20.04

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-01-13T15:22:43.135Z (commit 7e2ea4d)

### What's the problem 🤔

Hello,

When I'm using qBittorrent trough gluetun, I have a Entrypoint process that's taking lot of CPU.

   1506 root      20   0  853648  34852   6808 S   **_154_**   0.2  16:49.60 entrypoint

I am using 2 containers. One for qBittorrent, one for gluetun. The network interface is set by :
network_mode: "container:gluetun"

I've modified certain settings form my true configuration (country, ip, key).

### Share your logs

```log
2022/01/15 03:38:05 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
2022/01/15 03:38:06 INFO ip getter: Public IP address is 91.193.4.198 (Switzerland, Zurich, Zürich)
2022/01/15 12:51:28 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN

├── VPN settings:
|   ├── VPN provider settings:
|   |   ├── Name: mullvad
|   |   └── Server selection settings:
|   |       ├── VPN type: wireguard
|   |       ├── Countries: france
|   |       └── Wireguard selection settings:
|   └── Wireguard settings:
|       ├── Private key: xxxxxxxx
|       ├── Interface addresses:
|       |   └── 11.22.33.44/32
|       └── Network interface: wg0
├── DNS settings:
|   ├── DNS server address to use: 127.0.0.1
|   ├── Keep existing nameserver(s): no
|   └── DNS over TLS settings:
|       ├── Enabled: yes
|       ├── Update period: every 24h0m0s
|       ├── Unbound settings:
|       |   ├── Authoritative servers:
|       |   |   └── cloudflare
|       |   ├── Caching: yes
|       |   ├── IPv6: no
|       |   ├── Verbosity level: 1
|       |   ├── Verbosity details level: 0
|       |   ├── Validation log level: 0
|       |   ├── System user: root
|       |   └── Allowed networks:
|       |       ├── 0.0.0.0/0
|       |       └── ::/0
|       └── DNS filtering settings:
|           ├── Block malicious: yes
|           ├── Block ads: no
|           ├── Block surveillance: no
|           └── Blocked IP networks:
|               ├── 127.0.0.1/8
|               ├── 10.0.0.0/8
|               ├── 172.16.0.0/12
|               ├── 192.168.0.0/16
|               ├── 169.254.0.0/16
|               ├── ::1/128
|               ├── fc00::/7
|               ├── fe80::/10
|               ├── ::ffff:7f00:1/104
|               ├── ::ffff:a00:0/104
|               ├── ::ffff:a9fe:0/112
|               ├── ::ffff:ac10:0/108
|               └── ::ffff:c0a8:0/112
├── Firewall settings:
|   ├── Enabled: yes
|   └── VPN input ports:
|       └── 56250
├── Log settings:
|   └── Log level: INFO
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Address to ping: github.com
|   └── VPN wait durations:
|       ├── Initial duration: 5s
|       └── Additional duration: 5s
├── Shadowsocks server settings:
|   └── Enabled: no
├── HTTP proxy settings:
|   └── Enabled: no
├── Control server settings:
|   ├── Listening port: 8000
|   └── Logging: yes
├── OS Alpine settings:
|   ├── Process UID: 1000
|   ├── Process GID: 1000
|   └── Timezone: Europe/Paris
├── Public IP settings:
|   ├── Fetching: every 12h0m0s
|   └── IP file path: /tmp/gluetun/ip
└── Version settings:
    └── Enabled: yes
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 56250:56250 # Torrent
      - 8080:8080 # qBittorrent Admin
      - 9091:9091 # Transmission
#      - 8888:8888/tcp # HTTP proxy
#      - 8388:8388/tcp # Shadowsocks
#      - 8388:8388/udp # Shadowsocks
    volumes:
      - ./config:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - HTTPPROXY=off
      - VPNSP=mullvad
      - VPN_TYPE=wireguard
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=xxxxxxxxxxxx
      - WIREGUARD_ADDRESS=11.22.33.44/32
      - COUNTRY=xxxxxxxxxxxx
      - FIREWALL_VPN_INPUT_PORTS=56250
      # Timezone for accurate log times
      - TZ=Europe/Paris
    networks:
      myNetwork:
        ipv4_address: 192.168.1.121

networks:
  myNetwork:
    external:
      name: myNetwork


---
version: "2.1"
services:
  qbittorrent-vpn:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent-vpn
    network_mode: "container:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=8080
    volumes:
      - ./config:/config
      - /downloads:/downloads
    restart: unless-stopped
```
