### DISCUSSION TITLE
Help me connect tube-archivist stack via gluetun

### DISCUSSION THREAD

**Discussion by hugalafutro** [qdm12/gluetun#811] [Q&A]
Hi, I have trouble connecting following stack via gluetun, the main app never connects to the dependent elasticsearch container. Maybe it can't find the es container due to the traffic going thru gluetun container?

I tried both `network_mode: "service:vpn_gluetun_vm-docker"` and `network_mode: "container:vpn_gluetun_vm-docker"` options and I moved the gluetun's https server port to 8001 as the app listens on 8000, and I exposed 8543:8000 in gluetun container. I also tried routing all 3 containers via gluetun to same result. I can't connnect to the webui as the main app keeps saying in log it waits for elasticsearch startup indefinitely (the es container starts up ok)

tube-archivist stack:
```
version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: always
    image: bbilly1/tubearchivist:latest
    network_mode: "container:vpn_gluetun_vm-docker"
#    ports:
#      - 8543:8000
    volumes:
      - /shares/samba/private/_tube-archivist:/youtube
      - ./cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200
      - REDIS_HOST=archivist-redis
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_USERNAME=${TA_NAME}
      - TA_PASSWORD=${TA_PASS}
      - ELASTIC_PASSWORD=${ES_PASS}
      - TZ=${TIMEZONE}
    depends_on:
      - archivist-es
      - archivist-redis

  archivist-redis:
    image: redislabs/rejson:latest
    container_name: archivist-redis
    restart: always
    expose:
      - "6379"
    volumes:
      - ./redis:/data
    depends_on:
      - archivist-es

  archivist-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: archivist-es
    restart: always
    environment:
      - "xpack.security.enabled=true"
      - "ELASTIC_PASSWORD=${ES_PASS}"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es:/usr/share/elasticsearch/data
    expose:
      - "9200"
```

my gluetun:
```
version: '3.7'
services:
  gluetun:
    image: qmcgaw/private-internet-access
    container_name: vpn_gluetun_vm-docker
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 9888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8001:8001/tcp # Built-in HTTP control server
# other containers ports
      - 6767:6767     # bazarr
      - 8989:8989     # sonarr
      - 7878:7878     # radarr
      - 8686:8686     # lidarr
      - 8191:8191     # flaresolverr
      - 3579:3579     # ombi
      - 4040:4040     # airsonic
      - 8096:8096     # jellyfin
      - 5850:5800     # jdownloader2
      - 9696:9696     # prowlarr
      - 8532:8532     # qbittorrent
      - 8543:8000     # tube-archivist
    volumes:
      - ./data_gluetun:/gluetun
    environment:
      - VPNSP=mullvad
      - VPN_TYPE=wireguard
      - OWNED=yes
      - WIREGUARD_PRIVATE_KEY=${MULL_WG_KEY}
      - WIREGUARD_ADDRESS=${MULL_WG_ADDR}
      - CITY=${MULL_CITY}
      - TZ=${TIMEZONE}
      - UPDATER_PERIOD=48h
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - FIREWALL_VPN_INPUT_PORTS=${MULL_PORT}
      - HTTP_CONTROL_SERVER_PORT=8001
      - HTTPPROXY=on
      - HTTPPROXY_USER=${PROXY_USER}
      - HTTPPROXY_PASSWORD=${PROXY_PASS}
      - SHADOWSOCKS=on
      - SHADOWSOCKS_PASSWORD=${SHADOW_PASS}
      - SHADOWSOCKS_LOG=off
    restart: always
```

**Comment by qdm12** [comment]
You need gluetun and others to be on the same docker network. So precise the bridge network for your ES container so that gluetun connected containers can access it as well.

I personally have a custom docker network with gluetun and other containers so they can communicate between each other.

⚠️ note DNS resolution from Gluetun connected containers to resolve other container names doesn't work due to DNS-over-Tls (for now there is an issue to fix it), so you need to use IP addresses.

**Reply by hugalafutro** [reply]
> ⚠️ note DNS resolution from Gluetun connected containers to resolve other container names doesn't work due to DNS-over-Tls (for now there is an issue to fix it), so you need to use IP addresses.

I think this is my issue, as even without putting gluetun into the mix, when I tried to replace `ES_URL=http://archivist-es:9200` and `REDIS_HOST=archivist-redis` with localhost or 127.0.0.1 it didn't work and I presume the containers will have different ip each time they're brought up which is why they use hostnames in tho docker-compose.yml. Any idea how would I go about working around this?

**Reply by qdm12** [reply]
You can set fixed IP addresses to each container.
Ideally create a docker network (i. e. `docker network create yourname --subnet 10.0.0.0/24`) and then you can set the IP address with i. e.

```yml
networks:
      yournetworkname:
        ipv4_address: 10.0.0.2
```

I tend to use a shared (with symlinks) .env file with all the IP addresses for every container as well so they all have an assigned IP, in order to fiddle with my host firewall. I use in example `ipv4_address: ${MYAPPNAME}` in docker-compose.yml so all my container IPs are in the same file.

**Reply by hugalafutro** [reply]
Ok ,managed to define static network and static ip for each of the containers within docker-compose.yml like this:
```
version: '3.3'

networks:
  static-net:
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
  tubearchivist:
    container_name: tubearchivist
    restart: always
    image: bbilly1/tubearchivist:latest
    networks:
      static-net:
        ipv4_address: 10.0.0.20
    ports:
      - 8543:8000
    volumes:
      - /shares/samba/private/_tube-archivist:/youtube
      - ./cache:/cache
    environment:
      - ES_URL=http://10.0.0.22:9200
      - REDIS_HOST=10.0.0.21
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_USERNAME=${TA_NAME}
      - TA_PASSWORD=${TA_PASS}
      - ELASTIC_PASSWORD=${ES_PASS}
      - TZ=${TIMEZONE}
    depends_on:
      - archivist-es
      - archivist-redis

  archivist-redis:
    image: redislabs/rejson:latest
    container_name: archivist-redis
    restart: always
    networks:
      static-net:
        ipv4_address: 10.0.0.21
    expose:
      - "6379"
    volumes:
      - ./redis:/data
    depends_on:
      - archivist-es

  archivist-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: archivist-es
    restart: always
    environment:
      - "xpack.security.enabled=true"
      - "ELASTIC_PASSWORD=${ES_PASS}"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es:/usr/share/elasticsearch/data
    networks:
      static-net:
        ipv4_address: 10.0.0.22
    expose:
      - "9200"
```
Stack comes up and each container can talk to each other on the assigned ip.
Still not having any luck routing the tubearchivist container's traffic via vpn though.

I added `    network_mode: "container:vpn_gluetun_vm-docker"` to each container and commented out the ports which are exposed in gluetun container.

Bringing the stack up like this, tubearchivist can't speak to archivist-es. Running `docker inspect archivist-es` claims it has the assigned ip of 10.0.0.22, but looking at elasticsearch logs it listens on 10.64.240.32:9200.

I tried to "cheat" it by changing the network to 10.0.0.0/8 and change the ips to 10.64.240.30-32, but still no go.

Where does the 10.64.240.32 come from?

**Reply by qdm12** [reply]
It might have multiple network interfaces? You can check by exec in the container and run `ip link`?

Can't you change the server listening address for that container? Or make it listen on all interfaces (`:9200`)?

**Reply by hugalafutro** [reply]
Quite busy at work atm, prob won't have time to play around with this until weekend. I think I might end up giving up on it though as networking that happens outside 192.168.x.x scares me and I basically just copy paste stuff from manuals I don't really understand.

The elasticsearch container in logs claim it's listening on 0.0.0.0:9200 and (either 10.0.0.22:9200 if not going thru gluetun or 10.64.240.32:9200 with gluetun), but configuring elasticsearch is alas absolutely beyond me as I don't even understand what it does that well and this particular container only mounts the actual data, not it's config.

I had this issue ever since I started using gluetun though; basically I've been unable to connect via vpn with stacks that run containers that talk to each other on anything else else than localhost, or more precisely stack with interdependent containers that absolutely won't work if the other container is not reachable (my monster stack from other posts only works, because this is not the case there, bazarr will still work if sonarr and radarr is unreachable etc).

All I really need is a working example of such stack regardless of its function, as I'm much better at learning from working example than doing the ol' rtfm. You wouldn't happen to have one laying around I guess.

I know I could just probably make the whole vm use the vpn, but I'd really like to have it isolated in stacks.

**Reply by zero-thermo** [reply]
Hello. Did you ever figure out a solution?

I am also trying to put TubeArchivist behind a Gluetun VPN, and am also having trouble getting containers to talk to each other.

**Reply by hugalafutro** [reply]
@zero-thermo Nope, I ended up creating a "vpn" vm where the whole machine is routed via mullvad and run my "arr matey" stacks there.

**Reply by zero-thermo** [reply]
Played around with this, and think I figured out how to get TubeArchivist working with Gluetun. This works with each in a separate docker-compose.yaml file. In case it helps anyone else:

You can use `localhost` to access the Elasticsearch and Redis containers instead of manually assigning an IP. `ES_URL=http://localhost:9200`  
`REDIS_HOST=localhost`  

Add `network_mode: container:gluetun` to all three TubeArchivist services.  

Remove the `expose` ports from the Elasticsearch and Redis services to allow for `network_mode` to be used.  

Assign `TA_PORT` to something other than `8000` to avoid any nginx bind problems.

**Reply by nikiforos6** [reply]
@zero-thermo I tried your solution and all containers seem to be running fine. However I am not able to connect to the webui. I am getting a `Bad Request (400)` error. Do you have any ideas what I can do?

**Reply by calscoo** [reply]
# TubeArchivist & services successfully running behind GlueTun
I was struggling with this for a while and finally got tubearchivist and all it's services operational behind gluetun.

Two main things you gotta do.
1. use [this](https://github.com/tubearchivist/tubearchivist/issues/614#issuecomment-1837483290) browser extension to fetch a cookie from YT and import it into tubearchivist. This is necessary to trick youtube into thinking the VPN node downloading your content is a person using a legit youtube client. I have no clue how long this cookie is valid for/how often you have to use the client device with the chrome extension to update the cookie on your server.
2. change the following docker networking settings
## gluetun
```
...
    ports:
      - "7000:7000" <-- avoid port 8000 here
...
```
## tubearchivist
```
...
    network_mode: "service:gluetun"
    environment:
      - "ES_URL=http://localhost:9200"
      - "REDIS_HOST=localhost"
      - "TA_PORT=7000" <--------------------------------------------- avoid port 8000 here
      - "TA_UWSGI_PORT=8090" <--------------------------------------- avoid port 8080 here
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/health"] <-- update healthcheck to match selected port
...
```
..also remove the `ports:` section (moved ports to gluetun)
## archivist-redis & archivist-es
```
...
    network_mode: "service:gluetun"
...
```
..also remove the `expose:` section (not needed when on same gluetun network)

## full yaml
```
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - "NET_ADMIN"
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "7000:7000"
    volumes:
      - "{{ docker_services_config_dir }}/gluetun:/gluetun"
    environment:
      - "VPN_SERVICE_PROVIDER=private internet access"
      - "VPN_TYPE=openvpn"
      - "OPENVPN_USER={{ pia_user }}"
      - "OPENVPN_PASSWORD={{ pia_password }}"
      - "TZ={{ container_timezone }}"
  tubearchivist:
    image: bbilly1/tubearchivist
    container_name: tubearchivist
    network_mode: "service:gluetun"
    environment:
      - "ES_URL=http://localhost:9200"
      - "REDIS_HOST=localhost"
      - "HOST_UID={{ container_user }}"
      - "HOST_GID={{ container_group }}"
      - "TA_HOST={{ host_lan_ip }}"
      - "TA_USERNAME={{ container_ui_user }}"
      - "TA_PASSWORD={{ admin_pass }}"
      - "TA_PORT=7000"
      - "TA_UWSGI_PORT=8090"
      - "ELASTIC_PASSWORD={{ admin_pass }}"
      - "TZ={{ container_timezone }}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-es
      - archivist-redis
    volumes:
      - "{{ docker_services_config_dir }}/tubearchivist/media:/youtube"
      - "{{ docker_services_config_dir }}/tubearchivist/cache:/cache"
  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    network_mode: "service:gluetun"
    depends_on:
      - archivist-es
    volumes:
      - "{{ docker_services_config_dir }}/archivist-redis:/data"
  archivist-es:
    image: bbilly1/tubearchivist-es
    container_name: archivist-es
    network_mode: "service:gluetun"
    environment:
      - "ELASTIC_PASSWORD={{ admin_pass }}"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "{{ docker_services_config_dir }}/archivist-es:/usr/share/elasticsearch/data"
 ```
