### DISCUSSION TITLE
Help routing traffic of another container through Gluetun while exposing the container's web-ui with Traefik

### DISCUSSION THREAD

**Discussion by ghost** [qdm12/gluetun#815] [Q&A]
Hello,

I have been trying to get a container to route its traffic through the gluetun container while exposing a single port for the web-ui to Traefik.

I have other services in my docker-compose.yml that are not routed through the gluetun container, and they work fine. I also have Authelia working, if that matters.

Two people have apparently found solutions [here](https://github.com/qdm12/gluetun/discussions/647) and [here](https://github.com/qdm12/gluetun/issues/281), but I cannot seem to get those to work despite (as far as I can tell) copying the solution exactly. Please note my configs below and see if we can get to the bottom of this for me and others!

```yaml
version: "3.9"

networks:
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  default:
    driver: bridge

secrets:
  <REDACTED>
services:

  # Gluetun
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    depends_on:
      - traefik
    environment:
      VPNSP: mullvad
      VPN_TYPE: wireguard
      WIREGUARD_ADDRESS: 10.64.100.135/32
      CITY: Madrid
      WIREGUARD_PRIVATE_KEY: <REDACTED>
      DOT: "on"
      DOT_PROVIDERS: quad9
      DOT_CACHING: enabled
      TZ: $TZk
      FIREWALL_OUTBOUND_SUBNETS: 192.168.90.0/24
    networks:
       t2_proxy:
        ipv4_address: 192.168.90.100
       default:    
    extra_hosts:
      - "example.example.com:192.168.90.254"
    expose:
      - XXX/tcp # example
      - 8000/tcp # Control panel
    volumes: 
      - $DOCKERDIR/appdata/gluetun:/gluetun
    labels:      
      - "traefik.enable=true"
      # Gluetun Built-in HTTP control server
      ## HTTP Routers
      - "traefik.http.routers.gluetun-rtr.entrypoints=https"
      - "traefik.http.routers.gluetun-rtr.rule=Host(`gluetun.$DOMAINNAME0`)"
      ## Middlewares
      - "traefik.http.routers.gluetun-rtr.middlewares=chain-auth@file"
      ## HTTP Services
      - "traefik.http.routers.gluetun-rtr.service=gluetun-svc"
      - "traefik.http.services.gluetun-svc.loadbalancer.server.port=8000"

      ###### example
      ## HTTP Routers
      - "traefik.http.routers.example-rtr.entrypoints=https"
      - "traefik.http.routers.example-rtr.rule=Host(`example.$DOMAINNAME0`)"
      ## Middlewares
      - "traefik.http.routers.example-rtr.middlewares=chain-auth@file"
      ## HTTP Services
      - "traefik.http.routers.example-rtr.service=example-svc"
      - "traefik.http.services.example-svc.loadbalancer.server.port=80"

  # Traefik 2 - Reverse Proxy
  traefik:
    container_name: traefik
    image: traefik:v2.5
    restart: always
    command:
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=false
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
      - --entrypoints.https.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22
      - --entryPoints.traefik.address=:8080
      - --api=true
      - --api.dashboard=true
      - --log=true
      - --log.level=debug
      - --accessLog=true
      - --accessLog.filePath=/traefik.log
      - --accessLog.bufferingSize=100
      - --accessLog.filters.statusCodes=400-499
      - --providers.docker=true
      - --providers.docker.endpoint=tcp://socket-proxy:2375
      - --providers.docker.exposedByDefault=false
      - --entrypoints.https.http.middlewares=chain-auth@file
      - --entrypoints.https.http.tls.options=tls-opts@file
      - --entrypoints.https.http.tls.certresolver=dns-cloudflare
      - --entrypoints.https.http.tls.domains[0].main=$DOMAINNAME0
      - --entrypoints.https.http.tls.domains[0].sans=*.$DOMAINNAME0
      - --providers.docker.network=t2_proxy
      - --providers.docker.swarmMode=false
      - --providers.file.directory=/rules
      - --providers.file.watch=true
      - --certificatesResolvers.dns-cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesResolvers.dns-cloudflare.acme.email=$CLOUDFLARE_EMAIL
      - --certificatesResolvers.dns-cloudflare.acme.storage=/acme.json
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.delayBeforeCheck=90 
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.254
      socket_proxy:
    security_opt:
      - no-new-privileges:true
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - $DOCKERDIR/appdata/traefik2/rules:/rules
      - $DOCKERDIR/appdata/traefik2/acme/acme.json:/acme.json
      - $DOCKERDIR/appdata/traefik2/traefik.log:/traefik.log
    environment:
      - CF_API_EMAIL_FILE=/run/secrets/cloudflare_email
      - CF_API_KEY_FILE=/run/secrets/cloudflare_api_key
    secrets:
      - cloudflare_email
      - cloudflare_api_key
      - htpasswd
    labels:
      - "autoheal=true"
      - "traefik.enable=true"
      # HTTP-to-HTTPS Redirect
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # HTTP Routers
      - "traefik.http.routers.traefik-rtr.entrypoints=https"
      - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.$DOMAINNAME0`)"
      ## Services - API
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      ## Middlewares
      - "traefik.http.routers.traefik-rtr.middlewares=chain-auth@file"

  example:
    container_name: example
    image: example/example
    network_mode: "service:gluetun"
    depends_on: 
      - gluetun
    # networks:
    #   - t2_proxy
    # ports:
    #   - "$example_PORT:80"

```

Thank you!
