### DISCUSSION TITLE
Cannot connect from containers that are behind Gluetun to containers that are not behind gluetun

### DISCUSSION THREAD

**Discussion by ghost** [qdm12/gluetun#891] [Q&A]
I have the following setup:
```
version: "3.8"

services:

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: Sonarr-Compose
    depends_on:
      - prowlarr
    env_file: environment.env
    networks:
      - MediaNet
    volumes:
     - blah
    ports:
      - 8989:8989
    restart: unless-stopped
    
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    env_file: environment.env
    container_name: Prowlarr-Compose
    depends_on:
      - gluetunserve  # I realise this should be unnecessary, but I was getting some issues without it.
    volumes:
      - blah
    network_mode: service:gluetunserve
    restart: unless-stopped

  gluetunserve:
    image: qmcgaw/gluetun
    container_name: Gluetun-Compose
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    env_file: environment.env
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 9696:9696/tcp # prowlarr
    restart: unless-stopped
    volumes:
      - /share/DockerCompose/VPNCompose/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=pia
      - VPN_TYPE=openvpn
      - SERVER_HOSTNAMES=#######
      # OpenVPN:
      - OPENVPN_USER==#######
      - OPENVPN_PASSWORD==#######
    networks:
      - MediaNet

networks:
  MediaNet:
    name: MediaNet
```
Prior to putting Prowlarr behind gluetun, I could connect between services using, e.g., ```http://sonarr:8989``` or ```http://prowlarr:9696```.  I understand this is because the containers are on the same docker network so you can do this clever DNS resolving

Now that I have prowlarr using gluetun's network as per my docker-compose, I can still connect to prowlarr from sonarr using ```http://gluetunserve:9696```, however I cannot connect in reverse, prowlarr cannot access sonarr on ```http://sonarr:8989``` or ```http://localhost:8989```, ```http://127.0.0.1:8989``` or ```http://my.actual.device.ip:8989```.  I get the error meessage in prowlarr ```Unknown exception: DNS Name Resolution Failure: 'delugevpn'```.  For obvious reasons, I believe this to be an internal DNS issue, but unfortunately, I cannot figure out how to solve it, despite looking at the [DNS page here](https://github.com/qdm12/gluetun/wiki/DNS-options).

The gluetun instance is working OK, as if I connect to the gluetun or prowlarr consoles I get the remote IP address of my VPN.

The issue occurs when FIREWALL environment variable is not set, or when it is set to ```off```.

I would appreciate any help you can offer. 

PS - It goes without saying that I am very grateful for the time you put in to this. :-)
