### DISCUSSION TITLE
Healthchecks don't appear to run. Container remains healthy and idle when the tunnel breaks.

### DISCUSSION THREAD

**Discussion by Steve-Brule** [qdm12/gluetun#900] [Q&A] [answered]
Hello. When internet is reset for the host machine, gluetun does not fix the openvpn tunnel, requiring manual intervention to fix it when I notice it's broken. I've tried a few things out already (removing user mapping and the OPENVPN_PROCESS_USER variable to use the defaults, thinking it's something about the container or vpn process user as per this thread: https://github.com/qdm12/gluetun/discussions/613).

I have tried different domains for the HEALTH_ADDRESS_TO_PING variable, including simply 1.1.1.1 to rule out DNS weirdness. Healthchecks simply seem not to happen at all once the container starts. There's one "2022/03/20 15:59:47 INFO healthcheck: healthy!" entry just after the container starts and after that it's silent. The tunnel keeps working until the host's internet gets reset for the first time. Here's my docker-compose for this container:

```yml
version: "3"
services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - BLOCK_ADS=off
      - BLOCK_MALICIOUS=off
      - BLOCK_SURVEILLANCE=off
      - DNS_KEEP_NAMESERVER=on
      - DNS_UPDATE_PERIOD=0
      - DOT=off
      - DOT_CACHING=off
      - DOT_IPV6=off
      - DOT_PROVIDERS=quad9
      - DOT_VALIDATION_LOGLEVEL=0
      - DOT_VERBOSITY=1
      - DOT_VERBOSITY_DETAILS=0
      - FIREWALL=on
      - FIREWALL_DEBUG=off
      - FIREWALL_INPUT_PORTS=5001,8888,9091
      - FIREWALL_VPN_INPUT_PORTS=XXXXX,XXXXX
      - HEALTH_ADDRESS_TO_PING=debian.org
      - HEALTH_VPN_DURATION_ADDITION=5s
      - HEALTH_VPN_DURATION_INITIAL=10s
      - HTTPPROXY=on
      - HTTPPROXY_LISTENING_ADDRESS=:8888
      - HTTPPROXY_LOG=off
      - HTTPPROXY_STEALTH=on
      - HTTP_CONTROL_SERVER_ADDRESS=:8000
      - HTTP_CONTROL_SERVER_LOG=on
      - ISP=31173
      - OPENVPN_IPV6=on
      - OPENVPN_MSSFIX=0
      - OPENVPN_PROCESS_USER=nonrootuser
      - OPENVPN_PROTOCOL=udp
      - OPENVPN_USER=XXXXX
      - OPENVPN_VERBOSITY=1
      - OPENVPN_VERSION=2.5
      - OWNED_ONLY=yes
      - PGID=987
      - PUBLICIP_PERIOD=12h
      - PUID=994
      - SERVER_CITIES=gothenburg
      - SERVER_COUNTRIES=sweden
      - SERVER_HOSTNAMES=se-got-001,se-got-002,se-got-003,se-got-004,se-got-005,se-got-006,se-got-007,se-got-008,se-got-009,se-got-010,se-got-011,se-got-012
      - SHADOWSOCKS=on
      - SHADOWSOCKS_ADDRESS=:8388
      - SHADOWSOCKS_CIPHER=chacha20-ietf-poly1305
      - SHADOWSOCKS_LOG=off
      - SHADOWSOCKS_PASSWORD=XXXXX
      - TZ=Europe/Moscow
      - UPDATER_PERIOD=24h
      - UPDATER_VPN_SERVICE_PROVIDERS=mullvad
      - VERSION_INFORMATION=on
      - VPN_ENDPOINT_PORT=53
      - VPN_INTERFACE=tun0
      - VPN_SERVICE_PROVIDER=mullvad
    networks:
      - gluetun
    ports:
      - 127.0.0.1:8000:8000/tcp
      - 127.0.0.1:8888:8888/tcp
      - 8388:8388/tcp
      - 8388:8388/udp
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - /media/mainstor/dockerdata/gluetun:/gluetun
networks:
  gluetun:
    name: gluetun
```
