### DISCUSSION TITLE
Having trouble with Mullvad port forwarding

### DISCUSSION THREAD

**Discussion by nathan-manzano** [qdm12/gluetun#901] [Q&A] [answered]
Hi all I have been trying to setup the use of Mullvad port forwarding so I can access my Plex server from anywhere. I am in a NAT so Mullvad port forwarding is my best bet and I have confirmed it working with my QNAP using QTS but I am now using Unraid with the same hardware and cannot get this to work.

Here is my config:
```yml
version: '3'
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER=<USERID>
      - OPENVPN_PASSWORD=<USERID>
      - SERVER_HOSTNAMES=us-dal-101,us-dal-102,us-dal-103,us-dal-104,us-dal-105,us-dal-201,us-dal-202,us-dal-203,us-dal-204
      - FIREWALL_VPN_INPUT_PORTS=<PORT>
    ports:
      - 32400:32400/tcp
      
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - PLEX_UID=0
      - PLEX_GID=0
      - TZ=America/Chicago
      - PLEX_CLAIM=<CLAIMCODE>
    network_mode: "service:gluetun"
    volumes:
      - /mnt/user/appdata/Plex:/config
      - /mnt/user/plex/transcode>:/transcode
      - /mnt/user/plex/data:/data
```
      
I have verified using ``docker run --rm --network=container:gluetun alpine:3.14 sh -c "apk add wget && wget -qO- https://ipinfo.io"`` that gluetun is connected to mullvad but I cannot connect to myip:forwardedport so it does not seem like it is working properly. I also have plex setup to manually use the forwarded port but as I said I cannot connect to it so it is not working.

Any help is appreciated!
