### DISCUSSION TITLE
Not sure if I've setup my compose file correctly for Mullvad

### DISCUSSION THREAD

**Discussion by ghost** [qdm12/gluetun#909] [Q&A] [answered]
Hi everyone,

I already have a normal Qbit install on my server but wanted one combined with a VPN so I'm trying to acheive that using Docker and Gluetun.

My Docker experience is quite limited but It seems to be working so far and there's no IP leaks or anything (binded the wg0 interface and the optional IP to Qbit succesfully) however the speeds are a bit slow (10 - 25% of my 1Gbps connection). Here's what I have for my Gluetun compose file so far and was hoping that I could get some pointers on if I'm doing anything wrong.

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      # - 8888:8888/tcp # HTTP proxy
      # - 8388:8388/tcp # Shadowsocks
      # - 8388:8388/udp # Shadowsocks
      # Below I've used 18139 on the host as it was a random, unused port and I didn't want any of the torrent
      # traffic from this Qbit + VPN instance interferring with the torrent traffic that's coming from my
      # regular Qbit installation or just generally clashing with any other services on my system.
      #
      # I've then used 26953 as the ports for my Qbit Web UI, done how the Linuxserver page for Qbit
      # recommends to do it
      - 18139:6881
      - 18139:6881/udp
      - 26953:26953 
    volumes:
      - /home/me/.docker/vpn/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_INTERFACE=wg0

      - WIREGUARD_ENDPOINT_PORT=57538 # Am a bit confusd here, explained below
      - WIREGUARD_PRIVATE_KEY=wireguard-key
      - WIREGUARD_ADDRESSES=wireguard-address
      - SERVER_CITIES=a-city

      - TZ=Europe/a-city
```

Is there anything I should be editing here?

Also for `57538`, that's the port I got when I went to the `Mullvad account panel` -> `Wireguard and port forwarding` and got a port for a city. However I'm confused as I'm not sure which environment variable I should be having here. Should it be `VPN_ENDPOINT_PORT` or `FIREWALL_VPN_INPUT_PORTS` (which is what the wiki says). They both seem quite similar.

Any clarification or help about any of this would be really appreciated. Thank you!
