### DISCUSSION TITLE
Seems that I cannot expose transmission.example.local when using gluetun and Traefik

### DISCUSSION THREAD

**Discussion by ArneAnka** [qdm12/gluetun#916] [Q&A]
Hi!

Im trying to evolve my current docker configuration and use Traefik as a reversed proxy for containers that has an interface. But I having trouble to reach `Transmission` on `transmission.$DOMAINNAME` (in my case `transmission.example.local`). In the browser I get a `Gateway timed out` error, and Traefik doesn't seem to report any problems (I can see transmission in Traefik dashboard).

And when I connect to transmission container though `portainer` and do an `curl ifconfig.co`, I seem to receive an IP address from mullvad.

I don't know what im doing wrong and having a hard time troubleshoot.

Can it be due to gluetun `- NET_ADMIN`?

```
version: "3.5"

networks:
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
  default:
    driver: bridge

# Common environment values
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# Proxy Network and Security
x-network-and-security: &network-and-security
  networks:
    - t2_proxy
  security_opt:
    - no-new-privileges:true

# Keys common to some of the services in basic-services.txt
x-common-keys-core: &common-keys-core
  <<: *network-and-security
  restart: always
  # profiles:
  # - basic

# Keys common to some of the dependent services/apps
x-common-keys-apps: &common-keys-apps
  <<: *network-and-security
  restart: unless-stopped
  # profiles:
  # - apps

# Keys common to some of the services in media-services.txt
x-common-keys-media: &common-keys-media
  <<: *network-and-security
  restart: "no"
  # profiles:
  # - media

services:

  traefik:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      # - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # - "--entryPoints.traefik.address=:8080"
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    labels:
      # HTTP Routers
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-rtr.entrypoints=web"
      - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.$DOMAINNAME`)"
      ## Services - API
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      - "traefik.http.services.traefik-svc.loadbalancer.server.port=8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - $TRANSMISSION_PORT:9091/tcp # Transmission
      - 51413:51413/tcp # Transmission
      - 51413:51413/udp # Transmission
    volumes:
      - $USERDIR/docker/gluetun:/gluetun
    environment:
      - PUID=$PUID
      - PGID=$PGID
      # See https://github.com/qdm12/gluetun/wiki
      - VPNSP=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=$WIREGUARD_KEY
      - WIREGUARD_ADDRESS=$WIREGUARD_ADDRESS
      - CITY=Gothenburg
      # Timezone for accurate log times
      - TZ=$TZ

  transmission:
    image: ghcr.io/linuxserver/transmission:latest
    container_name: transmission
    network_mode: "service:gluetun"
    environment:
      - UMASK=022
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      # - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=$TRANSMISSION_RPC_USERNAME #optional
      - PASS=$TRANSMISSION_RPC_PASSWORD #optional
      - WHITELIST=127.0.0.1,$SERVER_IP,192.168.*.*
    volumes:
      - $USERDIR/docker/transmission:/config
      - /nfs/downloads:/downloads # default download dir
      - /nfs/incomplete:/downloads/incomplete # default incomplete dir
    # ports:
      # - $TRANSMISSION_PORT:9091
      # - 51413:51413
      # - 51413:51413/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.transmission-rtr.entrypoints=web"
      - "traefik.http.routers.transmission-rtr.rule=Host(`transmission.$DOMAINNAME`)"
      ## HTTP Services
      - "traefik.http.routers.transmission-rtr.service=transmission-svc"
      - "traefik.http.services.transmission-svc.loadbalancer.server.port=9091"
```
