### DISCUSSION TITLE
Traffic is flowing from container to gluetun, but need to be able to specify connections to not gluetun service containers

### DISCUSSION THREAD

**Discussion by patrickrobbins** [qdm12/gluetun#997] [Q&A]
I have gluetun running, and my radarr setup to connect through that, but I also have jellyfin outside of gluetun.  I want radarr to be able to notify jellyfin of updates, but radarr can't reach jellyfin, and I'm not sure the best way to set that up.  I have seen some documents describing static IPs, but I would rather not set those up, I really prefer container aliases.  I tried using links, but that didn't seem to work either. I added it to radarr, as I wouldn't want all my VPN'd containers talking to jellyfin.

```yml
services:
  gluetun:
    image: qmcgaw/gluetun
    .....
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:gluetun
    links:
      - "jellyfin:jellyfin"
     ....
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    ....
```
