### ISSUE TITLE
Bug: ProtonVPN server update fails, server list is stuck very out-of-date

### ISSUE THREAD

**Issue by mtalexan** [qdm12/gluetun#1018]
### Host OS

Ubuntu 18.04

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

`docker run` for failed update
`docker-compose` for gluetun extended usage

### What is the version of Gluetun

Running version latest built on 2022-06-06T18:13:11.996Z (commit 5359257)

### What's the problem 🤔

When trying to use a number of servers ProtonVPN lists as available, gluetun was claiming they didn't exist.  It appeared the gluetun server list was very out of date, so I attempted to update it separately.  

1. Stop the running gluetun server (if applicable)
2. Remove the server.json list
3. Run the update command (see command below)
4. Get an error (see log below)
5. Bring up the docker-compose again anyway (see config below)
6. Get an error on an unrecognized server that should be found as present (see log below)

### Share your logs

VPN server update command output
```log

2022-06-07T23:46:32Z INFO creating /gluetun/servers.json with 11559 hardcoded servers
2022-06-07T23:46:32Z INFO updating Protonvpn servers...
2022-06-07T23:46:34Z WARN ignoring server is-de-01c.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-ru-01.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-ru-01.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server se-ru-01a.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-ru-02.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-ru-02.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-ru-02.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-de-04.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-de-04.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-de-04.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-de-04.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-de-04.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-de-04.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-de-04.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-de-04.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server ch-de-01a.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-hu-02.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-hu-02.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-hu-02.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-hu-02.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server is-hu-01a.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-co-02.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-co-02.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-co-02.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-co-02.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server node-co-02.protonvpn.net with status 0
2022-06-07T23:46:34Z WARN ignoring server is-co-01a.protonvpn.net with status 0
2022-06-07T23:46:34Z ERROR cannot update server information: cannot get servers: not enough servers found: 439 and expected at least 613
2022-06-07T23:46:34Z INFO Shutdown successful
```

VPN server call output
```log
Recreating gluetun ... done
Attaching to gluetun
gluetun    | ========================================
gluetun    | ========================================
gluetun    | =============== gluetun ================
gluetun    | ========================================
gluetun    | =========== Made with ❤️ by ============
gluetun    | ======= https://github.com/qdm12 =======
gluetun    | ========================================
gluetun    | ========================================
gluetun    |
gluetun    | Running version latest built on 2022-06-06T18:13:11.996Z (commit 5359257)
gluetun    |
gluetun    | 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
gluetun    | 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
gluetun    | ✨ New feature? https://github.com/qdm12/gluetun/issues/new
gluetun    | ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
gluetun    | 💻 Email? quentin.mcgaw@gmail.com
gluetun    | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
gluetun    | 2022-06-07T16:37:01-07:00 WARN You are using the old environment variable HTTPPROXY_PORT, please consider changing it to HTTPPROXY_LISTENING_ADDRESS
gluetun    | 2022-06-07T16:37:01-07:00 WARN You are using the old environment variable HTTP_CONTROL_SERVER_PORT, please consider changing it to HTTP_CONTROL_SERVER_ADDRESS
gluetun    | 2022-06-07T16:37:01-07:00 INFO [routing] default route found: interface eth0, gateway 172.10.222.1 and assigned IP 172.10.222.2
gluetun    | 2022-06-07T16:37:01-07:00 INFO [routing] local ethernet link found: eth0
gluetun    | 2022-06-07T16:37:01-07:00 INFO [routing] local ipnet found: 172.10.222.0/24
gluetun    | 2022-06-07T16:37:01-07:00 INFO [firewall] enabling...
gluetun    | 2022-06-07T16:37:01-07:00 INFO [firewall] enabled successfully
gluetun    | 2022-06-07T16:37:01-07:00 INFO [storage] merging by most recent 11559 hardcoded servers and 11559 servers read from /gluetun/servers.json
gluetun    | 2022-06-07T16:37:02-07:00 ERROR VPN settings: provider settings: server selection: the server name specified is not valid: value is not one of the possible choices: value "ng#3", choices available are AE#12, AE#17, AE#18, AE#9, AR#17, AR#20, AT#1, AT#10, AT#13, AT#14, AT#3, AT#5, AT#7, AT#9, AU#13, AU#14, AU#17, AU#18, AU#21, AU#25, AU#29, AU#32, AU#37, AU#38, AU#41, AU#42, BE#1, BE#13, BE#14, BE#2, BE#5, BE#8, BG#05, BG#7, BR#21, BR#42, BR#9, CA#1, CA#17, CA#21, CA#24, CA#29, CA#3, CA#30, CA#33, CA#35, CA#41, CA#42, CA#45, CA#46, CA#49, CA#5, CA#7, CH#10, CH#12, CH#14, CH#16, CH#18-TOR, CH#5, CH#7, CH-AE#1, CH-AR#1, CH-AT#1, CH-AU#1, CH-BE#1, CH-CA#1, CH-CY#1, CH-CZ#1, CH-DE#1, CH-DK#1, CH-EE#1, CH-ES#1, CH-FI#1, CH-FR#1, CH-GR#1, CH-HU#1, CH-IE#1, CH-IL#1, CH-IN#1, CH-IT#1, CH-JP#1, CH-LT#1, CH-LU#1, CH-LV#1, CH-MD#1, CH-MX#1, CH-MY#1, CH-NL#1, CH-NO#1, CH-NZ#1, CH-PL#1, CH-PT#1, CH-RS#1, CH-SG#1, CH-SI#1, CH-SK#1, CH-TW#1, CH-UA#1, CH-UK#1, CH-US#1, CL#17, CL#20, CO#12, CO#9, CR#1, CR#2, CY#1, CY#2, CZ#1, CZ#13, CZ#16, CZ#3, DE#102, DE#105, DE#114, DE#13, DE#16, DE#33, DE#34, DE#53-TOR, DE#54, DE#58, DE#65, DE#69, DE#7-TOR, DE#77, DE#81, DE#90, DK#1, DK#13, DK#16, DK#21, DK#22, DK#3, EE#1, EE#4, EG#1, ES#12, ES#17, ES#18, ES#21, ES#22, ES#25, ES#9, FI#1, FI#2, FI#5, FR#13-TOR, FR#21, FR#24, FR#29, FR#32, FR#37, FR#39, FR#41, FR#42, FR#45, FR#46, FR#49, FR#50, FR#53, FR#54, FR#57, FR#58, FR#61, FR#73, FR#9, GE#1, GR#1, GR#4, HK#14, HK#15, HK#18, HK#21, HK#6, HK#9, HU#1, HU#10, HU#4, HU#9, IE#1, IE#2, IE#5, IE#8, IL#10, IL#5, IL#6, IL#9, IN#1, IN#11, IN#13, IN#2, IS#1, IS#3, IS#5, IS#7, IS#9-TOR, IS-AT#1, IS-BE#1, IS-BR#2, IS-CA#1, IS-CL#1, IS-CO#1, IS-CR#1, IS-DE#1, IS-DK#1, IS-ES#1, IS-FR#1, IS-GE#1, IS-HK#1, IS-HU#1, IS-IE#1, IS-IL#1, IS-IT#1, IS-LU#1, IS-NL#1, IS-NO#1, IS-PE#1, IS-PR#1, IS-RU#1, IS-TH#1, IS-UK#1, IS-US#1, IS-ZA#1, IT#1, IT#13, IT#14, IT#3, IT#5, IT#8, JP#43, JP#45, JP#51, JP#54, JP#59, JP#69, JP-FREE#1, JP-FREE#2, JP-FREE#3, JP-FREE#4, JP-FREE#5, JP-FREE#6, JP-FREE#7, JP-FREE#8, KH#1, KR#13, LT#1, LT#4, LU#13, LU#14, LU#5, LU#8, LV#1, LV#4, MD#1, MD#4, MX#1, MX#4, MY#1, MY#4, NG#1, NL#13, NL#14, NL#17, NL#21, NL#219, NL#220, NL#223, NL#224, NL#227, NL#228, NL#25, NL#26, NL#29, NL#3, NL#32, NL#37, NL#39, NL#41, NL#45, NL#46, NL#49, NL#5, NL#53, NL#54, NL#57, NL#58, NL#69, NL#70, NL#81, NL#82, NL#85, NL-FREE#1, NL-FREE#10, NL-FREE#11, NL-FREE#12, NL-FREE#13, NL-FREE#14, NL-FREE#15, NL-FREE#16, NL-FREE#17, NL-FREE#18, NL-FREE#19, NL-FREE#2, NL-FREE#20, NL-FREE#21, NL-FREE#22, NL-FREE#23, NL-FREE#24, NL-FREE#25, NL-FREE#26, NL-FREE#27, NL-FREE#28, NL-FREE#29, NL-FREE#3, NL-FREE#30, NL-FREE#31, NL-FREE#32, NL-FREE#33, NL-FREE#34, NL-FREE#35, NL-FREE#36, NL-FREE#37, NL-FREE#38, NL-FREE#39, NL-FREE#4, NL-FREE#40, NL-FREE#41, NL-FREE#42, NL-FREE#43, NL-FREE#44, NL-FREE#45, NL-FREE#46, NL-FREE#47, NL-FREE#48, NL-FREE#49, NL-FREE#5, NL-FREE#50, NL-FREE#51, NL-FREE#52, NL-FREE#53, NL-FREE#54, NL-FREE#55, NL-FREE#56, NL-FREE#57, NL-FREE#58, NL-FREE#59, NL-FREE#6, NL-FREE#60, NL-FREE#61, NL-FREE#62, NL-FREE#63, NL-FREE#64, NL-FREE#65, NL-FREE#66, NL-FREE#67, NL-FREE#68, NL-FREE#69, NL-FREE#7, NL-FREE#70, NL-FREE#71, NL-FREE#72, NL-FREE#73, NL-FREE#74, NL-FREE#75, NL-FREE#76, NL-FREE#77, NL-FREE#78, NL-FREE#79, NL-FREE#8, NL-FREE#9, NO#1, NO#13, NO#14, NO#17, NO#18, NO#2, NO#5, NO#8, NZ#13, NZ#16, NZ#5, NZ#8, PE#17, PE#20, PH#1, PL#1, PL#13, PL#16, PL#21, PL#22, PL#3, PR#1, PT#5, PT#8, RO#16, RO#9, RS#1, RS#4, RU#1, RU#13, RU#15, RU#5, RU#8, SE#1, SE#17, SE#23, SE#3, SE#31-TOR, SE-AU#1, SE-BG#1, SE-BR#1, SE-CA#1, SE-DE#1, SE-EE#1, SE-EG#1, SE-FI#1, SE-FR#1, SE-HK#1, SE-JP#1, SE-KH#1, SE-KR#2, SE-LT#1, SE-MD#1, SE-NG#1, SE-NL#1, SE-NO#1, SE-NZ#1, SE-PH#1, SE-PT#1, SE-RO#1, SE-SG#1, SE-TR#1, SE-TW#01, SE-UK#1, SE-US#1, SE-VN#1, SG#21, SG#23, SG#29, SG#37, SG#41, SG#45, SG#48, SG#57, SG#61, SG#63, SG#65, SG#66, SG#69, SG#71, SI#1, SI#4, SK#1, SK#4, TH#1, TR#17, TR#20, TW#13, TW#16, TW#21, UA#12, UA#9, UK#17, UK#20, UK#25, UK#28, UK#33, UK#34, UK#37, UK#38, UK#41, UK#42, UK#45, UK#46, UK#53, UK#55, UK#65, US-AZ#10, US-AZ#9, US-CA#17, US-CA#20, US-CA#25, US-CA#28, US-CA#33, US-CA#36, US-CA#41, US-CA#44, US-CA#49, US-CA#50, US-CA#53, US-CA#54, US-CA#57, US-CA#58, US-CA#61, US-CA#62, US-CA#65, US-CA#66, US-CA#69, US-CA#70, US-CA#77, US-CA#79, US-CA#89, US-CO#1, US-CO#10, US-CO#13, US-CO#14, US-CO#17, US-CO#18, US-CO#21-TOR, US-CO#4, US-CO#9, US-FL#1, US-FL#12, US-FL#17, US-FL#20, US-FL#25, US-FL#28, US-FL#33, US-FL#34, US-FL#37, US-FL#38, US-FL#4, US-FL#41, US-FL#42, US-FL#45, US-FL#46, US-FL#49, US-FL#50, US-FL#9, US-FREE#1, US-FREE#10, US-FREE#11, US-FREE#12, US-FREE#13, US-FREE#14, US-FREE#15, US-FREE#16, US-FREE#17, US-FREE#18, US-FREE#19, US-FREE#2, US-FREE#20, US-FREE#21, US-FREE#22, US-FREE#23, US-FREE#24, US-FREE#25, US-FREE#26, US-FREE#27, US-FREE#28, US-FREE#29, US-FREE#3, US-FREE#30, US-FREE#31, US-FREE#32, US-FREE#33, US-FREE#34, US-FREE#36, US-FREE#37, US-FREE#38, US-FREE#39, US-FREE#4, US-FREE#40, US-FREE#41, US-FREE#42, US-FREE#43, US-FREE#44, US-FREE#45, US-FREE#46, US-FREE#47, US-FREE#48, US-FREE#5, US-FREE#6, US-FREE#7, US-FREE#8, US-FREE#9, US-GA#109, US-GA#13, US-GA#16, US-GA#21, US-GA#22, US-GA#29-TOR, US-IL#45, US-IL#49, US-IL#57, US-IL#60, US-IL#69, US-IL#70, US-NJ#11, US-NJ#9, US-NY#126, US-NY#13, US-NY#16, US-NY#21, US-NY#24, US-NY#29, US-NY#32, US-NY#37, US-NY#38, US-NY#41, US-NY#42, US-NY#45, US-NY#46, US-NY#49, US-NY#5, US-NY#50, US-NY#53, US-NY#54, US-NY#61, US-NY#65, US-NY#73, US-NY#8, US-TX#12, US-TX#17, US-TX#18, US-TX#21, US-TX#22, US-TX#25, US-TX#26, US-TX#29, US-TX#30, US-TX#9, US-UT#25, US-UT#26, US-UT#29, US-UT#30, US-UT#34, US-VA#14, US-VA#17, US-VA#26, US-VA#28, US-WA#21, US-WA#34, VN#1, ZA#13, ZA#16
gluetun    | 2022-06-07T16:37:02-07:00 INFO Shutdown successful
```

### Share your configuration

VPN Server list update command
```shell
docker run -it --rm -v /docker/new-media-stack/vpn/gluetun/config:/gluetun qmcgaw/gluetun update -enduser -providers protonvpn
```

Or the actual VPN container making use of the list (docker-compose.yml)
```yml
version: '3.1'

services:
  gluetun:
    image:  qmcgaw/gluetun:latest
    container_name: 'gluetun'
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - SERVER_NAMES=NG#1,NG#3,NG#4,NG#5,RO#9,RO#10,RO#11,RO#12,RO#13,RO#14,RO#15,SG#29,SG#30,SG#31,SG#32,SG#33,SG#34,SG#35,SG#36,SG#41,SG#42,SG#43,SG#44,HU#5,HU#6,HU#7,HU#8,CZ#3,CZ#4,SE#3,UK#34,UK#35,UK#36,US-CA#20,US-CA#21,US-CA#22,US-CA#24,US-CA#28,US-CA#29,US-CA#30,US-CA#31,US-CA#32,US-CA#45,US-CA#47,US-CA#48,US-CA#50,US-CA#52,US-CA#34,US-CA#55,US-CA#56,US-CA#58,US-CA#59,US-CA#60,US-CA#62,US-CA#64,US-CA#66,US-CA#67,US-CA#68,US-CA#70,US-CA#71,US-CA#72,US-FL#5,US-FL#6,US-FL#8,US-FL#13,US-FL#14,US-FL#15,US-FL#16,US-FL#21,US-FL#23,US-FL#24,US-FL#29,US-FL#30,US-FL#31,US-FL#34,US-FL#35,US-FL#36,US-FL#38,US-FL#39,US-FL#40,US-FL#42,US-FL#43,US-FL#44,US-FL#46,US-FL#47,US-Fl#48,US-FL#50,US-FL#51,US-FL#52,US-TX#30,US-TX#31,US-TX#32,US-TX#33,US-TX#34,US-TX#35,US-TX#36,US-TX#37,US-TX#38,US-TX#39,US-TX#40,US-NY#17,US-NY#18,US-NY#19,US-NY#20,US-NY#25,US-NY#26,US-NY#27,US-NY#28,US-NY#33,US-NY#36,US-NY#38,US-NY#40,US-NY#42,US-NY#43,US-NY#44,US-NY#48,US-NY#50,US-NY#51,US-NY#52,US-NY#55,US-NY#56,US-NY#73,US-NY#75,US-NY#76,US-NY#77,US-NY#78,US-NY#79,US-NY#80,US-NY#81,US-NY#82,US-NY#84
      - OPENVPN_USER=myuser
      - OPENVPN_PASSWORD=mypassword
      - OPENVPN_PROTOCOL=udp
      - DOT_PROVIDERS=quad9
      - BLOCK_MALICIOUS=off
      # Disabled by default, turn on for testing VPN
      - HTTPPROXY=on
      - HTTPPROXY_PORT=8119
      # can't be turned off for some reason
      - HTTP_CONTROL_SERVER_PORT=11000
      - PUID=1000
      - GUID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /docker/new-media-stack/vpn/gluetun/config:/gluetun
    ports:
      # Proxy port, outside must match inside
      - "8119:8119"
    networks:
      - public-network
    security_opt:
      - no-new-privileges
    restart: unless-stopped

networks:
  public-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.222.0/24
```

EDIT: Fixed generated code blocks to handle multiple command and log blocks
