### ISSUE TITLE
Bug: protonvpn free servers are not working

### ISSUE THREAD

**Issue by howTOdoIT2** [qdm12/gluetun#1036]
### Is this urgent?

Yes

### Host OS

debian 11

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

gluetun-3.29.0

### What's the problem 🤔

when  FREE_ONLY=on    return failed finding a valid server,
this is because protonVPN change the free server name to  nl-free-01.protonvpn.net  and  on  servers.json list the free servers have the format "node-nl-01.protonvpn.net"
Or maybe not  but is not working for protonVPN free servers

### Share your logs

```plain text
failed finding a valid server connection: cannot filter servers: no server found: for VPN openvpn; protocol udp; free tier only
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    # container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /yourpath:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=xxxx
      - OPENVPN_PASSWORD=xxxx
    - SERVER_COUNTRIES=Netherlands
      - FREE_ONLY=on
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      # - WIREGUARD_ADDRESSES=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=
```
