### ISSUE TITLE
Bug: PIA port forwarded file is always created with root permissions

### ISSUE THREAD

**Issue by Just8Will** [qdm12/gluetun#1044]
### Is this urgent?

No

### Host OS

Arch

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-06-24T23:13:35.383Z (commit 535297d)

### What's the problem 🤔

The environment variables PUID and GUID do not affect the user id and gid of the forwarded port file produced by gluetun.
I have tried using them as PUID and PGID as documented in the wiki as well as trying to use UID and GID as environment variables.
Whatever I do the file is always created with root uid and gid.

I do get the line:
[openvpn] UID set to nonrootuser
in my logs but I don't know if that is related to this issue.

All the prot forwarding is working correctly it just the the forwarded_port file is root which makes it very difficult to read with other programs which i might not want to have root access.

This is a recurrence of issue 111 but that was before this feature was implemented. This is that feature breaking.

### Share your logs

```plain text
excerpts from the logs

├── OS Alpine settings:
|   ├── Process UID: 1000
|   ├── Process GID: 973
|   └── Timezone: Europe/London
├── Public IP settings:
|   ├── Fetching: every 12h0m0s
|   └── IP file path: /tmp/gluetun/ip
└── Version settings:
    └── Enabled: yes
~~~~
[openvpn] UID set to nonrootuser
~~~~
[port forwarding] writing port file /gluetun/forwarded_port
```

### Share your configuration

```yml
gluetun:
    image: qmcgaw/gluetun:latest
    container_name: deluge
    networks:
      media:
        ipv4_address: 172.20.4.100
      public:
        ipv4_address: 172.16.0.100
    privileged: true
    cap_add:
      - NET_ADMIN
    ports:
~~~~~~~~~~
    environment:
      - PUID=$ADMIN_UID
      - PGID=$DOCKER_GID
         - TZ=Europe/London
      - SERVER_REGIONS=Switzerland
      - PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING=on
      - PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING_STATUS_FILE=/gluetun/forwarded_port
      - FIREWALL_OUTBOUND_SUBNETS=172.20.4.0/24
      - DNS_KEEP_NAMESERVER=on
    volumes:
      - $CONFIG_DIR/gluetun-pia:/gluetun:rw
    restart: always
```
