### ISSUE TITLE
Bug: ERROR no iptables supported found: from iptables, iptables-nft: last error is: iptables: Failed to initialize nft: Protocol not supported (exit status 1)

### ISSUE THREAD

**Issue by Macmee** [qdm12/gluetun#1062]
### Is this urgent?

Yes

### Host OS

MacOS

### CPU arch

x86_64

### VPN service provider

TorGuard

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-07-04T00:42:53.696Z (commit a4c80b3)

### What's the problem 🤔

The container crashes with TorGuard now using this error: 

> iptables-nft: last error is: iptables: Failed to initialize nft: Protocol not supported (exit status 1)

The same config worked a few months ago

### Share your logs

```plain text
scrapers-vpn3-1          | Running version latest built on 2022-07-04T00:42:53.696Z (commit a4c80b3)
scrapers-vpn3-1          |
scrapers-vpn3-1          | 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
scrapers-vpn3-1          | 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
scrapers-vpn3-1          | ✨ New feature? https://github.com/qdm12/gluetun/issues/new
scrapers-vpn3-1          | ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
scrapers-vpn3-1          | 💻 Email? quentin.mcgaw@gmail.com
scrapers-vpn3-1          | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
scrapers-vpn3-1          | 2022-07-13T19:55:16Z INFO [routing] default route found: interface eth0, gateway 172.18.0.1 and assigned IP 172.18.0.2
scrapers-vpn3-1          | 2022-07-13T19:55:16Z INFO [routing] local ethernet link found: eth0
scrapers-vpn3-1          | 2022-07-13T19:55:16Z INFO [routing] local ipnet found: 172.18.0.0/16
scrapers-coordinator3-1  | [Wed Jul 13 19:55:16 2022] PHP 7.4.30 Development Server (http://0.0.0.0:80) started
scrapers-vpn3-1          | 2022-07-13T19:55:16Z ERROR no iptables supported found: from iptables, iptables-nft: last error is: iptables: Failed to initialize nft: Protocol not supported (exit status 1)
scrapers-vpn3-1          | 2022-07-13T19:55:16Z INFO Shutdown successful
scrapers-vpn3-1 exited with code 1
```

### Share your configuration

```yml
vpn3:
    image: qmcgaw/gluetun
    environment:
      HTTPPROXY: "on"
      VPN_SERVICE_PROVIDER: "custom"
      VPN_TYPE: "openvpn"
      OPENVPN_CUSTOM_CONFIG: "/vpn.conf"
      OPENVPN_USER: "YYYYYY"
      OPENVPN_PASSWORD: "XXXXX"
    volumes:
      - ./vpns/3.ovpn:/vpn.conf:rw
    ports:
      - 5803:5800
      - 8888:8888
    cap_add:
      - NET_ADMIN
```
