### ISSUE TITLE
OPENVPN: Unable to Reach services via URL 

### ISSUE THREAD

**Issue by xkoldxx** [qdm12/gluetun#1064]
I have Gluetun running on a mac vlan and a number of services running behind it, i also have other macvlans for non vpn'd services the issue im facing is i can not access the services behind gluetun via nginx reverse proxy manager but i can reach then via there IP address - i recently migrated from bubuntux/nordlynx and i was able to access them no issues 

```
- name: Create Gluetun Container
  community.general.docker_container:
    name: gluetun
    hostname: gluetun
    image: 'qmcgaw/gluetun'
    pull: yes
    state: started
    container_default_behavior: compatibility
    restart_policy: unless-stopped
    privileged: true
    env:
      VPN_TYPE: 'openvpn'
      TZ: '{{ default_timezone }}'
      FIREWALL_OUTBOUND_SUBNETS: '10.10.0.0/16'
      VPN_SERVICE_PROVIDER: 'torguard'
      SERVER_HOSTNAMES: 'location
      OPENVPN_USER: 'email@.emailcom'
      OPENVPN_PASSWORD: 'hththththt'
      OPENVPN_PROTOCOL: 'udp'
      OPENVPN_AUTH: 'sha256'
      OPENVPN_CIPHER: 'aes-128-cbc'
      DOT: 'off'
      DNS_KEEP_NAMESERVER: 'on'
    volumes:
      - '{{ project_directory }}/gluetun/vpnconfig.conf:/gluetun/config.conf:ro'
    devices:
      - /dev/net/tun
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    recreate: yes
    networks_cli_compatible: yes
    networks:
      - name: int3
        ipv4_address: x.x.x.x
  tags: gluetun
```
