### ISSUE TITLE
Bug: Openvpn host URL not resolved (using custom provider)

### ISSUE THREAD

**Issue by sa6kad** [qdm12/gluetun#1094]
### Host OS

Debian, Ubuntu

### CPU arch

x86_64

### VPN service provider

Custom

### What are you using to run the container

docker-compose

### What is the version of Gluetun

latest

### What's the problem 🤔

First of all, thanks for a cool container!

I am using custom provider in order to connect to Ivacy VPN. Conf .conf files usually containd URLs of the VPN servers. 

I tried to nslookup the IP address and substitute the URL and everything seem to work. 
Other containers, such as dperson's do not have this issue. 

### Share your logs

```plain text
` 2022-08-04T09:53:14Z ERROR VPN settings: OpenVPN settings: custom configuration file: failed extracting information from custom configuration file: cannot extract connection from file: on line 4: failed extracting from remote line: host is not an an IP address: pl2-auto-udp.ptoserver.com`
```

### Share your configuration

```yml
---
version: "3"

networks:
  infra_out:
    driver: bridge
    external: true

services:
  vpn_gw_ru:
    image: qmcgaw/gluetun
    container_name: vpn_gw
    cap_add:
      - NET_ADMIN
    volumes:
      - ~/docker_volumes/vpn_gw/client.conf:/gluetun/custom.conf:ro
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
      - OPENVPN_USER=myusername
      - OPENVPN_PASSWORD=mypass
    networks:
      infra_out
```
