### ISSUE TITLE
TLS Handshake issues

### ISSUE THREAD

**Issue by alphadijkstra** [qdm12/gluetun#110]
**1. What's your OS?**
QNAP NAS Linux Version 4.4.1.1216
System: QNAP TS-453 Pro
QNAP software: Container Station

**2. What's the version of the program (see at the top of logs)?**
Latest build version from: 2020/03/27 01:46:52
OpenVPN version: 2.4.7                                                                                                              
Unbound version: 1.9.1                                                                                                              
Iptables version: v1.8.3                                                                                                            
TinyProxy version: 1.10.0                                                                                                           
ShadowSocks version: 3.3.1

**3. How are you running the container? (i.e Docker, Docker Compose, Docker Swarm, Kubernetes, etc.)**
Docker Compose

**4. What's wrong? (please share some of your logs, and maybe configuration)**
My docker compose is set up to have containers route their traffic via the VPN.
It works fine but I keep getting errors and information logs about the NZBGet container having TLS handshake issues.
_**Things I tried:**_
When I run this container without routing traffic through the VPN container, no error or warning messages are seen in logging.
When running NZBGet and the PIA VPN client in a virtual machine, none of these issues are seen as well.

My Docker compose:
```
version: '3'

services:
  pia:
    image: qmcgaw/private-internet-access:latest
    container_name: pia
    cap_add: 
    - NET_ADMIN
    restart: always
    dns: 
    - 209.222.18.222
    - 209.222.18.218
    environment:
    - REGION=Netherlands
    - USER=myuser
    - PASSWORD=mypassword
    - PORT_FORWARDING=on
    - PIA_ENCRYPTION=normal
    - EXTRA_SUBNETS=192.168.0.0/24
    ports: 
    - "192.168.0.10:1234:6789"
    - "6881:6881"
    - "6881:6881/udp" 
  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    depends_on:
    - pia
    restart: unless-stopped
    environment:
    - PUID=0
    - PGID=0
    - PASSWORD=mypassword
    network_mode: "service:pia"
    volumes:
    - /share/docker/config/nzbget:/config
    - /share/homes/backup/Download/nzbget:/downloads
```
**5. Is this urgent?**
Quite urgent
