### ISSUE TITLE
Bug: cannot update files (dns over tls)

### ISSUE THREAD

**Issue by Whoffie** [qdm12/gluetun#1110]
### Is this urgent?

No

### Host OS

Ubuntu 22.04

### CPU arch

armv7l

### VPN service provider

Mullvad

### What are you using to run the container

docker-compose

### What is the version of Gluetun

v3.30.0

### What's the problem 🤔

Upon starting Gluetun, it always throws this error for me no matter what (on v3.29.0 as well).

This causes Gluetun to repeat the same error every 40 seconds throwing the client into schizophrenic loop. Not sure what to do with this one, I'm using wireguard with Mullvad.

### Share your logs

```plain text
container-gluetun-1             | 2022-08-19T00:14:19Z INFO [wireguard] Connecting to xx.xxx.xx.xxx:51820
container-gluetun-1             | 2022-08-19T00:14:19Z INFO [wireguard] Wireguard is up
container-gluetun-1             | 2022-08-19T00:14:22Z WARN [dns over tls] cannot update files: Get "https://www.internic.net/domain/named.root": dial tcp: lookup www.internic.net on 1.1.1.1:53: read udp 10.66.58.30:46758->1.1.1.1:53: i/o timeout
container-gluetun-1             | 2022-08-19T00:13:29Z INFO [healthcheck] program has been unhealthy for 6s: restarting VPN
container-gluetun-1             | 2022-08-19T00:13:29Z INFO [vpn] stopping
container-gluetun-1             | 2022-08-19T00:13:29Z ERROR [vpn] cannot get version information: Get "https://api.github.com/repos/qdm12/gluetun/releases": context canceled
container-gluetun-1             | 2022-08-19T00:13:29Z INFO [vpn] starting
container-gluetun-1             | 2022-08-19T00:13:29Z INFO [firewall] allowing VPN connection...
container-gluetun-1             | 2022-08-19T00:13:29Z INFO [wireguard] Using available kernelspace implementation
container-gluetun-1             | 2022-08-19T00:13:29Z INFO [wireguard] Connecting to 87.249.134.14:51820
container-gluetun-1             | 2022-08-19T00:13:29Z INFO [wireguard] Wireguard is up
```

### Share your configuration

```yml
gluetun:
    image: qmcgaw/gluetun:v3.29.0
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${MULLVAD_PKEY}
      - WIREGUARD_ADDRESSES=xx.xx.xx.xx/32
      - SERVER_CITIES=Chicago IL
    ports:
      - target: ${RT_DHT_PORT}
        published: ${RT_DHT_PORT}
        protocol: udp
      - target: ${RUTORRENT_PORT}
        published: ${RUTORRENT_PORT}
        protocol: tcp
      - target: ${WEBDAV_PORT}
        published: ${WEBDAV_PORT}
        protocol: tcp
      - target: ${RT_INC_PORT}
        published: ${RT_INC_PORT}
        protocol: tcp
    restart: always
```
