### ISSUE TITLE
Bug: Windscribe using AES-*-GCM - AEAD Decrypt error: cipher final failed

### ISSUE THREAD

**Issue by qdm12** [qdm12/gluetun#113]
OpenVPN gives the error `AEAD Decrypt error: cipher final failed` at random times.

This should be investigated.

**Comment by qdm12** [comment]
Refers to #59 , @Frepke

**Comment by Frepke** [comment]
> OpenVPN gives the error `AEAD Decrypt error: cipher final failed` at random times.
> 
> This should be investigated.

```
docker exec -it vpn echo $TZ
```
is blanc, no timezone is given.

In my docker-compose file I set TZ=Europe/Amsterdam.

**Comment by qdm12** [comment]
Are you sure? It should definitely be set :confused:
That must be the TLS sync issue error, 99% certain :wink:

For the AEAD Decrypt error, I don't know yet though.

**Comment by Frepke** [comment]
> Are you sure? It should definitely be set 😕
> That must be the TLS sync issue error, 99% certain 😉
> 
> For the AEAD Decrypt error, I don't know yet though.

Yes,
 
```
docker exec -it vpn echo $TZ
```
returns in a empty line 😢 

and my docker-compose.yml:
```
version: "3.7"
services:
  vpn:
    image: qmcgaw/private-internet-access:windscribe
    container_name: vpn
    cap_add:
      - NET_ADMIN
    # devices:
    network_mode: bridge
    init: true
    ports:
      - 8888:8888/tcp #tinyproxy
      - 8388:8388/tcp #shadowsocks
      - 8388:8388/udp #shadowsocks
      - 9501:8080/tcp #sabnzbd
      - 9502:5076/tcp #hydra2
      - 9503:9503/tcp #qbittorrent
      - 9504:5800/tcp #firefox
    # command:
    environment:
      - VPNSP=windscribe
      - USER=
      - PROTOCOL=UDP
      - OPENVPN_VERBOSITY=1
      - OPENVPN_ROOT=no
      - OPENVPN_TARGET_IP=
      - TZ=Europe/Amsterdam

      # PIA & Windscribe only
      - REGION=Netherlands
      - PASSWORD=
      - ENCRYPTION=strong
      - PORT_FORWARDING=off
      - PORT_FORWARDING_STATUS_FILE=/srv/dev-disk-by-label-NASinternalUSB1/vpn
      - OPENVPN_CIPHER=AES-256-GCM

      # Mullvad only
      - COUNTRY=Sweden
      - CITY=
      - ISP=

      # Mullvad & Windscribe only
      - PORT=54783

      # DNS over TLS
      - DOT=on
      - DOT_CACHING=on
      - DOT_IPV6=off
      - DOT_PROVIDERS=cloudflare,quad9
      - DOT_VERBOSITY=1
      - DOT_VERBOSITY_DETAILS=0
      - DOT_VALIDATION_LOGLEVEL=0
      - BLOCK_MALICIOUS=on
      - BLOCK_SURVEILLANCE=on
      - BLOCK_ADS=on
      - UNBLOCK=
      # Firewall
      - EXTRA_SUBNETS=10.54.1.0/24
      # Shadowsocks
      - SHADOWSOCKS=on
      - SHADOWSOCKS_LOG=off
      - SHADOWSOCKS_PORT=8388
      - SHADOWSOCKS_PASSWORD=
      #Tinyproxy
      - TINYPROXY=off
      - TINYPROXY_LOG=Info
      - TINYPROXY_PORT=8888
      - TINYPROXY_USER=
      - TINYPROXY_PASSWORD=

    restart: always

  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: "service:vpn"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /srv/dev-disk-by-label-NASinternalUSB1/sabnzbd:/config
      - /srv/dev-disk-by-label-BarraCuda/sabnzbd/downloads:/downloads
      - /srv/dev-disk-by-label-BarraCuda/sabnzbd/incomplete-downloads:/incomplete-downloads
    restart: always

  hydra2:
    image: linuxserver/hydra2:latest
    container_name: hydra2
    network_mode: "service:vpn"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /srv/dev-disk-by-label-NASinternalUSB1/hydra:/config
      - /srv/dev-disk-by-label-BarraCuda/hydra/downloads:/downloads
    restart: always

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:vpn"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Amsterdam
      - UMASK_SET=022
      - WEBUI_PORT=9503
    volumes:
      - /srv/dev-disk-by-label-NASinternalUSB1/qbittorrent:/config
      - /srv/dev-disk-by-label-BarraCuda/qbittorrent/downloads:/downloads
    restart: always

  firefox:
    image: jlesage/firefox:latest
    container_name: firefox
    network_mode: "service:vpn"
    volumes:
      - /srv/dev-disk-by-label-NASinternalUSB1/firefox:/config:rw
      - /dev/shm:/dev/shm
    restart: always
```
