### ISSUE TITLE
Wireguard kernelspace not detected

### ISSUE THREAD

**Issue by giovannipollo** [qdm12/gluetun#1137]
### Is this urgent?

No

### Host OS

Ubuntu Server 20.04 LTS

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

Portainer

### What is the version of Gluetun

The problem happens in all versions

### What's the problem 🤔

The problems happens in all releases, it is not a problem of the latest release. There are a lot of processes that I can see with `htop` that consumes a lot of CPU. I wanted to know if it normale or not.

Here a picture:

<img width="294" alt="Screenshot 2022-09-07 at 12 27 35" src="https://user-images.githubusercontent.com/50754123/188857867-2ee653a7-2350-4020-9400-eba809bd9056.png">

The column on the left is the CPU usage. As you can see there are some process that consumes up to 130% of CPU
### Share your configuration

```yml
---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - WEBUI_PORT=8080
    volumes:
      - /xxxx:/xxxx
      - /xxx:/xxxx
    restart: unless-stopped
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun_torrent
    ports:
      - 8080:8080
      - 6881:6881
      - 9696:9696
      - 6881:6881/udp
      - 8096:8096
      - 8920:8920
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=xxxxx
      - WIREGUARD_ADDRESSES=xxxx
      - SERVER_CITIES=xxxxx
      - FIREWALL_OUTBOUND_SUBNETS=xxxx
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - /xxx:/xxxx
    restart: unless-stopped
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - /xxx:/xxx
      - xxxx:/xxxx
    devices:
      - /dev/dri:/dev/dri #optional
    restart: unless-stopped
```
