### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by DevArctic** [qdm12/gluetun#1159]
### Is this urgent?

No

### Host OS

Ubuntu

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

Portainer

### What is the version of Gluetun

Running version latest built on 2022-08-13T19:21:32.290Z (commit 349b542)

### What's the problem 🤔

It just took me fifteen minutes to figure out the correct syntax in docker compose for the 

SERVER_REGION=United States

I first tried "United States"
which gave an error. Then I tried United\ States which gave an error, leading me to
try United States with the space included, unescaped. Which worked.

This can't be the proper behavior. If it is, excuse my ignorance.

### Share your logs

```plain text
No logs.
```

### Share your configuration

```yml
version: "2"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: Gluetun_S
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6446:8080/tcp #aria
      - 6556:6556/tcp #transmission
      - 6336:5800/tcp #firefox
    volumes:
      - /Cortana/Downloads-S/Gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - SERVER_REGIONS=United States
  transmission:
    image: ghcr.io/linuxserver/transmission
    restart: always
    container_name: "Transmission_S"
    environment:
      - PUID=1000
      - PGID=1000
      - USER=admin
      - PASS=averycomplexpasswordhere
    network_mode: "service:gluetun"
    volumes:
      - "/Cortana/Downloads-S/Config:/config"
      - "/Cortana/Downloads-S/Downloads:/downloads"
      - "/Cortana/Downloads-S/Watch:/watch"
  ariang:
    image: hurlenko/aria2-ariang
    container_name: "Aria_S"
    network_mode: "service:gluetun"
    volumes:
      - /Cortana/Downloads-S/AriaDownloads:/aria2/data
      - /Cortana/Downloads-S/AriaConfig:/aria2/conf
    environment:
      - PUID=1000
      - PGID=1000
      - BASIC_AUTH_USERNAME=arctic
      - BASIC_AUTH_PASSWORD=Z|BTWNH:w1c{y?M
      - ARIA2RPCPORT=6446
    restart: always

  floodui:
    image: jesec/flood
    #build: floodui
    container_name: "Flood_S"
    restart: always
    network_mode: "service:gluetun"
    volumes:
      - "/Cortana/Downloads-S/Downloads:/downloads"
      - "/Cortana/Downloads-S/Flood:/root/.local/share/flood"
    depends_on: 
      - transmission
    command: --port 6556 --trurl http://127.0.0.1:9091/transmission/rpc --truser admin --trpass averycomplexpasswordhere
    
  firefox:

    image: jlesage/firefox
    container_name: "Firefox_S"
    restart: always
    network_mode: "service:gluetun"
    volumes:
      - "/Cortana/Downloads-S/Firefox/Config:/config:rw"
    shm_size: "2gb"
```
