### ISSUE TITLE
Bug: Cannot get *arrs and downloaders to connect via docker-compose

### ISSUE THREAD

**Issue by mlnl221** [qdm12/gluetun#1174]
### Is this urgent?

No

### Host OS

docker

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-09-14T13:28:28.429Z (commit e5be20d)

### What's the problem 🤔

After settings up my docker compose to use Gluetun, I created a network_bridge pointing to `service:glutun`. This enables the individual *arr services to be able to use the VPN and contact the external work. I verified that sonarr was able to use the VPN by running `curl ifconfig.io` and getting back my VPN's ip address inside the container.

Now I am having issues having Sonarr connect to qBitorrent, SABnzbd and Prowlarr. These use to just connect to each other using my local network aka `192.168.1.40` but now there seems to be no contact between the services only `gluetun` and the outside world.

Any idea how to get the docker-compose network services to talk to each other?

### Share your logs

```plain text
2022-09-28T19:39:34-05:00 INFO IPv6 is not supported
2022-09-28T19:39:34-05:00 INFO [routing] default route found: interface eth0, gateway -------- and assigned IP ------
2022-09-28T19:39:34-05:00 INFO [routing] adding route for 0.0.0.0/0
2022-09-28T19:39:34-05:00 INFO [firewall] setting allowed subnets...
2022-09-28T19:39:34-05:00 INFO [routing] default route found: interface eth0, gateway -------- and assigned IP ------
2022-09-28T19:39:34-05:00 INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
2022-09-28T19:39:34-05:00 INFO [pprof] http server listening on [::]:6060
2022-09-28T19:39:34-05:00 INFO [http server] http server listening on [::]:8000
2022-09-28T19:39:34-05:00 INFO [dns over tls] using plaintext DNS at address 1.1.1.1
2022-09-28T19:39:34-05:00 INFO [firewall] allowing VPN connection...
2022-09-28T19:39:34-05:00 INFO [healthcheck] listening on 127.0.0.1:9999
2022-09-28T19:39:34-05:00 INFO [wireguard] Using available kernelspace implementation
2022-09-28T19:39:34-05:00 INFO [wireguard] Connecting to ----------.2:51820
2022-09-28T19:39:34-05:00 INFO [wireguard] Wireguard is up
2022-09-28T19:39:34-05:00 INFO [dns over tls] downloading DNS over TLS cryptographic files
2022-09-28T19:39:35-05:00 INFO [healthcheck] healthy!
2022-09-28T19:39:38-05:00 INFO [dns over tls] downloading hostnames and IP block lists
2022-09-28T19:39:49-05:00 INFO [healthcheck] unhealthy: cannot dial: dial tcp4: lookup cloudflare.com: i/o timeout
2022-09-28T19:39:50-05:00 INFO [dns over tls] init module 0: validator
2022-09-28T19:39:50-05:00 INFO [dns over tls] init module 1: iterator
2022-09-28T19:39:50-05:00 INFO [dns over tls] start of service (unbound 1.15.0).
2022-09-28T19:39:51-05:00 INFO [dns over tls] generate keytag query _ta-4a5c-4f66. NULL IN
2022-09-28T19:39:51-05:00 INFO [dns over tls] generate keytag query _ta-4a5c-4f66. NULL IN
2022-09-28T19:39:52-05:00 INFO [dns over tls] ready
2022-09-28T19:39:52-05:00 INFO [healthcheck] healthy!
2022-09-28T19:39:53-05:00 INFO [vpn] You are running on the bleeding edge of latest!
2022-09-28T19:39:53-05:00 INFO [ip getter] Public IP address is ----------.10 (Netherlands, North Holland, Amsterdam)
```

### Share your configuration

```yml
version: "2"
services:
  qbittorrentvpn:
    image: dyonr/qbittorrentvpn
    container_name: qbittorrentvpn
    privileged: true   
    environment:
      - VPN_ENABLED=no
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT_ENV=8080
      - INCOMING_PORT_ENV=8999
      - LAN_NETWORK=192.168.1.0/24 #adjust this to YOUR network settings
      - NAME_SERVERS=1.1.1.1 #you can use whatever DNS provider you want
    volumes:
      - /home/bobert/Documents/homlab/Configs/QBittorrentVPN:/config
      - /home/bobert/Documents/homlab/Torrents:/downloads
    restart: unless-stopped
    network_mode: "service:gluetun"
    
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    volumes:
      - /home/bobert/Documents/homlab/Configs/Radarr:/config
      - /home/bobert/Documents/homlab/Downloads:/NZBdownloads
      - /home/bobert/Documents/homlab/Movies:/movies
      - /home/bobert/Documents/homlab/Torrents:/downloads
      - /home/bobert/Documents/external/Movies:/moviesExternal
      - /home/bobert/gdrive/Movies:/moviesGdrive
    network_mode: "service:gluetun"
    restart: unless-stopped
    
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/bobert/Documents/homlab/Configs/Sabnzbd:/config
      - /home/bobert/Documents/homlab/Downloads:/NZBdownloads
      - /home/bobert/Documents/homlab/Downloads/Incomplete:/incomplete-downloads #optional
    restart: unless-stopped
    network_mode: "service:gluetun"
    
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022
    volumes:
      - /home/bobert/Documents/homlab/Configs/Sonarr:/config
      - /home/bobert/Documents/homlab/Downloads:/NZBdownloads
      - /home/bobert/Documents/homlab/Torrents:/downloads
      - /home/bobert/Documents/homlab/TvShows:/tv
      - /home/bobert/Documents/external/TvShows:/tvExternal
      - /home/bobert/gdrive/TvShows:/tvGdrive
    restart: unless-stopped
    network_mode: "service:gluetun"

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UMASK_SET=022
    volumes:
      - /home/bobert/Documents/homlab/Configs/Bazarr:/config
      - /home/bobert/Documents/homlab/TvShows:/tv
      - /home/bobert/Documents/external/TvShows:/tvExternal
      - /home/bobert/gdrive/TvShows:/tvGdrive
      - /home/bobert/Documents/homlab/Movies:/movies
      - /home/bobert/Documents/external/Movies:/moviesExternal
      - /home/bobert/gdrive/Movies:/moviesGdrive
    network_mode: "service:gluetun"
    restart: unless-stopped

  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /home/bobert/Documents/homlab/Configs/Whisparr:/config
      - /home/bobert/Documents/homlab/Pmovies:/Movies
      - /home/bobert/Documents/homlab/Downloads:/NZBdownloads
      - /home/bobert/Documents/homlab/Torrents:/downloads
    network_mode: "service:gluetun"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/bobert/Documents/homlab/Prowlarr:/config
    restart: unless-stopped
    network_mode: "service:gluetun"

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8886:8888/tcp # HTTP proxy  
      - 8388:8388/tcp # Shadowsocks  
      - 8388:8388/udp # Shadowsocks 
      - 8000:8000/tcp # Built-in HTTP control server
      - 9696:9696 #prowlarr
      - 8989:8989 #sonarr
      - 7878:7878 # Radarr
      - 6969:6969 # Whisparr
      - 6767:6767 # Bazarr
      - 8181:8080 # Sabnzbd
      - 9191:9090 # Sabnzbd
      - 8080:8080 # qbitorrent
      - 8999:8999 # qbitorrent
      - 8999:8999/udp # qbitorrent
    volumes:
      - /home/bobert/Documents/homelab/Gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=aIy**********************F8mXg=
      - WIREGUARD_ADDRESSES=10.65.174.77/32
      - SERVER_CITIES=Amsterdam
      - TZ=America/Chicago
    restart: unless-stopped
    network_mode: bridge
```

**Comment by bnhf** [comment]
The docker-compose I use, via Portainer - Stacks, looks very similar to yours. The main difference I'm noticing is that you aren't specifying ``` depends_on:     - gluetun ``` to the compose for each of the containers you want to use the VPN.  As I understand it, depends_on determines the order in which the containers are launched, so that gluetun will be up-and-running before the others attempt to connect through it.

In addition to the *arrs, you may want to add this Firefox container to your stack to help with debugging. I use AirVPN, and with the Firefox container I'm able to actually go to airvpn.org to verify which of their servers I'm using. I also use Speedtest.net and IPLeak.net, to check performance of the tunnel, check for DNS leaks and a number of other functions -- all via the containerized Firefox routed through the VPN tunnel:
```
firefox:
        image: lscr.io/linuxserver/firefox:latest
        container_name: firefox
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Denver
        volumes:
            - /data/firefox:/config
        shm_size: "1gb"
        network_mode: 'service:gluetun'
        depends_on:
            - gluetun
```
You'll need to add port 3000 to your list of ports under Gluetun to access the Firefox container.

With a correctly configured stack, there should be no need to do anything with Docker networking.  For example, there's no need to specify network_mode: bridge since that's the default. Gluetun is able connect to the Internet via /dev/tun by virtue of  ``` cap_add:     - NET_ADMIN ```, and the other containers through gluetun via network_mode and depends_on.

As you can see, the other containers in my gluetun stack don't even have their own Docker IP addresses:

![Screenshot 2022-09-29 090351](https://user-images.githubusercontent.com/41088895/193068603-fce4f76f-9619-435c-b128-e9f702ee3ced.png)

**Comment by bnhf** [comment]
> I figured this out finally. Docker network assigns a new ip to the network. I had to check each service using `docker exec 48da44986ae1 cat /etc/hosts` and that showed the ip address `172.17.0.3 9a6afdab394b` that connects to the container. Now I can go to each `Indexer` and `Download client` and use this new IP address for the services to communicate.

@minicoz

None of this is necessary. When your VPN stack is working properly, you can reference your download clients and indexers at 'localhost' in *arrs setup. Check my response above for more detail.

**Comment by bnhf** [comment]
@minicoz 

Not too sure this section of your stack is correct either -- though I use Deluge myself:
```
qbittorrentvpn:
    image: dyonr/qbittorrentvpn
    container_name: qbittorrentvpn
    privileged: true   
    environment:
      - VPN_ENABLED=no
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT_ENV=8080
      - INCOMING_PORT_ENV=8999
      - LAN_NETWORK=192.168.1.0/24 #adjust this to YOUR network settings
      - NAME_SERVERS=1.1.1.1 #you can use whatever DNS provider you want
    volumes:
      - /home/bobert/Documents/homlab/Configs/QBittorrentVPN:/config
      - /home/bobert/Documents/homlab/Torrents:/downloads
    restart: unless-stopped
    network_mode: "service:gluetun"
```
Why use a qbittorrent container that has a VPN embedded, even if it's disabled? I'd suggest you switch to the linuxserver.io version to keep things clean and consistent. The LAN_NETWORK and NAME_SERVERS environment variables would likely be for the embedded VPN, but if not might be causing issues.
