### ISSUE TITLE
HTTP Proxy: Username/Password Mismatch

### ISSUE THREAD

**Issue by TuRDMaN** [qdm12/gluetun#1176]
### Is this urgent?

Yes

### Host OS

Almalinux

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

Portainer

### What is the version of Gluetun

Running version latest built on 2022-09-14T13:28:28.429Z (commit e5be20d)

### What's the problem 🤔

I am trying to use the environment variables to set a username and/or password
```
environment:
      - HTTPPROXY_USER=username
      - HTTPPROXY_PASSWORD=password
```

When I attempt to connect to the HTTP proxy using those credentials, I get the following error in my logs: `Username or password mismatch from <ip:port>`

This happens if I set just a username, or a username and password.

I assume I'm doing something wrong, but I can't figure out what.

It works fine if I don't require username/password, but I don't want to have this exposed on the web without password protection. Or I'd be happy with just allowing LAN clients to access the HTTP proxy, but I haven't figured out how to do that either.

### Share your logs

```plain text
INFO [vpn] You are running on the bleeding edge of latest!
2022-09-30T16:37:47-04:00 INFO [http proxy] Username or password mismatch from <ip>:<port>
```

### Share your configuration

```yml
services:
  ######
  vpn: #
  ######
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      #- 8388:8388/tcp # Shadowsocks
      #- 8388:8388/udp # Shadowsocks
    volumes:
      - /opt/containers/vpn/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=user
      - OPENVPN_PASSWORD=password
      - SERVER_COUNTRIES=United States
      - FREE_ONLY=on
      - HTTPPROXY=on
      - HTTPPROXY_USER=user
      - HTTPPROXY_PASSWORD=password
      - FIREWALL=on
      - BLOCK_SURVEILLANCE=on
      - BLOCK_ADS=off
      - DNS_KEEP_NAMESERVER=on
      - PUBLICIP_FILE=/gluetun/ip
      - LOG_LEVEL=info
      - HTTPPROXY_LOG=on
      - HTTP_CONTROL_SERVER_LOG=on
      - SHADOWSOCKS_LOG=on
      - HEALTH_VPN_DURATION_ADDITION=10s
      - UPDATER_PERIOD=24h
      - VERSION_INFORMATION=on
      - DOT=off
      - BLOCK_MALICIOUS=on
      - HOST_HOSTNAME=my.host
      - HTTPPROXY_STEALTH=off
      - HTTPPROXY_LISTENING_ADDRESS=:8888
      - SHADOWSOCKS_LISTENING_ADDRESS=:8388
      - HTTP_CONTROL_SERVER_ADDRESS=:8000
```
