### ISSUE TITLE
Bug: Portugal not allowed in SERVER_COUNTRIES using PureVPN

### ISSUE THREAD

**Issue by hsmptg** [qdm12/gluetun#1195]
### Is this urgent?

No

### Host OS

Ubuntu 22.04

### CPU arch

aarch64

### VPN service provider

PureVPN

### What are you using to run the container

Portainer

### What is the version of Gluetun

Running version latest built on 2022-10-02T09:36:14.095Z (commit cb80457)

### What's the problem 🤔

Despite [Wiki page](https://github.com/qdm12/gluetun/wiki/PureVPN#Servers) mention the possibility of having an environment variable SERVER_COUNTRIES equal to Portugal, if I do that I get the error _...the country specified is not valid..._

### Share your logs

```plain text
2022-10-15T12:52:43+01:00 ERROR VPN settings: provider settings: server selection: the country specified is not valid: value is not one of the possible choices: value "portugal", choices available are Albania, Australia, Austria, Belgium, Brazil, Bulgaria, Canada, Costa Rica, Czech Republic, Denmark, Egypt, Estonia, Finland, France, Georgia, Germany, Hong Kong, Hungary, India, Indonesia, Ireland, Israel, Italy, Japan, Kenya, Korea, Latvia, Lithuania, Luxembourg, Malaysia, Moldova, Monaco, Netherlands, Nigeria, Norway, Poland, Romania, Russian Federation, Serbia, Singapore, Slovakia, South Africa, Switzerland, Taiwan, Thailand, Ukraine, United Arab Emirates, United Kingdom, United States, Vietnam
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /home/ubuntu/docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=purevpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=abc
      - OPENVPN_PASSWORD=abc
      - SERVER_COUNTRIES=Portugal
      - TZ=Europe/Lisbon
```
