### ISSUE TITLE
Bug: qBittorrent not reaching announce with Mullvad

### ISSUE THREAD

**Issue by Powablocks** [qdm12/gluetun#1211]
### Is this urgent?

No

### Host OS

Raspberry Pi OS Lite (32-bits)

### CPU arch

armv7l

### VPN service provider

Mullvad

### What are you using to run the container

docker-compose

### What is the version of Gluetun

2022-10-17T06:59:03.538Z (commit f15dde6)

### What's the problem 🤔

I'm having trouble getting qbittorrent to work through gluetun with mullvad. 
I'm thinking it comes from dns problem because the tracker announce are all unreachable.
![image](https://user-images.githubusercontent.com/16413448/197526233-667eaed3-f335-4f71-b61e-bbaedc27bae7.png)
I'm having DNS lookup problem in the logs so I think it come from here.
Does anyone have an idea what could be the reason ?

### Share your logs

```plain text
Attaching to gluetun, qbittorrent
gluetun      | ========================================
gluetun      | ========================================
gluetun      | =============== gluetun ================
gluetun      | ========================================
gluetun      | =========== Made with ❤️ by ============
gluetun      | ======= https://github.com/qdm12 =======
gluetun      | ========================================
gluetun      | ========================================
gluetun      |
gluetun      | Running version latest built on 2022-10-17T06:59:03.538Z (commit f15dde6)
gluetun      |
gluetun      | 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
gluetun      | 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
gluetun      | ✨ New feature? https://github.com/qdm12/gluetun/issues/new
gluetun      | ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
gluetun      | 💻 Email? quentin.mcgaw@gmail.com
gluetun      | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
gluetun      | 2022-10-24T13:57:49+02:00 INFO [routing] default route found: interface eth0, gateway 172.18.0.1 and assigned IP 172.18.0.2
gluetun      | 2022-10-24T13:57:49+02:00 INFO [routing] local ethernet link found: eth0
gluetun      | 2022-10-24T13:57:49+02:00 INFO [routing] local ipnet found: 172.18.0.0/16
gluetun      | 2022-10-24T13:57:49+02:00 INFO [firewall] enabling...
gluetun      | 2022-10-24T13:57:49+02:00 INFO [firewall] enabled successfully
qbittorrent  | [custom-init] No custom services found, skipping...
qbittorrent  | [migrations] started
qbittorrent  | [migrations] no migrations found
qbittorrent  |
qbittorrent  | -------------------------------------
qbittorrent  |           _         ()
qbittorrent  |          | |  ___   _    __
qbittorrent  |          | | / __| | |  /  \
qbittorrent  |          | | \__ \ | | | () |
qbittorrent  |          |_| |___/ |_|  \__/
qbittorrent  |
qbittorrent  |
qbittorrent  | Brought to you by linuxserver.io
qbittorrent  | -------------------------------------
qbittorrent  |
qbittorrent  | To support LSIO projects visit:
qbittorrent  | https://www.linuxserver.io/donate/
qbittorrent  | -------------------------------------
qbittorrent  | GID/UID
qbittorrent  | -------------------------------------
qbittorrent  |
qbittorrent  | User uid:    1000
qbittorrent  | User gid:    1000
qbittorrent  | -------------------------------------
qbittorrent  |
qbittorrent  | [custom-init] No custom files found, skipping...
qbittorrent  |
qbittorrent  | ******** Information ********
qbittorrent  | To control qBittorrent, access the WebUI at: http://localhost:8081
gluetun      | 2022-10-24T13:57:50+02:00 INFO [storage] merging by most recent 13173 hardcoded servers and 13173 servers read from /gluetun/servers.json
qbittorrent  | [ls.io-init] done.
gluetun      | 2022-10-24T13:57:51+02:00 INFO Alpine version: 3.16.2
gluetun      | 2022-10-24T13:57:51+02:00 INFO OpenVPN 2.4 version: 2.4.12
gluetun      | 2022-10-24T13:57:51+02:00 INFO OpenVPN 2.5 version: 2.5.6
gluetun      | 2022-10-24T13:57:51+02:00 INFO Unbound version: 1.15.0
gluetun      | 2022-10-24T13:57:51+02:00 INFO IPtables version: v1.8.8
gluetun      | 2022-10-24T13:57:51+02:00 INFO Settings summary:
gluetun      | ├── VPN settings:
gluetun      | |   ├── VPN provider settings:
gluetun      | |   |   ├── Name: mullvad
gluetun      | |   |   └── Server selection settings:
gluetun      | |   |       ├── VPN type: wireguard
gluetun      | |   |       ├── Hostnames: fr4-wireguard, fr5-wireguard, fr6-wireguard, fr7-wireguard
gluetun      | |   |       └── Wireguard selection settings:
gluetun      | |   └── Wireguard settings:
gluetun      | |       ├── Private key: 8M...W8=
gluetun      | |       ├── Interface addresses:
gluetun      | |       |   └── 10.68.20.132/32
gluetun      | |       └── Network interface: tun0
gluetun      | ├── DNS settings:
gluetun      | |   ├── DNS server address to use: 127.0.0.1
gluetun      | |   ├── Keep existing nameserver(s): no
gluetun      | |   └── DNS over TLS settings:
gluetun      | |       ├── Enabled: yes
gluetun      | |       ├── Update period: every 24h0m0s
gluetun      | |       ├── Unbound settings:
gluetun      | |       |   ├── Authoritative servers:
gluetun      | |       |   |   └── cloudflare
gluetun      | |       |   ├── Caching: yes
gluetun      | |       |   ├── IPv6: no
gluetun      | |       |   ├── Verbosity level: 1
gluetun      | |       |   ├── Verbosity details level: 0
gluetun      | |       |   ├── Validation log level: 0
gluetun      | |       |   ├── System user: root
gluetun      | |       |   └── Allowed networks:
gluetun      | |       |       ├── 0.0.0.0/0
gluetun      | |       |       └── ::/0
gluetun      | |       └── DNS filtering settings:
gluetun      | |           ├── Block malicious: yes
gluetun      | |           ├── Block ads: no
gluetun      | |           ├── Block surveillance: no
gluetun      | |           └── Blocked IP networks:
gluetun      | |               ├── 127.0.0.1/8
gluetun      | |               ├── 10.0.0.0/8
gluetun      | |               ├── 172.16.0.0/12
gluetun      | |               ├── 192.168.0.0/16
gluetun      | |               ├── 169.254.0.0/16
gluetun      | |               ├── ::1/128
gluetun      | |               ├── fc00::/7
gluetun      | |               ├── fe80::/10
gluetun      | |               ├── ::ffff:7f00:1/104
gluetun      | |               ├── ::ffff:a00:0/104
gluetun      | |               ├── ::ffff:a9fe:0/112
gluetun      | |               ├── ::ffff:ac10:0/108
gluetun      | |               └── ::ffff:c0a8:0/112
gluetun      | ├── Firewall settings:
gluetun      | |   └── Enabled: yes
gluetun      | ├── Log settings:
gluetun      | |   └── Log level: INFO
gluetun      | ├── Health settings:
gluetun      | |   ├── Server listening address: 127.0.0.1:9999
gluetun      | |   ├── Target address: cloudflare.com:443
gluetun      | |   ├── Read header timeout: 100ms
gluetun      | |   ├── Read timeout: 500ms
gluetun      | |   └── VPN wait durations:
gluetun      | |       ├── Initial duration: 6s
gluetun      | |       └── Additional duration: 5s
gluetun      | ├── Shadowsocks server settings:
gluetun      | |   └── Enabled: no
gluetun      | ├── HTTP proxy settings:
gluetun      | |   └── Enabled: no
gluetun      | ├── Control server settings:
gluetun      | |   ├── Listening address: :8000
gluetun      | |   └── Logging: yes
gluetun      | ├── OS Alpine settings:
gluetun      | |   ├── Process UID: 1000
gluetun      | |   ├── Process GID: 1000
gluetun      | |   └── Timezone: Europe/Paris
gluetun      | ├── Public IP settings:
gluetun      | |   ├── Fetching: every 12h0m0s
gluetun      | |   └── IP file path: /tmp/gluetun/ip
gluetun      | └── Version settings:
gluetun      |     └── Enabled: yes
gluetun      | 2022-10-24T13:57:51+02:00 INFO IPv6 is not supported
gluetun      | 2022-10-24T13:57:51+02:00 INFO [routing] default route found: interface eth0, gateway 172.18.0.1 and assigned IP 172.18.0.2
gluetun      | 2022-10-24T13:57:51+02:00 INFO [routing] adding route for 0.0.0.0/0
gluetun      | 2022-10-24T13:57:51+02:00 INFO [firewall] setting allowed subnets...
gluetun      | 2022-10-24T13:57:51+02:00 INFO [routing] default route found: interface eth0, gateway 172.18.0.1 and assigned IP 172.18.0.2
gluetun      | 2022-10-24T13:57:51+02:00 INFO [pprof] http server listening on [::]:6060
gluetun      | 2022-10-24T13:57:51+02:00 INFO [dns over tls] using plaintext DNS at address 1.1.1.1
gluetun      | 2022-10-24T13:57:51+02:00 INFO [http server] http server listening on [::]:8000
gluetun      | 2022-10-24T13:57:51+02:00 INFO [healthcheck] listening on 127.0.0.1:9999
gluetun      | 2022-10-24T13:57:51+02:00 INFO [firewall] allowing VPN connection...
gluetun      | 2022-10-24T13:57:51+02:00 INFO [wireguard] Using available kernelspace implementation
gluetun      | 2022-10-24T13:57:51+02:00 INFO [wireguard] Connecting to 193.32.126.69:51820
gluetun      | 2022-10-24T13:57:51+02:00 INFO [wireguard] Wireguard is up
gluetun      | 2022-10-24T13:57:51+02:00 INFO [dns over tls] downloading DNS over TLS cryptographic files
gluetun      | 2022-10-24T13:57:52+02:00 INFO [healthcheck] healthy!
gluetun      | 2022-10-24T13:57:52+02:00 INFO [dns over tls] downloading hostnames and IP block lists
gluetun      | 2022-10-24T13:58:00+02:00 INFO [healthcheck] unhealthy: cannot dial: dial tcp4: lookup cloudflare.com: i/o timeout
gluetun      | 2022-10-24T13:58:02+02:00 INFO [dns over tls] init module 0: validator
gluetun      | 2022-10-24T13:58:02+02:00 INFO [dns over tls] init module 1: iterator
gluetun      | 2022-10-24T13:58:02+02:00 INFO [dns over tls] start of service (unbound 1.15.0).
gluetun      | 2022-10-24T13:58:02+02:00 INFO [dns over tls] generate keytag query _ta-4a5c-4f66. NULL IN
gluetun      | 2022-10-24T13:58:02+02:00 INFO [dns over tls] generate keytag query _ta-4a5c-4f66. NULL IN
gluetun      | 2022-10-24T13:58:02+02:00 INFO [dns over tls] ready
gluetun      | 2022-10-24T13:58:02+02:00 INFO [healthcheck] healthy!
gluetun      | 2022-10-24T13:58:02+02:00 INFO [ip getter] Public IP address is xx.xx.xx.xx (hidden real address)
gluetun      | 2022-10-24T13:58:02+02:00 INFO [vpn] You are running on the bleeding edge of latest!
```

### Share your configuration

```yml
gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=8MKGw29cTeTi28aOd5fWYCrbQj0DMCYJu4WDwTsNQW8=
      - WIREGUARD_ADDRESSES=10.68.20.132/32
      - SERVER_HOSTNAMES=fr4-wireguard,fr5-wireguard,fr6-wireguard,fr7-wireguard
      # Timezone for accurate log times
      - TZ=Europe/Paris

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=8081
    volumes:
      - ./qbitorrent:/config
      - /media/usb/plex:/downloads
    restart: unless-stopped
```
