### ISSUE TITLE
Feature request: Read FIREWALL_VPN_INPUT_PORTS from file

### ISSUE THREAD

**Issue by EnumC** [qdm12/gluetun#1297]
### What's the feature 🧐

For providers that only provide ephemeral port forwarding, such as Windscribe, it would be beneficial to be able to dynamically modify the firewall port via modifying a mapped file rather than having to modify the environmental variable and restart the entire stack. 

#### Hypothetical example for port forwarding port 20454:

docker-compose.yml:
```
services:
  gluetun:
    environment:
      - FIREWALL_VPN_INPUT_PORTS_FILE=/vpn_port.txt
    volumes:
      - /root/docker/gluetun/vpn_port.txt:/vpn_port.txt
 ```

vpn_port.txt:
```
20454
```

### Extra information and references

This will enable users who rely on ephemeral port forwarding services to programmatically modify their port forwarding.
External containers such as [qbittorrent-windscribe-ephemeral-port](https://github.com/EnumC/qbittorrent-windscribe-ephemeral-port) & [deluge-windscribe-ephemeral-port](https://github.com/dumbasPL/deluge-windscribe-ephemeral-port) can automatically request a port from Windscribe and modify qbittorrent/deluge port setting, All that's left is to find a programmatic way to do the same for gluetun.
