### ISSUE TITLE
Bug: Sonarr cant reach indexer

### ISSUE THREAD

**Issue by TibiaBubble** [qdm12/gluetun#1349]
### Is this urgent?

No, but it would be nice if it was 😅

### Host OS

Docker

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

docker-compose

### What is the version of Gluetun

d0f678c

### What's the problem 🤔

My sonarr container cant connect to the indexer prowlarr (I have even tried jackett). I think it might be a firewall rule that needs to be implenented or somthing but I cant figure it out after 5 days I am starting to loose hope :(

all of this is pretty new to me and please go easy on me if I am doing somthing wrong :)

### Share your logs

```plain text
dont know how to find log
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy gluetun
      - 8388:8388/tcp # Shadowsocks gluetun
      - 8388:8388/udp # Shadowsocks gluetun
      - 9696:9696 #prowlarr
      - 8989:8989 #sonarr
      - 7878:7878 #radarr
      - 5055:5055 # overseer
      - 8080:8080 #qbittorrent
      - 6881:6881 #qbittorrent
      - 6881:6881/udp #qbittorrent
    volumes:
      - /home/vol1/docker/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=(WIREGUARD_PRIVATE_KEY)
      - WIREGUARD_ADDRESSES=(WIREGUARD_ADDRESSES)
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000



#---
#version: "2.1"
#services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WEBUI_PORT=8080
    volumes:
      - /home/vol1/docker/qbittorrent:/config
      - /home/vol1/data/arr/torr:/downloads
    #ports:
      #- 8080:8080 #qbittorrent
      #- 6881:6881 #qbittorrent
      #- 6881:6881/udp #qbittorrent
    restart: unless-stopped



#---
#version: "2.1"
#services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/vol1/docker/prowlarr:/config
    #ports:
      #- 9696:9696 #prowlarr
    restart: unless-stopped



#    ---
#version: "2.1"
#services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/vol1/docker/sonarr:/config
      - /home/vol1/data/arr:/tv #optional
      - /home/vol1/data/arr/torr:/downloads #optional
    #ports:
      #- 8989:8989 #sonarr
    restart: unless-stopped


#---
#version: "2.1"
#services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/vol1/docker/radarr:/config
      - /home/vol1/data/arr:/movies #optional
      - /home/vol1/data/arr/torr:/downloads #optional
    #ports:
      #- 7878:7878 #radarr
    restart: unless-stopped



#-----Overseer
  overseerr:
    image: ghcr.io/linuxserver/overseerr:latest
    container_name: overseerr
    network_mode: "service:gluetun"
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/vol1/docker/overseer:/config
    restart: unless-stopped
```

**Comment by bnhf** [comment]
@TibiaBubble 

Your stack looks OK to me, though I personally prefer to use network_mode plus depends_on for each dependent container, in the form:
```yml
        network_mode: 'service:gluetun'
        depends_on:
            - gluetun
```
It may not be mandatory, but it seems to work well for me.

Otherwise, I take it you can login to Prowlarr and Sonarr? If so, go to ```Settings - Apps - Sonarr``` in Prowlarr and check you've entered a ```Sonarr Server``` value in the form ```http://localhost:8989``` and double-check the ApiKey matches the one in Sonarr from ```Settings - General - Security```. Are you also having this problem with Radarr?
