### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by 3flippa** [qdm12/gluetun#1396]
### Is this urgent?

Yes

### Host OS

Ubuntu 22.04

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

latest

### What's the problem 🤔

Hey Quentin,

My team and me are working on a project of our firm example.com and have another development website dev.example.com. On dev.example.com we are testing the newest code from our code base. we are handling the automated testing with selenium and use your VPN container to test different versions and restrictions of the site depended of the country it was requested. This process is tracked for analysis for us by Google Analytics. 

because it is a critical part of testing we tried to tack the issue down and concluded that it has probably to do with the IP masking of your container but to this point we are not really sure were or what. 

note:
- the process is working fine when using nordvpn cli on linux 
- the process is working fine when started without masking

Thank you for your time and resources 

### Share your logs

```plain text
-
```

### Share your configuration

```yml
version: '3'
services:
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=philippwaldblick@gmail.com
      - OPENVPN_PASSWORD=michihatgeburtstag
      - SERVER_REGIONS=Spain
    ports:
      - 9000:9000/tcp
  tester:
    build: 
      context: ./container/tester
      shm_size: '2gb'
    container_name: tester
    shm_size: '2gb'
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_healthy
    restart: always
```
