### ISSUE TITLE
Bug: HTTP control server returns empty object for IP

### ISSUE THREAD

**Issue by jnines** [qdm12/gluetun#1431]
### Is this urgent?

No

### Host OS

Ubuntu 22.04.2 LTS 

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2023-02-27T20:21:31.112Z (commit a97fcda)

### What's the problem 🤔

HTTP control server returns `{}` when curling `server:8000/v1/publicip/ip`.  The server is still functioning as `server:8000/v1/openvpn/status` returns `{"status":"running"}`.  Can still see the request for both in the log.

### Share your logs

```plain text
gluetun  | 2023-02-28T09:00:02-06:00 INFO [http server] 200 GET /ip wrote 3B to 172.18.0.1:34858 in 27.555µs
gluetun  | 2023-02-28T09:06:29-06:00 INFO [http server] 200 GET /ip wrote 3B to 172.18.0.1:33022 in 29.033µs
gluetun  | 2023-02-28T09:06:40-06:00 INFO [http server] 200 GET /status wrote 21B to 10.10.10.8:60682 in 31.71µs
gluetun  | 2023-02-28T09:07:04-06:00 INFO [http server] 200 GET /ip wrote 3B to 10.10.10.8:60034 in 28.451µs
gluetun  | 2023-02-28T09:10:01-06:00 INFO [http server] 200 GET /status wrote 21B to 172.18.0.1:38452 in 23.66µs
gluetun  | 2023-02-28T09:10:01-06:00 INFO [http server] 200 GET /ip wrote 3B to 172.18.0.1:38468 in 19.537µs
```

### Share your configuration

```yml
gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
      - 9005:7878     # Radarr
      - 9012:8686     # Lidarr
      - 9006:9091     # Trans web
      - 51413:51413   # Trans
      - 9003:8989     # Sonarr
      - 9004:9696     # Prowlarr
    volumes:
      - ${DOCK}/gluetun:/gluetun
      - ${DOCK}/gluetun/port:/tmp/gluetun/
    environment:
      - OPENVPN_USER=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - VPN_SERVICE_PROVIDER=private internet access
      - TZ=${TZ}
      - SERVER_REGIONS=${VPN_CONFIG}
      - PUID=${PUID}
      - PGID=${PGID}
      - FIREWALL_OUTBOUND_SUBNETS=10.10.10.0/24,10.10.20.0/24,10.10.30.0/24
      - OPENVPN_CIPHERS=aes-256-gcm
      - OPENVPN_AUTH=sha256
      - PRIVATE_INTERNET_ACCESS_OPENVPN_ENCRYPTION_PRESET=strong
      - PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING=on
    restart: always
    networks:
      - media
```
