### ISSUE TITLE
Cannot connect container to gluetun

### ISSUE THREAD

**Issue by p6002** [qdm12/gluetun#1434]
### Is this urgent?

No

### Host OS

Ubuntu 22

### CPU arch

aarch64

### VPN service provider

AirVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

latest

### What's the problem 🤔

These two links do not contain full instructions:
https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
https://github.com/qdm12/gluetun/wiki/Port-mapping

How do I redirect the container to gluetun?

My compose:
gluetun:
https://pastebin.com/sFJ1RA6u
neko:
https://pastebin.com/AQQEicWC

### Share your logs

```plain text
no logs
```

**Comment by bnhf** [comment]
@p6002 

I'd suggest putting everything you want to access the Internet through Gluetun into a single stack. Try something like this:

```yml
version: '3.7'
services:

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8090:8090 # qbittorrent
      - 8558:8080 # neko
      - 52000-52100:52000-52100/udp #neko
    volumes:
      - /docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER=sdfsdfasdfasd
      - OPENVPN_PASSWORD=fdasfasdfasdf
      - SERVER_COUNTRIES=Sweden,Switzerland
      - TZ=Europe/Amsterdam

  neko:
    image: m1k1o/neko:latest
    container_name: neko
    shm_size: 4gb
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: asdfasdf
      NEKO_PASSWORD_ADMIN: sdafasdf
      NEKO_EPR: 52000-52100
      NEKO_NAT1TO1: 192.168.1.100
    network_mode: 'service:gluetun'
    depends_on:
      - gluetun
    restart: unless-stopped
```

**Comment by p6002** [comment]
I already use them together, but now I need to have them separately.

**Comment by bnhf** [comment]
@p6002 

As two stacks, give this a try. I just tested it on a Raspberry Pi 4 running 64bit Debian with a Firefox container, and it was working as expected:

Gluetun Stack:

```yml
version: '3.7'
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8090:8090 # qbittorrent
      - 8558:8080 # neko
      - 52000-52100:52000-52100/udp #neko
    volumes:
      - /docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER=sdfsdfasdfasd
      - OPENVPN_PASSWORD=fdasfasdfasdf
      - SERVER_COUNTRIES=Sweden,Switzerland
      - TZ=Europe/Amsterdam
```

Neko Stack:

```yml
version: '3.7'
services:
  neko:
    image: m1k1o/neko:latest
    container_name: neko
    shm_size: 4gb
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: asdfasdf
      NEKO_PASSWORD_ADMIN: sdafasdf
      NEKO_EPR: 52000-52100
      NEKO_NAT1TO1: 192.168.1.100
    network_mode: 'container:gluetun'
    restart: unless-stopped
```
