### ISSUE TITLE
Bug: "unversioned API: requested URI not found" on certain service

### ISSUE THREAD

**Issue by SHU-red** [qdm12/gluetun#1461]
### Is this urgent?

No

### Host OS

CoreOS

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

Portainer

### What is the version of Gluetun

Running version latest built on 2023-03-01T14:10:28.105Z (commit ab5dbdc)

### What's the problem 🤔

Im using a Portainer-Stack (=Docker-Compose), to deploy Gluetun with Mullvad-VPN and use

- jDownloader2
- PyLoad
 
in `network_mode: service:gluetun_vpn`

This way i can use specific services to only be able to use vpn through gluetun

The ports for the services have to be mapped from within the gluetun service (see compose-config below)

For jDownloader this has always been working

For PyLoad i only get the text `unversioned API: requested URI not found` when trying to access its WebUI

I have a second instance of PyLoad not running through VPN, being mapped on a different port and running fine

So only the combination PyLoad through gluetun seems to make the WebUI of PyLoad being unreachable

I have no idea if it is related to Gluetun or to PyLoad but regarding other posts for other services i can only guess that this is something Gluetun does?

### Share your logs

```plain text
On WebUI: `unversioned API: requested URI not found`
```

### Share your configuration

```yml
version: "3"
services:
  gluetun_vpn:
    image: qmcgaw/gluetun:latest
    container_name: gluetun_vpn
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - WIREGUARD_ADDRESSES=XXXXXXXXXXXXXXXXXXXX
      - SERVER_COUNTRIES=XXXXXXXXXXXXXXXXXXXXXXX
      - VPN_ENDPOINT_PORT=XXXXXXXXXXXXXXXXXXXXXXXXX
    ports:
      - 5800:5800 # jDownloader
      - 5901:8000 # PyLoad

  jdownloader2_vpn:
    image: jlesage/jdownloader-2:latest
    privileged: true
    container_name: jdownloader2_vpn
    network_mode: service:gluetun_vpn
    #ports:
    #  - 5800:5800 # no forwarding in case of network_mode: container:x
    volumes:
      - /var/home/core/dvol/jdownloader2_config:/config:Z
      - type: volume
        source: nfs_downloads
        target: /output
        volume:
          nocopy: true
    restart: unless-stopped
  pyload_vpn:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload_vpn
    network_mode: service:gluetun_vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=XXXXXXXXXXXXX
    volumes:
      - /var/home/core/dvol/pyload_vpn_config:/config:Z
      - type: volume
        source: nfs_downloads
        target: /downloads
        volume:
          nocopy: true
    #ports:
      #- 5901:8000
      #- 9666:9666 #optional
    restart: unless-stopped
volumes:
  nfs_downloads:
    driver_opts:
      type: "nfs"
      o: "addr=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,nolock,soft,rw"
      device: ":XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
```
