### ISSUE TITLE
Bug: Container failing health check constantly with Mullvad WireGuard

### ISSUE THREAD

**Issue by tony-ze-yi** [qdm12/gluetun#1464]
### Is this urgent?

No

### Host OS

Ubuntu 22.04 LTS

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2023-03-01T14:10:28.105Z (commit ab5dbdc)

### What's the problem 🤔

Running with docker-compose, the container cannot connect to the internet. It'll give errors such as `2023-03-21T16:11:52Z ERROR [vpn] cannot get version information: Get "https://api.github.com/repos/qdm12/gluetun/commits": context canceled`, `gluetun         | 2023-03-21T16:11:54Z WARN [dns over tls] cannot update files: Get "https://www.internic.net/domain/named.root": dial tcp: lookup www.internic.net on 1.1.1.1:53: read udp 10.66.184.113:47803->1.1.1.1:53: i/o timeout`, and constant healthcheck messages in the format of `[healthcheck] program has been unhealthy for <duration>: restarting VPN`. 

I've tried allowing 51820 through firewall, switching to OpenVPN and allowing 1194, etc. None have worked. I've tried the minimal configuration in https://github.com/qdm12/gluetun/issues/1458, and that doesn't work either. 

### Share your logs

```plain text
https://0bin.net/paste/wunrIwJN#LstigsGN04fHavS8gJV68w6UCkAnxhT+zoBcTQvS+XJ
```

### Share your configuration

```yml
version: "3.7"
services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    # Added 8/10/22:
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 9091:9091/tcp  # qbitorrent
      - 51820:51820
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      #- HEALTH_TARGET_ADDRESS
      - VPN_SERVICE_PROVIDER=mullvad
      #- VPN_TYPE=openvpn
      - VPN_TYPE=wireguard
# Wireguard:
      - WIREGUARD_PRIVATE_KEY=<PK from mullvad config>
      - WIREGUARD_ADDRESSES=<IP>/32
      - SERVER_HOSTNAME=ca-mtr-wg-105
      - FIREWALL_VPN_INPUT_PORTS=56244
    restart: always

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/storage:/downloads # downloads ***downloads=storage***
      - ${ROOT}/config/transmission:/config # config files
    network_mode: service:gluetun
    restart: unless-stopped
```

**Comment by bnhf** [comment]
@tony-ze-yi 

Nothing is jumping out at me that's wrong with your configuration. You might want to bind a directory to /gluetun so that servers.json gets written outside the container for persistence -- but I don't think that's the issue. As a test, I connected to the the same Mullvad server you're trying to use (with Wireguard) and didn't have any problems.

A bit of an off-the-wall idea, but how about trying to connect using the linuxserver.io Wireguard container. That could tell you if there's something wrong with the key, address, your account, Docker or whatever  -- and would help us zero-in on whether this is something specific to Gluetun. It's a pretty stripped-down config, so not as many moving parts to consider.

I did this myself a few minutes ago to test the concept, and here's the compose. You'll want to grab the ca-mtr-wg-105.conf file you downloaded from Mullvad and change the name to wg0.conf. In my case I needed to remove both of the IPv6 addresses in the file. The directory you put it in needs to be bound to the container's /config directory.

```yml
version: '3.7'
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Mountain
    volumes:
      - /data/wireguard:/config
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```
If you connect successfully the log should look like this. And then, you can exec into the container and ping something like google.com to confirm. Also ```curl ifconfig.co``` should give you your exit node IP: 

```console
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
WireGuard: https://www.wireguard.com/donations/
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
Uname info: Linux 21d5c22xxxxx 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 aarch64 aarch64 GNU/Linux
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
**** As the wireguard module is already active you can remove the SYS_MODULE capability from your container run/compose. ****
**** Client mode selected. ****
[custom-init] No custom files found, skipping...
**** Disabling CoreDNS ****
Warning: `/config/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.65.xxx.xxx/32 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] iptables-restore -n
[ls.io-init] done.
```

So if you're game, give that a go and let us know the result.

**Comment by tony-ze-yi** [comment]
Hi, I've already tried the LSIO wireguard but as a sanity check I tried it again. It doesn't work for me either, so I am stumped as to what the root cause is. Here are my logs:
```
~/Documents/htpc-download-box ❯ docker exec wireguard sh -c 'curl https://ifconfig.co'                              05:35:07 PM
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0curl: (6) Could not resolve host: ifconfig.co
~/Documents/htpc-download-box ❯ docker-compose logs wireguard                                                  05:35:21 PM
Attaching to wireguard
wireguard       | [migrations] started
wireguard       | [migrations] no migrations found
wireguard       | ───────────────────────────────────────
wireguard       |
wireguard       |       ██╗     ███████╗██╗ ██████╗
wireguard       |       ██║     ██╔════╝██║██╔═══██╗
wireguard       |       ██║     ███████╗██║██║   ██║
wireguard       |       ██║     ╚════██║██║██║   ██║
wireguard       |       ███████╗███████║██║╚██████╔╝
wireguard       |       ╚══════╝╚══════╝╚═╝ ╚═════╝
wireguard       |
wireguard       |    Brought to you by linuxserver.io
wireguard       | ───────────────────────────────────────
wireguard       |
wireguard       | To support the app dev(s) visit:
wireguard       | WireGuard: https://www.wireguard.com/donations/
wireguard       |
wireguard       | To support LSIO projects visit:
wireguard       | https://www.linuxserver.io/donate/
wireguard       |
wireguard       | ───────────────────────────────────────
wireguard       | GID/UID
wireguard       | ───────────────────────────────────────
wireguard       |
wireguard       | User UID:    1000
wireguard       | User GID:    1000
wireguard       | ───────────────────────────────────────
wireguard       |
wireguard       | Uname info: Linux 0f678a8cc0b1 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
wireguard       | **** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
wireguard       | **** As the wireguard module is already active you can remove the SYS_MODULE capability from your container run/compose. ****
wireguard       | **** Client mode selected. ****
wireguard       | [custom-init] No custom files found, skipping...
wireguard       | **** Disabling CoreDNS ****
wireguard       | Warning: `/config/wg0.conf' is world accessible
wireguard       | [#] ip link add wg0 type wireguard
wireguard       | [#] wg setconf wg0 /dev/fd/63
wireguard       | [#] ip -4 address add 10.66.xxx.xxx/32 dev wg0
wireguard       | [#] ip link set mtu 1420 up dev wg0
wireguard       | [#] resolvconf -a wg0 -m 0 -x
wireguard       | [#] wg set wg0 fwmark 51820
wireguard       | [#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
wireguard       | [#] ip -4 rule add not fwmark 51820 table 51820
wireguard       | [#] ip -4 rule add table main suppress_prefixlength 0
wireguard       | [#] iptables-restore -n
wireguard       | [ls.io-init] done.
~/Documents/htpc-download-box ❯ docker exec wireguard sh -c 'curl https://ifconfig.co'                            05:36:06 PM
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0curl: (6) Could not resolve host: ifconfig.co
~/Documents/htpc-download-box ▶ docker exec wireguard curl ifconfig.co                                         05:37:44 PM
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0curl: (6) Could not resolve host: ifconfig.co
~/Documents/htpc-download-box ❯                                                                                 
```
And here is my config:
```
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Mountain
    volumes:
      - ${ROOT}/config/wireguard:/config
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```
Note `${ROOT}` is where all my other LSIO configs are stored, and the other LSIO containers I have work fine in connecting to the internet. eg. for the docker container:
```
~/Documents/htpc-download-box ❯ docker exec deluge sh -c 'curl https://ifconfig.co'                             47s 05:40:41 PM
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0<home IP>
100    15  100    15    0     0     91      0 --:--:-- --:--:-- --:--:--    91
~/Documents/htpc-download-box ❯    
```
As an additional sanity check, I generated a fresh mullvad wireguard config and still no dice. I'm not sure what to make of this.
