### ISSUE TITLE
Bug: vpn unlimited settings

### ISSUE THREAD

**Issue by ksurl** [qdm12/gluetun#1490]
### Is this urgent?

No

### Host OS

Debian 11

### CPU arch

x86_64

### VPN service provider

VPNUnlimited

### What are you using to run the container

docker-compose

### What is the version of Gluetun

3.32.0

### What's the problem 🤔

link-mtu and comp-lzo mismatch between client and server settings

### Share your logs

```plain text
WARN [openvpn] 'link-mtu' is used inconsistently, local='link-mtu 1601', remote='link-mtu 1602'
WARN [openvpn] 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
```

### Share your configuration

```yml
services:
  gluetun:
    image: qmcgaw/gluetun:v3.32.0
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./gluetun:/gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - DOT=off
      - OPENVPN_CIPHERS=aes-256-cbc
      - OPENVPN_AUTH=sha512
      - SERVER_COUNTRIES=$vpncountry
      - SERVER_CITIES=$vpncity
      - SERVER_HOSTNAMES=$vpnserver
      - VPN_SERVICE_PROVIDER=vpn unlimited
      - OPENVPN_USER=$ovpnuser
      - OPENVPN_PASSWORD=$ovpnpw
      - TZ=UTC
```
