### ISSUE TITLE
Bug: Creating custom healthcheck with wget results in 100s of zombie processes

### ISSUE THREAD

**Issue by mjolnir870** [qdm12/gluetun#1494]
### Is this urgent?

No

### Host OS

unRAID (Slackware 15.0+)

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version v3.32.0 built on 2022-10-31T10:37:32.104Z (commit 126804c)

### What's the problem 🤔

I started using [qdm12/deunhealth](https://github.com/qdm12/deunhealth) and a custom health check on a couple dozen gluetun containers to recreate them if a site (filejoker.net) is unreachable. I believe this is resulting in hundreds of zombie processes. My server was locking up with many `fork failed: resource temporarily unavailable` errors, and other docker containers and processes were randomly crashing due to OOM.

I just removed the health check and those zombie processes disappeared. Fingers crossed that my server is back to normal now.

Is there a proper way to write this health check so that these zombie processes don't spawn, or is this a bug? Not even sure if it's in gluetun or in deunhealth.

![image](https://user-images.githubusercontent.com/35158449/229268480-7f5bf73a-de22-4e33-bbd4-806044a15af8.png)

### Share your logs

```plain text
logs useless here, I think, since the container recreation is the problem
```

### Share your configuration

```yml
  deunhealth:
    container_name: deunhealth
    environment:
      LOG_LEVEL: debug
      TZ: America/Chicago
    image: qmcgaw/deunhealth:latest
    networks:
      default: null
    restart: unless-stopped
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      bind:
        create_host_path: true
  vpia1:
    cap_add:
    - NET_ADMIN
    container_name: vpia1
    environment:
      BLOCK_ADS: "off"
      BLOCK_MALICIOUS: "on"
      BLOCK_SURVEILLANCE: "off"
      DNS_UPDATE_PERIOD: "0"
      DOT: "on"
      HEALTH_TARGET_ADDRESS: 1.1.1.1
      HTTP_CONTROL_SERVER_ADDRESS: :8000
      HTTP_CONTROL_SERVER_LOG: "on"
      HTTPPROXY: "on"
      HTTPPROXY_LISTENING_ADDRESS: :1080
      HTTPPROXY_LOG: "off"
      HTTPPROXY_PASSWORD_SECRETFILE: /run/secrets/vpn_proxy_password
      HTTPPROXY_STEALTH: "off"
      HTTPPROXY_USER_SECRETFILE: /run/secrets/vpn_proxy_username
      OPENVPN_PASSWORD_SECRETFILE: /run/secrets/vpn_pia_password
      OPENVPN_USER_SECRETFILE: /run/secrets/vpn_pia_username
      PGID: "100"
      PUBLICIP_FILE: /gluetun/ip
      PUBLICIP_PERIOD: 12h
      PUID: "1000"
      SERVER_REGIONS: US East
      TZ: America/Chicago
      UPDATER_PERIOD: "0"
      VERSION_INFORMATION: "off"
      VPN_SERVICE_PROVIDER: private internet access
    healthcheck:
      test: wget -q --spider filejoker.net
      start_period: 25s
      interval: 5s
      timeout: 5s
      retries: 2
    image: qmcgaw/gluetun:v3
    labels:
      deunhealth.restart.on.unhealthy: "true"
    networks:
      t2_proxy: null
    ports:
    - mode: ingress
      host_ip: 192.168.1.17
      target: 1080
      published: "43051"
      protocol: tcp
    restart: unless-stopped
    secrets:
    - source: vpn_proxy_username
    - source: vpn_proxy_password
    - source: vpn_pia_username
    - source: vpn_pia_password
    tmpfs:
    - /tmp
    volumes:
    - type: bind
      source: /mnt/user/appdata/docker/containers/gluetun/vpia1
      target: /gluetun
      bind:
        create_host_path: true
    - type: bind
      source: /mnt/user/appdata/docker/containers/gluetun/servers.json
      target: /gluetun/servers.json
      bind:
        create_host_path: true
```
