### ISSUE TITLE
Cannot connect to VPN Unlimited 

### ISSUE THREAD

**Issue by jsrich1102** [qdm12/gluetun#1540]
### Is this urgent?

None

### Host OS

Docker in Synology

### CPU arch

None

### VPN service provider

VPNUnlimited

### What are you using to run the container

docker-compose

### What is the version of Gluetun

lastest

### What's the problem 🤔

I went into VPN Unlimited and generated a manual configuration in the portal. Used the client key and cert. I tried it with the portal, device, and global login and it still will not connect to VPN. not sure what else I can try to get it to work

### Share your logs

```plain text
2023-04-22T22:08:07-04:00 ERROR reading from files: OpenVPN: client key: extracting base64 encoded data from PEM content: cannot decode PEM encoded block


2023-04-22T22:04:16-04:00 ERROR reading from files: OpenVPN: client certificate: extracting base64 encoded data from PEM content: cannot decode PEM encoded block
```

### Share your configuration

```yml
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8112:8112 # port for deluge
      
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=vpn unlimited
      - VPN_TYPE=openvpn
      - OPENVPN_USER= Removed
      - OPENVPN_PASSWORD=Removed
      - SERVER_HOSTNAMES=ca-tr.vpnunlimitedapp.com
      - TZ=America/New_York
      - HTTPPROXY=on #change to off if you don't wish to enable
      - SHADOWSOCKS=on #change to off if you don't wish to enable
      - FIREWALL_OUTBOUND_SUBNETS=172.20.0.0/16,192.168.0.0/24 #change this in line with your subnet see note on guide.
    network_mode: Arr-Servers
    restart: unless-stopped
```
