### ISSUE TITLE
gluetun crashes on startup when refreshing servers.json private internet access 

### ISSUE THREAD

**Issue by jamie-steele** [qdm12/gluetun#1542]
UPDATE:

I just realized it did update the file correctly but seems to crash immediately afterwards and restarts into an endless cycle.

Hello,

I am having an issue trying to get gluetun to refresh the servers.json file for private internet access.

It seems to crash right away.

Here is my docker compose file

version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
      - 7878:7878/tcp
      - 8000:8000/tcp
      - 8080:8080/tcp
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8989:8989/tcp
      - 9117:9117/tcp
      - 9696:9696/tcp
    volumes:
      - /volume1/docker/gluetun:/gluetun
    command: update -enduser -providers "private internet access"
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - SERVER_HOSTNAMES=ca-toronto.privacy.network
      - TZ=America/Toronto
      - UPDATER_PERIOD=24h
volumes:
  volume1:

And here is a dump of the log unfortunately there is not much there to go on. 
![image](https://user-images.githubusercontent.com/16930634/233852056-2b74b4b9-0776-46ff-9768-9f34b049486a.png)

Thanks,
Jamie

**Comment by bnhf** [comment]
@jamie-steele 

It's running fine, it's your yaml that's the issue, as you have ```restart: unless-stopped``` in it.

Try a stripped down compose just for manually updating like this:
```yml
version: '3'
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun-update
    cap_add:
      - NET_ADMIN
    volumes:
      - /data/gluetun:/gluetun
    command: update -enduser -providers 'private internet access'
```
