### ISSUE TITLE
Feature request: Env variable to disable IPv6 auto-enable

### ISSUE THREAD

**Issue by buroa** [qdm12/gluetun#1563]
### What's the feature 🧐

Allow us to complete disable IPv6, instead of automatically checking if our system supports it.

https://github.com/qdm12/gluetun/blob/master/internal/netlink/ipv6.go#L9
https://github.com/qdm12/gluetun/blob/master/internal/provider/utils/wireguard.go#L12
https://github.com/qdm12/gluetun/blob/master/internal/wireguard/address.go#L14
https://github.com/qdm12/gluetun/blob/master/internal/configuration/sources/env/wireguard.go#L12

Something like a env variable that goes into the user settings. Looks like the wireguard is already checking that setting so as long as we can pass it as an override, this will work for anyone that has the same setup.

**Comment by qdm12** [comment]
Why do you need this? What's the use case?

**Comment by buroa** [comment]
@qdm12 If I use `mullvad` for example, it attempts to connect to a lot of IPv6-enabled wireguard servers -- but I don't actually have IPv6 enabled in my homelab -- so it shouldn't even attempt this.

**Comment by qdm12** [comment]
Ok that's interesting, maybe a better way to address this would be to fix the IPv6 detection mechanism 😉 

The mechanism right now is https://github.com/qdm12/private-internet-access-docker/blob/3100cc1e5ee7d6523cc02e1c874a271713c13395/internal/netlink/ipv6.go#L9 and it basically goes through the routes of each links, and if one route is IPv6, it assumes IPv6 is supported. What's the output of

```
docker run -it --rm alpine ip route
docker run -it --rm alpine ip -6 route
```

**Comment by buroa** [comment]
> ip -6 route

```
ip r && ip -6 route
default via 10.244.1.220 dev eth0 mtu 9000
10.244.1.220 dev eth0 scope link
fe80::/64 dev eth0 proto kernel metric 256 pref medium
```

**Comment by qdm12** [comment]
@qriff interesting points, I am thinking to add an ipv6 dummy route to test for ipv6 support, instead of checking existing routes for IPv6 source or destination.

Would you have any suggestion of what `ip6 route add ...` you would use to not affect existing routing tables (not a routing expert to be honest) 🤔

**Comment by samip5** [comment]
This also happens with airvpn as I have blocked IPv6 outbound, and it stil tries to connect via v6.

For reference:
```
# ip r && ip -6 r 
default via 10.244.4.77 dev eth0 mtu 1500 
10.0.0.0/8 via 10.244.4.77 dev eth0 
10.244.4.77 dev eth0 scope link 
172.16.2.0/24 dev vxlan0 proto kernel scope link src 172.16.2.1 
192.168.0.0/16 via 10.244.4.77 dev eth0 
fd7d:76ee:e68f:a993:16a9:9a73:9cd9:c35c dev wg0 proto kernel metric 256 pref medium
fddf:f7bc:9670:4::bd91 dev eth0 proto kernel metric 256 pref medium
fddf:f7bc:9670:4::c7a7 dev eth0 metric 1024 pref medium
fe80::/64 dev eth0 proto kernel metric 256 pref medium
fe80::/64 dev vxlan0 proto kernel metric 256 pref medium
default via fddf:f7bc:9670:4::c7a7 dev eth0 metric 1024 mtu 1500 pref medium

**Comment by TheColetrain** [comment]
![image](https://github.com/qdm12/gluetun/assets/8950046/d58696a5-f6e1-4ef2-aeeb-a0458758bec5)

**Comment by markcagatandavis** [comment]
Can we please have the ability to disable the ipv6 checks? I can't use the firewall and port forward at all because Synology the lame buggers won't update the ipv6 table... So many people are having this issue :( <3 

![image](https://github.com/user-attachments/assets/bac8c90c-066d-48d5-99f5-4d5fd72b0dc5)

**Comment by markcagatandavis** [comment]
custom.conf
```
# Disable IPv6
pull-filter ignore "route-ipv6"
pull-filter ignore "ifconfig-ipv6"
```

Custom docker network
`docker network create --subnet 172.19.0.0/16 mynet`

docker-compose.yml
```
version: '3.7'

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

x-common-variables: &common-variables
  TZ: ${TZ}
  PUID: ${PUID}
  PGID: ${PGID}
  UMASK: ${UMASK}

  gluetun-p2p:
    image: qmcgaw/gluetun:latest
    container_name: gluetun-p2p
    hostname: gluetun-p2p
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      <<: *common-variables
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: openvpn
      VPN_PORT_FORWARDING: on
      VPN_PORT_FORWARDING_PROVIDER: ${VPN_PORT_FORWARDING_PROVIDER}
      VPN_PORT_FORWARDING_LISTENING_PORT: ${VPN_P2P_PORT_FORWARDING_LISTENING_PORT}
      OPENVPN_USER: ${OPENVPN_USER}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      OPENVPN_CUSTOM_CONFIG: /gluetun/custom.conf
      OPENVPN_PROTOCOL: tcp
      FREE_ONLY: off
      FIREWALL_OUTBOUND_SUBNETS: 172.19.0.0/16,192.168.20.0/24
      FIREWALL_VPN_INPUT_PORTS: 6881
      FIREWALL_INPUT_PORTS: 6881
      BLOCK_MALICIOUS: on
      DOT_PRIVATE_ADDRESS: 127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - ${QBITTORRENT_WEBUI_PORT}:8080
      - ${QBITTORRENT_INCOMING_PORT}:6881
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    restart: unless-stopped
    volumes:
      - /volume1/docker/gluetun:/gluetun
      - /volume1/docker/gluetun/config/custom.conf:/gluetun/custom.conf:ro
    networks:
      - mynet

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun-p2p"
    environment:
      <<: *common-variables
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      WEBUI_PORT: ${QBITTORRENT_WEBUI_PORT}
      TORRENTING_PORT: ${QBITTORRENT_INCOMING_PORT}
    volumes:
      - /volume1/docker/qbittorrent/config:/config
      - /volume1/Media:/media
    depends_on:
      gluetun-p2p:
        condition: service_healthy
    restart: unless-stopped

  qbittorrent_natmap:
    image: ghcr.io/soxfor/qbittorrent-natmap:latest
    container_name: qbittorrent_natmap
    environment:
      <<: *common-variables
      TZ: ${TZ}
      QBITTORRENT_USER: ${QBITTORRENT_USER}
      QBITTORRENT_PASS: ${QBITTORRENT_PASSWORD}
      QBITTORRENT_PORT: 8080
      VPN_CT_NAME: gluetun-p2p
      VPN_GATEWAY: ${VPN_GATEWAY}
    depends_on:
      qbittorrent:
        condition: service_started
      gluetun-p2p:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
