### ISSUE TITLE
Bug: TLS key negotiation began failing

### ISSUE THREAD

**Issue by oxlade39** [qdm12/gluetun#1570]
### Is this urgent?

None

### Host OS

Ubuntu 20.04.6 LTS

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Latest

### What's the problem 🤔

I have started recieving TLS negotiation timeout errors. I pulled the very latest image and retried but still get the same issue. I also tried a few other regions but they also failed in the same way.

This configuration has previously worked for several months with no changes on my side.

### Share your logs

```plain text
pia                 | 2023-05-16T18:47:27Z WARN [openvpn] TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
pia                 | 🚒🚒🚒🚒🚒🚨🚨🚨🚨🚨🚨🚒🚒🚒🚒🚒
pia                 | That error usually happens because either:
pia                 | 
pia                 | 1. The VPN server IP address you are trying to connect to is no longer valid 🔌
pia                 |    Update your server information using https://github.com/qdm12/gluetun/wiki/Updating-Servers
pia                 | 
pia                 | 2. The VPN server crashed 💥, try changing your VPN servers filtering options such as SERVER_REGIONS
pia                 | 
pia                 | 3. Your Internet connection is not working 🤯, ensure it works
pia                 | 
pia                 | 4. Something else ➡️ https://github.com/qdm12/gluetun/issues/new/choose
pia                 | 
pia                 | 2023-05-16T18:47:27Z INFO [openvpn] TLS Error: TLS handshake failed
pia                 | 2023-05-16T18:47:27Z INFO [openvpn] SIGTERM received, sending exit notification to peer
pia                 | 2023-05-16T18:47:27Z INFO [openvpn] SIGTERM[soft,tls-error] received, process exiting
pia                 | 2023-05-16T18:47:27Z INFO [vpn] retrying in 15s
pia                 | 2023-05-16T18:47:27Z INFO [healthcheck] program has been unhealthy for 1m0s: restarting VPN (see https://github.com/qdm12/gluetun/wiki/Healthcheck)
^CERROR: Aborting
```

### Share your configuration

```yml
pia:
    image: qmcgaw/gluetun
    container_name: pia
����networks:
�����default:
����cap_add:
�����- NET_ADMIN
����volumes:
������- ./config/pia:/config
������- ./config/gluetun:/gluetun
����environment:
������- VPN_SERVICE_PROVIDER=private internet access
������- OPENVPN_USER=${PIA_USER}
������- OPENVPN_PASSWORD=${PIA_PASSWORD}
������- SERVER_REGIONS=Bosnia and Herzegovina
������- PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING=on
������- PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING_STATUS_FILE=/config/vpnportfw
������- PUBLICIP_FILE=/config/ip
������- HEALTH_VPN_DURATION_INITIAL=60s
����restart: unless-stopped
```

**Comment by oxlade39** [comment]
I don’t know why this was suddenly required but I had to remove the networks section and replace with
`network_mode: bridge`

For some reason all my docker containers lost access to the internet without this, despite it working before.

**Comment by oxlade39** [comment]
Although annoyingly that now means I can’t address the network from other containers by service name

**Comment by oxlade39** [comment]
This appears to be the magic config. I guess perhaps the defaults changed in a version of docker.

```
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1450"
      com.docker.network.bridge.default_bridge: "true"
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
      com.docker.network.bridge.name: "docker0"
      com.docker.network.driver.mtu: "1500"
```
