### ISSUE TITLE
Bug: All containers connected to Gluetun stop working once Gluetun restarts/ or update via watchtower

### ISSUE THREAD

**Issue by rayne9963** [qdm12/gluetun#1587]
### Is this urgent?

No

### Host OS

Synology Docker

### CPU arch

None

### VPN service provider

VPNUnlimited

### What are you using to run the container

docker-compose

### What is the version of Gluetun

v3.34.0

### What's the problem 🤔

All containers connected to Gluetun stop working once Gluetun restarts/ or update via watchtower.

I had the containers separated at one point. Then combined them in one STACK

If I restart Gluetun then the connected containers stop working, when I manually restart the containers they work fine. 

I removed the depends_on line as it still has issues after removal and the containers still work without this line as they are all in one docker compose yaml syntax.

I also removed gluten from watchtower updates for now until I can get this resolved.

### Share your logs

```plain text
Point me were to pull the logs if needed.
I believe this can be tested, container logs clear once I restart, which logs will be needed to troubleshoot this issue?
```

### Share your configuration

```yml
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      #- 8388:8388/tcp #Shadowsocks
      #- 8388:8388/udp #Shadowsocks
      - 8888:8888/tcp  #HTTP proxy
      - 8383:8383      #qbittorrent
      - 6881:6881      #qbittorrent
      - 6881:6881/udp  #qbittorrent
      - 8989:8989      #sonarr
      - 7878:7878      #radarr
      - 8085:8080      #sabnzb
      - 9090:9090      #sabnzb
      - 5563:5563      #sabnzb
      - 563:563        #sabnzb
      - 5100:5076      #nzbhydra2
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      - PUID=1030
      - PGID=101
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=vpn unlimited
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=rayne9963@gmail.com
      - OPENVPN_PASSWORD=sVyokJ1ldPgR
      - SERVER_COUNTRIES=Canada
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      # - WIREGUARD_ADDRESSES=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=America/New_York
      # Server list updater. See https://github.com/qdm12/gluetun/wiki/Updating-Servers#periodic-update
      - UPDATER_PERIOD=24h
      - UPDATER_VPN_SERVICE_PROVIDERS=VPN Unlimited
      - FIREWALL_OUTBOUND_SUBNETS=10.0.1.0/24
    labels:
      - com.centurylinklabs.watchtower.enable=false

###############

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1030
      - PGID=101
      - TZ=America/New_York
      - HEALTH_CHECK_AMOUNT=10
      - HEALTH_CHECK_INTERVAL=300
      - HEALTH_CHECK_HOST=one.one.one.one
      - WEBUI_PORT=8383
    volumes:
      - /volume1/docker/qbittorrent/config:/config
      - /volume1/docker/sabnzbd/downloads:/downloads
    restart: unless-stopped
    network_mode: service:gluetun # run on the vpn network
 
 
###############

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1030
      - PGID=101
      - TZ=America/New_York
    volumes:
      - /volume1/docker/sonarrv3/config:/config
      - /volume1/media/TV:/tv
      - /volume1/media/TV:/media
      - /volume1/media/Anime:/anime   
      - /volume1/docker/sabnzbd/downloads:/downloads
  #ports:
     #- 8989:8989
    network_mode: service:gluetun # run on the vpn network
    restart: unless-stopped
   
###############

  radarr:
     image: ghcr.io/linuxserver/radarr
     container_name: radarr
     environment:
      - PUID=1030
      - PGID=101
      - TZ=America/New_York
      - UMASK_SET=022 #optional
     volumes:
      - /volume1/docker/radarr/config:/config
      - /volume1/media/Movies:/movies
      - /volume1/docker/sabnzbd/downloads:/downloads
    #ports:
     #- 7878:7878
     network_mode: service:gluetun # run on the vpn network
     restart: unless-stopped

###############

  nzbhydra2:
     image: ghcr.io/linuxserver/nzbhydra2
     container_name: nzbhydra2
     environment:
      - PUID=1030
      - PGID=101
      - TZ=America/New_York
     volumes:
      - /volume1/docker/hydra2/config:/config
      - /volume1/docker/hydra2/downloads:/downloads
    #ports:
     #- 5100:5076
     network_mode: service:gluetun # run on the vpn network
     restart: unless-stopped
   
###############

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1030
      - PGID=101
      - TZ=America/New_York
    volumes:
      - /volume1/docker/sabnzbd/config:/config
      - /volume1/docker/sabnzbd/downloads:/downloads
      - /volume1/docker/sabnzbd/downloads/idownloads:/incomplete-downloads #optional
      - /volume1/media/TV:/tv
      - /volume1/media/Movies:/movies
   #ports:
     #- 8085:8080
     #- 9191:9090
    network_mode: service:gluetun # run on the vpn network
    restart: unless-stopped
```
