### ISSUE TITLE
Bug: ERROR getting assigned IP of eth0: IP address not found for interface: interface eth0 in 1 addresses

### ISSUE THREAD

**Issue by teejo75** [qdm12/gluetun#1588]
### Is this urgent?

No

### Host OS

Debian Bullseye

### CPU arch

x86_64

### VPN service provider

AirVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2023-05-22T06:07:02.257Z (commit eed62fd)

### What's the problem 🤔

Container won't start.
If I change tag to v3.34.0 then container starts.

### Share your logs

```plain text
gluetun  | ========================================
gluetun  | ========================================
gluetun  | =============== gluetun ================
gluetun  | ========================================
gluetun  | =========== Made with ❤️ by ============
gluetun  | ======= https://github.com/qdm12 =======
gluetun  | ========================================
gluetun  | ========================================
gluetun  | 
gluetun  | Running version latest built on 2023-05-22T06:07:02.257Z (commit eed62fd)
gluetun  | 
gluetun  | 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
gluetun  | 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
gluetun  | ✨ New feature? https://github.com/qdm12/gluetun/issues/new
gluetun  | ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
gluetun  | 💻 Email? quentin.mcgaw@gmail.com
gluetun  | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
gluetun  | 2023-05-22T16:46:01+10:00 ERROR getting assigned IP of eth0: IP address not found for interface: interface eth0 in 1 addresses
gluetun  | 2023-05-22T16:46:01+10:00 INFO Shutdown successful
```

### Share your configuration

```yml
gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8080:8080 # QBT Web UI
    volumes:
      - ./gluetun-config:/gluetun
    environment:
      # Timezone for accurate log times
      - TZ=xxx
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=xxx
      - WIREGUARD_PRESHARED_KEY=xxx
      - WIREGUARD_ADDRESSES=xxx
      - SERVER_REGIONS=xxx
    restart: unless-stopped
```
