### ISSUE TITLE
Bug: ERROR getting assigned IP of eth0: IP address not found for interface: interface eth0 in 1 addresses

### ISSUE THREAD

**Issue by driiftkiing** [qdm12/gluetun#1589]
### Is this urgent?

Yes

### Host OS

Ubuntu Jammy

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2023-05-22T06:07:02.257Z (commit eed62fd)

### What's the problem 🤔

Container not starting

### Share your logs

```plain text
Running version latest built on 2023-05-22T06:07:02.257Z (commit eed62fd)

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2023-05-22T08:28:02+02:00 ERROR getting assigned IP of eth0: IP address not found for interface: interface eth0 in 1 addresses
2023-05-22T08:28:02+02:00 INFO Shutdown successful
```

### Share your configuration

```yml
version: "3.9"


x-base-data: &common
  environment: &docker-base-environment
    PUID: 1000
    PGID: 1000
  restart: unless-stopped

services:
  gluetun:
    <<: *common
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - ./gluetun:/gluetun
    env_file:
      - ./.gluetun.env
networks:
  default:
    external: true
    name: gluetun-network
```
