### ISSUE TITLE
Bug: Mullvad SERVER_COUNTRIES or SERVER_CITIES value errors

### ISSUE THREAD

**Issue by karserasl** [qdm12/gluetun#1599]
### Is this urgent?

No

### Host OS

Arch

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2023-05-25T12:12:44.932Z (commit a43973c)

### What's the problem 🤔

Latest commit i think it uses only lower case server cities/countries, which breaks the check.

### Share your logs

```plain text
gluetun  | 2023-05-25T12:55:51.869880339Z ========================================
gluetun  | 2023-05-25T12:55:51.869904715Z ========================================
gluetun  | 2023-05-25T12:55:51.869908143Z =============== gluetun ================
gluetun  | 2023-05-25T12:55:51.869910612Z ========================================
gluetun  | 2023-05-25T12:55:51.869912752Z =========== Made with ❤️ by ============
gluetun  | 2023-05-25T12:55:51.869915608Z ======= https://github.com/qdm12 =======
gluetun  | 2023-05-25T12:55:51.869917769Z ========================================
gluetun  | 2023-05-25T12:55:51.869920184Z ========================================
gluetun  | 2023-05-25T12:55:51.869922432Z 
gluetun  | 2023-05-25T12:55:51.869924535Z Running version latest built on 2023-05-25T12:12:44.932Z (commit a43973c)
gluetun  | 2023-05-25T12:55:51.869926755Z 
gluetun  | 2023-05-25T12:55:51.869928772Z 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
gluetun  | 2023-05-25T12:55:51.869931189Z 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
gluetun  | 2023-05-25T12:55:51.869933540Z ✨ New feature? https://github.com/qdm12/gluetun/issues/new
gluetun  | 2023-05-25T12:55:51.869935953Z ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
gluetun  | 2023-05-25T12:55:51.869938262Z 💻 Email? quentin.mcgaw@gmail.com
gluetun  | 2023-05-25T12:55:51.869940643Z 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
gluetun  | 2023-05-25T12:55:51.870424611Z 2023-05-25T15:55:51+03:00 INFO [routing] default route found: interface eth0, gateway 192.168.90.1, assigned IP 192.168.90.33 and family v4
gluetun  | 2023-05-25T12:55:51.870548700Z 2023-05-25T15:55:51+03:00 INFO [routing] local ethernet link found: eth0
gluetun  | 2023-05-25T12:55:51.870557879Z 2023-05-25T15:55:51+03:00 INFO [routing] local ipnet found: 192.168.90.0/24
gluetun  | 2023-05-25T12:55:51.916831926Z 2023-05-25T15:55:51+03:00 INFO [firewall] enabling...
gluetun  | 2023-05-25T12:55:51.916849157Z 2023-05-25T15:55:51+03:00 DEBUG [firewall] iptables --policy INPUT DROP
gluetun  | 2023-05-25T12:55:51.917867460Z 2023-05-25T15:55:51+03:00 DEBUG [firewall] iptables --policy OUTPUT DROP
gluetun  | 2023-05-25T12:55:51.918641851Z 2023-05-25T15:55:51+03:00 DEBUG [firewall] iptables --policy FORWARD DROP
gluetun  | 2023-05-25T12:55:51.919338447Z 2023-05-25T15:55:51+03:00 DEBUG [firewall] ip6tables-nft --policy INPUT DROP
gluetun  | 2023-05-25T12:55:51.953516611Z 2023-05-25T15:55:51+03:00 DEBUG [firewall] ip6tables-nft --policy OUTPUT DROP
gluetun  | 2023-05-25T12:55:51.954473145Z 2023-05-25T15:55:51+03:00 DEBUG [firewall] ip6tables-nft --policy FORWARD DROP
gluetun  | 2023-05-25T12:55:51.980448145Z 2023-05-25T15:55:51+03:00 DEBUG [firewall] iptables --append INPUT -i lo -j ACCEPT
gluetun  | 2023-05-25T12:55:51.981851706Z 2023-05-25T15:55:51+03:00 DEBUG [firewall] ip6tables-nft --append INPUT -i lo -j ACCEPT
gluetun  | 2023-05-25T12:55:51.983414037Z 2023-05-25T15:55:51+03:00 DEBUG [firewall] iptables --append OUTPUT -o lo -j ACCEPT
gluetun  | 2023-05-25T12:55:51.984612561Z 2023-05-25T15:55:51+03:00 DEBUG [firewall] ip6tables-nft --append OUTPUT -o lo -j ACCEPT
gluetun  | 2023-05-25T12:55:51.986016967Z 2023-05-25T15:55:51+03:00 DEBUG [firewall] iptables --append OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
gluetun  | 2023-05-25T12:55:51.987423192Z 2023-05-25T15:55:51+03:00 DEBUG [firewall] ip6tables-nft --append OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
gluetun  | 2023-05-25T12:55:51.997788330Z 2023-05-25T15:55:51+03:00 DEBUG [firewall] iptables --append INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
gluetun  | 2023-05-25T12:55:52.000129146Z 2023-05-25T15:55:51+03:00 DEBUG [firewall] ip6tables-nft --append INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
gluetun  | 2023-05-25T12:55:52.003772777Z 2023-05-25T15:55:52+03:00 DEBUG [firewall] iptables --append OUTPUT -o eth0 -s 192.168.90.33 -d 192.168.90.0/24 -j ACCEPT
gluetun  | 2023-05-25T12:55:52.005029054Z 2023-05-25T15:55:52+03:00 DEBUG [firewall] ip6tables-nft --append OUTPUT -o eth0 -d ff02::1:ff/104 -j ACCEPT
gluetun  | 2023-05-25T12:55:52.006037235Z 2023-05-25T15:55:52+03:00 DEBUG [firewall] iptables --append INPUT -i eth0 -d 192.168.90.0/24 -j ACCEPT
gluetun  | 2023-05-25T12:55:52.007088887Z 2023-05-25T15:55:52+03:00 INFO [firewall] enabled successfully
gluetun  | 2023-05-25T12:55:52.265745021Z 2023-05-25T15:55:52+03:00 INFO [storage] merging by most recent 13056 hardcoded servers and 13030 servers read from /gluetun/servers.json
gluetun  | 2023-05-25T12:55:52.267396017Z 2023-05-25T15:55:52+03:00 INFO [storage] Using mullvad servers from file which are 62 days more recent
gluetun  | 2023-05-25T12:55:52.321164701Z 2023-05-25T15:55:52+03:00 DEBUG [netlink] IPv6 is not supported after searching 2 links and 0 routes
gluetun  | 2023-05-25T12:55:52.321715969Z 2023-05-25T15:55:52+03:00 ERROR VPN settings: provider settings: server selection: for VPN service provider mullvad: the city specified is not valid: value is not one of the possible choices: value marseille, choices available are Adelaide, Amsterdam, Ashburn VA, Athens, Atlanta GA, Auckland, Belgrade, Bogota, Bratislava, Brisbane, Brussels, Bucharest, Budapest, Calgary, Chicago IL, Chisinau, Copenhagen, Dallas TX, Denver CO, Dubai, Dublin, Dusseldorf, Frankfurt, Gothenburg, Helsinki, Hong Kong, Houston TX, Johannesburg, Kyiv, Lisbon, London, Los Angeles CA, Luxembourg, Madrid, Malmö, Manchester, Marseille, Melbourne, Miami FL, Milan, Montreal, New York NY, Osaka, Oslo, Paris, Perth, Phoenix AZ, Prague, Raleigh NC, Riga, Salt Lake City UT, San Jose CA, Sao Paulo, Seattle WA, Secaucus NJ, Singapore, Skopje, Sofia, Stavanger, Stockholm, Sydney, Tallinn, Tel Aviv, Tirana, Tokyo, Toronto, Vancouver, Vienna, Warsaw, Zagreb, Zurich
gluetun  | 2023-05-25T12:55:52.321730358Z 2023-05-25T15:55:52+03:00 INFO Shutdown successful
gluetun exited with code 0
```

### Share your configuration

```yml
gluetun:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    image: qmcgaw/gluetun
    container_name: gluetun
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - $QBITTORRENT_PORT:8185 # Exposing qBittorrent through Docker Host LAN IP
      - $GLUETUN_FOR_PORT1:$GLUETUN_FOR_PORT1/tcp
      - $GLUETUN_FOR_PORT1:$GLUETUN_FOR_PORT1/udp
      - $GLUETUN_FOR_PORT2:$GLUETUN_FOR_PORT2/tcp
      - $GLUETUN_FOR_PORT2:$GLUETUN_FOR_PORT2/udp
      - 8079:8079
    volumes:
      - $DOCKERDIR/appdata/gluetun:/gluetun
    environment:
      <<: *default-tz-puid-pgid
      VPN_SERVICE_PROVIDER: mullvad
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: $GLUETUN_PRIV_KEY_MUL
      WIREGUARD_ADDRESSES: $GLUETUN_ADDRESS_MUL
      SERVER_COUNTRIES: "France"
      SERVER_CITIES: "Marseille"
      FIREWALL_VPN_INPUT_PORTS: $GLUETUN_FOR_PORT1,$GLUETUN_FOR_PORT2
      LOG_LEVEL: debug
      UPDATER_PERIOD: 24h
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth Bypass
      - "traefik.http.routers.gluetun-qbitorrent-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.gluetun-qbitorrent-rtr-bypass.rule=Host(`qbit.$DOMAINNAME1`) || Host(`qbit.$DOMAINNAME2`) && PathPrefix(`/api/v2`)" # qBittorrent
      - "traefik.http.routers.gluetun-qbitorrent-rtr-bypass.priority=100"
      ## HTTP Routers Auth
      - "traefik.http.routers.gluetun-qbitorrent-rtr.entrypoints=https"
      - "traefik.http.routers.gluetun-qbitorrent-rtr.rule=Host(`qbit.$DOMAINNAME2`)" # qBittorrent
      - "traefik.http.routers.gluetun-qbitorrent-rtr.priority=99"
      ## Middlewares
      - "traefik.http.routers.gluetun-qbitorrent-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.gluetun-qbitorrent-rtr.middlewares=chain-authelia@file" # qBittorrent
      ## HTTP Services
      - "traefik.http.routers.gluetun-qbitorrent-rtr.service=gluetun-qbit-svc"
      - "traefik.http.routers.gluetun-qbitorrent-rtr-bypass.service=gluetun-qbit-svc" # qBittorrent
      - "traefik.http.services.gluetun-qbit-svc.loadbalancer.server.port=8185" # qBittorrent
      #### SMOKEPING
      ## HTTP Routers
      - "traefik.http.routers.smokeping-rtr.entrypoints=https"
      - "traefik.http.routers.smokeping-rtr.rule=Host(`smokeping.$DOMAINNAME1`)"
      ## Middlewares
      - "traefik.http.routers.smokeping-rtr.middlewares=chain-local@file"
      ## HTTP Services
      - "traefik.http.routers.smokeping-rtr.service=smokeping-svc"
      - "traefik.http.services.smokeping-svc.loadbalancer.server.port=8079"
    # command: update -enduser -providers mullvad
    healthcheck:
      interval: 10s
      timeout: 15s
      retries: 3
      start_period: 30s
```
