### ISSUE TITLE
Bug: fast locally but slow remotely

### ISSUE THREAD

**Issue by KaKi87** [qdm12/gluetun#1610]
### Is this urgent?

Yes

### Host OS

Debian Bullseye

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2023-05-10T09:05:10.273Z (commit 4bb77eb)

### What's the problem 🤔

Downloading (e.g. using `curl` or `aria2c`) through the HTTP proxy is fast locally but slow remotely :

|     | Without proxy | With proxy |
| --- | --- | --- |
| Local | 5 MB/s | 10 MB/s |
| Remote | 80 MB/s | 1 MB/s |

Since remote speed without proxy is greater than local speed with proxy, I'd expect that remote with proxy would be at least as fast as local with proxy.

### Share your logs

```plain text
No output during speedtest (except `write: broken pipe` when interrupting, which I assume is normal).
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    restart: always
    image: qmcgaw/gluetun
    # container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - <port>:8888/tcp # HTTP proxy
    volumes:
      - <path>:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=<user>
      - OPENVPN_PASSWORD=<pass>
      - SERVER_REGIONS=France
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      # - WIREGUARD_ADDRESSES=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=Europe/Paris
      # Server list updater. See https://github.com/qdm12/gluetun/wiki/Updating-Servers#periodic-update
      - UPDATER_PERIOD=24h
      - UPDATER_VPN_SERVICE_PROVIDERS=nordvpn
      - HTTPPROXY=on
      - HTTPPROXY_USER=<user>
      - HTTPPROXY_PASSWORD=<pass>
      - HTTPPROXY_STEALTH=on


---

Thanks
```
