### ISSUE TITLE
Bug: ProtonVpn no longer works

### ISSUE THREAD

**Issue by KleinByte** [qdm12/gluetun#1624]
### Is this urgent?

Yes

### Host OS

Docker / latest

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

I pulled the latest version as of 2023-05-29 , I reverted back so I cant paste this line.

### What's the problem 🤔

No matter what, gluetun fails to authenticate with protonvpn . I tried debugging but it looks to be a regression issue.

I even reset my protonvpn openvpn user credentials and tried the new ones, that didnt work. I also tried using different country regions. But that didnt work.

### Share your logs

```plain text
The logs just showed failed to authenticate with X server.
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - traefik-proxy
    healthcheck:
      interval: 5s
      timeout: 20s
      start_period: 10s
      retries: 3
    restart: always   
    volumes:
      - /mnt/J/Services/Gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=redacted
      - OPENVPN_PASSWORD=redacted
      - SERVER_COUNTRIES=Netherlands
      - PGID=100
      - PUID=1000
```
