### ISSUE TITLE
Bug: Lowering MTU drastically improves the Wireguard upload bandwidth

### ISSUE THREAD

**Issue by invernizzi** [qdm12/gluetun#1650]
### Is this urgent?

None

### CPU arch

x86_64

### VPN service provider

AirVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

v3.34.3

### What's the problem 🤔

Hello! Thanks for the wonderful project. 

I’ve noticed that my upload across a custom site-to-site Wireguard connection was pretty bad, so I’ve replicated the issue on two commercial VPNs: Mullvad and AirVpn.
After a bit of investigation, I've identified the culprit: the MTU is a smidge too high. Lowering it slightly (1420 -> 1400) solves the issue.

How to replicate:
 - Start a wireguard vpn container
 - Run the following script (where $1 is the name of the container). It runs a speed test, lowers the mtu, and runs the same speed test.
```
# Install speedtest-cli.
docker-compose exec $1  /bin/sh -c "apk add speedtest-cli" > /dev/null
# Test with MTU=1420 (the default).
docker-compose exec $1  /bin/sh -c "speedtest-cli"
# Lower the MTU.
echo "Lowering MTU"
docker-compose exec $1  /bin/sh -c "ip link set dev tun0  mtu 1400"
# Test again.
docker-compose exec $1  /bin/sh -c "speedtest-cli"
```

The output I get:
- Airvpn: upload went from 0.36 Mbit/s to 69.71 Mbit/s
```
Retrieving speedtest.net configuration...
Testing from M247 Ltd (185.156.175.171)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by teliko GmbH (Limburg) [335.16 km]: 62.993 ms
Testing download speed................................................................................
Download: 185.52 Mbit/s
Testing upload speed......................................................................................................
Upload: 0.36 Mbit/s
Lowering MTU
Retrieving speedtest.net configuration...
Testing from M247 Ltd (185.156.175.171)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by KEVAG Telekom GmbH (Koblenz) [335.53 km]: 45.062 ms
Testing download speed................................................................................
Download: 249.50 Mbit/s
Testing upload speed......................................................................................................
Upload: 69.71 Mbit/s
```
- Mullvad: upload goes from from 0.21 Mbit/s  to 86.61 Mbit/s
```
Retrieving speedtest.net configuration...
Testing from 31173 Services AB (45.83.220.212)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by TDC Group (Copenhagen) [27.97 km]: 63.497 ms
Testing download speed................................................................................
Download: 113.53 Mbit/s
Testing upload speed......................................................................................................
Upload: 0.21 Mbit/s
Lowering MTU
Retrieving speedtest.net configuration...
Testing from 31173 Services AB (45.83.220.212)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Bahnhof AB (Malmo) [3.50 km]: 35.916 ms
Testing download speed................................................................................
Download: 143.11 Mbit/s
Testing upload speed......................................................................................................
Upload: 86.61 Mbit/s
```

This is likely due to packet fragmentation - I'm happy to confirm that through tcpdump/wireshark if needed.

Once you've confirmed this behavior, is it possible to either:
-  lower the default MTU
- provide a mechanism to set it (e.g., env variable `MTU=1400`)
?

Thanks for the attention and the great project!

### Share your logs

```plain text
N/A
```

### Share your configuration

```yml
vpnairvpn:
    image: qmcgaw/gluetun:v3
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_PRESHARED_KEY=
      - WIREGUARD_ADDRESSES=
      - SERVER_COUNTRIES=Switzerland


  vpnmullvad:
    image: qmcgaw/gluetun:v3
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_PRESHARED_KEY=
      - WIREGUARD_ADDRESSES=
      - SERVER_CITIES=Malmö
```
