### ISSUE TITLE
Bug: ERROR getting assigned IP of eth0: IP address not found for interface: interface eth0 in 1 addresses

### ISSUE THREAD

**Issue by LuanTD** [qdm12/gluetun#1664]
### Is this urgent?

No

### Host OS

DSM 7.1.1

### CPU arch

None

### VPN service provider

Custom

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2023-06-08T09:55:12.339Z (commit 2ec9293)

### What's the problem 🤔

Container won't start, despite pulling the latest image which should have fixed the issue as mentioned in https://github.com/qdm12/gluetun/issues/1588 and discussed in https://github.com/qdm12/gluetun/issues/1591
Reverting back to 3.34.1 works fine
Custom wireguard VPN provider via protonvpn

### Share your logs

```plain text
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================

Running version latest built on 2023-06-08T09:55:12.339Z (commit 2ec9293)

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2023-06-08T15:09:15Z INFO [routing] default route found: interface eth0, gateway 172.20.0.1, assigned IP 172.20.0.2 and family v4
2023-06-08T15:09:15Z ERROR getting assigned IP of lo: IP address not found for interface: interface lo in 1 addresses
2023-06-08T15:09:15Z INFO Shutdown successful
```

### Share your configuration

```yml
gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8090:8090 # port for webui
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_PUBLIC_KEY=myPublicKey
      - WIREGUARD_PRIVATE_KEY=myPrivateKey
      - VPN_ENDPOINT_IP=XXX.XX.XX.XX
      - VPN_ENDPOINT_PORT=XXXX
      - WIREGUARD_ADDRESSES=X.X.X.X/XX
      - TZ=Continent/City
    restart: unless-stopped
```
