### ISSUE TITLE
Bug: ERROR default route not found: in 9 route(s)

### ISSUE THREAD

**Issue by Robin-Sch** [qdm12/gluetun#1671]
### Is this urgent?

No

### Host OS

Debian bullseye

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2023-06-08T19:54:40.981Z (commit 412921f)

### What's the problem 🤔

Since the new update, my gluetun container doesn't start anymore and throws the error `default route not found: in 9 route(s)`. It was working fine before.

### Share your logs

```plain text
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================
Running version latest built on 2023-06-08T19:54:40.981Z (commit 412921f)
🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2023-06-09T13:37:41Z ERROR default route not found: in 9 route(s)
2023-06-09T13:37:41Z INFO Shutdown successful
protonvpn exited with code 0
```

### Share your configuration

```yml
version: "3"

services:
        protonvpn:
                container_name: protonvpn
                image: qmcgaw/gluetun
                restart: always
                cap_add:
                        - NET_ADMIN
                environment:
                        - VPN_SERVICE_PROVIDER=protonvpn
                        - OPENVPN_USER=xxx
                        - OPENVPN_PASSWORD=xxx
                        - SERVER_COUNTRIES=xxx
                        - HTTPPROXY=on
                        - HTTPPROXY_STEALTH=on
                        - HTTPPROXY_LOG=on
                volumes:
                        - gluetun:/gluetun
                ports:
                        - 8888:8888/tcp # HTTP proxy
                dns:
                        - 1.1.1.1

volumes:
        gluetun: {}
```
