### ISSUE TITLE
Bug: vyprvpn cr1.vyprvpn.com doesn't resolve properly. 

### ISSUE THREAD

**Issue by whitethorn** [qdm12/gluetun#1733]
### Is this urgent?

No

### Host OS

Debian bullseye

### CPU arch

x86_64

### VPN service provider

VyprVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

2023-07-06T07:13:35.417Z (commit 919b55c)

### What's the problem 🤔

VPN connection failed. 

Hardcoded IP in servers.json doesn't match ping : 

"vpn": "openvpn",
        "region": "Costa Rica",
        "hostname": "cr1.vyprvpn.com",
        "udp": true,
        "ips": [
          "**209.99.109.22**"

Currently cr1.vyprvpn.com : 216.168.16.22

### Share your logs

```plain text
gluetun-gluetun-1  | 2023-07-07T15:35:37Z INFO [routing] default route found: interface eth0, gateway 192.168.64.1, assigned IP 192.168.64.2 and family v4
gluetun-gluetun-1  | 2023-07-07T15:35:37Z INFO [routing] adding route for 0.0.0.0/0
gluetun-gluetun-1  | 2023-07-07T15:35:37Z INFO [firewall] setting allowed subnets...
gluetun-gluetun-1  | 2023-07-07T15:35:37Z INFO [routing] default route found: interface eth0, gateway 192.168.64.1, assigned IP 192.168.64.2 and family v4
gluetun-gluetun-1  | 2023-07-07T15:35:37Z INFO [dns over tls] using plaintext DNS at address 1.1.1.1
gluetun-gluetun-1  | 2023-07-07T15:35:37Z INFO [http server] http server listening on [::]:8000
gluetun-gluetun-1  | 2023-07-07T15:35:37Z INFO [healthcheck] listening on 127.0.0.1:9999
gluetun-gluetun-1  | 2023-07-07T15:35:37Z INFO [firewall] allowing VPN connection...
gluetun-gluetun-1  | 2023-07-07T15:35:37Z WARN [openvpn] Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
gluetun-gluetun-1  | 2023-07-07T15:35:37Z INFO [openvpn] OpenVPN 2.5.8 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov  2 2022
gluetun-gluetun-1  | 2023-07-07T15:35:37Z INFO [openvpn] library versions: OpenSSL 3.1.1 30 May 2023, LZO 2.10
gluetun-gluetun-1  | 2023-07-07T15:35:37Z INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]209.99.109.22:443
gluetun-gluetun-1  | 2023-07-07T15:35:37Z INFO [openvpn] UDP link local: (not bound)
gluetun-gluetun-1  | 2023-07-07T15:35:37Z INFO [openvpn] UDP link remote: [AF_INET]209.99.109.22:443
gluetun-gluetun-1  | 2023-07-07T15:35:43Z INFO [healthcheck] program has been unhealthy for 6s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
gluetun-gluetun-1  | 2023-07-07T15:35:43Z INFO [vpn] stopping
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
      - 8082:8081
    volumes:
      - ./config/gluetun:/config
    environment:
      - VPN_SERVICE_PROVIDER=vyprvpn
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - SERVER_HOSTNAMES=cr1.vyprvpn.com
    restart: unless-stopped
```
