### ISSUE TITLE
Bug: Transmission not downloading anything

### ISSUE THREAD

**Issue by varac** [qdm12/gluetun#1831]
### Is this urgent?

Yes

### Host OS

Debian Bookworm / K3s v1.27.4+k3s1

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

Kubernetes

### What is the version of Gluetun

Self-built image from commit 1ac031e (HEAD of today)

### What's the problem 🤔

Transmission can't download anything, I tried with a Ubuntu 23.04 torrent:

* Trackers can be reached, the number of seeders/leachers is shown
* Yet no download happens
* Port-forwarding works, see [my comment on #1488](https://github.com/qdm12/gluetun/issues/1488#issuecomment-1698799937)

I also tried Deluge with the same outcome.
Any help would be appreciated !

### Share your logs

```plain text
See https://dpaste.com//A6TZV3S8P
```

### Share your configuration

```yml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: media
spec:
  releaseName: transmission
  chart:
    spec:
      chart: transmission
      version: 16.1.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 1h
  valuesFrom:
    - kind: Secret
      name: addon-vpn
  values:
    TZ: Europe/Berlin
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                TRANSMISSION__DOWNLOAD_DIR: /media/transmission/complete
                TRANSMISSION__INCOMPLETE_DIR: /media/transmission/incomplete
                
                TRANSMISSION__PEX_ENABLED: "false"
                TRANSMISSION__DHT_ENABLED: "false"
                TRANSMISSION__UTP_ENABLED: "false"
                TRANSMISSION__MESSAGE_LEVEL: "5"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: transmission.example.org
            paths:
              - path: /
    persistence:
      config:
        enabled: true
        mountPath: "/config"
        existingClaim: varac-config
        subPath: transmission
        skipuninstall: true
      media:
        enabled: true
        mountPath: "/media"
        storageClass: smb
        existingClaim: varac-media
        skipuninstall: true
    portal:
      open:
        enabled: false
    gluetunImage:
      repository: registry.0xacab.org/varac-projects/images/gluetun
      tag: 1ac031e78c
    addons:
      vpn:
        type: gluetun
        env:
          VPN_TYPE: openvpn
          VPN_SERVICE_PROVIDER: protonvpn
          SERVER_COUNTRIES: Netherlands
          OPENVPN_PROTOCOL: udp
          DOT: on
          DNS_KEEP_NAMESERVER: off
          VPN_PORT_FORWARDING: on
          FIREWALL_DEBUG: on
```
```
