### ISSUE TITLE
Bug: Private Internet Access not working

### ISSUE THREAD

**Issue by yckai** [qdm12/gluetun#1842]
### Is this urgent?

None

### Host OS

Ubuntu sserver

### CPU arch

aarch64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker-compose

### What is the version of Gluetun

latest

### What's the problem 🤔

Private internet is not running there is no tun interface and I got an error and unhealthy docker

### Share your logs

```plain text
2023-09-02T16:33:26Z ERROR HTTP response status is not OK: 500 500 Internal Server Error: dialing: dial tcp4: lookup cloudflare.com on 1.1.1.1:53: write udp 172.17.0.3:53827->1.1.1.1:53: write: operation not permitted 2023-09-02T16:33:26Z INFO Shutdown successful
```

### Share your configuration

```yml
services:
  pialow:
    image: qmcgaw/gluetun
    container_name: pialow
    restart: always
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8080:8080
      - 6881:6881/tcp
      - 6881:6881/udp
#      - 58846:58846
#      - 58946:58946
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - VPN_TYPE=openvpn
      - SERVER_REGIONS=Netherlands
      - PRIVATE_INTERNET_ACCESS_OPENVPN_ENCRYPTION_PRESET=normal
      - OPENVPN_USER=user
      - OPENVPN_PASSWORD=pass
    volumes:
      - /gluetun:/gluetun
```
