### ISSUE TITLE
Bug: Server Region ENV variable set to lowercase, causing available region match to fail

### ISSUE THREAD

**Issue by cohenchris** [qdm12/gluetun#1892]
### Is this urgent?

None

### Host OS

Arch Linux

### CPU arch

x86_64

### VPN service provider

Windscribe

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2023-05-25T12:12:44.932Z (commit a43973c)

### What's the problem 🤔

Server Region variable is set to lowercase, causing a comparison to fail, even with valid server region selected.

### Share your logs (at least 10 lines)

```plain text
2023-10-03T14:25:17-07:00 ERROR VPN settings: provider settings: server selection: for VPN service provider windscribe: the region specified is not valid: value is not one of the possible choices: value switzerland, choices available are Albania, Argentina, Australia, Austria, Azerbaijan, Belgium, Bosnia, Brazil, Bulgaria, Cambodia, Canada East, Canada West, Chile, Colombia, Croatia, Cyprus, Czech Republic, Denmark, Ecuador, Estonia, Fake Antarctica, Finland, France, Georgia, Germany, Ghana, Greece, Hong Kong, Hungary, Iceland, India, Indonesia, Ireland, Israel, Italy, Japan, Kenya, Latvia, Lithuania, Luxembourg, Malaysia, Mexico, Moldova, Netherlands, New Zealand, North Macedonia, Norway, Panama, Peru, Philippines, Poland, Portugal, Romania, Russia, Serbia, Singapore, Slovakia, South Africa, South Korea, Spain, Sweden, Switzerland, Taiwan, Thailand, Turkey, US Central, US East, US West, Ukraine, United Arab Emirates, United Kingdom, Vietnam, WINDFLIX CA, WINDFLIX JP, WINDFLIX UK, WINDFLIX US
```

### Share your configuration

```yml
services:
  swag:
    image: linuxserver/swag:2.6.0
    container_name: swag
    cap_add:
      - NET_ADMIN
    networks:
      - reverseproxy
    environment:
      - PUID
      - PGID
      - TZ
      - URL=${DOMAIN}
      - SUBDOMAINS=${SUBDOMAINS}
      - VALIDATION=dns
      - DNSPLUGIN=${REGISTRAR}
      - EMAIL=${EMAIL}
      - STAGING=false
      - PROPAGATION=100
    volumes:
      - ${CONFIG}/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"
```
