### ISSUE TITLE
Custom wg0.conf, port fowarding and gluetun

### ISSUE THREAD

**Issue by waz1500** [qdm12/gluetun#1926]
I just wanted to check something with my setup regarding port forwarding and when you are using your *own* custom wireguard config from your own wireguard server. 

I've setup my own wireguard server via docker on an external server with a public facing IP, but does that wireguard server need any additional setup to allow the torrent port 6881/udp to pass through when using that connection on a home connection with gluetun?

I have enabled port forwarding for `6881 udp/tcp` on my router but I'm not sure what the VPN providers that give out and support wireguard configs do on their end to enable port forwarding for the torrent port on their servers. 

I have allowed gluetun to pass through the port `6881` by enabling the variable `FIREWALL_VPN_INPUT_PORTS` but from my understanding this is normally used to allow port forwarding given by VPN providers. I haven't setup any ufw/iptable rules on the wireguard server. 
```
gluetun added environment variables:
- FIREWALL_VPN_INPUT_PORTS=6881
 ```
```
gluetun ports:
- 8080:8080 #qbittorrent webui
- 6881:6881 #qbitorrent    
- 6881:6881/udp #qbitorrent  
```
I have also enabled qbittorrent to use gluetun via `network_mode: service:gluetun` and I have no errors in the gluetun output. 

If I switch my network interface in qbittorrent to `eth0`, I'll get a green connection icon suggesting I'm fully connectible since I've enabled port forwarding on my home router to my home IP. It's technically open on my router but I'm unable to download since it's using `eth0`. When I switch to `tun0` the interface gluetun creates, I can download but qbittorrent shows as not "fully" connectible. I can still seed but I'm relying on the other peer.  

I'm assuming I need to allow the torrenting packets to go through but I'm unsure how to. I'm aware that torrent sites show connectibility by `Torrent Client External IP:Torrent Port` but because I'm not running my torrent client directly on the wireguard server, it will always show as closed.

I have used qdm12's port checker inside the gluetun docker to check, doing so whilst qbittorrent is not open to avoid port conflicts.  
```
docker exec -it gluetun /bin/sh
./port-checker -port 6881
```
I see my browser IP address and user agent and I also see the request logged in the port-checker output.
Everything suggests port forwarding is working, but qbittorrent claims the port isn't open.

I've seen a lot of people do some fancy things with iptables and with Post Up/Post Down but I'm unsure if it's needed here or if I'm overlooking things. 

I would really appreciate any insight on this. I absolutely love gluetun. Thanks for making this qdm12! 

```
  gluetun:
    image: qmcgaw/gluetun:v3.35.0
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - proxynet
    ports:
      - 8080:8080 #qbittorrent
      - 6881:6881 #qbitorrent
      - 6881:6881/udp #qbitorrent
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=******
      - VPN_ENDPOINT_PORT=51820
      - WIREGUARD_PUBLIC_KEY=******
      - WIREGUARD_PRIVATE_KEY=******
      - WIREGUARD_PRESHARED_KEY=******
      - WIREGUARD_ADDRESSES=******
      - FIREWALL_VPN_INPUT_PORTS=6881
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.5.5-libtorrentv1
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    volumes:******
    network_mode: service:gluetun
    restart: unless-stopped
```

**Comment by dawidmachon** [comment]
Did you set up in Configuration of qbittorent incoming port?
![image](https://github.com/qdm12/gluetun/assets/44931854/d7442629-cbc3-4d28-a135-f37940f002e6)

**Comment by waz1500** [comment]
Yep. It's already set to `6881`, I've also tested other ports in case it was an ISP issue. `Use UPnP / NAT-PMP port forwarding` is disabled as per your screenshot. qbittorrent still shows a firewalled status on the tun0 interface. 

This shouldn't be the case if I understood how `FIREWALL_VPN_INPUT_PORTS` works. I thought it would allow that port from the `eth0` connection and allow it on the `tun0` interface. 

I don't think it was too clear on my original post. qbittorrent is using the VPN interface and has the right IP and it can download fine. I can use `curl ifconfig.io` in a command and the output is my VPN IP. 

It's the port forwarding that I'm having an issue with when using a custom server and not a public VPN provider.
I'm wondering if it's because in a docker environment and there's some sort of incompatibility.

**Comment by xavierfnk** [comment]
Hey @waz1500 , I am currently setting up in a similar environment (docker compose stack, personal wireguard vpn somewhere else on the internet). Did you find a setup that works?

**Comment by waz1500** [comment]
@xavierfnk Thanks for posting. I never quite found a solution where port forwarding worked when everything is dockerized but I do plan on trying again. The setup I had worked but you will be firewalled. Let me know if you ever get a step closer as I'd love to get this working.

**Comment by xavierfnk** [comment]
I managed to get a working configuration.

### Custom VPN Endpoint side

```
[Interface]
PrivateKey = redacted
Address = 10.0.0.1/32
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 6881 -j DNAT --to-destination 10.0.0.2
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE; iptables -t nat -D PREROUTING -i eth0 -p tcp --dport 6881 -j DNAT --to-destination 10.0.0.2
ListenPort = 51820

[Peer]
PublicKey = redacted
AllowedIPs = 10.0.0.2/32
```

Notice here that I put iptables rules so that requests to the "incoming connections" qBittorrent port on my VPN are NATed and forwarded to my client through the tunnel.

### Client side

```yaml
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881 # qbittorrent p2p
      - 6881:6881/udp # qbittorrent p2p
      - 8085:8085 # qbittorrent web ui
      - 7878:7878 # Radarr
      - 8989:8989 # Sonarr
      - 9696:9696 # Prowlarr
      - 8191:8191 # FlareSolverr
    volumes:
      - /home/arr-stack:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=redacted
      - VPN_ENDPOINT_PORT=51820
      - WIREGUARD_PUBLIC_KEY=redacted
      - WIREGUARD_PRIVATE_KEY=redacted
      - WIREGUARD_ADDRESSES=10.0.0.2/32
      - TZ=Europe/Paris
    networks:
      - traefik
```

Looks like there is no need to configure port forwarding in gluetun, as the iptables configuration inside the container looks completely open by default, but I may be mistaken.

I manage to get some seeding done, at least ratios are not 0 everywhere:
<img width="107" alt="image" src="https://github.com/qdm12/gluetun/assets/44227831/70d0d8cc-36a6-4634-8c27-870c0c383a96">

**Comment by waz1500** [comment]
That's great you managed to get something working! I had a feeling the issue was somewhere in the iptables.
I'm wondering if you installed wireguard using a docker container or locally on the remote server? My generated config is a little different, but that's most likely due to using linuxserver's wireguard image. I did attempt to add your iptables to my setup with my current address but no luck unfortunately. I'll try testing via another image and also try installing wireguard locally.  

```
[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = redacted
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer1
PublicKey = redacted
AllowedIPs = 10.13.13.2/32
```
If you have the green world icon in qbittorrent when you set the network interface to `tun0` then I believe it should be working.

There was an issue with some trackers and qbittorrent announcing on all available interfaces when it's set to `Any interface`. It's also misleading because qbittorrent will cycle through all the interfaces and in my case detects the open port in my router and shows the green world icon but since my wireguard server isn't setup correctly, I would only ever connect to half the amount of peers I normally would.
![chrome_SgA3WVrjmm](https://github.com/qdm12/gluetun/assets/17833884/9efb10ee-a0a8-4898-ae24-6fcb01d70608)

I'll do some more testing based on your setup. Thanks for replying to the issue.

**Comment by xavierfnk** [comment]
I am running wireguard directly on the remote server as it is its only purpose.
Indeed, I set `tun0` as the network interface in qBittorrent!

I managed to get the "green world" icon in qBittorrent by adding this to the gluetun environment variables:
```
FIREWALL_VPN_INPUT_PORTS=6881
```
It adds an iptables rule in the gluetun container to accept incoming connections on my qbittorrent "incoming" port:
<img width="623" alt="image" src="https://github.com/qdm12/gluetun/assets/44227831/96586b93-8e2f-4d7f-a51e-688453f369b7">
My seeding stats look much better with that.

**Comment by waz1500** [comment]
Very cool! Well done for getting this working! I can't see any more issues with your setup now.
My remote server is also just to house wireguard so I'm happy to forget about dockerizing it, remove that layer of complexity and I'll look to install it locally as you did. I do hope to get my setup working as you did yours.

Either way, I'll mark this issue as closed by the end of the weekend as it will confirm the issue will be on my end. 
Thank you again for posting your findings!

**Comment by waz1500** [comment]
Confirmed working after installing wireguard locally on the remote server as opposed to in docker. Hooray!
I'm sure it can work when both servers are in a dockerized environment but may require some additional network tweaking and in this case it was unnecessary.
Huge props to @xavierfnk for figuring this out. 

This should close this issue. As I mentioned in my initial post, although gluetun only allows connectivity through the `tun0` interface, when qbittorrent is incorrectly set to use `Any Interface` it can give the illusion that things are working as it will try to announce on all interfaces (including the eth0 connection) and using an external port checker to check for port connectivity can be misleading.

@xavierfnk, if you haven't already, you may want to add autohealing to your stack.
Gluetun has a built in kill-switch which is great as it will kill the qbittorrent connection when it looses connectivity but wont restart the unhealthy containers. This will allow for qbittorrent to restart itself automatically when gluetun regains connectivity should it be lost. I'm using autoheal but qdm12 has a similar container called [deunhealth](https://github.com/qdm12/deunhealth ) which you may also want to look at. 

 
```
qbittorrent:
...
    healthcheck:
      test: "curl -sf https://example.com  || exit 1"
      interval: 1m30s
      timeout: 10s
      retries: 1
      start_period: 20s
    labels:
      - autoheal=true
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
#    environment:
#      - AUTOHEAL_CONTAINER_LABEL=all #Could possibly use this for entire stack
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - /etc/localtime:/etc/localtime:ro
```

**Comment by julian-alarcon** [comment]
> I am running wireguard directly on the remote server as it is its only purpose. Indeed, I set `tun0` as the network interface in qBittorrent!
> 
> I managed to get the "green world" icon in qBittorrent by adding this to the gluetun environment variables:
> 
> ```
> FIREWALL_VPN_INPUT_PORTS=6881
> ```
> 
> It adds an iptables rule in the gluetun container to accept incoming connections on my qbittorrent "incoming" port: <img alt="image" width="623" src="https://private-user-images.githubusercontent.com/44227831/306022929-96586b93-8e2f-4d7f-a51e-688453f369b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyODg5NzYsIm5iZiI6MTczMjI4ODY3NiwicGF0aCI6Ii80NDIyNzgzMS8zMDYwMjI5MjktOTY1ODZiOTMtOGUyZi00ZDdmLWE1MWUtNjg4NDUzZjM2OWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDE1MTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YThkZjk0M2Y2ODMyOTkzZGJlNzU0YTg3ZTMwODgxNDRhNTEwM2MyZmU4YjIzNmYwZWVkYTMwYWFiYjNiOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.03Cfnp8CKFGHJFuBVZBz0CBLyJMmuRSF1YleWG2rLuw"> My seeding stats look much better with that.
> 
> As we have very similar configuration in the end, I guess your problem lies in the wireguard configuration on your remote server. If it is in a container, I suggest you identify how connections and routing is handled between your remote server host network and your container.

The variable FIREWALL_VPN_INPUT_PORTS was missing in my configuration in TrueNAS 24.10. Thank you!

If you are interested, this is my configuration (I'm using 2 different apps in Truenas):

Set new custom app with name `custom-app-gluetun`, paste the docker-compose setup below:

```yaml
# Source: https://forums.truenas.com/t/guide-how-to-install-qbittorrent-or-any-app-with-vpn-on-truenas-electric-eel/12677
# Configuration https://github.com/qdm12/gluetun-wiki
name: gluetun
services:
  gluetun:
    image: qmcgaw/gluetun:v3.39.1 # https://hub.docker.com/r/qmcgaw/gluetun/tags
    restart: always
    container_name: custom-app-gluetun-1
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8080:8080 # qbittorrent webui
      - 6881:6881 # qbittorrent
      - 6881:6881/udp # qbittorrent
    volumes:
      - /mnt/ssd-storage/apps-data/gluetun:/gluetun
    environment:
      - VPN_TYPE=wireguard
      - VPN_SERVICE_PROVIDER=protonvpn
      - WIREGUARD_PRIVATE_KEY=WIRGUARD_PRIVATE_KEY
      - SERVER_COUNTRIES=Switzerland
      - PORT_FORWARD_ONLY
      - UPDATER_PERIOD=24h
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - FIREWALL_VPN_INPUT_PORTS=6881
```

New custom app with name `custom-app-qbittorrent`, paste the docker-compose setup below:

```yaml
# Source: https://forums.truenas.com/t/guide-how-to-install-qbittorrent-or-any-app-with-vpn-on-truenas-electric-eel/12677
# Configuration https://docs.linuxserver.io/images/docker-qbittorrent
name: qbittorrent
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.7 # https://gitlab.com/Linuxserver.io/docker-qbittorrent/container_registry/774438
    restart: always
    container_name: custom-app-qbittorrent-1
    environment:
      - PUID=568 # Linux User ID for user: apps
      - PGID=568 # Linux User ID for group: apps
      - TZ=Europe/Berlin
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/ssd-storage/apps-data/qbittorrent/config:/config   #Directory you want to save your qbit config files
      - /mnt/backup-and-downloads/movies-series:/media    #movies/series/music directory 
    network_mode: container:custom-app-gluetun-1 #this is what makes the app to connect to the VPN.
    # Note that all ports were moved to the gluetun app.
```
