### ISSUE TITLE
Bug: windscribe  DNS over TLS errors

### ISSUE THREAD

**Issue by Miku-programm** [qdm12/gluetun#2018]
### Is this urgent?

Yes

### Host OS

Debian/ubuntu

### CPU arch

aarch64

### VPN service provider

Windscribe

### What are you using to run the container

docker run

### What is the version of Gluetun

latest version

### What's the problem 🤔

My container is not working because the DNS over TLS file is not downloading, I've checked that the configuration is correct, the VPN account is valid, and the VPS network is working

### Share your logs (at least 10 lines)

```plain text
jp-gluetun-1  | 2023-12-26T01:39:16Z INFO [vpn] stopping
jp-gluetun-1  | 2023-12-26T01:39:16Z INFO [vpn] starting
jp-gluetun-1  | 2023-12-26T01:39:16Z INFO [firewall] allowing VPN connection...
jp-gluetun-1  | 2023-12-26T01:39:16Z INFO [wireguard] Using userspace implementation since Kernel support does not exist
jp-gluetun-1  | 2023-12-26T01:39:16Z INFO [wireguard] Connecting to 193.148.16.244:1194
jp-gluetun-1  | 2023-12-26T01:39:16Z INFO [wireguard] Wireguard is up
jp-gluetun-1  | 2023-12-26T01:39:17Z INFO [dns over tls] downloading DNS over TLS cryptographic files
jp-gluetun-1  | 2023-12-26T01:39:27Z WARN [dns over tls] cannot update files: Get "https://www.internic.net/domain/named.root": dial tcp: lookup www.internic.net on 1.1.1.1:53: read udp 10.64.222.21:52467->1.1.1.1:53: i/o timeout
jp-gluetun-1  | 2023-12-26T01:39:27Z INFO [dns over tls] attempting restart in 20s
jp-gluetun-1  | 2023-12-26T01:39:32Z INFO [healthcheck] program has been unhealthy for 16s: restarting VPN (see https://github.com/qdm12/gluetun/wiki/Healthcheck)
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 29832:8888/tcp # HTTP proxy
      - 28154:1080 # 
    environment:
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_ADDRESSES=10.64.222.21/32
      - SERVER_REGIONS=Japan 
      - HTTPPROXY=on
  socks5:
    image: serjs/go-socks5-proxy
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
```
