### ISSUE TITLE
Bug: Control Server unreachable. "unversioned API: requested URI not found"

### ISSUE THREAD

**Issue by erphise** [qdm12/gluetun#2031]
### Is this urgent?

No

### Host OS

Unraid OS 6.12.4

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2024-01-01T18:24:19.221Z (commit c826707)

### What's the problem 🤔

Unable to access Control Server on `http://<your-docker-host-ip>:8000`. Error: `unversioned API: requested URI not found`

### Share your logs (at least 10 lines)

```plain text
On the WebGUI:
"unversioned API: requested URI not found"
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8080:8080/tcp # qBittorrent
    volumes:
      - /mnt/user/appdata/gluetun/config:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_PUBLIC_KEY=XXXXXXXX
      - WIREGUARD_PRIVATE_KEY=XXXXXXXX
      - WIREGUARD_ADDRESSES=XXXXXXXX
      - VPN_ENDPOINT_IP=XXXXXXXX
      - VPN_ENDPOINT_PORT=XXXXXXXX
      - VPN_DNS_ADDRESS=XXXXXXXX
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - TZ=Europe/Madrid
      - HTTPPROXY=off
      - SHADOWSOCKS=off
      - UPDATER_PERIOD=24h
    restart: unless-stopped
```
