### ISSUE TITLE
Bug: Server keep restarting

### ISSUE THREAD

**Issue by clpir3s** [qdm12/gluetun#2066]
### Is this urgent?

No

### Host OS

ubuntu

### CPU arch

aarch64

### VPN service provider

Surfshark

### What are you using to run the container

docker-compose

### What is the version of Gluetun

v3.36.0

### What's the problem 🤔

Hi all,

I already setup multiple server (in order to have many Public IP), I'm not sure if this is related to the number of server I'm using.

Can you help me if I'm missing some config?

### Share your logs (at least 10 lines)

```plain text
fr-proxyserver-4  | 2024-01-22T17:10:32Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o        timeout errors indicate the Wireguard connection is not working.
fr-proxyserver-1  | 2024-01-22T17:10:32Z INFO [healthcheck] unhealthy: dialing: dial tcp4: lookup cloudflare.com: i/o timeout
fr-proxyserver-1  | 2024-01-22T17:10:33Z INFO [healthcheck] healthy!
fr-proxyserver-3  | 2024-01-22T17:10:38Z INFO [healthcheck] program has been unhealthy for 41s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
fr-proxyserver-3  | 2024-01-22T17:10:38Z INFO [vpn] stopping
fr-proxyserver-3  | 2024-01-22T17:10:38Z INFO [vpn] starting
fr-proxyserver-3  | 2024-01-22T17:10:38Z INFO [firewall] allowing VPN connection...
fr-proxyserver-3  | 2024-01-22T17:10:38Z INFO [wireguard] Using available kernelspace implementation
fr-proxyserver-3  | 2024-01-22T17:10:38Z INFO [wireguard] Connecting to 45.134.79.166:51820
fr-proxyserver-3  | 2024-01-22T17:10:38Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o        timeout errors indicate the Wireguard connection is not working.
fr-proxyserver-4  | 2024-01-22T17:10:42Z ERROR [ip getter] Get "https://ipinfo.io/": dial tcp: lookup ipinfo.io on 1.1.1.1:53: read udp 10.14.0.2:47797->1.1.1.1:53: i/o timeout - retrying in 5s
fr-proxyserver-4  | 2024-01-22T17:10:43Z INFO [healthcheck] program has been unhealthy for 11s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
fr-proxyserver-4  | 2024-01-22T17:10:43Z INFO [vpn] stopping
fr-proxyserver-4  | 2024-01-22T17:10:43Z INFO [vpn] starting
fr-proxyserver-4  | 2024-01-22T17:10:43Z INFO [firewall] allowing VPN connection...
fr-proxyserver-4  | 2024-01-22T17:10:43Z INFO [wireguard] Using available kernelspace implementation
fr-proxyserver-4  | 2024-01-22T17:10:43Z INFO [wireguard] Connecting to 85.204.70.105:51820
fr-proxyserver-4  | 2024-01-22T17:10:43Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o        timeout errors indicate the Wireguard connection is not working.
fr-proxyserver-5  | 2024-01-22T17:10:48Z INFO [healthcheck] unhealthy: dialing: dial tcp4: lookup cloudflare.com: i/o timeout
fr-proxyserver-5  | 2024-01-22T17:10:56Z INFO [healthcheck] program has been unhealthy for 6s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
fr-proxyserver-5  | 2024-01-22T17:10:56Z INFO [vpn] stopping
fr-proxyserver-5  | 2024-01-22T17:10:56Z INFO [vpn] starting
fr-proxyserver-5  | 2024-01-22T17:10:56Z INFO [firewall] allowing VPN connection...
fr-proxyserver-5  | 2024-01-22T17:10:56Z INFO [wireguard] Using available kernelspace implementation
fr-proxyserver-5  | 2024-01-22T17:10:56Z INFO [wireguard] Connecting to 85.204.70.105:51820
fr-proxyserver-5  | 2024-01-22T17:10:56Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o        timeout errors indicate the Wireguard connection is not working.
fr-proxyserver-4  | 2024-01-22T17:10:57Z ERROR [ip getter] Get "https://ipinfo.io/": dial tcp: lookup ipinfo.io on 1.1.1.1:53: read udp 10.14.0.2:52811->1.1.1.1:53: i/o timeout - retrying in 10s
fr-proxyserver-4  | 2024-01-22T17:10:59Z INFO [healthcheck] program has been unhealthy for 16s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
fr-proxyserver-4  | 2024-01-22T17:10:59Z INFO [vpn] stopping
fr-proxyserver-4  | 2024-01-22T17:11:00Z INFO [vpn] starting
fr-proxyserver-4  | 2024-01-22T17:11:00Z INFO [firewall] allowing VPN connection...
fr-proxyserver-4  | 2024-01-22T17:11:00Z INFO [wireguard] Using available kernelspace implementation
fr-proxyserver-4  | 2024-01-22T17:11:00Z INFO [wireguard] Connecting to 146.70.18.91:51820
fr-proxyserver-4  | 2024-01-22T17:11:00Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o        timeout errors indicate the Wireguard connection is not working.
fr-proxyserver-3  | 2024-01-22T17:11:04Z ERROR [ip getter] Get "https://ipinfo.io/": dial tcp: lookup ipinfo.io on 1.1.1.1:53: read udp 10.14.0.2:54817->1.1.1.1:53: i/o timeout - retrying in 2m40s
fr-proxyserver-5  | 2024-01-22T17:11:06Z ERROR [ip getter] Get "https://ipinfo.io/": dial tcp: lookup ipinfo.io on 1.1.1.1:53: read udp 10.14.0.2:35512->1.1.1.1:53: i/o timeout - retrying in 5s
fr-proxyserver-5  | 2024-01-22T17:11:07Z INFO [healthcheck] program has been unhealthy for 11s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
fr-proxyserver-5  | 2024-01-22T17:11:07Z INFO [vpn] stopping
fr-proxyserver-5  | 2024-01-22T17:11:08Z INFO [vpn] starting
fr-proxyserver-5  | 2024-01-22T17:11:08Z INFO [firewall] allowing VPN connection...
fr-proxyserver-5  | 2024-01-22T17:11:08Z INFO [wireguard] Using available kernelspace implementation
fr-proxyserver-5  | 2024-01-22T17:11:08Z INFO [wireguard] Connecting to 85.204.70.93:51820
fr-proxyserver-5  | 2024-01-22T17:11:08Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o        timeout errors indicate the Wireguard connection is not working.
fr-proxyserver-4  | 2024-01-22T17:11:17Z ERROR [ip getter] Get "https://ipinfo.io/": dial tcp: lookup ipinfo.io on 1.1.1.1:53: read udp 10.14.0.2:37226->1.1.1.1:53: i/o timeout - retrying in 20s
fr-proxyserver-5  | 2024-01-22T17:11:21Z ERROR [ip getter] Get "https://ipinfo.io/": dial tcp: lookup ipinfo.io on 1.1.1.1:53: read udp 10.14.0.2:40054->1.1.1.1:53: i/o timeout - retrying in 10s
fr-proxyserver-4  | 2024-01-22T17:11:23Z INFO [healthcheck] program has been unhealthy for 21s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
fr-proxyserver-4  | 2024-01-22T17:11:23Z INFO [vpn] stopping
fr-proxyserver-4  | 2024-01-22T17:11:23Z INFO [vpn] starting
fr-proxyserver-4  | 2024-01-22T17:11:23Z INFO [firewall] allowing VPN connection...
fr-proxyserver-4  | 2024-01-22T17:11:23Z INFO [wireguard] Using available kernelspace implementation
fr-proxyserver-4  | 2024-01-22T17:11:23Z INFO [wireguard] Connecting to 143.244.57.81:51820
fr-proxyserver-4  | 2024-01-22T17:11:23Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o        timeout errors indicate the Wireguard connection is not working.
fr-proxyserver-5  | 2024-01-22T17:11:24Z INFO [healthcheck] program has been unhealthy for 16s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
fr-proxyserver-5  | 2024-01-22T17:11:24Z INFO [vpn] stopping
fr-proxyserver-5  | 2024-01-22T17:11:24Z INFO [vpn] starting
fr-proxyserver-5  | 2024-01-22T17:11:24Z INFO [firewall] allowing VPN connection...
fr-proxyserver-5  | 2024-01-22T17:11:24Z INFO [wireguard] Using available kernelspace implementation
fr-proxyserver-5  | 2024-01-22T17:11:24Z INFO [wireguard] Connecting to 194.110.113.227:51820
fr-proxyserver-5  | 2024-01-22T17:11:24Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o        timeout errors indicate the Wireguard connection is not working.
fr-proxyserver-3  | 2024-01-22T17:11:25Z INFO [healthcheck] program has been unhealthy for 46s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
fr-proxyserver-3  | 2024-01-22T17:11:25Z INFO [vpn] stopping
fr-proxyserver-3  | 2024-01-22T17:11:25Z INFO [vpn] starting
fr-proxyserver-3  | 2024-01-22T17:11:25Z INFO [firewall] allowing VPN connection...
fr-proxyserver-3  | 2024-01-22T17:11:25Z INFO [wireguard] Using available kernelspace implementation
fr-proxyserver-3  | 2024-01-22T17:11:25Z INFO [wireguard] Connecting to 146.70.194.227:51820
fr-proxyserver-3  | 2024-01-22T17:11:25Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o        timeout errors indicate the Wireguard connection is not working.
fr-proxyserver-5  | 2024-01-22T17:11:41Z ERROR [ip getter] Get "https://ipinfo.io/": dial tcp: lookup ipinfo.io on 1.1.1.1:53: read udp 10.14.0.2:58582->1.1.1.1:53: i/o timeout - retrying in 20s
fr-proxyserver-5  | 2024-01-22T17:11:47Z INFO [healthcheck] program has been unhealthy for 21s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
fr-proxyserver-5  | 2024-01-22T17:11:47Z INFO [vpn] stopping
fr-proxyserver-5  | 2024-01-22T17:11:47Z INFO [vpn] starting
fr-proxyserver-5  | 2024-01-22T17:11:47Z INFO [firewall] allowing VPN connection...
fr-proxyserver-5  | 2024-01-22T17:11:47Z INFO [wireguard] Using available kernelspace implementation
fr-proxyserver-5  | 2024-01-22T17:11:47Z INFO [wireguard] Connecting to 185.166.84.137:51820
fr-proxyserver-5  | 2024-01-22T17:11:47Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
fr-proxyserver-4  | 2024-01-22T17:11:47Z ERROR [ip getter] Get "https://ipinfo.io/": dial tcp: lookup ipinfo.io on 1.1.1.1:53: read udp 10.14.0.2:42960->1.1.1.1:53: i/o timeout - retrying in 40s
fr-proxyserver-4  | 2024-01-22T17:11:50Z INFO [healthcheck] program has been unhealthy for 26s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
fr-proxyserver-4  | 2024-01-22T17:11:50Z INFO [vpn] stopping
fr-proxyserver-4  | 2024-01-22T17:11:50Z INFO [vpn] starting
fr-proxyserver-4  | 2024-01-22T17:11:50Z INFO [firewall] allowing VPN connection...
fr-proxyserver-4  | 2024-01-22T17:11:50Z INFO [wireguard] Using available kernelspace implementation
fr-proxyserver-4  | 2024-01-22T17:11:50Z INFO [wireguard] Connecting to 194.110.113.227:51820
fr-proxyserver-4  | 2024-01-22T17:11:50Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
```

### Share your configuration

```yml
base.yml
version: "3.9"
services:
  vpn:
    image: qmcgaw/gluetun:v3.36.0
    restart: always
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    #ports:
    #  - 8888:8888/tcp # HTTP proxy
    environment:
      - /lib/modules:/lib/modules:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=OHAI/JZMjhr8sy3aW4ioDv2LSuXbHTKr20L7nX2yjm8=
      - WIREGUARD_ADDRESSES=10.14.0.2/16
    # System
      - PUID=1030
      - PGID=101
      - TZ=Europe/Lisbon
    # HTTPproxy
      - HTTPPROXY=on
      - HTTPPROXY_LOG=on
    # HTTP Control server
      - HTTPPROXY_LISTENING_ADDRESS=:8888
      - HTTPPROXY_STEALTH=on
    # DNS over TLS
      - DOT=off
      - DOT_IPV6=on
    # Other
      # 30 dias - https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      #- UPDATER_PERIOD=720h
      - PUBLICIP_PERIOD=720h
      
  fr-proxyserver:
    extends:
      file: ./base.yml
      service: vpn   
    environment:
      - SERVER_COUNTRIES=France

fr.yml (ony the ip and name is diferente)
version: "3.9"

services:
  #          
  fr-proxyserver-1:
    extends:
      file: ./../base.yml
      service: fr-proxyserver
    container_name: fr-proxyserver-1  
    networks:
      vpn:
        ipv4_address: 10.0.1.200
```
