### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Doug411** [qdm12/gluetun#2093]
### Is this urgent?

No

### Host OS

Debian Bullseye

### CPU arch

aarch64

### VPN service provider

NordVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

latest

### What's the problem 🤔

 have 3 current issues:

Priority 1:   The DHCP Server in my AdguardHome Container is not receiving DHCP requests when Network Mode is a Gluten Service.   See Docker Compose Below.   If I set a static IP on the client and manually assign the DNS to the macvlan, then DNS queries work perfectly under this configuration, and I get full ad blocking.   When I comment out Gluetun, and connect my Adguard container directly to the macvlan network, then everything works including DHCP.   Therefore it seems the problem is Gluetun related (not Macvlan).    I also tried creating my Gluetun container in HOST mode but it kept erroring out on startup.  I'd prefer macvlan, and it seems to work great with the exception of DHCP.

Priority 2:   I'd like clarification on expected behavior when my DNS is set to local adguard using gluetun network that is connected to Nordvpn.  When I do a leak test, it shows my DNS servers are Quad9 (my upstream servers).   I connected my laptop to the gluetun container via a shadowsocks proxy.   My IP address changes to Nord, however my DNS servers still show Quad 9. Is this expected?

Priority 3:  When I use the shadowsocks Proxy, my adblocking doesnt work.  Any idea why, or how to resolve?

### Share your logs (at least 10 lines)

```plain text
1
2
3
4
5
6
7
8
9
10
```

### Share your configuration

```yml
DOCKER COMPOSE
version: "1.5"

########################### NETWORKS########
networks:
  VPN-MACVLAN:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
      - subnet: "192.168.1.0/24"
        ip_range: "192.168.1.5/32"
        gateway: "192.168.1.1"
##########################################
services:
  gluetun-host:
    image: qmcgaw/gluetun    #image: ghcr.io/qdm12/gluetun:pr-1598
    container_name: gluetun-host
    privileged: true        
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp                         # Gluetun Local Network HTTP proxy
      - 8388:8388/tcp                         # Gluetun Local Network Shadowsocks
      - 8388:8388/udp                         # Gluetun Local Network Shadowsocks      
###########################################Ports for Adguard#########################################
      - 53:53/udp
      - 67:67/udp 
      - 68:68/tcp 
      - 68:68/udp 
      - 80:80/tcp 
      - 443:443/tcp 
      - 853:853/tcp 
      - 3000:3000/tcp 
########################################################################################################
    volumes:
      - /opt/docker/gluetun-host:/gluetun-host
    environment:
      #- PUID=${PUID:?err}
      #- PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - VPN_TYPE=${VPN_TYPE}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:?err}
      - SERVER_CITIES=${SERVER_CITIES}
      #- SERVER_HOSTNAMES=${SERVER_HOSTNAMES}
      - FIREWALL_OUTBOUND_SUBNETS=${LOCAL_SUBNET:?err}
      #- WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      #- WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      #- WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SHADOWSOCKS_PASSWORD=${SHADOWSOCKS_PASSWORD:?err}
      - DOT=off
      - DNS_ADDRESS=127.0.0.1
      - HTTPPROXY=on
      - SHADOWSOCKS=on
    networks:
      - VPN-MACVLAN
  adguard:
    container_name: adguard
    image: adguard/adguardhome
    privileged: true
    restart: unless-stopped
    network_mode: "service:gluetun-host"
    #networks:
      #VPN-MACVLAN:
        #ipv4_address: 192.168.1.5
    #ports:
      #- 53:53/udp
      #- 67:67/udp 
      #- 68:68/tcp 
      #- 68:68/udp 
      #- 80:80/tcp 
      #- 443:443/tcp 
      #- 853:853/tcp 
      #- 3000:3000/tcp
    volumes:
      - type: bind
        source: /opt/docker/adguard/conf/ca-certificates.crt
        target: /etc/ssl/certs/ca-certificates.crt      
      - /opt/docker/adguard/conf:/opt/adguardhome/conf
      - /opt/docker/adguard/work:/opt/adguardhome/work
```
