### ISSUE TITLE
Bug: Memory leak and OOM

### ISSUE THREAD

**Issue by iwch** [qdm12/gluetun#2099]
### Is this urgent?

None

### Host OS

Ubuntu 22.04, kernel 6.5.0-17-generic

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2024-02-07T08:39:22.859Z (commit 659bc0c)

### What's the problem 🤔

Gluetun seems to be causing my system to OOM very suddenly when large amounts of data are being downloaded. I'm constantly observing large memory spikes; usually it's sitting at ~10-20MiB of memory used. However, occasionally, its memory usage greatly spikes to many gigabytes, which triggers the oom killer.

This issue seems to happen even when the Gluetun container is given a memory limit. Sometimes, it allocates so much memory so quickly that the Docker daemon is unable to kill and restart it before the oom killer triggers.

### Share your logs (at least 10 lines)

```plain text
Gluetun log: https://pastebin.com/N93Twxcs
Kernel log: https://pastebin.com/jg6zSByG

docker stats output:
CONTAINER ID   NAME                  CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O        PIDS
...
27db0ea63396   gluetun               0.44%     6.336MiB / 500MiB     1.27%     537MB / 14.3MB    155MB / 63.5MB   18
```

### Share your configuration

```yml
gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=...
      - WIREGUARD_ADDRESSES=...
      - SERVER_CITIES=...
      - UPDATER_PERIOD=24h
    restart: unless-stopped
    mem_limit: 700m
```
