### ISSUE TITLE
Bug: Gluetun cannot be used in a L3 IP VLAN

### ISSUE THREAD

**Issue by IComplainInComments** [qdm12/gluetun#2115]
### Is this urgent?

None

### Host OS

Ubuntu 23.10

### CPU arch

aarch64

### VPN service provider

NordVPN

### What are you using to run the container

Portainer

### What is the version of Gluetun

Running version latest built on 2024-02-14T07:39:38.933Z (commit 423a5c3)

### What's the problem 🤔

Using an IPVLAN L3 network with a gluetun container instantly fails at start.

### Share your logs (at least 10 lines)

```plain text
========================================

========================================

=============== gluetun ================

========================================

=========== Made with ❤️ by ============

======= https://github.com/qdm12 =======

========================================

========================================

Running version latest built on 2024-02-14T07:39:38.933Z (commit 423a5c3)

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new

🐛 Bug? https://github.com/qdm12/gluetun/issues/new

✨ New feature? https://github.com/qdm12/gluetun/issues/new

☕ Discussion? https://github.com/qdm12/gluetun/discussions/new

💻 Email? quentin.mcgaw@gmail.com

💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12

2024-02-16T16:30:47-05:00 ERROR getting assigned IP of eth0: IP address not found for interface: interface eth0 in 1 addresses

2024-02-16T16:30:47-05:00 INFO Shutdown successful
```

### Share your configuration

```yml
version: "3"
services:

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      torrent-net:
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /var/lib/docker/volumes/gluetun_data/_data:/gluetun
      - /lib/modules:/lib/modules:ro
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - SERVER_HOSTNAMES=
      - SERVER_COUNTRIES=
      # OpenVPN:
      # - OPENVPN_USER=
      # - OPENVPN_PASSWORD=
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=
      # - WIREGUARD_ADDRESSES=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=Etc/UTC
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=0



networks:
  torrent-net:
    external: true
```
