### ISSUE TITLE
Bug: latest image breaks Socks5 container

### ISSUE THREAD

**Issue by elliotks** [qdm12/gluetun#2134]
### Is this urgent?

No

### Host OS

Ubuntu 22.04.4 LTS

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2024-02-21T17:01:05.694Z (commit a20695f)

### What's the problem 🤔

Hello, 

After updating to qmcgaw/gluetun:latest - breaks integration with SOCKS5 `serjs/go-socks5-proxy`

`SOCKS5 proxy error. Address: 10.1.8.37:1080. Message: "Connection reset by peer".`

`qmcgaw/gluetun:latest`
`DIGEST:sha256:63220ec07e40bdf5fdbfe0a6d39d0468ee25c93bd2b31b0e12005cd230b44b8e`

My current compose file, had to switch to
`qmcgaw/gluetun:v3`  
`DIGEST:sha256:e15ede3ce007e3f6e3f6532c7d8d6051f4bb0dca4bb3c5edd7aa3316916e9990`

for it to work again. 

I don't have time to review the repo and place blame on a change yet. Please don't disregard this because I didn't save logs before switching to v3. 

### Share your logs (at least 10 lines)

```plain text
Bart Simpson: I will gather logs next time this happens.
Bart Simpson: I will gather logs next time this happens.
Bart Simpson: I will gather logs next time this happens.
Bart Simpson: I will gather logs next time this happens.
Bart Simpson: I will gather logs next time this happens.
Bart Simpson: I will gather logs next time this happens.
Bart Simpson: I will gather logs next time this happens.
Bart Simpson: I will gather logs next time this happens.
Bart Simpson: I will gather logs next time this happens.
Bart Simpson: I will gather logs next time this happens.
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
    # Specify ports to access other containers inside glutun network.
      - 8888:8888/tcp # HTTP proxy
    # - 8388:8388/tcp # Shadowsocks
    # - 8388:8388/udp # Shadowsocks
      - 1080:1080 #socks5 proxy
    volumes:
      - glutun_data:/gluetun
    restart: unless-stopped
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      # providers https://github.com/qdm12/gluetun/blob/master/internal/constants/providers/providers.go
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      # OpenVPN:
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      # update manually with glutun_update 
      # docker run --rm -v gluton_gluton_data:/gluetun qmcgaw/gluetun update -enduser -providers "private internet access"
      - SERVER_REGIONS=${SERVER_REGIONS}
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      # - WIREGUARD_ADDRESSES=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=${TZ}
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      # default is 24h
      - UPDATER_PERIOD=${UPDATER_PERIOD}
      - HTTPPROXY=${HTTPPROXY}
    env_file:
      - stack.env
  socks5:
    image: serjs/go-socks5-proxy:latest
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    restart: unless-stopped
  #xyz:
  #  image: xyz
  #  container_name: xyz
  #  network_mode: "service:gluetun"
  # Add the following to another docker-compose.yaml 
  #  network_mode: "container:gluetun"

volumes:
  glutun_data:
```
