### ISSUE TITLE
Feature request: support for Windscribe Static IP Port Forwarding over Wireguard

### ISSUE THREAD

**Issue by tobsynl** [qdm12/gluetun#2140]
### What's the feature 🧐

Hi there,

I have a Windscribe plan with a Static IP with Permanent Port Forwarding. Following instructions in the Gluetun Wiki, I have a working Gluetun container with qBittorrent (yay!). I have added the forwarded port I created in the Windscribe portal to `FIREWALL_VPN_INPUT_PORTS`. Unfortunately though, the port is still closed. I have been able to get it to work by using one of their regular servers, but the Static IP seems to cause trouble. Any chance to get support for this?

Cheers,
Tobsy

### Extra information and references

```
version: "3.5"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8085:8085
    volumes:
      - /volume1/docker/gluetun:/tmp/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=redacted
      - VPN_ENDPOINT_PORT=redacted
      - WIREGUARD_PUBLIC_KEY=redacted
      - WIREGUARD_PRIVATE_KEY=redacted      
      - WIREGUARD_PRESHARED_KEY=redacted
      - WIREGUARD_ADDRESSES=redacted
      - FIREWALL_VPN_INPUT_PORTS=redacted
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrentvpn
    network_mode: "service:gluetun"
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8085
    volumes:
      - '/volume1/docker/qbittorrentvpn:/config'
      - '/volume1/docker/Downloads:/downloads'
    depends_on:
      - gluetun
    restart: always
```
