### ISSUE TITLE
Bug: Docker container exit code 2 immediately on run

### ISSUE THREAD

**Issue by eurotransient** [qdm12/gluetun#2163]
### Is this urgent?

None

### Host OS

Ubuntu 22.04.4 LTS

### CPU arch

x86_64

### VPN service provider

AirVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2024-03-18T17:49:37.003Z (commit 3d16798)

### What's the problem 🤔

Gluetun container exits immediately on run with an exit code 2.

### Share your logs (at least 10 lines)

```plain text
2024-03-18T13:55:49-04:00 INFO [http server] http server listening on [::]:8000
2024-03-18T13:55:49-04:00 INFO [healthcheck] listening on 127.0.0.1:9999
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x78e831]
goroutine 107 [running]:
github.com/qdm12/gluetun/internal/storage.filterServer({{0xc001e9fdd0, 0x9}, {0xc001e9faa8, 0x7}, {0xc001e9fed0, 0x6}, {0xc001e9fed6, 0x6}, {0x0, 0x0}, ...}, ...)
	github.com/qdm12/gluetun/internal/storage/filter.go:77 +0x1b1
github.com/qdm12/gluetun/internal/storage.(*Storage).FilterServers(_, {_, _}, {{0xc00002a039, 0x9}, {{0x0, 0xffff00000000}, 0xc0000a4000}, {0xc001131310, 0x1, ...}, ...})
	github.com/qdm12/gluetun/internal/storage/filter.go:33 +0x2fb
github.com/qdm12/gluetun/internal/provider/utils.GetConnection({_, _}, {_, _}, {{0xc00002a039, 0x9}, {{0x0, 0xffff00000000}, 0xc0000a4000}, {0xc001131310, ...}, ...}, ...)
	github.com/qdm12/gluetun/internal/provider/utils/connection.go:39 +0xad
github.com/qdm12/gluetun/internal/provider/airvpn.(*Provider).GetConnection(_, {{0xc00002a039, 0x9}, {{0x0, 0xffff00000000}, 0xc0000a4000}, {0xc001131310, 0x1, 0x1}, {0x0, ...}, ...}, ...)
	github.com/qdm12/gluetun/internal/provider/airvpn/connection.go:12 +0x105
github.com/qdm12/gluetun/internal/vpn.setupWireguard({_, _}, {_, _}, {_, _}, {_, _}, {{0xc00002a039, 0x9}, ...}, ...)
	github.com/qdm12/gluetun/internal/vpn/wireguard.go:20 +0xbe
github.com/qdm12/gluetun/internal/vpn.(*Loop).Run(0xc0000fcf20, {0x109d840, 0xc0004caeb0}, 0xc00008ce40?)
	github.com/qdm12/gluetun/internal/vpn/run.go:40 +0x4f5
created by main._main in goroutine 35
	./main.go:427 +0x385a
```

### Share your configuration

```yml
gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - ####:####
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=##################################
      - WIREGUARD_PRESHARED_KEY=#################################
      - WIREGUARD_ADDRESSES=###############################
      - FIREWALL_VPN_INPUT_PORTS=######
      - TZ=America/New_York
      - UPDATER_PERIOD=24h
      - SERVER_COUNTRIES=##############
```
