### ISSUE TITLE
Bug: How is servers.json created?

### ISSUE THREAD

**Issue by ezekieldas** [qdm12/gluetun#2164]
### Is this urgent?

No

### Host OS

Ubuntu

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2024-03-07T12:32:25.391Z (commit 3254fc8)

### What's the problem 🤔

I brought this up in Discussions last year (see below) but haven't heard anything on it. Now I'm working with Mullvad and find the same issue: no Mexico servers in `servers.json`. While I understand how my container's `servers.json` is updated, how is this updated? https://github.com/qdm12/gluetun/tree/master/internal/storage
Is there a reason why not all servers are being included? 

https://github.com/qdm12/gluetun/discussions/1918

### Share your logs (at least 10 lines)

```plain text
No logs associated
```

### Share your configuration

```yml
Limited to: 

SERVER_COUNTRIES="Canada,USA"

Would like to see:

SERVER_COUNTRIES="Mexico,Canada,USA"
```
