### ISSUE TITLE
Getting segmentation fault on :latest

### ISSUE THREAD

**Issue by sunbeam60** [qdm12/gluetun#2172]
### Is this urgent?

No

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker-compose

### What is the version of Gluetun

-

### What's the problem 🤔

When running :latest, I receive a segmentation fault on start-up. This happens before the Gluetun version is printed in the logs, but it's happened overnight, so I presume it's associated with the docker container pushed on the [March 19th, 2024](https://hub.docker.com/layers/qmcgaw/gluetun/latest/images/sha256-245a8094eb54591747438f8e7a5ce9d108c83f4ce462abd760fe88c99095a537?context=explore).

Fixing to v3.37 removes the issue.

### Share your logs (at least 10 lines)

```plain text
2024-03-20T12:45:29Z INFO [dns] using plaintext DNS at address 1.1.1.1 
2024-03-20T12:45:29Z INFO [http server] http server listening on [::]:8000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x78e831]
2024-03-20T12:45:29.530342146Z
goroutine 113 [running]:
github.com/qdm12/gluetun/internal/storage.filterServer({{0xc000bcd6a0, 0x7}, {0x0, 0x0}, {0xc000bcd660, 0xb}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)                                                                                      
github.com/qdm12/gluetun/internal/storage/filter.go:77 +0x1b1
github.com/qdm12/gluetun/internal/storage.(*Storage).FilterServers(_, {_, _}, {{0xc000012029, 0x7}, {{0x0, 0xffff00000000}, 0xc0000bc000}, {0x0, 0x0, ...}, ...})                                                                   github.com/qdm12/gluetun/internal/storage/filter.go:33 +0x2fb
github.com/qdm12/gluetun/internal/provider/utils.GetConnection({_, _}, {_, _}, {{0xc000012029, 0x7}, {{0x0, 0xffff00000000}, 0xc0000bc000}, {0x0, ...}, ...}, ...)                                                                 github.com/qdm12/gluetun/internal/provider/utils/connection.go:39 +0xad 
github.com/qdm12/gluetun/internal/provider/privateinternetaccess.(*Provider).GetConnection(_, {{0xc000012029, 0x7}, {{0x0, 0xffff00000000}, 0xc0000bc000}, {0x0, 0x0, 0x0}, {0xc000332300, ...}, ...}, ...)
github.com/qdm12/gluetun/internal/provider/privateinternetaccess/connection.go:23 +0x185
github.com/qdm12/gluetun/internal/vpn.setupOpenVPN({_, _}, {_, _}, {_, _}, {_, _}, {{0xc000012029, 0x7}, ...}, ...)                                                                                                                github.com/qdm12/gluetun/internal/vpn/openvpn.go:19 +0xbe
github.com/qdm12/gluetun/internal/vpn.(*Loop).Run(0xc00026f340, {0x109d840, 0xc00028cfa0}, 0xc000150f00?)
github.com/qdm12/gluetun/internal/vpn/run.go:36 +0x405
created by main._main in goroutine 66
./main.go:427 +0x385a
```

### Share your configuration

```yml
version: "3.8"
networks:
  arr-fixed-network:
    external: true

services:
  gluetun:
    container_name: gluetun
    #mage: qmcgaw/gluetun:v3.37
    image: qmcgaw/gluetun:latest
    networks:
      - arr-fixed-network
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/[REPLACED]/docker/arr/gluetun/:/gluetun #The location of our config files
    environment:
      - VPN_SERVICE_PROVIDER=pia
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - SERVER_REGIONS=
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - TZ=Europe/London
    ports: #the port below allow the WebUI of any application connecting through the VPN to remain accessible locally
      - 9696:9696 # port for prowlarr
      - 7878:7878 # port for radarr
      - 8989:8989 # port for sonarr
      - 9090:8080 # port for qbittorrent
    restart: unless-stopped
```
