### ISSUE TITLE
Prowlarr cannot connect to Radarr/Sonarr when behind gluetun

### ISSUE THREAD

**Issue by Daive01** [qdm12/gluetun#2187]
### Is this urgent?

Yes

### Host OS

Windows: Docker Desktop

### CPU arch

None

### VPN service provider

NordVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2024-03-26T07:27:44.668Z (commit 6b2f350)

### What's the problem 🤔

Today I was connecting Radarr/Sonarr to Prowlarr, which is using gluetun, and it wouldn't work. So I tried running Prowlarr in a compose file with no connection to gluetun, and it connected just fine. I am on the latest release of all images. Also, the API keys for Radarr/Sonarr are all correct, and I have tried using "localhost" and the server's address to try to connect, but to no avail.

P.S. I am relatively new to this stuff, so the less complicated the solution, the better.

Thanks

### Share your logs (at least 10 lines)

```plain text
2024-03-26 04:08:21 [Warn] ProwlarrErrorPipeline: Invalid request Validation failed: 
2024-03-26 04:08:21  -- BaseUrl: Unable to complete application test, cannot connect to Radarr. Connection refused (localhost:7878)
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881     # qbittorent
      - 6881:6881/udp # qbittorent
      - 8080:8080     # qbittorent
      - 8191:8191     # flaresolverr
      - 9696:9696     # prowlarr
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=CORRECT
      - SERVER_COUNTRIES=CORRECT
      - SERVER_CITIES=CORRECT
      - TZ=CORRECT
    volumes:
      - CORRECT:/gluetun
    restart: always



  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CORRECT
    volumes:
      - CORRECT:/config
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy



  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: "service:gluetun"
    environment:
      - TZ=CORRECT
    restart: unless-stopped 
    depends_on:
      gluetun:
        condition: service_healthy



  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CORRECT
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - CORRECT:/config
      - CORRECT:/downloads
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy

**Comment by vfaergestad** [comment]
Can you include your Sonarr/Radarr configuration?

**Comment by Nicxx2** [comment]
Something that I did was to include a hostname as well for gluetun:

An example:
![image](https://github.com/qdm12/gluetun/assets/7188489/93eb1d8c-f46f-444e-a60a-b992c926af78)


So for your example, with Prowlarr to communicate with Radarr, you can just put the hostname of gluetun and the port.


As an example:
![image](https://github.com/qdm12/gluetun/assets/7188489/f40767d8-591d-4ec7-b8c1-55f7071f410d)


Hope this helps. 😁

**Comment by Daive01** [comment]
> Can you include your Sonarr/Radarr configuration?

Sure ill update it now.

**Comment by Daive01** [comment]
> Something that I did was to include a hostname as well for gluetun:
> 
> An example: ![image](https://private-user-images.githubusercontent.com/7188489/316984176-93eb1d8c-f46f-444e-a60a-b992c926af78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTMxMTAsIm5iZiI6MTcxMTUxMjgxMCwicGF0aCI6Ii83MTg4NDg5LzMxNjk4NDE3Ni05M2ViMWQ4Yy1mNDZmLTQ0NGUtYTYwYS1iOTkyYzkyNmFmNzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMDQxMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWMxNjdlYTUxMDQ4MGRhYTQ2MzI0NjQwZTlhOTM2MzBhZGRkNDM2Yjg4ZGE5ZTVhZjllYzUwZTJmMzYzMDY1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1OAcWvXsjsRa7JxNOYJ6QwWv-uvM9QDWJ5yIqPpUxiw)
> 
> So for your example, with Prowlarr to communicate with Radarr, you can just put the hostname of gluetun and the port. ***Note:** For this to work, you need to have Radarr and Prowlarr go through gluetun. Make sure to have all the ports needed in the gluetun service as well.
> 
> As an example: ![image](https://private-user-images.githubusercontent.com/7188489/316985195-f40767d8-591d-4ec7-b8c1-55f7071f410d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTMxMTAsIm5iZiI6MTcxMTUxMjgxMCwicGF0aCI6Ii83MTg4NDg5LzMxNjk4NTE5NS1mNDA3NjdkOC01OTFkLTRlYzctYjhjMS01NWY3MDcxZjQxMGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMDQxMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjI3ZjU1OWJlYTliNjAyMTgwNjljZDczZGY0YTMzNzk5MTViZTU1OWMyNDM5NDBmMWZlNTk3MmFjZDczZDk4ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.H7yX4KRVFLR5IN2sC6xJPFoOLj8iDcqcgJ8GfFK69ME)
> 
> Hope this helps. 😁

Thanks for your input and help.

I heard that running Radarr/Sonarr behind glutun causes some problems. But ill definitely try this out as a last resort.

Something i forgot to mention in the original post was that Prowlarr is able to connect fine to Qbitttorrent and flaresolverr which are also using gluetun. But not with Radarr/Sonarr which are not.

**Comment by Daive01** [comment]
> Can you include your Sonarr/Radarr configuration?

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CORRECT
    volumes:
      - CORRECT:/config
      - CORRECT:/data
    ports:
      - 7878:7878
    restart: unless-stopped



  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CORRECT
    volumes:
      - CORRECT:/config
      - CORRECT/data
    ports:
      - 8989:8989
    restart: unless-stopped

**Comment by Nicxx2** [comment]
Some extra notes:

In a Docker environment, "localhost" within a container refers to that specific container's own network environment, not to the host machine or any other container. When a container is configured to use another container's network stack (with network_mode: service:<name>), "localhost" in that context points to the network environment of the container it's linked to. This means that "localhost" is isolated to the local scope of the container's network namespace, making direct communication between containers using "localhost" not feasible (not in the same network space). For inter-container communication, Docker's internal networking and DNS resolution using container names are used instead.


If you tried other options, try the below as well. I put all the containers that you shared into one stack. I made some adjustments:

- hostname and container name for gluetun
- radarr network mode to point at gluetun
- sonarr network mode to point at gluetun
- depends on gluetun. No matter what the service_health is, it point to gluetun and if the VPN is down, then no internet connection.


```yaml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: mediagluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881     # qbittorent
      - 6881:6881/udp # qbittorent
      - 8080:8080     # qbittorent
      - 8191:8191     # flaresolverr
      - 9696:9696     # prowlarr
      - 8989:8989     # sonarr
      - 7878:7878     # radarr
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=CORRECT
      - SERVER_COUNTRIES=CORRECT
      - SERVER_CITIES=CORRECT
      - TZ=CORRECT
    volumes:
      - CORRECT:/gluetun
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CORRECT
    volumes:
      - CORRECT:/config
    restart: unless-stopped
    depends_on:
      - gluetun

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: "service:gluetun"
    environment:
      - TZ=CORRECT
    restart: unless-stopped 
    depends_on:
      - gluetun

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CORRECT
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - CORRECT:/config
      - CORRECT:/downloads
    restart: unless-stopped
    depends_on:
      - gluetun

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CORRECT
    volumes:
      - CORRECT:/config
      - CORRECT:/data
 
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CORRECT
    volumes:
      - CORRECT:/config
      - CORRECT:/data
      
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun


```
