### ISSUE TITLE
Bug: cipher negotiation fails on OpenVPN 2.6 with TorGuard

### ISSUE THREAD

**Issue by gabrielwhite** [qdm12/gluetun#2271]
### Is this urgent?

No

### Host OS

Debian Bookworm

### CPU arch

x86_64

### VPN service provider

TorGuard

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2024-05-04T16:22:29.394Z (commit ef6874f)

### What's the problem 🤔

* I'm getting cipher negotiation failures with TorGuard when I try to connect with OpenVPN 2.6 (`INFO [openvpn] Error: negotiated cipher not allowed - AES-128-GCM not in AES-128-CBC`).
* TorGuard doesn't accept AES-128-GCM, only AES-128-CBC
* I've specified AES-128-CBC in the CIPHER environment variable
* When I use OpenVPN 2.5 there is no problem
* The errors indicate the OpenVPN is trying to negotiate a cipher different to the one I specified in the environment variable
* OpenVPN docs say that the "--data-ciphers" option has replaced the "--cipher" option (

So, is it possible that gluetun isn't passing my cipher specification correctly using OpenVPN 2.6?

> Here's the documentation for --cipher for OpenVPN 2.6:
> 
> This option should not be used any longer in TLS mode and still exists for two reasons:
> 
> compatibility with old configurations still carrying it around;
> allow users connecting to OpenVPN peers older than 2.6.0 to have --cipher configured the same way as the remote counterpart. This can avoid MTU/frame size warnings.
> Before 2.4.0, this option was used to select the cipher to be configured on the data channel, however, later versions usually ignored this directive in favour of a negotiated cipher. Starting with 2.6.0, this option is always ignored in TLS mode when it comes to configuring the cipher and will only control the cipher for --secret pre-shared-key mode (note: this mode is deprecated and strictly not recommended).
> 
> If you wish to specify the cipher to use on the data channel, please see --data-ciphers (for regular negotiation) and --data-ciphers-fallback (for a fallback option when the negotiation cannot take place because the other peer is old or has negotiation disabled).

### Share your logs (at least 10 lines)

```plain text
vpn-cl  | 2024-05-09T08:51:55-04:00 INFO [openvpn] OpenVPN 2.6.8 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD]
vpn-cl  | 2024-05-09T08:51:55-04:00 INFO [openvpn] library versions: OpenSSL 3.1.4 24 Oct 2023, LZO 2.10
vpn-cl  | 2024-05-09T08:51:55-04:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]37.235.52.64:1912
vpn-cl  | 2024-05-09T08:51:55-04:00 INFO [openvpn] UDPv4 link local: (not bound)
vpn-cl  | 2024-05-09T08:51:55-04:00 INFO [openvpn] UDPv4 link remote: [AF_INET]redacted:1912
vpn-cl  | 2024-05-09T08:51:55-04:00 INFO [openvpn] [server] Peer Connection Initiated with [AF_INET]37.235.52.64:1912
vpn-cl  | 2024-05-09T08:51:56-04:00 INFO [openvpn] TUN/TAP device tun0 opened
vpn-cl  | 2024-05-09T08:51:56-04:00 INFO [openvpn] /sbin/ip link set dev tun0 up mtu 1500
vpn-cl  | 2024-05-09T08:51:56-04:00 INFO [openvpn] /sbin/ip link set dev tun0 up
vpn-cl  | 2024-05-09T08:51:56-04:00 INFO [openvpn] /sbin/ip addr add dev tun0 local 10.35.0.26 peer 10.35.0.25
vpn-cl  | 2024-05-09T08:51:56-04:00 ERROR [openvpn] OpenVPN tried to add an IP route which already exists (RTNETLINK answers: File exists)
vpn-cl  | 2024-05-09T08:51:56-04:00 WARN [openvpn] Previous error details: Linux route add command failed: external program exited with error status: 2
vpn-cl  | 2024-05-09T08:51:56-04:00 ERROR [openvpn] Linux route add command failed
vpn-cl  | 2024-05-09T08:51:56-04:00 INFO [openvpn] Error: negotiated cipher not allowed - AES-128-GCM not in AES-128-CBC
vpn-cl  | 2024-05-09T08:51:56-04:00 INFO [openvpn] OPTIONS ERROR: failed to import crypto options
vpn-cl  | 2024-05-09T08:51:56-04:00 INFO [openvpn] Failed to open tun/tap interface
vpn-cl  | 2024-05-09T08:51:56-04:00 INFO [openvpn] SIGUSR1[soft,process-push-msg-failed] received, process restarting
```

### Share your configuration

```yml
vpn-cl:
    image: qmcgaw/gluetun:latest
    container_name: vpn-cl
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=America/Santiago
      - PUID=1000
      - PGID=1000
      - VPN_SERVICE_PROVIDER=torguard
      - OPENVPN_VERSION=2.6
      - OPENVPN_CIPHERS=AES-128-CBC
      - OPENVPN_USER=${TG_USER}
      - OPENVPN_PASSWORD=${TG_PASSWORD}
      - SERVER_COUNTRIES='Chile'
      - HEALTH_TARGET_ADDRESS=cloudflarestatus.com
      - HTTPPROXY=on
      - HTTPPROXY_STEALTH=on
      - BLOCK_SURVEILLANCE=off
      - BLOCK_MALICIOUS=off
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8880:8888   # Proxy
    restart: always
```
