### ISSUE TITLE
Help: Connects to same IP all the time

### ISSUE THREAD

**Issue by entrptaher** [qdm12/gluetun#229]
**TLDR**: *Connects to same IP all the time*

Even if I restart the docker, reconnect, the IP doesn't change at all. So if the IP is bad, I cannot use the VPN at all to browse any website.

1. Is this urgent?

    - [x] Yes
    - [ ] No

2. What VPN service provider are you using?

    - [x] PIA
    - [ ] Mullvad
    - [ ] Windscribe
    - [ ] Surfshark
    - [ ] Cyberghost

3. What's the version of the program?

    `Running version latest built on 2020-08-30T14:49:36Z (commit 7c102c0)`

4. What are you using to run the container?

    - [ ] Docker run
    - [x] Docker Compose
    - [ ] Kubernetes
    - [ ] Docker stack
    - [ ] Docker swarm
    - [ ] Podman
    - [ ] Other:

5. Extra information

Logs:

```log
gluetun_1  | 2020-08-31T00:47:17.252Z	INFO	openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]212.102.37.77:1197
gluetun_1  | 2020-08-31T00:47:17.252Z	INFO	openvpn: UDP link local: (not bound)
gluetun_1  | 2020-08-31T00:47:17.252Z	INFO	openvpn: UDP link remote: [AF_INET]212.102.XX.XX:1197

```

Configuration file:

```yml
gluetun:
    image: qmcgaw/private-internet-access
    # uncomment to use the check ip
    # container_name: gluetun
    network_mode: bridge
    ports: 
      - ${VPN_ADMIN_PORT}:8000/tcp
    cap_add:
      - NET_ADMIN
    environment:
      - VPNSP=private internet access
      - USER=${PIA_USER}
      - PASSWORD=${PIA_PASSWORD}
      - REGION=Switzerland
      - TINYPROXY=on
    restart: always
```

Host OS: Ubuntu 20.04
