### ISSUE TITLE
Bug: Healthcheck shows heaslthy even tho portforwardin is enabled and refused by the server.

### ISSUE THREAD

**Issue by christianmerges** [qdm12/gluetun#2333]
### Is this urgent?

No

### Host OS

Ubuntu 24.04

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2024-06-17T22:37:52.988Z (commit 93ed87d)

### What's the problem 🤔

Health check is not checking if poftfording is not working when it is enabled.

### Share your logs (at least 10 lines)

```plain text
It seems that the Serverlist is outdated. There is another update regarding to this. To workaround this, I always have to restart the container, till i have randomly a server chosen, which is serving the port forwarding feature.
```

### Share your configuration

```yml
version: '3.8'
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=+nr+f2+pmp
      - OPENVPN_PASSWORD=
      - SERVER_COUNTRIES=Germany
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - SERVER_CITIES=Frankfurt
```
