### ISSUE TITLE
Bug: Wireguard preshared key gets picked up only through environment variable and not through wg0.conf

### ISSUE THREAD

**Issue by emsknock** [qdm12/gluetun#2339]
### Is this urgent?

No

### Host OS

Ubuntu 22.04.4 LTS

### CPU arch

x86_64

### VPN service provider

Custom

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version v3.38.0 built on 2024-03-25T15:53:33.983Z (commit b3ceece)

### What's the problem 🤔

When I bind `/gluetun/wireguard/wg0.conf` to a Wireguard configuration file through docker-compose, the `Presharedkey` value seems to get ignored. This does not happen when the Wireguard configuration is passed through environment variables.

I have tested the Wireguard configuration file in question outside of Gluetun and verified that it works, so it doesn't seem like the config file is the problem.

There's also a "Target IP address" value that appears when I pass in the settings through the environment but I don't know what that relates to — I don't know Wireguard internals very well.

### Share your logs (at least 10 lines)

When the `volumes` key in `docker-compose.yaml` has `./wg.conf:/gluetun/wireguard/wg0.conf`:
```
VPN settings:
├── VPN provider settings:
|   ├── Name: custom
|   └── Server selection settings:
|       ├── VPN type: wireguard
|       └── Wireguard selection settings:
|           ├── Endpoint IP address: xxx.xxx.xxx.xxx
|           ├── Endpoint port: 443
|           └── Server public key: 5...k=
└── Wireguard settings:
    ├── Private key: 8...o=
    ├── Interface addresses:
    |   └── xxx.xxx.xxx.xxx/xx
    ├── Allowed IPs:
    |   ├── 0.0.0.0/0
    |   └── ::/0
    └── Network interface: tun0
        └── MTU: 1400
```

When the above file *is not mounted* but instead the configuration is given through `docker-compose.yaml`'s `environment` key (`WIREGUARD_PUBLIC_KEY` etc):
```
VPN settings:
├── VPN provider settings:
|   ├── Name: custom
|   └── Server selection settings:
|       ├── VPN type: wireguard
|       ├── Target IP address: xxx.xxx.xxx.xxx # ← ~~~~~ ! This line is new !
|       └── Wireguard selection settings:
|           ├── Endpoint IP address: xxx.xxx.xxx.xxx
|           ├── Endpoint port: 443
|           └── Server public key: 5...k=
└── Wireguard settings:
    ├── Private key: 8...o=
    ├── Pre-shared key: h...I= # ← ~~~~~~~~~~~~~~~~~~~~~ ! This line is new !
    ├── Interface addresses:
    |   └── xxx.xxx.xxx.xxx/xx
    ├── Allowed IPs:
    |   ├── 0.0.0.0/0
    |   └── ::/0
    └── Network interface: tun0
        └── MTU: 1400
```

### Share your configuration

```yml
# docker-compose.yaml:
services:
  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /srv/gluetun:/gluetun
      #
      # 1: This does not work!
      #    Contents pasted after this block.
      #
      # - /srv/gluetun/wg.conf:/gluetun/wireguard/wg0.conf
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      #
      # 2: These settings do work!
      #    Exact values redacted.
      #
      # - VPN_ENDPOINT_IP=xxx.xxx.xxx.xxx
      # - VPN_ENDPOINT_PORT=443
      # - WIREGUARD_PUBLIC_KEY=5...k=
      # - WIREGUARD_PRIVATE_KEY=8...o=
      # - WIREGUARD_PRESHARED_KEY=h...I=
      # - WIREGUARD_ADDRESSES=xxx.xxx.xxx.xxx/xx
```

```ini
# /srv/gluetun/wg.conf:
[Interface]
PrivateKey = 8...o=
Address = xxx.xxx.xxx.xxx/xx

[Peer]
Presharedkey = h...I=
PublicKey = 5...k=
Endpoint = xxx.xxx.xxx.xxx:443
```
