### ISSUE TITLE
Bug: Gluetun does not handle shell variables

### ISSUE THREAD

**Issue by geekau** [qdm12/gluetun#2358]
### Is this urgent?

No

### Host OS

Ubuntu Desktop 24.04 LTS x64

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2024-07-12T19:57:02.146Z (commit 9d50c23)

### What's the problem 🤔

We've just updated our project files after 2 years to accommodate the new Docker Compose 2, and to include updated $Variables from Gluetun wiki, however we are having issues with getting the Gluetun container to start with the new set of $Variables.

We've added $Variables into our ENV file, referencing the Gluetun NordVPN wiki: https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/nordvpn.md

Our updated ENV and YAML files are listed in full at the bottom, however the specific updates to the files are:

**UPDATED ENV:**
```
VPN_TYPE=openvpn
VPN_SERVICE_PROVIDER=nordvpn
VPN_USERNAME=<redacted>
VPN_PASSWORD=<redacted>

SERVER_COUNTRIES=Albania # Comma separated list of countries
SERVER_REGIONS=Europe    # Comma separated list of countries
SERVER_CITIES=           # Comma separated list of server cities
SERVER_HOSTNAMES=        # Comma separated list of server hostnames
SERVER_CATEGORIES=       # Comma separated list of server categories
```

**UPDATED YAML:**
```
      - VPN_PORT_FORWARDING_USERNAME=${VPN_USERNAME:?err}
      - VPN_PORT_FORWARDING_PASSWORD=${VPN_PASSWORD:?err}
      - SERVER_COUNTRIES=$(SERVER_COUNTRIES)
      - SERVER_REGIONS=$(SERVER_REGIONS)
      - SERVER_CITIES=$(SERVER_CITIES)
      - SERVER_HOSTNAMES=$(SERVER_HOSTNAMES)
      - SERVER_CATEGORIES=$(SERVER_CATEGORIES)
```

The stack is started with the following command.... removing the "-d" when we're debugging:

```
sudo docker compose --file docker-compose-gluetun.yaml --env-file docker-compose.env up -d
```

However, we're getting the following error on value $(SERVER_COUNTRIES):

```
ERROR VPN settings: provider settings: server selection: for VPN service provider nordvpn: the country specified is not valid: value is not one of the possible choices: value $(SERVER_COUNTRIES), choices available are Albania, Algeria, Andorra, Argentina, Armenia, Australia, Austria, Azerbaijan, Bahamas, Bangladesh, Belgium, Belize, Bermuda, Bhutan, Bolivia, Bosnia and Herzegovina, Brazil, Brunei Darussalam, Bulgaria, Cambodia, Canada, Cayman Islands, Chile, Colombia, Costa Rica, Croatia, Cyprus, Czech Republic, Denmark, Dominican Republic, Ecuador, Egypt, El Salvador, Estonia, Finland, France, Georgia, Germany, Ghana, Greece, Greenland, Guam, Guatemala, Honduras, Hong Kong, Hungary, Iceland, India, Indonesia, Ireland, Isle of Man, Israel, Italy, Jamaica, Japan, Jersey, Kazakhstan, Kenya, Lao People's Democratic Republic, Latvia, Lebanon, Liechtenstein, Lithuania, Luxembourg, Malaysia, Malta, Mexico, Moldova, Monaco, Mongolia, Montenegro, Morocco, Myanmar, Nepal, Netherlands, New Zealand, Nigeria, North Macedonia, Norway, Pakistan, Panama, Papua New Guinea, Paraguay, Peru, Philippines, Poland, Portugal, Puerto Rico, Romania, Serbia, Singapore, Slovakia, Slovenia, South Africa, South Korea, Spain, Sri Lanka, Sweden, Switzerland, Taiwan, Thailand, Trinidad and Tobago, Turkey, Ukraine, United Arab Emirates, United Kingdom, United States, Uruguay, Uzbekistan, Venezuela, Vietnam
gluetun  | 2024-07-14T14:06:32+10:00 INFO Shutdown successful
```

It doesn't seem to matter what SERVER_COUNTRIES we use, it always throws the same error.

Further, If we comment out the SERVER_COUNTRIES=$(SERVER_COUNTRIES) line from the YAML file, then we get the following error from the next listed variable in the YAML file. Again, it doesn't seem to matter what SERVER_CITIES we use, it always throws the same error.

```
ERROR VPN settings: provider settings: server selection: for VPN service provider nordvpn: the city specified is not valid: value is not one of the possible choices: value $(SERVER_CITIES), choices available are Accra, Adelaide, Algiers, Amsterdam, Andorra la Vella, Astana, Asunción, Athens, Atlanta, Auckland, Baku, Bandar Seri Begawan, Bangkok, Barcelona, Beirut, Belgrade, Belmopan, Berlin, Bogota, Bratislava, Brisbane, Brussels, Bucharest, Budapest, Buenos Aires, Buffalo, Cairo, Caracas, Charlotte, Chicago, Chisinau, Colombo, Copenhagen, Dallas, Denver, Dhaka, Douglas, Dubai, Dublin, Edinburgh, Frankfurt, George Town, Glasgow, Guatemala City, Hagatna, Hamilton, Hanoi, Helsinki, Hong Kong, Istanbul, Jakarta, Johannesburg, Kansas City, Karachi, Kathmandu, Kingston, Kuala Lumpur, Kyiv, La Paz, Lagos, Lima, Lisbon, Ljubljana, London, Los Angeles, Luxembourg, Madrid, Manassas, Manchester, Manila, Marseille, Melbourne, Mexico, Miami, Milan, Monte Carlo, Montevideo, Montreal, Mumbai, Nairobi, Nassau, Naypyidaw, New York, Nicosia, Nuuk, Osaka, Oslo, Panama City, Paris, Perth, Phnom Penh, Phoenix, Podgorica, Port Moresby, Port of Spain, Prague, Quito, Rabat, Reykjavik, Riga, Rome, Saint Helier, Saint Louis, Salt Lake City, San Francisco, San Jose, San Juan, San Salvador, Santiago, Santo Domingo, Sao Paulo, Sarajevo, Seattle, Seoul, Singapore, Skopje, Sofia, Stockholm, Sydney, Taipei, Tallinn, Tashkent, Tbilisi, Tegucigalpa, Tel Aviv, Thimphu, Tirana, Tokyo, Toronto, Ulaanbaatar, Vaduz, Valletta, Vancouver, Vienna, Vientiane, Vilnius, Warsaw, Yerevan, Zagreb, Zurich
```

The only way we can get Gluetun to deploy without error is to revert back to using the original OPENVPN_USER and OPENVPN_PASSWORD variables, as per below.

```
      - OPENVPN_USER=${VPN_USERNAME:?err}
      - OPENVPN_PASSWORD=${VPN_PASSWORD:?err}
        #      - SERVER_COUNTRIES=$(SERVER_COUNTRIES)
      - SERVER_REGIONS=$(SERVER_REGIONS)
        #      - SERVER_CITIES=$(SERVER_CITIES)
        #      - SERVER_HOSTNAMES=$(SERVER_HOSTNAMES)
        #      - SERVER_CATEGORIES=$(SERVER_CATEGORIES)
```

Then we go back to the original WARNING messages in the logs, asking to update to the new variables.

```
WARN You are using the old environment variable OPENVPN_USER, please consider changing it to VPN_PORT_FORWARDING_USERNAME
WARN You are using the old environment variable OPENVPN_PASSWORD, please consider changing it to VPN_PORT_FORWARDING_PASSWORD
```

We have Gluetun running for the time being, however we'd like to make sure our users have an easy implementation to keep their issues down.

Thanks for the app and your support.

### Share your logs (at least 10 lines)

```plain text
username@vm1:/media-stack$ sudo docker compose --file docker-compose-gluetun.yaml --env-file docker-compose.env up
[+] Running 2/1
 ✔ Network mediastack  Created                                                                                                                                                                              0.1s
 ✔ Container gluetun   Created                                                                                                                                                                              0.0s
Attaching to gluetun
gluetun  | ========================================
gluetun  | ========================================
gluetun  | =============== gluetun ================
gluetun  | ========================================
gluetun  | =========== Made with ❤️ by ============
gluetun  | ======= https://github.com/qdm12 =======
gluetun  | ========================================
gluetun  | ========================================
gluetun  |
gluetun  | Running version latest built on 2024-07-12T19:57:02.146Z (commit 9d50c23)
gluetun  |
gluetun  | 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
gluetun  | 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
gluetun  | ✨ New feature? https://github.com/qdm12/gluetun/issues/new
gluetun  | ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
gluetun  | 💻 Email? quentin.mcgaw@gmail.com
gluetun  | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
gluetun  | 2024-07-14T14:44:39+10:00 WARN You are using the old environment variable OPENVPN_USER, please consider changing it to VPN_PORT_FORWARDING_USERNAME
gluetun  | 2024-07-14T14:44:39+10:00 WARN You are using the old environment variable OPENVPN_PASSWORD, please consider changing it to VPN_PORT_FORWARDING_PASSWORD
gluetun  | 2024-07-14T14:44:39+10:00 INFO [routing] default route found: interface eth0, gateway 10.20.30.1, assigned IP 10.20.30.2 and family v4
gluetun  | 2024-07-14T14:44:39+10:00 INFO [routing] local ethernet link found: eth0
gluetun  | 2024-07-14T14:44:39+10:00 INFO [routing] local ipnet found: 10.20.30.0/24
gluetun  | 2024-07-14T14:44:39+10:00 INFO [firewall] enabling...
gluetun  | 2024-07-14T14:44:39+10:00 INFO [firewall] enabled successfully
gluetun  | 2024-07-14T14:44:39+10:00 INFO [storage] merging by most recent 19425 hardcoded servers and 19425 servers read from /gluetun/servers.json
gluetun  | 2024-07-14T14:44:39+10:00 ERROR VPN settings: provider settings: server selection: for VPN service provider nordvpn: the country specified is not valid: value is not one of the possible choices: value $(SERVER_COUNTRIES), choices available are Albania, Algeria, Andorra, Argentina, Armenia, Australia, Austria, Azerbaijan, Bahamas, Bangladesh, Belgium, Belize, Bermuda, Bhutan, Bolivia, Bosnia and Herzegovina, Brazil, Brunei Darussalam, Bulgaria, Cambodia, Canada, Cayman Islands, Chile, Colombia, Costa Rica, Croatia, Cyprus, Czech Republic, Denmark, Dominican Republic, Ecuador, Egypt, El Salvador, Estonia, Finland, France, Georgia, Germany, Ghana, Greece, Greenland, Guam, Guatemala, Honduras, Hong Kong, Hungary, Iceland, India, Indonesia, Ireland, Isle of Man, Israel, Italy, Jamaica, Japan, Jersey, Kazakhstan, Kenya, Lao People's Democratic Republic, Latvia, Lebanon, Liechtenstein, Lithuania, Luxembourg, Malaysia, Malta, Mexico, Moldova, Monaco, Mongolia, Montenegro, Morocco, Myanmar, Nepal, Netherlands, New Zealand, Nigeria, North Macedonia, Norway, Pakistan, Panama, Papua New Guinea, Paraguay, Peru, Philippines, Poland, Portugal, Puerto Rico, Romania, Serbia, Singapore, Slovakia, Slovenia, South Africa, South Korea, Spain, Sri Lanka, Sweden, Switzerland, Taiwan, Thailand, Trinidad and Tobago, Turkey, Ukraine, United Arab Emirates, United Kingdom, United States, Uruguay, Uzbekistan, Venezuela, Vietnam
gluetun  | 2024-07-14T14:44:39+10:00 INFO Shutdown successful
gluetun exited with code 0
```

### Share your configuration

```yml
# ENV FILE:	docker-compose.env
#################################################################################
#################################################################################
#################################################################################
##
##  Docker Compose Environment Variable file for Jellyfin / *ARR Media Stack
##
##  Update any of the environment variables below as required.
##
##  It is highly recommended Linux users set up a "docker" user, so the
##  applications can access the local filesystem with this user's access
##  privileges. Use PUID / PGID to map user access between the Docker apps
##  and local filesystem.
##
##  The MediaStack Guide is located at https://mediastake.guide
##
#################################################################################
#################################################################################
#################################################################################

#Name of the project in Docker
COMPOSE_PROJECT_NAME=mediastack

# This is the network subnet which will be used inside the docker "media_network", change as required.
# LOCAL_SUBNET is your home network and is needed so the VPN client allows access to your home computers.
DOCKER_SUBNET=10.20.30.0/24
DOCKER_GATEWAY=10.20.30.1
LOCAL_SUBNET=192.168.1.0/24      # Update for your home network
LOCAL_DOCKER_IP=192.168.1.10     # Update for your home network

# Each of the "*ARR" applications have been configured so the theme can be changed to your needs.
# Refer to Theme Park for more info / options: https://docs.theme-park.dev/theme-options/aquamarine/
TP_THEME=nord

# These are the folders on your local host computer / NAS running docker, they MUST exist
# and have correct permissions for PUID and PGUI prior to running the docker compose.
#
# Use the commands in the Guide to create all the sub-folders in each of these folders.

# Host Data Folders - Will accept Linux, Windows, NAS folders.
# Make sure these folders exists before running the "docker compose" command.
FOLDER_FOR_MEDIA=/mediastack            # Update for your folders
FOLDER_FOR_DATA=/mediastackdata         # Update for your folders

# File access, date and time details for the containers / applications to use.
# Run "sudo id docker" on host computer to find PUID / PGID and update these to suit.
PUID=1000
PGID=1000
UMASK=0002
TIMEZONE=Europe/Zurich

# Update your own Internet VPN provide details below
# Online documentation: https://github.com/qdm12/gluetun-wiki/tree/main/setup/providers
VPN_TYPE=openvpn
VPN_SERVICE_PROVIDER=VPN provider name
VPN_USERNAME=<username from VPN provider>
VPN_PASSWORD=<password from VPN provider>

SERVER_COUNTRIES=       # Comma separated list of countries
SERVER_REGIONS=         # Comma separated list of regions
SERVER_CITIES=          # Comma separated list of server cities
SERVER_HOSTNAMES=       # Comma separated list of server hostnames
SERVER_CATEGORIES=      # Comma separated list of server categories

# Fill in this item ONLY if you're using a custom OpenVPN configuration
# Should be inside gluetun data folder - Example: /gluetun/custom-openvpn.conf
# You can then edit it inside the FOLDER_FOR_DATA location for gluetun.
OPENVPN_CUSTOM_CONFIG=

# Fill in these items ONLY if you change VPN_TYPE to "wireguard"
VPN_ENDPOINT_IP=
VPN_ENDPOINT_PORT=
WIREGUARD_PUBLIC_KEY=
WIREGUARD_PRIVATE_KEY=
WIREGUARD_PRESHARED_KEY=
WIREGUARD_ADDRESSES=

# These are the default ports used to access each of the application in your web browser.
# You can safely change these if you need, but they can't conflict with other active ports.
QBIT_PORT_TCP=6881
QBIT_PORT_UDP=6881
FLARESOLVERR_PORT=8191

TDARR_SERVER_PORT=8266
WEBUI_PORT_TDARR=8265

WEBUI_PORT_BAZARR=6767
WEBUI_PORT_DDNS_UPDATER=6500
WEBUI_PORT_JELLYFIN=8096
WEBUI_PORT_JELLYSEERR=5055
WEBUI_PORT_LIDARR=8686
WEBUI_PORT_MYLAR3=8090
WEBUI_PORT_PORTAINER=9443
WEBUI_PORT_PROWLARR=9696
WEBUI_PORT_QBITTORRENT=8200
WEBUI_PORT_RADARR=7878
WEBUI_PORT_READARR=8787
WEBUI_PORT_SONARR=8989
WEBUI_PORT_SABNZBD=8100
WEBUI_PORT_WHISPARR=6969

# SWAG is configured for Reverse Proxy. Set your Internet gateway to redirect incoming ports 80 and 443
# to the ports used below (using Docker IP Address), and they will be translated back to 80 and 443 by SWAG.
# Change these port numbers if you have conflicting services running on the Docker host computer.

REVERSE_PROXY_PORT_HTTP=5080
REVERSE_PROXY_PORT_HTTPS=5443

# SWAG REVERSE PROXY SETTINGS:
URL=your-domain-name-goes-here.com
SUBDOMAINS=wildcard
VALIDATION=dns
DNSPLUGIN=cloudflare
CERTPROVIDER=
PROPAGATION=
DUCKDNSTOKEN=
EMAIL=
ONLY_SUBDOMAINS=false
EXTRA_DOMAINS=
STAGING=false



# YAML FILE: docker-compose-gluetun.yaml
###########################################################################
###########################################################################
##
##  Docker Compose File: Gluetun (qmcgaw)
##  Function: VPN Client
##
##  Documentation: https://github.com/qdm12/gluetun/wiki
##
###########################################################################
###########################################################################
networks:
  mediastack:
    name: mediastack
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${DOCKER_SUBNET:?err}
        gateway: ${DOCKER_GATEWAY:?err}

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8888:8888/tcp"                         # Gluetun Local Network HTTP proxy
      - "8388:8388/tcp"                         # Gluetun Local Network Shadowsocks
      - "8388:8388/udp"                         # Gluetun Local Network Shadowsocks

# Comment out lines below if they are not going to use Gluetun VPN for Internet connection:

      - "${WEBUI_PORT_BAZARR:?err}:6767"        # WebUI Portal: Bazarr
      - "${WEBUI_PORT_JELLYFIN:?err}:8096"      # WebUI Portal: Jellyfin
      - "${WEBUI_PORT_JELLYSEERR:?err}:5055"    # WebUI Portal: Jellyseerr
      - "${WEBUI_PORT_LIDARR:?err}:8686"        # WebUI Portal: Lidarr
      - "${WEBUI_PORT_MYLAR3:?err}:8090"        # WebUI Portal: Mylar3
      - "${WEBUI_PORT_PROWLARR:?err}:9696"      # WebUI Portal: Prowlarr
      - "${WEBUI_PORT_RADARR:?err}:7878"        # WebUI Portal: Radarr
      - "${WEBUI_PORT_READARR:?err}:8787"       # WebUI Portal: Readarr
      - "${WEBUI_PORT_SABNZBD:?err}:8080"       # WebUI Portal: SABnzbd
      - "${WEBUI_PORT_SONARR:?err}:8989"        # WebUI Portal: Sonarr
      - "${WEBUI_PORT_WHISPARR:?err}:6969"      # WebUI Portal: Whisparr
      - "${WEBUI_PORT_QBITTORRENT:?err}:${WEBUI_PORT_QBITTORRENT:?err}"   # WebUI Portal: qBittorrent

      - "${QBIT_PORT_TCP:?err}:6881/tcp"        # Transmission Torrent Port TCP
      - "${QBIT_PORT_UDP:?err}:6881/udp"        # Transmission Torrent Port UDP
      - "${FLARESOLVERR_PORT:?err}:8191"        # Service Port: FlareSolverr
      
      - "${TDARR_SERVER_PORT:?err}:${TDARR_SERVER_PORT:?err}"   # Tdarr: Server Port
      - "${WEBUI_PORT_TDARR:?err}:${WEBUI_PORT_TDARR:?err}"     # Tdarr: WebUI Portal

    volumes:
      - ${FOLDER_FOR_DATA:?err}/gluetun:/gluetun
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:?err}
      - VPN_PORT_FORWARDING_USERNAME=${VPN_USERNAME:?err}
      - VPN_PORT_FORWARDING_PASSWORD=${VPN_PASSWORD:?err}
      - SERVER_COUNTRIES=$(SERVER_COUNTRIES)
      - SERVER_REGIONS=$(SERVER_REGIONS)
      - SERVER_CITIES=$(SERVER_CITIES)
      - SERVER_HOSTNAMES=$(SERVER_HOSTNAMES)
      - SERVER_CATEGORIES=$(SERVER_CATEGORIES)
      - FIREWALL_OUTBOUND_SUBNETS=${LOCAL_SUBNET:?err}
      - OPENVPN_CUSTOM_CONFIG=${OPENVPN_CUSTOM_CONFIG}
      - VPN_TYPE=${VPN_TYPE}
      - VPN_ENDPOINT_IP=${VPN_ENDPOINT_IP}
      - VPN_ENDPOINT_PORT=${VPN_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - HTTPPROXY=on
      - SHADOWSOCKS=on

# NOTE: Gluetun VPN container MUST ONLY connect to the mediastack network

    networks:
      - mediastack
```
