### ISSUE TITLE
Bug: VPN Port Forwarding Doesn't Work When Specifying Multiple Ports

### ISSUE THREAD

**Issue by yuljk** [qdm12/gluetun#2361]
### Is this urgent?

No

### Host OS

Debian 12

### CPU arch

x86_64

### VPN service provider

AirVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

latest

### What's the problem 🤔

Hi - I'm using AirVPN and have configured my compose as per the documentation.  However, I have found that when specifying multiple VPN ports with e.g FIREWALL_VPN_INPUT_PORTS=56887,57889 I get a 'connection timed out' message in the port checker in the client area of AirVPN.

If I specify a single port, it shows as open.

My syntax looks, correct so not sure what is happening here.

Any help would be much appreciated.

### Share your logs (at least 10 lines)

```plain text
n
```

### Share your configuration

```yml
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1001
      - PGID=998
      - TZ=Europe/London
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_PRESHARED_KEY=
      - WIREGUARD_ADDRESSES=10.170.248.7
      - SERVER_COUNTRIES=United Kingdom
      - FIREWALL_VPN_INPUT_PORTS=44108
      - UPDATER_PERIOD=24h
    volumes:
      - /opt/docker/gluetun:/gluetun
      - /lib/modules:/lib/modules:ro
    ports:
      - 9696:9696
      - 51413:51413
      - 51413:51413/udp
      - 7878:7878
      - 9091:9091
      - 8989:8989
      - 8090:8090
      - 8080:8080
      - 8686:8686
      - 6767:6767
      - 5030:5030
      - 5031:5031
      - 44108:44108
      - 50300:50300
    restart: unless-stopped
```
