### ISSUE TITLE
Bug: Can not connect to host.docker.internal (external localhost) from service mapped to glueutun

### ISSUE THREAD

**Issue by adiberk** [qdm12/gluetun#2362]
### Is this urgent?

Yes

### Host OS

Windows

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

latest (image: qmcgaw/gluetun)

### What's the problem 🤔

  I have the following service 
```
  random_service:
    container_name: random_service
........
    network_mode: "service:gluetun"
```

Here is my glueutun service
```
  gluetun:
    container_name: gluetun
    hostname: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=6EpmqdMbPTYDa5fELmziXXYq
      - OPENVPN_PASSWORD=B5s8PvVsMeEobPQtRg5EuHN2
      - SERVER_COUNTRIES=Switzerland
    ports:
      - "6811:6811"
```

Everything works fine in terms of access my "random_service" via vpn.  However if I try to access external localhost via "host.docker.internal" inside "random_service" I hit an issue as I can't resolve this

### Share your logs (at least 10 lines)

```plain text
No logs in gluetun for this
```
