### ISSUE TITLE
Feature request/Question: Multiple wireguard config files ?

### ISSUE THREAD

**Issue by TheRealBix** [qdm12/gluetun#2373]
### What's the feature 🧐

Currently gluetun is able to switch between openvpn servers on unhealthy states (right now I use SERVER_HOSTNAMES setting to achieve this with cherry picked servers. Would it be possible to do the same with wireguard config files like wg0.conf, wg1.conf etc.. 
Or maybe there's already a way to do this I'm unaware of ?

**Comment by skedastically** [comment]
I found a hacky way to do this by symlinking a different .conf file to `wg0.conf` before executing the `/gluetun-entrypoint` binary. This requires redefining the entrypoint command to run a shell script, and restarting your container when a defined healthcheck is triggered.

Suppose you have `wireguard-01.conf`, `wireguard-02.conf`, and `wireguard-03.conf` in your `/gluetun/wireguard` directory. Add the following script in `/gluetun/startup.sh`:

```sh
#!/bin/sh

WGCONF=/gluetun/wireguard/wg0.conf
# Unlinking the old wg0.conf
unlink $WGCONF

# Randomly choosing a new conf file from the wireguard* list
# For me this is enough
NEWCONF=$(ls /gluetun/wireguard/wireguard-*.conf | shuf -n 1)

# Make that the new wg0.conf
ln -T $NEWCONF $WGCONF

# Executing the binary

/gluetun-entrypoint
```

Then execute it on gluetun startup with the following docker-compose options:
```yaml
services:
  gluetun:
    ...
    healthcheck:
      # If network is unreachable, exit 1 to indicate unhealthy container
      test: wget -O- https://ipinfo.io || exit 1
      # Tune these as needed
      interval: 20s
      timeout: 5s
      retries: 2
    
    # Run the shell script as the entrypoint
    entrypoint: '/bin/sh'
    command: '/gluetun/startup.sh'    
```

AFAIK Docker doesn't natively restart unhealthy containers, so feel free to use one of the following [methods](https://stackoverflow.com/questions/47088261/restarting-an-unhealthy-docker-container-based-on-healthcheck). For me a cron job would do.

**Comment by TheRealBix** [comment]
That's a clever way i'll be happy to try,  thanks !

**Comment by TheRealBix** [comment]
Oops, it doesn't work... 

```
ln: /gluetun/wireguard/wireguard-01.conf : No such file or directory
unlink: can't remove file '/gluetun/wireguard/wg0.conf ': No such file or directory
```

I sure have the wireguard folder and glutun volume mounted, when manually edited the wg0.conf is read by gluetun.
If you have a clue...

**Comment by ribas89** [comment]
I hit the same issue and used @stratself approach, which worked perfectly. I additionally added some logging and a small state file so the configs cycle in order (01 -> 02 -> 03) instead of randomly. I also used the healthcheck to update my IP on my DNS server.

https://gist.github.com/ribas89/0a6d6a2c1b11765d79eb696a0ef31918

my docker compose config
```yml
  gluetunw:
    image: qmcgaw/gluetun:latest
    container_name: gluetunw
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8080:8080"
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - HEALTH_RESTART_VPN=on
      - TZ=America/Sao_Paulo
    healthcheck:
      test: wget -qO- https://link-ip.nextdns.io/change-this-hash || exit 1
      interval: 10m
      timeout: 10s
      retries: 2
      start_period: 30s
    entrypoint: /bin/sh
    command: /gluetun/wireguardfile.sh
    restart: unless-stopped
```
