### ISSUE TITLE
Bug: `latest` tag in docker image points to unstable version

### ISSUE THREAD

**Issue by marcosvrs** [qdm12/gluetun#2387]
### Is this urgent?

None

### CPU arch

None

### VPN service provider

NordVPN

### What are you using to run the container

docker run

### What is the version of Gluetun

v3.38.0

### What's the problem 🤔

The `latest` tag in docker image points to unstable version:
![image](https://github.com/user-attachments/assets/5051fe95-3263-4dbc-a481-2470cd188a91)
![image](https://github.com/user-attachments/assets/2c6b0d76-74e1-46a5-bcdd-ecb20550c80c)

It should point to the latest stable one, or? (v3.38.0)

### Share your logs (at least 10 lines)

```plain text
gluetun-1  | ========================================
gluetun-1  | ========================================
gluetun-1  | =============== gluetun ================
gluetun-1  | ========================================
gluetun-1  | =========== Made with ❤️ by ============
gluetun-1  | ======= https://github.com/qdm12 =======
gluetun-1  | ========================================
gluetun-1  | ========================================
gluetun-1  | 
gluetun-1  | Running version latest built on 2024-07-30T20:03:23.398Z (commit 7bc2972)
gluetun-1  | 
gluetun-1  | 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
gluetun-1  | 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
gluetun-1  | ✨ New feature? https://github.com/qdm12/gluetun/issues/new
gluetun-1  | ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
gluetun-1  | 💻 Email? quentin.mcgaw@gmail.com
gluetun-1  | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    # container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /yourpath:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=ivpn
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      # - WIREGUARD_ADDRESSES=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=
```
