### ISSUE TITLE
Bug: Wireguard info doesn't work on the Control Server API

### ISSUE THREAD

**Issue by samtate** [qdm12/gluetun#2391]
### Is this urgent?

No

### Host OS

Debian 12 (virtualised in Proxmox)

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2024-08-01T11:55:38.342Z (commit 34e8f5f)

### What's the problem 🤔

I am trying to find my forwarded port using the endpoint `/v1/openvpn/portforwarded` as stated on the Wiki, however I always get a response of `{"port":0}`. Similarly when using the endpoint  `/v1/openvpn/status` I always get a response of `{"status":"stopped"}`.

However, the endpoint `/v1/publicip/ip` does work and return the IP and other data as expected. The connection works other than this, so I think there is an issue with the openvpn endpoint for wireguard connections?

I am using ProtonVPN via Wireguard using the custom provider as outlined on the Wiki.

### Share your logs (at least 10 lines)

```plain text
gluetun                     | 2024-08-02T14:06:57+01:00 INFO [http server] 200 GET /status wrote 21B to 192.168.86.88:37044 in 33.956µs
gluetun                     | 2024-08-02T14:06:57+01:00 INFO [http server] 200 GET /status wrote 21B to 192.168.86.88:37044 in 15.839µs
gluetun                     | 2024-08-02T14:06:57+01:00 INFO [http server] 200 GET /status wrote 21B to 192.168.86.88:37044 in 17.371µs
gluetun                     | 2024-08-02T14:06:57+01:00 INFO [http server] 200 GET /status wrote 21B to 192.168.86.88:37044 in 16.661µs
gluetun                     | 2024-08-02T14:06:58+01:00 INFO [http server] 200 GET /status wrote 21B to 192.168.86.88:37044 in 24.243µs
gluetun                     | 2024-08-02T14:06:58+01:00 INFO [http server] 200 GET /status wrote 21B to 192.168.86.88:37044 in 17.233µs
gluetun                     | 2024-08-02T14:06:58+01:00 INFO [http server] 200 GET /status wrote 21B to 192.168.86.88:37044 in 17.215µs
gluetun                     | 2024-08-02T14:06:58+01:00 INFO [http server] 200 GET /status wrote 21B to 192.168.86.88:37044 in 18.046µs
gluetun                     | 2024-08-02T14:06:59+01:00 INFO [http server] 200 GET /status wrote 21B to 192.168.86.88:37044 in 26.882µs
gluetun                     | 2024-08-02T14:06:59+01:00 INFO [http server] 200 GET /status wrote 21B to 192.168.86.88:37044 in 20.99µs
gluetun                     | 2024-08-02T14:07:13+01:00 INFO [http server] 200 GET /portforwarded wrote 11B to 192.168.86.88:59334 in 20.011µs
gluetun                     | 2024-08-02T14:07:20+01:00 INFO [http server] 200 GET /ip wrote 259B to 192.168.86.88:59344 in 28.535µs
```

### Share your configuration

```yml
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8001:8000/tcp
      - 8888:8888/tcp # HTTP proxy
    volumes:
      - /mnt/NAS/gluetun:/gluetun
    environment:
      - TZ=Europe/London #CHANGE_TO_YOUR_TZ
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=xx.xx.xx.xx
      - VPN_ENDPOINT_PORT=51820
      - WIREGUARD_PUBLIC_KEY=xxx
      - WIREGUARD_PRIVATE_KEY=xxx
      - WIREGUARD_ADDRESSES=xx.xx.xx.xx
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - HTTPPROXY=off #change to on if you wish to enable
      - SHADOWSOCKS=off #change to on if you wish to enable
      - FIREWALL_OUTBOUND_SUBNETS=172.20.0.0/16,192.168.86.0/24 #change this in line with your subnet see note on guide.
      - UPDATER_PERIOD=24h
    labels:
      - com.centurylinklabs.watchtower.enable=false
    security_opt:
      - no-new-privileges:true
    restart: always
```
