### ISSUE TITLE
Bug: Mullvad has Turkey servers but Gluetun says they are not valid

### ISSUE THREAD

**Issue by xrudiitx** [qdm12/gluetun#2433]
### Is this urgent?

Yes

### Host OS

Ubuntu 22.04.4 LTS

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

docker-compose

### What is the version of Gluetun

qmcgaw/gluetun:latest (Fri Aug 23 09:25:08 AM UTC 2024)

### What's the problem 🤔

Hi, Mullvad has Turkey servers and servers are located in Istanbul. There are two servers in Istanbul that run by Mullvad.

Can you fix or update your code to supporting Turkey/Istanbul server for Mullvad?

Here is Istanbul servers: (source: https://mullvad.net/en/servers | Turkey)

SERVER 1:

| Name| Description |
| ----------- | ----------- |
| Domain name | tr-ist-wg-001.relays.mullvad.net | 
| IPv4 | 149.102.229.129 | 
| IPv6|  2a02:6ea0:e813::f001 | 
| public key | jPhK/ziQfJ1Z5GCPj+qR3A7YV2mIQSQtEPCRuG7TUW8= | 
| socks5 |  proxy address tr-ist-wg-socks5-001.relays.mullvad.net:1080 | 
| multihop port | 3325 | 

SERVER2:

| Name| Description |
| ----------- | ----------- |
| Domain name | tr-ist-wg-002.relays.mullvad.net |
| IPv4 | 149.102.229.158| 
| IPv6 | 2a02:6ea0:e813:1::f001| 
| public key | TDHn9OvFYoHh9nwlYG7OCpPRvCjfODUOksSQPzhguTg=| 
| socks5 proxy address | tr-ist-wg-socks5-002.relays.mullvad.net:1080| 
| multihop port | 3326| 

### Share your logs (at least 10 lines)

```plain text
gluetun-1            | 2024-08-23T09:27:53Z INFO [routing] default route found: interface eth0, gateway 172.31.0.1, assigned IP 172.31.0.2 and family v4
gluetun-1            | 2024-08-23T09:27:53Z INFO [routing] local ethernet link found: eth0
gluetun-1            | 2024-08-23T09:27:53Z INFO [routing] local ipnet found: 172.31.0.0/16
gluetun-1            | 2024-08-23T09:27:53Z INFO [firewall] enabling...
gluetun-1            | 2024-08-23T09:27:53Z INFO [firewall] enabled successfully
gluetun-1            | 2024-08-23T09:27:54Z INFO [storage] creating /gluetun/servers.json with 20480 hardcoded servers
gluetun-1            | 2024-08-23T09:27:54Z ERROR VPN settings: provider settings: server selection: for VPN service provider mullvad: the city specified is not valid: value is not one of the possible choices: none of Istanbul is one of the choices available Adelaide, Amsterdam, Ashburn VA, Athens, Atlanta GA, Auckland, Belgrade, Berlin, Bogota, Bratislava, Brisbane, Brussels, Bucharest, Budapest, Calgary, Chicago IL, Chisinau, Copenhagen, Dallas TX, Denver CO, Dubai, Dublin, Dusseldorf, Frankfurt, Gothenburg, Helsinki, Hong Kong, Houston TX, Johannesburg, Kyiv, Lisbon, London, Los Angeles CA, Luxembourg, Madrid, Malmö, Manchester, Marseille, Melbourne, Miami FL, Milan, Montreal, New York NY, Osaka, Oslo, Paris, Perth, Phoenix AZ, Prague, Raleigh NC, Riga, Salt Lake City UT, San Jose CA, Sao Paulo, Seattle WA, Secaucus NJ, Singapore, Skopje, Sofia, Stavanger, Stockholm, Sydney, Tallinn, Tel Aviv, Tirana, Tokyo, Toronto, Vancouver, Vienna, Warsaw, Zagreb, Zurich


OR


gluetun-1            | 2024-08-23T09:28:28Z INFO [routing] default route found: interface eth0, gateway 172.31.0.1, assigned IP 172.31.0.2 and family v4
gluetun-1            | 2024-08-23T09:28:28Z INFO [routing] local ethernet link found: eth0
gluetun-1            | 2024-08-23T09:28:28Z INFO [routing] local ipnet found: 172.31.0.0/16
gluetun-1            | 2024-08-23T09:28:28Z INFO [firewall] enabling...
gluetun-1            | 2024-08-23T09:28:28Z INFO [firewall] enabled successfully
gluetun-1            | 2024-08-23T09:28:29Z INFO [storage] creating /gluetun/servers.json with 20480 hardcoded servers
gluetun-1            | 2024-08-23T09:28:29Z ERROR VPN settings: provider settings: server selection: for VPN service provider mullvad: the country specified is not valid: value is not one of the possible choices: none of Turkey is one of the choices available Albania, Australia, Austria, Belgium, Brazil, Bulgaria, Canada, Colombia, Croatia, Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hong Kong, Hungary, Ireland, Israel, Italy, Japan, Latvia, Luxembourg, Moldova, Netherlands, New Zealand, North Macedonia, Norway, Poland, Portugal, Romania, Serbia, Singapore, Slovakia, South Africa, Spain, Sweden, Switzerland, UK, USA, Ukraine, United Arab Emirates
```

### Share your configuration

```yml
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY="SECRET1"
      - WIREGUARD_ADDRESSES="X.X.X.X/32"
      - SERVER_CITIES=Istanbul
      - SHADOWSOCKS=on
      - SHADOWSOCKS_PASSWORD="SECRET2"
      - SHADOWSOCKS_CIPHER="chacha20-ietf-poly1305"
    restart: always
  shadowsocks-libev:
    image: shadowsocks/shadowsocks-libev
    command: ss-local -s "gluetun" -p 8388 -l 1083 -k "SECRET2" -m "chacha20-ietf-poly1305" -b "0.0.0.0" -t 300
    ports:
      - 1083:1083
    restart: always
```
