### ISSUE TITLE
Bug: List of Privado Countries limited

### ISSUE THREAD

**Issue by Fleggy** [qdm12/gluetun#2439]
### Is this urgent?

No

### Host OS

OpenMediaVault 6

### CPU arch

x86_64

### VPN service provider

Privado

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2024-08-23T13:50:02.262Z (commit ff7cadb)

### What's the problem 🤔

I am running Privado VPN and it is giving me an error that only United States, Germany, Hungary and Netherlands are available countries. Up until now, I have been using Australia or New Zealand. I have manually updated the provider list but it has not helped

### Share your logs (at least 10 lines)

```plain text
Running version latest built on 2024-08-23T13:50:02.262Z (commit ff7cadb)

🔧 Need help? ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new/choose
🐛 Bug? ✨ New feature? https://github.com/qdm12/gluetun/issues/new/choose
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2024-08-25T08:08:48+10:00 INFO [routing] default route found: interface eth0, gateway 172.17.0.1, assigned IP 172.17.0.2 and family v4
2024-08-25T08:08:48+10:00 INFO [routing] local ethernet link found: eth0
2024-08-25T08:08:48+10:00 INFO [routing] local ipnet found: 172.17.0.0/16
2024-08-25T08:08:48+10:00 INFO [firewall] enabling...
2024-08-25T08:08:48+10:00 INFO [firewall] enabled successfully
2024-08-25T08:08:49+10:00 INFO [storage] merging by most recent 20480 hardcoded servers and 20483 servers read from /gluetun/servers.json
2024-08-25T08:08:49+10:00 INFO [storage] Using privado servers from file which are 5 days more recent
2024-08-25T08:08:49+10:00 ERROR VPN settings: provider settings: server selection: for VPN service provider privado: the country specified is not valid: value is not one of the possible choices: none of AUSTRALIA is one of the choices available Germany, Hungary, Netherlands, United States
2024-08-25T08:08:49+10:00 INFO Shutdown successful

END OF LINE
```

### Share your configuration

```yml
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge	#depends on your setup, I use docker on synology
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8001:8001/tcp # Built-in HTTP control server
      - 8080:8080 # sabnzbd
      - 9090:9090 # sabnzbd
      - 8191:8191 # flaresolverr
      - 9117:9117 # jackett
      - 8282:8282 # qbittorrent
      - 6881:6881 # qbittorrent
      - 6881:6881/udp # qbittorrent
    volumes:
      - /srv/dev-disk-by-uuid-68b6b54d-7eda-4545-b0cb-0100bff5f4fe/Config/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=privado
      - OPENVPN_USER=xxxxxx
      - OPENVPN_PASSWORD=xxxxxx
      - SERVER_COUNTRIES=AUSTRALIA
      - UPDATER_PERIOD=24h
      - HTTPPROXY=on
      - PUID=1000				#your local user ID (this can be the same for all following containers)
      - PGID=100				#your local users group (this can be the same for all following containers)
      - TZ=Australia/Melbourne			#for acurate logs (change to your Timezone)
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"    #this is my watchtower label to automatically update the container

#-----SABnzbd
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Australia/Melbourne
    volumes:
      - /srv/dev-disk-by-uuid-68b6b54d-7eda-4545-b0cb-0100bff5f4fe/downloads:/downloads
      - /srv/dev-disk-by-uuid-68b6b54d-7eda-4545-b0cb-0100bff5f4fe/incomplete-downloads:/incomplete-downloads
      - /srv/dev-disk-by-uuid-68b6b54d-7eda-4545-b0cb-0100bff5f4fe/Config/sabnzbd:/config
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"  
      
#-----Flaresolverr    
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Australia/Melbourne
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      
#-----Jackett
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Australia/Melbourne
    volumes:
      - /srv/dev-disk-by-uuid-68b6b54d-7eda-4545-b0cb-0100bff5f4fe/Config/jackett:/config
      - /srv/dev-disk-by-uuid-68b6b54d-7eda-4545-b0cb-0100bff5f4fe/downloads:/downloads
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  
#-----qBitTorrent  
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Australia/Melbourne
      - WEBUI_PORT=8282
    volumes:
      - /srv/dev-disk-by-uuid-68b6b54d-7eda-4545-b0cb-0100bff5f4fe/Config/qbittorrent:/config
      - /srv/dev-disk-by-uuid-68b6b54d-7eda-4545-b0cb-0100bff5f4fe/downloads:/downloads
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```
