### ISSUE TITLE
Bug: listing routes: address family not supported by protocol

### ISSUE THREAD

**Issue by padermon** [qdm12/gluetun#2448]
### Is this urgent?

Yes

### Host OS

Ubuntu 22.04

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2024-08-25T07:04:32.409Z (commit 01fa993)

### What's the problem 🤔

When I try to run with docker compose up, I immediately receive the error `listing routes: address family not supported by protocol`

### Share your logs (at least 10 lines)

```plain text
gluetun  | ========================================
gluetun  | ========================================
gluetun  | =============== gluetun ================
gluetun  | ========================================
gluetun  | =========== Made with ❤️ by ============
gluetun  | ======= https://github.com/qdm12 =======
gluetun  | ========================================
gluetun  | ========================================
gluetun  | 
gluetun  | Running version latest built on 2024-08-25T07:04:32.409Z (commit 01fa993)
gluetun  | 
gluetun  | 🔧 Need help? ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new/choose
gluetun  | 🐛 Bug? ✨ New feature? https://github.com/qdm12/gluetun/issues/new/choose
gluetun  | 💻 Email? quentin.mcgaw@gmail.com
gluetun  | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
gluetun  | 2024-08-29T11:01:18+02:00 ERROR listing routes: address family not supported by protocol
gluetun  | 2024-08-29T11:01:18+02:00 INFO Shutdown successful
```

### Share your configuration

```yml
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}   
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - TZ=${TZ}
      - LOG_LEVEL=DEBUG
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
```
