### ISSUE TITLE
Feature request: SOCKS5 for outgoing traffic

### ISSUE THREAD

**Issue by christianmerges** [qdm12/gluetun#2459]
### What's the feature 🧐

Using gluetun infront of other containers is nice because it is impossible for other containers to reach the outside world without using gluetun. Gluetun is made to use wireguard or openvpn tunnel to go out. Is it possible to use SOCKS as well? We have a requirement, where we need to use residential IP addresses from different countries, so we can't use a public vpn provider for this. So gluetun would get all the traffic as usual, but would forward it to a SOCKS5 Proxy and also forward DNS-Requests to the SOCKS5 proxy. Is that feasable? I know SOCKS5 is unencrypted, but for this requirement it's not a problem at all.

**Comment by qdm12** [comment]
> We have a requirement, where we need to use residential IP addresses from different countries, so we can't use a public vpn provider for this. 

Why not then use a Socks5 client container and use it as the network stack of other containers??

**Comment by christianmerges** [comment]
This was my first idea, but didn't find anything that was working 😔.

**Comment by qdm12** [comment]
Actually socks5 is above the layer of VPNs, so it won't tunnel the entire traffic of the host. For example browsers can use it, but it's not at the application layer. You would need some VPN to route all the traffic I think, socks5 won't cut it (similar to an http proxy), unless you run all your requests through for example a browser implementing a socks5 client.

**Comment by christianmerges** [comment]
The Android App shadowrocket does exacctly this. It creates a Tunnel to a locket socket on the device itself (the app) so all the traffic of all apps goes to shadowrocket app. And then it leaves the app throu the socks proxy. Exactly this i want to do for a docker container to feel more safe, than setting the socks settings within the application and some applications don't even support socks protocol. Usaually only browsers.

**Comment by qdm12** [comment]
I think that would fit: https://code.google.com/archive/p/badvpn/wikis/tun2socks.wiki perhaps?

**Comment by christianmerges** [comment]
I did it with redsocks

**Comment by BasToTheMax** [comment]
> I did it with redsocks

Can you show me how you did it? Looking to do the same

**Comment by christianmerges** [comment]
> > I did it with redsocks [@christianmerges](https://github.com/christianmerges)
> 
> Can you show me how you did it? Looking to do the same

```yaml
services:   
  someservice:
    network_mode: "service:someservice-socks"
    
  someservice-socks:
    container_name: someservice-socks
    image: mietzen/redsocks-proxy:stable
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - PROXY_SERVER=$IP
      - DNSCrypt_Active=false
      - PROXY_PORT=5005
      #- ALLOW_DOCKER_CIDR=true
      #- REDIRECT_PORTS=all
      #- LOGIN=$USER
      #- PASSWORD=$PW
    dns:
     - 8.8.8.8
     - 9.9.9.9
    ports:
      - 80:80
```

I did not test this, because I have automatic deployment with a lot of compose extends. But should be working like that.
