### ISSUE TITLE
UDPv6 []: Address not available (fd=3,code=99)Bug: 

### ISSUE THREAD

**Issue by mikul9** [qdm12/gluetun#2467]
### Is this urgent?

No

### Host OS

DSM 7.21 (Synology)

### CPU arch

x86_64

### VPN service provider

AirVPN

### What are you using to run the container

docker run

### What is the version of Gluetun

Running version latest built on 2024-08-25T07:04:32.409Z (commit 01fa993) 

### What's the problem 🤔

Failure to connect to AirVPN after update to the latest version. The problem persists with the firewall disabled. Moving back to pr-2285 works.

### Share your logs (at least 10 lines)

```plain text
Stuck in this loop:

2024/09/05 11:00:22	stdout	2024-09-05T11:00:22-04:00 INFO [firewall] removing allowed port 13482...
2024/09/05 11:00:22	stdout	2024-09-05T11:00:22-04:00 INFO [vpn] stopping
2024/09/05 11:00:22	stdout	2024-09-05T11:00:22-04:00 INFO [healthcheck] DO NOT OPEN AN ISSUE UNLESS YOU READ AND TRIED EACH POSSIBLE SOLUTION
2024/09/05 11:00:22	stdout	2024-09-05T11:00:22-04:00 INFO [healthcheck] 👉 See https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md
2024/09/05 11:00:22	stdout	2024-09-05T11:00:22-04:00 INFO [healthcheck] program has been unhealthy for 11s: restarting VPN
2024/09/05 11:00:18	stdout	2024-09-05T11:00:18-04:00 INFO [openvpn] write UDPv6 []: Address not available (fd=3,code=99)
2024/09/05 11:00:13	stdout	2024-09-05T11:00:13-04:00 INFO [openvpn] write UDPv6 []: Address not available (fd=3,code=99)
2024/09/05 11:00:11	stdout	2024-09-05T11:00:11-04:00 INFO [openvpn] write UDPv6 []: Address not available (fd=3,code=99)
2024/09/05 11:00:11	stdout	2024-09-05T11:00:11-04:00 INFO [openvpn] UDPv6 link remote: [AF_INET6]2001:ac8:40:8:6e2e:89db:741:eecb:1194
2024/09/05 11:00:11	stdout	2024-09-05T11:00:11-04:00 INFO [openvpn] UDPv6 link local: (not bound)
2024/09/05 11:00:11	stdout	2024-09-05T11:00:11-04:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET6]2001:ac8:40:8:6e2e:89db:741:eecb:1194
2024/09/05 11:00:11	stdout	2024-09-05T11:00:11-04:00 INFO [openvpn] library versions: OpenSSL 3.3.1 4 Jun 2024, LZO 2.10
2024/09/05 11:00:11	stdout	2024-09-05T11:00:11-04:00 INFO [openvpn] OpenVPN 2.6.11 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD]
2024/09/05 11:00:11	stdout	2024-09-05T11:00:11-04:00 INFO [firewall] allowing VPN connection...
2024/09/05 11:00:11	stdout	2024-09-05T11:00:11-04:00 INFO [vpn] starting
```

### Share your configuration

```yml
gluetun:
    image: qmcgaw/gluetun:latest   
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp 
      - 8388:8388/tcp 
      - 8388:8388/udp 
      - 8090:8090/tcp
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      - PUID=1030 
      - PGID=65526 
      - TZ=America/New_York 
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=openvpn  
      - OPENVPN_USER=UserName
      - OPENVPN_PASSWORD=PaSsWoRd
      - HTTPPROXY=off 
      - SHADOWSOCKS=off 
      - FIREWALL_OUTBOUND_SUBNETS=181.20.0.0/16,192.168.1.0/24 
      - FIREWALL_VPN_INPUT_PORTS=12462 
      - UPDATER_PERIOD=24h
    network_mode: synobridge
    labels:
      - com.centurylinklabs.watchtower.enable=false
    security_opt:
      - no-new-privileges:true
    restart: always
```

**Comment by caballinger** [comment]
Having the exact same issue here with openvpn connections on airvpn. Wireguard connections on airvpn continue to work just fine on the latest image.

**Comment by qdm12** [comment]
This is due to Openvpn trying to use IPv6, and your Docker setup probably doesn't support it. It could also be due to the upgrade from openvpn 2.5 to 2.6.

1. If you run with `LOG_LEVEL=debug`, what IPv6 relevant lines do you get (for example `IPv6 is supported by link ....`)?
2. What happens if you run image `qmcgaw/gluetun:v3.39.0` with `OPENVPN_VERSION=2.5`?
3. What happens if you run image `qmcgaw/gluetun:v3.38.1`?

also please use v3.x.x tagged images, not `pr-2285`. I have no idea what that image tag (for PR #2285) and it's hard for me to debug.

**Comment by caballinger** [comment]
qmcgaw/gluetun:v3.39.0 with OPENVPN_VERSION=2.5: Same issue
qmcgaw/gluetun:v3.38.1 without OPENVPN_VERSION=2.5: Working

**Comment by VonPuffelen** [comment]
Same issue, i go back to V3.38.0 and no problems anymore.

**Comment by olivier0013** [comment]
Hi, I have the exact same issue with v3.40, it works with v3.39.1 and previous.

**Comment by mikul9** [comment]
It has been 7 months, and this is still a problem.

**Comment by Staubgeborener** [comment]
Same issue here with AirVPN, but v3.40 nor v3.39.1 is solving it for me. I need to go back to v3.38.0 to get rid of it.

Otherwise, I am forced to disable ipv6 with `net.ipv6.conf.all.disable_ipv6=1`

Oh, and btw i can trigger this issue no matter which version i am using while restarting the service with the api like
`docker exec Gluetun /usr/bin/wget -qO- --method=PUT --body-data='{"status":"restart"}' --header='x-api-key: API-KEY' http://127.0.0.1:8000/v1/vpn/status`

This issue **does not** occur when i restart the docker container in a more classic way: `docker restart Gluetun`

Edit: Nope, still not working. Doesn't matter which version i am trying. The error also occurs sometimes with a normal `docker restart Gluetun`. But right now, my setups seems to work if i
- put the container into host mode (not bridge)
- disable DOT (`DOT=off `). Otherwise i get port related errors while using DOT in host mode.

Edit 2: Nah, gluetun in host mode is stupid, this will lead into firewall issues and will mess up my network

**Comment by caballinger** [comment]
I FINALLY was able to crack this nut during my xmas break, and it was a 2-part problem for me on my Synology. In order to fix this issue I had to:
1) add this to my docker compose:
```
environment:
   - OPENVPN_FLAGS=--proto udp4 --pull-filter ignore ifconfig-ipv6 --pull-filter ignore route-ipv6
   - STORAGE_FILEPATH= #might not be needed
```

2) change `image: qmcgaw/gluetun:latest` to `image: qmcgaw/gluetun:v3`

I HAD to do BOTH of these, I tried both options on their own and I'd end up with this error again. Setting any specific v3 tag seemed to work as well

EDIT:
I may have spoken too soon on this. It seems to work SOMETIMES, but ends up failing again every few days.

**Comment by lushc** [comment]
I've been experiencing the same issue, but after a lot of trial & error I think I've got a satisfactory workaround for now, which is to strip the AirVPN server list of IPv6 addresses.

I'm on Synology so I can't disable IPv6 completely (#2450), but even when I do the improved detection in #2523 seems to count the `lo` loopback link as support for IPv6. And if you're flagged to have IPv6 support then gluetun will consider the IPv6 addresses in the list when loading the next server to connect. This address is saved in `/etc/openvpn/target.ovpn` which means when you get unlucky, container restarts don't fix trying to connect to a bad remote.

So, I'm now offloading managing the AirVPN server list to a separate container. It requires being on the bleeding edge of gluetun to be able to [use a third-party tool to update the list](https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#use-a-third-party-tool-to-update-your-servers-list) and set the modified AirVPN list as the preferred one.

<details>
<summary>My stripped down Docker Compose file which defines a gluetun-updater container</summary>

```yaml
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 # https://github.com/qdm12/gluetun/issues/2450
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /volume2/docker/gluetun:/gluetun
    environment:  
      - VPN_SERVICE_PROVIDER=airvpn
      - FIREWALL_VPN_INPUT_PORTS=1234
      - LOG_LEVEL=debug
      - OPENVPN_FLAGS="--proto udp4 --pull-filter ignore tun-ipv6 --pull-filter ignore ifconfig-ipv6 --pull-filter ignore route-ipv6"
      - UPDATER_PERIOD=0 # disables server updates completely
    network_mode: bridge
    security_opt:
      - no-new-privileges:true
    restart: always

  gluetun-updater:
    image: alpine:3.24
    container_name: gluetun-updater
    depends_on:
      - gluetun
    volumes:
      - /volume2/docker/gluetun:/gluetun
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOST_VOLUME=/volume2/docker/gluetun # we're using docker-in-docker to update, so need to know the host volume
      - UPDATER_PERIOD_HOURS=360
      - PROVIDER=airvpn
    network_mode: bridge
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    command: /gluetun/update.sh # see below
```

</details>

<details>
<summary>The update script that the gluetun-updater container runs</summary>

```sh
#!/bin/sh
set -eu

: "${HOST_VOLUME:?HOST_VOLUME not set}"
: "${PROVIDER:?PROVIDER not set}"

IMAGE_VERSION="${IMAGE_VERSION:-latest}"
TIME_WINDOW_HOURS="${UPDATER_PERIOD_HOURS:-360}"

log() {
    printf '[controller] %s\n' "$*"
}

case "$TIME_WINDOW_HOURS" in
    ''|*[!0-9]*)
        log "UPDATER_PERIOD_HOURS must be a positive integer (got: $TIME_WINDOW_HOURS)"
        exit 1
        ;;
esac

TIME_WINDOW_SECONDS=$((TIME_WINDOW_HOURS * 3600))

GLUETUN_DIR="/gluetun"
OUT_DIR="$GLUETUN_DIR/servers"
OUT_FILE="$OUT_DIR/$PROVIDER.json"

apk add --no-cache jq docker-cli >/dev/null

mkdir -p "$OUT_DIR"

file_age() {
    if [ ! -f "$OUT_FILE" ]; then
        echo 2147483647
        return
    fi

    now=$(date +%s)
    mtime=$(stat -c %Y "$OUT_FILE" 2>/dev/null || echo 0)

    echo $((now - mtime))
}

run_update() {
    docker run --rm \
        -v "$HOST_VOLUME:$GLUETUN_DIR" \
        "qmcgaw/gluetun:$IMAGE_VERSION" \
        update -providers "$PROVIDER"
}

rebuild_provider_file() {
    [ -f "$OUT_FILE" ] || return

    log "re-building provider JSON for $PROVIDER"

    now=$(date +%s)
    tmp="${OUT_FILE}.tmp"

    rm -f "$tmp"

	jq --argjson now "$now" '
	  def has_ipv6:
	    (.ips // []) | any(test(":"));
	
	  {
	    version: 1,
	    timestamp: $now,
	    preferred: true,
	    servers: (
	      (.servers // [])
	      | map(select(has_ipv6 | not))
	    )
	  }
	' "$OUT_FILE" > "$tmp"

    mv "$tmp" "$OUT_FILE"
}

restart_gluetun() {
	log "cleaning gluetun"
	docker exec gluetun sh -c "rm /etc/openvpn/target.ovpn"
    log "restarting gluetun"
    docker restart gluetun >/dev/null
}

update_servers() {
    log "checking ${OUT_FILE}..."

    age=$(file_age)

    log "age: ${age}s / limit ${TIME_WINDOW_SECONDS}s"

    if [ "$age" -ge "$TIME_WINDOW_SECONDS" ]; then
        if [ "$age" -eq 2147483647 ]; then
            log "missing -> generating via CLI"
        else
            log "stale -> regenerating via CLI"
        fi

        run_update
        rebuild_provider_file
        restart_gluetun
    else
        log "fresh -> skipping update"
    fi
}

update_servers

while :; do
    sleep "$TIME_WINDOW_SECONDS"
    update_servers
done
```

</details>

Once the container updates the AirVPN server config and restarts gluetun, two log messages will appear:

```
INFO [storage] Using airvpn servers from file (marked as preferred)
INFO [storage] merging by most recent 27405 hardcoded servers and 26625 servers read from manifest file /gluetun/servers/manifest.json
```

I've not ran this for long but I'm hoping for good uptime now that there should be no IPv6 addresses to connect to.
