### ISSUE TITLE
Bug: openvpn certificate warning

### ISSUE THREAD

**Issue by pik4li** [qdm12/gluetun#2476]
### Is this urgent?

No

### Host OS

Debian Trixie

### CPU arch

x86_64

### VPN service provider

Cyberghost

### What are you using to run the container

docker-compose

### What is the version of Gluetun

both :latest and v3.38.0

### What's the problem 🤔

The client certificate warning for openvpn is not letting me start the container.. Also tried the version 3.38.0 as in #2184 described. Same problem here..

### Share your logs (at least 10 lines)

```plain text
Latest:
gluetun-vpn  | ========================================
gluetun-vpn  | ========================================
gluetun-vpn  | =============== gluetun ================
gluetun-vpn  | ========================================
gluetun-vpn  | =========== Made with ❤️ by ============
gluetun-vpn  | ======= https://github.com/qdm12 =======
gluetun-vpn  | ========================================
gluetun-vpn  | ========================================
gluetun-vpn  |
gluetun-vpn  | Running version latest built on 2024-08-25T07:04:32.409Z (commit 01fa993)
gluetun-vpn  |
gluetun-vpn  | 🔧 Need help? ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new/choose
gluetun-vpn  | 🐛 Bug? ✨ New feature? https://github.com/qdm12/gluetun/issues/new/choose
gluetun-vpn  | 💻 Email? quentin.mcgaw@gmail.com
gluetun-vpn  | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
gluetun-vpn  | 2024-09-09T09:32:20+02:00 INFO [routing] default route found: interface eth0, gateway 172.19.0.1, assigned IP 172.19.0.2 and family v4
gluetun-vpn  | 2024-09-09T09:32:20+02:00 INFO [routing] local ethernet link found: eth0
gluetun-vpn  | 2024-09-09T09:32:20+02:00 INFO [routing] local ipnet found: 172.19.0.0/16
gluetun-vpn  | 2024-09-09T09:32:20+02:00 INFO [firewall] enabling...
gluetun-vpn  | 2024-09-09T09:32:20+02:00 INFO [firewall] enabled successfully
gluetun-vpn  | 2024-09-09T09:32:20+02:00 INFO [storage] merging by most recent 20480 hardcoded servers and 20480 servers read from /gluetun/servers.json
gluetun-vpn  | 2024-09-09T09:32:21+02:00 ERROR VPN settings: OpenVPN settings: client certificate: missing value
gluetun-vpn  | 2024-09-09T09:32:21+02:00 INFO Shutdown successful

v3.38.0:
gluetun-vpn  | ========================================
gluetun-vpn  | ========================================
gluetun-vpn  | =============== gluetun ================
gluetun-vpn  | ========================================
gluetun-vpn  | =========== Made with ❤️ by ============
gluetun-vpn  | ======= https://github.com/qdm12 =======
gluetun-vpn  | ========================================
gluetun-vpn  | ========================================
gluetun-vpn  |
gluetun-vpn  | Running version v3.38.0 built on 2024-03-25T15:53:33.983Z (commit b3ceece)
gluetun-vpn  |
gluetun-vpn  | 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
gluetun-vpn  | 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
gluetun-vpn  | ✨ New feature? https://github.com/qdm12/gluetun/issues/new
gluetun-vpn  | ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
gluetun-vpn  | 💻 Email? quentin.mcgaw@gmail.com
gluetun-vpn  | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
gluetun-vpn  | 2024-09-09T09:32:54+02:00 INFO [routing] default route found: interface eth0, gateway 172.19.0.1, assigned IP 172.19.0.2 and family v4
gluetun-vpn  | 2024-09-09T09:32:54+02:00 INFO [routing] local ethernet link found: eth0
gluetun-vpn  | 2024-09-09T09:32:54+02:00 INFO [routing] local ipnet found: 172.19.0.0/16
gluetun-vpn  | 2024-09-09T09:32:54+02:00 INFO [firewall] enabling...
gluetun-vpn  | 2024-09-09T09:32:54+02:00 INFO [firewall] enabled successfully
gluetun-vpn  | 2024-09-09T09:32:54+02:00 INFO [storage] merging by most recent 19476 hardcoded servers and 20480 servers read from /gluetun/servers.json
gluetun-vpn  | 2024-09-09T09:32:54+02:00 INFO [storage] Using airvpn servers from file which are 488 days more recent
gluetun-vpn  | 2024-09-09T09:32:54+02:00 INFO [storage] Using fastestvpn servers from file which are 608 days more recent
gluetun-vpn  | 2024-09-09T09:32:54+02:00 INFO [storage] Using ivpn servers from file which are 717 days more recent
gluetun-vpn  | 2024-09-09T09:32:54+02:00 INFO [storage] Using privado servers from file which are 187 days more recent
gluetun-vpn  | 2024-09-09T09:32:54+02:00 INFO [storage] Using private internet access servers from file which are 176 days more recent
gluetun-vpn  | 2024-09-09T09:32:54+02:00 INFO [storage] Using protonvpn servers from file which are 702 days more recent
gluetun-vpn  | 2024-09-09T09:32:54+02:00 INFO [storage] Using surfshark servers from file which are 82 days more recent
gluetun-vpn  | 2024-09-09T09:32:54+02:00 INFO [storage] Using vpnsecure servers from file which are 677 days more recent
gluetun-vpn  | 2024-09-09T09:32:54+02:00 INFO [storage] Using windscribe servers from file which are 212 days more recent
gluetun-vpn  | 2024-09-09T09:32:54+02:00 ERROR VPN settings: OpenVPN settings: client certificate: missing value
gluetun-vpn  | 2024-09-09T09:32:54+02:00 INFO Shutdown successful
```

### Share your configuration

```yml
# version: "3"
services:
  gluetun:
    # image: qmcgaw/gluetun:latest
    image: qmcgaw/gluetun:v3.38.0
    container_name: gluetun-vpn
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - ./gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=cyberghost
      - VPN_TYPE=openvpn

      # OpenVPN:
      - OPENVPN_USER=<user>
      - OPENVPN_PASSWORD=<password>
      - SERVER_COUNTRIES=Argentina

      # Timezone for accurate log times
      - TZ=Europe/Berlin

      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      # - UPDATER_PERIOD=
# volumes:
#   librum:
#     name: "librum"
```
