### ISSUE TITLE
Public IP leaking at start of container

### ISSUE THREAD

**Issue by Pelvis99** [qdm12/gluetun#2484]
### Is this urgent?

Yes

### Host OS

Ubuntu

### CPU arch

x86_64

### VPN service provider

AirVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

v3.39

### What's the problem 🤔

V3.39 is allowing network traffic on startup, which will leak your actual IP.
(Using AirVPN but using custom config)

How to test:
Start this compose:
```
version: '3.7'
services:
  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    restart: always
    networks:
      outside:
        ipv4_address: 172.26.0.4
    cap_add:
      - NET_ADMIN
    devices:
      - '/dev/net/tun:/dev/net/tun'
    volumes:
      - 'gluetun:/gluetun'
    environment:
      VPN_SERVICE_PROVIDER: custom
      WIREGUARD_PRIVATE_KEY: '${WIREGUARD_PRIVATE_KEY}'
      WIREGUARD_ADDRESSES: '${WIREGUARD_ADDRESSES}'
      VPN_TYPE: 'wireguard'
      VPN_ENDPOINT_IP: '${VPN_ENDPOINT_IP}'
      VPN_ENDPOINT_PORT: '${VPN_ENDPOINT_PORT}'
      WIREGUARD_PUBLIC_KEY: '${WIREGUARD_PUBLIC_KEY}'
      WIREGUARD_PRESHARED_KEY: '${WIREGUARD_PRESHARED_KEY}'
      HTTP_CONTROL_SERVER_ADDRESS: ':8000'
      BLOCK_ADS: 'off'
      DOT: 'off'
      DOT_PRIVATE_ADDRESS: ''
      DNS_KEEP_NAMESERVER: 'off'
      BLOCK_MALICIOUS: 'off'
      BLOCK_SURVEILLANCE: 'off'
      FIREWALL_VPN_INPUT_PORTS: '${WIRE_PORTFORWARD_PORT}'
      FIREWALL_INPUT_PORTS: '${WIRE_PORTFORWARD_PORT}'
      FIREWALL_OUTBOUND_SUBNETS: '172.26.0.0/16'
      HEALTH_TARGET_ADDRESS: 'google.com:443'
  checkip:
    network_mode: 'service:gluetun'
    image: curlimages/curl
    command: ['-L', '-v', '-4', 'icanhazip.com']
    restart: no
networks:
  outside:
    ipam:
      config:
        - subnet: 172.26.0.0/16
volumes:
  gluetun:
  ```
  
After it's running, change the image to (which is the same version, but this was the most reliable way to test it)
```
 image: qmcgaw/gluetun:v3.39
 ```
 
After this do compose up again &  you will see in the logs of checkip your actual ip and not the VPN IP.

### Share your logs (at least 10 lines)

```plain text
2024-09-17T21:22:03Z INFO IPtables version: v1.8.10
2024-09-17T21:22:03Z INFO Settings summary:
├── VPN settings:
|   ├── VPN provider settings:
|   |   ├── Name: custom
|   |   └── Server selection settings:
|   |       ├── VPN type: wireguard
|   |       ├── Target IP address: xxxx
|   |       └── Wireguard selection settings:
|   |           ├── Endpoint IP address: xxx
|   |           ├── Endpoint port: xxx
|   |           └── Server public key: xxxx
|   └── Wireguard settings:
|       ├── Private key: xxx
|       ├── Pre-shared key: xxx
|       ├── Interface addresses:
|       |   └── xxxxx
|       ├── Allowed IPs:
|       |   ├── 0.0.0.0/0
|       |   └── ::/0
|       └── Network interface: tun0
|           └── MTU: 1400
├── DNS settings:
|   ├── Keep existing nameserver(s): no
|   ├── DNS server address to use: 127.0.0.1
|   └── DNS over TLS settings:
|       └── Enabled: no
├── Firewall settings:
|   ├── Enabled: yes
|   ├── VPN input ports:
|   |   └── xxx
|   ├── Input ports:
|   |   └── xxx
|   └── Outbound subnets:
|       ├── 172.26.0.0/16
├── Log settings:
|   └── Log level: info
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Target address: google.com:443
|   ├── Duration to wait after success: 5s
|   ├── Read header timeout: 100ms
|   ├── Read timeout: 500ms
|   └── VPN wait durations:
|       ├── Initial duration: 6s
|       └── Additional duration: 5s
├── Shadowsocks server settings:
|   └── Enabled: no
├── HTTP proxy settings:
|   └── Enabled: no
├── Control server settings:
|   ├── Listening address: :8000
|   └── Logging: yes
├── OS Alpine settings:
|   ├── Process UID: 1000
|   └── Process GID: 1000
├── Public IP settings:
|   ├── Fetching: every 12h0m0s
|   ├── IP file path: /tmp/gluetun/ip
|   └── Public IP data API: ipinfo
└── Version settings:
    └── Enabled: yes
```

**Comment by qdm12** [comment]
See https://github.com/qdm12/gluetun-wiki/blob/main/faq/firewall.md#timing

I'm not sure it's possible to mitigate, since *just* launching the binary takes (after the gluetun container starts) takes a few milliseconds.
If you use

```yml
  checkip:
    network_mode: 'service:gluetun'
    image: curlimages/curl
    entrypoint: /bin/sh -c "sleep 0.1 && curl -L -v -4 icanhazip.com"
    restart: no
```

this should fail, correct?
