### ISSUE TITLE
Bug: No server can be found, despite the fact that there are ProtonVPN servers that support the set of features

### ISSUE THREAD

**Issue by FlorentLM** [qdm12/gluetun#2498]
### Is this urgent?

Yes

### Host OS

Debian Bookworm

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2024-09-28T17:54:55.225Z (commit c665b13)

### What's the problem 🤔

No server can be found, despite the fact that there are, indeed, many ProtonVPN servers that support Wireguard, secure-core and port forwarding. 

Tried deleting `/gluetun/servers.json` and no change.
Tried adding the environment variable `- PROTOCOL=tcp` and no change.

I see that in `/gluetun/servers.json`, only OpenVPN servers have the fields `"udp": ` and `"tcp": `, but the Wireguard servers have neither of these fields. Could that be why the Wireguard ones return `false` for both udp and tcp?

### Share your logs (at least 10 lines)

```plain text
2024-09-29T16:54:22+02:00 INFO [routing] default route found: interface eth0, gateway 172.18.0.1, assigned IP 172.18.0.4 and family v4
2024-09-29T16:54:22+02:00 INFO [routing] local ethernet link found: eth0
2024-09-29T16:54:22+02:00 INFO [routing] local ipnet found: 172.18.0.0/16
2024-09-29T16:54:22+02:00 INFO [firewall] enabling...
2024-09-29T16:54:22+02:00 INFO [firewall] enabled successfully
2024-09-29T16:54:23+02:00 INFO [storage] merging by most recent 20553 hardcoded servers and 20553 servers read from /gluetun/servers.json
2024-09-29T16:54:23+02:00 INFO Alpine version: 3.20.3
2024-09-29T16:54:23+02:00 INFO OpenVPN 2.5 version: 2.5.10
2024-09-29T16:54:23+02:00 INFO OpenVPN 2.6 version: 2.6.11
2024-09-29T16:54:23+02:00 INFO IPtables version: v1.8.10
2024-09-29T16:54:23+02:00 INFO Settings summary:
├── VPN settings:
|   ├── VPN provider settings:
|   |   ├── Name: protonvpn
|   |   ├── Server selection settings:
|   |   |   ├── VPN type: wireguard
|   |   |   ├── Secure Core only servers: yes
|   |   |   ├── Port forwarding only servers: yes
|   |   |   └── Wireguard selection settings:
|   |   └── Automatic port forwarding settings:
|   |       ├── Redirection listening port: disabled
|   |       ├── Use code for provider: protonvpn
|   |       └── Forwarded port file path: /tmp/gluetun/forwarded_port
|   └── Wireguard settings:
|       ├── Private key: 0GZ...2s=
|       ├── Interface addresses:
|       |   └── 10.2.0.2/32
|       ├── Allowed IPs:
|       |   ├── 0.0.0.0/0
|       |   └── ::/0
|       └── Network interface: tun0
|           └── MTU: 1400
├── DNS settings:
|   ├── Keep existing nameserver(s): no
|   ├── DNS server address to use: 127.0.0.1
|   └── DNS over TLS settings:
|       ├── Enabled: yes
|       ├── Update period: every 24h0m0s
|       ├── Upstream resolvers:
|       |   └── cloudflare
|       ├── Caching: yes
|       ├── IPv6: no
|       └── DNS filtering settings:
|           ├── Block malicious: yes
|           ├── Block ads: no
|           ├── Block surveillance: no
|           └── Blocked IP networks:
|               ├── 127.0.0.1/8
|               ├── 172.16.0.0/12
|               ├── 169.254.0.0/16
|               ├── ::1/128
|               ├── fc00::/7
|               ├── fe80::/10
|               ├── ::ffff:127.0.0.1/104
|               ├── ::ffff:169.254.0.0/112
|               ├── ::ffff:172.16.0.0/108
├── Firewall settings:
|   └── Enabled: yes
├── Log settings:
|   └── Log level: info
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Target address: cloudflare.com:443
|   ├── Duration to wait after success: 5s
|   ├── Read header timeout: 100ms
|   ├── Read timeout: 500ms
|   └── VPN wait durations:
|       ├── Initial duration: 6s
|       └── Additional duration: 5s
├── Shadowsocks server settings:
|   └── Enabled: no
├── HTTP proxy settings:
|   └── Enabled: no
├── Control server settings:
|   ├── Listening address: :8000
|   ├── Logging: yes
|   └── Authentication file path: /gluetun/auth/config.toml
├── Storage settings:
|   └── Filepath: /gluetun/servers.json
├── OS Alpine settings:
|   ├── Process UID: xxx
|   ├── Process GID: xxx
|   └── Timezone: xxxxxx/xxxxxx
├── Public IP settings:
|   ├── Fetching: every 12h0m0s
|   ├── IP file path: /tmp/gluetun/ip
|   └── Public IP data API: ipinfo
└── Version settings:
    └── Enabled: yes
2024-09-29T16:54:23+02:00 INFO [routing] default route found: interface eth0, gateway 172.18.0.1, assigned IP 172.18.0.4 and family v4
2024-09-29T16:54:23+02:00 INFO [routing] adding route for 0.0.0.0/0
2024-09-29T16:54:23+02:00 INFO [firewall] setting allowed subnets...
2024-09-29T16:54:23+02:00 INFO [routing] default route found: interface eth0, gateway 172.18.0.1, assigned IP 172.18.0.4 and family v4
2024-09-29T16:54:23+02:00 INFO [dns] using plaintext DNS at address 1.1.1.1
2024-09-29T16:54:23+02:00 INFO [http server] http server listening on [::]:8000
2024-09-29T16:54:23+02:00 INFO [healthcheck] listening on 127.0.0.1:9999
2024-09-29T16:54:23+02:00 ERROR [vpn] finding a VPN server: filtering servers: no server found: for VPN wireguard; protocol udp; port forwarding only; secure core only; target ip address 0.0.0.0
2024-09-29T16:54:23+02:00 INFO [vpn] retrying in 15s
```

### Share your configuration

```yml
networks:
  reverseproxy:
    external: true

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - reverseproxy
    environment:
      - TZ=xxxxxx/xxxxxx
      - PUID=xxx
      - PGID=xxx
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - SECURE_CORE_ONLY=on
      - PORT_FORWARD_ONLY=on
      - WIREGUARD_PRIVATE_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
      - SHADOWSOCKS=off
      - HTTPPROXY=off
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /xxxx/xxxx/xxxx/gluetun:/gluetun
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=reverseproxy
      - traefik.http.routers.qbittorrent.tls=true
      - traefik.http.routers.qbittorrent.rule=Host(`xxxxx.xxxxx.xx`)
      - traefik.http.routers.qbittorrent.entrypoints=xxxxx
      - traefik.http.routers.qbittorrent.tls.certResolver=xxxxxx
      - traefik.http.routers.qbittorrent.tls.options=xxxxx@file
      - traefik.http.routers.qbittorrent.middlewares=xxxxx@file
      - traefik.http.routers.qbittorrent.service=xxxxx
      - traefik.http.services.qbittorrent.loadbalancer.server.port=xxxxx
```
```
