### ISSUE TITLE
Feature request: Pure VPN Port Forwarding

### ISSUE THREAD

**Issue by iLostAllCTRL** [qdm12/gluetun#2532]
### What's the feature 🧐

Pure VPN allows for static port forwarding.  Can it get added to the list of port-forwarding-enabled VPN providers?

### Extra information and references

https://www.purevpn.com/port-forwarding

**Comment by tiberio87** [comment]
I believe you can use custom provider configuration!

**Comment by iLostAllCTRL** [comment]
I tried to do custom but I might have done it wrong.

**Comment by tiberio87** [comment]
`For non-native integrations where you have a designated forwarded port from your VPN provider, you can allow it by adding it to the environment variable FIREWALL_VPN_INPUT_PORTS. `

Enter the port you opened on the purevpn website as a variable.

**Comment by Sevyn13** [comment]
So I got this to work using VPN_SERVICE_PROVIDER=custom and downloading the .conf file from PureVPN. Checking if the port is open using a port checking site hitting the VPN IP shows it as open, but the speeds are horrible, below 1MB/s. Compared to 20MB/s+ when using VPN_SERVICE_PROVIDER=purevpn. Any idea why the speeds are horrible? Here is the compose.


```
services:
  gluetun:
    container_name: gluetunvpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /home/user/docker/gluetun:/gluetun
    environment:
    ########   NO PORT FORWARDING   #########
      - VPN_SERVICE_PROVIDER=purevpn
      - SERVER_COUNTRIES=Belgium
      - VPN_TYPE=openvpn
      - OPENVPN_USER=user from purevpn site
      - OPENVPN_PASSWORD=app password from purevpn site

    ########   PORT FORWARDING   ########
      # - VPN_TYPE=openvpn
      # - VPN_SERVICE_PROVIDER=custom
      # - OPENVPN_CUSTOM_CONFIG=/gluetun/belgium.conf
      # - OPENVPN_USER=user from purevpn site
      # - OPENVPN_PASSWORD=app password from purevpn site
      # - FIREWALL_VPN_INPUT_PORTS=6881
      
    ports:
      - 6969:6969 # qbittorrent web interface
      - 6881:6881 # qbittorrent torrent port
    restart: always


  qbittorrentvpn:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrentvpn
    network_mode: "service:gluetun"
    environment:
      #- PUID=1000
      #- PGID=1000
      - WEBUI_PORT=6969
      - TORRENTING_PORT=6881
    volumes:
      - /home/user/docker/qbittorrentvpn:/config
      - /home/user/torrents:/data/torrents

    depends_on:
       gluetun:
         condition: service_healthy
    restart: always
```
