### ISSUE TITLE
Firewall and EXTRA_SUBNETS with Kubernetes sidecar

### ISSUE THREAD

**Issue by darthf1** [qdm12/gluetun#254]
**TLDR**: Cannot access container via domain when configured as k8s sidecar container and when firewall is enabled

1. Is this urgent?

    - [ ] Yes
    - [x] No

2. What VPN service provider are you using?

    - [ ] PIA
    - [ ] Mullvad
    - [ ] Windscribe
    - [ ] Surfshark
    - [ ] Cyberghost
    - [x] NordVPN

3. What's the version of the program?

Running version latest built on 2020-09-26T13:33:59Z (commit ecf7689)

4. What are you using to run the container?

    - [ ] Docker run
    - [ ] Docker Compose
    - [x] Kubernetes
    - [ ] Docker stack
    - [ ] Docker swarm
    - [ ] Podman
    - [ ] Other:

5. Extra information

Configuration file:

```yml
gluetun:
  name: gluetun
  replicaCount: 1
  image:
    repository: qmcgaw/private-internet-access
    tag: latest
    pullPolicy: Always
  env:
    - name: VPNSP
      value: 'nordvpn'
    - name: USER
      value: "xxx"
    - name: PASSWORD
      value: "xxx"
    - name: REGION
      value: "xxx"
    - name: TZ
      value: "xxx"
    - name: DOT
      value: "off"
    - name: EXTRA_SUBNETS
      value: "192.168.2.0/24"
    - name: FIREWALL_DEBUG
      value: "on"
    - name: FIREWALL
      value: "on"
  securityContext:
    capabilities:
      add:
        - NET_ADMIN
```

Host OS:
Ubuntu 20.04.1, microk8s, k8s 1.19

I have a local Kubernetes cluster, with Traefik as my load balancer. I have an image of `deluge` deployed which is made accessible via a custom domain. To run the traffic via the VPN, I loaded the docker image from this repo as a sidecar container. My VPN provider is NordVPN.

When the firewall is disabled via the env variable `FIREWALL=off`, I can access my `deluge` image via the previously configured domain.
When the firewall is enabled, I cannot access the domain. The response is `504 Gateway Timeout`
When I exec into the container, I verified that the internet connection is working, and all traffic is routed through the VPN connection (via `curl ipinfo.io/ip`).

I configured the env variable `EXTRA_SUBNETS=192.168.2.0/24` to allow access via LAN. My DHCP lease pool is configured between `192.168.2.150` and `192.168.2.254`. Unfortunately, I'm still unable to access `deluge` via the configured domain.

Is there additional config required when running this image as a sidecar container? Or is there something else I'm missing?

**Comment by qdm12** [comment]
Thanks for the detailed issue!

I haven't used gluetun in Kubernetes so far but I'm familiar with Kubernetes, let's see if that can help 😉

How exactly do you make the sidecar deluge container use the network stack of gluetun? Can you try (with the firewall on) to shell into the deluge container and see if your connection works through the tunnel?

If it's something related to the firewall then it should be fixable (unlike routing issues which sometimes aren't). You could always try to exec in gluetun and fiddle with iptables to see what unblocks or blocks it. Feel free to let me know if you're not familiar with iptables, I can help guiding you.

**Comment by darthf1** [comment]
Thanks for getting back to me. Below are my `yaml` files, its one deployment files with two container definitions.

> Can you try (with the firewall on) to shell into the deluge container and see if your connection works through the tunnel?

I'm not exactly sure what you mean by this. When (with the firewall on) I exec into the container, I can access the internet via `curl`. E.g. `curl ipinfo.io/ip` gives my me public IP, in this case the VPNs IP.

> Feel free to let me know if you're not familiar with iptables, I can help guiding you.

That would be great, as I have zero experience with iptables.

`deluge.deployment.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deluge.name }}
  labels:
    app: {{ .Values.deluge.name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deluge.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deluge.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deluge.name }}
        release: {{ .Release.Name }}
    spec:
      volumes:
{{ toYaml .Values.deluge.volumes | indent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deluge.image.repository }}:{{ .Values.deluge.image.tag }}"
          imagePullPolicy: {{ .Values.deluge.image.pullPolicy }}
          env:
{{ toYaml .Values.deluge.env | indent 12 }}
          ports:
            - name: http
              containerPort: 8989
              protocol: TCP
          volumeMounts:
{{ toYaml .Values.deluge.volumeMounts | indent 12 }}
          resources:
{{ toYaml .Values.deluge.resources | indent 12 }}
        - name: {{ .Values.gluetun.name }}
          image: "{{ .Values.gluetun.image.repository }}:{{ .Values.gluetun.image.tag }}"
          imagePullPolicy: {{ .Values.gluetun.image.pullPolicy }}
          env:
{{ toYaml .Values.gluetun.env | indent 12 }}
          ports:
{{ toYaml .Values.gluetun.ports | indent 12 }}
          securityContext:
{{ toYaml .Values.gluetun.securityContext | indent 12 }}
    {{- with .Values.deluge.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.deluge.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.deluge.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
```

`values.yaml`
```yaml
gluetun:
  name: gluetun
  replicaCount: 1
  image:
    repository: qmcgaw/private-internet-access
    tag: latest
    pullPolicy: Always
  env:
    - name: VPNSP
      value: 'nordvpn'
    - name: USER
      value: "xxx"
    - name: PASSWORD
      value: "xxx"
    - name: REGION
      value: "xxx"
    - name: TZ
      value: "xxx"
    - name: DOT
      value: "off"
    - name: EXTRA_SUBNETS
      value: "192.168.2.0/24"
    - name: FIREWALL_DEBUG
      value: "on"
    - name: FIREWALL
      value: "on"
  ports:
    - name: tinyproxy
      containerPort: 8888
      protocol: TCP
    - name: shadowsocks-tcp
      containerPort: 8388
      protocol: TCP
    - name: shadowsocks-udp
      containerPort: 8388
      protocol: UDP
    - name: http
      containerPort: 8000
      protocol: TCP
  securityContext:
    capabilities:
      add:
        - NET_ADMIN
deluge:
  name: deluge
  replicaCount: 1
  image:
    repository: linuxserver/deluge
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  env:
    - name: TZ
      value: "xxx"
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
  volumes: []
  volumeMounts: []
