### ISSUE TITLE
Bug: gluetun port tcp 8888 bind: already in use

### ISSUE THREAD

**Issue by atticusmatticus** [qdm12/gluetun#2540]
### Is this urgent?

Yes

### Host OS

macOS

### CPU arch

Apple Silicon

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version v3.39.1 built on 2024-09-29T18:16:23.495Z (commit 67ae5f5)

### What's the problem 🤔

After latest Docker Desktop update (v4.35.0) my typical way of pulling and starting up containers after a reboot failed:
`docker-compose pull; docker-compose up -d --remove-orphans;`

gave the following,
```
Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:8888 -> 0.0.0.0:0: listen tcp4 0.0.0.0:8888: bind: address already in use
```

This command had worked as expected immediately before updating Docker Desktop. I tried completely killing docker and all associated processes, rebooting and rerunning the command but this error message always came up.

### Share your logs (at least 10 lines)

```plain text
There are no logs because gluetun won't start.
```

### Share your configuration

```yml
gluetun:
  container_name: gluetun
  image: qmcgaw/gluetun:latest
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun:/dev/net/tun
  ports:
    - 8888:8888/tcp # HTTP proxy
    - 8388:8388/tcp # Shadowsocks
    - 8388:8388/udp # Shadowsocks
    ## Port-mapped from a:
    - 5055:5055
    ## Port-mapped from b:
    - 7878:7878
    ## Port-mapped from c:
    - 8989:8989
    ## Port-mapped from d:
    - 8787:8787
    ## Port-mapped from e
    - 6767:6767
    ## Port-mapped from f
    - 8080:8080
    - 9090:9090
  volumes:
    - ~/gluetun_docker:/gluetun
  environment: # See https://github.com/qdm12/gluetun/wiki
    # ProtonVPN
    - VPN_SERVICE_PROVIDER=protonvpn
    - VPN_TYPE=wireguard
    # 
    - VPN_ENDPOINT_IP=###########
    - VPN_ENDPOINT_PORT=#####
    - WIREGUARD_PUBLIC_KEY=#########################=
    - WIREGUARD_PRIVATE_KEY=#################################=
    - WIREGUARD_ADDRESSES=##########
    #
    - TZ=America/Chicago
```
