### ISSUE TITLE
Bug: PIA wireguard port forwarding not working with wiki config

### ISSUE THREAD

**Issue by phillibl** [qdm12/gluetun#2646]
### Is this urgent?

None

### CPU arch

None

### VPN service provider

Private Internet Access

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2024-12-27T20:18:46.989Z (commit 61b053f)

### What's the problem 🤔

I'm following the wiki for setting up PIA Wireguard with port forwarding, but get the error

`ERROR VPN settings: OpenVPN settings: user is empty`

I'm obviously not using OpenVPN so that makes sense.

I tried a couple combos of config and it didn't work, such as setting the provider to custom.  I can run it without port forwarding with a wg0.conf

### Share your logs (at least 10 lines)

```plain text
gluetun1  | 2025-01-06T23:25:19.114127792Z 2025-01-06T23:25:19Z INFO [routing] default route found: interface eth0, gateway 192.168.176.1, assigned IP 192.168.176.2 and family v4
gluetun1  | 2025-01-06T23:25:19.114240034Z 2025-01-06T23:25:19Z INFO [routing] local ethernet link found: eth0
gluetun1  | 2025-01-06T23:25:19.114355798Z 2025-01-06T23:25:19Z INFO [routing] local ipnet found: 192.168.176.0/20
gluetun1  | 2025-01-06T23:25:19.286044644Z 2025-01-06T23:25:19Z INFO [firewall] enabling...
gluetun1  | 2025-01-06T23:25:19.486603175Z 2025-01-06T23:25:19Z INFO [firewall] enabled successfully
gluetun1  | 2025-01-06T23:25:20.276747097Z 2025-01-06T23:25:20Z INFO [storage] merging by most recent 20776 hardcoded servers and 20776 servers read from /gluetun/servers.json
gluetun1  | 2025-01-06T23:25:20.382760214Z 2025-01-06T23:25:20Z ERROR VPN settings: OpenVPN settings: user is empty
gluetun1  | 2025-01-06T23:25:20.382782032Z 2025-01-06T23:25:20Z INFO Shutdown successful
```

### Share your configuration

```yml
services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - %path to config%:/gluetun:rw
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_USERNAME=%user
      - VPN_PORT_FORWARDING_PASSWORD=%pass
      - SERVER_NAMES=panama405
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
```
