### ISSUE TITLE
Bug: Gluetun Not Starting on System/Docker Reboot

### ISSUE THREAD

**Issue by GitHubQueenn** [qdm12/gluetun#2673]
### Is this urgent?

Yes

### Host OS

Ubuntu

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2024-12-25T01:30:06Z (commit e890c50 )

### What's the problem 🤔

When I restart my server PC, Gluetun is not auto-starting, which also is making my qBittorrent not start at all since it runs through that. My docker-compose.yml file is:

```
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - Redacted
      - Redacted
      - Redacted # qbittorrent
    volumes:
      - /home/username/Dockers/Gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=0BuyigohGVUO8Y7G8UIbiuHo=
      - SERVER_COUNTRIES=United States
      - TZ=America/New_York
    restart: always
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=Redacted
    volumes:
      - /home/username/Dockerrrrr/qBittorrent:/config
      - /media/folder/Torrents:/downloads
      - /media/folder/Torrents/incomplete:/downloads/incomplete
    depends_on:
      - gluetun
    restart: always
```

### Share your logs (at least 10 lines)

```plain text
See above.
```

### Share your configuration

```yml

```
