### ISSUE TITLE
Bug: Non-VPN IP when using Traefik

### ISSUE THREAD

**Issue by truthsword** [qdm12/gluetun#2676]
### Is this urgent?

None

### Host OS

Debian Bookworm

### CPU arch

x86_64

### VPN service provider

AirVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

latest

### What's the problem 🤔

I have a Metube container that runs through gluetun using the compose line `network_mode: container:gluetun` 

When I test the IP using `docker exec -it metube curl ipconfig.io` the IP matches the VPN destination Belgium (without traefik).

Then I added Traefik labels to the Gluetun container:

```
labels:
      - "traefik.enable=true"
      - "traefik.docker.network=t3_proxy"
      - "traefik.http.routers.metube.entrypoints=web"
      - "traefik.http.routers.metube.rule=Host(`metube.serv2.internal`)"
      - "traefik.http.routers.metube.service=metube"
      - "traefik.http.services.metube.loadbalancer.server.port=8081"
```
When I test the IP using `docker exec -it metube curl ipconfig.io` the IP matches the VPN destination Chicago, United States (not my location, FWIW)

### Share your logs (at least 10 lines)

```plain text
gluetun  | 2025-01-27T23:14:03-05:00 INFO [healthcheck] healthy!
gluetun  | 2025-01-27T23:14:04-05:00 INFO [dns] downloading hostnames and IP block lists
gluetun  | 2025-01-27T23:14:10-05:00 INFO [dns] init module 0: validator
gluetun  | 2025-01-27T23:14:10-05:00 INFO [dns] init module 1: iterator
gluetun  | 2025-01-27T23:14:10-05:00 INFO [dns] start of service (unbound 1.20.0).
gluetun  | 2025-01-27T23:14:10-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66-9728. NULL IN
gluetun  | 2025-01-27T23:14:10-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66-9728. NULL IN
gluetun  | 2025-01-27T23:14:11-05:00 INFO [dns] ready
gluetun  | 2025-01-27T23:14:11-05:00 INFO [healthcheck] healthy!
gluetun  | 2025-01-27T23:14:12-05:00 INFO [ip getter] Public IP address is 194.187.251.155 (Belgium, Flanders, Zaventem)
gluetun  | 2025-01-27T23:14:14-05:00 INFO [vpn] There is a new release v3.40.0 (v3.40.0) created 33 days ago
```

### Share your configuration

```yml
services:
  gluetun:
    image: qmcgaw/gluetun:v3.39
    container_name: gluetun
    restart: always
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    security_opt:
      - no-new-privileges=true
    environment:
      - HTTPPROXY=on
      - SHADOWSOCKS=off
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=123
      - WIREGUARD_PRESHARED_KEY=456
      - WIREGUARD_ADDRESSES=10.147.92.230/32
      - SERVER_COUNTRIES=Belgium
      - TZ=America/New_York
      - UPDATER_PERIOD=24h
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
    networks:
      - gluetun
      - t3_proxy

    # ports:
      # - 8081:8081 # metube downloader
	  
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=t3_proxy"
      - "traefik.http.routers.metube.entrypoints=web"
      - "traefik.http.routers.metube.rule=Host(`metube.serv2.internal`)"
      - "traefik.http.routers.metube.service=metube"
      - "traefik.http.services.metube.loadbalancer.server.port=8081"

networks:
  gluetun:
    external: true
  t3_proxy:
    external: true
```
