### ISSUE TITLE
Bug: protonvpn port forwarding connection refused

### ISSUE THREAD

**Issue by UltraBlackLinux** [qdm12/gluetun#2679]
### Is this urgent?

No

### Host OS

Arch Linux

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

13532c8

### What's the problem 🤔

Port forwarding servers do not work despite having added +pmp to my openvpn username. Gluetun tries to connect but fails. I have confirmed several times that it is there and that I've regenerated my containers, to no avail.

Even though there's an IO timeout at the end of my logs, the proxy at least works completely fine.

### Share your logs (at least 10 lines)

```plain text
gluetun-vpn  | 2025-02-01T14:42:51Z INFO [vpn] starting
gluetun-vpn  | 2025-02-01T14:42:51Z INFO [firewall] allowing VPN connection...
gluetun-vpn  | 2025-02-01T14:42:51Z INFO [openvpn] OpenVPN 2.6.11 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD]
gluetun-vpn  | 2025-02-01T14:42:51Z INFO [openvpn] library versions: OpenSSL 3.3.2 3 Sep 2024, LZO 2.10
gluetun-vpn  | 2025-02-01T14:42:51Z INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]212.92.104.241:1194
gluetun-vpn  | 2025-02-01T14:42:51Z INFO [openvpn] UDPv4 link local: (not bound)
gluetun-vpn  | 2025-02-01T14:42:51Z INFO [openvpn] UDPv4 link remote: [AF_INET]212.92.104.241:1194
gluetun-vpn  | 2025-02-01T14:42:51Z INFO [openvpn] [node-nl-167.protonvpn.net] Peer Connection Initiated with [AF_INET]212.92.104.241:1194
gluetun-vpn  | 2025-02-01T14:42:52Z INFO [openvpn] setsockopt TCP_NODELAY=1 failed
gluetun-vpn  | 2025-02-01T14:42:52Z INFO [openvpn] TUN/TAP device tun0 opened
gluetun-vpn  | 2025-02-01T14:42:52Z INFO [openvpn] /sbin/ip link set dev tun0 up mtu 1500
gluetun-vpn  | 2025-02-01T14:42:52Z INFO [openvpn] /sbin/ip link set dev tun0 up
gluetun-vpn  | 2025-02-01T14:42:52Z INFO [openvpn] /sbin/ip addr add dev tun0 10.27.0.6/16
gluetun-vpn  | 2025-02-01T14:42:52Z INFO [openvpn] UID set to nonrootuser
gluetun-vpn  | 2025-02-01T14:42:52Z INFO [openvpn] Initialization Sequence Completed
gluetun-vpn  | 2025-02-01T14:42:53Z INFO [healthcheck] healthy!
gluetun-vpn  | 2025-02-01T14:42:54Z INFO [ip getter] Public IP address is 212.92.104.248 (Netherlands, North Brabant, Roosendaal - source: ipinfo)
gluetun-vpn  | 2025-02-01T14:42:54Z INFO [port forwarding] starting
gluetun-vpn  | 2025-02-01T14:42:54Z ERROR [vpn] starting port forwarding service: port forwarding for the first time: getting external IPv4 address: executing remote procedure call: reading from udp connection: read udp 10.27.0.6:54346->10.27.0.1:5351: recvfrom: connection refused - make sure you have +pmp at the end of your OpenVPN username
gluetun-vpn  | 2025-02-01T14:42:56Z WARN [dns] dialing tls server for request IN A cloudflare.com.: dial tcp 1.0.0.1:853: i/o timeout
```

### Share your configuration

```yml
gluetun-vpn:
        image: qmcgaw/gluetun
        container_name: gluetun-vpn
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        ports:
            - 8389:8888/tcp # HTTP proxy

            - 7575:7575 # QBT
            - 7676:7676 # QBT
            - 7676:7676/udp # QBT
            - 7777:9696 # PRLR
            - 7878:7878 # RDR
        volumes:
            - /podconf/vpn/gluetun:/gluetun
        environment:
            - HTTPPROXY=on
            - HTTPPROXY_USER=<>
            - HTTPPROXY_PASSWORD=<>
            - HTTPPROXY_LOG=on
            - HTTPPROXY_STEALTH=on

            # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/protonvpn.md
            - VPN_SERVICE_PROVIDER=protonvpn

            - SERVER_COUNTRIES=Germany,Poland,France,Denmark,Netherlands,Ireland,Austria
            - STREAM_ONLY=off
            - SECURE_CORE_ONLY=off

            # https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/vpn-port-forwarding.md#qbittorrent-example
            - VPN_PORT_FORWARDING=on
            - PORT_FORWARD_ONLY=on
            - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:7575/api/v2/app/setPreferences 2>&1'
            - OPENVPN_USER=<>+pmp+nr
            - OPENVPN_PASSWORD=<>
```
