### ISSUE TITLE
Bug: You are running 1 commit behind the most recent latest

### ISSUE THREAD

**Issue by 56k-modem** [qdm12/gluetun#2692]
### Is this urgent?

No

### Host OS

Debian Bullseye

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2025-01-22T08:30:14.628Z (commit 13532c8)

### What's the problem 🤔

```
$ docker compose logs
[...]
2025-02-05T11:06:03Z INFO [vpn] You are running 1 commit behind the most recent latest
```
Despite in `docker-compose.yml`:

```
services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
```
And having done:
```
docker compose down --rmi all
docker compose pull
docker compose up -d
```

### Share your logs (at least 10 lines)

```plain text
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================

Running version latest built on 2025-01-22T08:30:14.628Z (commit 13532c8)

🔧 Need help? ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new/choose
🐛 Bug? ✨ New feature? https://github.com/qdm12/gluetun/issues/new/choose
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2025-02-05T11:06:01Z INFO [routing] default route found: interface eth0, gateway 172.28.0.1, assigned IP 172.28.0.2 and family v4
2025-02-05T11:06:01Z INFO [routing] local ethernet link found: eth0
2025-02-05T11:06:01Z INFO [routing] local ipnet found: 172.28.0.0/16
2025-02-05T11:06:01Z INFO [firewall] enabling...
2025-02-05T11:06:01Z INFO [firewall] enabled successfully
2025-02-05T11:06:02Z INFO [storage] creating /gluetun/servers.json with 20776 hardcoded servers
2025-02-05T11:06:02Z INFO Alpine version: 3.20.5
2025-02-05T11:06:02Z INFO OpenVPN 2.5 version: 2.5.10
2025-02-05T11:06:02Z INFO OpenVPN 2.6 version: 2.6.11
2025-02-05T11:06:02Z INFO IPtables version: v1.8.10
2025-02-05T11:06:02Z INFO Settings summary:
├── VPN settings:
|   ├── VPN provider settings:
|   |   ├── Name: mullvad
|   |   └── Server selection settings:
|   |       ├── VPN type: wireguard
|   |       ├── Countries: switzerland
|   |       └── Wireguard selection settings:
|   └── Wireguard settings:
|       ├── Private key: oDF...HI=
|       ├── Interface addresses:
|       |   └── X.X.X.X/32
|       ├── Allowed IPs:
|       |   ├── 0.0.0.0/0
|       |   └── ::/0
|       └── Network interface: tun0
|           └── MTU: 1320
├── DNS settings:
|   ├── Keep existing nameserver(s): no
|   ├── DNS server address to use: 1.1.1.1
|   └── DNS over TLS settings:
|       ├── Enabled: yes
|       ├── Update period: every 24h0m0s
|       ├── Upstream resolvers:
|       |   └── cloudflare
|       ├── Caching: yes
|       ├── IPv6: no
|       └── DNS filtering settings:
|           ├── Block malicious: no
|           ├── Block ads: no
|           ├── Block surveillance: no
|           └── Blocked IP networks:
|               ├── 127.0.0.1/8
|               ├── 10.0.0.0/8
|               ├── 172.16.0.0/12
|               ├── 192.168.0.0/16
|               ├── 169.254.0.0/16
|               ├── ::1/128
|               ├── fc00::/7
|               ├── fe80::/10
|               ├── ::ffff:127.0.0.1/104
|               ├── ::ffff:10.0.0.0/104
|               ├── ::ffff:169.254.0.0/112
|               ├── ::ffff:172.16.0.0/108
|               └── ::ffff:192.168.0.0/112
├── Firewall settings:
|   └── Enabled: yes
├── Log settings:
|   └── Log level: info
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Target address: cloudflare.com:443
|   ├── Duration to wait after success: 5s
|   ├── Read header timeout: 100ms
|   ├── Read timeout: 500ms
|   └── VPN wait durations:
|       ├── Initial duration: 20s
|       └── Additional duration: 5s
├── Shadowsocks server settings:
|   └── Enabled: no
├── HTTP proxy settings:
|   └── Enabled: no
├── Control server settings:
|   ├── Listening address: :8000
|   ├── Logging: yes
|   └── Authentication file path: /gluetun/auth/config.toml
├── Storage settings:
|   └── Filepath: /gluetun/servers.json
├── OS Alpine settings:
|   ├── Process UID: 1000
|   └── Process GID: 1000
├── Public IP settings:
|   ├── IP file path: /tmp/gluetun/ip
|   ├── Public IP data base API: ipinfo
|   └── Public IP data backup APIs:
|       ├── ifconfigco
|       ├── ip2location
|       └── cloudflare
└── Version settings:
    └── Enabled: yes
2025-02-05T11:06:02Z WARN DNS address is set to 1.1.1.1 so the DNS over TLS (DoT) server will not be used. The default value changed to 127.0.0.1 so it uses the internal DoT serves. If the DoT server fails to start, the IPv4 address of the first plaintext DNS server corresponding to the first DoT provider chosen is used.
2025-02-05T11:06:02Z INFO [routing] default route found: interface eth0, gateway 172.28.0.1, assigned IP 172.28.0.2 and family v4
2025-02-05T11:06:02Z INFO [routing] adding route for 0.0.0.0/0
2025-02-05T11:06:02Z INFO [firewall] setting allowed subnets...
2025-02-05T11:06:02Z INFO [routing] default route found: interface eth0, gateway 172.28.0.1, assigned IP 172.28.0.2 and family v4
2025-02-05T11:06:02Z INFO [dns] using plaintext DNS at address 1.1.1.1
2025-02-05T11:06:02Z INFO [http server] http server listening on [::]:8000
2025-02-05T11:06:02Z INFO [healthcheck] listening on 127.0.0.1:9999
2025-02-05T11:06:02Z INFO [firewall] allowing VPN connection...
2025-02-05T11:06:02Z INFO [wireguard] Using available kernelspace implementation
2025-02-05T11:06:02Z INFO [wireguard] Connecting to X.X.X.X:51820
2025-02-05T11:06:02Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2025-02-05T11:06:02Z INFO [dns] downloading hostnames and IP block lists
2025-02-05T11:06:02Z INFO [healthcheck] healthy!
2025-02-05T11:06:02Z INFO [dns] DNS server listening on [::]:53
2025-02-05T11:06:02Z INFO [dns] ready
2025-02-05T11:06:03Z INFO [ip getter] Public IP address is X.X.X.X (Switzerland, Zurich, Zürich - source: ipinfo)
2025-02-05T11:06:03Z INFO [vpn] You are running 1 commit behind the most recent latest
```

### Share your configuration

```yml
services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=XXXXXXXXXXXXX
      - WIREGUARD_ADDRESSES=X.X.X.X/32
      - SERVER_COUNTRIES=Switzerland
      - BLOCK_MALICIOUS=off
      - BLOCK_SURVEILLANCE=off
      - BLOCK_ADS=off
      - DNS_ADDRESS=1.1.1.1
      - HEALTH_VPN_DURATION_INITIAL=20s
    ports:
      - "0.0.0.0:9091:9091/tcp"
      - 51413:51413
      - 51413:51413/udp
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - UMASK="022"
    volumes:
      - ./data:/config
      - /disk2/share2/torrent:/share2-torrent
      - /disk1/share1/torrent-watch:/watch
      - /disk1/share1/torrent:/share1-torrent
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
```
