### ISSUE TITLE
Bug: Torrents behind gluetun suddenly cannot resolve magnet links. Stuck in "Downloading metadata"

### ISSUE THREAD

**Issue by cryo-dog** [qdm12/gluetun#2735]
### Is this urgent?

None

### Host OS

Debian 12 (bookworm): Raspberry Pi OS Lite

### CPU arch

aarch64

### VPN service provider

Surfshark

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2025-01-22T08:30:14.628Z (commit 13532c8)

### What's the problem 🤔

I am using qbittorrent behind gluetun in a stack on my raspberry pi 5 with Ubuntu and OMV (now also tried deluge but same issue). Everything was working fine for quite a long time but recently my magnet link downloads are getting stuck in "Downloading metadata". Same happens for torrent ip leak test sites.

When it fist started appearing, I haven't changed anything. By now I treat quite a lot of options (ipv4 only, setting [1.1.1.1](http://1.1.1.1/) as dns etc.) but nothing works. Anyone with similar issues and ideas how to solve it?

For now the workaround is a list of trackers that I auto append to all downloads but I would much rather have it actually work how it should + even the leak tests like [ipleak.net](http://ipleak.net/), bash ws etc. are not working (for some reason also some of the leak tests that have a torrent file don't work).

Existing torrents work fine though and the workaround with the tracker list also works.

If I use gluetun as a http proxy, I can surf the internet without issues. Only torrents and gluetun make issues. (qbittorrent from my desktop with gluetun as http proxy also does not work)

As said, I haven't really touched the stack but OMV and watchtower both keep everything automatically updated so that cannot be ruled out.

### Share your logs (at least 10 lines)

```plain text
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================
Running version latest built on 2025-01-22T08:30:14.628Z (commit 13532c8)
🔧 Need help? ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new/choose
🐛 Bug? ✨ New feature? https://github.com/qdm12/gluetun/issues/new/choose
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2025-03-06T15:40:39Z INFO [routing] default route found: interface eth0, gateway 172.23.0.1, assigned IP 172.23.0.2 and family v4
2025-03-06T15:40:39Z INFO [routing] local ethernet link found: eth0
2025-03-06T15:40:39Z INFO [routing] local ipnet found: 172.23.0.0/16
2025-03-06T15:40:39Z INFO [firewall] enabling...
2025-03-06T15:40:40Z INFO [firewall] enabled successfully
2025-03-06T15:40:42Z INFO [storage] merging by most recent 20776 hardcoded servers and 20776 servers read from /gluetun/servers.json
2025-03-06T15:40:42Z INFO Alpine version: 3.20.5
2025-03-06T15:40:42Z INFO OpenVPN 2.5 version: 2.5.10
2025-03-06T15:40:42Z INFO OpenVPN 2.6 version: 2.6.11
2025-03-06T15:40:42Z INFO IPtables version: v1.8.10
2025-03-06T15:40:42Z INFO Settings summary:
├── VPN settings:
|   ├── VPN provider settings:
|   |   ├── Name: surfshark
|   |   └── Server selection settings:
|   |       ├── VPN type: wireguard
|   |       ├── Countries: netherlands
|   |       └── Wireguard selection settings:
|   └── Wireguard settings:
|       ├── Private key: mIF...Vs=
|       ├── Interface addresses:
|       |   └── 10.14.0.2/16
|       ├── Allowed IPs:
|       |   ├── 0.0.0.0/0
|       |   └── ::/0
|       └── Network interface: tun0
|           └── MTU: 1320
├── DNS settings:
|   ├── Keep existing nameserver(s): no
|   ├── DNS server address to use: 127.0.0.1
|   └── DNS over TLS settings:
|       ├── Enabled: yes
|       ├── Update period: every 24h0m0s
|       ├── Upstream resolvers:
|       |   └── cloudflare
|       ├── Caching: yes
|       ├── IPv6: no
|       └── DNS filtering settings:
|           ├── Block malicious: yes
|           ├── Block ads: no
|           ├── Block surveillance: no
|           └── Blocked IP networks:
|               ├── 127.0.0.1/8
|               ├── 10.0.0.0/8
|               ├── 172.16.0.0/12
|               ├── 192.168.0.0/16
|               ├── 169.254.0.0/16
|               ├── ::1/128
|               ├── fc00::/7
|               ├── fe80::/10
|               ├── ::ffff:127.0.0.1/104
|               ├── ::ffff:10.0.0.0/104
|               ├── ::ffff:169.254.0.0/112
|               ├── ::ffff:172.16.0.0/108
|               └── ::ffff:192.168.0.0/112
├── Firewall settings:
|   └── Enabled: yes
├── Log settings:
|   └── Log level: info
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Target address: cloudflare.com:443
|   ├── Duration to wait after success: 5s
|   ├── Read header timeout: 100ms
|   ├── Read timeout: 500ms
|   └── VPN wait durations:
|       ├── Initial duration: 6s
|       └── Additional duration: 5s
├── Shadowsocks server settings:
|   └── Enabled: no
├── HTTP proxy settings:
|   ├── Enabled: yes
|   ├── Listening address: :8888
|   ├── User: 
|   ├── Password: [not set]
|   ├── Stealth mode: no
|   ├── Log: no
|   ├── Read header timeout: 1s
|   └── Read timeout: 3s
├── Control server settings:
|   ├── Listening address: :8000
|   ├── Logging: yes
|   └── Authentication file path: /gluetun/auth/config.toml
├── Storage settings:
|   └── Filepath: /gluetun/servers.json
├── OS Alpine settings:
|   ├── Process UID: 1003
|   └── Process GID: 100
├── Public IP settings:
|   ├── IP file path: /tmp/gluetun/ip
|   ├── Public IP data base API: ipinfo
|   └── Public IP data backup APIs:
|       ├── ifconfigco
|       ├── ip2location
|       └── cloudflare
└── Version settings:
    └── Enabled: yes
2025-03-06T15:40:42Z INFO [routing] default route found: interface eth0, gateway 172.23.0.1, assigned IP 172.23.0.2 and family v4
2025-03-06T15:40:42Z INFO [routing] adding route for 0.0.0.0/0
2025-03-06T15:40:42Z INFO [firewall] setting allowed subnets...
2025-03-06T15:40:42Z INFO [routing] default route found: interface eth0, gateway 172.23.0.1, assigned IP 172.23.0.2 and family v4
2025-03-06T15:40:42Z INFO [http server] http server listening on [::]:8000
2025-03-06T15:40:42Z INFO [healthcheck] listening on 127.0.0.1:9999
2025-03-06T15:40:42Z INFO [dns] using plaintext DNS at address 1.1.1.1
2025-03-06T15:40:42Z INFO [firewall] allowing VPN connection...
2025-03-06T15:40:42Z INFO [http proxy] listening on :8888
2025-03-06T15:40:42Z INFO [wireguard] Using available kernelspace implementation
2025-03-06T15:40:42Z INFO [wireguard] Connecting to [external ip redacted]:51820
2025-03-06T15:40:42Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2025-03-06T15:40:43Z INFO [dns] downloading hostnames and IP block lists
2025-03-06T15:40:44Z INFO [dns] DNS server listening on [::]:53
2025-03-06T15:40:45Z INFO [healthcheck] healthy!
2025-03-06T15:40:45Z INFO [dns] ready
2025-03-06T15:40:45Z INFO [ip getter] Public IP address is [external ip redacted] (Netherlands, North Holland, Amsterdam - source: ipinfo)
2025-03-06T15:40:45Z INFO [vpn] You are running 1 commit behind the most recent latest
2025-03-06T16:00:56Z INFO [healthcheck] healthy!
2025-03-06T16:10:51Z WARN [dns] exchanging over tls connection for request IN AAAA torrentdns4-[...].dnstest4.top10vpn.com.: read tcp 10.14.0.2:45770->1.0.0.1:853: i/o timeout
```

### Share your configuration

```yml
services:
 gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
#    sysctls: # I tried this as a workaround... did not work
#      - net.ipv6.conf.all.disable_ipv6=1
#      - net.ipv6.conf.default.disable_ipv6=1
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
#      - VPN_ENDPOINT_IP_VERSION=4
#      - VPN_TYPE=openvpn #same issue with openvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=[redacted]
      - WIREGUARD_ADDRESSES=10.14.0.2/16
#      - OPENVPN_USER=deleted
#      - OPENVPN_PASSWORD=[redacted]
#      - OPENVPN_CUSTOM_CONFIG=/gluetun/surfsharkbarca.conf
      - SERVER_COUNTRIES=Netherlands
      - PUID=1003
      - PGID=100
      - HTTPPROXY=on
      #- UPDATER_PERIOD=48h
    volumes:
      - /appdata/gluetun:/gluetun
    ports:
      - 8080:8080 # qBittorrent 
      - 7336:7336 # qBittorrent
      - 7336:7336/udp # qBittorrent
      - 8112:8112 # deluge
      - 6881:6881 # deluge
      - 6881:6881/udp # deluge
    labels:
      - "com.centurylinklabs.watchtower.enable=true" 
    restart: unless-stopped

  deluge: # also tried deluge but same issue
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1003
      - PGID=100
      - TZ=Europe/Berlin
      - DELUGE_LOGLEVEL=error #optional
      - UMASK=002
    volumes:
      - /appdata/deluge/config:/config
      - /mnt/hdd1/SambaShare/torrents:/downloads
    network_mode: "service:gluetun"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
#    sysctls:
#      - net.ipv6.conf.all.disable_ipv6=1
#      - net.ipv6.conf.default.disable_ipv6=1
    environment:
      - PUID=1003
      - PGID=100
      - TZ=Europe/Berlin
      - WEBUI_PORT=8080
#      - TORRENTING_PORT=7336 # Selected random in qbittorrent but also did not work
      - UMASK=002
    volumes:
      - /appdata/qbittorrent/appdata:/config
      - /appdata/torrent-downloading:/incomplete
      - /appdata/logs/qbittorrent:/config/qBittorrent/logs
      - /mnt/hdd1/SambaShare/torrents:/data/torrents 
    network_mode: "service:gluetun"
    restart: unless-stopped
    healthcheck: # https://github.com/qdm12/gluetun/issues/641#issuecomment-933856220
      test: "curl -sf https://example.com  || exit 1"
      interval: $INTERVAL
      timeout: 10s
      retries: $RETRIES
      start_period: $STARTP
```
