### ISSUE TITLE
Bug: HEALTH_TARGET_ADDRESS to default value of cloudflare.com:443

### ISSUE THREAD

**Issue by yantex0** [qdm12/gluetun#2784]
### Is this urgent?

No

### Host OS

RHEL 9.5

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

Podman

### What is the version of Gluetun

Running version latest built on 2025-01-22T08:30:14.628Z (commit 13532c8)

### What's the problem 🤔

Gluetun container exits with ExitCode: 2 when HEALTH_TARGET_ADDRESS=cloudflare:443 ie default value. When I add HEALTH_TARGET_ADDRESS=1.1.1.1 the container works. Not familiar with submitting issues in Github, sorry if this should be a pull request or something else entirely, just thought it might help someone if they run into this issue on Podman.

### Share your logs (at least 10 lines)

```plain text
command: podman inspect gluetun #using cloudflare:443 ie no HEALTH_TARGET_ADDRESS env variable

[
     {
          "Id": "239d229fb3c679247a026daee707c84a010a14d5de1a94dd75c1ea4b584d0d50",
          "Created": "2025-04-21T12:04:46.809369492+10:00",
          "Path": "/gluetun-entrypoint",
          "Args": [
               "/gluetun-entrypoint"
          ],
          "State": {
               "OciVersion": "1.2.0",
               "Status": "exited",
               "Running": false,
               "Paused": false,
               "Restarting": false,
               "OOMKilled": false,
               "Dead": false,
               "Pid": 0,
               "ExitCode": 2,
               "Error": "",
               "StartedAt": "2025-04-21T12:04:48.333943871+10:00",
               "FinishedAt": "2025-04-21T12:06:24.696379573+10:00",
               "Health": {
                    "Status": "healthy",
                    "FailingStreak": 0,
                    "Log": [
                         {
                              "Start": "2025-04-21T12:04:48.419742071+10:00",
                              "End": "2025-04-21T12:04:48.486962057+10:00",
                              "ExitCode": 1,
                              "Output": "Device \"tun0\" does not exist.\n"
                         },
                         {
                              "Start": "2025-04-21T12:05:48.95826194+10:00",
                              "End": "2025-04-21T12:05:49.021686682+10:00",
                              "ExitCode": 0,
                              "Output": "4: tun0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1320 qdisc noqueue state UNKNOWN group default \n    link/none \n    inet 10.2.0.2/32 scope global tun0\n       valid_lft forever preferred_lft forever\n"
                         }
                    ]
               },
               "CheckpointedAt": "0001-01-01T00:00:00Z",
               "RestoredAt": "0001-01-01T00:00:00Z",
               "StoppedByUser": true
          },

command: podman inspect gluetun #using 1.1.1.1 ie HEALTH_TARGET_ADDRESS=1.1.1.1 env variable

[
     {
          "Id": "77b5b4fb014c3919ec7afd4a3d38f8cf68d8ad0cf8631be18df36cd7ea3b544d",
          "Created": "2025-04-21T12:10:21.99249194+10:00",
          "Path": "/gluetun-entrypoint",
          "Args": [
               "/gluetun-entrypoint"
          ],
          "State": {
               "OciVersion": "1.2.0",
               "Status": "running",
               "Running": true,
               "Paused": false,
               "Restarting": false,
               "OOMKilled": false,
               "Dead": false,
               "Pid": 441364,
               "ConmonPid": 441362,
               "ExitCode": 0,
               "Error": "",
               "StartedAt": "2025-04-21T12:10:23.894215445+10:00",
               "FinishedAt": "0001-01-01T00:00:00Z",
               "Health": {
                    "Status": "healthy",
                    "FailingStreak": 0,
                    "Log": [
                         {
                              "Start": "2025-04-21T12:10:23.981548279+10:00",
                              "End": "2025-04-21T12:10:24.047472584+10:00",
                              "ExitCode": 1,
                              "Output": "Device \"tun0\" does not exist.\n"
                         },
                         {
                              "Start": "2025-04-21T12:11:25.007060557+10:00",
                              "End": "2025-04-21T12:11:25.080776774+10:00",
                              "ExitCode": 0,
                              "Output": "3: tun0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1320 qdisc noqueue state UNKNOWN group default \n    link/none \n    inet 10.2.0.2/32 scope global tun0\n       valid_lft forever preferred_lft forever\n"
                         },
                         {
                              "Start": "2025-04-21T12:12:25.965088608+10:00",
                              "End": "2025-04-21T12:12:26.030675523+10:00",
                              "ExitCode": 0,
                              "Output": "3: tun0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1320 qdisc noqueue state UNKNOWN group default \n    link/none \n    inet 10.2.0.2/32 scope global tun0\n       valid_lft forever preferred_lft forever\n"
                         }
                    ]
               },
               "CgroupPath": "/user.slice/user-1000.slice/user@1000.service/user.slice/user-libpod_pod_f0a5a82919e5d611e445e806063d1cef4625fb5d9b6c8d0d297b3648e44a50fc.slice/libpod-77b5b4fb014c3919ec7afd4a3d38f8cf68d8ad0cf8631be18df36cd7ea3b544d.scope",
               "CheckpointedAt": "0001-01-01T00:00:00Z",
               "RestoredAt": "0001-01-01T00:00:00Z"
          },
```

### Share your configuration

```yml
Simply uncommenting the HEALTH_TARGET_ADDRESS line fixes the issue.

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    privileged: true
    container_name: gluetun
    restart: always
#    cap_add:
#      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8000:8000/tcp"           # Gluetun Status Port
      - "8888:8888/tcp"           # Gluetun Local Network HTTP proxy
      - "8388:8388/tcp"           # Gluetun Local Network Shadowsocks
      - "8388:8388/udp"           # Gluetun Local Network Shadowsocks
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/gluetun:/gluetun:Z
    environment:
    # Generic Environment Variables
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
    #VPN
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
    # Gluetun Environment Variables
#      - HEALTH_TARGET_ADDRESS=1.1.1.1
    networks:
      - mediastack
    healthcheck:
      test: ["CMD", "ip", "a", "show", "tun0"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 2m
```
