### ISSUE TITLE
Bug: API ProtonVPN - Invalid access token - 401 Unauthorized

### ISSUE THREAD

**Issue by Paulpatou** [qdm12/gluetun#2788]
### Is this urgent?

Yes

### Host OS

Ubuntu

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2025-01-22T08:30:14.628Z (commit 13532c8)

### What's the problem 🤔

Hello,

I am using Gluetun and updating the servers.json list via a Docker container with the following command: command: update -enduser -providers protonvpn. However, it seems that the ProtonVPN API has been modified recently, and the method for connecting to retrieve the servers is no longer functioning (please see the logs I have provided).

Could you please look into this issue? Any guidance on how to resolve it or updates regarding the API changes would be greatly appreciated.

Additionally, I noticed that the message "Using mullvad servers" appears when I specify "protonvpn." Is this expected behavior, or does it indicate a configuration issue?

Thank you for your help!

Best regards,

### Share your logs (at least 10 lines)

```plain text
INFO merging by most recent 20776 hardcoded servers and 20797 servers read from /gluetun/servers.json
 INFO Using mullvad servers from file which are 665 days more recent
 INFO updating Protonvpn servers...
 ERROR updating server information: getting servers: HTTP status code not OK: 401 401 Unauthorized
 INFO Shutdown successful
```

### Share your configuration

```yml
services:
  gluetun-updater:
    image: qmcgaw/gluetun
    container_name: gluetun-updater
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=IDCREDENTIALS
      - OPENVPN_PASSWORD=PASSWORDCREDENTIALS
      - SERVER_COUNTRIES=Netherlands
      - DNS_ADDRESS=10.16.0.1
      - DOT=off
      - HTTPPROXY=off
      - SHADOWSOCKS=off
      - UPDATER_PERIOD=24h
      - UPDATER_VPN_SERVICE_PROVIDERS=protonvpn
    volumes:
      - /home/user/docker/gluetun_server_updater/server-list-proton:/gluetun
    command: update -enduser -providers protonvpn
```
