### ISSUE TITLE
Bug: Gluetun blocks all incoming connections to the host after switching to `network_mode: host`

### ISSUE THREAD

**Issue by dimitur2204** [qdm12/gluetun#2793]
### Is this urgent?

Yes

### Host OS

Debian Bookworm

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

v3.40.0

### What's the problem 🤔

Note: I have specified the issue as "urgent" since I feel like it could be a big issue for other people, in my specific case the access to that machine I lost is not "urgent".

While experimenting with my ports configuration in Docker, I originally had a large list of ports exposed. To simplify, I decided to switch Gluetun to use `network_mode: host`. After doing so, it seems Gluetun's firewall is now blocking all incoming connections on the host system.

As a result:

- All services publicly exposed through Cloudflare and routed with nginx are unreachable.
- Access through Tailscale also fails.
- **SSH access directly over the public IP fails** with ` Connection reset by peer error` (note: port 22 is not exposed on my router, so this might be expected)
-  **SSH via Tailscale fails with** `Operation timed out error`

Expected behavior: 

I am not sure what the expected behaviour is, now that I think about it probably it does not make sense to use `network_mode: host` at all, but I certianly did not expect to get locked out of my system completely, I will be able to access the machine physically in a couple of days and can give more detailed logs then, any help currently will be greatly appreciated.

### Share your logs (at least 10 lines)

```plain text
I do not have access to the machine that was running the container anymore, can't provide logs.
-
-
-
-
-
-
-
-
-
Sorry for that, but I do not see another way to open an issue that has no logs
```

### Share your configuration

```yml
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    # I had the ports defined like this initially
    # ports: 
    #  - 8888:8888/tcp # HTTP proxy
    #  - 8388:8388/tcp # Shadowsocks
    #  - 8388:8388/udp # Shadowsocks
    #  - 51413:51413
    #  - 51413:51413/udp
    # This below is the change that broke the network
    network_mode: host
    volumes:
      - /mnt/wd/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - VPN_PORT_FORWARDING=on
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=Netherlands
      - TZ=Europe/Sofia
      - UPDATER_PERIOD=24h
networks: {}
```
