### ISSUE TITLE
Bug: Network stalls for Torrent client container but other containers traffic is fine

### ISSUE THREAD

**Issue by nebbit32** [qdm12/gluetun#2807]
### Is this urgent?

Yes

### Host OS

Docker Compose (Ubuntu 24.04)

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

qmcgaw/gluetun - latest (18/05/2025)

### What's the problem 🤔

Please help. I have been playing with my configuration now for months. I have tried qBittorrent & Deluge. I have tried every combination of DNS /  DOT settings in my compose file yet the torrent client hangs and fails to download metadata and / or just doesn't do anything at all and stalls.

I don't quite understand how the DNS resolving works in Gluetun. I am pointing my Gluetun configuration to NordVPN using Wireguard. I have a firewall rule on my pfSense which restricts the LAN IP of the Gluetun box out onto the internet 'ONLY' through the Wireguard port. I was thinking how does it do the initial DNS lookup for the NordVPN server address?

I started running packet traces on my pfSense. It appears the DNS lookups happen with the source address as the Docker host instead of listening to my configuration. My configuration uses Docker ipvlan L2 for Gluetun, and I specify a seperate IP address for Gluetun so I can distinguish between the host traffic, and the Gluetun / container traffic. The Docker host LAN IP is '10.239.173.22' & the container IP is set to '10.239.173.250'. So all traffic from the host should fly about from '.22' and all traffic from the containers, including Gluetun, should fly about my network from '.250'. This way, on my pfSense, I can say 'allow absolutely all traffic from .22 (host) but restrict traffic from .250 (containers) to Wireguard port.

Anyway, the stack works fine, but after X amount of hours / days the other containers networks work fine, but the torrent client stalls in terms of traffic. After looking through tonnes and tonnes of Reddit posts & GitHub pages, apparantly Gluetun by default uses DoT DNS instead of plain? I ran a packet trace on my pfSense while switching between lots of different DNS configurations in my compose file and not once, did I find a single packet flying about on port 853 (DoT).

Is there something I am missing? When I packet trace plain DNS port 53 I find the DNS lookups are ignoring my configuration and using the hosts IP of '.22'. I can't find any trace of DoT traffic in or out of the containers or host.

I'm assuming the issue is DNS related. I see timeout errors for DNS after some time in the Gluetun logs.

### Share your logs (at least 10 lines)

```plain text
|   |   └── Server selection settings:

|   |       ├── VPN type: wireguard

|   |       ├── Countries: united kingdom

|   |       ├── Categories: p2p

|   |       └── Wireguard selection settings:

|   └── Wireguard settings:

|       ├── Private key: <REDACTED>

|       ├── Interface addresses:

|       |   └── 10.5.0.2/32

|       ├── Allowed IPs:

|       |   ├── 0.0.0.0/0

|       |   └── ::/0

|       └── Network interface: tun0

|           └── MTU: 1320

├── DNS settings:

|   ├── Keep existing nameserver(s): no

|   ├── DNS server address to use: 127.0.0.1

|   └── DNS over TLS settings:

|       ├── Enabled: yes

|       ├── Update period: every 24h0m0s

|       ├── Upstream resolvers:

|       |   └── cloudflare

|       ├── Caching: yes

|       ├── IPv6: no

|       └── DNS filtering settings:

|           ├── Block malicious: yes

|           ├── Block ads: no

|           ├── Block surveillance: no

|           └── Blocked IP networks:

|               ├── 127.0.0.1/8

|               ├── 10.0.0.0/8

|               ├── 172.16.0.0/12

|               ├── 192.168.0.0/16

|               ├── 169.254.0.0/16

|               ├── ::1/128

|               ├── fc00::/7

|               ├── fe80::/10

|               ├── ::ffff:127.0.0.1/104

|               ├── ::ffff:10.0.0.0/104

|               ├── ::ffff:169.254.0.0/112

|               ├── ::ffff:172.16.0.0/108

|               └── ::ffff:192.168.0.0/112

├── Firewall settings:

|   └── Enabled: yes

├── Log settings:

|   └── Log level: info

├── Health settings:

|   ├── Server listening address: 127.0.0.1:9999

|   ├── Target address: cloudflare.com:443

|   ├── Duration to wait after success: 5s

|   ├── Read header timeout: 100ms

|   ├── Read timeout: 500ms

|   └── VPN wait durations:

|       ├── Initial duration: 6s

|       └── Additional duration: 5s

├── Shadowsocks server settings:

|   └── Enabled: no

├── HTTP proxy settings:

|   └── Enabled: no

├── Control server settings:

|   ├── Listening address: :8000

|   ├── Logging: yes

|   └── Authentication file path: /gluetun/auth/config.toml

├── Storage settings:

|   └── Filepath: /gluetun/servers.json

├── OS Alpine settings:

|   ├── Process UID: 111

|   ├── Process GID: 111

|   └── Timezone: europe/london

├── Public IP settings:

|   ├── IP file path: /tmp/gluetun/ip

|   ├── Public IP data base API: ipinfo

|   └── Public IP data backup APIs:

|       ├── ifconfigco

|       ├── ip2location

|       └── cloudflare

├── Server data updater settings:

|   ├── Update period: 24h0m0s

|   ├── DNS address: 1.1.1.1:53

|   ├── Minimum ratio: 0.8

|   └── Providers to update: nordvpn

└── Version settings:

    └── Enabled: yes

2025-05-18T14:37:04+01:00 INFO [routing] default route found: interface eth0, gateway 10.239.173.10, assigned IP 10.239.173.250 and family v4

2025-05-18T14:37:04+01:00 INFO [routing] adding route for 0.0.0.0/0

2025-05-18T14:37:04+01:00 INFO [firewall] setting allowed subnets...

2025-05-18T14:37:04+01:00 INFO [routing] default route found: interface eth0, gateway 10.239.173.10, assigned IP 10.239.173.250 and family v4

2025-05-18T14:37:04+01:00 INFO [dns] using plaintext DNS at address 1.1.1.1

2025-05-18T14:37:04+01:00 INFO [http server] http server listening on [::]:8000

2025-05-18T14:37:04+01:00 INFO [healthcheck] listening on 127.0.0.1:9999

2025-05-18T14:37:04+01:00 INFO [firewall] allowing VPN connection...

2025-05-18T14:37:04+01:00 INFO [wireguard] Using available kernelspace implementation

2025-05-18T14:37:04+01:00 INFO [wireguard] Connecting to 152.89.207.173:51820

2025-05-18T14:37:04+01:00 INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.

2025-05-18T14:37:04+01:00 INFO [dns] downloading hostnames and IP block lists

2025-05-18T14:37:04+01:00 INFO [healthcheck] healthy!

2025-05-18T14:37:05+01:00 INFO [dns] DNS server listening on [::]:53

2025-05-18T14:37:05+01:00 INFO [dns] ready

2025-05-18T14:37:05+01:00 INFO [ip getter] Public IP address is 103.219.20.230 (United Kingdom, England, Manchester - source: ipinfo)

2025-05-18T14:37:06+01:00 INFO [vpn] You are running 1 commit behind the most recent latest
```

### Share your configuration

```yml
# --------------------------------------------------
name: torstack
# --------------------------------------------------
networks:
# --------------------------------------------------
  tornet:
    driver: ipvlan
    driver_opts:
      parent: eth0
      ipvlan_mode: l2
    ipam:
      config:
      - subnet: 10.239.173.0/24
        gateway: 10.239.173.10
# --------------------------------------------------
services:
# --------------------------------------------------
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      tornet:
        ipv4_address: 10.239.173.250
    environment:
      - PUID=111 # gluetun
      - PGID=111 # gluetun
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=<REDACTED>
      - WIREGUARD_ADDRESSES=10.5.0.2/32
      - SERVER_CATEGORIES=P2P
      - SERVER_COUNTRIES=United Kingdom
      - TZ=Europe/London
      - UPDATER_PERIOD=24h
    volumes:
      - /docker/volumes/gluetun:/gluetun
    restart: unless-stopped
# --------------------------------------------------
```
