### ISSUE TITLE
Bug: Port Forwarding not working on Air VPN

### ISSUE THREAD

**Issue by ooTruffle** [qdm12/gluetun#2809]
### Is this urgent?

No

### Host OS

Debian bookworm

### CPU arch

x86_64

### VPN service provider

AirVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

airvpn  | Running version latest built on 2025-01-22T08:30:14.628Z (commit 13532c8)

### What's the problem 🤔

When trying to setup port forwarding for torrneting  the container just stops itself,  im notsure what to put to get this to work

### Share your logs (at least 10 lines)

```plain text
airvpn  | ========================================
airvpn  | ========================================
airvpn  | =============== gluetun ================
airvpn  | ========================================
airvpn  | =========== Made with ❤️ by ============
airvpn  | ======= https://github.com/qdm12 =======
airvpn  | ========================================
airvpn  | ========================================
airvpn  | 
airvpn  | Running version latest built on 2025-01-22T08:30:14.628Z (commit 13532c8)
airvpn  | 
airvpn  | 🔧 Need help? ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new/choose
airvpn  | 🐛 Bug? ✨ New feature? https://github.com/qdm12/gluetun/issues/new/choose
airvpn  | 💻 Email? quentin.mcgaw@gmail.com
airvpn  | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
airvpn  | 2025-05-19T15:42:50Z INFO [routing] default route found: interface eth0, gateway 192.168.16.1, assigned IP 192.168.16.2 and family v4
airvpn  | 2025-05-19T15:42:50Z INFO [routing] local ethernet link found: eth0
airvpn  | 2025-05-19T15:42:50Z INFO [routing] local ipnet found: 192.168.16.0/20
airvpn  | 2025-05-19T15:42:50Z INFO [firewall] enabling...
airvpn  | 2025-05-19T15:42:50Z INFO [firewall] enabled successfully
airvpn  | 2025-05-19T15:42:51Z INFO [storage] merging by most recent 20776 hardcoded servers and 20776 servers read from /gluetun/servers.json
airvpn  | 2025-05-19T15:42:51Z ERROR VPN settings: provider settings: port forwarding: port forwarding cannot be enabled: value is not one of the possible choices: airvpn must be one of perfect privacy, private internet access, privatevpn or protonvpn
airvpn  | 2025-05-19T15:42:51Z INFO Shutdown successful
airvpn exited with code 1
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: airvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=airvpn
      - FIREWALL_OUTBOUND_SUBNETS=[localip]
      - FIREWALL_VPN_INPUT_PORTS=9856
      - VPN_PORT_FORWARDING=ON
      - VPN_PORT_FORWARDING_PROVIDER=airvpn
    volumes:
      - /home/truffle/gluetun:/gluetun
    ports:
      - 8112:8112
      - 8080:8080
      - 58846:58846 #optional
networks: {}
```
