### ISSUE TITLE
Bug: protonvpn servers update broken? 400 Bad Request

### ISSUE THREAD

**Issue by dot-i** [qdm12/gluetun#2820]
### Is this urgent?

Yes

### Host OS

Unraid

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2025-01-22T08:30:14.628Z (commit 13532c8)

### What's the problem 🤔

Tried to run:

```docker run --rm -v /mnt/cache/appdata/gluetun:/gluetun ghcr.io/qdm12/gluetun update -enduser -providers protonvpn```

But get a Bad Request Error

### Share your logs (at least 10 lines)

```plain text
2025-06-04T22:31:32Z INFO merging by most recent 20776 hardcoded servers and 20776 servers read from /gluetun/servers.json
2025-06-04T22:31:33Z INFO updating Protonvpn servers...
2025-06-04T22:31:33Z ERROR updating server information: getting servers: HTTP status code not OK: 400 400 Bad Request
2025-06-04T22:31:33Z INFO Shutdown successful
```

### Share your configuration

```yml
gluetun:
    container_name: gluetun
    image: ghcr.io/qdm12/gluetun:latest
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://static-00.iconduck.com/assets.00/vpn-icon-1863x2048-b1dwlnad.png'
      net.unraid.docker.webui: ''
      net.unraid.docker.shell: ''
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /mnt/user/appdata/gluetun:/gluetun
    environment:
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
      - SERVER_COUNTRIES=Belgium
```
