### ISSUE TITLE
Feature request: Add support for Docker secrets

### ISSUE THREAD

**Issue by averri** [qdm12/gluetun#306]
**What's the feature?** 🧐
To add support for Docker secrets for all sensitive data like  `USER` and `PASSWORD`.

It should be able to start the service using the following docker-compose.yml:

```yaml
version: "3"

services:

  gluetun:
    image: qmcgaw/private-internet-access
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # Tinyproxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
    environment:
      - VPNSP=private internet access
      - TZ=${TZ}
      - USER_FILE=/run/secrets/vpn_user
      - PASSWORD_FILE=/run/secrets/vpn_password
    restart: unless-stopped
    secrets:
      - vpn_user
      - vpn_password

secrets:
    vpn_user:
        file: vpn_user.txt
    vpn_password:
        file: vpn_password.txt
```

- Support this new feature because that and that
Docker secrets are a standard way of handling sensitive information.
