### ISSUE TITLE
Help: image seems to be invisible to Traefik

### ISSUE THREAD

**Issue by codetheweb** [qdm12/gluetun#312]
**Host OS**: Ubuntu 20

**Is this urgent?**: No

**What VPN provider are you using**: PIA

**What is the version of the program** (See the line at the top of your logs)

```
Running version latest built on 2020-12-06T21:20:02Z (commit 3f721b1)
```

**What's the problem** 🤔

I realize this is probably out of scope, but I was wondering if you had any ideas on how to debug this issue.

I have Deluge traffic routed through a Gluetun container, and the Deluge Web UI is made available using Traefik. This setup was working perfectly fine until today, and I can't think of anything that I did to change things other than a reboot.

The situation:
- ✅ VPN container can connect to the internet (`curl ifconfig.me` works correctly)
- ✅ Running `curl localhost:8112` in the VPN container works
- ✅ Running `wget <VPN container IP>:8112` in the Traefik container works
- ✅ Replacing *just* the container image in the below compose file with `containous/whoami` makes it magically work
- 🟥 A route for the VPN container never appears in the Traefik Web UI (Traefik doesn't detect the container)

What I've tried:
- Rolling back to previous versions of Gluetun / Traefik
- Disabling the Gluetun firewall
- Reboots, rebuilding compose stack, etc

I've spent a good 4+ hours on this at this point and I have no idea what's going on. I feel like it is related to this image specifically since replacing it with something else works fine.

**Share your logs...**

Gluetun logs look good.

**What are you using to run your container?**: Docker Compose

Please also share your configuration file:

```yml
version: '3'

services:
  vpn:
    image: qmcgaw/private-internet-access:latest # replacing with containous/whoami works
    container_name: seedbox-vpn
    restart: always
    cap_add:
      - NET_ADMIN
    networks:
      - web
    environment:
      USER: ''
      PASSWORD: ''
      FIREWALL_INPUT_PORTS: 8112
    volumes:
      - /docker/seedbox/vpn:/gluetun
    expose:
      - 8112
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.vpn.loadbalancer.server.port=8112"
      - "traefik.http.routers.vpn.rule=Host(`deluge.example.com`)"
      - "traefik.http.routers.vpn.tls.certresolver=default"
      - "traefik.http.routers.vpn.middlewares=google-auth@file"
...
```

**Potentially related issues:**

https://github.com/qdm12/gluetun/issues/254
