### ISSUE TITLE
ERROR routing: cannot teardown routing: cannot delete route for 0.0.0.0/0: operation not permitted

### ISSUE THREAD

**Issue by prokreato** [qdm12/gluetun#314]
**Host OS** (approximate answer is fine too): Debian GNU/Linux bullseye/sid armv7l (Raspberry PI OS)

**Is this urgent?**: Yes

**What VPN provider are you using**: Mullvad

**What are you using to run your container?**: Docker Compose

**What is the version of the program** (See the line at the top of your logs)

Running version latest built on 2020-12-20T01:11:04Z (commit 4257581)

**What's the problem** 🤔

```
2020-12-20T13:51:02.689Z	INFO	routing: deleting route for 0.0.0.0/0
2020-12-20T13:51:02.690Z	ERROR	routing: cannot teardown routing: cannot delete route for 0.0.0.0/0: operation not permitted
2020-12-20T13:51:02.690Z	ERROR	cannot setup routing: operation not permitted
```

**Share your logs...**

```
=========================================,
================ Gluetun ================,
=========================================,
==== A mix of OpenVPN, DNS over TLS, ====,
======= Shadowsocks and HTTP proxy ======,
========= all glued up with Go ==========,
=========================================,
=========== For tunneling to ============,
======== your favorite VPN server =======,
=========================================,
=== Made with ❤️  by github.com/qdm12 ====,
=========================================,
,
Running version latest built on 2020-12-20T01:11:04Z (commit 4257581),
,
,
🔧  Need help? https://github.com/qdm12/gluetun/issues/new,
💻  Email? quentin.mcgaw@gmail.com,
☕  Slack? Join from the Slack button on Github,
💸  Help me? https://github.com/sponsors/qdm12,
2020-12-20T13:51:02.512Z	INFO	OpenVPN version: 2.4.9,
2020-12-20T13:51:02.517Z	INFO	Unbound version: 1.10.1,
2020-12-20T13:51:02.520Z	INFO	IPtables version: v1.8.4,
2020-12-20T13:51:02.521Z	INFO	Settings summary below:,
OpenVPN settings:,
|--User: [redacted],
|--Password: [redacted],
|--Verbosity level: 1,
|--Run as root: no,
|--Mullvad settings:,
 |--Network protocol: udp,
 |--Countries: switzerland,
 |--Cities: zurich,
 |--ISPs: ,
 |--Custom port: ,
 |--IPv6: off,
System settings:,
|--User ID: 1000,
|--Group ID: 1000,
|--Timezone: ,
|--IP Status filepath: /tmp/gluetun/ip,
DNS over TLS settings:,
 |--DNS over TLS provider:,
  |--cloudflare,
 |--Caching: enabled,
 |--Block malicious: enabled,
 |--Block surveillance: disabled,
 |--Block ads: disabled,
 |--Allowed hostnames:,
  |--,
 |--Private addresses:,
  |--127.0.0.1/8,
  |--10.0.0.0/8,
  |--172.16.0.0/12,
  |--192.168.0.0/16,
  |--169.254.0.0/16,
```

so i was running the container with following settings:

```sh
docker run --rm -d --name gluetun --cap-add=NET_ADMIN -e VPNSP="mullvad" -e COUNTRY="Switzerland" -e CITY="Zurich" -e OWNED="yes" -e USER="XXX" -e FIREWALL_VPN_INPUT_PORTS="14239,27702,59530,59726" qmcgaw/private-internet-access:latest
```

and there it runs without problems but if i try it with docker compose i get that error what am i doing wrong

my docker-compose looks like this:

```yml
version: "3.7"
services:
  gluetun:
    image: qmcgaw/private-internet-access
    container_name: gluetun
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
    # command:
    volumes:
      - /home/pi/dockerconfig/pia:/gluetun
    environment:
      # More variables are available, see the readme table
      - VPNSP=mullvad
      - USER=XXX
      - COUNTRY=Switzerland
      - CITY=Zurich
    restart: "no"
```
