### ISSUE TITLE
Help: Communication between containers in the service:gluetun network

### ISSUE THREAD

**Issue by itavero** [qdm12/gluetun#342]
**Host OS**
Ubuntu Server 20.04

**Is this urgent?**: No

**What VPN provider are you using**:
PIA

**What is the version of the program** (See the line at the top of your logs)
```
You are running on the bleeding edge of latest!
```

**What's the problem** 🤔
The containers within the `service:gluetun` need to communicate with each other.
I.e. `sonarr` needs to access `jackett`.

It's unclear to me what the hostname should be that I can use (I tried `jackett`, `gluetun` and the hostname of my server.. all without success).

**What are you using to run your container?**:
Docker Compose (via Portainer)

Please also share your configuration file:

```yml
version: "2"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8008:8000/tcp # Built-in HTTP control server
      - 8989:8989 # sonarr
      - 9117:9117 # jackett
      - 7878:7878 # radarr
      - 9091:9091 # transmission
    volumes:
      - gluetun:/gluetun
    environment:
      - VPNSP=private internet access
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASS}
      - TZ=${TZ:-Europe/Amsterdam}
      - REGION=${REGION:-Netherlands,Belgium,Luxembourg,Denmark,Sweden,Finland,Norway,UK London,UK Manchester,UK Southampton}
    restart: always

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    depends_on:
      - gluetun
    network_mode: service:gluetun
    environment:
      - TZ=${TZ:-Europe/Amsterdam}
      - PUID=${PUID:-1000}
      - GUID=${GUID:-1000}
    volumes:
      - config_transmission:/config
      - /mnt/media/downloads/busy:/downloads
      - transmission_watch:/watch
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Europe/Amsterdam}
      - PUID=${PUID:-1000}
      - GUID=${GUID:-1000}
    volumes:
      - config_sonarr:/config 
      - /mnt/media/downloads/tv:/tv 
      - /mnt/media/downloads/busy:/downloads 
    network_mode: service:gluetun
    depends_on:
      - jackett
      - gluetun

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Europe/Amsterdam}
      - PUID=${PUID:-1000}
      - GUID=${GUID:-1000}
    volumes:
      - /mnt/media/downloads/busy:/downloads
      - config_jackett:/config
    network_mode: service:gluetun
    depends_on:
      - gluetun

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Europe/Amsterdam}
      - PUID=${PUID:-1000}
      - GUID=${GUID:-1000}
    volumes:
      - config_radarr:/config 
      - /mnt/media/downloads/movie:/movies 
      - /mnt/media/downloads/busy:/downloads
    network_mode: service:gluetun
    depends_on:
      - jackett
      - gluetun
```
