### ISSUE TITLE
Help: Conflicting ports on images (How to remap ports?)

### ISSUE THREAD

**Issue by lx30011** [qdm12/gluetun#343]
**Host OS** (approximate answer is fine too): Ubuntu 20.04.1 LTS

**Is this urgent?**: No

**What VPN provider are you using**: Private Internet Access

**What is the version of the program**

```
Running version latest built on 2021-01-04T13:46:01Z (commit bf6bab7)
```

**What's the problem** 🤔

I'm trying to route `jlesage/firefox` as well as `jlesage/jdownloader-2` through the gluetun service, but both images use port 5800 by default and as far as I can tell, the images provide no option to change the port through e. g. environment variables. Normally, I would just remap the ports in the respective ports sections in the docker compose file, but I don't know how to this with gluetun.

**What are you using to run your container?**: Docker Compose

Please also share your configuration file:

```yml
version: '3.9'

services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPNSP=private internet access
      - OPENVPN_USER=${GLUETUN_OPENVPN_USER}
      - OPENVPN_PASSWORD=${GLUETUN_OPENVPN_PASS}
      - REGION=DE Frankfurt
      - PORT_FORWARDING=on
      - PROTOCOL=udp
      - PIA_ENCRYPTION=strong
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      # HOST:CONTAINER
      # TCP if not specified
      # qBittorrent
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080

      # This doesn't work, just shows JDownloader on both ports

      # Firefox
      - 5800:5800
      # JDownloader
      - 5801:5800

      # I also tried using the `ports` section down at JDownloader to remap the port
      # "before" routing the connection through gluetun (and then using `5801:5801` for JDownloader here) 
      # but `network_mode` and `ports` can't be used at the same time

    volumes:
      - gluetun:/gluetun
    restart: unless-stopped

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent:/config
      - downloads:/downloads
    restart: unless-stopped

  firefox:
    container_name: firefox
    image: jlesage/firefox
    network_mode: service:gluetun
    shm_size: 2g
    environment:
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
      - TZ={TZ}
    volumes:
      - firefox:/config
      - downloads:/downloads
    restart: unless-stopped

  rclone:
    container_name: rclone
    image: rclone/rclone
    command: rcd --rc-web-gui --rc-addr :5572 --rc-user ${RCLONE_USER} --rc-pass ${RCLONE_PASS}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 5572:5572
    volumes:
      - rclone:/config/rclone
      - rclone:/data
      - downloads:/downloads
    restart: unless-stopped

  jdownloader:
    container_name: jdownloader
    image: jlesage/jdownloader-2
    network_mode: service:gluetun
    environment:
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
      - TZ={TZ}
    volumes:
      - jdownloader:/config
      - downloads:/output

volumes:
  gluetun:
  qbittorrent:
  downloads:
  firefox:
  rclone:
  jdownloader:
```

Thank you!
