### ISSUE TITLE
Bug: config parse error results in container restart loop

### ISSUE THREAD

**Issue by jnsn** [qdm12/gluetun#370]
**Host OS**: Ubuntu 20.04.2 LTS

**Is this urgent?**: No

**What VPN provider are you using**: Mullvad

**What are you using to run your container?**: Docker Compose

**What is the version of the program** (See the line at the top of your logs)

```
Running version latest built on 2021-02-06T18:34:44Z (commit b1f1f94)
```

**What's the problem** 🤔

Container fails to start and ends up in a restarting loop. Reverting back to v3.13.1 fixes the problem.

**Share your logs...**

...*careful to remove i.e. token information with PIA port forwarding*

```log
2021-02-07T09:49:31.031+0100    INFO    OpenVPN version: 2.4.10
2021-02-07T09:49:31.034+0100    INFO    Unbound version: 1.10.1
2021-02-07T09:49:31.035+0100    INFO    IPtables version: v1.8.4
panic: runtime error: index out of range [3] with length 3

goroutine 18 [running]:
github.com/qdm12/gluetun/internal/configuration.readCustomPort(0xbbc8e0, 0xc0000aa990, 0xc000026059, 0x3, 0xc00041ebbe, 0x3, 0x3, 0xc00041ebc4, 0xa, 0xa, ...)
        github.com/qdm12/gluetun/internal/configuration/provider.go:97 +0x3cc
github.com/qdm12/gluetun/internal/configuration.(*Provider).readMullvad(0xc00041fb50, 0xbbc8e0, 0xc0000aa990, 0xbba220, 0xc0000aa9c0, 0xbbb9e0, 0xc000094ea0, 0xbb8d00, 0xeb5280, 0x995201, ...)
        github.com/qdm12/gluetun/internal/configuration/mullvad.go:62 +0x3f4
github.com/qdm12/gluetun/internal/configuration.(*OpenVPN).read(0xc00041fb00, 0xbbc8e0, 0xc0000aa990, 0xbba220, 0xc0000aa9c0, 0xbbb9e0, 0xc000094ea0, 0xbb8d00, 0xeb5280, 0xf, ...)
        github.com/qdm12/gluetun/internal/configuration/openvpn.go:137 +0x81b
github.com/qdm12/gluetun/internal/configuration.(*Settings).Read(0xc00041fb00, 0xbbc8e0, 0xc0000aa990, 0xbb8d00, 0xeb5280, 0xbba220, 0xc0000aa9c0, 0x0, 0x0)
        github.com/qdm12/gluetun/internal/configuration/settings.go:56 +0x1f6
main._main(0xbb7ec0, 0xc000066000, 0xba33b0, 0x6, 0xba3ec8, 0x7, 0xba8580, 0x14, 0xc0001021c0, 0x1, ...)
        command-line-arguments/main.go:152 +0xe09
main.main.func1(0xc0001000c0, 0xbb7ec0, 0xc00017ea00, 0xba33b0, 0x6, 0xba3ec8, 0x7, 0xba8580, 0x14, 0xc0001021c0, ...)
        command-line-arguments/main.go:72 +0x12c
created by main.main
        command-line-arguments/main.go:71 +0x35d
```

**Compose config**

```yaml
container_name: dl-vpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    init: true
    environment:
      - VPNSP=mullvad
      - Country=XX
      - City=XX
      - ISP=XX
      - PORT=53
      - OPENVPN_USER=XX
      - PASSWORD=dummy
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - TZ=Europe/Brussels
      - FIREWALL_VPN_INPUT_PORTS=XX
      - OPENVPN_IPV6=on
    restart: always
    ports:
      - 8180:80/tcp
      - 5000:5000
      - 6881:6881/udp
```
