### ISSUE TITLE
Bug: IPv6 might leak with PIA and docker configured to enable IPv6

### ISSUE THREAD

**Issue by kubax** [qdm12/gluetun#425]
**Is this urgent?**: it might be...

**Host OS** (approximate answer is fine too): Arch Linux

**CPU arch** or **device name**: amd64

**What VPN provider are you using**: PIA

**What are you using to run your container?**: Docker Compose (Portainer)

**What is the version of the program**: 

```
gluetun:latest
```

**What's the problem** 🤔

In case of Docker is configured to use IPv6, "networkmode: bridge" leads to the container be able to use the Hosts IPv6 address, and bypass the OpenVPN (in case of PIA at least).

Changed my Docker-compose like so, to have only IPv4 in this container.

```yml
version: "3.7"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
    # command:
    volumes:
      - /yourpath:/gluetun
    secrets:
      - openvpn_user
      - openvpn_password
    environment:
      # More variables are available, see the readme table
      - VPNSP=private internet access
      # Timezone for accurate logs times
      - TZ=
    restart: always
    networks:
      - gluetun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

secrets:
  openvpn_user:
    file: ./openvpn_user
  openvpn_password:
    file: ./openvpn_password

networks:
  gluetun:
    enable_ipv6: false
```

I might also be missing something... i recently enabled IPv6 on my docker Host, and just started switching from combined vpn + service container, to gluetun... hoping in simplyfying my structures... (wich seems promising so far)
