### ISSUE TITLE
Help: PureVPN multi-container applications - Docker Compose help.

### ISSUE THREAD

**Issue by nodecentral** [qdm12/gluetun#458]
**Is this urgent?**: No

This issue likely falls outside of the scope of gluetun, but if it can help me (and by association others)  to get a multi-container set up up and running that leverages the gluetun VPN container as the transports conduit - then it can’t be a bad thing :-)

Reading through the repository and some of the open/closed issues, I’ve pulled the following together to try and create my own “PureVPN gluetun’ application set up, but whenever I try to run it, it returns the following error. 
````
Service 'deluge' uses the network stack of container 'purevpn-gluetun' which does not exist.
````
Here is my Docker compose yml 

````yml
version: "3.7"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: purevpn-gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8000:8000/tcp # Built-in HTTP control server
    # command:
    volumes:
      - /share/Container/Gluetun:/gluetun
    environment:
      # More variables are available, see the readme table
      - VPNSP=purevpn
      - REGION=North Holland
      - COUNTRY=Netherlands
      - SERVER_HOSTNAME=nl2-ovpn-udp.pointtoserver.com
      - OPENVPN_USER=purevpn123456
      - OPENVPN_PASSWORD=purevpnpassword 
      # Timezone for accurate logs times
      - TZ=Europe/London
    restart: always

  deluge:
    container_name: purevpn-deluge
    image: linuxserver/deluge
    network_mode: "container:purevpn-gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /share/Container/delugeLS/config:/config
      - /share/Container/delugeLS/downloads:/downloads
    restart: unless-stopped

  whoami:  # using whoami here, but could be any container
    container_name: purevpn-whoami
    image: containous/whoami # A container that exposes an API to show its IP address
    restart: unless-stopped
    network_mode: "container:purevpn-gluetun" 

````
