### ISSUE TITLE
Documentation: advanced port forwarding setup

### ISSUE THREAD

**Issue by ddelange** [qdm12/gluetun#464]
**Is this urgent?**: No

**Host OS** (approximate answer is fine too): Ubuntu Desktop 20.10

**CPU arch** or **device name**: aarch64

**What VPN provider are you using**: private internet access

**What is the version of the program**:

```
Running version latest built on 2021-05-19T17:58:32Z (commit a3751a7)
```

**What's the problem** 🤔

I've been struggling to host a docker container on the forwarded port:

- situation
  - gluetun successfully writes pia's forwarded port to the bind mounted volume
  - gluetun has `ports` statements disabled -- only want to use this VPN connection within this docker-compose and ideally not interfere with the rest of host's network
  - added container with `network_mode: "service:gluetun"`, running owncloud (LAMP stack) on 8080 ([not easy/recommended](https://central.owncloud.org/t/change-default-ports-for-owncloud-on-newest-appliance/15457/3) to change away from 8080) -- IP from this container corresponds to public VPN IP
- goal
  - i want to visit `http://public_vpn_ip:forwarded_port` in some browser outside my network, which should resolve to the owncloud container -- no HTTPS at all for now as it will be tricky to get letsencrypt to work for the DNS which is not accessible on port 80 as the DNS points to VPN IP
- dead ends
  - [cannot use](https://github.com/dperson/openvpn-client/issues/210#issuecomment-828267734) `ports` compose statement in combination with `network_mode: "service:gluetun"`
  - [`nginx-proxy`](https://github.com/nginx-proxy/nginx-proxy) does not work with gluetun networking setup, requires `ports` compose statement. also, it proxies exposed container port XXXX to 80, instead of proxying container port 80 to forwarded port XXXX
  - totally lost setting up [`traefik`](https://github.com/traefik/traefik), not sure if applicable and/or compatible with gluetun 
  - tried with explicitly defined `networks: gluetun-network` at bottom of compose file (so I could use the `ports` statement) and added to both services, but results in owncloud not being under the VPN IP anymore

any help reaching my owncloud container through the forwarded port would be greatly appreciated!

**What are you using to run your container?**: Docker Compose

```yml
version: "3.7"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    # ports:
    #   - 8888:8888/tcp # HTTP proxy
    #   - 8388:8388/tcp # Shadowsocks
    #   - 8388:8388/udp # Shadowsocks
    #   - 8000:8000/tcp # Built-in HTTP control server
    volumes:
      - ./storage/gluetun:/gluetun
      - ./storage/forwarded_port_dir:/tmp/forwarded_port_dir
    environment:
      - VPNSP=private internet access
      - PORT_FORWARDING=on
      - PORT_FORWARDING_STATUS_FILE=/tmp/forwarded_port_dir/forwarded_port
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - REGION=${REGION:-DE Berlin}
      # https://github.com/qdm12/gluetun/wiki/Environment-variables
      - DOT=off
    restart: always

  owncloud:
    image: owncloud/server:${OWNCLOUD_RELEASE_DOCKER_TAG:-10.6}
    network_mode: "service:gluetun"
    restart: always
    # could extract forwarded port from gluetun bind mount, export env var in host, and then another docker-compose up
    # but ports statement doesn't work with network_mode: "service:gluetun"
    # ports:
    #   - ${OWNCLOUD_HTTP_PORT}:8080
```

**Comment by qdm12** [comment]
## Host ports mapping

More of an FYI than a useful point;

You need to publish the ports on gluetun, as there is only one 'network host' which is gluetun. Containers you connect to gluetun use the network stack of gluetun. So technically your owncloud container has the same container IP address as gluetun. Therefore you need to have the ports in the gluetun service definition. **However** this seems to be irrelevant in your situation since you care about the VPN server side port forwarded, so no need to worry about that ports section.

## Reverse proxy

I would recommend you to try caddy v2 instead of nginx or traefik, it's really better having tried them all. You can use [`qmcgaw/caddy-scratch`](https://github.com/qdm12/caddy-scratch) if you want. You should use a Caddyfile to define your proxy rules, it should be easier-than-nginx to setup. And make Caddy connected to gluetun as you did for owncloud.

## Listen on the forwarded port

Adapt your Caddyfile such that Caddy listens on the forwarded port, e.g. `:5858`, and proxies to `127.0.0.1:8080` (your LAMP stack). The only problem is that you would need to update Caddy whenever that port forwarded port changes (see the [Extras](#Extras)) 

## HTTPS

- You can use https://caddyserver.com/docs/automatic-https#dns-challenge to get https LE certs without having port 80 or 443 accessible
- You can use [`qmcgaw/ddns-updater`](https://github.com/qdm12/ddns-updater) connected to the gluetun container to dynamically update your domain name whenever your VPN IP address changes

That way you should be able to access https://yourdomain.com:forwarded_port  😉 

Note that these may miss small things as I'm pulling this off from the top of my head, but feel free to add missing steps, I'll most likely add a page in the Wiki.

## Extras

### Auto-update the forwarded port in Caddy

Caddy has an HTTP API listening on port 2019 that you can enable (see the Caddyfile config options).
You could have program running in gluetun periodically fetching the forwarded port with the gluetun control http server and the patching the Caddy configuration through the Caddy API. If you managed to each all the steps, I can help code that for you if you want.

### Use subpaths to split to different services

You can make Caddy to use subpaths such as `/owncloud` and proxy to owncloud. That way you could split it to more services running in gluetun.

**Comment by ddelange** [comment]
Hi @qdm12, thanks a million for your thoughtful and structured response.

I will dive into Caddy ASAP and report back!

Also thanks for elaborating on HTTPS (and keeping me from giving up on security), sounds indeed like Caddy is the way to go for me 💪

**Comment by ddelange** [comment]
Hi again!

My progress:

- [x] DDNS
- [x] Update forwarded port in Caddyfile (`http_port`), push using Caddy API @ `http://localhost:2019/load`
  ```sh
  #!/usr/bin/env bash
  # auto_update_port.sh
  while true; do
    # upon gluetun startup, this file doesn't exist: skip updating
    current_port="$(cat /tmp/forwarded_port_dir/forwarded_port || echo '')"
    if grep -q "${current_port}" /caddydir/Caddyfile ; then
        :
    else
        echo "Updating Caddy"
        # update (no /g here because the port is only mentioned once)
        sed -ri "s/http_port [0-9]+/http_port ${current_port}/" /caddydir/Caddyfile
        # reload
        curl -X POST "http://localhost:2019/load" \
            -H "Content-Type: text/caddyfile" \
            --data-binary @/caddydir/Caddyfile
    fi
    sleep 10
  done
  ```
  ```yaml
  forwarded_port_bind_mount_listener:
    build:
      context: .
      dockerfile: bash-alpine.Dockerfile
    network_mode: "service:gluetun"
    volumes:
      - ./auto_update_port.sh:/auto_update_port.sh
      - ./storage/forwarded_port_dir:/tmp/forwarded_port_dir
      - ./caddydir:/caddydir
    command: ["bash", "/auto_update_port.sh"]
    restart: always
  ```
- [x] all containers specify `network_mode: "service:gluetun"`
- [ ] access http://yourdomain.com:forwarded_port
- [ ] https LE certs without having port 80 or 443 accessible
- [ ] access https://yourdomain.com:forwarded_port
- [ ] subpaths to split to different services

So making my way down the TODO list, I've reached a bit of a catch 22:

- With an owncloud (80) container and a Caddyfile
  ```
  {
      http_port 42424
      admin 127.0.0.1:2019
  }

  reverse_proxy 127.0.0.1:80
  ```
  - caddy starts and runs (with some tls warnings, ignoring for now)
  - owncloud startup (takes some time) errors '80 already in use'


- Switching to an [ocis](https://github.com/owncloud/ocis) (9250 by default) container and a Caddyfile
  ```
  {
      http_port 42424
      admin 127.0.0.1:2019
  }

  reverse_proxy 127.0.0.1:9250
  ```
  - either ocis, or caddy starts correctly, the other will exit (depending who did the bind mount first I guess)
  - caddy is the more verbose of the two: `run: loading initial config: loading new config: http app module: start: tcp: listening on :9250: listen tcp :9250: bind: address already in use`

Trying to keep compose as basic as possible for testing purposes:
```yaml
services:
  # gluetun unchanged

  # ddns added

  # forwarded_port_bind_mount_listener added, updates/reloads caddy when needed

  caddy:
    image: qmcgaw/caddy-scratch
    container_name: caddy
    volumes:
     - ./caddydir:/caddydir
    network_mode: "service:gluetun"
    restart: always

  ocis:
    image: "owncloud/ocis:${OCIS_DOCKER_TAG:-latest}"
    container_name: ocis
    network_mode: "service:gluetun"
    environment:
      - OCIS_RUNTIME_PORT=9250
```

My search for similar issues left me stranded, [this post](https://www.reddit.com/r/jellyfin/comments/krcl23/trouble_with_caddy_reverse_proxy/gi9bjre?utm_source=share&utm_medium=web2x&context=3) is the closest I got. Any more wisdom you can spare? :)
