### ISSUE TITLE
Help: Correct Port to specify for Qbittorrent to route via Gluetun ?

### ISSUE THREAD

**Issue by nodecentral** [qdm12/gluetun#472]
**Is this urgent?**: No

**Host OS** (approximate answer is fine too): Gluetun Docker
**CPU arch** or **device name**: amd64
**What VPN provider are you using**: PureVPN
**What is the version of the program** (See the line at the top of your logs) v3.16.0
**What's the problem** 🤔

I have the following in my Docker Compose, and while I can populate qbittorrent from other sources, when it searches for trackers, it doesn’t find any or download anything ?  Do i need a specific port to be set  ?
````
version: "2"
services:
  gluetun:
    image: qmcgaw/gluetun:v3.16.0
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8000:8000/tcp # Built-in HTTP Control Server
      - 8112:8112/tcp # qbittorrent Admin interface
      - 89:80/tcp # whoami health api
      - 7878:7878/tcp # radarr access 
      - 9117:9117/tcp # jackett
      - 8989:8989/tcp # sonarr
      - 8686:8686/tcp # lindarr
      - 3000:3000/tcp # firefox
      - 8083:8083/tcp # lindarr
      - 6881:6881/tcp
      - 6881:6881/udp
    # command:
    volumes:
      - /share/Container/Gluetun:/gluetun
    environment:
      # More variables are available, see the readme table
      - VPNSP=purevpn
      - REGION=North Holland
      - COUNTRY=Netherlands
      - SERVER_HOSTNAME=nl2-ovpn-udp.pointtoserver.com,nl2-ovpn-tcp.pointtoserver.com,vlap-th2-ovpn-udp.pointtoserver.com
      - OPENVPN_USER=purevpn
      - OPENVPN_PASSWORD=Mypassword
      - PUBLICIP_FILE=/share/Container/Gluetun/ip
      # OPENVPN_CIPHER=aes-256-gcm
      - OPENVPN_VERBOSITY=3
      # Timezone for accurate logs times
      - TZ=Europe/London
    restart: always

  qbittorrent:
   image: ghcr.io/linuxserver/qbittorrent
   container_name: qbittorrent
   environment:
     - PUID=1005
     - PGID=1000
     - TZ=Europe/London
     - WEBUI_PORT=8083
   volumes:
      - /share/Container/qbittorrent/config:/config
      - /share/Container/Gluetun/downloads:/downloads
   network_mode: "service:gluetun"
   depends_on:
     - gluetun
   restart: unless-stopped
````

![6934DE55-CC9D-43E9-9DA1-DBB9183AB2CC](https://user-images.githubusercontent.com/4349292/120066161-27679480-c06d-11eb-9e06-fb04331b98a7.jpeg)
