### ISSUE TITLE
Help: Connect another Docker container to Gluetun container

### ISSUE THREAD

**Issue by nodecentral** [qdm12/gluetun#476]
**Is this urgent?**: No
**Host OS** (approximate answer is fine too): QNAP Debian 
**CPU arch** or **device name**: amd64
**What VPN provider are you using** PUREVPN
**What is the version of the program** This is a Docker question more that an Gluetun one
**What's the problem** 🤔

I’m trying to connect another container (jackett) to my existing Gluetun one (which I finally have working 😃, using this guide on the wiki, https://github.com/qdm12/gluetun/wiki/Connect-to-gluetun but it give me an error.
````
**Container in another docker-compose.yml**
Add network_mode: "container:gluetun" to your docker-compose.yml, provided Gluetun is already running.
````
**What are you using to run your container?**: Docker Compose

Here’s the compose configuration file:

```yml
version: "3"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PGID=1005
      - PUID=1000
      - TZ=Europe/London
    volumes:
      - /share/Container/jackett/config:/config
    network_mode: "container:gluetun"
    depends_on:
      - gluetun
    restart: always
```
Here’s the error message
````
The Compose YAML is invalid

Service 'jackett' depends on service 'gluetun' which is undefined.
`````
