### ISSUE TITLE
Add new server as maintainer ends in ERROR

### ISSUE THREAD

**Issue by DevZiegler** [qdm12/gluetun#566]
**Is this urgent?**: No

**Host OS** (approximate answer is fine too): Armbian

**CPU arch** or **device name**: armv7

**What VPN provider are you using**: PureVPN

**What are you using to run your container?**: Docker Compose

**What is the version of the program** (See the line at the top of your logs)

```
Running version latest built on 2020-03-13T01:30:06Z (commit d0f678c)
```

**What's the problem** 🤔

Adding new servers ends in an error.
```
version: '3.7'

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
    # command:
    volumes:
      - ./gluetun:/gluetun
    environment:
      # More variables are available, see the readme table
      - OPENVPN_USER=...
      - OPENVPN_PASSWORD=...
      - VPNSP=purevpn
      # Timezone for accurate logs times
      - TZ=Europe/Berlin
      # Regions
      #- COUNTRY=Spain <-- New location
    restart: always
```

New servers
```
{
  "country": "Spain",
  "region": "Madrid",
  "city": "Madrid",
  "hostname": "es2-ovpn-tcp.pointtoserver.com",
  "tcp": true,
  "udp": false,
  "ips": [
    "217.138.218.210"
  ]
},
{
  "country": "Spain",
  "region": "Madrid",
  "city": "Madrid",
  "hostname": "es2-ovpn-udp.pointtoserver.com",
  "tcp": false,
  "udp": true,
  "ips": [
    "217.138.218.212"
  ]
}
```

update command
```
docker run -it --rm -v /my/path/gluetun:/gluetun qmcgaw/gluetun update -purevpn -maintainer
```  

**Share your logs... (careful to remove in example tokens)**

```log

2021/../.. ..:..:.. INFO merging by most recent 11007 hardcoded servers and 11009 servers read from /gluetun/servers.json
2021/../.. ..:..:.. INFO updating PureVPN servers...
2021/../.. ..:..:.. WARN PureVPN: reached the maximum number of consecutive failures: 2 failed attempts resolving vlap-th2-ovpn-tcp.pointtoserver.com: lookup vlap-th2-ovpn-tcp.pointtoserver.com on 192.168.178.1:53: no such host
2021/../.. ..:..:.. WARN PureVPN: reached the maximum number of consecutive failures: 2 failed attempts resolving vlus-pa2-ovpn-udp.pointtoserver.com: lookup vlus-pa2-ovpn-udp.pointtoserver.com on 192.168.178.1:53: no such host
2021/../.. ..:..:.. WARN PureVPN: reached the maximum number of consecutive failures: 2 failed attempts resolving vlap-vn2-ovpn-udp.pointtoserver.com: lookup vlap-vn2-ovpn-udp.pointtoserver.com on 192.168.178.1:53: no such host
2021/../.. ..:..:.. WARN PureVPN: reached the maximum number of consecutive failures: 2 failed attempts resolving ussa2-ovpn-tcp.pointtoserver.com: lookup ussa2-ovpn-tcp.pointtoserver.com on 192.168.178.1:53: no such host
2021/../.. ..:..:.. WARN PureVPN: reached the maximum number of consecutive failures: 2 failed attempts resolving usphx2-ovpn-tcp.pointtoserver.com: lookup usphx2-ovpn-tcp.pointtoserver.com on 192.168.178.1:53: no such host
2021/../.. ..:..:.. WARN PureVPN: reached the maximum number of consecutive failures: 2 failed attempts resolving ussf2-ovpn-tcp.pointtoserver.com: lookup ussf2-ovpn-tcp.pointtoserver.com on 192.168.178.1:53: no such host
2021/../.. ..:..:.. WARN PureVPN: reached the maximum number of consecutive failures: 2 failed attempts resolving gr2-ovpn.pointtoserver.com: lookup gr2-ovpn.pointtoserver.com on 192.168.178.1:53: no such host
2021/../.. ..:..:.. WARN PureVPN: reached the maximum number of consecutive failures: 2 failed attempts resolving usut2-ovpn-tcp.pointtoserver.com: lookup usut2-ovpn-tcp.pointtoserver.com on 192.168.178.1:53: no such host
2021/../.. ..:..:.. WARN PureVPN: reached the maximum number of consecutive failures: 2 failed attempts resolving it2-ovpn-udp.pointtoserver.com: lookup it2-ovpn-udp.pointtoserver.com on 192.168.178.1:53: no such host
2021/../.. ..:..:.. ERROR cannot write updated information to file: open ./internal/constants/servers.json: no such file or directory
2021/../.. ..:..:.. INFO Shutdown successful

```
