### ISSUE TITLE
Feature request: Support IPv6 tunnelling over Wireguard

### ISSUE THREAD

**Issue by stoli412** [qdm12/gluetun#594]
As discussed in #134 ([here](https://github.com/qdm12/gluetun/issues/134?_pjax=%23js-repo-pjax-container#issuecomment-907426446)) it would be great if IPv6 tunnelling over Wireguard could be enabled for providers who support it (eg, Mullvad).

I've done some testing with the existing image and as expected IPv6 routing does not work. In my docker-compose file, I've tried:

1. Replacing my Mullvad IPv4 address block with the IPv6 block
2. Keeping the existing IPv4 block and adding an additional `WIREGUARD_ADDRESS` line with the IPv6 block

In both cases the container fails to complete startup because it can't resolve IP addresses and never connects to Mullvad's servers. (Logs: [_gluetun-wireguard-ipv6test_gluetun-wireguard_1_logs.txt](https://github.com/qdm12/gluetun/files/7070508/_gluetun-wireguard-ipv6test_gluetun-wireguard_1_logs.txt))

My gluetun docker-compose looks like this:

```
version: "3.7"
services:
  gluetun-wireguard:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8800:8000/tcp # Built-in HTTP control server
    # command:
    volumes:
      - /mnt/data/docker-configs/gluetun-ipv6test:/gluetun
    environment:
      # More variables are available, see the Wiki table
      - VPNSP=mullvad
      - VPN_TYPE=wireguard
      - PUBLICIP_FILE=/tmp/gluetun/ip
      # Timezone for accurate logs times
      - TZ=Europe/London
      - DOT_IPV6=ON
      - WIREGUARD_PRIVATE_KEY=[redacted]
      - WIREGUARD_ADDRESS=xxx.xxx.xxx.xxx/32
      - WIREGUARD_ADDRESS=xxxx:xxxx:xxxx:xxxx::x:xxxx/128 # Tried with IPv6 on its own and with IPv4 above
      - WIREGUARD_PORT=51820
      - CITY=Manchester
      - FIREWALL_VPN_INPUT_PORTS=54810,54953,55126,55811,56115
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - PUID=1001
      - PGID=1001
    restart: always
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
networks:
    default:
        driver: bridge
        enable_ipv6: true
        driver_opts:
            com.docker.network.bridge.enable_icc: "true"
            com.docker.network.bridge.enable_ip_masquerade: "true"
            com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
            com.docker.network.driver.mtu: "1500"
        ipam:
            driver: default
            config:
                - subnet: 172.16.5.0/24
                  gateway: 172.16.5.1
                - subnet: fd5f:c26e:7746:f664::/64
                  gateway: fd5f:c26e:7746:f664::1
```
