### ISSUE TITLE
ERROR openvpn: --up script fails with '/etc/openvpn/update-resolv-conf': No such file or directory (errno=2)Bug: 

### ISSUE THREAD

**Issue by pvanryn** [qdm12/gluetun#655]
### Is this urgent?

No

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2021-09-30T15:34:25Z (commit 5ad4136)

### What's the problem 🤔

Container fails health check, restarts. From the log;` ERROR openvpn: --up script fails with '/etc/openvpn/update-resolv-conf': No such file or directory (errno=2)Bug: `

If I revert to v3.21.1, everything works ok.

### Share your logs

```log
| Running version latest built on 2021-09-30T15:34:25Z (commit 5ad4136)
gluetun    | 
gluetun    | 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
gluetun    | 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
gluetun    | ✨ New feature? https://github.com/qdm12/gluetun/issues/new
gluetun    | ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
gluetun    | 💻 Email? quentin.mcgaw@gmail.com
gluetun    | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
gluetun    | 2021/10/04 08:55:29 INFO storage: merging by most recent 11186 hardcoded servers and 11186 servers read from /gluetun/servers.json
gluetun    | 2021/10/04 08:55:29 INFO Alpine version: 3.14.2
gluetun    | 2021/10/04 08:55:29 INFO OpenVPN 2.4 version: 2.4.11
gluetun    | 2021/10/04 08:55:29 INFO OpenVPN 2.5 version: 2.5.2
gluetun    | 2021/10/04 08:55:29 INFO Unbound version: 1.13.2
gluetun    | 2021/10/04 08:55:29 INFO IPtables version: v1.8.7
gluetun    | 2021/10/04 08:55:29 INFO Settings summary below:
gluetun    | |--VPN:
gluetun    |    |--Type: openvpn
gluetun    |    |--OpenVPN:
gluetun    |       |--Version: 2.5
gluetun    |       |--Verbosity level: 1
gluetun    |       |--Network interface: tun0
gluetun    |       |--Run as root: enabled
gluetun    |       |--Configuration file: /gluetun/custom.conf
gluetun    |    |--Custom settings:
gluetun    |       |--OpenVPN selection:
gluetun    |          |--Custom configuration file: /gluetun/custom.conf
gluetun    |          |--Protocol: udp
gluetun    | |--DNS:
gluetun    |    |--Plaintext address: 1.1.1.1
gluetun    |    |--DNS over TLS:
gluetun    |       |--Unbound:
gluetun    |           |--DNS over TLS providers:
gluetun    |               |--Cloudflare
gluetun    |           |--Listening port: 53
gluetun    |           |--Access control:
gluetun    |               |--Allowed:
gluetun    |                   |--0.0.0.0/0
gluetun    |                   |--::/0
gluetun    |           |--Caching: enabled
gluetun    |           |--IPv4 resolution: enabled
gluetun    |           |--IPv6 resolution: disabled
gluetun    |           |--Verbosity level: 1/5
gluetun    |           |--Verbosity details level: 1/4
gluetun    |           |--Validation log level: 1/2
gluetun    |           |--Username: 
gluetun    |       |--Blacklist:
gluetun    |          |--Blocked categories: 
gluetun    |          |--Additional IP networks blocked: 13
gluetun    |       |--Update: every 24h0m0s
gluetun    | |--Firewall:
gluetun    |    |--Outbound subnets: 192.168.50.0/24
gluetun    | |--Log:
gluetun    |    |--Level: INFO
gluetun    | |--System:
gluetun    |    |--Process user ID: 1000
gluetun    |    |--Process group ID: 1000
gluetun    |    |--Timezone: america/denver
gluetun    | |--HTTP proxy:
gluetun    |    |--Port: 8888
gluetun    | |--Health:
gluetun    |    |--Server address: 127.0.0.1:9999
gluetun    |    |--Address to ping: github.com
gluetun    |    |--VPN:
gluetun    |       |--Initial duration: 6s
gluetun    |       |--Addition duration: 5s
gluetun    | |--HTTP control server:
gluetun    |    |--Listening port: 8000
gluetun    |    |--Logging: enabled
gluetun    | |--Public IP getter:
gluetun    |    |--Fetch period: 12h0m0s
gluetun    |    |--IP file: /tmp/gluetun/ip
gluetun    | |--Github version information: enabled
gluetun    | 2021/10/04 08:55:29 INFO routing: default route found: interface eth0, gateway 172.17.0.1
gluetun    | 2021/10/04 08:55:29 INFO routing: local ethernet link found: eth0
gluetun    | 2021/10/04 08:55:29 INFO routing: local ipnet found: 172.17.0.0/16
gluetun    | 2021/10/04 08:55:29 INFO routing: default route found: interface eth0, gateway 172.17.0.1
gluetun    | 2021/10/04 08:55:29 INFO routing: adding route for 0.0.0.0/0
gluetun    | 2021/10/04 08:55:29 INFO firewall: firewall disabled, only updating allowed subnets internal list
gluetun    | 2021/10/04 08:55:29 INFO routing: default route found: interface eth0, gateway 172.17.0.1
gluetun    | 2021/10/04 08:55:29 INFO routing: adding route for 192.168.50.0/24
gluetun    | 2021/10/04 08:55:29 INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
gluetun    | 2021/10/04 08:55:29 INFO firewall: enabling...
gluetun    | 2021/10/04 08:55:30 INFO firewall: enabled successfully
gluetun    | 2021/10/04 08:55:30 INFO dns over tls: using plaintext DNS at address 1.1.1.1
gluetun    | 2021/10/04 08:55:30 INFO healthcheck: listening on 127.0.0.1:9999
gluetun    | 2021/10/04 08:55:30 INFO http proxy: listening on :8888
gluetun    | 2021/10/04 08:55:30 INFO http server: listening on :8000
gluetun    | 2021/10/04 08:55:30 INFO firewall: setting VPN connection through firewall...
gluetun    | 2021/10/04 08:55:30 ERROR openvpn: --up script fails with '/etc/openvpn/update-resolv-conf': No such file or directory (errno=2)
gluetun    | 2021/10/04 08:55:30 ERROR openvpn: Please correct this error.
gluetun    | 2021/10/04 08:55:30 INFO openvpn: Use --help for more information.
gluetun    | 2021/10/04 08:55:30 ERROR vpn: exit status 1
gluetun    | 2021/10/04 08:55:30 INFO vpn: retrying in 15s
gluetun    | 2021/10/04 08:55:36 INFO healthcheck: program has been unhealthy for 6s: restarting VPN
gluetun    | 2021/10/04 08:55:45 INFO firewall: setting VPN connection through firewall...
gluetun    | 2021/10/04 08:55:45 ERROR openvpn: --up script fails with '/etc/openvpn/update-resolv-conf': No such file or directory (errno=2)
gluetun    | 2021/10/04 08:55:45 ERROR openvpn: Please correct this error.
gluetun    | 2021/10/04 08:55:45 INFO openvpn: Use --help for more information.
gluetun    | 2021/10/04 08:55:45 ERROR vpn: exit status 1
gluetun    | 2021/10/04 08:55:45 INFO vpn: retrying in 30s
```

### Share your configuration

```yml
version: '3.7'
services:
   protonvpn:
     image: qmcgaw/gluetun
     container_name: protonvpn
     cap_add:
       - NET_ADMIN
     network_mode: bridge
     ports:
       - 8082:8082 # Searx Port
       - 8003:8000 # HTTP Control Server
       - 8888:8888/tcp # HTTP Proxy
     volumes:
       - ~/Dockers/protonvpn:/gluetun
       - ~/Dockers/protonvpn/current.udp.ovpn:/gluetun/custom.conf
     environment:
       - VPNSP=protonvpn
       - OPENVPN_USER=IKEv2User
       - OPENVPN_PASSWORD=IKEv2password
       - REGION=

       - COUNTRY=
       - CITY=
       - SERVER_NAME=
       - SERVER_HOSTNAME=209.95.56.120
       - PORT=1194
       - PROTOCOL=udp
       - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
       - OPENVPN_VERBOSITY=1
       - TZ=America/Denver

##########################################
#########  DNS Over TLS  #################
##########################################
       - DOT=on
       - DOT_PROVIDERS=cloudflare
       - DOT_CACHING=ON
       - DOT_IPV6=off
       - DOT_VERBOSITY=1
       - DOT_VERBOSITY_DETAILS=1
       - DOT_VALIDATION_LOGLEVEL=1
       - DNS_UPDATE_PERIOD=24H
       - BLOCK_MALICIOUS=off
       - BLOCK_SURVEILLANCE=off
       - BLOCK_ADS=off
       - UNBLOCK=
       - DNS_PLAINTEXT_ADDRESS=1.1.1.1
       - DNS_KEEP_NAMESERVER=off
###########################################
#########  Firewall  ######################
###########################################
       - FIREWALL=on
       - FIREWALL_OUTBOUND_SUBNETS=192.168.50.0/24
###########################################
#########  Shadowsocks  ###################
###########################################
       - SHADOWSOCKS=off
       - SHADOWSOCKS_PORT=8388
       - SHADOWSOCKS_LOG=on
       - SHADOWSOCKS_PASSWORD=
       - SHADOWSOCKS_METHOD=
############################################
#########  HTTP Proxy  ######################
############################################
       - HTTPPROXY=on
       - HTTPPROXY_USER=
       - HTTPPROXY_PASSWORD=
       - HTTPPROXY_STEALTH=off
```
