### ISSUE TITLE
Bug: Container will not start "ERROR default route not found: in 0 route(s)" 

### ISSUE THREAD

**Issue by Joeharrison94** [qdm12/gluetun#708]
### Host OS

Ubuntu Server 20.04

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2021-11-08T22:45:48.907Z (commit c07a0b0)

### What's the problem 🤔

Whenever I try to start the container it just states that the default route was not found and no more information is provided about this, please can someone tell me if this is expected? I only want to route some containers through this for internet access.

I have checked the config and the access credentials which are all fine to my knowledge.

Also a little side question, how would you map the ports of containers that use the same ports as gluetun i.e. yacht on port 8000 or if 2 containers use the same backend port like sab on 8080 and dozzle on 8080 for example?

### Share your logs

```log
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================

Running version latest built on 2021-11-08T22:45:48.907Z (commit c07a0b0)

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2021/11/11 08:53:44 INFO storage: merging by most recent 11104 hardcoded servers and 11104 servers read from /gluetun/servers.json
2021/11/11 08:53:44 INFO Alpine version: 3.14.2
2021/11/11 08:53:44 INFO OpenVPN 2.4 version: 2.4.11
2021/11/11 08:53:44 INFO OpenVPN 2.5 version: 2.5.2
2021/11/11 08:53:44 INFO Unbound version: 1.13.2
2021/11/11 08:53:44 INFO IPtables version: v1.8.7
2021/11/11 08:53:44 INFO Settings summary below:
|--VPN:
   |--Type: openvpn
   |--OpenVPN:
      |--Version: 2.5
      |--Verbosity level: 1
      |--Network interface: tun0
      |--Run as root: enabled
   |--Nordvpn settings:
      |--OpenVPN selection:
         |--Protocol: udp
|--DNS:
   |--Plaintext address: 1.1.1.1
   |--DNS over TLS:
      |--Unbound:
          |--DNS over TLS providers:
              |--Cloudflare
          |--Listening port: 53
          |--Access control:
              |--Allowed:
                  |--0.0.0.0/0
                  |--::/0
          |--Caching: enabled
          |--IPv4 resolution: enabled
          |--IPv6 resolution: disabled
          |--Verbosity level: 1/5
          |--Verbosity details level: 0/4
          |--Validation log level: 0/2
          |--Username:
      |--Blacklist:
         |--Blocked categories: malicious
         |--Additional IP networks blocked: 13
      |--Update: every 24h0m0s
|--Firewall:
|--Log:
   |--Level: INFO
|--System:
   |--Process user ID: 1000
   |--Process group ID: 2000
   |--Timezone: europe/london
|--HTTP proxy:
   |--Port: 8888
|--Shadowsocks server:
   |--Listening address: :8388
   |--Cipher: chacha20-ietf-poly1305
|--Health:
   |--Server address: 127.0.0.1:9999
   |--Address to ping: github.com
   |--VPN:
      |--Initial duration: 6s
      |--Addition duration: 5s
|--HTTP control server:
   |--Listening port: 8000
   |--Logging: enabled
|--Public IP getter:
   |--Fetch period: 12h0m0s
   |--IP file: /tmp/gluetun/ip
|--Github version information: enabled
2021/11/11 08:53:44 ERROR default route not found: in 0 route(s)
2021/11/11 08:53:44 INFO Shutdown successful
```

### Share your configuration

```yml
secrets:
  NORD_PASSWORD:
    file: $SECRETSDIR/NORD_PASSWORD
  NORD_USER:
    file: $SECRETSDIR/NORD_USER
  NORD_REGION:
    file: $SECRETSDIR/NORD_REGION
  SHADOW_PASS:
    file: $SECRETSDIR/SHADOW_PASS

services:

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
      - 8989:8989     # sonarr
    volumes:
      - $DOCKERLOCALDIR/gluetun/data:/gluetun
      - $DOCKERLOCALDIR/gluetun/port_forward:/tmp/gluetun/forwarded_port
    environment:
      - VPNSP=nordvpn
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - OPENVPN_USER_SECRETFILE=/run/secrets/NORD_USER
      - OPENVPN_PASSWORD_SECRETFILE=/run/secrets/NORD_PASSWORD
      - REGION_SECRETFILE=/run/secrets/NORD_REGION
      - PORT_FORWARDING=on
      - HTTPPROXY=on
      - SHADOWSOCKS=on
      - SHADOWSOCKS_PASSWORD_SECRETFILE=/run/secrets/SHADOW_PASS
    secrets:
      - NORD_USER
      - NORD_PASSWORD
      - NORD_REGION
      - SHADOW_PASS
    restart: unless-stopped
```
