### ISSUE TITLE
Bug: mtu negotiated seems wrong 

### ISSUE THREAD

**Issue by dsm1212** [qdm12/gluetun#710]
### Is this urgent?

No

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

Portainer

### What is the version of Gluetun

Top of log is always truncated, but I'm running latest docker as of 11/12/21

### What's the problem 🤔

If I use defaults an MTU of 1500 is negotiated and set on the port. If enter the container I cannot push a 1500 byte frame through the port. The largest unfragmented thing I can get out is 1498. So I force it to 1498 from the command line. I use these command line settings after running some tests to tune by the way (debian buster):

OPENVPN_FLAGS=--fast-io --sndbuf 512000 --rcvbuf 512000 --txqueuelen 2000 --tun-mtu 1498

### Share your logs

```log
2021/11/12 08:40:31 WARN openvpn: 'link-mtu' is used inconsistently, local='link-mtu 1567', remote='link-mtu 1554',
2021/11/12 08:40:31 WARN openvpn: 'tun-mtu' is used inconsistently, local='tun-mtu 1498', remote='tun-mtu 1500',
2021/11/12 08:40:31 WARN openvpn: 'keysize' is used inconsistently, local='keysize 256', remote='keysize 128',
2021/11/12 08:40:31 WARN openvpn: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo',
```

### Share your configuration

```yml
gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    network_mode: lsio
    cap_add:
      - NET_ADMIN
    ports:
    volumes:
      - /apps/gluetun:/gluetun
    environment:
      - VPNSP=private internet access
      - OPENVPN_USER=xxxx
      - OPENVPN_PASSWORD=xxxx
      - OPENVPN_FLAGS=--fast-io --sndbuf 512000 --rcvbuf 512000 --txqueuelen 2000 --tun-mtu 1498
      - REGION=CA Montreal
      - PORT_FORWARDING=on
      - PORT_FORWARDING_STATUS_FILE=/gluetun/forwarded_port
      - TZ=America/New_York
    restart: unless-stopped
```
