### ISSUE TITLE
Bug: Port Forwarding on CyberGhost

### ISSUE THREAD

**Issue by claussma** [qdm12/gluetun#732]
### Is this urgent?

No

### CPU arch

x86_64

### VPN service provider

Cyberghost

### What are you using to run the container

docker-compose

### What is the version of Gluetun

v3.26.0 built on 2021-11-27T12:16:34.703Z (commit b9a9319)

### What's the problem 🤔

Hi,

i can't start port forwards when i want to connect to CyberGhost. I have enabled the option in the docker-compose.yml file, however the option is not recognized. If I change the provider (e.g. VPNSP=private internet access) everything starts as expected.

What can I do?

Thx

### Share your logs

```log
dl_vpn     | ========================================
dl_vpn     | 
dl_vpn     | Running version v3.26.0 built on 2021-11-27T12:16:34.703Z (commit b9a9319)
dl_vpn     | 
dl_vpn     | 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
dl_vpn     | 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
dl_vpn     | ✨ New feature? https://github.com/qdm12/gluetun/issues/new
dl_vpn     | ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
dl_vpn     | 💻 Email? quentin.mcgaw@gmail.com
dl_vpn     | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
dl_vpn     | 2021/12/02 11:08:36 INFO storage: merging by most recent 11120 hardcoded servers and 11120 servers read from /gluetun/servers.json
dl_vpn     | 2021/12/02 11:08:36 INFO Alpine version: 3.14.3
dl_vpn     | 2021/12/02 11:08:36 INFO OpenVPN 2.4 version: 2.4.11
dl_vpn     | 2021/12/02 11:08:36 INFO OpenVPN 2.5 version: 2.5.2
dl_vpn     | 2021/12/02 11:08:36 INFO Unbound version: 1.13.2
dl_vpn     | 2021/12/02 11:08:36 INFO IPtables version: v1.8.7
dl_vpn     | 2021/12/02 11:08:36 INFO Settings summary below:
dl_vpn     | |--VPN:
dl_vpn     |    |--Type: openvpn
dl_vpn     |    |--OpenVPN:
dl_vpn     |       |--Version: 2.5
dl_vpn     |       |--Verbosity level: 1
dl_vpn     |       |--Network interface: tun0
dl_vpn     |       |--Run as root: enabled
dl_vpn     |       |--Client key is set
dl_vpn     |       |--Client certificate is set
dl_vpn     |    |--Cyberghost settings:
dl_vpn     |       |--Countries: canada, netherlands
dl_vpn     |       |--OpenVPN selection:
dl_vpn     |          |--Protocol: udp
dl_vpn     | |--DNS:
```

### Share your configuration

```yml
version: "3"
services:
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: dl_vpn
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - ./gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPNSP=cyberghost
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PWD}
      - COUNTRY=Canada,Netherlands
      - HTTPPROXY=on
      - HTTPPROXY_LOG=off
      - HTTPPROXY_PORT=8888
      - FIREWALL=on
      - PUBLICIP_FILE=/gluetun/ip
      - PORT_FORWARDING=on
      - PORT_FORWARDING_STATUS_FILE=/gluetun/forwarded_port
```
