### ISSUE TITLE
iptables errors after container update

### ISSUE THREAD

**Issue by shaftspanner** [qdm12/gluetun#770]
I've been happily running gluetun for about 6 months, forwarding Jackett and transmission containers through it using my NordVPN account as a VPN provider.  Kudos to qdm12, it's been by far the easiest VPN proxy I've found to work with.  However shortly before Christmas, it stopped working and I've finally had a chance to look at what's going on.

gluetun wasn't connecting to the VPN and I figured out that something's changed so it no longer likes special characters within my password - not a problem, password changed and the new one has no special characters, but it then threw up another error message.

To cut a long story short, I went back to basics, copied and pasted the example docker-compose, replaced the username/password and it connects i.e. this config works for me:

```
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPNSP=nordvpn
      - OPENVPN_USER={myemail@address}
      - OPENVPN_PASSWORD={my_NordVPN_Password}
      - REGION=Romania 
```
However, as soon as I add a port mapping e.g.

```
    ports:
      - 9091:9091     # Transmission
```
I get the error message:

```
ERROR: for htpc_gluetun_1  Cannot start service gluetun: driver failed programming external connectivity on endpoint htpc_gluetun_1 (a696d71a4d5657d3f6f8e9bd78fbb48a3a3db4f9a432b20a98aa6e8a4e0bc77a):  (iptables failed: iptables --wait -t filter -A DOCKER ! -i br-0879badbc278 -o br-0879badbc278 -p tcp -d 172.21.0.2 --dport 9091 -j ACCEPT: iptables: No chain/target/match by that name.
 (exit status 1))
```
Note that nothing else is running on 9091, and my corresponding transmission service (in the same docker-compose file doesn't have any port mappings and does include

`    network_mode: "service:gluetun"`
I don't think I've changed anything between the service working and the service not working other than probably pulling the latest version of gluetun. And it doesn't seem to matter whether I'm trying to open a port for transmission, jackett or the internal http proxy, I get the same sort of error message.
