### ISSUE TITLE
Bug: Container fails to start with firewall vpn input port out of range when its not

### ISSUE THREAD

**Issue by arpitgupta** [qdm12/gluetun#773]
### Is this urgent?

Yes

### Host OS

Synology

### VPN service provider

Mullvad

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-01-06T11:44:16.796Z (commit 7d824a5)

### What's the problem 🤔

container fails to start

### Share your logs

```log
/01/06 07:57:58 ERROR cannot read from source *env.Reader: environment variable FIREWALL_VPN_INPUT_PORTS: port value is not valid: 
must be between 1 and 65535: 54863
2022/01/06 07:57:58 INFO Shutdown successful
```

### Share your configuration

```yml
mvd_vpn:
    container_name: mvd_vpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      TZ: 'America/Los_Angeles'
      VPNSP: 'mullvad'
      VPN_TYPE: 'wireguard'
      CITY: 'Gothenburg'
      OWNED: 'yes'
      FIREWALL_VPN_INPUT_PORTS: 54863
      FIREWALL_OUTBOUND_SUBNETS: '192.168.1.0/24'
      FIREWALL_DEBUG: 'off'
      LOG_LEVEL: 'info'
      FIREWALL: 'on'
```
```
