### ISSUE TITLE
Bug: Not starting with custom openvpn config (VPN provider name is not valid: openvpn)

### ISSUE THREAD

**Issue by Fietspomp86** [qdm12/gluetun#777]
### Host OS

Debian

### CPU arch

x86_64

### VPN service provider

Custom

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-01-06T19:20:18.202Z (commit ae074df)

### What's the problem 🤔

Not starting with latest version and custom openvpn config.
Already tried with different strings on docker-compose.yaml, like removing the "VPN_TYPE=openvpn" completely.

### Share your logs
Logs when using different options in docker-compose.yaml.
Even when completely omitting - VPNSP=openvpn and - VPN_TYPE=openvpn it fails.
```log
With VPNSP=openvpn:
gluetun              | 2022/01/07 09:31:08 INFO storage: creating /gluetun/servers.json with 11120 hardcoded servers
gluetun              | 2022/01/07 09:19:28 ERROR failed validating VPN settings: provider settings validation failed: server selection settings validation failed: VPN provider name is not valid: openvpn
gluetun              | 2022/01/07 09:19:28 INFO Shutdown successful


With VPNSP=custom:
gluetun              | 2022/01/07 09:31:08 INFO storage: creating /gluetun/servers.json with 11120 hardcoded servers
gluetun              | 2022/01/07 09:31:08 ERROR failed validating VPN settings: VPN type is not valid: "custom" and can only be one of openvpn, wireguard
gluetun              | 2022/01/07 09:31:08 INFO Shutdown successful

With omitted VPNSP/VPN_TYPE:
gluetun              | 2022/01/07 09:32:30 INFO storage: creating /gluetun/servers.json with 11120 hardcoded servers
gluetun              | 2022/01/07 09:32:31 ERROR failed validating VPN settings: provider settings validation failed: server selection settings validation failed: VPN provider name is not valid: openvpn
gluetun              | 2022/01/07 09:32:31 INFO Shutdown successful

```
```


### Share your configuration

```yml
#GlueTUN
  gluetun:
    image: qmcgaw/gluetun:latest    
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/data/docker/gluetun/config/:/gluetun/config/:ro
    ports:
      - 8112:8112
      - 58846:58846
      - 8000:8000/tcp      
    environment:
      #General
      - BLOCK_MALICIOUS=off      
      - TZ=Europe/Amsterdam
      - DOT=off
      - DNS_PLAINTEXT_ADDRESS=84.200.70.40  
##SlickVPN
      - VPNSP=openvpn
      - OPENVPN_CUSTOM_CONFIG=/gluetun/config/custom.conf
      - VPN_TYPE=openvpn
      - OPENVPN_USER=xxxxxxxxxxx
      - OPENVPN_PASSWORD=xxxxxxx
      - OPENVPN_CIPHER=AES-256-CBC
      - HEALTH_VPN_DURATION_INITIAL=60s
      - HEALTH_VPN_DURATION_ADDITION=10s
```
