### ISSUE TITLE
Bug: gluetun container constantly restarting

### ISSUE THREAD

**Issue by shuntera** [qdm12/gluetun#787]
### Is this urgent?

Yes

### Host OS

MacOS

### CPU arch

x86_64

### VPN service provider

Privado

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-01-07T22:46:55.519Z (commit 6f5a78c)

### What's the problem 🤔

Container is crashing and restarting

### Share your logs

```log
========================================

========================================

=============== gluetun ================

========================================

=========== Made with ❤️ by ============

======= https://github.com/qdm12 =======

========================================

========================================

Running version latest built on 2022-01-07T22:46:55.519Z (commit 6f5a78c)

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new

🐛 Bug? https://github.com/qdm12/gluetun/issues/new

✨ New feature? https://github.com/qdm12/gluetun/issues/new

☕ Discussion? https://github.com/qdm12/gluetun/discussions/new

💻 Email? quentin.mcgaw@gmail.com

💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12

2022/01/09 17:39:40 INFO storage: merging by most recent 11100 hardcoded servers and 11100 servers read from /gluetun/servers.json

2022/01/09 17:39:40 ERROR failed validating VPN settings: provider settings validation failed: server selection settings validation failed: the hostname specified is not valid: value is not one of the possible choices: value "jfk-003.vpn.privado.io", choices available are akl-004.vpn.privado.io, ams-001.vpn.privado.io, ams-004.vpn.privado.io, ams-005.vpn.privado.io, ams-006.vpn.privado.io, ams-007.vpn.privado.io, ams-008.vpn.privado.io, ams-009.vpn.privado.io, ams-011.vpn.privado.io, ams-012.vpn.privado.io, ams-014.vpn.privado.io, ams-015.vpn.privado.io, arn-003.vpn.privado.io, arn-004.vpn.privado.io, ath-001.vpn.privado.io, ath-002.vpn.privado.io, ath-003.vpn.privado.io, ath-004.vpn.privado.io, beg-001.vpn.privado.io, beg-002.vpn.privado.io, ber-001.vpn.privado.io, ber-002.vpn.privado.io, bkk-001.vpn.privado.io, bkk-002.vpn.privado.io, bru-001.vpn.privado.io, bru-002.vpn.privado.io, bru-003.vpn.privado.io, bru-004.vpn.privado.io, bts-001.vpn.privado.io, bts-002.vpn.privado.io, bud-001.vpn.privado.io, cdg-001.vpn.privado.io, cdg-004.vpn.privado.io, cgk-001.vpn.privado.io, cgk-003.vpn.privado.io, cgk-004.vpn.privado.io, cgk-005.vpn.privado.io, cgk-007.vpn.privado.io, cgk-009.vpn.privado.io, cph-001.vpn.privado.io, cph-002.vpn.privado.io, cph-003.vpn.privado.io, dca-001.vpn.privado.io, dca-003.vpn.privado.io, dca-004.vpn.privado.io, dca-005.vpn.privado.io, dca-007.vpn.privado.io, dca-009.vpn.privado.io, dca-012.vpn.privado.io, dca-017.vpn.privado.io, den-002.vpn.privado.io, den-004.vpn.privado.io, den-005.vpn.privado.io, den-006.vpn.privado.io, dfw-001.vpn.privado.io, dfw-002.vpn.privado.io, dfw-003.vpn.privado.io, dfw-004.vpn.privado.io, dfw-005.vpn.privado.io, dfw-006.vpn.privado.io, dfw-007.vpn.privado.io, dfw-010.vpn.privado.io, dfw-011.vpn.privado.io, dfw-012.vpn.privado.io, dfw-013.vpn.privado.io, dfw-014.vpn.privado.io, dfw-015.vpn.privado.io, dfw-016.vpn.privado.io, dfw-021.vpn.privado.io, dfw-022.vpn.privado.io, dfw-023.vpn.privado.io, dfw-024.vpn.privado.io, dfw-025.vpn.privado.io, dfw-026.vpn.privado.io, dfw-027.vpn.privado.io, dfw-028.vpn.privado.io, dfw-029.vpn.privado.io, dfw-031.vpn.privado.io, dfw-032.vpn.privado.io, dfw-033.vpn.privado.io, dub-001.vpn.privado.io, dub-002.vpn.privado.io, dub-003.vpn.privado.io, dub-004.vpn.privado.io, fra-001.vpn.privado.io, fra-004.vpn.privado.io, fra-007.vpn.privado.io, gru-001.vpn.privado.io, hkg-001.vpn.privado.io, hkg-002.vpn.privado.io, hkg-004.vpn.privado.io, iev-001.vpn.privado.io, ist-001.vpn.privado.io, ist-002.vpn.privado.io, jfk-002.vpn.privado.io, jfk-004.vpn.privado.io, jfk-005.vpn.privado.io, jfk-006.vpn.privado.io, jfk-008.vpn.privado.io, jfk-010.vpn.privado.io, jfk-011.vpn.privado.io, jfk-012.vpn.privado.io, jfk-014.vpn.privado.io, jfk-015.vpn.privado.io, jfk-017.vpn.privado.io, jfk-019.vpn.privado.io, jfk-020.vpn.privado.io, jfk-023.vpn.privado.io, jfk-024.vpn.privado.io, jfk-025.vpn.privado.io, jfk-026.vpn.privado.io, jfk-028.vpn.privado.io, jfk-029.vpn.privado.io, jfk-030.vpn.privado.io, jfk-031.vpn.privado.io, jfk-033.vpn.privado.io, jfk-035.vpn.privado.io, jfk-038.vpn.privado.io, jfk-039.vpn.privado.io, jfk-040.vpn.privado.io, jfk-041.vpn.privado.io, jfk-048.vpn.privado.io, jrs-001.vpn.privado.io, jrs-002.vpn.privado.io, kul-001.vpn.privado.io, kul-002.vpn.privado.io, kul-006.vpn.privado.io, kul-007.vpn.privado.io, kul-009.vpn.privado.io, kul-010.vpn.privado.io, kul-011.vpn.privado.io, kul-013.vpn.privado.io, lax-001.vpn.privado.io, lax-003.vpn.privado.io, lax-004.vpn.privado.io, lax-006.vpn.privado.io, lax-007.vpn.privado.io, lax-008.vpn.privado.io, lhr-007.vpn.privado.io, lhr-008.vpn.privado.io, lhr-009.vpn.privado.io, lhr-012.vpn.privado.io, lhr-013.vpn.privado.io, lhr-014.vpn.privado.io, lhr-018.vpn.privado.io, lhr-020.vpn.privado.io, lhr-023.vpn.privado.io, lhr-025.vpn.privado.io, lis-002.vpn.privado.io, mad-001.vpn.privado.io, mad-002.vpn.privado.io, mad-003.vpn.privado.io, mad-004.vpn.privado.io, man-001.vpn.privado.io, man-002.vpn.privado.io, man-003.vpn.privado.io, man-004.vpn.privado.io, man-006.vpn.privado.io, man-007.vpn.privado.io, man-008.vpn.privado.io, mex-003.vpn.privado.io, mex-004.vpn.privado.io, mex-005.vpn.privado.io, mex-006.vpn.privado.io, mex-009.vpn.privado.io, mex-010.vpn.privado.io, mia-003.vpn.privado.io, mia-004.vpn.privado.io, mxp-002.vpn.privado.io, nrt-001.vpn.privado.io, nrt-002.vpn.privado.io, ord-003.vpn.privado.io, ord-005.vpn.privado.io, ord-006.vpn.privado.io, ord-007.vpn.privado.io, ord-008.vpn.privado.io, ord-011.vpn.privado.io, ord-012.vpn.privado.io, ord-015.vpn.privado.io, ord-016.vpn.privado.io, ord-017.vpn.privado.io, ord-018.vpn.privado.io, ord-019.vpn.privado.io, ord-020.vpn.privado.io, ord-021.vpn.privado.io, ord-022.vpn.privado.io, ord-023.vpn.privado.io, ord-027.vpn.privado.io, ord-028.vpn.privado.io, ord-029.vpn.privado.io, ord-031.vpn.privado.io, ord-032.vpn.privado.io, ord-033.vpn.privado.io, ord-034.vpn.privado.io, ord-036.vpn.privado.io, ord-037.vpn.privado.io, ord-038.vpn.privado.io, ord-039.vpn.privado.io, ord-041.vpn.privado.io, ord-042.vpn.privado.io, ord-043.vpn.privado.io, ord-044.vpn.privado.io, ord-050.vpn.privado.io, ord-052.vpn.privado.io, ord-053.vpn.privado.io, ord-054.vpn.privado.io, ord-057.vpn.privado.io, ord-058.vpn.privado.io, ord-060.vpn.privado.io, ord-061.vpn.privado.io, osl-003.vpn.privado.io, otp-002.vpn.privado.io, pdx-001.vpn.privado.io, pdx-002.vpn.privado.io, pdx-003.vpn.privado.io, pdx-004.vpn.privado.io, pdx-005.vpn.privado.io, pdx-006.vpn.privado.io, pdx-007.vpn.privado.io, pdx-009.vpn.privado.io, pdx-010.vpn.privado.io, pdx-013.vpn.privado.io, pdx-014.vpn.privado.io, pdx-015.vpn.privado.io, pdx-016.vpn.privado.io, pdx-017.vpn.privado.io, pdx-021.vpn.privado.io, pdx-022.vpn.privado.io, pdx-025.vpn.privado.io, pdx-026.vpn.privado.io, pdx-027.vpn.privado.io, pdx-028.vpn.privado.io, pdx-029.vpn.privado.io, prg-001.vpn.privado.io, rix-001.vpn.privado.io, rkv-001.vpn.privado.io, rkv-003.vpn.privado.io, rkv-004.vpn.privado.io, sin-001.vpn.privado.io, sin-002.vpn.privado.io, sin-003.vpn.privado.io, sin-004.vpn.privado.io, stl-002.vpn.privado.io, syd-002.vpn.privado.io, syd-004.vpn.privado.io, syd-006.vpn.privado.io, tsa-001.vpn.privado.io, tsa-002.vpn.privado.io, tsa-003.vpn.privado.io, tsa-005.vpn.privado.io, tsa-006.vpn.privado.io, tsa-007.vpn.privado.io, tsa-009.vpn.privado.io, tsa-010.vpn.privado.io, tsa-011.vpn.privado.io, tsa-012.vpn.privado.io, tsa-014.vpn.privado.io, vie-001.vpn.privado.io, vie-002.vpn.privado.io, vie-004.vpn.privado.io, waw-006.vpn.privado.io, waw-007.vpn.privado.io, waw-009.vpn.privado.io, waw-011.vpn.privado.io, waw-012.vpn.privado.io, waw-013.vpn.privado.io, waw-015.vpn.privado.io, waw-016.vpn.privado.io, waw-017.vpn.privado.io, waw-018.vpn.privado.io, waw-020.vpn.privado.io, waw-021.vpn.privado.io, waw-022.vpn.privado.io, waw-023.vpn.privado.io, waw-025.vpn.privado.io, waw-026.vpn.privado.io, waw-027.vpn.privado.io, waw-029.vpn.privado.io, waw-030.vpn.privado.io, waw-032.vpn.privado.io, yul-001.vpn.privado.io, yul-002.vpn.privado.io, yul-003.vpn.privado.io, yul-004.vpn.privado.io, yvr-002.vpn.privado.io, yyz-003.vpn.privado.io, zrh-001.vpn.privado.io, zrh-002.vpn.privado.io, zrh-004.vpn.privado.io

2022/01/09 17:39:40 INFO Shutdown successful
```

### Share your configuration

```yml
version: "3.7"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun_vpn
    cap_add:
      - NET_ADMIN
    network_mode: default
    ports:
      - 8888:8888/tcp # Tinyproxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
      - 9500:5076/tcp # nzbhydra2
      - 9501:8080/tcp # SabNZBD
      - 9502:9090/tcp # SabNZBD
      - 9503:8989/tcp # sonarr
      - 9504:7878/tcp # radarr
    volumes:
      - /Users/myname/vpn/config/glueutun:/gluetun
    environment:
      - VPNSP=privado
      - SHADOWSOCKS=on
      - SHADOWSOCKS_PASSWORD=XXXXXXXXX
      - SHADOWSOCKS_LOG=on
      - TZ=America/New_York
      - OPENVPN_USER=XXXXXXXX
      - OPENVPN_PASSWORD=XXXXXXXX
      - SERVER_HOSTNAME=jfk-002.vpn.privado.io,jfk-003.vpn.privado.io,jfk-005.vpn.privado.io,jfk-007.vpn.privado.io,jfk-009.vpn.privado.io,jfk-010.vpn.privado.io
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.107/32 #192.168.1.0/24
    restart: unless-stopped

  nzbhydra2:
    image: linuxserver/nzbhydra2
    network_mode: "service:gluetun"
    container_name: nzbhydra2_vpn
    volumes: 
      - /Users/myname/vpn/config/linuxserver_nzbhydra2/data:/data
      - /Users/myname/vpn/config/linuxserver_nzbhydra2/config:/config
    restart: unless-stopped
    
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd_vpn
    network_mode: "service:gluetun"
    environment:
        - TZ=America/New_York
    volumes:
        - /Users/myname/vpn/config/sabnzbd:/config
        - /Volumes/Samsung_T5/Downloads:/downloads
        - /Volumes/Samsung_T5/Downloads/incomplete:/incomplete-downloads
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr_vpn
    network_mode: "service:gluetun"
    environment:
       - TZ=America/New_York
    volumes:
      - /Users/myname/vpn/config/sonarr:/config
      - /Volumes/Samsung_T5/TV Shows:/tv
      - /Volumes/Samsung_T5/Downloads:/downloads
    restart: unless-stopped
    
  radarr:
    image: linuxserver/radarr:nightly
    container_name: radarr_vpn
    network_mode: "service:gluetun"
    environment:
      - TZ=America/New_York
    volumes:
      - /Users/myname/vpn/config/radarr:/config
      - /Volumes/Samsung_T5/Movies:/movies
      - /Volumes/Samsung_T5/Downloads:/downloads
    restart: unless-stopped
```
