### ISSUE TITLE
Feature request: Support hostnames on WIREGUARD_ENDPOINT_IP 

### ISSUE THREAD

**Issue by fishnux** [qdm12/gluetun#788]
### What's the feature 🧐

Currently, WIREGUARD_ENDPOINT_IP only accepts IP addresses. Some VPN providers specify a domain name instead of an IP address on their Wireguard configuration files

### Extra information and references

```
cannot read server selection settings: environment variable WIREGUARD_ENDPOINT_IP: cannot parse IP address: example.com
```

**Comment by ahmaddxb** [comment]
I also required this option

**Comment by qdm12** [comment]
For now just use `docker run --rm alpine:3.15 nslookup yourvpnserver.com` to translate it to an IP address.

The current situation is gluetun doesn't do any network interaction until the VPN is connected to avoid leaking anything. I put special attention to this and to have the firewall setup as quickly as possible too.

Now this issue and others such as querying VPN provider web API to obtain Wireguard keys need to access internet before the VPN is up so it will ultimately be an option, but I can't say how long it will take me to get to it. Thanks for your understanding and of course let's keep this issue opened!

**Comment by misery** [comment]
Same here to connect to my local wireguard server at home. I'm using DDNS for this.

**Comment by misery** [comment]
@qdm12 Is there any work around to use ddns for own wireguard server? Any automatic shell script that could fetch the new IP and send it to the control server?
Every night the connection is broken.

**Comment by TMD20** [comment]
I'm using this as a middle as a intermediate vpn
services:
  ipgen:
    image: wbitt/network-multitool:alpine-extra
    container_name: ipgen
    networks:
      - mynetwork
    command:  ["bin/bash","-c","while true;do dig europe.all.vpn.airdns.org +short |nc -l 4000;done"]


Change the entry point to this on the vpn service
    entrypoint:
          ["/bin/sh", "-c" , export VPN_ENDPOINT_IP=$$(timeout  0.1 nc ipgen 4000|shuf -n 1)&&/gluetun-entrypoint]

I imagine with this if the connection failed the healthtest, maybe it would remake the connection. 
However I just configure this today. 

It at least able to grab the IP on initial connect

**Comment by pranjaljain0** [comment]
I found a way. If anyone wants help can reach out. I will post it.
Thanks

**Comment by pranjaljain0** [comment]
Yes I tried it for wireguard custom and it wasnt working

**Comment by pranjaljain0** [comment]
What I did was started a nginx container and made a TCP/UDP proxy_pass and then in gluetun I used the localhost IP

**Comment by vdrover** [comment]
Would love this feature.

**Comment by vdrover** [comment]
@pCoder3000 that would have been awesome otherwise!

**Comment by pCoder3000** [comment]
did someone tryed it in the new release?

**Comment by Eiqnepm** [comment]
Just came across this issue because one of my providers doesn't provide IP addresses, they automatically determine the nearest server each time you connect using a hostname.


> Maybe add an extra option like WIREGUARD_ENDPOINT_ALLOW_DNS=1 to explicitly let the user decide that it could leak the address.

Probably easier to create one more environment variable called `VPN_ENDPOINT_HOSTNAME`, which when used implicitly enables DNS resolution that hostname.

**Comment by danriedl** [comment]
BIG +1
I'm using gluetun together with home-assistant in a truenas (truecharts) app-deployment. 
It is connecting to my dad's router (it runs the WireGuard server), where he has a dynamic IP from his ISP.
Therefore, I have to redeploy the helm chart every time he gets a new IP, which freaks me out.

**Comment by MulverineX** [comment]
It doesn't even look like gluetun ever actually fully supported running custom openvpn configs. I tried resolving my VPN provider to an IP, and this happened

```
2023-08-30T03:39:30Z ERROR [openvpn] No client-side authentication method is specified.  You must use either --cert/--key, --pkcs12, or --auth-user-pass
2023-08-30T03:39:30Z INFO [openvpn] Use --help for more information.
2023-08-30T03:39:30Z ERROR [vpn] exit status 1
```

**Comment by raphamotta** [comment]
> What I did was started a nginx container and made a TCP/UDP proxy_pass and then in gluetun I used the localhost IP

Could you please give more details about that?

**Comment by gurabli** [comment]
One more vote for this, using custom wireguard (my own) and need ddns.

**Comment by JoshBeer** [comment]
+1 vote for this. I'm baffled this is not a feature yet. So many usecases with dynamic IPs where you just need to use DDNS and therefore have to resort to a hostname.

**Comment by Kreakdude** [comment]
+1

My vpn provider, Ivacy, lets me download some wireguard files and they come with a couple values labeled dns so I wonder if those could be used with some optional env vars? Just a wild guess, I haven't successfully got anything working yet.

**Comment by alphadijkstra** [comment]
+1
I am in dire need of this feature as well.

@raphamotta I tried doing the same. My Nginx Proxy Manager, running through docker, runs on ip 192.168.0.25 and routes port 5182 to domain.com:51820. However I am unable to succesfully connect. I am sure the Wireguard server works correctly. But just can't route/set up the connection. In docker I set the Nginx ports open for 5182 and even 51820. But to no avail. 
I've been struggling hard with this. Any tips? Am I missing some firewall settings? I use ipfire.

**Comment by MulverineX** [comment]
@alphadijkstra have you tried using the resolved IP address? Is using that a problem due to a lack of a static IP?

**Comment by alphadijkstra** [comment]
> @alphadijkstra have you tried using the resolved IP address?

Using the resolved IP works within gluetun. But that would break as soon as the Wireguard host changes IP (dynamic IP). That is why this gluetun feature is quite important to me.

**Comment by sj14** [comment]
It was also somewhat tricky for me to get it running, so here is my example (but it's from Kubernetes, anyway, I hope it's still helpful for some).
I've added the google endpoint for debugging, so I could see if it's a problem with my network or the configuration.

<details>
  <summary>Show Manifests</summary>

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
  labels:
    name: wireguard
---
apiVersion: v1
kind: Service
metadata:
  name: vpn
  namespace: wireguard
spec:
  ports:
    - name: httpproxy
      port: 8888
      protocol: TCP
      targetPort: 8888
    - name: shadowsockstcp
      port: 8388
      protocol: TCP
      targetPort: 8388
    - name: shadowsocksudp
      port: 8388
      protocol: UDP
      targetPort: 8388
  selector:
    app: wireguard
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wireguard
  name: vpn
  namespace: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
      namespace: wireguard
    spec:
      containers:
        - name: debug
          image: curlimages/curl
          command: ["sleep"]
          args: ["infinity"]
          resources:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 200m
        - name: vpn
          image: qmcgaw/gluetun:v3.35.0
          imagePullPolicy: IfNotPresent
          env:
            - name: HEALTH_TARGET_ADDRESS
              value: 192.168.0.1:80
            - name: VPN_SERVICE_PROVIDER
              value: custom
            - name: VPN_TYPE
              value: wireguard
            - name: VPN_ENDPOINT_IP
              value: 10.102.159.86 # dyndns proxy service, use hostname when https://github.com/qdm12/gluetun/issues/788 is fixed
            - name: VPN_ENDPOINT_PORT
              value: "53280"
            - name: WIREGUARD_PUBLIC_KEY
              value: <CHANGE_ME>
            - name: WIREGUARD_PRESHARED_KEY
              value: <CHANGE_ME>
            - name: WIREGUARD_PRIVATE_KEY
              value: <CHANGE_ME>
            - name: WIREGUARD_ADDRESSES
              value: 10.200.200.1/24
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
          volumeMounts:
            - mountPath: /gluetun
              name: gluetun
          resources:
            requests:
              memory: 512Mi
              cpu: 10m
            limits:
              memory: 768Mi
              cpu: 200m
      volumes:
        - hostPath:
            path: /dev/net/tun
          name: mydevice0
        - name: gluetun
          emptyDir:
            sizeLimit: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dns
  name: dyndns-proxy
  namespace: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns
  template:
    metadata:
      labels:
        app: dns
      namespace: wireguard
    spec:
      containers:
        - name: debug
          image: curlimages/curl
          command: ["sleep"]
          args: ["infinity"]
          resources:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 200m
        - name: dyndns-proxy
          image: nginx:1.25
          volumeMounts:
          - mountPath: /etc/nginx
            readOnly: true
            name: nginx-conf
          resources:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 256Mi
              cpu: 200m
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf # place ConfigMap `nginx-conf` in /etc/nginx
            items:
              - key: nginx.conf
                path: nginx.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: wireguard
data:
  nginx.conf: |
    # Variable to allow dns refresh (see https://serverfault.com/a/593003)
    events {}
    stream {
      server {
        resolver 8.8.8.8;
        listen 53280 udp;
        set $url "<DYNAMIC_DNS_HOST>:53280";
        proxy_pass $url;
      }
      server {
        resolver 8.8.8.8;
        listen 53000;
        set $url "google.com:80";
        proxy_pass $url;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: wireguard
spec:
  type: ClusterIP
  clusterIP: 10.102.159.86
  ports:
  - name: google
    port: 53000
    targetPort: 53000
    protocol: TCP
  - name: dyndns
    port: 53280
    targetPort: 53280
    protocol: UDP
  selector:
    app: dns
```

</details>
