### ISSUE TITLE
Bug: OpenVPN settings validation failed: user is empty

### ISSUE THREAD

**Issue by Raptor039** [qdm12/gluetun#789]
### Is this urgent?

Yes

### Host OS

Debian Buster

### CPU arch

x86_64

### VPN service provider

Custom

### What are you using to run the container

docker-compose

### What is the version of Gluetun

4bdce76

### What's the problem 🤔

Hi Quentin,

a bug occured just after had pulled of latest image, please see below for logs related to it

In my setup, I don't use user / password authentication, only certificates based auth . I didn't have this error with the 3.26.0 release.

Thanks for your help.

### Share your logs

```log
2022/01/13 12:42:19 INFO storage: merging by most recent 11100 hardcoded servers and 11100 servers read from /gluetun/servers.json
2022/01/13 12:42:19 ERROR failed validating VPN settings: OpenVPN settings validation failed: user is empty
2022/01/13 12:42:19 INFO Shutdown successful
```

### Share your configuration

```yml
version: '3'
services:
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    restart: always
    cap_add:
      - NET_ADMIN
    environment: # Voir ici pour plus d'info : https://github.com/qdm12/gluetun/wiki/Environment-variables
      - TZ=Europe/Paris
      - VPNSP=custom
      - OPENVPN_CUSTOM_CONFIG=/gluetun/conf.ovpn
      - FIREWALL_VPN_INPUT_PORTS=8112,6881
    ports:
      - 8112:8112
    expose:
      - 6881
      - 6881/udp
    labels:
      com.centurylinklabs.watchtower.enable: false
    volumes:
      - gluetun_data:/gluetun
      - /srv/docker_data/ovpn/conf.ovpn:/gluetun/conf.ovpn
volumes:
  gluetun_data:
```
