### ISSUE TITLE
Bug: Container fails to start

### ISSUE THREAD

**Issue by jnines** [qdm12/gluetun#800]
### Is this urgent?

Yes

### Host OS

Ubuntu 20.04

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker-compose

### What is the version of Gluetun

commit 2e80645adbd7a732d5b304e194cac4e9e4c19b6

### What's the problem 🤔

`Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/gluetun": permission denied: unknown`

### Share your logs

```log
None other available
```

### Share your configuration

```yml
gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
      - 9008:9117     # Jacket
      - 9005:7878     # Radarr
      - 9012:8686     # Lidarr
      - 9006:9091     # Trans web
      - 51413:51413   # Trans
      - 9003:8989     # Sonarr
    volumes:
      - ${DOCK}/gluetun:/gluetun
    environment:
      - OPENVPN_USER=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - VPNSP=private internet access
      - TZ=${TZ}
      - REGION=${VPN_CONFIG}
      - PUID=${PUID}
      - PGID=${PGID}
      - FIREWALL_OUTBOUND_SUBNETS=10.10.10.0/24,10.10.20.0/24,10.10.30.0/24
      - OPENVPN_CIPHER=aes-256-gcm
      - OPENVPN_AUTH=sha256
      - PIA_ENCRYPTION=strong
    restart: always
    networks:
      - media
```
