### ISSUE TITLE
Bug: gluetun crashes, restarts and drops local LAN access

### ISSUE THREAD

**Issue by hugalafutro** [qdm12/gluetun#803]
### Is this urgent?

No

### Host OS

Ubuntu 21.10

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker-compose

### What is the version of Gluetun

latest built on 2022-01-19T00:42:09.225Z (commit a1a1128)

### What's the problem 🤔

Last 2 or 3 days I'm noticing my gluetun stack suddenly ceases to be accessible from local lan, but the containers themselves seem to access internet no problem. When I check gluetun's logs there's a panic and restart. Have to bring whole stack down and up to fix.

### Share your logs

```log
pia_gluetun_vm-docker  | 2022/01/21 14:52:47 INFO updater: updating Custom servers...
pia_gluetun_vm-docker  | panic: cannot update custom provider
pia_gluetun_vm-docker  |
pia_gluetun_vm-docker  | goroutine 175465 [running]:
pia_gluetun_vm-docker  | github.com/qdm12/gluetun/internal/updater.(*updater).getUpdateFunction(0xc0005b4800, {0x9005ed, 0x6})
pia_gluetun_vm-docker  |        github.com/qdm12/gluetun/internal/updater/updater.go:74 +0x89f
pia_gluetun_vm-docker  | github.com/qdm12/gluetun/internal/updater.(*updater).UpdateServers(_, {_, _})
pia_gluetun_vm-docker  |        github.com/qdm12/gluetun/internal/updater/updater.go:55 +0x155
pia_gluetun_vm-docker  | github.com/qdm12/gluetun/internal/updater.(*looper).Run.func1()
pia_gluetun_vm-docker  |        github.com/qdm12/gluetun/internal/updater/loop.go:104 +0xf8
pia_gluetun_vm-docker  | created by github.com/qdm12/gluetun/internal/updater.(*looper).Run
pia_gluetun_vm-docker  |        github.com/qdm12/gluetun/internal/updater/loop.go:102 +0x2e5
pia_gluetun_vm-docker  | ========================================
pia_gluetun_vm-docker  | ========================================
pia_gluetun_vm-docker  | =============== gluetun ================
pia_gluetun_vm-docker  | ========================================
pia_gluetun_vm-docker  | =========== Made with ❤️ by ============
pia_gluetun_vm-docker  | ======= https://github.com/qdm12 =======
pia_gluetun_vm-docker  | ========================================
pia_gluetun_vm-docker  | ========================================
pia_gluetun_vm-docker  |
pia_gluetun_vm-docker  | Running version latest built on 2022-01-19T00:42:09.225Z (commit a1a1128)
pia_gluetun_vm-docker  |
pia_gluetun_vm-docker  | 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
pia_gluetun_vm-docker  | 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
pia_gluetun_vm-docker  | ✨ New feature? https://github.com/qdm12/gluetun/issues/new
pia_gluetun_vm-docker  | ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
pia_gluetun_vm-docker  | 💻 Email? quentin.mcgaw@gmail.com
pia_gluetun_vm-docker  | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO storage: merging by most recent 11100 hardcoded servers and 11100 servers read from /gluetun/servers.json
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO Alpine version: 3.15.0
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO OpenVPN 2.4 version: 2.4.11
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO OpenVPN 2.5 version: 2.5.4
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO Unbound version: 1.13.2
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO IPtables version: v1.8.7
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO Settings summary:
pia_gluetun_vm-docker  | ├── VPN settings:
pia_gluetun_vm-docker  | |   ├── VPN provider settings:
pia_gluetun_vm-docker  | |   |   ├── Name: private internet access
pia_gluetun_vm-docker  | |   |   ├── Server selection settings:
pia_gluetun_vm-docker  | |   |   |   ├── VPN type: openvpn
pia_gluetun_vm-docker  | |   |   |   ├── Regions: uk london
pia_gluetun_vm-docker  | |   |   |   └── OpenVPN server selection settings:
pia_gluetun_vm-docker  | |   |   |       ├── Protocol: UDP
pia_gluetun_vm-docker  | |   |   |       └── Private Internet Access encryption preset: strong
pia_gluetun_vm-docker  | |   |   └── Automatic port forwarding settings:
pia_gluetun_vm-docker  | |   |       ├── Enabled: yes
pia_gluetun_vm-docker  | |   |       └── Forwarded port file path: /tmp/gluetun/forwarded_port
pia_gluetun_vm-docker  | |   └── OpenVPN settings:
pia_gluetun_vm-docker  | |       ├── OpenVPN version: 2.5
pia_gluetun_vm-docker  | |       ├── User: [set]
pia_gluetun_vm-docker  | |       ├── Password: [set]
pia_gluetun_vm-docker  | |       ├── Private Internet Access encryption preset: strong
pia_gluetun_vm-docker  | |       ├── Tunnel IPv6: no
pia_gluetun_vm-docker  | |       ├── Network interface: tun0
pia_gluetun_vm-docker  | |       ├── Run OpenVPN as: root
pia_gluetun_vm-docker  | |       └── Verbosity level: 1
pia_gluetun_vm-docker  | ├── DNS settings:
pia_gluetun_vm-docker  | |   ├── DNS server address to use: 127.0.0.1
pia_gluetun_vm-docker  | |   ├── Keep existing nameserver(s): no
pia_gluetun_vm-docker  | |   └── DNS over TLS settings:
pia_gluetun_vm-docker  | |       ├── Enabled: yes
pia_gluetun_vm-docker  | |       ├── Update period: every 24h0m0s
pia_gluetun_vm-docker  | |       ├── Unbound settings:
pia_gluetun_vm-docker  | |       |   ├── Authoritative servers:
pia_gluetun_vm-docker  | |       |   |   └── cloudflare
pia_gluetun_vm-docker  | |       |   ├── Caching: yes
pia_gluetun_vm-docker  | |       |   ├── IPv6: no
pia_gluetun_vm-docker  | |       |   ├── Verbosity level: 1
pia_gluetun_vm-docker  | |       |   ├── Verbosity details level: 0
pia_gluetun_vm-docker  | |       |   ├── Validation log level: 0
pia_gluetun_vm-docker  | |       |   ├── System user: root
pia_gluetun_vm-docker  | |       |   └── Allowed networks:
pia_gluetun_vm-docker  | |       |       ├── 0.0.0.0/0
pia_gluetun_vm-docker  | |       |       └── ::/0
pia_gluetun_vm-docker  | |       └── DNS filtering settings:
pia_gluetun_vm-docker  | |           ├── Block malicious: yes
pia_gluetun_vm-docker  | |           ├── Block ads: no
pia_gluetun_vm-docker  | |           ├── Block surveillance: no
pia_gluetun_vm-docker  | |           └── Blocked IP networks:
pia_gluetun_vm-docker  | |               ├── 127.0.0.1/8
pia_gluetun_vm-docker  | |               ├── 10.0.0.0/8
pia_gluetun_vm-docker  | |               ├── 172.16.0.0/12
pia_gluetun_vm-docker  | |               ├── 192.168.0.0/16
pia_gluetun_vm-docker  | |               ├── 169.254.0.0/16
pia_gluetun_vm-docker  | |               ├── ::1/128
pia_gluetun_vm-docker  | |               ├── fc00::/7
pia_gluetun_vm-docker  | |               ├── fe80::/10
pia_gluetun_vm-docker  | |               ├── ::ffff:7f00:1/104
pia_gluetun_vm-docker  | |               ├── ::ffff:a00:0/104
pia_gluetun_vm-docker  | |               ├── ::ffff:a9fe:0/112
pia_gluetun_vm-docker  | |               ├── ::ffff:ac10:0/108
pia_gluetun_vm-docker  | |               └── ::ffff:c0a8:0/112
pia_gluetun_vm-docker  | ├── Firewall settings:
pia_gluetun_vm-docker  | |   ├── Enabled: yes
pia_gluetun_vm-docker  | |   └── Outbound subnets:
pia_gluetun_vm-docker  | |       └── {192.168.1.0 ffffff00}
pia_gluetun_vm-docker  | ├── Log settings:
pia_gluetun_vm-docker  | |   └── Log level: INFO
pia_gluetun_vm-docker  | ├── Health settings:
pia_gluetun_vm-docker  | |   ├── Server listening address: 127.0.0.1:9999
pia_gluetun_vm-docker  | |   ├── Address to ping: github.com
pia_gluetun_vm-docker  | |   └── VPN wait durations:
pia_gluetun_vm-docker  | |       ├── Initial duration: 5s
pia_gluetun_vm-docker  | |       └── Additional duration: 5s
pia_gluetun_vm-docker  | ├── Shadowsocks server settings:
pia_gluetun_vm-docker  | |   ├── Enabled: yes
pia_gluetun_vm-docker  | |   ├── Listening address: :8388
pia_gluetun_vm-docker  | |   ├── Cipher: chacha20-ietf-poly1305
pia_gluetun_vm-docker  | |   ├── Password: [set]
pia_gluetun_vm-docker  | |   └── Log addresses: no
pia_gluetun_vm-docker  | ├── HTTP proxy settings:
pia_gluetun_vm-docker  | |   ├── Enabled: yes
pia_gluetun_vm-docker  | |   ├── Listening address: :8888
pia_gluetun_vm-docker  | |   ├── User: gluetun
pia_gluetun_vm-docker  | |   ├── Password: [set]
pia_gluetun_vm-docker  | |   ├── Stealth mode: no
pia_gluetun_vm-docker  | |   └── Log: no
pia_gluetun_vm-docker  | ├── Control server settings:
pia_gluetun_vm-docker  | |   ├── Listening port: 8000
pia_gluetun_vm-docker  | |   └── Logging: yes
pia_gluetun_vm-docker  | ├── OS Alpine settings:
pia_gluetun_vm-docker  | |   ├── Process UID: 1000
pia_gluetun_vm-docker  | |   ├── Process GID: 1000
pia_gluetun_vm-docker  | |   └── Timezone: Europe/London
pia_gluetun_vm-docker  | ├── Public IP settings:
pia_gluetun_vm-docker  | |   ├── Fetching: every 12h0m0s
pia_gluetun_vm-docker  | |   └── IP file path: /tmp/gluetun/ip
pia_gluetun_vm-docker  | ├── Server data updater settings:
pia_gluetun_vm-docker  | |   ├── Update period: 48h0m0s
pia_gluetun_vm-docker  | |   ├── DNS address: 1.1.1.1
pia_gluetun_vm-docker  | |   └── Providers to update: custom, cyberghost, expressvpn, fastestvpn, hidemyass, ipvanish, ivpn, mullvad, nordvpn, perfect privacy, privado, private internet access, privatevpn, protonvpn, purevpn, surfshark, torguard, vpn unlimited, vyprvpn, wevpn, windscribe
pia_gluetun_vm-docker  | └── Version settings:
pia_gluetun_vm-docker  |     └── Enabled: yes
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO routing: default route found: interface eth0, gateway 172.17.0.1
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO routing: local ethernet link found: eth0
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO routing: local ipnet found: 172.17.0.0/16
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO routing: default route found: interface eth0, gateway 172.17.0.1
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO routing: adding route for 0.0.0.0/0
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO firewall: firewall disabled, only updating allowed subnets internal list
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO routing: default route found: interface eth0, gateway 172.17.0.1
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO routing: adding route for 192.168.1.0/24
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO firewall: enabling...
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO firewall: enabled successfully
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO healthcheck: listening on 127.0.0.1:9999
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO http server: listening on :8000
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO dns over tls: using plaintext DNS at address 1.1.1.1
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO http proxy: listening on :8888
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO firewall: setting VPN connection through firewall...
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO shadowsocks: listening TCP on :8388
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO shadowsocks: listening UDP on :8388
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO openvpn: OpenVPN 2.5.4 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov 15 2021
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO openvpn: library versions: OpenSSL 1.1.1l  24 Aug 2021, LZO 2.10
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO openvpn: CRL: loaded 1 CRLs from file -----BEGIN X509 CRL-----
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO openvpn: [REDACTED]
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO openvpn: -----END X509 CRL-----
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET][REDACTED]:1197
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO openvpn: UDP link local: (not bound)
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO openvpn: UDP link remote: [AF_INET][REDACTED]:1197
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 WARN openvpn: 'link-mtu' is used inconsistently, local='link-mtu 1569', remote='link-mtu 1554'
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 WARN openvpn: 'keysize' is used inconsistently, local='keysize 256', remote='keysize 128'
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 WARN openvpn: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO openvpn: [london433] Peer Connection Initiated with [AF_INET][REDACTED]:1197
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO openvpn: TUN/TAP device tun0 opened
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO openvpn: /sbin/ip link set dev tun0 up mtu 1500
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO openvpn: /sbin/ip link set dev tun0 up
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO openvpn: /sbin/ip addr add dev tun0 [REDACTED]/24
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO openvpn: UID set to nonrootuser
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO openvpn: Initialization Sequence Completed
pia_gluetun_vm-docker  | 2022/01/21 14:52:48 INFO dns over tls: downloading DNS over TLS cryptographic files
pia_gluetun_vm-docker  | 2022/01/21 14:52:49 INFO healthcheck: healthy!
pia_gluetun_vm-docker  | 2022/01/21 14:52:50 INFO dns over tls: downloading hostnames and IP block lists
pia_gluetun_vm-docker  | 2022/01/21 14:52:55 INFO dns over tls: init module 0: validator
pia_gluetun_vm-docker  | 2022/01/21 14:52:55 INFO dns over tls: init module 1: iterator
pia_gluetun_vm-docker  | 2022/01/21 14:52:55 INFO dns over tls: start of service (unbound 1.13.2).
pia_gluetun_vm-docker  | 2022/01/21 14:52:55 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
pia_gluetun_vm-docker  | 2022/01/21 14:52:55 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
pia_gluetun_vm-docker  | 2022/01/21 14:52:55 INFO dns over tls: ready
pia_gluetun_vm-docker  | 2022/01/21 14:52:55 INFO vpn: You are running on the bleeding edge of latest!
pia_gluetun_vm-docker  | 2022/01/21 14:52:55 INFO vpn: VPN gateway IP address: [REDACTED]
pia_gluetun_vm-docker  | 2022/01/21 14:52:55 INFO port forwarding: Found saved forwarded port data for port 20917
pia_gluetun_vm-docker  | 2022/01/21 14:52:55 INFO port forwarding: Forwarded port data expires in 17 days
pia_gluetun_vm-docker  | 2022/01/21 14:52:55 INFO port forwarding: Port forwarded data expires in 17 days
pia_gluetun_vm-docker  | 2022/01/21 14:52:55 INFO port forwarding: port forwarded is 20917
pia_gluetun_vm-docker  | 2022/01/21 14:52:55 INFO firewall: setting allowed input port 20917 through interface tun0...
pia_gluetun_vm-docker  | 2022/01/21 14:52:55 INFO port forwarding: writing port file /tmp/gluetun/forwarded_port
pia_gluetun_vm-docker  | 2022/01/21 14:52:55 INFO ip getter: Public IP address is [REDACTED] (United Kingdom, England, London)
```

### Share your configuration

```yml
version: '3.7'
services:
  gluetun:
    image: qmcgaw/private-internet-access
    container_name: pia_gluetun_vm-docker
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 9888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8001:8000/tcp # Built-in HTTP control server
# other containers ports
      - 6767:6767     # bazarr
      - 8989:8989     # sonarr
      - 7878:7878     # radarr
      - 8686:8686     # lidarr
      - 8191:8191     # flaresolverr
      - 3579:3579     # ombi
      - 4040:4040     # airsonic
      - 8096:8096     # jellyfin
      - 5850:5800     # jdownloader2
      - 9696:9696     # prowlarr
      - 8532:8532     # qbittorrent
    volumes:
      - ./data_gluetun:/gluetun
      - ./data_gluetun/port_forward:/tmp/gluetun/forwarded_port
    environment:
      - OPENVPN_IPV6=off
      - OPENVPN_ROOT=no
      - VPNSP=private internet access
      - TZ=${TIMEZONE}
      - OPENVPN_USER=${PIA_USER}
      - OPENVPN_PASSWORD=${PIA_PASS}
      - REGION=${PIA_REGION}
      - BLOCK_MALICIOUS=on
      - UPDATER_PERIOD=48h
      - PORT_FORWARDING=on
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - HTTPPROXY=on
      - HTTPPROXY_USER=${PROXY_USER}
      - HTTPPROXY_PASSWORD=${PROXY_PASS}
      - SHADOWSOCKS=on
      - SHADOWSOCKS_PASSWORD=${SHADOW_PASS}
      - SHADOWSOCKS_LOG=off
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: pia_qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8532
    volumes:
      - ./config_qbt:/config
      - ./data_qbt:/webui_alt
      - /shares/samba/media2/_downloads:/downloads
    network_mode: "service:gluetun"
    restart: always
    depends_on:
      - gluetun
    stop_grace_period: 60s

  flaresolverr:
    container_name: pia_flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    image: flaresolverr/flaresolverr:latest
    environment:
      - TZ=${TIMEZONE}
      - LOG_LEVEL=info
    network_mode: "service:gluetun"
    restart: always
    depends_on:
      - gluetun

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: pia_lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:universal-wait-for-internet
    volumes:
      - ./config_lidarr:/config
      - /shares/samba/media:/media
      - /shares/samba/media2:/media2
    network_mode: "service:gluetun"
    restart: always
    depends_on:
      - gluetun
      - prowlarr
      - qbittorrent
    stop_grace_period: 60s

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: pia_radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:universal-wait-for-internet
    volumes:
      - ./config_radarr:/config
      - /shares/samba/media:/media
      - /shares/samba/media2:/media2
    network_mode: "service:gluetun"
    restart: always
    depends_on:
      - gluetun
      - prowlarr
      - qbittorrent
    stop_grace_period: 60s

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: pia_sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:universal-wait-for-internet
    volumes:
      - ./config_sonarr:/config
      - /shares/samba/media:/media
      - /shares/samba/media2:/media2
    network_mode: "service:gluetun"
    restart: always
    depends_on:
      - gluetun
      - prowlarr
      - qbittorrent
    stop_grace_period: 60s

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: pia_bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:universal-wait-for-internet
    volumes:
      - ./config_bazarr:/config
      - /shares/samba/media:/media
      - /shares/samba/media2:/media2
    network_mode: "service:gluetun"
    restart: always
    depends_on:
      - gluetun
      - sonarr
      - radarr
    stop_grace_period: 60s

  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: pia_ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:universal-wait-for-internet
    volumes:
      - ./config_ombi:/config
    restart: always
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
      - sonarr
      - radarr

  airsonic:
    image: airsonicadvanced/airsonic-advanced:latest
    container_name: pia_airsonic
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - 'JAVA_OPTS=-Xmx512m -Xms512m'
    volumes:
      - ./config_airsonic:/var/airsonic
      - /shares/samba/media/music:/var/music
      - ./airsonic_playlists:/var/playlists
      - ./airsonic_podcasts:/var/podcast
    network_mode: "service:gluetun"
    restart: always
    depends_on:
      - gluetun
    stop_grace_period: 60s

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: pia_prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:universal-wait-for-internet
    volumes:
      - ./data_prowlarr:/config
    network_mode: "service:gluetun"
    restart: always
    depends_on:
      - gluetun
      - flaresolverr
      - qbittorrent
    stop_grace_period: 60s

  jdownloader2:
    image: jlesage/jdownloader-2
    container_name: pia_jdownloader2
    restart: always
    volumes:
      - ./config_jdl2:/config
      - /shares/samba/private/_jdl2:/output
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - TZ=${TIMEZONE}
      - VNC_PASSWORD=
    network_mode: "service:gluetun"
    depends_on:
      - gluetun

  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: pia_jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/mods:universal-wait-for-internet
    volumes:
      - ./library_jellyfin:/config
      - /shares/samba/media:/media
      - /shares/samba/media2:/media2
    network_mode: "service:gluetun"
    restart: always
    depends_on:
      - gluetun
    stop_grace_period: 60s
```
