### ISSUE TITLE
Container showing unhealthy in portainer

### ISSUE THREAD

**Issue by YanisKyr** [qdm12/gluetun#831]
I'm getting an unhealthy flag from my Gluetun container and the error [looks like this](https://i.imgur.com/mQ9Lhig.png).

Below you'll see my docker-compose
```
version: "3"
services:
  gluetun:
    cap_add:
      - NET_ADMIN
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    network_mode: bridge
    environment:
      - VPNSP=****
      - VPN_TYPE=****
      - OPENVPN_PROTOCOL=udp
      - OPENVPN_USER=****
      - OPENVPN_PASSWORD=****
      - OPENVPN_FLAGS=--comp-lzo
      - REGION=Netherlands
      - TZ=Europe/London
      - PUID=****
      - PGID=****
    devices:
        - /dev/net/tun:/dev/net/tun
    privileged: true
    restart: unless-stopped
    volumes:
      - /****/gluetun:/config
```
