### ISSUE TITLE
Bug: Mullvad VPN fails to start due to timeouts

### ISSUE THREAD

**Issue by denizdogan** [qdm12/gluetun#859]
### Is this urgent?

No

### Host OS

Ubuntu

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-02-20T21:30:49.183Z (commit e756273)

### What's the problem 🤔

The VPN tunnel keeps failing to start. (See the logs)

### Share your logs

```log
gluetun_1  | 2022/02/20 23:11:45 INFO vpn: starting
gluetun_1  | 2022/02/20 23:11:45 INFO firewall: allowing VPN connection...
gluetun_1  | 2022/02/20 23:11:45 INFO wireguard: Using available kernelspace implementation
gluetun_1  | 2022/02/20 23:11:45 INFO wireguard: Connecting to <IP>:<PORT>
gluetun_1  | 2022/02/20 23:11:45 INFO wireguard: Wireguard is up
gluetun_1  | 2022/02/20 23:11:52 WARN dns over tls: cannot update files: Get "https://www.internic.net/domain/named.root": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
gluetun_1  | 2022/02/20 23:11:52 INFO dns over tls: attempting restart in 1m20s
gluetun_1  | 2022/02/20 23:11:52 ERROR ip getter: Get "https://domains.google.com/checkip": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
gluetun_1  | 2022/02/20 23:11:52 INFO ip getter: retrying in 5s
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPNSP=mullvad
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_PORT=<PORT>
      - WIREGUARD_PRIVATE_KEY=<PRIVATE_KEY>
      - WIREGUARD_ADDRESS=<ADDRESS>
      - SERVER_HOSTNAME=<SERVER1>,<SERVER2>,<SERVER3>
      - CITY=<CITY>
```

The above is based on the following WireGuard configuration file(s):

```
[Interface]
PrivateKey = <PRIVATE_KEY>
Address = <ADDRESS>,<ADDRESS_IP6>
DNS = <DNS>

[Peer]
PublicKey = <PUBLIC_KEY>
AllowedIPs = 0.0.0.0/0,::0/0
Endpoint = <ENDPOINT_IP>:<PORT>
```
