### ISSUE TITLE
Bug: Port forwarding guide doesn't work for Mullvad

### ISSUE THREAD

**Issue by denizdogan** [qdm12/gluetun#869]
### Is this urgent?

No

### Host OS

Ubuntu

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-02-26T16:19:23.160Z (commit 2b09b9c)

### What's the problem 🤔

Following these guides:

- https://github.com/qdm12/gluetun/wiki/VPN-server-port-forwarding
- https://mullvad.net/en/help/port-forwarding-and-mullvad/

I am doing all of this just to get an HTTP server working over Mullvad VPN.

It simply doesn't work. I'm surprised that everyone tells me not to port forward anything in the router, are we sure that's not needed?

I am not behind a NAT and my real IP is static and dedicated.

I CAN access the opened port from my local network using the local IP address of the Docker host.

### Share your logs

```log
gluetun        | 2022/02/26 17:59:36 INFO ip getter: Public IP address is x.y.z.w (Country, City, City)

Inside the gluetun container:

$ ./port-checker -port <PORT>
#################################
######### Port Checker ##########
######## by Quentin McGaw #######
######## Give some ❤️ at #########
# github.com/qdm12/port-checker #
#################################

2022/02/26 18:06:46 INFO listening on 0.0.0.0:<PORT>
```

### Share your configuration

```yml
gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPNSP=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=<PRIVATE_KEY>
      - WIREGUARD_ADDRESS=<IP_ADDRESS>/32
      - CITY=<CITY>
    ports:
      - <PORT>:<PORT>
      - <PORT>:<PORT>/udp
    restart: unless-stopped
```
