### ISSUE TITLE
Bug: Container restarting often with 3.28.1 because of health

### ISSUE THREAD

**Issue by arpitgupta** [qdm12/gluetun#906]
### Is this urgent?

No

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

docker-compose

### What is the version of Gluetun

3.28.1

### What's the problem 🤔

I have my own health check setup
```
 healthcheck:                                                                                                                                   
   test: ["CMD-SHELL", "apk info | grep -q ^curl || apk add curl && curl -s https://am.i.mullvad.net/ip"]                                        
   interval: 1m                                                                                                                                 
   timeout: 15s                                                                                                                                 
   retries: 5                                                                                                                                   
   start_period: 40s        
```

Has there been any change in how these are interpreted? I noticed that we made some changes to github endpoint, but i assume that since i have my own test command it should not be impacted? 

For now I have reverted back to 3.28.0 to see if it becomes stable and I will retry 3.28.1 once i confirm that.

### Share your logs

```log
None for now. I am still doing more testing.
```
