### ISSUE TITLE
Bug: "password is empty" error message with Mullvad and OpenVPN

### ISSUE THREAD

**Issue by Dared87** [qdm12/gluetun#907]
### Is this urgent?

Yes

### Host OS

Fedora 34 (Server Edition)

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

Podman

### What is the version of Gluetun

Running version v3.27.1 built on 2022-03-21T21:01:57.916Z (commit 5cc55c9)

### What's the problem 🤔

Since the update to version 3.27.1 I'm not able to connect to Mullvad with OpenVPN anymore. For some reason it expects to use a password, which is not needed for this VPN Provider. The problem started after the update to 3.27.1 and it was working before with this settings.

### Share your logs

```log
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================

Running version v3.27.1 built on 2022-03-21T21:01:57.916Z (commit 5cc55c9)

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2022/03/22 10:32:33 INFO storage: creating /gluetun/servers.json with 11100 hardcoded servers
2022/03/22 10:32:33 ERROR failed validating VPN settings: OpenVPN settings validation failed: password is empty
2022/03/22 10:32:33 INFO Shutdown successful
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    container_name: vpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun    
    security_opt:
      - "label=type:vpn.process"    
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER=XXX
      - SERVER_CITIES=XXX
```
