### ISSUE TITLE
Bug: Issues with TLS connections using custom provider

### ISSUE THREAD

**Issue by krsh-off** [qdm12/gluetun#912]
### Host OS

Mac OS Monterey 12.1, Ubuntu TSL 20.04

### CPU arch

x86_64

### VPN service provider

Custom

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-03-22T08:54:52.426Z (commit c6f68a6)

### What's the problem 🤔

I have a Premium subscription in Hotspot Shield VPN provider and I'd like to utilize its OpenVPN config file to establish a VPN connection through gluetun. The desired goal is to have other containers connecting to the network via gluetun. 

The problem I'm seeing is that I'm getting TLS-related errors, it looks like the gluetun container is unable to establish any TLS connection. 

### Share your logs

```log
With DOT enabled:

gluetun    | 2022/03/27 14:28:16 INFO openvpn: Initialization Sequence Completed
gluetun    | 2022/03/27 14:28:16 INFO dns over tls: downloading DNS over TLS cryptographic files
gluetun    | 2022/03/27 14:28:16 INFO healthcheck: healthy!
gluetun    | 2022/03/27 14:28:25 WARN dns over tls: cannot update files: Get "https://www.internic.net/domain/named.root": EOF
gluetun    | 2022/03/27 14:28:25 INFO dns over tls: attempting restart in 10s
gluetun    | 2022/03/27 14:28:28 ERROR vpn: cannot get version information: Get "https://api.github.com/repos/qdm12/gluetun/releases": EOF
gluetun    | 2022/03/27 14:28:28 ERROR ip getter: Get "https://ipinfo.io/ip": EOF
gluetun    | 2022/03/27 14:28:28 INFO ip getter: retrying in 5s
gluetun    | 2022/03/27 14:28:35 INFO dns over tls: downloading DNS over TLS cryptographic files
gluetun    | 2022/03/27 14:28:38 WARN dns over tls: cannot update files: Get "https://www.internic.net/domain/named.root": EOF
gluetun    | 2022/03/27 14:28:38 INFO dns over tls: attempting restart in 20s
gluetun    | 2022/03/27 14:28:40 WARN ip getter: Get "https://ipinfo.io/45.137.106.205": EOF
gluetun    | 2022/03/27 14:28:40 INFO ip getter: Public IP address is 45.137.106.205
gluetun    | 2022/03/27 14:28:58 INFO dns over tls: downloading DNS over TLS cryptographic files
gluetun    | 2022/03/27 14:29:02 WARN dns over tls: cannot update files: Get "https://www.internic.net/domain/named.root": EOF
gluetun    | 2022/03/27 14:29:02 INFO dns over tls: attempting restart in 40s

With DOT disabled:
gluetun    | 2022/03/27 14:30:04 INFO openvpn: Initialization Sequence Completed
gluetun    | 2022/03/27 14:30:04 INFO healthcheck: healthy!
gluetun    | 2022/03/27 14:30:08 ERROR ip getter: Get "https://ipinfo.io/ip": EOF
gluetun    | 2022/03/27 14:30:08 INFO ip getter: retrying in 5s
gluetun    | 2022/03/27 14:30:08 ERROR vpn: cannot get version information: Get "https://api.github.com/repos/qdm12/gluetun/releases": EOF
gluetun    | 2022/03/27 14:30:12 INFO healthcheck: unhealthy: cannot dial: dial tcp4: i/o timeout
gluetun    | 2022/03/27 14:30:13 INFO healthcheck: healthy!
gluetun    | 2022/03/27 14:30:21 WARN ip getter: Get "https://ipinfo.io/45.137.106.77": EOF
gluetun    | 2022/03/27 14:30:21 INFO ip getter: Public IP address is 45.137.106.77
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/HotspotShield_AM_v4.ovpn:/gluetun/config.conf:ro
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - OPENVPN_USER=my_user
      - OPENVPN_PASSWORD=my_pass
      - OPENVPN_CUSTOM_CONFIG=/gluetun/config.conf
      - DOT=off
```
