### ISSUE TITLE
Bug: Latest PIA image getting: ERROR [port forwarding] cannot refresh port forward data: cannot fetch token: HTTP status code is not OK: https://userid:password@privateinternetaccess.com/gtoken/generateToken: 403 403 Forbidden: response received: error code: 1020

### ISSUE THREAD

**Issue by td001** [qdm12/gluetun#930]
### Is this urgent?

No

### Host OS

Ubuntu Server 18

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-04-02T17:35:24.679Z (commit be386a8)

### What's the problem 🤔

Basically, when I fire up the container I keep getting these messages in the logs every 5 seconds when it tries to get a port forwarded (I removed personal account info):

`ERROR [port forwarding] cannot refresh port forward data: cannot fetch token: HTTP status code is not OK: https://userid:password@privateinternetaccess.com/gtoken/generateToken: 403 403 Forbidden: response received: error code: 1020`

I know you made some changes recently from a previous ticket I had read - so I made sure to update my image and make the required changes to my compose file. Am I doing something wrong or is this a legit issue?

### Share your logs

```log
ERROR [port forwarding] cannot refresh port forward data: cannot fetch token: HTTP status code is not OK: https://userid:password@privateinternetaccess.com/gtoken/generateToken: 403 403 Forbidden: response received: error code: 1020
```

### Share your configuration

```yml
vpn:
    image: qmcgaw/private-internet-access:latest
    container_name: vpn
    secrets:
      - VPN_USER
      - VPN_PASSWORD
    cap_add:
      - NET_ADMIN
    networks:
      vpn:
#        ipv4_address: 172.21.0.3
    init: true
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp
      - 8000:8000/tcp
      - 7080:80/tcp
      - 5000:5000/tcp
      - 51413:51413/tcp
      - 8388:8388/tcp
      - 6881:6881/udp
      - 6882:6882/udp
      - 8388:8388/udp
      - 8080:8080/tcp
    volumes:
      - /home/td00/rtorrent2config:/home/td00/rtorrent2config
      - /home/td00/pia_port_forward:/pia_port_forward
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=redacted
      - OPENVPN_PASSWORD=redacted
      - OPENVPN_IPV6=off
      - SERVER_REGIONS=CA Toronto
      - OPENVPN_PROCESS_USER=yes
      - TZ=America/Toronto
      - PRIVATE_INTERNET_ACCESS_OPENVPN_ENCRYPTION_PRESET=normal
      - PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING=on
      - PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING_STATUS_FILE=pia_port_forward
      - DOT=on
      - DOT_PROVIDERS=cloudflare
      - DOT_IPV6=off
      - DOT_VERBOSITY=1
      - PUID=1000
      - PGID=1000
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
    restart: always
```
