### ISSUE TITLE
Bug: Purevpn: cannot specify server country

### ISSUE THREAD

**Issue by fgurdradee** [qdm12/gluetun#934]
### Host OS

Windows 10

### CPU arch

x86_64

### VPN service provider

PureVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-04-02T17:35:24.679Z (commit be386a8)

### What's the problem 🤔

unable to connect to purevpn 

### Share your logs

```log
2022-04-11T09:46:00+08:00 ERROR VPN settings: provider settings: server selection: the country specified is not valid: one or more values is set but there is no possible value available
2022-04-11T09:46:00+08:00 INFO [storage] merging by most recent 11195 hardcoded servers and 11195 servers read from /gluetun/servers.json
2022-04-11T09:46:00+08:00 INFO Shutdown successful
```

### Share your configuration

```yml
purevpn:
        image: qmcgaw/gluetun
        container_name: purevpn
        cap_add:
          - NET_ADMIN
        ports:
          #  ------begin configure app ports that use vpn here
          - 6881:6881/tcp # qbittorrent
          - 6881:6881/udp # qbittorrent
          - 9091:9091/tcp # qbittorrent
          # -------end application ports ^^^^^^^^^^^^^^^^
        volumes:
          - C:\Docker2\docker\purevpn:/gluetun
        environment:
          # More variables are available, see the Wiki table
          - OPENVPN_VERBOSITY=6
          - DOT_VERBOSITY=5
          - DOT_VERBOSITY_DETAILS=4
          - OPENVPN_USER=username
          - OPENVPN_PASSWORD=pass
          # P2P friendly Purevpn server locations
          - SERVER_COUNTRIES=Netherlands,Russian Federation,Germany,Norway
```
