### ISSUE TITLE
Bug: Generic Error with custom VPN provider

### ISSUE THREAD

**Issue by npawelek** [qdm12/gluetun#952]
### Is this urgent?

No

### Host OS

Ubuntu 20.04 (5.10+ kernel)

### CPU arch

x86_64

### VPN service provider

Custom

### What are you using to run the container

Kubernetes

### What is the version of Gluetun

v3.28.2

### What's the problem 🤔

With ProtonVPN finally adding Wireguard config support, I took a stab at testing it over the weekend without much luck. I bumped to the latest version of gluntun `v3.28.2` and set the specific variables I believed were required. After attempting to start, I receive a very generic error (last two octets of the address were removed).

```
2022/04/15 19:25:44 ERROR reading from environment variables: VPN provider: server selection: environment variable VPN_ENDPOINT_IP: invalid IP address: 89.187.XXX.XXX
2022/04/15 19:25:44 INFO Shutdown successful
```

Here's the associated environment variables I have defined for the container:

```
    Environment:
      VPN_SERVICE_PROVIDER:       custom
      VPN_TYPE:                   wireguard
      VPN_ENDPOINT_IP:            <set to the key 'VPN_ENDPOINT_IP' in secret 'secondary-conf13'>        Optional: false
      VPN_ENDPOINT_PORT:          <set to the key 'VPN_ENDPOINT_PORT' in secret 'secondary-conf13'>      Optional: false
      WIREGUARD_PUBLIC_KEY:       <set to the key 'WIREGUARD_PUBLIC_KEY' in secret 'secondary-conf13'>   Optional: false
      WIREGUARD_PRIVATE_KEY:      <set to the key 'WIREGUARD_PRIVATE_KEY' in secret 'secondary-conf13'>  Optional: false
      WIREGUARD_ADDRESSES:        <set to the key 'WIREGUARD_ADDRESSES' in secret 'secondary-conf13'>    Optional: false
      FIREWALL_OUTBOUND_SUBNETS:  10.96.0.0/12
      DOT:                        off
      DNS_KEEP_NAMESERVER:        off
      DNS_ADDRESS:                10.96.0.10
      BLOCK_MALICIOUS:            off
      PORT_FORWARDING:            off
      HTTPPROXY:                  on
      HTTPPROXY_PORT:             8888
      HTTPPROXY_STEALTH:          on
      HTTPPROXY_LOG:              on
      SHADOWSOCKS:                off
      TZ:                         America/Chicago
```

This is how I transposed them from my generated wireguard config. Is there anything wrong here?

```
[Interface]
PrivateKey = *****
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
PublicKey = jqu/dcZfEtoee0IN1H4ZFnnR8p4sZ7juna+eUndhRgs=
AllowedIPs = 0.0.0.0/0
Endpoint = 89.187.XXX.XXX:51820
```

`VPN_ENDPOINT_IP` --> `89.187.XXX.XXX`
`VPN_ENDPOINT_PORT` --> `51820`
`WIREGUARD_PUBLIC_KEY` --> `jqu/dcZfEtoee0IN1H4ZFnnR8p4sZ7juna+eUndhRgs=` (Does this need to be run through base64 first?)
`WIREGUARD_PRIVATE_KEY` --> used verbatim private key from config (Does this need to be run through base64 first?)
`WIREGUARD_ADDRESSES` --> `10.2.0.2/32`

Hopefully this is just an issue transposing the config. Thanks again!

### Share your logs

```log
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================

Running version v3.28.2 built on 2022-03-31T22:15:18.183Z (commit c04cd62)

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2022/04/15 19:25:44 ERROR reading from environment variables: VPN provider: server selection: environment variable VPN_ENDPOINT_IP: invalid IP address: 89.187.XXX.XXX
2022/04/15 19:25:44 INFO Shutdown successful
```

### Share your configuration

```yml
additionalContainers:
      vpn:
        name: vpn
        image: qmcgaw/gluetun:v3.28.2
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        env:
        - name: VPN_SERVICE_PROVIDER
          value: custom
        - name: VPN_TYPE
          value: wireguard
        - name: VPN_ENDPOINT_IP
          valueFrom:
            secretKeyRef:
              name: secondary-conf13
              key: VPN_ENDPOINT_IP
        - name: VPN_ENDPOINT_PORT
          valueFrom:
            secretKeyRef:
              name: secondary-conf13
              key: VPN_ENDPOINT_PORT
        - name: WIREGUARD_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: secondary-conf13
              key: WIREGUARD_PUBLIC_KEY
        - name: WIREGUARD_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: secondary-conf13
              key: WIREGUARD_PRIVATE_KEY
        - name: WIREGUARD_ADDRESSES
          valueFrom:
            secretKeyRef:
              name: secondary-conf13
              key: WIREGUARD_ADDRESSES
        - name: FIREWALL_OUTBOUND_SUBNETS
          value: "10.96.0.0/12"
        - name: DOT
          value: "off"
        - name: DNS_KEEP_NAMESERVER
          value: "off"
        - name: DNS_ADDRESS
          value: "10.96.0.10"
        - name: BLOCK_MALICIOUS
          value: "off"
        - name: PORT_FORWARDING
          value: "off"
        - name: HTTPPROXY
          value: "on"
        - name: HTTPPROXY_PORT
          value: "8888"
        - name: HTTPPROXY_STEALTH
          value: "on"
        - name: HTTPPROXY_LOG
          value: "on"
        - name: SHADOWSOCKS
          value: "off"
        - name: TZ
          value: ${TIMEZONE}
        ports:
        - containerPort: 8888
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - "ping"
            - "-W3"
            - "-c1"
            - "-q"
            - "-s8"
            - "1.1.1.1"
          initialDelaySeconds: 20
          failureThreshold: 3
          successThreshold: 1
          periodSeconds: 20
          timeoutSeconds: 5
```
