### ISSUE TITLE
Bug: PrivateVPN no connection to pick from

### ISSUE THREAD

**Issue by short-circuit** [qdm12/gluetun#959]
### Is this urgent?

Yes

### Host OS

Ubuntu server 22.04

### CPU arch

x86_64

### VPN service provider

PrivateVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-04-21T13:12:58.163Z (commit 0c0f166)

### What's the problem 🤔

Gluetun fails to start. It seems it cannot find the connection for the VPN.
Does not work in either case if the Country is specified or not.

Worked before latest pull without updating servers.json.

It looks like servers.json entries for PrivateVPN have no IPs assigned to them since commit aa72951. (IP Server model streamlining)

### Share your logs

```log
gluetun-se    | ========================================
gluetun-se    | ========================================
gluetun-se    | =============== gluetun ================
gluetun-se    | ========================================
gluetun-se    | =========== Made with ❤️ by ============
gluetun-se    | ======= https://github.com/qdm12 =======
gluetun-se    | ========================================
gluetun-se    | ========================================
gluetun-se    | 
gluetun-se    | Running version latest built on 2022-04-21T13:12:58.163Z (commit 0c0f166)
gluetun-se    | 
gluetun-se    | 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
gluetun-se    | 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
gluetun-se    | ✨ New feature? https://github.com/qdm12/gluetun/issues/new
gluetun-se    | ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
gluetun-se    | 💻 Email? quentin.mcgaw@gmail.com
gluetun-se    | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
gluetun-se    | 2022-04-22T11:39:31+02:00 INFO [routing] default route found: interface eth0, gateway 172.17.0.1 and assigned IP 172.17.0.4
gluetun-se    | 2022-04-22T11:39:31+02:00 INFO [routing] local ethernet link found: eth0
gluetun-se    | 2022-04-22T11:39:31+02:00 INFO [routing] local ipnet found: 172.17.0.0/16
gluetun-se    | 2022-04-22T11:39:31+02:00 INFO [firewall] enabling...
gluetun-se    | 2022-04-22T11:39:31+02:00 INFO [firewall] enabled successfully
gluetun-se    | 2022-04-22T11:39:32+02:00 INFO [storage] merging by most recent 11382 hardcoded servers and 11382 servers read from /gluetun/servers.json
gluetun-se    | 2022-04-22T11:39:32+02:00 INFO Alpine version: 3.15.4
gluetun-se    | 2022-04-22T11:39:33+02:00 INFO OpenVPN 2.4 version: 2.4.12
gluetun-se    | 2022-04-22T11:39:33+02:00 INFO OpenVPN 2.5 version: 2.5.6
gluetun-se    | 2022-04-22T11:39:33+02:00 INFO Unbound version: 1.13.2
gluetun-se    | 2022-04-22T11:39:33+02:00 INFO IPtables version: v1.8.7
gluetun-se    | 2022-04-22T11:39:33+02:00 INFO Settings summary:
gluetun-se    | ├── VPN settings:
gluetun-se    | |   ├── VPN provider settings:
gluetun-se    | |   |   ├── Name: privatevpn
gluetun-se    | |   |   └── Server selection settings:
gluetun-se    | |   |       ├── VPN type: openvpn
gluetun-se    | |   |       └── OpenVPN server selection settings:
gluetun-se    | |   |           └── Protocol: UDP
gluetun-se    | |   └── OpenVPN settings:
gluetun-se    | |       ├── OpenVPN version: 2.5
gluetun-se    | |       ├── User: [set]
gluetun-se    | |       ├── Password: [set]
gluetun-se    | |       ├── Tunnel IPv6: no
gluetun-se    | |       ├── Network interface: tun0
gluetun-se    | |       ├── Run OpenVPN as: root
gluetun-se    | |       └── Verbosity level: 1
gluetun-se    | ├── DNS settings:
gluetun-se    | |   ├── DNS server address to use: 127.0.0.1
gluetun-se    | |   ├── Keep existing nameserver(s): no
gluetun-se    | |   └── DNS over TLS settings:
gluetun-se    | |       ├── Enabled: yes
gluetun-se    | |       ├── Update period: every 24h0m0s
gluetun-se    | |       ├── Unbound settings:
gluetun-se    | |       |   ├── Authoritative servers:
gluetun-se    | |       |   |   └── cloudflare
gluetun-se    | |       |   ├── Caching: yes
gluetun-se    | |       |   ├── IPv6: no
gluetun-se    | |       |   ├── Verbosity level: 1
gluetun-se    | |       |   ├── Verbosity details level: 0
gluetun-se    | |       |   ├── Validation log level: 0
gluetun-se    | |       |   ├── System user: root
gluetun-se    | |       |   └── Allowed networks:
gluetun-se    | |       |       ├── 0.0.0.0/0
gluetun-se    | |       |       └── ::/0
gluetun-se    | |       └── DNS filtering settings:
gluetun-se    | |           ├── Block malicious: yes
gluetun-se    | |           ├── Block ads: no
gluetun-se    | |           ├── Block surveillance: yes
gluetun-se    | |           └── Blocked IP networks:
gluetun-se    | |               ├── 127.0.0.1/8
gluetun-se    | |               ├── 10.0.0.0/8
gluetun-se    | |               ├── 172.16.0.0/12
gluetun-se    | |               ├── 192.168.0.0/16
gluetun-se    | |               ├── 169.254.0.0/16
gluetun-se    | |               ├── ::1/128
gluetun-se    | |               ├── fc00::/7
gluetun-se    | |               ├── fe80::/10
gluetun-se    | |               ├── ::ffff:7f00:1/104
gluetun-se    | |               ├── ::ffff:a00:0/104
gluetun-se    | |               ├── ::ffff:a9fe:0/112
gluetun-se    | |               ├── ::ffff:ac10:0/108
gluetun-se    | |               └── ::ffff:c0a8:0/112
gluetun-se    | ├── Firewall settings:
gluetun-se    | |   ├── Enabled: yes
gluetun-se    | |   ├── VPN input ports:
gluetun-se    | |   |   └── 55555
gluetun-se    | |   └── Outbound subnets:
gluetun-se    | |       └── {192.168.0.1 ffffffff}
gluetun-se    | ├── Log settings:
gluetun-se    | |   └── Log level: INFO
gluetun-se    | ├── Health settings:
gluetun-se    | |   ├── Server listening address: 127.0.0.1:9999
gluetun-se    | |   ├── Target address: cloudflare.com:443
gluetun-se    | |   └── VPN wait durations:
gluetun-se    | |       ├── Initial duration: 5s
gluetun-se    | |       └── Additional duration: 5s
gluetun-se    | ├── Shadowsocks server settings:
gluetun-se    | |   └── Enabled: no
gluetun-se    | ├── HTTP proxy settings:
gluetun-se    | |   ├── Enabled: yes
gluetun-se    | |   ├── Listening address: 0.0.0.0:8890
gluetun-se    | |   ├── User: proxy
gluetun-se    | |   ├── Password: [set]
gluetun-se    | |   ├── Stealth mode: yes
gluetun-se    | |   └── Log: yes
gluetun-se    | ├── Control server settings:
gluetun-se    | |   ├── Listening address: :8000
gluetun-se    | |   └── Logging: yes
gluetun-se    | ├── OS Alpine settings:
gluetun-se    | |   ├── Process UID: 1000
gluetun-se    | |   ├── Process GID: 1000
gluetun-se    | |   └── Timezone: Europe/Zurich
gluetun-se    | ├── Public IP settings:
gluetun-se    | |   ├── Fetching: every 12h0m0s
gluetun-se    | |   └── IP file path: /tmp/gluetun/ip
gluetun-se    | └── Version settings:
gluetun-se    |     └── Enabled: yes
gluetun-se    | 2022-04-22T11:39:33+02:00 INFO [routing] default route found: interface eth0, gateway 172.17.0.1 and assigned IP 172.17.0.4
gluetun-se    | 2022-04-22T11:39:33+02:00 INFO [routing] adding route for 0.0.0.0/0
gluetun-se    | 2022-04-22T11:39:33+02:00 INFO [firewall] setting allowed subnets...
gluetun-se    | 2022-04-22T11:39:33+02:00 INFO [routing] default route found: interface eth0, gateway 172.17.0.1 and assigned IP 172.17.0.4
gluetun-se    | 2022-04-22T11:39:33+02:00 INFO [routing] adding route for 192.168.0.1/32
gluetun-se    | 2022-04-22T11:39:33+02:00 INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
gluetun-se    | 2022-04-22T11:39:33+02:00 INFO [pprof] http server listening on [::]:6060
gluetun-se    | 2022-04-22T11:39:33+02:00 INFO [http server] http server listening on [::]:8000
gluetun-se    | 2022-04-22T11:39:33+02:00 INFO [healthcheck] listening on 127.0.0.1:9999
gluetun-se    | 2022-04-22T11:39:33+02:00 INFO [dns over tls] using plaintext DNS at address 1.1.1.1
gluetun-se    | 2022-04-22T11:39:33+02:00 INFO [http proxy] listening on 0.0.0.0:8890
gluetun-se    | 2022-04-22T11:39:33+02:00 ERROR [vpn] failed finding a valid server connection: no connection to pick from
gluetun-se    | 2022-04-22T11:39:33+02:00 INFO [vpn] retrying in 15s
gluetun-se    | 2022-04-22T11:39:38+02:00 INFO [healthcheck] program has been unhealthy for 5s: restarting VPN
gluetun-se    | 2022-04-22T11:39:48+02:00 ERROR [vpn] failed finding a valid server connection: no connection to pick from
gluetun-se    | 2022-04-22T11:39:48+02:00 INFO [vpn] retrying in 30s
gluetun-se    | 2022-04-22T11:40:18+02:00 ERROR [vpn] failed finding a valid server connection: no connection to pick from
gluetun-se    | 2022-04-22T11:40:18+02:00 INFO [vpn] retrying in 1m0s
gluetun-se    | 2022-04-22T11:41:18+02:00 ERROR [vpn] failed finding a valid server connection: no connection to pick from
gluetun-se    | 2022-04-22T11:41:18+02:00 INFO [vpn] retrying in 2m0s
gluetun-se    | 2022-04-22T11:43:18+02:00 ERROR [vpn] failed finding a valid server connection: no connection to pick from
gluetun-se    | 2022-04-22T11:43:18+02:00 INFO [vpn] retrying in 4m0s
```

### Share your configuration

```yml
gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8890:8890/tcp # HTTP proxy
      - 8390:8388/tcp # Shadowsocks
      - 8390:8388/udp # Shadowsocks
      # - 8002:8000/tcp # Built-in HTTP control server
    # command:
    volumes:
      - ./gluetun:/gluetun
    environment:
      # More variables are available, see the readme table
      OPENVPN_USER: abc
      OPENVPN_PASSWORD: abc
      VPN_SERVICE_PROVIDER: privatevpn
      SERVER_COUNTRIES: Sweden
      SERVER_CITIES: Stockholm
      TZ: Europe/Berlin
      FIREWALL_OUTBOUND_SUBNETS: 192.168.0.1/32
      FIREWALL_VPN_INPUT_PORTS: 55555
      SHADOWSOCKS: 'on'
      SHADOWSOCKS_LOG: 'on'
      SHADOWSOCKS_USER: 'abc'
      SHADOWSOCKS_PASSWORD: 'abc'
      HTTPPROXY: 'on'
      HTTPPROXY_LOG: 'on'
      HTTPPROXY_LISTENING_ADDRESS: 0.0.0.0:8890
      HTTPPROXY_USER: 'abc'
      HTTPPROXY_PASSWORD: 'abc'
      HTTPPROXY_STEALTH: 'on'
      BLOCK_SURVEILLANCE: 'on'
      UPDATE_PERIOD: 24h
    restart: unless-stopped
```
