### ISSUE TITLE
Bug: Setting HEALTH_VPN_DURATION_ADDITION changes HEALTH_VPN_DURATION_INITIAL

### ISSUE THREAD

**Issue by Raph521** [qdm12/gluetun#960]
### Is this urgent?

No

### Host OS

Debian Bullseye

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version v3.28.2 built on 2022-03-31T22:15:18.183Z (commit c04cd62)

### What's the problem 🤔

I just noticed that setting HEALTH_VPN_DURATION_ADDITION actually changed the setting for HEALTH_VPN_DURATION_INITIAL.

I think it's because health.VPN.Initial (instead of health.VPN.Addition) is being set with the value of HEALTH_VPN_DURATION_ADDITION:

### internal/healthcheck/openvpn.go
```
func (r *Reader) ReadHealth() (health settings.Health, err error) {
    health.ServerAddress = os.Getenv("HEALTH_SERVER_ADDRESS")
    _, health.TargetAddress = r.getEnvWithRetro("HEALTH_TARGET_ADDRESS", "HEALTH_ADDRESS_TO_PING")

    health.VPN.Initial, err = r.readDurationWithRetro(
        "HEALTH_VPN_DURATION_INITIAL",
        "HEALTH_OPENVPN_DURATION_INITIAL")
    if err != nil {
        return health, err
    }

    health.VPN.Initial, err = r.readDurationWithRetro(
        "HEALTH_VPN_DURATION_ADDITION",
        "HEALTH_OPENVPN_DURATION_ADDITION")
    if err != nil {
        return health, err
    }

    return health, nil
}
```

### Share your logs

```log
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Target address: github.com:443
|   └── VPN wait durations:
|       ├── Initial duration: 30s
|       └── Additional duration: 5s
```

### Share your configuration

```yml
gluetun:
        container_name: gluetun
        image: qmcgaw/gluetun:v3
        cap_add:
            - NET_ADMIN
        volumes:
            - /mnt/disk1/config/gluetun/main:/gluetun
            - /mnt/disk1/config/gluetun/ip_port:/tmp/gluetun
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - OPENVPN_PROTOCOL=udp
            - VPN_SERVICE_PROVIDER=private internet access
            - SERVER_REGIONS=CA Toronto
            - PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING=on
            - PRIVATE_INTERNET_ACCESS_OPENVPN_ENCRYPTION_PRESET=normal
            - OPENVPN_USER=XXXX
            - OPENVPN_PASSWORD=YYYY
            - UPDATE_PERIOD=24h
            - HEALTH_VPN_DURATION_ADDITION=30s
```
