### ISSUE TITLE
http server curl public ip?

### ISSUE THREAD

**Issue by BoW2EviL** [qdm12/gluetun#989]
maybe its just me but i pulled the new docker image this morning and 
could not curl the public ip address.

specs:
rpi4, 8gb ram, 128gb sd running raspibian bullseye x64
Docker version 20.10.16, build aa7e414

Portion of docker-compose.yml

```yml
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:dev/net/tun
    networks:
      piratenet:
        ipv4_address: redacted
    ports:
     #PORT_FORWARDING blah blah
      - redacted
      - "8000:8000"     # gluetun api
    volumes:
      - /srv/configs/pirate/gluetun/config:/gluetun
      - /srv/configs/pirate/gluetun/foward:/tmp/forwarded_port_dir
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - VPN_TYPE=openvpn
      - PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING=on
      - PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING_STATUS_FILE=redacted
      - TZ=America/New_York
      - OPENVPN_USER=redacted
      - OPENVPN_PASSWORD=redacted
      - "SERVER_REGIONS=CA Toronto,CA Vancouver"
      # - REGION=Mexico
```

what i did to find issue:
after doing a PULL to get the current version of gluetun i noticed a script i was running was always returning a blank ip ie:{public_ip:""}. i figured it might be the token or the forward files so i deleted them and tried a fresh start with DOWN the UP. while watching the logs i didn't notice anything a miss. the log even contained the valid ip issued but it still didn't return a public ip from the http server(port 8000) ie:"curl -s localhost:8000/v1/publicip/ip". after several attempts i gave up.

to fix my issue:
 i changed docker-compose.yml to...

```yml
services:
  gluetun:
    image: qmcgaw/gluetun:v3.28.2   
    container_name: gluetun
```
after a docker PULL, DOWN, then UP everything went back to normal.

it could just be me. but i figured i should report it.

Thx so much for gluetun it has been a wonderful experience
