### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by seanmcbroom** [qdm12/gluetun#993]
### Is this urgent?

Yes

### Host OS

DSM 7.0.1 (Synology)

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-5-7 (commit e32d251)

### What's the problem 🤔

Forgive me if I'm doing something wrong, I am a beginner to networking especially in docker. My problem is that any container connected to the gluetun network is not accessible by other containers. Inspecting the container on docker just shows empty network settings theres no IP address for these containers, making it impossible to index inside or outside of the network.

### Share your logs

```log
Network Settings on Gluetun
"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {}
        }
```

### Share your configuration

```yml
version: '3'

networks:
  web:
    name: web
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24

services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:v3.29.0
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    networks:
      - web
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 9080:9080 # qBittorrent Web UI
      - 6881:6881/tcp # qBittorrent
      - 6881:6881/udp # qBittorrent
      - 8080:8080/tcp # qBittorrent
    volumes:
      - /volume1/docker/gluetun:/gluetun:rw
    environment:
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - VPNSP=protonvpn
      - VPN_TYPE=openvpn
      - PUID=1026
      - PGID=100
      - TZ=CST
      - FIREWALL_OUTBOUND_SUBNETS=192.168.2.0/24
    restart: always

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1026
      - PGID=100
      - TZ=CST
      - UMASK=022
      - WEBUI_PORT=9080
    volumes:
      - /volume1/docker/qbittorrent/config:/config:rw
      - /volume1/Torrents:/Torrents:rw
    restart: unless-stopped

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    networks:
      - web
    environment:
      - PUID=1026
      - PGID=100
      - AUTO_UPDATE=true
    volumes:
      - /volume1/docker/jackett/config:/config:rw
      - /volume1/Torrents:/Torrents:rw
    restart: unless-stopped
    ports:
      - 9117:9117


  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    networks:
      - web
    environment:
      - PUID=1026
      - PGID=100
    volumes:
      - /volume1/docker/radarr/config:/config:rw
      - /volume1/Plex/Library/Movies:/Movies:rw
      - /volume1/Torrents:/Torrents:rw
    depends_on:
      - gluetun
    restart: unless-stopped
    ports:
      - 7878:7878

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    networks:
      - web
    environment:
      - PUID=1026
      - PGID=100
      - AUTO_UPDATE=true
    volumes:
      - /volume1/docker/sonarr/config:/config:rw
      - /volume1/Plex/Library/TV Shows:/TV Shows:rw
      - /volume1/Plex/Library/Anime:/Anime:rw
      - /volume1/Torrents:/Torrents
    restart: unless-stopped
    ports:
      - 8989:8989
```
